### ISSUE TITLE
UI corrupted text (accents). UTF8 support missing.

### ISSUE THREAD

**Issue by Mangoes** [CollaboraOnline/online#10014]
### Describe the Bug
In French, the accented characters are replaced with corrupt text. It looks exactly like the problem Linux had ~ 10+ years ago when it was missing UTF8 support.

This only happens in the UI (writing is fine).

Example:
Caractère -> caractÃ"re
défaut -> dÃ©faut

### Steps to Reproduce
1. Click on the characters edit icon.
2. Look at the accented words
3. See the corrupted words

### Expected Behavior
Display the accented characters correctly in the UI.

### Actual Behavior
The accented characters in the UI are corrupted. (Missing UTF8 support).

### Screenshots
![Screenshot_20240909-151012](https://github.com/user-attachments/assets/fc087a24-fcae-46f5-975c-93e65ba4646f)
![Screenshot_20240909-150926](https://github.com/user-attachments/assets/45825c69-2056-4604-8d6b-b52bb32e9976)

### Smartphone
 - Pixel 8 pro
 - Android 14
 - Collabora 24.04.6.2 fdroid.

**Comment by Minion3665** [comment]
Heya!

> It looks exactly like the problem Linux had ~ 10+ years ago when it was missing UTF8 support.

Yep, that's pretty much what happened - we encoded into base64 for transport, and then used JavaScript's base64 decode functions to decode ... which don't support UTF8.

---

It should be fixed in #10016, and I'll build an Android snapshot afterwards so you can check it over :)

Thanks very much for your report!

**Comment by Mangoes** [comment]
> It should be fixed in #10016, and I'll build an Android snapshot afterwards so you can check it over :)
>

Yes, the latest snapshot (2024-09-10) fixes the problem.

Please push this to the stable fdroid repo (if you can).

Thanks!

**Comment by Minion3665** [comment]
> > It should be fixed in #10016, and I'll build an Android snapshot afterwards so you can check it over :)
> 
> Yes, the latest snapshot (2024-09-10) fixes the problem.

Awesome, I'm glad to hear it!

> Please push this to the stable fdroid repo (if you can).

I can't immediately do that, but it should be in our next Android release, which we expect to be in early October. We're trying to do a bit of a quicker cadence on these things to make sure that fixes get out to you faster...
