### ISSUE TITLE
Helm Chart: allow configuring WOPI proof keys

### ISSUE THREAD

**Issue by wkloucek** [CollaboraOnline/online#10020]
### Is your feature request related to a problem?

I would like to configure WOPI proof keys when deploying Collabora with the Helm Chart maintained in this repository.

### Describe the solution you'd like

Probably it makes sense to have the proof key in a secret, so that it can be mounted in all Collabora pods

### Describe alternatives you've considered

Generate the proof key during runtime and store it in a RWX volume. But this should be avoided since makes Collabora require RWX storage now (which it doesn't have right now).

### Additional context

This is what I came across when reading about Collabora and WOPI proof keys: https://www.collaboraonline.com/blog/how-to-wopi-binding-for-collabora-online-in-sharepoint-2016-server/

**Comment by wkloucek** [comment]
I'd also be willing to contribute code when we agree that adding a ConfigMap is the right way.

**Comment by Darshan-upadhyay1110** [comment]
Hello @wkloucek 

> I'd also be willing to contribute code when we agree that adding a ConfigMap is the right way.

Sure

**Comment by Rash419** [comment]
> Describe the solution you'd like
> 
> Probably it makes sense to have the proof key in a secret, so that it can be mounted in all Collabora pods

@wkloucek looks like a great idea. Go ahead! Let me know if you need any help. Thanks
