### ISSUE TITLE
`coolwsd.xml` defaults do not match built-in defaults

### ISSUE THREAD

**Issue by xzfc** [CollaboraOnline/online#10049]
### Describe the Bug

[The comment in `COOLWSD.cpp`](https://github.com/CollaboraOnline/online/blob/cp-24.04.7-2/wsd/COOLWSD.cpp#L2036-L2043) states that defaults from `coolwsd.xml` and built-in defaults from the `coolwsd` C++ sources should be the same. However, they are not. Consequently, when `coolwsd` is started with an empty `coolwsd.xml`, the factual configuration would not be the same as if it was started with the default `coolwsd.xml`. 

This cause problems for systems that generate the `coolwsd.xml` config file on its own (e.g. Nix). We can't generate `coolwsd.xml` from scratch with just a few user-specified options, we have to patch the default `coolwsd.xml` instead. This is inconvenient.

Incomplete list of mismatched options:

| Option                               | `coolwsd.xml`                  | built-in                                                              |
| ------------------------------------ | ------------------------------ | --------------------------------------------------------------------- |
| `logging.level`                      | `@COOLWSD_LOGLEVEL@`/`warning` | `trace`                                                               |
| `num_prespawn_children`              | `4`                            | `1`                                                                   |
| `per_document.cleanup[@enable]`      | `true`                         | `false`                                                               |
| `per_view.out_of_focus_timeout_secs` | `300`                          | `120` or `60`                                                         |
| `ssl.termination`                    | `false`                        | `true`                                                                |
| `ssl.cert_file_path`                 | `/etc/coolwsd/cert.pem`        | `COOLWSD_CONFIGDIR "/cert.pem"`/<br>`/usr/local/etc/coolwsd/cert.pem` |
| `storage.ssl.as_scheme`              | `true`                         | `false`                                                               |
| And others                           |                                |                                                                       |

### Steps to Reproduce

1. Create `empty.xml` with this contents: `<config></config>`.
2. First run: run `coolwsd` with the default `coolwsd.xml`.
3. Second run: run `coolwsd --config-file=empty.xml`.

### Expected Behavior

Both runs should behave exactly the same.

### Actual Behavior

They are not. Presumably, the most visible difference is the logging level (see the table above) and paths to SSL certs.

**Comment by timar** [comment]
wrt. `storage.ssl.as_scheme` there is a comment why it is so: [wsd/wopi/StorageConnectionManager.cpp#L163](https://github.com/CollaboraOnline/online/blob/0c5c35eff44d569008f0da98f18116a532757d0b/wsd/wopi/StorageConnectionManager.cpp#L163)
