### ISSUE TITLE
Formula bar: replace everything after '=' sign with the item selected in formula popup

### ISSUE THREAD

**Issue by bayramcicek** [CollaboraOnline/online#10040]
### Steps to Reproduce
1. Type `=s` in the formula bar
2. Click on e.g. `SUM` on the popup
3. You will see the cell filled with `=sSUM(` instead of `=SUM(`

### Expected Behavior
when clicking one of the popup items, it should replace everything after `=` sign with the item selected

### Actual Behavior
it appends the selected item after whatever you typed with `=` sign

### Screenshots

https://github.com/user-attachments/assets/b825e778-88fb-40b9-bd7f-b021fc1d14f1

### Desktop
COOLWSD version: 24.04.7.2(git hash: e2ed2f59)
LOKit version: Collabora Office 24.04.7.2(git hash: 8c74383)
Served by: Manjaro Linux
Server ID: 699ede2e

**Comment by jazevedo-coll** [comment]
Also present in: 

COOLWSD version: 24.04.6.1 (git hash: 8ec5fda (E))
LOKit version: Collabora Office 24.04.6.1 (git hash: cd7968a)
Served by: Debian GNU/Linux 12 (bookworm)
Server ID: 0a44b267

Just to be clear the formula continues to work. 

And if you type the full word, then this issue does not happen.

[Screencast from 2024-09-12 17-15-43.webm](https://github.com/user-attachments/assets/9e6471e5-7cfd-4451-b8ca-7388154949d7)

**Comment by bayramcicek** [comment]
> Just to be clear the formula continues to work.
> 
> And if you type the full word, then this issue does not happen.

Yes. If you type & select while you are in the cell itself, it is working. 


But, if you type on the `formula bar` then select the formula in the popup then select cells to calculate -> it goes wrong, does not work. e.g:

https://github.com/user-attachments/assets/40117330-35bc-44c7-9f9f-eefe8ac6cbf8

Thanks.

**Comment by Rash419** [comment]
should be fixed in https://gerrit.libreoffice.org/c/core/+/173333

**Comment by Rash419** [comment]
@bayramcicek @jazevedo-coll the patch has been merged, can you test again and close this issue ?

**Comment by bayramcicek** [comment]
> @bayramcicek @jazevedo-coll the patch has been merged, can you test again and close this issue ?

Thanks for the fix, works well on my side with the last build.

https://github.com/user-attachments/assets/a3ecc4b7-2ed0-44be-943f-afc4ce892a51

### An unrelated issue
clicking inside the formula bar sometimes does not show the cursor inside / maybe a focus problem? Is it expected or ....?


https://github.com/user-attachments/assets/ec8b9484-3447-44ec-82ef-726c4e9b71fe

**Comment by bayramcicek** [comment]
@jazevedo-coll : if the fix also works on your side you can close the issue. Thank you.

**Comment by jazevedo-coll** [comment]
@bayramcicek @Rash419 it worked for me. Closing.
