### ISSUE TITLE
Mention issues: PostMessage is only sent once. Keyboard doesn't work

### ISSUE THREAD

**Issue by juliusknorr** [CollaboraOnline/online#10047]
### Describe the Bug

While working on emitting notifications for [user mentions](https://github.com/nextcloud/richdocuments/pull/3960) in the Nextcloud integration I noticed a couple of issues around mentions that are related to the Collabora side of the implementation.

It would be great to address those to make the mentions feature more flawless.

### Steps to Reproduce

1. Use the Nextcloud integration with Collabora
2. Type `@` to insert a mention
3. Start typing and search for a user

- [ ] Currently the search is only triggered once on the first character press `@a`. This is especially a problem for large instances with lots of users where the first result set would not contain all of the users. Instead there should be a debounced fetching of users while typing. You also see that only one postmessage is sent to Nextcloud.
- [ ] Clicking is required to insert a mention, having one match an pressing enter does not work

### Additional Context

Latest master branch of online

**Comment by timur-g** [comment]
#7923 seems related where double @@mention may work.

**Comment by Rash419** [comment]
https://github.com/Rash419/online/commits/debounce-mention-user-query/ I will create a PR once https://github.com/CollaboraOnline/online/pull/10145 is merged : )
