### ISSUE TITLE
iOS app: Font selection button has no label when text with multiple fonts is selected

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#1005]
**Describe the bug**
In writer on iOS the button that calls the font selection dialog has no label (or no text on the label) when a user selects text that is formated with more than one font family.

**To Reproduce**
1. Write some text in a writer document using the iOS app
2. Format one word with e.g. "Arial" and one other word with e.g. "Liberation Sans"
3. Select the paragraph that contains the two individually styled words
4. Check what the font selection button looks like

**Expected behavior**
The button to open the font selection dialog should show something like "Multiple Fonts" or just "Select Font"

**Actual behavior**
The button to open the font selection dialog is tiny and has no visible text on it

**Screenshots**
![no_text_font_selection_button](https://user-images.githubusercontent.com/1211300/102318937-6b148900-3f7a-11eb-8202-c371fbc113f9.png)

**Tablet**
 - OS: iOS 14.2
 - Version: 6.4.2 (2)

**Comment by tml1024** [comment]
Fixed this right away as I guessed (correctly) that it would be trivial to fix. Which is nice for a change...
