### ISSUE TITLE
perf: improve ScFlatUInt16RowSegments::dumpAsString()

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#10060]
Performance of this method is not that ideal:

![image](https://github.com/user-attachments/assets/7fa71d37-85cc-4d21-b5fd-ae8c5d68a024)

We repeatedly allocate and free strings it seems. We should instead use an OStringBuffer from rtl/strbuf.hxx and preferably guestimate it's size to pre-allocate that too once before appending numbers to it - which can be converted in-line directly into the data structure.

Then convertToOStringAndClear at the end =)

Every 1.5% matters I think - if it's easy to nail.

For bonus points, there are two other dumpAsString methods in this file:

core/sc/source/core/data/segmenttree.cxx

That could be similarly easily optimized :-) @Darshan-upadhyay1110 I assume you can mentor this too :-)

**Comment by Darshan-upadhyay1110** [comment]
> That could be similarly easily optimized :-) @Darshan-upadhyay1110 I assume you can mentor this too :-)

Sure :)

**Comment by sopyb** [comment]
I would like to work on this issue and try to make a patch for it. Could you please assign the issue to me?

**Comment by sopyb** [comment]
I have submitted a patch on [gerrit](https://gerrit.libreoffice.org/c/core/+/174142) and I am awaiting review.

**Comment by Darshan-upadhyay1110** [comment]
@sopyb Thanks for the patch :)

**Comment by mmeeks** [comment]
Ooh - thanks =) nice work.

**Comment by mmeeks** [comment]
@sopyb merged - are you interested in other easy-ish performance things ?

I think looking at https://github.com/CollaboraOnline/online/issues/8159 there might be some more low hanging fruit if you're interested =)

**Comment by sopyb** [comment]
> @sopyb merged - are you interested in other easy-ish performance things ?
> 
> I think looking at https://github.com/CollaboraOnline/online/issues/8159 there might be some more low hanging fruit if you're interested =)

I'll be looking into it Thursday, thanks for the heads-up

**Comment by Darshan-upadhyay1110** [comment]
> > @sopyb merged - are you interested in other easy-ish performance things ?
> > I think looking at #8159 there might be some more low hanging fruit if you're interested =)
> 
> I'll be looking into it Thursday, thanks for the heads-up

Hello @sopyb how are you :)

I think you were working on https://github.com/CollaboraOnline/online/issues/8159 . How are things going on here , any joy ? 
CC: @grandinj

**Comment by sopyb** [comment]
> > > @sopyb merged - are you interested in other easy-ish performance things ?
> > > I think looking at #8159 there might be some more low hanging fruit if you're interested =)
> > 
> > I'll be looking into it Thursday, thanks for the heads-up
> 
> Hello @sopyb how are you :)
> 
> I think you were working on https://github.com/CollaboraOnline/online/issues/8159 . How are things going on here , any joy ? 
> CC: @grandinj 

Thanks for checking in. I started university on September 30th, which has been keeping me pretty busy. I'm still adapting to the new schedule and figuring out how to balance everything. I haven't had a chance to look into this issue yet, but I'm working on finding time for it. I'll send an update in here once I've made some progress. 

Currently, it would be a great help for when I get around to working on it if you could provide a link to documentation or provide pointers on how to view the frame-graph to properly check my work.

**Comment by Darshan-upadhyay1110** [comment]
hii @sopyb Great to hear from you! I hope university is going well. 

Also, we’re in Hacktoberfest right now! If you have some spare time, consider contributing—it's a great way to get involved! 

https://collaboraonline.github.io/hacktoberfest/
https://hacktoberfest.com/

Happy hacking
