### ISSUE TITLE
Collabora Android Spreadsheet app "Copy & Paste" no longer “Pastes” the copied formulas or formatting

### ISSUE THREAD

**Issue by GilDH** [CollaboraOnline/online#10089]
### Describe the Bug
Since the 8/23/2024 and 8/28/24 Push Versions, Collabora Spreadsheet "Copy & Paste" no longer Pastes the formulas or cell formatting after being copied from a Template at the top (above the freeze rows and columns) on the same Tab/Sheet.

I am now using the more current Collabora spreadsheet Push Version 24.04.6.2 with no improvement to this "COPY & PASTE" issue. 

As of the 8/23/2024 Push, all of the Tabs/Sheets always show (ISSUE #9895 posted 8/24/2024). So it is possible that the fix for GitHub Issue #9895 caused the current problem that I am posting here.

A) Using this file on GitHub 
[240920_24bAugSepGil.ods](https://github.com/user-attachments/files/17088253/240920_24bAugSepGil.ods)

B) **Steps to Reproduce: For Copy & Paste FORMULAS**
1. Go to: "REG" Tab
2. Copy Cell D2 (i.e. from the "Template" at the top of the Tab)
3. Type 77 into D11 and 23 into C12
4. Paste the copy of Cell D2 to the empty Cell D12

C) **Expected Vs Actual Behavior: For Copy & Paste FORMULAS**
1. After Doing "B)" above, The formula in D2 does not show when you click on D12 whereas it used to show. ACTUAL BEHAVIOR: A Zero shows as the result instead of the EXPECTED BEHAVIOR: which should be a value of 100 (i.e. 77+23)
2. **Now look at row 109 (8/22/24) and below - you will notice that the COPIED Template formulas from row 2 "TotOz" are there when clicked on and they yield the correct values prior to 8/23/24**
3. Next took at the "TotOz" rows above row 109, after the Colabora Spreadsheet 8/23/2024 PUSH, and you will see that Copy & Paste FORMULA has not worked since,
4.  Formerly i could copy and past the formulas for a whole row or group of rows quickly in one copy & Paste.  Now I'd have to enter the formulas by typing the formulas into each cell. So i do the cumulative Totals in my head and enter them into each cell by hand.

D) **Steps to Reproduce: For Copy & Paste _FORMATTING_**
1. Go to: "HLTH" Tab
2. Note that the conditional Template Font Colors are shown in rows 11 and above (i.e. rows 3-11).
3. Copy from columns “E” (row 6 = bright BLUE, Value is “<=173”) and “F” (row 9 = bright GREEN,  Value is “<=95”)  I have to do this because consistently picking the same Highlight Color for the respective Observation Value for any day's observation from the Highlight Color pull down is too time consuming compared to a copy & paste followed by an "Edit"
4. Next Paste respectively into the same Columns on row 14 (for the 30th of September) as an example.
5. then I would edit the paste value to match the actual value observed which keeps the appropriate color.  That is simpler and less time consuming than entering the observed value then looking at the template and then going to the highlight panel and trying to match the appropriate color for the cell in the Template.

E) **Expected Vs Actual Behavior: For Copy & Paste _FORMATTING_**
Expected: Copy & Paste is always quicker and the text color is  consistently in agreement with the template.  Actual Behavior:  After 8/23/24, you will see that I just gave up whereas before 8/23/24 the text colors were consistent and meaningful for evaluating my performance by monitoring my Blood Sugar and Weight in order to help me change diet and exercise to keep things healthy.

### Smartphone
 - **Device:** Samsung A53 5G model SM-A536U with max storage
 - **OS:** Latest Android
 - **Browser and version:** Latest FireFox

### Additional Context
N/A
### Screenshots
N/A
### Desktop
N/A

GilDH 9/21/2024

**Comment by Darshan-upadhyay1110** [comment]
Hi @GilDH! I just tested the issue you mentioned with copy and paste not working in the latest version, and it appears to be fixed. Could you please give it a try and let us know how it goes?

Apologies for the inconvenience, and thanks for your feedback!

[Screencast from 2024-11-11 17-09-09.webm](https://github.com/user-attachments/assets/35437ed1-42a9-44e4-9975-393fb589e3e3)
