### ISSUE TITLE
Writer: hyperlink overview location covers relevant text

### ISSUE THREAD

**Issue by BrelLandJusticeFutures** [CollaboraOnline/online#10151]
### Issue

When selecting a hyperlink, the link description covers the text of the link itself, making the selected text unreadable.
![Screenshot 2024-09-30 at 12 27 38 PM](https://github.com/user-attachments/assets/889e8181-d827-44cc-bb7a-4f25aa80ea5e)

https://github.com/user-attachments/assets/0a82a18f-86c8-40aa-aec4-2ef8b74022d4

### Solution

Adjust the pin location for the link description box so that the bottom edge is right above the top line of the link, or below the top line if there is not enough room above to display, depending on scroll height.

### Alternatives:

1. Add a Grab bar on the right of the description box to be able to manually move the box as the user sees fit. (not mutually exclusive with a pin location change)
2. Have the description appear in an alternative location off the page.

**Comment by eszkadev** [comment]
I think we already worked on that: https://github.com/CollaboraOnline/online/pull/10146

**Comment by BrelLandJusticeFutures** [comment]
Yes. Looks like. Thanks.
