### ISSUE TITLE
Optimize the update of the loolwsd systemplate

### ISSUE THREAD

**Issue by erikfdev** [CollaboraOnline/online#1016]
**Is your feature request related to a problem? Please describe.**
My linux system (Linux Mint 20) automatically installs package updates every night.
Each time, the loolwsd systemplate is rebuild. The current size of the template is about 1GB. 
My systems main disk is an SSD. This almost daily rebuilding of the template wears out my SSD

**Describe the solution you'd like**
Why not use rsync to update the template, instead of using plain 'cp' ? Then only the changed/added/removed files are actually copied or deleted.

**Describe alternatives you've considered**
I could reduce the update frequency to once a week, but that is not a good idea cyber-security wise, because my system is reachable from the internet.

**Additional context**
N/A

**Comment by mmeeks** [comment]
Well - first, thanks for following the snapshots =) that's great for testing.
Beyond that - why is your systemplate 1Gb ? that seems excessively large. Mine is ~15MB.
We have a fix coming that will avoid needing fonts in the systemplate which should help - Ash is working on that currently I think; Ash - I suppose we should remember to copy the fontconfig files in, but not the fonts when we create the systemplate (although I wonder if we really need the fontconfig files if we pre-load them all (?)).

**Comment by erikfdev** [comment]
My current /opt/lool/systemplate:
# du -sh *
4,0K    dev
1008K   etc
1,5M    lib
180K    lib64
4,0K    lo
4,0K    opt
8,0K    tmp
955M    usr
7,9M    var

usr:
6,2M    lib
949M    share

usr/share:
940M    fonts
1,6M    hyphen
2,0M    liblangtag
5,4M    zoneinfo

usr/share/fonts:
11M     cmap
12K     cMap
300M    opentype
616M    truetype
13M     type1
576K    wps-office
1,6M    X11

**Comment by mmeeks** [comment]
Great - its almost all fonts =) in which case Ash's fix (in progress) will really help. Can you do an:
ls -lSh /opt/lool/systemplate/usr/share/fonts/truetype | head -n 20
and paste that here ? thanks =)

**Comment by erikfdev** [comment]
ls -lSh /opt/lool/systemplate/usr/share/fonts/truetype | head -n 20
totaal 6,3M
-rw-r--r-- 2 root root 6,0M jul  9  2015 fonts-japanese-gothic.ttf
drwxr-xr-x 2 root root 132K dec  1 16:39 noto
drwxr-xr-x 2 root root  12K nov 29 12:25 copied-from-windows
drwxr-xr-x 2 root root 4,0K dec  1 15:24 abyssinica
drwxr-xr-x 2 root root 4,0K nov 29 12:25 ancient-scripts
drwxr-xr-x 2 root root 4,0K nov 29 12:25 crosextra
drwxr-xr-x 2 root root 4,0K nov 29 12:25 dejavu
drwxr-xr-x 2 root root 4,0K nov 29 12:25 droid
drwxr-xr-x 2 root root 4,0K dec  1 15:23 fonts-beng-extra
drwxr-xr-x 2 root root 4,0K dec  1 15:09 fonts-deva-extra
drwxr-xr-x 2 root root 4,0K dec  1 15:23 fonts-gujr-extra
drwxr-xr-x 2 root root 4,0K dec  1 15:23 fonts-guru-extra
drwxr-xr-x 2 root root 4,0K dec  1 15:09 fonts-kalapi
drwxr-xr-x 2 root root 4,0K dec  1 15:24 fonts-orya-extra
drwxr-xr-x 2 root root 4,0K nov 29 12:25 fonts-telu-extra
drwxr-xr-x 2 root root 4,0K dec  1 16:38 fonts-yrsa-rasa
drwxr-xr-x 2 root root 4,0K dec  1 15:23 freefont
drwxr-xr-x 2 root root 4,0K nov 29 12:25 Gubbi
drwxr-xr-x 2 root root 4,0K nov 29 12:25 kacst


Note that this does not show the real size of each directory in the listing.

**Comment by Ezinnem** [comment]
@erikfdev, please can you update to the current version and test if this issue still occurs at your end?

**Comment by Ezinnem** [comment]
Closing this issue due to no response from the author.
