### ISSUE TITLE
Improve hover text labels in Table menu for consistency and clarity

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#10175]
### Describe the Bug
In the Tabbed View change the text labels in the Table menu to ensure they more accurately describe their actions, and also to better match their naming in the Context Menu and the Compact View:
Adjustments to be done based on which string should be displayed from unocommand.js file( "Context" or "menu").
To resolve inconsistencies and improve user experience by providing clearer descriptions for each menu action.

“Column Before” to “Insert Column Before”
“Column After” to “Insert Column After”
“Rows Above” to “Insert Rows Above”
“Rows Below” to “Insert Rows Below”
"Properties" to "Table Properties"

### Steps to Reproduce
Hover mouse over these buttons on the tabbed view to see their hover text label

### CODE
Collabora version: 24.04.7.3

**Comment by Darshan-upadhyay1110** [comment]
>Hi Darshan,
Please will you assign #10175 to me, rpear.  "Fix more hover text labels in Table menu for consistency and clarity".
Rob

@rpear done

Happy hacking

**Comment by Darshan-upadhyay1110** [comment]
Hello @rpear any joy here ?

**Comment by Darshan-upadhyay1110** [comment]
Message form @rpear :

"I can't look at this for at least 4 weeks, as I have to finish some tasks at work and then travel to the UK for an overdue catchup with siblings.

I am happy for you to assign the hover labels issue #10175 to someone else to have a go"

Unassigning @rpear for now...
