### ISSUE TITLE
If a document's filename contains spaces, export as PDF fails

### ISSUE THREAD

**Issue by LostinSpacetime** [CollaboraOnline/online#10179]
### Steps to Reproduce
1. Open a document with spaces in its name like "test test.odt"
2. Got to "File" -> Export as PDF
3. Accept default name and settings and export
4. see error
5. go back to the document file and rename it to test.odt
6. Repeat the export procedure
7. success!

### Expected Behavior
One should get a message that the document was successfully exported and a new PDF-file should be created. 

### Actual Behavior
Nothing happens, and there is also no newly created PDF-file.

### Desktop
Tested on multiple clients with multiple OSs and Browsers with the same behavior.

### Server
Ubuntu 22.04 with Plesk
Nextcloud 30.0.0
Built-in CODE server 24.4.702
Nextcloud Office 8.5.1

**Comment by timur-g** [comment]
yes, but this is reported at proper place https://github.com/CollaboraOnline/richdocumentscode/issues/284
