### ISSUE TITLE
Create Download CSV icon

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#1020]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @pedropintosilva 

### Detailed description and rationale
Add new icon to be used in the:
* Notebookbar mode: File tab
* Classic mode: File > Download as...
* Mobile: Hamburger menu > Download as..

**Comment by rizmut** [comment]
What is the filename of this icon?

**Comment by pedropintosilva** [comment]
@rizmut  please follow the same name conventions present in https://github.com/CollaboraOnline/online/search?q=id%3A+%27downloadas-ods%27 so, in this case, it would be :
```css
lc_downloadas-ods.svg
```

**Comment by rizmut** [comment]
> @rizmut please follow the same name conventions present in https://github.com/CollaboraOnline/online/search?q=id%3A+%27downloadas-ods%27 so, in this case, it would be :
> 
> ```css
> lc_downloadas-ods.svg
> ```

Are you sure it does not mean to be `lc_downloadas-csv.svg`?

**Comment by pedropintosilva** [comment]
_polite ping_ Did you find time to tackle this?

**Comment by rizmut** [comment]
I have drawn the icon, but not the time to rearrange my workflow. :(

**Comment by mmeeks** [comment]
Oh - cool, if you have the icon - please do attach it here, and we can push it for you - if you're happy to state it is CC0 licensed etc. =) Thanks ! excited to get this complete.

**Comment by rizmut** [comment]
I got "We don't support that file type. Try agan with a GIF, JPEG, JPG, MOV, MP4, PNG, DOCX, GZ, LOG, PDF, PPTX, TXT, XLSX or ZIP. Why on earth Github does not support SVG file?

**Comment by vmiklos** [comment]
Perhaps work it around by zipping your svg. :)

**Comment by rizmut** [comment]
[lc_exportdirecttocsv.zip](https://github.com/CollaboraOnline/online/files/5848311/lc_exportdirecttocsv.zip)
Here is it

**Comment by pedropintosilva** [comment]
https://github.com/CollaboraOnline/online/pull/1404
