### ISSUE TITLE
Use Core LibreOffice templates

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#1021]
COOL didn't use the default templates of for example writer.

Core LibreOffice use a hardcoded template but this template is also available within core (https://github.com/LibreOffice/core/tree/master/extras/source/templates/styles).

It would be nice if COOL can use the template from core so there is less maintanance work and improvements will be within COOL and Core.

**Comment by Andreas-Kainz** [comment]
@kendy already discuss in the weekly meeting https://staging.eu.collaboraonline.com/nextcloud/index.php/s/RwLeZjxiQTw8Z9y

**Comment by kendy** [comment]
@Andreas-Kainz: Reported this against richdocuments actually: https://github.com/nextcloud/richdocuments/issues/1306

**Comment by Andreas-Kainz** [comment]
As NC has template support this can be closed, cause it will duplicate functionality.
