### ISSUE TITLE
Remote fonts only partially working

### ISSUE THREAD

**Issue by djupdal** [CollaboraOnline/online#10227]
### Describe the Bug

I have set up collabora office and nextcloud using docker compose. 

I have set the remote_font_config url to point to my nextcloud fonts.json, and it works well in text documents and spreadsheets. But it does not work in drawings and presentations.

I am not sure if this is a bug in CollaboraOnline, or if this is a setup problem on my server.  I posted a question on the forum, but no solution was found.  Therefore assumes this is a real bug. 

[Original forum post](https://forum.collaboraonline.com/t/remote-fonts-only-partially-working/2823) 

### Steps to Reproduce
1. Set up a server using docker compose, with a docker compose file like this:

`collabora:`
`    image: collabora/code`
`    restart: unless-stopped`
`    container_name: collabora`
`    environment:`
`      - domain=<removed>`
`      - DONT_GEN_SSL_CERT=YES`
`      - dictionaries=nb_NO nn_NO es_ES ca_ES en_US en_GB`
`      - extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:remote_font_config.url=https://<removed>/apps/richdocuments/settings/fonts.json --o:user_interface.mode=compact`
`    ports:`
`      - 9980:9980`
`    expose:`
`      - "9980"`
`    depends_on:`
`      - traefik`
`    cap_add:`
`      - MKNOD`
`    labels:`
`      - "traefik.enable=true"`
`      - "traefik.http.routers.collabora.rule=Host(`<removed>`)"`
`      - "traefik.http.routers.collabora.entrypoints=websecure"`
`      - "traefik.http.routers.collabora.tls=true"`
`      - "traefik.http.routers.collabora.tls.certresolver=myresolver"`

3. Make sure the remote_font_config.url is pointing to your nextcloud fonts
4. Create a text document in nextcloud and see that the remote fonts are available
5. Create a presentation in nextcloud and see that the remote fonts are not available

### Expected Behavior
That the remote fonts are working in all the collabora office apps. 

### Actual Behavior
Remote fonts are only available in collabora text documents and spreadsheets, not in drawings and presentations. 

### Screenshots

Nextcloud settings, showing the fonts that are available:

![nextcloud_settings](https://github.com/user-attachments/assets/79aa72ba-85a6-4ed1-b98b-38b16f3287b8)

Collabora writer, showing that font pacifico is available:

![writer](https://github.com/user-attachments/assets/17215f0d-6f36-4cb6-b8cc-8ac28c62a2a3)

Collabora draw, showing that font pacifico is missing:

![draw](https://github.com/user-attachments/assets/069e8717-4ca9-4a83-a0fa-ea970c3b4347)

### Desktop
 - **Collabora version:** 24.04.8.2 (although has been like this for several versions of collabora and nextcloud)
 - **OS and version:** Ubuntu 24.04
 - **Browser and version:** Firefox 131.0.2

**Comment by sebastiaanveld** [comment]
Nice catch, that explains soem of the weird presentation behavior I saw before:)
Can duplicate this too.

Environment:
Firefox 131.0.3 x64, Windows 11

Nextcloud 30.0.1.2
+Nextcloud Office App 8.5.2

CODE:
COOLWSD version: 24.04.8.2(git hash: 77a0aab (E))
LOKit version: Collabora Office 24.04.8.2(git hash: ac08496)
Served by: Debian GNU/Linux 12 (bookworm)
Server ID: f995c3d5
WOPI host: nextcloud 30.0.1.2 - richdocuments 8.5.2

**Comment by skywalker478** [comment]
I have also encountered the same issue. What's funny is I couldn't even get remote fonts to work with SSL enabled before seeing this post. It used to say hostname lookup error for my nextcloud domain. Disabling SSL at least loads the font in writer and sheets.

Hope the issue is solved. And I would be grateful if anyone would explain it to me why enabling ssl resulted in hostname lookup failure.

**Comment by timur-g** [comment]
I would expect that this was fixed later, so I close, please use 24.04.10.

**Comment by skywalker478** [comment]
Yes it was fixed. I forgot that I even opened this issue lol. My bad!
