### ISSUE TITLE
mobile: icon missing in comment option menu

### ISSUE THREAD

**Issue by Rash419** [CollaboraOnline/online#10230]
Potential mentor: @pedropintosilva or @Darshan-upadhyay1110 

### Describe the Bug
`Resolve` and `Resolve Thread` icon missing in comment option menu for mobile

### Steps to Reproduce
1. Open document in mobile view using browser's 'Responsive Design Mode' 
2. Insert Comment using Comment Wizard
3. Open Comment Wizard again
4. Click on 3-dot menu

### Expected Behavior
Should have icons for consistency

### Actual Behavior
Icons are missing

### Screenshots
![image](https://github.com/user-attachments/assets/607a8edc-652f-4977-8c8d-dabc1eb6790b)

**Comment by Fictionistique** [comment]
May I work on this issue? 
What icons are to be used for these two options? Is there an icon library to refer to or do those icons need to be created?

**Comment by Rash419** [comment]
@Fictionistique sure. Go for it : )
