### ISSUE TITLE
No Tooltip when command has icon + label

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#1029]
In Notebookbar mode only in Home tab there are icons without labels in the other tabs each command has an icon + label as the labe is similar to the tooltip, a tooltip isn't needed.

![2020-12-18 09_50_36-Welcome to Nextcloud Hub docx - Dateien - Nextcloud](https://user-images.githubusercontent.com/8517736/102594478-8caa7780-4116-11eb-88fd-31c31a61c0cf.png)

**Comment by eszkadev** [comment]
Code pointer:
these buttons are created in: https://github.com/CollaboraOnline/online/blob/7f6cacb18734a1a2fbe6604745adeea450851851/loleaflet/src/control/Control.JSDialogBuilder.js#L1986

Toolip is created by:
$(div).tooltip();
it uses: div.title  property as a text

probably:
useInLineLabelsForUnoButtons === true
condition detects the case from an image

**Comment by eszkadev** [comment]
fixed in: https://github.com/CollaboraOnline/online/pull/1237
