### ISSUE TITLE
Another APK-Build/Version

### ISSUE THREAD

**Issue by ghost** [CollaboraOnline/online#10308]
I want to use Collabora Office but there is only a F-Droid Build or Google Play Version but I don't have Google Play Services and I don't like F-Droid because of their Security Issues in the past. Could you publish a Build/APK on Github which is just a normal Build/APK without both dependencies? It would provide a helpful solution for anyone who don't like both like me, because we see it as degoogling and more security efficient/wise. It would make me and a lot of people really happy!

**Comment by timur-g** [comment]
You may also download from https://www.collaboraoffice.com/downloads/fdroid/repo/.
