### ISSUE TITLE
Copy function is broken

### ISSUE THREAD

**Issue by mlan** [CollaboraOnline/online#10421]
### Describe the Bug
It's not possible to copy content from within the Text, Calc and Presentation apps to the clipboard.

### Steps to Reproduce
Copy some text in a document, calc or presentation
Paste in any Windows application.

### Expected Behaviour
Text gets copied.

### Actual Behaviour
Nothing gets added to the clipboard.
Noting get copied in Windows application.

### Additional findings
The reverse operation, that is, copy text in a Windows application and pasting it into a document opened in ColaboraOnline works as expected. 

### Desktop
``` 
COOLWSD version: 24.04.9.1(git hash: 55317ef (E))
LOKit version: Collabora Office 24.04.9.1(git hash: 087c4c5)
Served by: Debian GNU/Linux 12 (bookworm)
Traefik version 3.2.0 built on 2024-10-28T14:49:00Z
```

**Comment by jazevedo-coll** [comment]
hello @mlan are you using traefik as a reverse proxy in your setup?

**Comment by jazevedo-coll** [comment]
@mlan sorry, I missed the: `Traefik version 3.2.0 built on 2024-10-28T14:49:00Z` in the info you sent. 

We have a fix for this issue which will be in the next CODE Collabora Online Development Edition release. 

https://github.com/CollaboraOnline/online/pull/10190
https://github.com/CollaboraOnline/online/pull/10394
https://github.com/CollaboraOnline/online/pull/10413

**Comment by mlan** [comment]
That is excellent news. I will verify on my end as soon as the new version will be available.

**Comment by jazevedo-coll** [comment]
I will close this issue. If you still have this problem after the update, please reopen it.
