### ISSUE TITLE
Shapes Misaligned Upon Reopening Document for Editing

### ISSUE THREAD

**Issue by Ezinnem** [CollaboraOnline/online#10458]
### Describe the Bug
In writer, shapes are misaligned upon Reopening Document for Editing.

### Steps to Reproduce

1. Create document with some content (not saved)
2. Add a shape and position it (not saved)
3. Save document
4. Close document
5. Re-open document for editing
6. Shape is in the wrong place

### Expected Behavior
The Shape is at the position that was placed at 
### Actual Behavior
shapes are misaligned upon reopening document
### Desktop
 - **Collabora version:** 24.04.6.3

**Comment by annanazarayan** [comment]
It is now done. I will close this task
