### ISSUE TITLE
security.server_signature easy bypass

### ISSUE THREAD

**Issue by tuxArg** [CollaboraOnline/online#10454]
A security.server_signature config was recently added with default value to false to hide server version but it's easy to bypass it by looking at the user agent that is returned by getAgentString. I think that function should also use the new server_signature flag.

**Comment by Ashod** [comment]
Thanks, @tuxArg, for the report.

Unlike the server signature, the user agent string is used for _client_ requests. That is, the agent string is only sent in HTTP requests, which are sent to _trusted_ servers.

This is very different from the situation with the server responding with its name and version to any external request, which is by nature untrusted (and what the referenced config controls).

Notice that it should not be possible to force coolwsd to communicate with any arbitrary server, through an HTTP request, and thereby reveal its user agent string. At least as long as there is no practical way to make it communicate with a server controlled by an untrusted 3rd party, the agent string remains safe.
As such, in practice, the agent string wouldn't be a possible method for revealing the server's version to an untrusted 3rd party.

Let me know if this answers your concern or if I missing something.
Thank you.

**Comment by tuxArg** [comment]
Hi, so I don't know if I have something misconfigured then because if I do:
```
curl -v https://office.mycloud.tld/cool/ 2>&1 | grep user-agent
> user-agent: curl/7.81.0
< user-agent: COOLWSD HTTP Agent 24.04.9.1
```
So everyone can get my server version. Do I have to fix my settings somehow?

**Comment by Ashod** [comment]
Here is what I have with 24.04.10:

```
$ curl -v http://localhost:9980/
*   Trying 127.0.0.1:9980...
* Connected to localhost (127.0.0.1) port 9980 (#0)
> GET / HTTP/1.1
> Host: localhost:9980
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Tue, 12 Nov 2024 11:47:44
< Server: COOLWSD HTTP Server 24.04.10.0
< Content-Length: 2
< Content-Type: text/plain
< Last-Modified: Tue, 12 Nov 2024 11:47:44
< 
* Connection #0 to host localhost left intact
OK
```

Of course the "Server:" header is now controlled behind `security.server_signature`, which I don't have set.

**Comment by tuxArg** [comment]
@Ashod I get that too if I query `http://localhost:9980/` but if I query `http://localhost:9980/cool/` then I get the User-Agent header:

`< User-Agent: COOLWSD HTTP Agent 24.04.9.1`

That's why I think that it should be hidden too. Or I misunderstood the new `security.server_signature` purpose.

**Comment by Ashod** [comment]
@tuxArg, yes, it would seem that in case of a bad request you are right. This is easy to fix in isolation of course.

I couldn't find another case, though, where the User-Agent is sent back.

I'll review and fix the cases I find. `security.server_signature` can remain for the `Server:` header, and we make sure `User-Agent:` is only sent on client requests, not server responses.

Is that reasonable?

**Comment by tuxArg** [comment]
That's ok.
Anyway, I don't think setting `security.server_signature` to `false` is working for me.
I've tried adding
`<server_signature desc="server_signature" type="bool" default="false">false</server_signature>` under `<securiy>` section in to coowsd.xml. But server version is always being sent.

**Comment by Ashod** [comment]
@tuxArg, to confirm, I just tried it and with `security.server_signature` set to `false` the output is:
```
< HTTP/1.1 200 OK
< Date: Tue, 19 Nov 2024 23:57:31
< Server:  
< Content-Length: 2
< Content-Type: text/plain
< Last-Modified: Tue, 19 Nov 2024 23:57:31
```

But with it set to `true`, the output is:
```
< HTTP/1.1 200 OK
< Date: Tue, 19 Nov 2024 23:57:09
< Server: COOLWSD HTTP Server 24.04.10.0
< Content-Length: 2
< Content-Type: text/plain
< Last-Modified: Tue, 19 Nov 2024 23:57:09
```

Worth double-checking that there are no typos, and that your restarted coolwsd. Note that the latest version now dumps the config entries that are different from the default, which should help.

**Comment by tuxArg** [comment]
@Ashod I'm using the docker image. And apparently the `security.server_signature` flag was ported in `24.04.9.2.1`. Version `24.04.9.1.1` still ignored that setting. So it's working for me now!
