### ISSUE TITLE
Not compatible Bug

### ISSUE THREAD

**Issue by ghost** [CollaboraOnline/online#10659]
### Describe the Bug

A warning popup saying that this Version is not compatible with the newest Android Version or I should update the App, even tho it is the last Version.

### Steps to Reproduce
1. Install Collabora Office from their Repo
2. Open App first time
3. Popup warning shows

### Expected Behavior

That this do now show up. Because when I install it from the Website, then this warning do not appear.

### Actual Behavior
A clear and concise description of what actually happens.

Warning popup do appear

### Desktop
(Please complete the following information)
 - **Collabora version:** [e.g. 23.05.5.3]
 - **OS and version:** [e.g. Windows 11]
 - **Browser and version:** [e.g. Chrome 114.0]

### Smartphone
(Please complete the following information)
 - **Device:** [e.g. iPhone 14] - Xiaomi Poco X3 NFC
 - **OS:** [e.g. iOS 16.5] - Android 14
 - **Browser and version:** [e.g. Safari 16.4] - Mulch Browser 131.0.6778.108

**Comment by eszkadev** [comment]
Could it be related to https://github.com/CollaboraOnline/online/pull/10537#event-15532689794 ? @Minion3665

**Comment by Minion3665** [comment]
> Could it be related to [#10537 (comment)](https://github.com/CollaboraOnline/online/pull/10537#event-15532689794) ? @Minion3665

No, this is iOS only, has been in our release branches for a while and doesn't indicate anything about Android version...

---

However

> Because when I install it from the Website, then this warning do not appear

makes me wonder if this is maybe an issue with how we're updating F-Droid, as if I read correctly this is only an issue when the app is installed from there...
