### ISSUE TITLE
collabora-online doesn't build in Fedora 41 due to npm dependency

### ISSUE THREAD

**Issue by renich** [CollaboraOnline/online#10660]
### Describe the Bug
When I try to build collabora-online against a freshly compiled LibreOffice (matching tags), I get an npm error with a 404 somewhere in there.

### Steps to Reproduce
I will assume that we have both; collabora-online and libreoffice's sources at: ~/src/lo-upstream/core and ~/src/lo-upstream/online respectively. I am trying this in Fedora 41 x86_64.

First, we build LibreOffice:

```bash
#!/usr/bin/bash
set -x

#lo_path=$HOME/src/lo-gob.mx/office-gobmx
lo_path=$HOME/src/lo-upstream/core
tag=cp-24.04.10-2

# ir allá
cd "$lo_path"

# instalar dependencias
sudo dnf -y install \
    ant \
    ant-junit \
    autoconf \
    automake \
    cups-devel \
    dnf-plugins-core \
    gcc-c++ \
    git \
    java-latest-openjdk \
    java-latest-openjdk-devel \
    libcap-devel \
    make \
    nasm \
    poco-devel

sudo dnf -y builddep libreoffice

# irse al tag
git reset --hard
git clean -dfx
git checkmout master
git pull
git checkout $tag
git submodule update --init

# autogenerar los recursos de compilación
## opciones
options=(
    '--with-myspell-dicts'
    '--with-lang=es'
)

## agregar branding si es gobmx
if [[ "$lo_path" =~ gobmx ]]; then
    options=(
        ${options[@]}
        '--with-branding=custom_images'
    )
fi

## generar configuración
./autogen.sh ${options[@]}

# iniciar compilación
make clean build

```

Then, we compile collabora-online against that one:

```bash
#!/usr/bin/bash

# definir el path a libreoffice
lo_path=/home/cool/src/lo-upstream/core
online_path=$HOME/src/lo-upstream/online
online_tag=cp-24.04.10-2

# instalar dependencias
sudo dnf -y install --allowerasing \
    chromium \
    cppunit-devel \
    gcc \
    gcc-c++ \
    libcap-devel \
    libpng \ 
    libpng-devel \
    libstdc++-devel \
    libtool \
    libzstd-devel \
    nodejs \
    nodejs-devel \
    npm \
    pam-devel \
    poco-devel \
    python3-polib
    
# el comando anterior funciona con la versión poco-devel-1.12.4-6.fc40

# ir ahí
cd $online_path

# situarse en la etiqueta requerida
git reset --hard HEAD
git clean -dfx
git checkout master
git pull
git checkout $online_tag

# generar la configuración
./autogen.sh
    
export CFLAGS="$CFLAGS -DPOCO_UNBUNDLED=1"
export CXXFLAGS="$CXXFLAGS -DPOCO_UNBUNDLED=1"

./configure \
    --disable-android-google-play \
    --disable-androidapp \
    --disable-bundle \
    --disable-debug-protocol \
    --disable-iosapp \
    --disable-setcap \
    --disable-werror \
    --enable-cypress \
    --enable-silent-rules \
    --with-dictionaries="en_US es_ES es_MX" \
    --with-lo-path=$lo_path/instdir \
    --with-lokit-path=$lo_path/include/

make -j
```

The second procedure yields a very long error, which I will append as a log file. 

[2024-12-05T02_41_55_945Z-debug-0.log](https://github.com/user-attachments/files/18016573/2024-12-05T02_41_55_945Z-debug-0.log)

### Expected Behavior
It should compile.

### Actual Behavior
It doesn't compile.

### Desktop
(Please complete the following information)
 - **Collabora version:** cp-24.04.10-2
 - **OS and version:** Fedora 41 x86_64
 - **Browser and version:** Irrelevant

**Comment by renich** [comment]
I've updated the scripts used to build. They were outdated. The problem persists, though.

**Comment by renich** [comment]
I'd like to point out that it builds fine in Fedora 40. The key difference being:

f40: 
* nodejs-20.17.0-1.fc40.x86_64
* nodejs-npm-10.8.2-1.20.17.0.1.fc40.x86_64

f41: 
* nodejs-22.11.0-1.fc41.x86_64
* nodejs-npm-10.9.0-1.22.11.0.1.fc41.x86_64

**Comment by timar** [comment]
There is no binary for node canvas on GitHub for this specific version of node, and build falls back to compile it from source. Try to `--disable-werror` with configure script. This module is needed for mocha tests, it is 3rd party code, so we cannot fix the problem otherwise in this repo.

**Comment by renich** [comment]
OK, we figured it out. We had to npm install canvas@next at browser/.

Here's the diff:

```diff
diff --git a/browser/package.json b/browser/package.json
index a1144589e0..adace8c48a 100644
--- a/browser/package.json
+++ b/browser/package.json
@@ -16,7 +16,7 @@
     "autolinker": "3.14.1",
     "browserify": "16.5.1",
     "browserify-css": "0.15.0",
-    "canvas": "^2.6.1",
+    "canvas": "^3.0.0-rc3",
     "d3": "6.7.0",
     "dompurify": "3.1.7",
     "eslint": "7.0.0",
```
