### ISSUE TITLE
Bug total

### ISSUE THREAD

**Issue by Erwan62** [CollaboraOnline/online#10700]
### Describe the Bug
Bug en cascade :
- Importation totalement foireuse des textes, photos et tableaux
- bug des formats de texte à répétition et en cascade (y compris les textes antérieurs)
- blocage du document online
- imposssible de revenir en arrière pour annuler les erreurs
- impossible de refuser une modifications (avec suivi)
- corruption de la sauvegarde

### Steps to Reproduce
1. Éditer votre document
2. essayer d'importer des éléments d'un autre ODT : tableau, texte ou photo (hors-ligne, libreoffice)
3. essayer de reprendre votre travail
4. les bug en cascade corrompent tout le document qui devient irrécupérable.

### Desktop
COOLWSD version: 24.04.9.1(git hash: 55317ef2)
LOKit version: Collabora Office 24.04.9.1(git hash: 087c4c5)
Served by: Debian GNU/Linux 12 (bookworm)
Server ID: 811eaf3f
WOPI host: 

 - Windows 11
 - Firefox nightly 135.0a1

**Comment by Darshan-upadhyay1110** [comment]
Translated text:

Describe the Bug

Bug a cascade :
- Totally failed import of texts, photos and tables
- bug in repeating and cascading text formats (including past texts)
- online document blocking
- cannot go back to undo mistakes
- Unable to refuse a modification (with tracking)
- backup corruption

Steps to Reproduce

- Edit your document
- try to import elements from another ODT: table, text or photo (offline, libreoffice)
- try to get your job back
- cascading bugs corrupt the entire document, making it unrecoverable.

**Comment by thebearon** [comment]
@Erwan62 Please give sample file and specific steps.
