### ISSUE TITLE
PDF download sometimes happens on the wrong view

### ISSUE THREAD

**Issue by vmiklos** [CollaboraOnline/online#10782]
### Describe the Bug
Sometimes when having multiple users, the wrong user gets the PDF after clicking "download as PDF" on the notebookbar.

### Steps to Reproduce
1. User 1 opens e.g. [test.odt](https://github.com/user-attachments/files/18208947/test.odt)
2. User 2 joins the same document
2. User 2 clicks on "download as PDF"

### Expected Behavior
User 2 gets the PDF result.

### Actual Behavior
Sometimes user 1 gets the PDF result

### Screenshots
Here is a case where this happens:

https://github.com/user-attachments/assets/b63f5cff-195d-48de-969d-22013188ad29

### Additional Context
I had trouble reproducing this, one working scenario is User 1 using Chrome, user 2 using Firefox, a 'make run' session of locally built optimized cp-24.04.7-3, but surely this happens with latest core.git co-24.04 + online.git master as well, just less frequently.

**Comment by vmiklos** [comment]
https://gerrit.libreoffice.org/c/core/+/178883

**Comment by thebearon** [comment]
This was a regression from the following change:
https://github.com/CollaboraOnline/online/commit/930cd616fb6defd8c0de0163bd92e637c7b6b76f
https://github.com/CollaboraOnline/online/pull/9896
```
Author:     Miklos Vajna <vmiklos@collabora.com>
AuthorDate: Mon Aug 26 09:26:59 2024 +0200
Commit:     Caolán McNamara <caolanm@gmail.com>
CommitDate: Mon Aug 26 09:07:37 2024 +0100

    Related: cool#9735 kit: use the new registerAnyInputCallback() LOK API
```
