### ISSUE TITLE
Wrong text vertical alignment compared to the checkbox in show sheets dialog

### ISSUE THREAD

**Issue by banobepascal** [CollaboraOnline/online#10813]
Describe the bug
![image](https://github.com/user-attachments/assets/a830ebf1-0551-4b27-bc23-c38a5f6dcdc7)

...

### Steps to Reproduce
- Open Calc and multiple sheets
- 1st hide some sheets (by right click in a sheet > hide) 
-  2nd right click -> Show sheets and you will have access to the dialog

**Comment by stranger-scripts-06** [comment]
Can I please work on this issue?
