### ISSUE TITLE
NB Home Tab

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#1086]
The Home Tab of notebookbar was preloaded by the notebookbarxxx.js file and than the notebookbar from the .ui file (core) was loaded.

As the alignment and also the arrangement is way easier with .js within cool I suggest to don't load the home tab from core and show ONLY the home tab from cool, like we did with file and insert tab.

**Comment by eszkadev** [comment]
its not possible at the moment (should be soon). As we load whole tab to update styles preview.
I'm going to make  only images reloading with styles soon.

**Comment by Andreas-Kainz** [comment]
that will be great! use the styles only will improve the home tab also. 

Maybe we can than use the previews in calc and impress too.
