### ISSUE TITLE
Introduce WOPI endpoints for local file access

### ISSUE THREAD

**Issue by kendy** [CollaboraOnline/online#110]
This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).
Potential mentors: @kendy 

When the Collabora Online is built with --enable-debug, it is possible to open local files for easy testing. The problem with the current implementation is that it is a separate code path from what is later used in the real world - which always integrates through WOPI.

This task has two parts:

1) Introduce serving the local files via WOPI endpoints directly from loolwsd.
2) Kill the implementation of the local file storage, and do appropriate changes in the loolwsd.xml setting.

Ad 1) - this can be done in wsd/FileServer.cpp, see the FileServerRequestHandler::handleRequest - which would implement the GET and POST methods appropriately. For an inspiration what endpoints have to be implemented, have a look at test/WopiTestServer.hpp, method handleHttpRequest() that does the same thing for unit tests.

Ad 2) - <tt>git grep LocalStorage</tt> and kill all the uses.  Then update the message that outputs the URL to be issued locally with the right one (<tt>git grep LOOLWSD_TEST_DOCUMENT_RELATIVE_PATH</tt>) and also check the setting in loolwsd.xml.in (the <tt>filesystem</tt> option).

**Comment by pedropintosilva** [comment]
fixed by #3226
