### ISSUE TITLE
Kill WebDAVStorage in the code

### ISSUE THREAD

**Issue by kendy** [CollaboraOnline/online#111]
This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).
Potential mentors: @kendy 

<tt>git grep WebDAVStorage</tt>, remove all the occurrences of the WebDAVStorage and make the code building without that :-)

Also please remove the <tt>&lt;webdav&gt;</tt> section from loolwsd.xml.in

**Comment by yunusbulutt** [comment]
I would like to solve this! Can you please assign?

**Comment by mrkara** [comment]
> I would like to solve this! Can you please assign?

Thank you for your interest! :)

Please, feel free to go ahead and submit a pull request. First come, first served.

**Comment by yunusbulutt** [comment]
Hi @mrkara 
I sent a pull request but. I need to edit. I edit it immediately and send it again.

**Comment by mrkara** [comment]
This is fixed now. Thank you @yunusbulutt ! We are looking forward to your next pull request. :)
