### ISSUE TITLE
Arrow in presentation

### ISSUE THREAD

**Issue by pascoual** [CollaboraOnline/online#1139]
**Describe the bug**
Spent a lot of time searching how to insert simple (line) arrows in presentation :). Here the Insert menu:
![image](https://user-images.githubusercontent.com/5540535/103488814-2d37b180-4e10-11eb-85cf-ff0ccc378384.png)

**To Reproduce**
1. Open a presentation
2. Go to insert
3. no way to get an simple arrow

**Expected behavior**
A way to add simple line with arrow extremity in insert section.

**Actual behavior**
No way to add it.

**Screenshots**
![image](https://user-images.githubusercontent.com/5540535/103488814-2d37b180-4e10-11eb-85cf-ff0ccc378384.png)

**Additional context**
[Forum post about it](https://forum.collaboraonline.com/t/arrow-in-presentation/122)

**Comment by pedropintosilva** [comment]
Thanks @pascoual I have answered it in the Forum : ) but here is a more technical answer .

I have tested, unfortunately we do not have that option currently. Nevertheless it's pretty straight forward to add that but it wouldn't solve other issues, so I think it needs some more development and testing. 

Meanwhile and by adding the respective uno command `.uno:Line` to `loleaflet/src/control/Control.Menubar.js` as a test and by updating the commands by running `/home/pedro/online/scripts/unocommands.py --update /home/pedro/online/ /home/pedro/LibreOffice/core/` it was visible some of the quirks that sill need to be ironed:

* quite difficult to select the line
* some visual feedback when we are about to draw (cursor)
* some visual feedback while dragging (wonders if that's possible)

![uno-Line](https://user-images.githubusercontent.com/65948705/103646995-dd193600-4f5a-11eb-936d-882909268a14.gif)

Thanks for reporting it, hopefully, we will manage to have this soon : )

**Comment by pascoual** [comment]
Thanks @pedropintosilva I will try the workaround ;).

**Comment by mrkara** [comment]
@pedropintosilva So is this now resolved, after the merged commits?

**Comment by pedropintosilva** [comment]
@mrkara yes it's already merged (master) and working everywhere (writer, calc, impress). However in impress insert a line shares the same common bug as describe in  #1183 also I have created a small list of improvements regarding line manipulation #1462
