### ISSUE TITLE
Impress: Inserting text box can happen twice

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#1184]
**Describe the bug**
Similar to #1183 but only on impress

**Describe the bug**
When clicking in the insert text box icon, it :
* adds a text box to the centre on the slide
* plus it binds the creation of the text box to the cursor, so if I click and drag It creates an extra text box

**Expected behavior**
It should be consistent with the desktop counterpart, do not add a text box until the user:
1. clicks and drags *or*
2. untill the user clicks anywhere (one click)

**Screenshots**

https://user-images.githubusercontent.com/65948705/104026020-b1e64f00-51c5-11eb-865d-98a384b52a50.mp4

**Comment by gitgt** [comment]
I am not seeing this in 23.05, where new text box shoudl apper in Navigator .
I cannot be sure though as it is not written in which version it was reproduced.
I will close but @thebearon please retest as you confirmed the bug.
