### ISSUE TITLE
Unauthorized WOPI Host after upgrade to latest 6.4.3.1

### ISSUE THREAD

**Issue by RolandSM** [CollaboraOnline/online#1191]
Hello,

until today I had a working setup with Collabora-Code 6.4.2.2 and latest stable Nextcloud and Owncloud instances.

I startup with following docker command:
> docker run --name collabora \
>            --hostname collabora.mydomain.de \
>            --net mynetwork \
>            --ip 173.18.0.66 \
>            -d \
>            -t \
>            -p 127.0.0.1:9980:9980 \
>            -e 'domain=owncloud\\.mydomain\\.de|nextcloud\\.mydomain\\.de' \
>            -e 'username=myuser' \
>            -e 'password=mypassword' \
>            -v /etc/timezone:/etc/timezone \
>            -v /etc/localtime:/etc/localtime \
>            --restart always \
>            --cap-add MKNOD \
>            collabora/code:6.4.2.2

But when I switch last line from 6.4.2.2 to latest (6.4.3.1) I get on both clients an unauthorized wopi host.
When I go back to 6.4.2.2 it works again.

Here is ma apache2 vhost, working with 6.4.2.2:

> \# Encoded slashes need to be allowed
> AllowEncodedSlashes NoDecode
> 
> \# Container uses a unique non-signed certificate
> SSLProxyEngine On
> SSLProxyVerify None
> SSLProxyCheckPeerCN Off
> SSLProxyCheckPeerName Off
> 
> \# keep the host
> ProxyPreserveHost On
> 
> \# static html, js, images, etc. served from loolwsd
> \# loleaflet is the client part of Collabora Online
> ProxyPass           /loleaflet https://127.0.0.1:9980/loleaflet retry=0
> ProxyPassReverse    /loleaflet https://127.0.0.1:9980/loleaflet
> 
> \# WOPI discovery URL
> ProxyPass           /hosting/discovery https://127.0.0.1:9980/hosting/discovery retry=0
> ProxyPassReverse    /hosting/discovery https://127.0.0.1:9980/hosting/discovery
> 
> \# Capabilities
> ProxyPass           /hosting/capabilities https://127.0.0.1:9980/hosting/capabilities retry=0
> ProxyPassReverse    /hosting/capabilities https://127.0.0.1:9980/hosting/capabilities
> 
> \# Main websocket
> ProxyPassMatch "/lool/(.*)/ws$" wss://127.0.0.1:9980/lool/$1/ws nocanon
> 
> \# Admin Console websocket
> ProxyPass   /lool/adminws wss://127.0.0.1:9980/lool/adminws
> 
> \# Download as, Fullscreen presentation and Image upload operations
> ProxyPass           /lool https://127.0.0.1:9980/lool
> ProxyPassReverse    /lool https://127.0.0.1:9980/lool

**Comment by EricKerby** [comment]
@RolandSM, Try the docker run command without using any "\" escape characters. I ran into this exact issue and noticed in the logs of the container that the exact domain I had specified was being detected but failed to match the config. When I removed the backslashes from the domain parameter everything started working normally again. I'm guessing something changed in how the domain list is parsed such that the escapes are no longer needed.

**Comment by RolandSM** [comment]
@EricKerby 
Yes this works... Thanks...

**Comment by palto42** [comment]
I run into the same issue with update to 6.4.3.1 and could also solve it by removing the backslashes.
The [official documentation](https://www.collaboraoffice.com/code/docker/) still says that the dots must be escaped, which seems wrong now.

**Comment by ivanalonzo** [comment]
+1 on escaping issue. Unescaping the dots in the URL fixed the issue for me as well
