### ISSUE TITLE
F-Droid repo hasn't been updated for 2 months 

### ISSUE THREAD

**Issue by Timmy183-ui** [CollaboraOnline/online#1193]
The f-droid repo hasn't been updated for two months it is still stuck on version 4.2 while the play store release is on 6.4.1 it's really bad to see that play store is given priority over f Droid. Hope it will be updated soon there

**Comment by yunusem** [comment]
It is not stuck, we mainly serve our snapshots there, however it is true that 4.2 android version does not get update.
Thus, when you look at latest update notation in fdroid it can be seen that 6.4 snapshot binary got updated 28.12.2020.

Possible solution for end-point, we can add 6.4 android release to fdroid release chain.

**Comment by mmeeks** [comment]
Clearly Timmy is right, we should be releasing concurrently on F-droid with Play if we can - no idea how to avoid this happening again, but if we can we should do something to weld those two together.

Thanks !

**Comment by yunusem** [comment]
Welded and tied fdroid chain with specifically google play internal testing track chain. 
Checked the fdroid repository from my fdroid client (my phone : Xiaomi Mi6 ) everything looks in order.

@Timmy183-ui you also should be able to see the changes after updating your fdroid client's metadata. :wink: 
I think issue is fixed.

**Comment by licaon-kter** [comment]
Can you reopen this? It been a year already.... without updates.

While I see them pushed to https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/
