### ISSUE TITLE
Write Protected Sections allow addition of alphanumeric content

### ISSUE THREAD

**Issue by harman-cn** [CollaboraOnline/online#1199]
**The bug**
In LibreOffice, making a section of the document "write protected" stops users from adding or editing any content in that section. This includes adding any characters - alphanumeric or otherwise. In CODE, however, users are able to add alphanumeric characters even to protected sections. Trying to add white space of any kind - spaces, tabs, newlines are correctly blocked, as is removing content - backspace and delete. However, users can freely add alphanumeric characters at any position in the protected section. Tested on CODE as well as the Collabora Online Demo in Chrome and Firefox.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to CODE Online Writer
2. From the toolbar, Insert > Section > Tick Protect under the Write Protection heading (Password optional) > Insert
3. Try to add alphanumeric characters in the protected section, eg. "abc123"
4. This content is added to the protected section, which is unexpected behaviour

Making an existing section write-protected rather than creating a new one also leads to the same behavior.

**Expected behavior**
Just like in LibreOffice, write-protected sections should be protected from modifications of **any kind**, including the addition of alphanumeric content. The blocking of modifications and the message "Write-protected content cannot be changed. No modifications will be accepted" that pops up when trying to add in a space/newline/backspace should also be the behaviour when trying to add in alphanumeric content.

**Actual behavior**
Alphanumeric content is added to the write-protected section.

**Screenshots**
[Adding alphanumeric content in protected section](https://ibb.co/p27dHHc)
[Blocked from adding spaces to the protected section](https://ibb.co/9wrC4SX)

**Comment by mmeeks** [comment]
Interesting - I imagine this is a core bug; whereby the input method code-paths are missing these checks - that the keystroke code-paths have (we use key-strokes for the characters you outline). I guess:

void SfxLokHelper::postExtTextEventAsync(const VclPtr<vcl::Window> &xWindow,
                                         int nType, const OUString &rText)
vs.
void SfxLokHelper::postKeyEventAsync(const VclPtr<vcl::Window> &xWindow,
                                     int nType, int nCharCode, int nKeyCode, int nRepeat)

is the difference. So I guess:

        pLOKEv->mnEvent = VclEventId::WindowKeyInput;
vs.
        pLOKEv->mnEvent = VclEventId::ExtTextInput;

Perhaps somewhere like:

sw/source/uibase/docvw/edtwin.cxx:    case CommandEventId::StartExtTextInput:

But not a writer expert. Quite possibly we just need to share some checks / conditionals from the key input code path. Please do dig around in the core code in sw/ to see if anything jumps out at you.

Thanks !

**Comment by vmiklos** [comment]
Let me see, indeed sounds like a core problem.

**Comment by vmiklos** [comment]
Fix is pending CI at <https://gerrit.libreoffice.org/c/core/+/109212>.

**Comment by vmiklos** [comment]
Fixed with https://github.com/LibreOffice/core/commit/f3bedf92fb8d07114bc3d53d8a01928c77e479fc

**Comment by harman-cn** [comment]
Thanks for the fast fix! Could you please give me some pointers on how to include this fix in CODE?

**Comment by vmiklos** [comment]
Just build the code yourself or wait for the next CODE update, they are quite frequent. Building the code:

https://collaboraonline.github.io/post/build-code/
