### ISSUE TITLE
Notebookbar Home Tab need too much height

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#1219]
Home tab is 92px height (defined in notebookbar.css with 84px) and Insert Tab (which come from Control.NotebookbarWriter.js) is 60 px height.

Home Tab
![2021-01-13 08_41_36-ws-e0f5a3a5-2ec4-4203-9c60-fd8f590b6eee_0 - noVNC](https://user-images.githubusercontent.com/8517736/104421273-6d6b0280-557b-11eb-9afd-43d31759eb63.png)

Insert Tab
![2021-01-13 08_41_04-ws-e0f5a3a5-2ec4-4203-9c60-fd8f590b6eee_0 - noVNC](https://user-images.githubusercontent.com/8517736/104421217-5af0c900-557b-11eb-856e-0a993deed2b8.png)

How can we reduce the height of the Home Tab? I think in calc the issue is even bigger.

**Comment by Andreas-Kainz** [comment]
@eszkadev in control.notebookbarwriter.js all widgets has id names, can we make there custom settings for padding, ... @pedropintosilva 

I think the main issue is that .cell.notebookbar where there is 2px padding and when there is an empty .cell.notebookbar it has also this 2px which I will overwrite with the css file.

**Comment by eszkadev** [comment]
in one week I think, it will be doable to edit all tabs even Home tab (I'm working on it currently)

**Comment by Andreas-Kainz** [comment]
Thanks for the feedback. I hope I can wait. Let me know when it's done.

**Comment by Andreas-Kainz** [comment]
fixed
