### ISSUE TITLE
Kit - dumpState

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#1234]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @mmeeks 

### Detailed description and rationale
When we give a 'USR1' signal to any of our processes we try to dump their internal state to the console. This really helps when a process has got stuck for some reason, or is consuming lots of resources. Unfortunately, we don't dump all of our state - which is not ideal.

### Code pointers
kit.Kit.cpp in the 'dumpState' method. There is a long list of TODOs there that may help eg.

        // TODO: PngCache _pngCache;
To do this - we want to add a 'dumpState' method onto the PngCache class - and call that method:
_pngCache.dumpState(os);

And then in the PngCache dump any class members that look helpful =)

### Links to related documentation
checkout the C++ output streams, this '<<' overload is a bit of a 'cute' way to print things.

To test do:

$ make run
$ ps auwx | grep loolforkit # and do a:
$ kill -USR1 <pid> # usually of the 2nd forkit process - which is the 'live' one

Thanks !

**Comment by 22shubh22** [comment]
For PngCache class, what are the members which seem useful?
I see only CacheData as helpful.
