### ISSUE TITLE
[CODE 6.4.3.1] impossible to pass multiple dictionaries to the Docker container

### ISSUE THREAD

**Issue by craue** [CollaboraOnline/online#1235]
**Describe the bug**
With `collabora/code:6.4.2.2`, passing multiple dictionaries (as mentioned on https://www.collaboraoffice.com/code/docker/) worked fine, but with `collabora/code:6.4.3.1`, only the first will take effect.

**To Reproduce**
run `collabora/code:6.4.3.1` with `-e "dictionaries=de en"`
(I'll use "collabora" as container name from here on.)

**Expected behavior (as-is with collabora/code:6.4.2.2)**
```sh
> docker logs collabora 2>&1 >/dev/null | grep "Whitelisted languages"
Whitelisted languages: de en
```

**Actual behavior (with collabora/code:6.4.3.1)**
```sh
> docker logs collabora 2>&1 >/dev/null | grep "Whitelisted languages"
Whitelisted languages: de

> docker logs collabora 2>&1 >/dev/null | head -n 1
start-collabora-online.sh: line 42: [: de: binary operator expected
```

**Comment by mmeeks** [comment]
How are you setting that environment variable; I would expect -e "dictionaries='de en'" - ie. using individual quites to group those so they are a single string surely (?) =)

**Comment by craue** [comment]
@mmeeks, I tried several quoting strategies, with your example resulting in this...
```sh
> docker logs collabora 2>&1 >/dev/null | grep "Whitelisted languages"
Whitelisted languages: 'de
```

**Comment by timar** [comment]
we have two options.
1. revert to the old behaviour of manipulating the loolwsd.xml
2. circumvent crazy shell escapes somehow.

`--o:allowed_languages=de hu en` -- wrong
`'--o:allowed_languages="de' hu 'en"'` -- wrong

I had no luck with backslash escapes spaces either.

**Comment by timar** [comment]
we have two options.
1. revert to the old behaviour of manipulating the loolwsd.xml
2. circumvent crazy shell escapes somehow.

`--o:allowed_languages=de hu en` -- wrong
`'--o:allowed_languages="de' hu 'en"'` -- wrong

I had no luck with backslash escapes spaces either.

**Comment by timar** [comment]
I reverted the wrong commit. It's better not to break existing documentation, and I could not solve the shell escape problem easily.
