### ISSUE TITLE
recent update breaks access to collabora

### ISSUE THREAD

**Issue by pieter-groeneweg** [CollaboraOnline/online#1246]
After updating the day before yesterday, collabora is not accessible anymore.
One server it cannot start.
Second server it is running but not accessible.

Strange is that since day before yesterday there were two new updates available for loolwsd.
Neither update did resolve

Expected would be a running loolwsd.service and collabora being available at least from ip:9980

Server with non running service is a debian10/webmin/virtualmin
Server with running service but still not accessible is a debian 9/webmin/virtualmin
Both intel 64 bit

Collabora was running fine before (already for years on the debian 9)

Odd thing is that both logs complain the access to the ssl.ca file is denied... a ca file which was and should still be accesible as nothing changed there.
Changing permissions to the max doesn't even resolve. User lool is member and has full permissions to the folder with the cert files.

this is a collabora install, no docker.

I am clueless... can someone shine some light? Tx.

**Comment by mmeeks** [comment]
Hi Pieter - can you report which version you upgraded from and to ? Sounds horrible, sorry for the issue.

**Comment by pieter-groeneweg** [comment]
Hi Michael, this was a 6.4.1 now on 6.4.3 (loolwsd that is)
though that was updated way back from 6.0 which was, even more far away in history, updated from 5.3

As mentioned, these are no docker installations. 

loolwsd.xml with unchanged.

for some odd reason it seems not to be able to access the ssl.ca file while the other ssl files which are above the ca in the xml show no problems...

user for collabora is lool, user for the hosts file is collabora... collabora has the ssl files, lool is made member with all permissions to collabora group.
I already rechecked all of that and there is no issue there... "lool" can access "collabora" just fine

**Comment by pieter-groeneweg** [comment]
In addition.. I checked again.
user lool has access to the folders of collabora
permissions are set correct.
still don't work unless I copy all certs to /etc/loolwsd/ folder...
for some reason after updating it doesn't accept any other folder but /etc/loolwsd/ for the certs to be stored.

next thing I don't know if it is related, i have a subdomain share-20.domain.com as a connecting host (nextcloud)
which was escaped share/-20/.domain/.com

Discovered this no longer works but did before the updates. This maybe related? As it is how te xml is read, interpreted and settings are executed?

**Comment by mmeeks** [comment]
Interesting - perhaps Andras has some insight; thanks for reporting!

**Comment by thebearon** [comment]
> user lool has access to the folders of collabora
> permissions are set correct.
> still don't work unless I copy all certs to /etc/loolwsd/ folder...
> for some reason after updating it doesn't accept any other folder but /etc/loolwsd/ for the certs to be stored.

The logs should state the reason why reading the certificates failed, if they claim it is an access problem, that is the case. Eg. it could be intermediate directories that are inaccessible to user lool.

> next thing I don't know if it is related, i have a subdomain share-20.domain.com as a connecting host (nextcloud)
> which was escaped share/-20/.domain/.com
> 
> Discovered this no longer works but did before the updates. This maybe related? As it is how te xml is read, interpreted and settings are executed?

The domain should be dot-escaped with backslashes, and should look like this: `share-20\.domain\.com`

**Comment by pieter-groeneweg** [comment]
> The logs should state the reason why reading the certificates failed, if they claim it is an access problem, that is the case. Eg. it could be intermediate directories that are inaccessible to user lool.

Then why after an update to collabora it is an issue where it wasn't an issue before the update? No changes to user/groups have been made

> The domain should be dot-escaped with backslashes, and should look like this: share-20\.domain\.com

Sorry my typo in previous post... they are escaped \ 
But losing the \ before the minus did help..  still that worked before with an escaped minus

**Comment by Ezinnem** [comment]
@pieter-groeneweg, please can you update to the recent version and check if the issue still occurs?

**Comment by Ezinnem** [comment]
Closing this issue due to no response from the author.
