### ISSUE TITLE
Can't open link or copy content from read-only document

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#1248]
When I open an online document via link like the weekly online meeting minutes
https://staging.eu.collaboraonline.com/nextcloud/index.php/s/GSDfzkyByigDHQ5 
why it's not possible to open an link OR to copy stuff?

**Comment by thebearon** [comment]
This is because the document is read-only, but you are right, being able to do those would be very useful.

On a sidenote, eg. not being able to copy content might be a useful restriction in some cases (if it could be controlled).

**Comment by ferdiga** [comment]
A year has gone and the enhancement is still "open" and annoying missing feature

**Comment by Andreas-Kainz** [comment]
So it's good to bring the issue up again. Thanks

**Comment by ferdiga** [comment]
and copy/past should also be enabled - it's currently "view only"

**Comment by pedropintosilva** [comment]
the hyperlink situationon NC shared links has been fixed with https://github.com/nextcloud/richdocuments/issues/1444 . For any further discussion around the enablement of selections and copy within read-only mode: please head over to https://github.com/CollaboraOnline/online/issues/4914

**Comment by RainerBielefeld** [comment]
Well, it would be useful if some devs would handle this bug instead of pointing around in a circle to alleged bug fixes.
