### ISSUE TITLE
Comments appear again after resolving/deleting thread and re-opening document

### ISSUE THREAD

**Issue by RegisPerdreau** [CollaboraOnline/online#1250]
Version
6.4.3 loolwsd

6.4.19 lokit

**Step to reproduce :**

1. Insert comment
2. Resolve comment or thread : it disappears
3. Close document (with or without force save)
4. Re-open document

**Expected behavior**

The comment should stay hidden/invisible

**Actual behavior**

The comment re-appears

**Comment by vmiklos** [comment]
This is also reported at https://bugs.documentfoundation.org/show_bug.cgi?id=136861, I'll take a look.

**Comment by vmiklos** [comment]
https://github.com/LibreOffice/core/commit/df8a65e3b5b4a4e9213450407c08c74503f36a29 is meant to fix this.
