### ISSUE TITLE
The display jumps to the first page when multiple users are editing

### ISSUE THREAD

**Issue by RegisPerdreau** [CollaboraOnline/online#1251]
Version :
6.4.3 loolwsd
6.4.19 lokit

**Step
to reproduce :**

1. Load multiple pages document in Writer and scroll to page 2 or
others

2. Begin to edit together, add some text to other pages

**Expected behavior**

The display stays where you are when editing. No jump or scroll.

**Actual behavior**

The display jumps to page 1.

**Comment by dan-elevate** [comment]
i have noticed that problem too, very annoying

**Comment by Ezinnem** [comment]
This issue seems to have been fixed.

It is not reproducible on Share 6.4.10snapshot (git hash: [b373871](https://github.com/CollaboraOnline/online/commits/b373871)).
