### ISSUE TITLE
notebookbar JSON

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#1257]
The idea is to use the JSON implementation of notebookbar from online in core.
The goal of the JSON implementation is:
- simple text file for easier maintenance
- reuse of JSON parts in other libo apps
- extension support like in toolbar available

**Comment by Andreas-Kainz** [comment]
I would suggest to rework all Notebook stuff in online and when done bring it to core. So we can start with the already available stuff from online and have to be in mind only core.

**Comment by Andreas-Kainz** [comment]
**Simplify existing JSON: uno command section**

```
'id': 'saveas',
'type': 'bigtoolitem',
'text': _UNO('.uno:SaveAs', 'text'),
'command': '.uno:SaveAs' 
```

change to
```
'type': 'bigtoolitem',
'command': '.uno:SaveAs' 
```

id:     is by default the name of the .uno: command, so no need to add an id
text:  come from the .uno: command so only needed when overwrite the .uno: command string

**Comment by Andreas-Kainz** [comment]
**Simplify existing JSON: structure section**

```
'id': 'Section2',
'type': 'toolbox',
'text': '',
'enabled': 'true',
```

change to

```
'type': 'toolbox',
```

**id:** is by default the name of ALL .uno: command within the structure, can be user defined for example to reuse part of the structure somewhere else.
**enable:** is by default true so only needed when enable: false
**text:** by default text is empty so only added when text is needed.

**Comment by eszkadev** [comment]
this is exactly what I'm doing currently in : https://github.com/CollaboraOnline/online/pull/1254

**Comment by Andreas-Kainz** [comment]
Great. I also want to have an issue tracker if there is stuff to discuss.

**Comment by Andreas-Kainz** [comment]
> 
> 
> **Simplify existing JSON: uno command section**
> 
> ```
> 'id': 'saveas',
> 'type': 'bigtoolitem',
> 'text': _UNO('.uno:SaveAs', 'text'),
> 'command': '.uno:SaveAs' 
> ```
> 
> change to
> 
> ```
> 'type': 'bigtoolitem',
> 'command': '.uno:SaveAs' 
> ```
> 
> **id:** is by default the name of the .uno: command, so no need to add an id
> **text:** come from the .uno: command so only needed when overwrite the .uno: command string

would it be possible to have ONLY
'command': '.uno:SaveAs' 
cause 'type:bigtoolitem' or 'type:menuitem' or 'type:toolitem' is implementation stuff which for example I as an designer didn't know so have only the uno: command would reduce the notebookbar.js file to list the commands and somewhere else there is the information how to get the uno: command. The size (bigtoolitem or toolitem) should be done somewhere else in a more generic way. For example if there is only one command it will show as 32px icon + bottom label if there are two commands it will be 24px icon + right label.

**Comment by pedropintosilva** [comment]
@Andreas-Kainz I understand your worries but I would rather have extra valuable information within the JSON like the type of tooltiem instead of delegating it 100% to the code part. By keeping the type in JSON everyone including designers get to play, test and change the type of tooltip without hunting it in the code or messing something else. It also provides any user,/customer , integration to have a more direct access to that as well.

**Comment by eszkadev** [comment]
BTW @Andreas-Kainz @pedropintosilva I would like to ask you to not change our JSONs in master branch for a while (until I will push https://github.com/CollaboraOnline/online/pull/1254) to avoid conflicts.

**Comment by Andreas-Kainz** [comment]
In the past I switch 'type:menuitem' to 'type:bigtoolitem' which cause a problem but you can switch 'type:toolitem' to 'type:bigtoolitem' without problems.

The generic setting for the notebookbar (that if there is only one command it will look like this, ...) should be an easy to read and edit separate file, so that it would be very easy to switch between for example notebookbar and notebookbar_compact which can than use the same source files with different generic settings.

**Comment by eszkadev** [comment]
I have plan to unify all items to be just 'toolitems' as I will be able to write algorithm which will always promote single items into 'bigtoolitems', and I will remove need for using 'menutoolitem'

**Comment by kendy** [comment]
@Andreas-Kainz: Thanks for looking into this!

I'd like to see the JSON minimized to whatever is the minimal thing possible, so 'command': '.uno:SaveAs' is perfect from that point of view. But indeed, interested to see that you don't think the size should be defined directly - what if you have a command that can show as small in one tab, but big in another one?  Like if there is a context tab for eg. tables?

**Comment by kendy** [comment]
@Andreas-Kainz: But let's not be 3 people here telling you what to do :-) - if you can come up with a more complete JSON example here as a "this is what I'd like it to look like in the ideal world" that would be great.

**Comment by Andreas-Kainz** [comment]
I already start with an complete JSON structure, but than thought, it would be better, to start from the existing structure and minimize it, so it's easier to go step by step, but I wrote will also submit a complete JSON structure. In addition without discussion you wan't get a perfect solution ;-) .

**Comment by Andreas-Kainz** [comment]
this is an example of an JSON cleanup #1268. If stuff like id, visibility, ... is needed it can be added, but by default it's not shown.

```
{
  'type': 'container',
  'children': [
    {
      'type': 'toolbox',
      'children': [
        {
          'command': '.uno:InsertTable'
        }
      ]
    },
    {
      'type': 'toolbox',
      'children': [
        {
          'command': '.uno:InsertObjectChart'
        }
      ]
    },
  ]
},
{
  'type': 'separator'
},  
```

For Notebookbar layouts you need:
- type: container (for the structure)
- type: toolbox (for uno: commands)
- type: separator 

as 98 % you have only one uno: command in a toolbox it can be reduced to containers only.

On the desktop there is a separation between containers that can be hidden or are always visible. Therefore a property can be added to the container if it should be always visible.

**Comment by Andreas-Kainz** [comment]
For desktop (and maybe also for online) an ManagedMenuButton is needed which contain a GtkMenu. 

![2021-01-18 14_57_39-](https://user-images.githubusercontent.com/8517736/104924331-8faab900-599d-11eb-88f5-9481c568dbc2.png)


The GtkMenu use the same structure than Control.Menubar.js

![GtkMenu](https://user-images.githubusercontent.com/8517736/104923827-e794f000-599c-11eb-89c3-a651c78c3299.png)

**Comment by Andreas-Kainz** [comment]
> as 98 % you have only one uno: command in a toolbox it can be reduced to containers only.

Control.Notebookbar.js can be than simplyfied to:

```
{
  'type': 'container',
  'children': [
    {
      'command': '.uno:InsertGraphic'
    }
  ]
},
{
  'type': 'container',
  'children': [
    {
      'command': '.uno:InsertTable'
      'command': '.uno:InsertObjectChart'
    }
  ]
},
{
  'type': 'separator'
},  
```

![2021-01-18 15_08_29-ws-c3a797d1-e299-452d-a78e-b6a62d7d0140_0 - noVNC](https://user-images.githubusercontent.com/8517736/104925377-0eecbc80-599f-11eb-96cb-f493864d9d09.png)


special cases like in the home tab can look like this:

```
{
  'type': 'container',
  'children': [
    {
      'type': 'container',
      'children': [
        {
          'command': '.uno:CharFontName'
          'command': '.uno:FontHeight'
          'command': '.uno:Grow'
          'command': '.uno:Shrink'
      ]
    },
    {
      'type': 'container',
      'children': [
        {
          'command': '.uno:Bold'
          'command': '.uno:Italic
          'command': '.uno:Underline'
          'command': '.uno:Strikeout'
          'command': '.uno:SubScript'
          'command': '.uno:SuperScript'
          'command': '.uno:BackColor'
          'command': '.uno:Color'
      ]
    }
  ]
},  
```

![2021-01-18 15_09_04-ws-c3a797d1-e299-452d-a78e-b6a62d7d0140_0 - noVNC](https://user-images.githubusercontent.com/8517736/104925447-2330b980-599f-11eb-803d-1e422c583f54.png)

**Comment by Andreas-Kainz** [comment]
what would be nice, would be if there is less space (width) than commands will be collapes for example
from:
![2021-01-18 15_27_20-ws-c3a797d1-e299-452d-a78e-b6a62d7d0140_0 - noVNC](https://user-images.githubusercontent.com/8517736/104927446-b9fe7580-59a1-11eb-9571-ce98204ff065.png)
to:
![2021-01-18 15_27_33-ws-c3a797d1-e299-452d-a78e-b6a62d7d0140_0 - noVNC](https://user-images.githubusercontent.com/8517736/104927452-bcf96600-59a1-11eb-97f5-5b45e32852c1.png)

In this example you can say
if width is available show { uno:leftpara; uno:centerpara; uno:rightpara; uno:justifypara }
else { uno:textalign }

**Comment by eszkadev** [comment]
> > as 98 % you have only one uno: command in a toolbox it can be reduced to containers only.
> 
> Control.Notebookbar.js can be than simplyfied to:
> 
> ```
> {
>   'type': 'container',
>   'children': [
>     {
>       'type': 'separator',
>       'command': '.uno:InsertGraphic',
>     }
>   ]
> },
> {
>   'type': 'container',
>   'children': [
>     {
>       'command': '.uno:InsertTable',
>       'command': '.uno:InsertObjectChart',
>     }
>   ]
> },
> ```
> 
this is not a correct JSON, you can['t have multiple 'command' properties in one node. it has to be split:
`{
command: 'a'
},
{
command: 'b'
}`

**Comment by eszkadev** [comment]
> what would be nice, would be if there is less space (width) than commands will be collapes for example
> from:
> ![2021-01-18 15_27_20-ws-c3a797d1-e299-452d-a78e-b6a62d7d0140_0 - noVNC](https://user-images.githubusercontent.com/8517736/104927446-b9fe7580-59a1-11eb-9571-ce98204ff065.png)
> to:
> ![2021-01-18 15_27_33-ws-c3a797d1-e299-452d-a78e-b6a62d7d0140_0 - noVNC](https://user-images.githubusercontent.com/8517736/104927452-bcf96600-59a1-11eb-97f5-5b45e32852c1.png)
> 
> In this example you can say
> if width is available show { uno:leftpara; uno:centerpara; uno:rightpara; uno:justifypara }
> else { uno:textalign }

this is implementation detail which will be implemented depending on a platform. Gtk3 does that thing with toolboxes, in case there is no space it shows an arrow with popup.

**Comment by kendy** [comment]
> this is not a correct JSON, 

Let's not nitpick about the syntax, I'm much more interested in the structure & semantics :-)

@andeas-kainz: This container with orientation horizontal / vertical + separators looks good in general.  But I wonder if you need also some synchronization of the form that some items should be below each other; and stuff like that?

Also what about some priorities of the buttons - that we could hide the less important ones when shrinking the notebookbar?

And last - there are (or should be) buttons leading to dialogs that allow to set everything; should we specify them from here too?

**Comment by Andreas-Kainz** [comment]
> this is not a correct JSON, you can['t have multiple 'command' properties in one node. it has to be split:
> `{ command: 'a' }, { command: 'b' }`

good point, in addition as there should be options available for text: icon: (in addition to .uno:) if needed it would be better to have `'type': 'toolbox'` for each uno: command.

**Comment by Andreas-Kainz** [comment]
> @andeas-kainz: This container with orientation horizontal / vertical + separators looks good in general. But I wonder if you need also some synchronization of the form that some items should be below each other; and stuff like that?

This will be done by an config file where "template layouts" will be stored like:

**notebookbar.config**

![2021-01-18 15_08_29-ws-c3a797d1-e299-452d-a78e-b6a62d7d0140_0 - noVNC](https://user-images.githubusercontent.com/8517736/104925377-0eecbc80-599f-11eb-96cb-f493864d9d09.png)
```
{
'type': 'toolbox',
  'children': [
    {
      'type': 'bigtoolitem',
      'command': '.uno:xxx',
    }
 ]
}
```
```
{
'type': 'container',
  'children': [
    {
      'type': 'container',
      'children': [
        {
          'type': 'toolbox',
          'children': [
            {
              'type': 'toolitem',
            }
          ]
        },
        {
          'type': 'toolbox',
          'children': [
            {
              'type': 'toolitem',
            }
          ]
        }
      ],
      'vertical': 'true'
    }
],
}
```

**notebookbar_compact.config**
![ImageTableChart](https://user-images.githubusercontent.com/8517736/105098746-d803cd00-5aaa-11eb-972f-5a3d6380a90b.png)
type: switch from bigtoolbox to toolbox and vertical: true to false the JSON file will be 100 % the same.
```
{
'type': 'toolbox',
  'children': [
    {
      'type': 'toolitem',
      'command': '.uno:xxx',
    }
 ]
}
```
```
{
'type': 'container',
  'children': [
    {
      'type': 'container',
      'children': [
        {
          'type': 'toolbox',
          'children': [
            {
              'type': 'toolitem',
            }
          ]
        },
        {
          'type': 'toolbox',
          'children': [
            {
              'type': 'toolitem',
            }
          ]
        }
      ],
      'vertical': 'false'
    }
],
}
```

**Comment by Andreas-Kainz** [comment]
## Shrinking

> Also what about some priorities of the buttons - that we could hide the less important ones when shrinking the notebookbar?

I prefer the idea in COOL where you can scroll instead of hide stuff into a dropdown item like in LibreOffice desktop.

### Option 1:
However there can be an if enough space show 4 command's else show 1 command with drop-down.

### Option 2:
There can be also an if enough space in the config file where uno: commands will show icon + label and when there is less space the layout switch to icon only. As the config file define the template layout this can be done for each single template label. Like:

![ImageTableChart2](https://user-images.githubusercontent.com/8517736/105100085-0da9b580-5aad-11eb-8d4f-70b4cdac21e1.png)

```
{
'type': 'container',
  'children': [
    {
      'type': 'container',
      'children': [
        {
          'type': 'toolbox',
          'children': [
            {
              IF (less width) {
                'type': 'icononly',
              }
              ELSE {
                'type': 'toolitem',
              }
            }
          ]
        },
        {
          'type': 'toolbox',
          'children': [

            {
              IF (less width) {
                'type': 'icononly',
              }
              ELSE {
                'type': 'toolitem',
              }
            }
          ]
        }
      ],
      'vertical': 'false'
    }
],
}
```

### Option 3:
Another option is that commands that didn't fit into the window width, will move automatic into a ManagedMenuButton which a GtkMenu. 

![2021-01-18 14_57_39-](https://user-images.githubusercontent.com/8517736/104924331-8faab900-599d-11eb-88f5-9481c568dbc2.png)

### Note:
Priority every time from right to left. NO user defined priority stuff.

**Comment by Andreas-Kainz** [comment]
## Open Dialogs

> And last - there are (or should be) buttons leading to dialogs that allow to set everything; should we specify them from here too?

In LibreOffice I implemented this with a three dot's icon which will than open the dialog depend on the section.

![dots](https://user-images.githubusercontent.com/8517736/105101211-cc1a0a00-5aae-11eb-89a3-d9b600092cc6.png)

This has the benefit that the layout wasn't disturbed by all the different dialogue icons but the dialogues are near the commands of the specific dialog group. MSO use three dot's for swap commands that didn't have space. I prefer open the dialog, cause in the dialogues ALL stuff can be edited.

If you design the three dot's well, you can use them as a separator.

From dev point of view the three dot's are the .uno: command with an user specific icon
```
  'command': '.uno:FontDialog',
  'icon': 'open_more.svg'
```

**Comment by eszkadev** [comment]
> I prefer the idea in COOL where you can scroll instead of hide stuff into a dropdown item like in LibreOffice desktop.
> ### Option 1:
> 
> However there can be an if enough space show 4 command's else show 1 command with drop-down.

doable. for example 'toolbox' in gtk3 has this feature, we could do the same for 'toolbox' in online

> 
> ### Option 3:
> 
> Another option is that commands that didn't fit into the window width, will move automatic into a ManagedMenuButton which a GtkMenu.
> 

I can only imagine that moving things from place to another will be extremly hard to implement, and probably not doable in the same way in desktop and online

**Comment by eszkadev** [comment]
so short summary for now:
we will use minified JSON and we need elements like :
- single item: `{type: 'bigitem', uno: '.uno:xxx', icon: 'xxx.svg'}`
- container: `{type: 'container', vertical: true, children: [ ... ]}`
- toolbox which in case of no space shows items in dropdown: `{ type: 'toolbox', children: [ ... ] }`
- menu button: `{type: 'menu', children: [ {uno: 'menuItemCommand'} ... ] }`

what else? @Andreas-Kainz ? :)

**Comment by Andreas-Kainz** [comment]
type: 'separator'

maybe hidden possible or not (so some commands are always visible)

**Comment by Andreas-Kainz** [comment]
>     * menu button: `{type: 'menu', children: [ {uno: 'menuItemCommand'} ... ] }`

It's importend that it's possible to list instead of the single commands, the link to an separate JSON file (which can be reused for menubar also).

**Comment by Andreas-Kainz** [comment]
>     * container: `{type: 'container', vertical: true, children: [ ... ]}`

and you can have container within a container isn't it?

**Comment by eszkadev** [comment]
> and you can have container within a container isn't it?

yes, inside `children: [ .. ]`
 we can put anything we want

**Comment by Andreas-Kainz** [comment]
> > I prefer the idea in COOL where you can scroll instead of hide stuff into a dropdown item like in LibreOffice desktop.
> > ### Option 1:
> doable. for example 'toolbox' in gtk3 has this feature, we could do the same for 'toolbox' in online

cool, but shouldn't be the first preference, cause global structure is more importand. 

> > ### Option 3:
> I can only imagine that moving things from place to another will be extremly hard to implement, and probably not doable in the same way in desktop and online

Ok no problem, than don't care about this. We can do it with menu button (and show there all commands), that's fine.

**Comment by Andreas-Kainz** [comment]
everything is possible with the defined structure from @eszkadev. 

The only question is how to define where to hide stuff. Ordinary it's from right to left - I prefer the mobile solution - but when there are on the right elements that should be always visible, than we need therefore an solution like `visible: 'always'` for the container.

![notebookbar](https://user-images.githubusercontent.com/8517736/105351173-7c415d00-5bec-11eb-9b46-358035d7df52.png)

**Comment by eszkadev** [comment]
> ### Option 1:
> 
> However there can be an if enough space show 4 command's else show 1 command with drop-down.

![nbgtk](https://user-images.githubusercontent.com/5307369/105627596-19dc9c80-5e38-11eb-8777-08714ae4b3e2.gif)

this is how the shrinking will look in native gtk3 backend

**Comment by eszkadev** [comment]
@Andreas-Kainz on the last meeting you said it would be good to have one JSON with list of comands and it will be "converted" to multiple different layouts like: tabbed layout, compact tabbed layout, menubar structure.
After some thinking I think it is a great idea! So lets define JSON with content only but layout will be not described there (will be generated by the code). This will simplify our JSON, we will not need 'container' with 'vertical: true' property, we will not need toolboxes. Layout strategies will automatically generate vertical containers for us if needed. Instead we will split commands into logical sections. eg.:
```
{
    type: group,     <- will represent a 'tab'  or  menu in menubar
    title: File,
    children: [
        {
            type: section     <- will group similar items, will represent submenu in menubar, or group separated by separator in tabbed notebookbar
            title: 'File operations'
            children: [
                { uno: Open, size: big },     <- big item will have height 2 rows in tabbed layout, other layouts ignore this
                { uno: Save },                     <- other items are split into 2 rows in tabbed layout, other layouts ignore this
                { uno: SaveAs }
            ]
        },
         {
            type: section,
            title: 'Export'
            children: [
                { uno:ExportODT, title: 'Export as odt' },
                { uno:ExportDOC, title: 'Export as doc' },
                { uno:ExportRTF, title: 'Export as rtf' }
                ... many more items
            ]
        }
    ]
}
```

it will result in:
1) Menu layout
```
+ File
     + Open        < first section has only 3 items so don't create submenu (example rule, can be different :) )
     + Save
     + SaveAs
     + Export
          +  Export as Odt
          +  Export as Doc
          +  Export as RTF
          + ...
```

2) Tabbed layout
```
| File tab | ...
             Save      |   Export as ODT      Export as RTF      ...       |
Open                   |                                                   |
             Save As   |    Export as DOC      Export as .....       ...   |
```

3) Compact Layout
```
| File tab | ...
Open   Save   SaveAs  |  Export as ODT   Export as DOC   Export as RTF   ... | ...
```

So JSON is one and the same, we use only different layout strategies (programmed in the code) to show in a different layout

**Comment by Andreas-Kainz** [comment]
> @Andreas-Kainz on the last meeting you said it would be good to have one JSON with list of comands and it will be "converted" to multiple different layouts like: tabbed layout, compact tabbed layout, menubar structure.

thumb up; I'm not 100 % sure if menubar structure has be the same structure, but if possible, why not.

> After some thinking I think it is a great idea! So lets define JSON with content only but layout will be not described there (will be generated by the code). This will simplify our JSON, we will not need 'container' with 'vertical: true' property, we will not need toolboxes. Layout strategies will automatically generate vertical containers for us if needed. Instead we will split commands into logical sections. eg.:

perfect also the structure. For `size: big` there have to be a second option within the notebookbar.css file to respect that online didn't have all commands than desktop so some commands are hidden online so the layout from the other command has to be big.

**Comment by Andreas-Kainz** [comment]
I would remove NB-default blocker label, cause this is a new, simplier implementation of the NB json file structure. As all json files are already updated, it should be easier to simplify it for szymon.

**Comment by Andreas-Kainz** [comment]
Do we need this issue?

in general it's more an LibO issue, cause in cool I think the json file is not to complicated.

**Comment by Darshan-upadhyay1110** [comment]
This enhancement request is now in COOL. We can close this thread. 
CC: @Andreas-Kainz @eszkadev @pedropintosilva
