### ISSUE TITLE
Docker image fails with double escaped domain.

### ISSUE THREAD

**Issue by tobiasKaminsky** [CollaboraOnline/online#1264]
Nextcloud shows:
```
docker run -t --name collabora -d -p 127.0.0.1:9980:9980 -e 'domain=nextcloud\\.cloud\\.com' -e 'username=admin' -e 'password=123123' --cap-add MKNOD collabora/code
```
to start Collabora server.

With recent Collabora version, we need to start it via:
- `-e "domain=nextcloud\\.cloud\\.com`
- `-e 'domain=nextcloud\.cloud\.com`

Both ways are "new" and existing upgrade/installation routines are therefore not working.
Is there a chance to have the old way back?

It seems to be related to https://github.com/CollaboraOnline/online/commit/93dfff7dadeaf93a2b196fc41c23f3a5f4025aaa

**Comment by juliushaertl** [comment]
One addition, previous documentations seem to mention single quotes with a double escaping `-e 'domain=nextcloud\.cloud\.com'` which is what is assumed that the mentioned commit has changed to be no longer working:

**Comment by timar** [comment]
I reverted the wrong commit. It's better not to break existing documentation, and I could not solve the shell escape problem easily.
