### ISSUE TITLE
Action menu and keyboard overlapping 

### ISSUE THREAD

**Issue by nabilys** [CollaboraOnline/online#1277]
**Describe the bug**
With collabora recent menu changes, I get the keyboard overlapping action menu. 

**To Reproduce**
1. Start editing a document (keyboard on screen
2. Tap a menu element in the top left bar (for example font editing)

**Expected behavior**
The keyboard should hide when selecting a menu
There should be a button to easily hide the keyboard

**Actual behavior**
The keyboard doesn’t hide if a menu is selected

**Screenshots**
![B84F0E50-7DBD-44FA-842F-315059B2C8AF](https://user-images.githubusercontent.com/59312735/105023044-c38fe800-5a4a-11eb-9dde-e77de08d1230.jpeg)

**Smartphone**
 - Device: iPhone XS 
 - OS: iOS 14.3
 - Language : French
 - Version: 6.4.4 (1)

**Comment by Ezinnem** [comment]
This issue described does not occur in the Collabora Office 6.4.9 test version.

**Comment by Ezinnem** [comment]
This issue is not reproducible in the recent Collaobra Office 6.4.13 (git hash: [255f42ff](https://github.com/CollaboraOnline/online/commits/ [255f42ff)).
