### ISSUE TITLE
Propagate the new log level to the WSD children including forkit

### ISSUE THREAD

**Issue by mrkara** [CollaboraOnline/online#129]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @gokaysatir

There has been some improvements to _AdminConsole: control logging_ by the commit ac682772a6edf4045371670552a9c831623d45f4

For bonus points, we should really propagate this to all the _WSD_ children too including the _forkit_ - but that is a fair bit of protocol work & tweaking =)

Thanks !

**Comment by gokaysatir** [comment]
I was eager to solve this one :) Since it is not assigned on Hacktoberfest :)

https://github.com/CollaboraOnline/online/pull/900
