### ISSUE TITLE
Select Table has strange gray elements

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#1297]
see screenshot

![Screenshot_20210121_155525](https://user-images.githubusercontent.com/8517736/105367866-35aa2d80-5c01-11eb-80d7-bb7158d272d7.png)

**Comment by Andreas-Kainz** [comment]
how should it look like?

**Comment by pedropintosilva** [comment]
Very good catch @Andreas-Kainz ! thanks to you report, even though not directly related, I found out that those markers are not working they are supposed to be clickable. I already found where the regression came from and I will try either to revert back completely or partly with some adjustments. 

Meanwhile and answering to your question, these should definitely be improved, They were suppose to be a quick way to select a whole row or column and the same commit that added the regression also enlarged that svg to be more touch friendly. This is how it looked before:
![image](https://user-images.githubusercontent.com/65948705/105496580-f4c41e80-5cbd-11eb-84ff-8ca1b7244afe.png)

Either way that svg needs 1. improvement/redraw for sure. And on top of that needs more 2. status, at very least is missing hover and focus status as you see in the image. Do you want to take that task?

**Comment by Andreas-Kainz** [comment]
I don't think that the gray elements are easy enough to understood.

**Comment by Andreas-Kainz** [comment]
some ideas maybe you like one

![Screenshot_20210123_004622](https://user-images.githubusercontent.com/8517736/105560578-7181e780-5d14-11eb-9282-77521fed0a4a.png)
