### ISSUE TITLE
Incorrect encoding detection

### ISSUE THREAD

**Issue by xklonx** [CollaboraOnline/online#1309]
**Describe the bug**
Try open this file in collabora, i see only questions instead of cyrillic text.
looks like its 1251 encoding
[текстовик с кириллицей внутри.txt](https://github.com/CollaboraOnline/online/files/5862668/default.txt)

**Expected behavior**
Text showed up correctly as if it was utf8

**Actual behavior**
Question marks instead of text

**Screenshots**
![image](https://user-images.githubusercontent.com/9824966/105636890-7f9e4800-5e7b-11eb-9e5b-e23c70b3d112.png)

**Desktop (please complete the following information)**
 - OS: win10
 - Browser: chrome
 - Version: 87.0.4280.141

**Comment by thebearon** [comment]
This is rather a case of missing UI so the user can choose encoding for text files without BOM.

**Comment by rloutrel** [comment]
... alternatives to:
* @xklonx suggestion: automatic detection
* @thebearon suggestion: manual selection while opening

The possibility to reopen file with encoding selection is also possible (sometimes, we notice after opening the file and it might avoid a pre-rendering like in libreoffice flow to provide the functionality earlier)

**Comment by Darshan-upadhyay1110** [comment]
![image](https://github.com/user-attachments/assets/b4cbdd92-7817-4ef7-bb49-6ad949dd27cf)


COOLWSD version: 24.04.6.1 (git hash: 9dfee827)
LOKit version: Collabora OfficeDev 24.04.6.1 (git hash: 8b00f3a)
Served by: Ubuntu 23.10
Server ID: 83043426
