### ISSUE TITLE
iOS App: Impress: Sidebar is empty

### ISSUE THREAD

**Issue by smirta** [CollaboraOnline/online#1322]
**Describe the bug**
Sidebar is empty. Select and de-select the sidebar doesn't change anything.

**To Reproduce**
1. Open/Create a presentation
2. Select sidebar top right

**Expected behavior**
Sidebar with tools appears.

**Actual behavior**
Sidebar appears but is empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/6649852/105742401-c0f62c80-5f3b-11eb-8a20-7ad6f47dd157.png)

**iPad Pro**
 - iPad OS: 14.0.1
 - Collabora Office 6.4.5

**Comment by thebearon** [comment]
Thanks for reporting, this is a regression from the following commit: d37bad53f6258a1ad0bcf75bb45cdc85cfa477ec
@pedropintosilva, what are your thoughts?

**Comment by thebearon** [comment]
This is fixed in in build 6.4.5 (2). Thanks, @pedropintosilva!

**Comment by smirta** [comment]
I can confirm this as resolved in 6.4.5 (2). Thanks, guys!
