### ISSUE TITLE
Logging null pointer

### ISSUE THREAD

**Issue by mrslavutich** [CollaboraOnline/online#1342]
I implemented checkFileInfo and getFile rest endpoints for my integration, but I see unreadable error, namely 'null pointer' in the next line: 
Exception while loading url [file:///tmp/user/docs/ctJz8Pyj2hclUJcY/w2dROpKEtjbxJffsxyGfZyGuRQ4WkW8q] for session [197]: Null pointer| kit/Kit.cpp:961

There is a really poor description of the error.  I suggest describing a detail log of the problem, because it's tough to find out a reason.

**Comment by kendy** [comment]
@mrslavutich: Hello! Thank you for the report. What integration are you working on? Can you please let me know (even privately is fine if you don't want to share the information publicly)?

What CODE version are you using actually? We used to have a problem that when the CheckFileInfo didn't contain the UserFriendlyName property, we ended up with this null; but I thought @Ashod has fixed this one...

**Comment by mrslavutich** [comment]
it's 6.4.4.2. Thank you very much, document is rendering with the filled field "UserFriendlyName".
