### ISSUE TITLE
File extension is shown in filename textbox

### ISSUE THREAD

**Issue by xklonx** [CollaboraOnline/online#1383]
**Describe the bug**
I don’t know why anyone thought it was a good idea to display the file extension in a text box with the file name. The operation of renaming a file [does not imply](https://wopi.readthedocs.io/projects/wopirest/en/latest/files/RenameFile.html) changing the file extension, and this is not just that, because you cannot just change the file extension, it will stop opening. If you change the docx to docx2, the server eventually gets the name ....docx2.dot and its not just rename it is saving relative file converted to (surprise) odt, what kind of feature is that I do not understand at all.

I am in favor of removing the extension from the text field with the file name or displaying it grayed out but so that it cannot be changed.

**Comment by Ezinnem** [comment]
The file name with the extension is displayed such that the renaming of the file and the file conversion is simplified.

If a user has a  .odt file and changes the extension to .docx, the document will be converted to DOCX format.

**Comment by xklonx** [comment]
The problem is that the spec clearly says that the filename is sent without the extension.
https://wopi.readthedocs.io/projects/wopirest/en/latest/files/RenameFile.html
X-WOPI-RequestedName – A UTF-7 encoded string that is a file name, not including the file extension.
