### ISSUE TITLE
Rename file not working for pdf files

### ISSUE THREAD

**Issue by xklonx** [CollaboraOnline/online#1386]
**Describe the bug**
File rename not working for pdf files

**To Reproduce**
Open pdf file in viewer, UserCanRename and UserCanWrite true, try to change file name and press enter.
Nothing happens, wopi server not received rename request

**Expected behavior**
File succesfully renamed

**Actual behavior**
File is not renamed

**Desktop (please complete the following information)**
 - OS: win 10
 - Browser: chrome 88.0.4324.104 
 - Version: collabora 6.4.4

**Comment by Ezinnem** [comment]
The feature is available in the LOOLWSD n 6.4.10 snapshot (git hash: [4843b98](https://github.com/CollaboraOnline/online/commits/4843b98)).
