### ISSUE TITLE
Notebookbar: font size

### ISSUE THREAD

**Issue by dossantg** [CollaboraOnline/online#1411]
The new notebookbar is really good but the current font takes up a lot of space and overloads the display a little.

**Describe the solution you'd like**
One improvement might be to reduce the font size. 

**Additional context**
OS: Debian 10
Version: loolwsd 6.4.5

**Comment by pedropintosilva** [comment]
Thanks for reporting it @dossantg ! fixed: https://github.com/CollaboraOnline/online/issues/2002

**Comment by Andreas-Kainz** [comment]
check out #2235

### Home Tab After
![home-after](https://user-images.githubusercontent.com/8517736/116762594-28c88180-aa1b-11eb-9bd2-4ea3593b8494.png)
