### ISSUE TITLE
Push images for arm64

### ISSUE THREAD

**Issue by wreed4** [CollaboraOnline/online#1412]
I'm trying to run the docker images on a raspberrypi 4 and it seems it does not work.  I get 
```
exec format error
```

**Comment by wreed4** [comment]
I also seem unable to build it myself.. 
```
Executing: /tmp/apt-key-gpghome.lCWMRVY73m/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0C54D189F4BA284D
gpg: key 0C54D189F4BA284D: 1 signature not checked due to a missing key
gpg: key 0C54D189F4BA284D: public key "Collabora Productivity <libreoffice@collabora.com>" imported
gpg: Total number processed: 1                                                                           
gpg:               imported: 1                                                                           
Hit:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease          
Hit:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease     
Hit:3 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease              
Hit:4 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease                
Get:5 https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-ubuntu1804  InRelease [1728 B]
Get:6 https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-ubuntu1804  Packages [23.2 kB]
Fetched 24.9 kB in 2s (10.3 kB/s)                                                                        
Reading package lists...                                                                                 
Reading package lists...                                                                                 
Building dependency tree...                                                                              
Reading state information...                                                                             
Package loolwsd is not available, but is referred to by another package.    
This may mean that the package is missing, has been obsoleted, or            
is only available from another source                                                                    
                                                                                                                                                                                                                   
E: Package 'loolwsd' has no installation candidate                                                       
E: Unable to locate package collaboraoffice6.4-dict*                                                 
E: Couldn't find any package by glob 'collaboraoffice6.4-dict*'           
E: Couldn't find any package by regex 'collaboraoffice6.4-dict*'           
E: Unable to locate package collaboraofficebasis6.4-ar           
E: Couldn't find any package by glob 'collaboraofficebasis6.4-ar'                                        
E: Couldn't find any package by regex 'collaboraofficebasis6.4-ar'                                       
E: Unable to locate package collaboraofficebasis6.4-as           
E: Couldn't find any package by glob 'collaboraofficebasis6.4-as' 
E: Couldn't find any package by regex 'collaboraofficebasis6.4-as'
E: Unable to locate package collaboraofficebasis6.4-ast  
E: Couldn't find any package by glob 'collaboraofficebasis6.4-ast'  
E: Couldn't find any package by regex 'collaboraofficebasis6.4-ast'                                      
E: Unable to locate package collaboraofficebasis6.4-bg                  
E: Couldn't find any package by glob 'collaboraofficebasis6.4-bg'                  
E: Couldn't find any package by regex 'collaboraofficebasis6.4-bg'                  
E: Unable to locate package collaboraofficebasis6.4-bn-in
E: Couldn't find any package by glob 'collaboraofficebasis6.4-bn-in'                                     
E: Couldn't find any package by regex 'collaboraofficebasis6.4-bn-in'
E: Unable to locate package collaboraofficebasis6.4-br      
E: Couldn't find any package by glob 'collaboraofficebasis6.4-br'                                        
....
```

**Comment by RomainTT** [comment]
@wreed4 What’s your status ? I don’t understand why Collabora does not provide an image for ARM architectures yet. I’ve seen it has been asked for several years.

**Comment by wget** [comment]
@wreed4 Hi William (Oh, another William :) ). TL;DR: **Please wait, we are working on it.**

While you can find some images online built for ARM, even if they aren't labeled as it, these can be considered as development versions. We are not quite ready for prime time yet. So please consider ARM and ARM64 as unsupported architectures for the time being. 

But rest assured, we are coming and will be announcing support for this shortly :) Don't hesitate to follow us on our social media (e.g. [Twitter](https://twitter.com/CollaboraOffice)) or follow [our blog](https://www.collaboraoffice.com/news/) to know the first when this will be announced.

**Comment by wreed4** [comment]
thanks @wget (nice username :p )   this is good to know.  I'm happy waiting for the primetime, assuming it's weeks or months, not years :).  Do you happen to have any links to the dev versions though? I've been searching for days.  I'm trying to  use nextcloud with collabora on a handful or RaspberryPi's running a kubernetes cluster.  At this point, I'm really just trying to evaluate collabora as a gsuite replacement, but the only means I have is my rpi cluster.  If it has some issues, I'm okay for now, but it would be great to get it working. for the life of me, I cannot seem to in any configuration I find :laughing:

**Comment by yllekz** [comment]
Following, as I'm looking for a good Docker image for my Pi 4B that can do self-hosted document editing in a web browser.

**Comment by wget** [comment]
@wreed4 Haha ;P That's just my initials lightly tweaked to make it look like the UNIX command ^^

It's definitely **not** a story of years. Following how the commits go wrt. the ARM**64** port, that's definitely something for max. a few months.

@yllekz You can already try the [ARM64 port](https://apps.nextcloud.com/apps/richdocumentscode_arm64) although like said previously it is currently not ready for prime time and your mileage may vary. Also please note the link above is the **built-in server** which is best tailored for small structures/tests, etc., using a dedicated instance of Collabora Online (when it will be ready) is still the recommended way :) There is no ARM64 docker image port for now.

**Comment by wget** [comment]
We have been discussing this forum page in today's marketing talk: https://forum.collaboraonline.com/t/code-arm-aarch64-build/31

So the announcement is in the pipeline with the latest fixes coming along if applicable :)

**Comment by yllekz** [comment]
Thanks. Do you have any roadmap for arm32? The 64-bit Raspberry Pi OS is still new and not fully released as far as I am aware.

**Comment by mmeeks** [comment]
ARM32 is much more of a challenge, size-wise our binaries are quite large - and they really like to address a chunk of storage virtually - I don't believe we support x86 32bit either for this reason and the maintenance cost. Of course if someone wants to play with / get this setup and contribute their own images - we can help to promote them =)

**Comment by WhiteBahamut** [comment]
So the announcement for Collabora on ARM is out, any news on when the image gets arm(64) support? :)

**Comment by Thatoo** [comment]
Any update on this matter?

**Comment by timur-g** [comment]
This is old issue that started for arm64 - but it was out 2 years ago. So I close this. 
Thatoo opened the other issue referenced here.
