### ISSUE TITLE
Allow to update querystring based access_token

### ISSUE THREAD

**Issue by TijZwa** [CollaboraOnline/online#1416]
Hi,

My webapplication uses Collabora. 
The webapp user is authorizedby openid using Identity server with short-living token (1 hour lifetime).
The LoLeaflet is loading with the url https://%webserver%/%wopisrc%?access_token=%access_token% where %access_token% is received from the localStorage.
This works great, but if the access_token is already 50 mins old, the user can only use the freshly loaded document/LoLeaflet for 10 minutes.

With IdentityServer, the token is silently renewd in a iFrame.
I've added "updateaccesstoken %token%" to the protocol which allows the webapplication to push the new access_token to Collaboro using L.Map.THIS._socket.sendMessage("updateaccesstoken xyz") on the iFrame.

The implementation is kind of quick and dirty (https://github.com/TijZwa/online/commit/39315cb5c80ae06b45516e66e7492b04918e351b)

Is this something we want to have?

**Comment by kendy** [comment]
@TijZwa: Interesting, thanks for the patch! I wonder, did you also try to use the access_token_ttl? I'd guess it would be able to sort out your problem without having to use the message?

**Comment by TijZwa** [comment]
@kendy I've tried to solve this issue using the access_token_ttl, but all it does is show the user a message, stating that a refresh of the page is needed (to update the accesss token)
Thats kind of strange for my end-users because our access tokens are renewed silently in other applications.
