### ISSUE TITLE
iOS App: Writer, Calc & Impress: comment function does not work reliably while keyboard is already active

### ISSUE THREAD

**Issue by Gianni154** [CollaboraOnline/online#1432]
**Describe the bug**
If you insert a comment in any document (whether writer, calc or impress) via Notebookbar > Insert > Comment and then you click on the comment field while the keyboard is already active, it causes problems. It can cause the Collabora app to crash. When reproducing, my iPad even rebooted once.

**To Reproduce**

1. Open the Collabora iOS App
2. Open any document
3. Make sure that the keyboard is already displayed
3. On the notebookbar click on Insert
4. Click on Comment to open the comment dialog
5. Click on the comment field

**Expected behavior**
The comment field can be filled in and you can create a comment.

**Actual behavior**
Creating a comment is not possible. The keyboard has a strange behavior. It can crash the iOS Collabora app as well as the device itself (iPad). 

**Screenshots**

![comment](https://user-images.githubusercontent.com/78140364/107212482-50eda900-6a07-11eb-828d-b164061a0409.gif)

Unfortunately, you can't see in this GIF that the keyboard sometimes disappears. Below I have linked another video Google Drive. 
Link: https://drive.google.com/file/d/1Osk-BACANK5AZ0xg7CYIt0yN_LTTugK5/view

**Device**
 - iPad OS 14.4
 - iPad 6th generation
 - iOS Collabora App Version 6.4.5 (2)

**Comment by tml1024** [comment]
Yep, can reproduce in a fresh build. Keyboard-related bugs are in general complicated, so this might be hard to fix.

**Comment by tml1024** [comment]
Note to self: If the on-screen keyboard is displayed when you tap the "Comment" button, you can't type into it. If the on-screen keyboard is not displayed when you tap the button, you can.

**Comment by tml1024** [comment]
This bug is related to the use of CollaboraOnlineWebViewKeyboardManager to handle on-screen keyboard for "normal" input, but then for this input, which is into a plain HTML dialog or some such, we apparently *don't* want to do that, and the state gets all confused. Hacking on this and trying to come up with some not too insane solution. (But I expect that will be impossible, and even more insanity will have to be added...)

**Comment by tml1024** [comment]
After some initial hacking attempts, I even managed to end up with **two** dialogs to enter a comment at the same time, looking slightly different... ![IMG_0099](https://user-images.githubusercontent.com/310731/109993896-6eb3e280-7d15-11eb-97ce-b209f8d03f5c.PNG) Note how in the left, smaller dialog the buttons are smaller and rounded. No idea which is the correct way they are supposed to look. (Personally I like the one with rectangular buttons more, it doesn't look like it would be desperately attempting to mimic some "native" look but failing.)

**Comment by tml1024** [comment]
Gosh it is hard to understand what is going on here. I wonder if there is some fundamental problem in the code (even for Collabora Online in a normal browser) and it seems to work fine just by accident? That it is possible to get two different-looking dialogs for the same thing is so weird.
