### ISSUE TITLE
iOS App: Unable to create a new document after closing the dialog

### ISSUE THREAD

**Issue by Gianni154** [CollaboraOnline/online#1433]
**Describe the bug**
If I want to create a new document and click on "+" or at the bottom on "Create Document" the dialog appears as usual. If I click outside this black box, this dialog disappears (so far so good). If I now click again on the "+" symbol or on "Create Document", it is no longer possible to create a new document. To open a new document you have to close the app and restart it.

**To Reproduce**

1. Open the Collabora iOS App
2. Click on 'Create Document' or on the top left on '+'
3. Click outside the black box so that it closes again
4. Try to open a new document (again)

**Expected behavior**
A new file can still be opened even if you close the first dialog.

**Actual behavior**
If you open a new document but then close the dialog for opening a new document, you cannot open a new document and you have to restart the app.

**Screenshots**
![bug](https://user-images.githubusercontent.com/78140364/107225461-1ab92500-6a19-11eb-8a8a-031443c604d4.gif)

**Device**
 - Device: iPad 6th generation 
 - OS: iPad OS 14.4
 - Version: iOS Collabora App Version 6.4.5 (2)

**Comment by thebearon** [comment]
Confirmed with app version 6.4.5 (2).

**Comment by tml1024** [comment]
On this now.

**Comment by tml1024** [comment]
The above is an admittedly somewhat silly workaround, but hey, it prevents the problematic situation from occurring.

**Comment by nikslor** [comment]
I think this workaround is good enough; let's close this issue.
