### ISSUE TITLE
Libertinus Font in CODE docker container

### ISSUE THREAD

**Issue by quizilkend** [CollaboraOnline/online#1444]
I have the Libertinus font family as my default in my documents. Libertinus is the successor of LinuxLibertine.

It would be lovely to have Libertinus packaged instead or in addition to LinuxLibertine in the docker container of CODE.

It is possible to get the fonts in the CODE-docker-container as described here: https://help.nextcloud.com/t/collobora-online-and-docker-how-to-add-new-fonts/65750/9  
But it would be very useful to have the successor of LinuxLibertine in the Container as well.

Hopefully this is the right place to post - otherwise just close the issue and I am happy to ask where you point me to.

Best regards  
Samuel

**Comment by timar** [comment]
Thanks for the tip, I think it's useful. We ship Linux Libertine G, which is the [Graphite versions of Linux Libertine](https://numbertext.org/linux/) so I'm not sure we can replace it to Libertinus. What do you think, @laszlonemeth ?

On the other hand, we can consider adding Libertinus Font in CODE docker container. I'll check.

**Comment by laszlonemeth** [comment]
Linux Libertine G is for typesetting in LibreOffice Writer, Libertinus is for typesetting formula in TeX and its relatives.

Linux Libertine G contains several corrections for kerning and combining diacritics (for example, kerning is missing for ISO 8859-2 letters in Libertinus, see e.g. „Vő”). You can typeset complete texts in its superior, i.e. you have a real (not distorted) font type for small letters, as in a high quality font set for DTP (for example see footnotes in http://www.numbertext.org/logo/logofuzet.pdf).

Linux Libertine G supports
– hanging punctuation;
– French spacing (default for French and Hungarian);
– Italic correction;
– thousand separation;
– right aligned footnote alignment (fixing incompleteness of Writer);
– etc. see http://numbertext.org/linux/fontfeatures.pdf (and https://github.com/alerque/libertinus/blob/master/documentation/Opentype-Features.pdf for comparison).

So Libertinus is not a replacement of Linux Libertine G.

**Comment by quizilkend** [comment]
Ah okay. I didn't get that the Libertine G fonts are an independent fork of LinLibertine with extendet functionality.

As far as I can see, the added features to the LinLibertineG-Fonts are used, so that Libertinus cannot be a replacement.

For what I can see the G-types aren't maintained since several years, so that maybe a Libertinus as additional font would not hurt. It seems as there are some efforts to port Graphite features to the OpenType Font, but I am not able to judge if those are the important features or how good this is going.

I did some quick search in the libertinus repository regarding your feature list:

- hanging punctuation:  
  seems to be possible with some OpenType feature, but is not supported by most software ([Libertinus 220](https://github.com/alerque/libertinus/issues/220))
- french spacing:  
  I did not find anything regarding ths
- italic correction:  
  there is some source code mentioning that and issues as well. But I don't know really what "italic correction" meand
- thousand separation:  
  Did not find this.

**Comment by pedropintosilva** [comment]
Hi @quizilkend while trying to hunt old issues I found this one and I was wondering if we can close it or if we should keep it open. Particularly because  @laszlonemeth 's comment:

> Linux Libertine G is for typesetting in LibreOffice Writer, Libertinus is for typesetting formula in TeX and its relatives.

/me closing, if needed please ping back and we can always reopen it :)

**Comment by quizilkend** [comment]
Actually, I think @laszlonemeth was not particularly right.
Libertinus font is used in WYSIWYG editors and I would be happy if it could be included in the collabora docker image.

It could be useful, because the Libertine Fonts (including the Libertine G variant) haven't seen any activity in the recent years.

However it seems to be possible to add custom fonts, so I will stick to that at the moment.
