### ISSUE TITLE
Renaming becomes available after rename by another user

### ISSUE THREAD

**Issue by xklonx** [CollaboraOnline/online#1450]
**Describe the bug**
Filename textbox becomes editable,although initially was disabled, when UserCanRename false and UserCanNotWriteRelative true after other user who have UserCanRename true renames file

**To Reproduce**
Open file by user who cant rename, check that filename textbox disabled.
Open same file by another user who can rename file, rename it.
Now check first user interface, textbox now editable and nothing happens if you try to rename because use still not have access.

**Expected behavior**
Filename textbox remains disabled

**Actual behavior**
Filename textbox becomes editable

**Desktop (please complete the following information)**
 - Version: collabora 6.4.5

**Comment by Ezinnem** [comment]
I can confirm this behavior occurs in LOOLWSD 6.4.10 snapshot (git hash: [b4fa48ef](https://github.com/CollaboraOnline/online/commits/b4fa48ef))

**Comment by timur-g** [comment]
This still occurs in 23.05 but not sure that is a bug. 
Rename button is still available, rather it does not rename but saves as. 
Server knows rename is restricted so it will not rename, but online UI is unaware of that thing so button will be visible.
This seems like a matter of integration to me.
