### ISSUE TITLE
iOS App: Calc: Text "Background Color" is visible when selecting a color for coloring a cell

### ISSUE THREAD

**Issue by Gianni154** [CollaboraOnline/online#1461]
**Describe the bug**
If you want to color a cell in a table document (calc), this works without problems. However, I noticed that when selecting the background color, the text "Background Color" is displayed in the foreground. Unfortunately, this covers some colors during the selection, such as the color black.

**To Reproduce**

1. Open the Collabora iOS App
2. Open a new or an existing spreadsheet (calc)
3. Go to Edit Mode and click on any cell
4. Select "Home" in the notebookbar
5. Click on the "Background Color" icon 

**Expected behavior**
The text "Background Color" is no longer visible when selecting colors. 

**Actual behavior**
When selecting the color, the text "Background Color" hides the selection of some colors. 

**Screenshots**

![File_000](https://user-images.githubusercontent.com/78140364/107613394-82a18280-6c48-11eb-932c-a31bf9731b6f.jpeg)

**Device**
 - Device: iPad 6th generation 
 - OS: iPad OS 14.4
 - Version: iOS Collabora App Version 6.4.5 (2)

**Comment by timar** [comment]
@pedropintosilva or @eszkadev would it be possible to move the tooltip out of the way when someone touches those dropdowns? There are other examples. Backgorund color, Font color, Conditional...

**Comment by tml1024** [comment]
No tooltips should ever be displayed in the iOS app, right? Presumably this will be easy to fix.

**Comment by thebearon** [comment]
> No tooltips should ever be displayed in the iOS or Android apps, right? Presumably this will be easy to fix.

@kendy back then thought tooltips on mobile could be shown for a short amount of time (eg 5s), and then disappear, but I agree it's probably fine without tooltips, too.

On the other hand, now the behavior diverges between web-based online on tablet and the mobile app, which is less desired.

**Comment by tml1024** [comment]
> now the behavior diverges between web-based online on tablet and the mobile app, which is less desired

See the commit message. We should probably just use the window.mode.isDesktop() condition for all tooltip creation?

**Comment by tml1024** [comment]
> thought tooltips on mobile could be shown for a short amount of time (eg 5s)

But how would we know when to display a "tooltip" when there is no cursor that would be kept over a UI element while the user wants to figure out (or tries to remember) what it does (to which the tooltip helpfully gives the answer)?

If there was proximity sensing and we would know that the user is "hovering" their finger above a certain spot, but not touching, the situation would be different. But no touch device does that, I think.

If our UI on touch devices work such that you occasionally have to tap on an element twice to get it to do its thing, and then after the first tap a "tooltip" could be displayed, that is a bug, isn't it? That is not how it is supposed to work.

**Comment by pedropintosilva** [comment]
@thebearon @tml1024 

I agree, a tooltip in the majority * of the cases (certainly in our case) should be avoided. 

----
`* Otherwise, it can be shown on mobile but then it needs to be triggered by long press. User pattern documented on Android since ~ version 8 (on iOS there is not such info but rather other solutions targeted to point devices or pointy settings , I think)`

**Comment by lpranam** [comment]
btw have a look at #1909.
it enables tooltip to appear on long press in tables
