### ISSUE TITLE
Difficult to select lines

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#1462]
# Improve .uno:Line element

- Fixing the general #1183 and #1184 should improve Insert Line as well
  - It would fix the duplicated inserts (it would insert only when the user clicks and drags as stated in the issues)

## Improve how a line is selected
  - For now it would be already a great help if the default value would be a higher number (ticker)
  - We should also change the cursor on hover 
  - Ideally we would increase the active area of the line element so it's easy to select even if the line is tiny in width. (We could pretend that any line as a minimum width of active area of 3pt)

**Comment by pedropintosilva** [comment]
@nikslor have also point out that this might be more dramatic on tablets (blocking the user to interact wit those)

> Lines as well as other "thin" elements from the "Basic Shapes" collection are hard to select and use using a finger. In many cases I struggle to get the line selected at all; the area that acts on a finger tap must be increased.

>  ![image](https://user-images.githubusercontent.com/65948705/220919841-5d3bf719-4404-43ef-8d18-857f1446bb38.png)

**To Reproduce**
Steps to reproduce the behavior:
1. Open a writer document in the iOS app
2. Insert a line and/or a basic shape as shown in the screenshot
3. Try to select the element using a finger

**Expected behavior**
It should be easy to select such an element and then drag it around or resize it.

**Actual behavior**
It's very hard to select such an element.

**Tablet**
 - OS: iPadOS 14.4.2
 - Version: 6.4.9 (1)

**Comment by LorenAmelang** [comment]
I'm the author of #6573. For curiosity, I opened the file I showed there in Libre on Windows. Even on a Surface Book with a mouse, it is very difficult to select those Lines! The vertical distance that works for selection is about the same size as the movement step size of my Bluetooth mouse, and it takes maybe a dozen tries to get a mouse movement to stop in the right place. 

Here are two screen photos (from my phone, screenshots can't show the pointer position). They are with Microsoft Screen Scaling at 200% and Magnifier at 4X, so 8 screen pixels in the photo is a single pixel in the original display. Looks like the Lines are a single pixel wide...  

With the pointer too high to select the Line: 
![Not close enough 4X](https://github.com/CollaboraOnline/online/assets/1297090/40de00a2-7494-48b4-a717-a273ab68f2c7)

The lowest position that can actually select:
![lowest selection position 4X](https://github.com/CollaboraOnline/online/assets/1297090/cf02b52a-b0f6-408d-b1f6-39e4047d8b3f)

This is not just a "finger on touchscreen" problem!

**Comment by pedropintosilva** [comment]
@shehr7 let me add here some more info that can be help:
* https://wiki.documentfoundation.org/Development/DispatchCommands , ctrl+F for `.uno:Line`
  * https://opengrok.libreoffice.org/xref/core/officecfg/registry/data/org/openoffice/Office/UI/GenericCommands.xcu?r=980b5f26#2065 
* Also notice the existence of .uno:LineWidth so in theory it seems we are able to change that width but with a different command and after inserted the line. Which is not ideal. Nevertheless and if 
* It can also be useful to search for clues in:
  * https://bugs.documentfoundation.org
  * core repository and try different grep strings. Both searching in the commit messages: `git log --gep="<yoursearch>"` and searching in the code changes `git grep <yoursearch>`
  * LO dev lists: https://lists.freedesktop.org/archives/libreoffice/

**Comment by shehr7** [comment]
@pedropintosilva I have checked first 2 links though, and the .uno:LineWidth does not respond to any changes, though it has arguments passed to it as well. I think we need to pass arguments to the .uno:Line command but I am unable to find it's dispatch command, where we have to dispatch it along with the arguments. I am unable to understand the purpose of .uno:LineWidth as it does not have any effect on the line command.

**Comment by pedropintosilva** [comment]
Today's minutes: https://forum.collaboraonline.com/t/improve-uno-line-minutes/1919

**Comment by shehr7** [comment]
.uno:LineWidth is triggered whenever a line is introduced, though changing it's value does not change the default line width in core or in online writer, I think changing the active area will be a better approach. 
The terms "bounding box", "shape render" and "hit test" show some results (in core) which may or may not be related to the selection of active area when the line is selected. I was able to find some code pointers but am not sure if it is related to the code related to selection of active area.

**Comment by shehr7** [comment]
The increase in value of "xBoundingShape" in libreoffice/chart2/source/view/main/ChartView.cxx may result in increase in the active area of the line.

**Comment by pedropintosilva** [comment]
@GulsahKose can you help Shehr with some clarifications/code pointers?

**Comment by LorenAmelang** [comment]
Just a possibly useless question...  As I wrote in https://github.com/CollaboraOnline/online/issues/6573, when I first accidentally tapped the line button, it seemed the line appeared at a random location in my sheet with a random length. And when I tapped it again, another one appeared randomly lower and to the right. What controls those aspects of the inserted line? Maybe the line width is set the same way? What is the intention?

**Comment by shehr7** [comment]
@LorenAmelang The line now does appear in the middle of the sheet (in writer) and when clicked for the second time, another line overlaps the previous one (and both have the same dimensions) 
The default line width is zero. And we have not been successful in changing the default width of the line.

**Comment by GulsahKose** [comment]
Hi Shehr, To understand how uno:Line command handled on core side first you should search the Line word in sdi files here (svx.sdi) you can see the related commad defination:
SfxBoolItem Line SID_DRAW_LINE

[
    AutoUpdate = TRUE,
    FastCall = FALSE,
    ReadOnlyDoc = FALSE,
    Toggle = FALSE,
    Container = FALSE,
    RecordAbsolute = FALSE,
    RecordPerItem;


    AccelConfig = TRUE,
    MenuConfig = TRUE,
    ToolBoxConfig = TRUE,
    GroupId = SfxGroupId::Drawing;
]

For each component uno:Lİne command handled different. For example if you understand how it handled in impress you should search the SID_DRAW_LINE keyword in sd directory:

If you debug you will see:
https://opengrok.libreoffice.org/xref/core/sd/source/ui/view/drviewse.cxx?r=ea63b3d2#400
is the related part. It invokes FuConstructBezierPolygon::Create then creates the line object.

I think you can find the line width setting if you track that way. Then you can use ticker value.
I hope it helps.

**Comment by shehr7** [comment]
The meeting minutes at https://forum.collaboraonline.com/t/improve-uno-line-minutes/1919/1 show the code pointers where the changes to the input value of line width does not show any effect on the core side or on the online side. Instead of changing the default line width, the focus should be somehow on changing the active selection area when the line is introduced, for which the code pointers mentioned in Gulsah's comments might be helpful.

**Comment by pedropintosilva** [comment]
The core issue has been fixed by @lpranam  with 168837: LOK: fixed incorrect Logic point calculation for Map mode | https://gerrit.libreoffice.org/c/core/+/168837 . Still it would be great if the active area would be bigger (so the user doesn't need to aim to accurately) maybe that can be issued as an enhancement. 

Additionally, the line can be also selected from the navigation sidebar:


https://github.com/CollaboraOnline/online/assets/65948705/b63feb11-5c6b-4aae-b08d-14746c45530e
