### ISSUE TITLE
Menu tab "File" is empty

### ISSUE THREAD

**Issue by sowoi** [CollaboraOnline/online#1491]
**Describe the bug**
When clicking on menu tab "File" nothing is displayed.

**To Reproduce**
1. Open Office365 Document
2. Click on tab "File"
3.  Expand

**Expected behavior**
Show Save or print

**Actual behavior**
Empty

**Screenshots**
![Bildschirmfoto vom 2021-02-17 14-00-22](https://user-images.githubusercontent.com/10256263/108207821-8a6d9500-7128-11eb-8506-62024f29cb37.png)

**Desktop (please complete the following information)**
 - OS: Windows 10 or Ubuntu 20
 - Browser: Chrome 88 , Firefox 85
 - Version: [e.g. 22]

**Additional context**
Where are using Collabora with Seafile Server.

**Comment by timar** [comment]
I think Seafile integration disables all menu items from the File menu, because it implements their functionality elsewhere. Can you confirm that?
The empty menu is a cosmetic bug.

**Comment by Andreas-Kainz** [comment]
I would say it's a design decision from seafile, so from my point of view we can close this report.

**Comment by thebearon** [comment]
We wouldn't want to display an empty menu, though.

**Comment by Andreas-Kainz** [comment]
But show an menu bar without file would look also strange. 

How would it look at file tab in notebookbar view?

Seafile bug?
