### ISSUE TITLE
iOS only opens MSO documents

### ISSUE THREAD

**Issue by oiselarius** [CollaboraOnline/online#1509]
**Describe the bug**
All open doc and pdf formats are grayed out while MSO formats are highlighted to open.

**To Reproduce**
1. Install Collabora on iPhone 12 Pro Max running iOS 14.4.
2. Connect to my document folder in Google Drive
3. Try to open files 

**Expected behavior**
I thought Collabora was open document friendly

**Actual behavior**
doesn’t allow open format files to be opened

**Screenshots**

**Desktop (please complete the following information)**
N/A

**Smartphone (please complete the following information)**
 - Device: iPhone 12 Pro Max
 - OS: iOS 14.4
 - Browser: Firefox, Safari, or Edge
 - Version: 31.0

**Additional context**

**Comment by cornouws** [comment]
Thanks for reporting oiselarius!
Can you pls add if opening an odf file from the storage on the phone does work?

**Comment by oiselarius** [comment]
If I transfer the file from cloud storage to the phone it seems to work. I don’t know why the same files stored on a cloud server won’t open.

**Comment by tml1024** [comment]
Looking into this now. As far as I recall, other storage providers used to work just fine. There certainly is no intentional code in there that would restrict it to open files from iCloud.

**Comment by tml1024** [comment]
I just tried opening a .ods document from OneDrive a it worked just fine. (This is using the latest TestFlight build.)

**Comment by tml1024** [comment]
But yeah, for some reason all ODF documents in Google Drive are greyed out in the app. This is probably Google Drive's fault.

**Comment by tml1024** [comment]
The fix for this seems to be to move the ODF entries for the ODF file types from the UTExportedTypeDeclarations section to the UTImportedTypeDeclarations section in the Info.plist. (Sadly the exact semantics of the Info.plist file leaves much to be desired.)
