### ISSUE TITLE
Different color in font color icon of toolbar and sidebar

### ISSUE THREAD

**Issue by Rash419** [CollaboraOnline/online#1511]
**Describe the bug**
If we change font color from toolbar , the font color icon does not change in sidebar,but if we change it from sidebar then font color in toolbar icon does change

**To Reproduce**
1. change font color from toolbar the sidebar font color icon will not change

**Expected behavior**
when changing font color from toolbar both font color icon should be same

**Actual behavior**
Right now if we change font color icon from toolbar it doesnot change in sidebar

**Screenshots**
![1st_issue](https://user-images.githubusercontent.com/26241069/108596133-1261d200-73a9-11eb-83be-745474eed200.png)

**Desktop (please complete the following information)**
 - OS: Arch Linux
 - Browser: Chrome

**Comment by thebearon** [comment]
This originates from core: https://bugs.documentfoundation.org/show_bug.cgi?id=82438

**Comment by pedropintosilva** [comment]
Since the sidebar is now rendered on the client side I think we can close this issue now
