### ISSUE TITLE
[Bug Report] Doesn't open Arabic docx files!

### ISSUE THREAD

**Issue by SerjSX** [CollaboraOnline/online#1513]
**Describe the bug**
I tried to open a document today with Arabic text in it, but it's just blank! 

**To Reproduce**
1. Go to 'Collabora Office app'.
2. Click on 'the file icon at the top right'.
3. Find and open the file.
4. See blank page and no text.

**Expected behavior**
Blank page instead of the Arabic text.

**Actual behavior**
When opening a document with Arabic text file, it shows blank.

**Screenshots**
![Screenshot_20210221_064834](https://user-images.githubusercontent.com/74871847/108615942-8c2da600-7411-11eb-886c-2f1c204c92b3.jpg)

**Desktop (please complete the following information)**
 - OS: Android
 - Browser: Firefox (but I don't use it from browser)
 - Version: 6.4.3

**Smartphone (please complete the following information)**
 - Device: Huawei Nova 3i
 - OS: Android 9 / EMUI 9.1
 - Browser: Firefox (but I don't use it from browser)
 - Version: 6.4.3

**Additional context**
Fix it asap!

**Comment by kendy** [comment]
@SerjSX: Thank you for the report! Can you please also attach here a public example document where this happens? Thank you in advance!

**Comment by SerjSX** [comment]
> @SerjSX: Thank you for the report! Can you please also attach here a public example document where this happens? Thank you in advance!

Hello! I'm very sorry I just opened the file with normal Office and it was an issue with the file, I tested with another document and it shows fine! I will report soon about the Powerpoint, it's VERY unstable, but thanks anyways! Feel free to close this. Sorry for the trouble!

**Comment by kendy** [comment]
@SerjSX Cool, thank you for double-checking, closing :-)

**Comment by Ai80-8** [comment]
Delete it all
