### ISSUE TITLE
[Bug] Powerpoint Bug Hub

### ISSUE THREAD

**Issue by SerjSX** [CollaboraOnline/online#1521]
**Describe the bug**
Full of bugs, very slow animations and transitions, not displaying pictures and app freezes a lot.

**To Reproduce**
1. Go to 'a Powerpoint file'
2. Click on 'play button'
3. See the bugs and glitches.

**Expected behavior**
A lot of freezing.

**Actual behavior**
Most of the time background pictures don't show, instead it's white. Animations of objects freeze in the middle then directly skip to the default position. When trying to change slide the app freezes (for a long time) and sometimes it also crashes.

**Desktop (please complete the following information)**
 - OS: Android
 - Browser: Firefox
 - Version: 6.4.3

**Smartphone (please complete the following information)**
 - Device: Nova 3i and Galaxy Tab 3 10.1
 - OS: Android 9 (Nova 3i) and 7.1.2 (Galaxy Tab 3 10.1)
 - Browser: Firefox
 - Version: 6.4.3

**Additional context**
The Powerpoint needs a lot of improvements for it to be stable, it needs to be taken into consideration ASAP! I had to change to the normal Office app back to play powerpoints, but I really want this app to be stable since you know the Mr. Office guy has trackers and etc. And I don't want to include screenshots or recordings, so whenever you have a time just get a random powerpoint that has like all animations on texts, transitions and etc, and then test it to see how it works. I hope this gets fixed as soon as possible!

**Comment by thebearon** [comment]
Please attach a sample, and add detailed reproduction steps.

**Comment by SerjSX** [comment]
> Please attach a sample, and add detailed reproduction steps.

Okay when I'm done I'll mention you.

**Comment by SerjSX** [comment]
> Please attach a sample, and add detailed reproduction steps.

Hello! I attached here a quick Powerpoint file, check it out! And read the texts as well, I did write some stuff in it like what you should expect and etc, I did test it on Collabora Office as well (Android).
[Collabora Test.pptx](https://github.com/CollaboraOnline/online/files/6036972/Collabora.Test.pptx)

More clear instructions (sorry if it wasn't clear in the text):
1. Open the Collabora Office app.
2. Click on the Folder icon at the top right (make sure you moved the file on your phone as well), navigate to the file and open it.
3. Then there's a play button at the top in the middle with an arrow like this >, click on that and it should start playing the powerpoint.
4. You should be able to see now the lags, missing background pictures, and etc. Well, at least I did.

If you're not facing my issue, then the app doesn't have well compatibility with all devices, try to optimize it as much as possible. Don't forget to add it on the F-Droid version too! Let me know :)

**Comment by SerjSX** [comment]
> > Please attach a sample, and add detailed reproduction steps.
> 
> Hello! I attached here a quick Powerpoint file, check it out! And read the texts as well, I did write some stuff in it like what you should expect and etc, I did test it on Collabora Office as well (Android).
> [Collabora Test.pptx](https://github.com/CollaboraOnline/online/files/6036972/Collabora.Test.pptx)
> 
> More clear instructions (sorry if it wasn't clear in the text):
> 
>     1. Open the Collabora Office app.
> 
>     2. Click on the Folder icon at the top right (make sure you moved the file on your phone as well), navigate to the file and open it.
> 
>     3. Then there's a play button at the top in the middle with an arrow like this >, click on that and it should start playing the powerpoint.
> 
>     4. You should be able to see now the lags, missing background pictures, and etc. Well, at least I did.
> 
> 
> If you're not facing my issue, then the app doesn't have well compatibility with all devices, try to optimize it as much as possible. Don't forget to add it on the F-Droid version too! Let me know :)

@thebearon are you still there?

**Comment by SerjSX** [comment]
Sorry? Anyone available to look into this and eventually update it??

**Comment by thebearon** [comment]
Sure, eventually. Thanks for creating a sample! Generally it tends to be more useful if it isn't a hodgepodge of different bugs, and the issues are separated into different bug reports. Right now it isn't even worth checking the original description: seeing how those individual transitions or animations behave in CODE on a desktop machine is perfectly enough to identify if there's a bug with a specific one or not.

**Comment by SerjSX** [comment]
> Sure, eventually. Thanks for creating a sample! Generally it tends to be more useful if it isn't a hodgepodge of different bugs, and the issues are separated into different bug reports. Right now it isn't even worth checking the original description: seeing how those individual transitions or animations behave in CODE on a desktop machine is perfectly enough to identify if there's a bug with a specific one or not.

Hey, sorry for late response! Is this going to be fixed or not? Or this is happening because of how the application is coded? I didn't understand quite much from your explanation.

**Comment by SerjSX** [comment]
Please I need someone to look into this issue!! This is a great app and I want to use it on my tablet, but the powerpoint isn't working well.

**Comment by SerjSX** [comment]
@vmiklos @mmilata Please anyone? Let me know.

**Comment by vmiklos** [comment]
Please mail us at hello@collaboraoffice.com if you are interested in paid options for your need. Thanks!
