### ISSUE TITLE
Sheets: HiDPI screen + cell formatting causes screen to jump to the right when inputting text

### ISSUE THREAD

**Issue by shuhaowu** [CollaboraOnline/online#1539]
**Describe the bug**
When using a HiDPI screen (4k 27"), when a cell has any number formatting (such as percent formatting) on it and when text is inputted, the screen jumps to the right.

#548 maybe related.

**To Reproduce**
1. Get a HiDPI screen (4k 27" is what I have).
2. Create a new sheet
3. Zoom to 200%.
4. Enter a number on that textbox (say 30).
5. Convert it into a percent.
6. Go back to the same textbox and try to enter another number.
7. The moment you hit a number key while on that textbox, the screen jumps way to the right.

Note, if you leave the zoom to 100% (unusable due to #654), the screen won't jump to the right, but it remains unusable.

**Expected behavior**
It should not jump to the right.

**Screenshots**

![output](https://user-images.githubusercontent.com/338100/109253324-89d69d80-77bd-11eb-94d4-bb5da741c11f.gif)

**Desktop**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: 85.0.1

**Comment by thebearon** [comment]
I'm assuming this is the same as #1867. Let me close as duplicate, thanks for reporting!
