### ISSUE TITLE
Chapter Numbering dialog is not available in Collabora CODE 6.4

### ISSUE THREAD

**Issue by manuth** [CollaboraOnline/online#1546]
**Describe the bug**
When opening a text-document using Collabora CODE 6.4, the `Tools`-tab is missing in the ribbon-menu.

**To Reproduce**
1. Open a file
1. Try to find the `Tools`-tab in the ribbon menu

**Expected behavior**
The `Tools`-tab should be visible providing some extra features such as setting the `Chapter Numbering` as described [in the official docs](https://help.collaboraoffice.com/6.4/en-US/text/swriter/guide/numbering_paras.html?&DbPAR=SHARED&System=UNIX)

**Actual behavior**
The `Tools`-tab is not visible

**Screenshots**
![image](https://user-images.githubusercontent.com/7085564/109402780-ee7a2f80-7958-11eb-856f-a4307f37ae9f.png)

**Desktop (please complete the following information)**
 - OS: Docker-Image `collabora/code` on an `Ubuntu 20.04.2 LTS` machine
 - Browser: Edge 88.0.705.81 (based on Chromium)
 - Version: Collabora CODE 6.4.6 (git hash: 44a46d7)

**Comment by farrad** [comment]
Same here:

    OS: Docker-Image collabora/code on an Ubuntu 20.04.2 LTS machine
    Browser: Firefox 86.0.1 (64-bit) Win10
    Version: Collabora CODE 6.4.6.8

**Comment by thebearon** [comment]
That information is a bit misleading, as the help is based on the desktop (not online) version, and not all of the dialogs and menu items are available in Collabora Online.

**Comment by pedropintosilva** [comment]
Hello, yes the dialog button is missing from the tabbed view but it is accessible from the compact view.

I will add it under the "Format" tab, thanks for reporting.

**Comment by pedropintosilva** [comment]
or maybe @GulsahKose can you do it please?
