### ISSUE TITLE
White Screen text no visible

### ISSUE THREAD

**Issue by SaadYasir** [CollaboraOnline/online#1547]
Text is not visible when editing any document. 
I can write text, all menu's are working. 
i can type the text. but its not visible
![image](https://user-images.githubusercontent.com/4014715/109428837-a02d6500-7a1a-11eb-9eeb-4baf43bf9ba1.png)

Core 7.1.1
ARM 64 bit

**Comment by thebearon** [comment]
This seems like a case of missing font. When you open the properties using the [A]-like button on the top toolbar, what does it say for Font Name?

**Comment by SaadYasir** [comment]
Please see the screenshot
[Image]


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SaadYasir** [comment]
![Screenshot_2021-03-11-11-00-20-083_org libreoffice androidapp debug](https://user-images.githubusercontent.com/4014715/110744319-51be6880-825b-11eb-92d5-9b4fffa604d3.jpg)

**Comment by thebearon** [comment]
That's strange, I've never seen a problem with the default font. At the same time, I haven't seen a dark mode like this with the app before, either, for me the toolbars and the config panel haven't become dark even when switching on dark mode in the app and in the phone.

**Comment by SaadYasir** [comment]
I am using dark mode on my mobile.

**Comment by Ezinnem** [comment]
Collabora office app version 6.4.13 was released recently and this issue seems not reproducible using it.

@SaadYasir, please can you test again using the new version?

**Comment by Ezinnem** [comment]
This issue does not seem reproducible with the recent version.

Since the author did not respond for several weeks, It would be best to close the ticket.
