### ISSUE TITLE
Cannot make selection in CODE Writer Document after inactivity timeout

### ISSUE THREAD

**Issue by harman-cn** [CollaboraOnline/online#1558]
**Describe the bug**
When trying to modify a document after the inactivity timeout, there is occasionally an uncaught exception when trying to remove the old view. In the browser console: 
> Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
After this exception, when I try to make a text selection, the document briefly shows a blank modal before reloading contents. Making a selection is still not possible after this however, until I force-reload from the browser.

**To Reproduce**
1. Run loleaflet.html in an iframe
2. Wait for inactivity timeout
3. Bring the document back in focus and make a modification
4. Check the browser console for the exception. It doesn't happen consistently every time, so if the exception is not present you may have to restart from step 1
5. Make a text selection and try to make a modification on it (Bold, italics, insert comment etc)
6. Document should reload and the modification in step 5 is not applied

**Screenshots**
[Exception in browser console](https://ibb.co/bdyx9w9)
[Blank modal popup](https://ibb.co/y5z9h67)
[Document reloading](https://ibb.co/gWR5Q70)

**Desktop (please complete the following information)**
 - OS: Ubuntu 20.04
 - Browser: Chrome

**Comment by Ezinnem** [comment]
@harman-cn, please does this issue still occurs at your end?

Can you upgrade to the CODE version 6.4.11 and test again?

**Comment by Ezinnem** [comment]
Closing this issue due to no response from the author.
