### ISSUE TITLE
Calc: "Show sheet" dialog isn't scrollable

### ISSUE THREAD

**Issue by lpranam** [CollaboraOnline/online#1565]
**Describe the bug**
dialogue "show sheet" has a messed up layout and is not scrollable. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Add and hide at least 12-15 calc sheets
2. Right-click on any sheet and then select  "show sheet" option
 notice the dialogue layout is not in place

**Screenshots**
![Screenshot_20210302_182419](https://user-images.githubusercontent.com/24812220/109651842-08985580-7b85-11eb-92c7-ed0f1554f74f.png)

**Additional context**
similar behaviour can be seen on mobile too, don't forget to check the mobile case after fixing in the desktop.

**Comment by lpranam** [comment]
@Rash419 :D

**Comment by husisusi** [comment]
Same here

**Comment by thebearon** [comment]
Thanks for fixing, @Rash419!
