### ISSUE TITLE
broken link (404) in your tutorial "Contributing to Collabora Online"

### ISSUE THREAD

**Issue by pflegende** [CollaboraOnline/online#1672]
**Describe the bug**
broken link in your tutorial "Contributing to Collabora Online"
https://github.com/CollaboraOnline/online/blob/44fd1c6b513547013dfc20de8ddf63f1b6dca517/CONTRIBUTING.md

in point 4 in "Guidelines"
`Report the issue using one of our templates, they include (...)`
"templates" has the broken link:
https://github.com/CollaboraOnline/online/blob/44fd1c6b513547013dfc20de8ddf63f1b6dca517/ISSUE_TEMPLATE

gives: 404

**To Reproduce**
_seems not necessary_

**Expected behavior**
_working link_

**Actual behavior**
_broken link_

**Screenshots**
_seems not necessary_

**Desktop (please complete the following information)**
 - OS: [W10]
 - Browser: [chrome]
 - Version: [last]

**Smartphone (please complete the following information)**
_not yet tested_

**Additional context**
_seems not necessary_

**Comment by thebearon** [comment]
@mrkara, can you please check?

**Comment by mrkara** [comment]
@pflegende Thank you for letting us know!

@thebearon Thanks for the ping! I'm on it.

:)

**Comment by mrkara** [comment]
Fixed by commit 0b284eb338958e2edcc57d75acb7d74a30ed1a7c

**Comment by pflegende** [comment]
seen,
thx
https://github.com/CollaboraOnline/online/issues/new/choose

CU
