### ISSUE TITLE
X-LOOL-WOPI-Timestamp error

### ISSUE THREAD

**Issue by xklonx** [CollaboraOnline/online#168]
Looks like collabora parses milliseconds with error.
For example i sent 2020-09-22T21:45:12.583000Z in CheckFileInfo
but then i recieve 2020-09-22T21:45:12.000583Z in X-LOOL-WOPI-Timestamp in PutFile.

**Comment by thebearon** [comment]
Which CODE version are you using, and what kind of setup are you working on? I wonder if using fractions of seconds is relevant.

What's strange is that the following commit added the current code to perform time conversions, and it includes unit tests that all pass:
https://github.com/CollaboraOnline/online/commit/22f1656e08d1cc873a523bf1f869bdd75066dd2a

**Comment by xklonx** [comment]
Im using version "productVersion":"6.4.0","productVersionHash":"6ad9d47"
In c# DateTime serialized in json by default as iso8601
![image](https://user-images.githubusercontent.com/9824966/95924658-abac2680-0dc0-11eb-8f30-a55f85cee2fe.png)
