### ISSUE TITLE
Is this still "free" ?

### ISSUE THREAD

**Issue by woeterman94** [CollaboraOnline/online#1692]
Is collabora office still available for free? What about collabora online?

![image](https://user-images.githubusercontent.com/5755057/110818491-98c55180-828d-11eb-9cbd-893a3c538075.png)
Does this mean I can only have 10 documents in the free version? Lol.

**Comment by timar** [comment]
This text is inaccurate. We removed the 10 documents limit in October, 2020. Where did you find this? It has to be corrected.

**Comment by woeterman94** [comment]
Right here: https://nextcloud.com/collaboraonline/
So how free is the free version? What are the limits?

**Comment by timar** [comment]
> Right here: https://nextcloud.com/collaboraonline/

Thanks, I'll ask Nextcloud to correct this.

> So how free is the free version? What are the limits?
There are no limits. For more details, please read https://www.collaboraoffice.com/code/ (there's FAQ, etc.)

**Comment by timar** [comment]
https://github.com/nextcloud/nextcloud.com/pull/1464
