### ISSUE TITLE
Impress: Incorrect mouse pointers over the selection areas

### ISSUE THREAD

**Issue by lpranam** [CollaboraOnline/online#1716]
**Describe the bug**
In Impress, insert a table, and hover over row/column selection areas, or the four arrows icon that selects the whole table.

->

1. Over the row/column selection area, you get a move cursor,
2. Over the four arrows, you get a left-right arrow cursor.

**Expected behavior**
In case 1, I'd expect it to be a thick arrow, like in desktop LO, in case 2 I'd expect it to be the same four arrows icon.

**Comment by lpranam** [comment]
@Rash419 something of your interest

**Comment by Rash419** [comment]
@lpranam  the cursor over column/row to resize is already a black dark arrow ,it is not handcursor

**Comment by lpranam** [comment]
@Rash419 not on the resizers but on the actual column/row headers. it should be hand but we get move cursor.
on the other hand on the top left corner over the four arrow we get left-right resize cursor which should be move cursor
