### ISSUE TITLE
Autosave on exit

### ISSUE THREAD

**Issue by suniltandan** [CollaboraOnline/online#1739]
**Describe the bug**
Even when always save on exit is disabled in loolwsd.xml, the document is saved on exit. 

<always_save_on_exit desc="On exiting the last editor, always perform the save, even if the document is not modified." type="bool" default="false">0</always_save_on_exit>

**To Reproduce**
1. Open a document. 
2. Modify the document.
3. Close the document, without explicitly saving. 
4. The document is saved. 

**Expected behavior**
The changes in the document should be ignored. 

**Actual behavior**
The changes are saved. 

**Desktop (please complete the following information)**
 - OS: MAC OS
 - Browser: ALL

**Collabora online version**
LOOLWSD
4.2.6 (git hash: ed4f732)
LOKit
Collabora Office 6.2-21 (git hash: 2efab9d

**Additional Notes**
Once a document is open and modified, the changes are always saved.

**Comment by thebearon** [comment]
This is not a bug, as the description says:
> "On exiting the last editor, **always** perform the save, **even if the document is not modified**."

This simply means that even an unmodified document gets saved, compared to having this setting turned off.
A modified document always gets saved to avoid potential data loss (eg. if the browser tab is closed by accident, or in case of connectivity issues), regardless of the setting.

**Comment by suniltandan** [comment]
@thebearon 
I see, It seems I misunderstood the configuration, thanks for your clarification. Is there anyway to turn this auto save off for the modified document without user explicitly saving it?

**Comment by enlight3d** [comment]
I second this, I'm searching for a way to disable auto save function even if document was modified until the user has clicked on save button ...

**Comment by betaWeb** [comment]
Same problem here : I try to disable the auto save, I don't wan't my document modified if the user don't click on the save button.
Is there a workaround to achieve this ?

**Comment by Tom-Finke** [comment]
I still have the same issue. The config in coolwsd now looks like this
`<always_save_on_exit default="false" desc="On exiting the last editor, always perform a save and upload if the document had been modified. This is to allow the storage to store the document, if it had skipped doing so, previously, as an optimization." type="bool">false</always_save_on_exit>`

Although I set it to false, the document still gets saved on last editor exit. 
I could fix this by changing the WOPI server behavior, but I want to avoid config in two different places.

**Comment by jazevedo-coll** [comment]
@Tom-Finke as mentioned before by @thebearon :
  
> A modified document always gets saved to avoid potential data loss (eg. if the browser tab is closed by accident, or in case of connectivity issues), regardless of the setting.

Can I ask what is your use case to want to disable autosave on exit?

**Comment by Tom-Finke** [comment]
> Can I ask what is your use case to want to disable autosave on exit?

We integrate with a service where files are version controlled and it is important that every new version is an active choice by the user, not created automatically.

Ideally, we would like collabora to cache the modified version even when the last user exits, as if there is still an active session, and only save back to the wopi server when the user hits save (and ideally enters a version comment)

**Comment by Tom-Finke** [comment]
> @Tom-Finke as mentioned before by @thebearon :
>   
> > A modified document always gets saved to avoid potential data loss (eg. if the browser tab is closed by accident, or in case of connectivity issues), regardless of the setting.
> 
The setting has a different description now where this does not become clear i.m.o.
It now says 
> always_save_on_exit default="false" desc="On exiting the last editor, always perform a save and upload if the document had been modified [...]

which I took to mean: "If set to true, save modified document on exit. If set to false, don't."
But thanks for confirming the setting still behaves this way.

**Comment by thebearon** [comment]
> Ideally, we would like collabora to cache the modified version even when the last user exits, as if there is still an active session, and only save back to the wopi server when the user hits save (and ideally enters a version comment)

It may be the best to implement some sort of staging storage and your own UI around this. The principle in Collabora Online is that a user session can terminate abruptly due to various reasons, eg. the user closing the browser tab, or an intermittent connection failure, and data loss is generally a worse option than a save.

> The setting has a different description now where this does not become clear i.m.o. It now says

Right, this was developed based on a request from a partner, and has been the source of some confusion. The description was updated to reflect that there's no save if the document is unmodified, only if it's been modified at least once in the session. And even then, it just adds an extra save, there's no way to prevent saving a modified document.

I'm not sure what exactly they needed it for, but unless the description clearly fits what you need (and it doesn't in your case), the best is to avoid this setting.

**Comment by Tom-Finke** [comment]
> > Ideally, we would like collabora to cache the modified version even when the last user exits, as if there is still an active session, and only save back to the wopi server when the user hits save (and ideally enters a version comment)
> 
> It may be the best to implement some sort of staging storage and your own UI around this. [...]


I think this is what we will do. @thebearon  thank you for your time and advice.
