### ISSUE TITLE
PDF for Android?

### ISSUE THREAD

**Issue by danielDimovski** [CollaboraOnline/online#1740]
Hello,

Collabora works great with office documents, but I don't seem to be able to open a PDF file on Android? I am not able to select a PDF document using the file picker, as it is greyed out. 
Is this something that will be implemented in the near future or is there a reason why it can't be implemented? 

Thanks

**Comment by Ezinnem** [comment]
The feature to open PDF files on Andriod is available in the Collabora Office 6.4.9 test version.

**Comment by danielDimovski** [comment]
Great, will give it a try. Thank you :)
