### ISSUE TITLE
/usr/bin/loolforkit CPU at 100%

### ISSUE THREAD

**Issue by robertofabrizi** [CollaboraOnline/online#1771]
**Describe the bug**
The CPU is fully taken by this process:
104       6614 19570 89 Mar17 ?        15:42:03 /usr/bin/loolforkit          --losubpath=lo --systemplate=/opt/lool/systemplate --lotemplate=/opt/collaboraoffice6.4 --childroot=/opt/lool/child-roots/ --clientport=9980 --masterport=loolwsd-mYkGf5R0 --rlimits=limit_virt_mem_mb:0;limit_stack_mem_kb:8000;limit_file_size_mb:0;limit_num_open_files:0 --version --ui=notebookbar

**To Reproduce**
That process has access to this file

kitbroker 6614      104   27u   REG   0,82  1955045 442796806 /opt/lool/child-roots/nFcwLVhhXCATjz4d/tmp/user/docs/nFcwLVhhXCATjz4d/117628 - Low Value Consignment xxxxx_v1.1.docx

**Expected behavior**
The cpu would not be stuck at 99%

**Actual behavior**
The cpu was stuck at 99%

**Screenshots**

**Desktop (please complete the following information)**
 - OS: Nextcloud 21.0.0 and collabora/code:6.4.6.2
 - Browser: not sure

**Smartphone (please complete the following information)**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by mmeeks** [comment]
This should be fixed by:

commit b7d7cef0d68aeb019949a546a7193eb8f7e14e55
Author: Ashod Nakashian <ashod.nakashian@collabora.co.uk>
Date:   Wed Mar 3 23:59:38 2021 -0500

    wsd: terminate Kit when disconnected while loading

and also helped by:

commit cda7357a82b3be7b60cc314cecbc59922beda629
Author: Noel Grandin <noelgrandin@gmail.com>
Date:   Sat Mar 13 09:36:46 2021 +0200

    check for quit when calling Yield in loop

Should be in the next code release tomorrow. Please do re-open if you can reproduce withthat.

Thanks for reporting ! =)

**Comment by robertofabrizi** [comment]
@mmeeks Doesn't seem to be:
top - 15:42:19 up 8 days,  3:54,  1 user,  load average: 64.18, 63.81, 56.73
Tasks: 368 total,  66 running, 234 sleeping,   0 stopped,   0 zombie
%Cpu(s): 95.0 us,  4.8 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem : 12271532 total,  1846932 free,  5938252 used,  4486348 buff/cache
KiB Swap:  4194300 total,  4175600 free,    18700 used.  5825948 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
11857 104       20   0 1660936 494204  85952 R  65.7  4.0   2763:38 kitbroker_00e
 4725 104       20   0 1661352 495160  86308 R  65.0  4.0   2762:58 kitbroker_00f
 4016 104       20   0 2209776 969752 104536 R  54.8  7.9 124:45.43 kitbroker_014

I'm running the latest collabora application for nextcloud.

**Comment by thebearon** [comment]
@robertofabrizi It is not clear to me whether you have also upgraded CODE (you are mentioning the Collabora Online app for Nextcloud, which is less relevant in this case), have you? Can you share the version number from Help -> About with a file open? It should say 6.4.7.

**Comment by robertofabrizi** [comment]
Ah, shame on me, I'm upgrading to 6.4.7.3 now, will update if it happens again, sorry
