### ISSUE TITLE
PDF for IOS

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#1824]
**Is your feature request related to a problem? Please describe.**
Collabora Online is able to handle PDF's for viewing and adding/modifying Comments, but this is not available in the IOS and Android (issue #1740) App's as of yet.

**Describe the solution you'd like**
Would be great to have this available in the IOS App too so when a PDF is opened from the IOS Explorer the file gets opened in the Collabora Office App and Send To function is available.

The needed lib's seem to be added as part of #1710 but as mentioned there by @tml1024 that does not expose the functionality to open PDF's from IOS to the App yet.

**Comment by tml1024** [comment]
What do you think about this, @timar @mmeeks ?

**Comment by mmeeks** [comment]
Sounds great to me; thanks Tor (& Sebastiaan)

**Comment by tml1024** [comment]
See also https://gerrit.libreoffice.org/c/core/+/113079

**Comment by tml1024** [comment]
The feature is present now in the 6.4.8(2) TestFlight build. (If there are no horrible new bugs in it, I will release that, as 6.4.7-2 or something like that.)

**Comment by nikslor** [comment]
Tested some PDFs, looks good! Thanks a lot to the Collabora team and especially @tml1024 to work in this!

**Comment by sebastiaanveld** [comment]
Viewing works for me too. Thx @tml1024 :)
* [issue] the only real issue I run into so far is that there is no (visible) Close-button in upper left corner on an iPhone (X). I have to close down the App to close the document. Think the issue here is that the toolbar is missing at all. The hamburger menu in the right top is visible. Enabling-Edit-mode does also not show the toolbar either. 
* [issue] Following previous issue: in Edit-mode the Edit-button switches to a "+" button. Clicking  "+" inserts a page in the PDF, which is probably inherited from Draw but serves (for now) no function; I would expect clicking "+" to allow me to add a new comment or maybe to popup a list of quickly selectable features like 1) "add a comment", 2) "add a page", 3) "Yellow marker" otherwise also (but less quickly) available on the toolbar or "hidden" in the hamburger menu. For the time being "+" may need to be hidden.
* [issue] On an iPad I'm able to go into edit-mode, add a Comment and then Save the document, reopening shows the Comment's made. Only thing is that opening a document with Comments shows no indication those are there as the page is opened full-size. I think in COOL the page width is auto-adjusted in case Comments are in the document so there is an indication to scroll right to see that data.
* [enhancement] From a navigation perspective it would be nice to be able to swipe left/right to navigate to previous/next page, instead of selecting the pages individually.
* Is there a way to force IOS to open

**Comment by sebastiaanveld** [comment]
[issue] in edit-mode the pdf content (the picture of the page) is quite touch sensitive. So, when I try to navigate the page by zoom and slide to scroll the picture get's selected and easily dragged off-page, at least it add to easily changing the page content while the only thin a user intends to do in edit mode is Add a comment or other graphics on top of the PDF page. Guess this is not a problem of the "PDF open mode" itself by inherited from how Draw handles the object. Maybe in case of opening a PDF the rendered page picture position (layer) can be locked by default, unless the user unlocks that (layer) using a function in the menu bar. That would also make selecting and dragging around objects (like "Yellow marker"-lines, signature, stamps and other graphics) added on top of the document content.

**Comment by sebastiaanveld** [comment]
@tml1024 let me now if you want me to split things up in new issues, for now I'll at them here to track issues related to the functionality.

**Comment by danielDimovski** [comment]
Hi,

It's great that the PDF was added for iOS. Will it be available for Android, too?

**Comment by tml1024** [comment]
@sebastiaanveld Please file each separate issues, yes. Also note that it is quite likely that many of the things you notice are not specific to the iOS app, but show up in a browser on a mobile device against web-based Collabora Online, too. Maybe even in desktop browser.

**Comment by Ezinnem** [comment]
The Collabora Office app version 6.4.13 was released recently.

This feature has been implemented on it.,
