### ISSUE TITLE
iOS App: 6.4.7 occasional crashes

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#1825]
**Describe the bug**
While testing the IOS App 6.4.7 I've seen two occasional crashes of the app at (so far) random points. I'm not able to reproduce this (yes), bot when it occurs again I'll send the crashlog and refer to this ticket and if possible how to reproduce it. 
App: Collabora Office 6.4.7 (1)

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots**

**Smartphone (please complete the following information)**
 - Device: iPhone X
 - OS: [e.g. iOS 14.4.1

**Additional context**

**Comment by nikslor** [comment]
Hi @sebastiaanveld today I also run in one (random) crash with 6.4.7 (1). I'm investigating as well.

**Comment by sebastiaanveld** [comment]
Spend quite some time trying to reproduce but are not able to yet; beginning to suspect these have had to do with documents that crashed the App before with an previous version and left some "cache" or other data behind which trigger the crash once after the update for any of these doc's.

**Comment by sebastiaanveld** [comment]
> 
> 
> Hi @sebastiaanveld today I also run in one (random) crash with 6.4.7 (1). I'm investigating as well.

Hi @nikslor , I spend quite some time trying to reproduce but are not able to yet; beginning to suspect these have had to do with documents that crashed the App before with an previous version and left some "cache" or other data behind which trigger the crash once after the update for any of these doc's. Played around multiple times with the same files in Read and Edit mode.

**Comment by nikslor** [comment]
Same here; no more random crashes in my last testing sessions. I propose to close this issue. What do you think @sebastiaanveld?

**Comment by sebastiaanveld** [comment]
Yes, let's close it for now as there is also the second build now.
