### ISSUE TITLE
iOS App: not possible to view/delete comments in impress component

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#1830]
**Describe the bug**
While it's possible to add comments in the impress part using the iOS app I don't see a possibility to open/see/read such a comment and I also don't see a possibility to delete such a comment (ihis works well in writer/calc).

**To Reproduce**
1. Insert a comment in an impress presentation using the iOS app -> an orange/yellow comment icon will be shown on the slide
2. Try to open/see/read or delete this comment

**Expected behavior**
A long press on the comment should possibly show the contextual menu which offers functions such as "show comment" or "delete comment"

**Actual behavior**
There is no way to show the contextual menu (using a finger)

**iPad**
 - OS: iOS 14.4
 - Version: 6.4.7 (1)

**Comment by eszkadev** [comment]
I think now we have 'comments manager' on mobile which can be opened using an icon in the top toolbar. There you can see all threads and reply / delete/ add new comments.

**Comment by nikslor** [comment]
I'm not sure if I just oversee how I could access the comments or if 6.4.7 (1) does not yet include the "comments manager".

Furthermore I see some "up/down" buttons which seem not to work on iOS.

See screenshot below:

<img width="1112" alt="comments_impress" src="https://user-images.githubusercontent.com/1211300/112339172-b8ae3980-8cbf-11eb-8c00-baf5b2c2951f.png">

**Comment by eszkadev** [comment]
I see, you are looking for it on a tablet, 'comment manager' is smartphone-only. sorry for noise :)
