### ISSUE TITLE
iOS App: there's something wrong with the calc UI rendering

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#1831]
**Describe the bug**
The calc UI is somehow not completely rendered correct at the moment. Some elements take too much space and others overlap.

<img width="1112" alt="calc_ui_broken" src="https://user-images.githubusercontent.com/1211300/112323787-64508d00-8cb2-11eb-8680-d8cf11656254.png">

**To Reproduce**
1. Open a calc sheet using the iOS app

**Expected behavior**
Input bar should not have unused space; sheets tab should not overlap.

**Actual behavior**
There are some issues with the UI; especially the unused space below the input bar as well as the sheets tab that gets overlapped and is not fully visible.

**iPad**
 - OS: iOS 14.4
 - Version: 6.4.7 (1)

**Comment by eszkadev** [comment]
I worked on that recently, 'document container' size should be fixed on tablets with the next release :)

**Comment by nikslor** [comment]
cool, thanks a lot for the information and the work @eszkadev!

**Comment by thebearon** [comment]
This was fixed by the commits in the following pull request: https://github.com/CollaboraOnline/online/pull/1777

Fix is already in app version 6.4.8 (2).
