### ISSUE TITLE
Add transparency on automatic font colored text make it invisible or white colored

### ISSUE THREAD

**Issue by galupa** [CollaboraOnline/online#1837]
**Describe the bug**
Add transparency on automatic font colored text make the text invisible or white colored

**To Reproduce**
1. Open a word document (doc / docx / odt)
2. Create a text with automatic color without any highlight or background color
3. Highlight the text and add transparency font effect
4. Text becomes white colored after applying transparency

**Expected behavior**
After applying transparency, text should be black with transparency effect.

**Actual behavior**
Text color appear white.

**Desktop (please complete the following information)**
 - OS: Ubuntu Bionic, Windows
 - Browser: Chrome, Firefox
 - Version: I test this using CODE 6.4.6

**Additional context**
Based on the code, I suspect the cause is because if I apply font color as automatic, it sent `statechanged: .uno:FontColor=-1` message. And based on this logic
```
if (commandName === '.uno:FontColor' || commandName === '.uno:Color') {
        // confusingly, the .uno: command is named differently in Writer, Calc and Impress
        color = parseInt(e.state);
        if (color === -1) {
            color = 'transparent';
        }
```
It seems `-1` color is treated as transparent.

Let me know if you need more details

**Comment by galupa** [comment]
I add some screenshot to make it clearer : 
Create a text, make the font color automatic and add transparency font effect
![Screenshot from 2021-03-25 14-00-20](https://user-images.githubusercontent.com/29434066/112403383-2f583f00-8d73-11eb-932c-1de225bd5688.png)
After save the text is not readable
![Screenshot from 2021-03-25 14-00-51](https://user-images.githubusercontent.com/29434066/112403391-31ba9900-8d73-11eb-91de-8493ae91b8d9.png)
If we open the option again, it says the text is white colorer.
![Screenshot from 2021-03-25 14-00-42](https://user-images.githubusercontent.com/29434066/112403389-30896c00-8d73-11eb-9f3c-d78912b559b1.png)

**Comment by Ezinnem** [comment]
I can seem to be able to reproduce this issue.

@galupa, please can you update your CODE version and test again?

**Comment by galupa** [comment]
I have tried using the 6.4.14-2 version and it is still resulting the same

**Comment by timur-g** [comment]
This is still true in 23.05. But this is Core issue, tracked in https://bugs.documentfoundation.org/show_bug.cgi?id=139751.
So I close the report here.
