### ISSUE TITLE
Ability to unfreeze first column or row individually

### ISSUE THREAD

**Issue by galupa** [CollaboraOnline/online#1838]
**Is your feature request related to a problem? Please describe.**
Sometimes when we are working on spreadsheet, we need to freeze first column and row and later we probably want to unfreeze either column or the row, however on current Collabora online, it seems we can only unfreeze both of them and it seems there is no indicator if we have already freeze the column only or row only.

**Describe the solution you'd like**
It will be good if after we click freeze first row, there is a tick on the side of the menu. Also apply for the freeze first column. And if we click again freeze first row with the tick on the side, the tick will be gone and the first row will be unfreeze.

**Describe alternatives you've considered**
Create a new button / menu to unfreeze rows / column also works as long as we can unfreeze it individually and there is an indicator whether we have freeze the column / row.

**Additional context**
Example of spreadsheet with first column or row frozen, it will be good if there a tick on the right side of the menu item after it was frozen and also clicking the menu item freeze first column / row does not unfreeze either of those.
![Screenshot from 2021-03-25 15-46-08](https://user-images.githubusercontent.com/29434066/112411543-f83d5a00-8d81-11eb-9dac-322dc35868c3.png)

**Comment by thebearon** [comment]
I would assume this is only really useful if someone is switching between frozen rows/columns often. And I would also assume which rows and/or columns are frozen is clear when looking at the spreadsheet, is that not so? I'd be a bit afraid of making the relevant menu more complicated for a fairly uncommon use case.

**Comment by galupa** [comment]
Ah yes, thank you for the confirmation, I will cancel this
