### ISSUE TITLE
iOS App: iPad toolbar missing in Read Only mode

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#1841]
**Describe the bug**
The IOS App 6.4.7 (1) on iPad has the (simple) toolbar missing in Read-Only-mode. So Comments is not accessible, in Presenter the Play button is missing and the hamburger menu is not there to be able to save/export/search etc. You have to go into Edit-mode first to start a Presentation or read Comments. This is both in Portrait and Landscape mode. The menu bar is there on an iPhone. 

**To Reproduce**
1. Install the App 6.4.7 (1) on an iPad
2. Open an document with the App
3. There is no menu bare in the to for basic Read-Only mode features (screenshot).

**Expected behavior**
In RO mode on an iPad there should be a (simple) toolbar for basic functions as there is on iPhone.

**Actual behavior**
Users now the to go to Edit-mode with the risk of modifying the document as part of interacting with is (view comments, play the presentation) and may modify it slightly as part of that which will create a new version of the document.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/37268999/112443113-d83f7380-8d4c-11eb-97d5-d3fafe57d7ac.png)

**Smartphone (please complete the following information)**
 - Device: iPad (5th gen) Model MP2G2NF/A
 - OS: IOS 14.4.1
 - Collabora Office 6.4.7 (1) App

**Additional context**
Guess the issue has to to with the different toolbar on iPad vs iPhone.

**Comment by Ezinnem** [comment]
Closing this issue as it is not reproducible on my end and there was no response from the author.
