### ISSUE TITLE
iOS App: file overlays should use ODF logo instead of the Collabora logo as the Android App does 

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#1846]
**Is your feature request related to a problem? Please describe.**
File overlays showing the ODF file types in the IOS Explorer should use ODF/LibreOffice logo's for odt/ods/odp/etc files. Think this helps in adoption of ODF as a standard, makes files more recognizable (instead of making the user believe these files may be a CO limited format) and is consistent with how these files are displayed in the Android App and on desktop platforms where LO is installed.

**Describe the solution you'd like**
File overlays showing the ODF file types in the IOS Explorer should use ODF/LibreOffice logo's for odt/ods/odp/etc files. 

**Describe alternatives you've considered**
-

**Additional context**
![afbeelding](https://user-images.githubusercontent.com/37268999/112451273-98c95500-8d55-11eb-9ef1-4946b21e383a.png)

**Comment by thebearon** [comment]
Seems reasonable, thanks for the suggestion!

**Comment by tml1024** [comment]
It is far from obvious how to fix this... Note that in our Assets.xcassets we only have an icon for the app itself, and that does *not* look like the icons depicted above. (The app icon is a white square with the logo reaching almost the sides.)

Our Info.plist(.in) does **not** specify any icon at all for any of the file types it lists. How iOS then comes up with the depicted icon, with a small version of our app icon in the middle of a larger "paper" icon with the upper-left corner bent, I have no idea. (Likely it is just a coincidence that that looks a bit like the LibreOffice logo.)

And on my iPad, for some .odt documents, their icon in the Files app is as above, but for others, the icon is a square with tiny text in it, apparently a preview of the text in the document (but missing the images). I have had also Word installed on this iPad, possibly it has also affected some icons in some way at some stage.

Anyway, isn't ODF supposed to be vendor-neutral, and LibreOffice just one implementation? Surely LibreOffice's logo is not the official ODF logo? I don't see the LibreOffice logo on https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=office .

**Comment by thebearon** [comment]
> Anyway, isn't ODF supposed to be vendor-neutral, and LibreOffice just one implementation? Surely LibreOffice's logo is not the official ODF logo? I don't see the LibreOffice logo on https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=office .

There are the following file type icons in the online repo:
https://github.com/CollaboraOnline/online/blob/master/loleaflet/images/x-office-document.svg
https://github.com/CollaboraOnline/online/blob/master/loleaflet/images/x-office-drawing.svg
https://github.com/CollaboraOnline/online/blob/master/loleaflet/images/x-office-presentation.svg
https://github.com/CollaboraOnline/online/blob/master/loleaflet/images/x-office-spreadsheet.svg

The icons in the Android app are different, though, those are the actual icons from the core Colibre theme (find them in `icon-themes/colibre/res`).

**Comment by sebastiaanveld** [comment]
Your're right there is no default; maybe I should have stated them as LibreOffice-ish-ODF icons :) I agree using the already available Colibre theme icons have the preference as that is consistent with Android and the default theme on most platforms.  

Looked around a bit, maybe this helps by defining them in the app and adding the right logo's: 
https://www.infragistics.com/community/blogs/b/stevez/posts/ios-tips-and-tricks-associate-a-file-type-with-your-app-part-2

**Comment by tml1024** [comment]
That post is from 2013 and Xcode looks very different nowadays....

**Comment by tml1024** [comment]
I think I'll close this (as WONTFIX in Bugzill parlance).
