### ISSUE TITLE
iOS App: calc input bar not usable

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#1864]
**Describe the bug**
In 6.4.8. (2) the issue #1831 was tackled, but now the whole input bar doesn't work anymore. I can't put the cursor in the input bar and the button to expand the input bar into a multiline element as well as the "down arrow" next to the sigma letter seem not to react on touch inputs.

**To Reproduce**
1. Open a calc document using the iOS app - v 6.4.8 (2)
2. Try to put the cursor in the input bar

**Expected behavior**
It should be no issue to put the cursor into the input bar.

**Actual behavior**
It seems not to be possible to put the cursor in the input bar.

**Screenshots**
Not easy to make a screenshot of this :)

**Tablet**
 - OS: iOS 14.4.1
 - Version: 6.4.8 (2)

**Comment by thebearon** [comment]
This works for me on an iPad, and the same version, 6.4.8 (2). What device are you using?

**Comment by smirta** [comment]
I'm using iPad Pro (12.9-inch) (3rd generation) with iOS 14.3 and Collabora 6.4.8 (2). Something doesn't seem to be right here. It somehow become hard to klick into the top bar via touch and I'm having troubles with the whole yellow marked area.

![image](https://user-images.githubusercontent.com/6649852/114530156-f7923800-9c4a-11eb-91ee-1ffae543f15f.png)

**Comment by tml1024** [comment]
Seems to work better now, in 6.4.12(1) (TestFlight version number, will be called 6.4.11-2 when in App Store).

**Comment by nikslor** [comment]
Works in 6.4.12 (1), the issue with the issue with the missing elements/visibility of the "select function" dropdown remains, but is reported and tracked separately here: #590
