### ISSUE TITLE
iOS app: the redline under a misspelled word is too small/thin (IMHO?)

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#1865]
**Describe the bug**
The redline under a misspelled word seems too small/thin in my opinion. See the the attached screenshot. 

**To Reproduce**
1. Open a writer document in the iOS
2. Enter a misspelled word and make sure spellchecking is active

**Expected behavior**
The redline under the misspelled word(s) should clearly be visible.

**Actual behavior**
The redline under the misspelled word(s) are so small/thin that it’s hard to find typos.

**Screenshots**
![4F0F759A-9DFF-486E-A1DB-4608AAF7E3D5](https://user-images.githubusercontent.com/1211300/112600890-0935ac00-8e12-11eb-8db3-a74c96e54a7b.png)

**Tablet**
 - OS: iOS 14.4.1
 - Version: 6.4.8 (2)

**Comment by thebearon** [comment]
Confirmed, it affects both phone and tablet view, and not specific to the iOS app.
