### ISSUE TITLE
iOS App: parts of the calc column headers seems to be cut off

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#1866]
**Describe the bug**
I think parts of the calc column headers are cut off in the iOS app 6.4.8. (2). See screenshot.

**To Reproduce**
1. Open a calc document in the iOS app
2. Switch to edit mode

**Expected behavior**
The content of the column header (A, B, C, ...) should have some padding to the input bar above.

**Actual behavior**
There is no padding and I think this looks wrong/broken/ugly.

**Screenshots**
![C275EF3E-E5F6-4D10-BEB0-D608DBEDA638](https://user-images.githubusercontent.com/1211300/112601783-25861880-8e13-11eb-9a76-09b00866b274.jpeg)

**Tablet**
 - OS: 14.4.1
 - Version: 6.4.8 (2)

**Comment by thebearon** [comment]
Confirmed, I'm wondering if this is due to the expanded size of the formula bar due to the larger than usual dropdown. In web-based online it looks fine. I wonder if this is somehow related to #1831.

**Comment by tml1024** [comment]
Seems to be fixed now? 
![IMG_0180](https://user-images.githubusercontent.com/310731/133077061-11d5e421-b464-48af-a3c4-f054509e1dc7.PNG)

**Comment by nikslor** [comment]
Yes, this is fixed :)

Thanks a lot to the Collabora team!
