### ISSUE TITLE
iOS App: calc view jumps (file specific issue)

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#1867]
**Describe the bug**
The attached file shows a file specific issue I can’t see in other files - but I think it’s still worth documenting and having a reproducible case.

Note: I can't reproduce this in normal online; may be iOS specific?

**To Reproduce**
1. Open the attached file
2. Enter Edit mode
3. Tab into the orange cell B25
4. Double tap on the cell B25 to put the cursor into it

**Expected behavior**
The view should not jump.

**Actual behavior**
(Often) the view jumps to column AK (in my case)

**Screenshots**
I’ll upload a video

**Tablet**
 - OS: 14.4.1
 - Version: 6.4.8 (2)

**Comment by nikslor** [comment]
https://user-images.githubusercontent.com/1211300/112603710-ab0ac800-8e15-11eb-921c-978d6bc03d50.MP4

**Comment by nikslor** [comment]
[Formeln.zip](https://github.com/CollaboraOnline/online/files/6210352/Formeln.zip)

Example file (seems I can not upload ODT files directly)

**Comment by gokaysatir** [comment]
It is reproducable with Chrome iPad view. View is jumping to another cell.

**Comment by WurstMitDurst** [comment]
It is also reproducible on 

- Windows, when display scaling is set to anything other than 100% with Collabora Online 6.4.8.6 (git hash ba528af)
- The Android App on a OnePlus 8T. Version 6.4.3 (git hash eec532f9d)

This renders spreadsheet editing unusable.

**Comment by nikslor** [comment]
I can't reproduce this issue on 21.6.1 (2) anymore; I think we can close this one. @WurstMitDurst could you also briefly check with a current build?

**Comment by nikslor** [comment]
I'll close it for now, feel free to re-open @WurstMitDurst if it's not fixed for you.
