### ISSUE TITLE
iOS-App: Impress: Blank screen when adding slide withoug pressing edit button

### ISSUE THREAD

**Issue by smirta** [CollaboraOnline/online#1881]
**Describe the bug**
A blank screen appears if the icon for adding a new slide at bottom left is clicked.

**To Reproduce**
![video](https://user-images.githubusercontent.com/6649852/112954931-2e425b80-913f-11eb-8f54-1c566b6037d4.mp4)

**Expected behavior**
The button is not clickable or a hint appears that the document has to put in edit mode.

**Actual behavior**
A blank screen appears.

**Smartphone**
 - Device: iPad
 - OS: iPadOS 14.3
 - Collabora Office
 - Version: 6.4.8 (2) from Testflight

**Comment by thebearon** [comment]
As i can see, you clicked on the full-screen presentation button with an empty presentation (it even highlights the button for a split second at 0:09), the blank screen is thus expected. Please retest and confirm if that is the case.

**Comment by smirta** [comment]
Oh lord, yes, you're absolutely right. I'll go shame myself. Sorry for the fuss.
