### ISSUE TITLE
iOS-App: Impress: Copy & paste of text box does not work as expected

### ISSUE THREAD

**Issue by smirta** [CollaboraOnline/online#1882]
**Describe the bug**
If a text box on a slide is copied a text box of the same size is pasted filled with default color and contents has lost its formatting.

**To Reproduce**
1. Long press on text box
2. Click on 'Copy'
3. Long press somewhere on the slide
4. Click on 'Paste'

**Expected behavior**
Same text box is pasted.

**Actual behavior**
Text box of same size with default background color is pasted, formatting of contents is lost.

**Screenshots**
https://user-images.githubusercontent.com/6649852/112961753-f25ec480-9145-11eb-9a8b-ce26368a85e6.mp4

**Smartphone (please complete the following information)**
 - Device: iPad
 - OS: iPadOS 14.3
 - Collabora Office
 - Version: 6.4.8 (2) from Testflight

**Comment by thebearon** [comment]
Confirmed with iOS app version 6.4.8 (2), seems like it's something specific to the iOS app, I couldn't reproduce it in web-based online.

**Comment by tml1024** [comment]
I am not sure if I can reproduce in 6.4.12(1) from TestFlight, but possibly I am not doing it right. Exactly what formatting is it that is lost? When I paste a text box, for instance a word that is bold in the original is bold in the copy, too, and paragraphs that are right-aligned stay that way. But the size of the text does change for some reason. Is that the remaining issue? See screen capture.

https://user-images.githubusercontent.com/310731/133075266-25ddb4b6-68a6-483e-96ce-9cd772da3230.mov

**Comment by nikslor** [comment]
I can still reproduce this in 22.05.11 (22.5.202303212054), see video:

https://user-images.githubusercontent.com/1211300/227887956-9d63c222-ae41-4772-b1f4-c03d6e35027b.mp4

**Comment by Darshan-upadhyay1110** [comment]
Works fine now.

COOLWSD version: 24.04.6.2 (git hash: 7bb21429)
LOKit version: Collabora OfficeDev 24.04.6.2 (git hash: 321166f)
Served by: Ubuntu 23.10
Server ID: 9fd431d3
