### ISSUE TITLE
IOS App: SendTo for and App does not open the document in the Collabora App 

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#1885]
**Describe the bug**
When performing a SendTo from an App to the Collabora App the file is not opened but the Collabora App just shows the "file explorer" start screen as if one normally gets to see when the App is launched.

**To Reproduce**
1. Go to 'email app'
2. Click on and email with attachement and click the attachement (.odt file for example)
3. The IOS action screen pop's up so a destination app can be selected to Send the file To: select Collabora Office (could be you need to click More first).
4. The Collabora Office Start-Screen shows up (where you can select file Locations etc)  

**Expected behavior**
I would expect the send file would be opened in the App.

**Actual behavior**
The Collabora Office Start-Screen shows up (where you can select file Locations etc)  

**Screenshots**
nothing to see, just the The Collabora Office Start-Screen shows up (where you can select file Locations etc)  

**Smartphone (please complete the following information)**
 - Device: iPhone X
 - OS: [e.g. iOS14.4.2
 - Collabora Office 6.4.8, same issue with previous builds.

**Additional context**
If users have no other file viewers/editor then CO on their phone the Send To should open the file to be able to read like attachements in email send to the App.

**Comment by tyreun** [comment]
Hi,

I agree with you. It's the same bug that #1817

**Comment by tyreun** [comment]
hi,

This issue is not solved with the last release 6.4.7-3

Regards

**Comment by Ezinnem** [comment]
I can reproduce this issue using 6.4.13 (git hash: cea7112d)

**Comment by sebastiaanveld** [comment]
Issue is still there in App 21.06.1.0 (Testflight)
Let's close this ticket and continue it at #1817
