### ISSUE TITLE
Dockerhub latest tag is gone

### ISSUE THREAD

**Issue by stavros-k** [CollaboraOnline/online#1908]
**Describe the bug**
The tag `:latest` is no longer available in dockerhub.  
Now you have to check in docker hub every time to find out if a newer tag is available. 

**To Reproduce**
1. Go to dockerhub
2. Click on tags
3. You can't see latest tag

**Expected behavior**
`docker pull collabora/code` to work

**Actual behavior**
```
root@Prometheus:~# docker pull collabora/code
Using default tag: latest
Error response from daemon: manifest for collabora/code:latest not found: manifest unknown: manifest unknown
```

**Comment by yunusem** [comment]
Hey @stavros-k , what architecture are you pulling on, general amd64 ? Starting yesterday we only support amd64 and arm64 architectures regarding docker.

**Comment by stavros-k** [comment]
Silly me,, forgot to mention! I'm pulling on an amd64 / unraid OS.

**Comment by yunusem** [comment]
@stavros-k No worries, it should be working already, do you mind confirming :)

**Comment by stavros-k** [comment]
Yes, it does! Thanks
