### ISSUE TITLE
Drag cells

### ISSUE THREAD

**Issue by ChameleonScales** [CollaboraOnline/online#1917]
It would be great to have the possibility to move cells by selecting and dragging them.

In LO Calc you do it by clicking and dragging from inside the selection.
I don't know if that would conflict with another function in Collabora but if so, we could either do it the Excel way (clicking on the edge of the selection) or instead use a modifier key like <kbd>Ctrl</kbd> (I think <kbd>Alt</kbd> should not be used because LO uses it for a shifting kind of move so we should keep that key for a possible future implementation) or even have a dedicated move tool in the toolbar (with e.g. a “four arrows” icon: ✢)

Forum topic this issue originated from: https://forum.collaboraonline.com/t/drag-cells-to-move-them/229/2

**Comment by n-davies** [comment]
Yes! As a long time LO user I spent some time trying to find this feature only to now discover it is not (yet) implemented.

**Comment by timur-g** [comment]
I assume this was reported for 21.11 and that really did not work then. 
But it works now in 23.05.7. So I close.
