### ISSUE TITLE
deprecated use of apt-key in linux install documentation

### ISSUE THREAD

**Issue by thkoch2001** [CollaboraOnline/online#1934]
I did not find a better place to report a minor issue on this page:

https://www.collaboraoffice.com/code/linux-packages/

The Debian and Ubuntu installation instructions make use of the command `apt-key` which is deprecated. Also it is not good practice to add non-debian repositories to /etc/apt/sources.

The recommended way is:

1. Download the collaboraonline archive public key to `/usr/share/keyrings/collaboraonline-archive-keyring.gpg`.
2. Add the following lines into `/etc/apt/sources.list.d/collaboraonline.sources`:

```
Types: deb
URIs: https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-debian10
Suites: ./
Signed-By: /usr/share/keyrings/collaboraonline-archive-keyring.gpg
```

These instructions are also easier to put under configuration management as no command needs to be executed and no preexisting file needs to be changed.

More documentation:

- https://wiki.debian.org/DebianRepository/UseThirdParty
- [man 5 sources.list](https://manpages.debian.org/buster/apt/sources.list.5.en.html) - for the not so common data sources file format

**Comment by pedropintosilva** [comment]
Thanks for reporting it @thkoch2001 !

**Comment by pedropintosilva** [comment]
so I guess we should also update this: https://github.com/CollaboraOnline/online/blob/master/docker/from-packages/scripts/install-collabora-online-ubuntu.sh

**Comment by timar** [comment]
> so I guess we should also update this: https://github.com/CollaboraOnline/online/blob/master/docker/from-packages/scripts/install-collabora-online-ubuntu.sh

Maybe. I'll check.

**Comment by timar** [comment]
- [ ] https://www.collaboraoffice.com/code/linux-packages/
- [ ] Collabora Online Installation Guide
- [ ] Customer Portal
- [ ] docker creation scripts
