### ISSUE TITLE
Collabora Office Snapshot 6.4.99 in F-Droid incompatible with Android 6.0

### ISSUE THREAD

**Issue by Leif-W** [CollaboraOnline/online#1956]
**Describe the bug**
Collabora Office Snapshot 6.4.99 in F-Droid incompatible with Android 6.0

**To Reproduce**
1. Go to Android 6.0 device
2. Go in F-Droid app
3. Add Collabora repo
4. Search for "Collabora Office"
5. See two options
6. Version 6.4.3 can be installed but 6.4.99 can not.

**Expected behavior**
Expect 6.4.99 to install.  Otherwise, expect a note in the description notifying that Android 6.0 support has been dropped.  If support being dropped, some prominent announcement should be made, and persistent references, on site, announcement blog, in forums, in README.md, or something.  Trying to search commit messages and diffs and tags to find the exact moment support was dropped or became broken, along with reason, is tedious.

**Actual behavior**
Version 6.4.99 installation failed for unknown reason.

**Smartphone**
 - Device: SM-N910W8 Samsung Galaxy Note 4 (Qualcomm Snapdragon not Samsung Exynos CPU)
 - OS: Android 6.0
 - Browser: Brave
 - Version: ???  Not sure what version is asked.

**Comment by Ezinnem** [comment]
@Leif-W, please do you experience a similar issue on the updated Collabora Office 21.11 version as well?

**Comment by Leif-W** [comment]
Listed as "Collabora Office 6.4" with 3 versions"22.11.5.3", of which 2 are tagged "Incompatible" in red, and the third is tagged "Suggested" in grey.  Attempting to install by clicking F-Droid's big "Instsll" button gives a warning that the version is incompatible with my device.  Ignoring the warning and choosing "yes" for "Ateempt to install anyway" ends up with an error dialog with 2 lines of text: "Error installing Collabora Office 6.4" and "Failed to install due to an unknown error."  Expanding the "Suggested" version and choosing install shows the expected APK Installer dialog, with text "Installing".   The install seems to have succeeded, but F-Droid insists that it is incompatible.  If the app proper appears to be working, then the confusion at this point might be with the way the F-Droid package is set up.  It should behave in such a way that only the compatible version is installed, and should not flag app as incompatible as long as one build is compatible, ignoring the others.

**Comment by timur-g** [comment]
This is old and current Android app id 23.05.

**Comment by Leif-W** [comment]
Sorry for the late reply.  Just wanted to confirm that Collabora installed version 23.05.4.1 from F-Droid on Android 6.0.1.
