### ISSUE TITLE
IOS App: there is no (visible) Back- or Exit-button in the New File window

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#1962]
Describe the bug
If a user (accidentally) clicks the New File button in the Start window of the App there is no (visible) back or exit-button, so the only way to get out of this window is to either create a new file by selecting one of the file types, or force-close the App.

To Reproduce

- Start the Collabora Office App
- In the Start window click the + button to create a new file
- The New File window pops up and shows the file types that can be created from here
- If the user decides this is not what he/she wanted, there is no (visible) Back-button to leave this window.
- One has to go forward and create a new file, or Force-close the App

Expected behavior
I would expect a Back-button in the (upper-left) corner which brings the user back in the Start-window

Actual behavior
A user is forced to create a new file, case they do not now about Force-closing the App, and has to close the viewer/editor screen leaving an empty "...new file..." in the Start window which they the have to delete. Not a really friendly workflow.

Screenshots

![afbeelding](https://user-images.githubusercontent.com/37268999/114271248-bb739300-9a10-11eb-8d0c-73e21d5ecffa.png)

Smartphone (please complete the following information)

    Device: iPhone X
    OS: [e.g. iOS14.4.2
    Collabora Office 6.4.8 (2)

Additional context
-

**Comment by thebearon** [comment]
Confirming that this issue is still there in the app version 6.4.11 (1).

**Comment by tml1024** [comment]
I remember I tried to fix this problem a long time ago, and it was surprisingly hard, and more urgent tasks intervened, so it is still there.

**Comment by plubius** [comment]
So I have a partial fix: tapping outside of the "create new file" dialog will now dismiss the dialog. I don't know if it will work on an iPhone (does the dialog fill the entire screen?) but now that I have figured out how to get the dialog to be dismissed without creating a new document, I have adding a "cancel" or "done" button to the dialog.

**Comment by sebastiaanveld** [comment]
On iPhone the file dialog is full screen.

![5D187B09-5C9C-4B66-A6C6-8C8D74848C4C](https://user-images.githubusercontent.com/37268999/226062567-61dc6dc3-95b4-4f75-87f5-0b9b90d7c893.png)

**Comment by plubius** [comment]
I was able to splice a [native "navigator bar"](https://user-images.githubusercontent.com/104370511/226073318-40bd957d-0864-4d52-b997-0c4ac711ec51.png) into the dialog. The navigator bar comes with a fully localized cancel button (a "done" button sounds strange to me here as you can't actually do anything in this dialog other than tap an icon).

**Comment by sebastiaanveld** [comment]
Agree a Cancel button is sufficient. Happy you got this one figured out, thx!

**Comment by sebastiaanveld** [comment]
Successfully tested fix in TestFlight build 22.5.11 (22.5.202303212054)
