### ISSUE TITLE
Sometimes taking very LONG time to open documents

### ISSUE THREAD

**Issue by Thewisem** [CollaboraOnline/online#1966]
**Describe the bug**
Sometimes the document will open within a short period of time. Sometimes the document will take a LONG period of time and I have to close the app and open it again

**To Reproduce**
1. Go to documents
2. Click on any document
3. Just let it open

**Expected behavior**
It would take equal time to opwn any document.

**Actual behavior**
A clear and concise description of what actually happens.
Irregular opening time
**Screenshots**

**Desktop (please complete the following information)**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information)**
 - Device: [e.g. iPhone6] Samsung Galaxy Tab A
 - OS: [e.g. iOS8.1] Android Version 7 Nougat
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22] 6.4

**Additional context**

**Comment by Ezinnem** [comment]
The Collabora Office app version 6.4.13 was released recently. This seems not to occur in this new version.

@Thewisem, please can you update your Collabora Office app version and test it again?

**Comment by Ezinnem** [comment]
Closing this issue due to no response from the author.
