### ISSUE TITLE
Notebookbar: use the same margins and paddings across all tabs

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2007]
**Describe the bug**
Currently we have different layouts (different html) with different
- top margins
- bottom margins 
- inner margins

![image](https://user-images.githubusercontent.com/65948705/114837938-81b9d800-9dd4-11eb-85b1-35aa4a2f8aca.png)

**Comment by Andreas-Kainz** [comment]
My idea is to have everywhere, or at the first step, at the json tabs the same structure, so that if something in the css file was change, it will be changed everywhere and will be consistent. Also if the structure is everywhere the same, an issue from the code has to be changed only one time.

### Notebookbar Tab JSON Structure

![Section](https://user-images.githubusercontent.com/8517736/115877322-98e96d00-a447-11eb-8625-6d8f125a5ee4.png)

````
getInsertTab: function() {
		var content = [
			{
				'type': 'bigtoolitem',
				'text': _UNO('.uno:InsertPage', 'presentation'),
				'command': '.uno:InsertPage'
			},
			{
				'id': 'Insert-Section-Pages',
				'type': 'container',
				'children': [
					{
						'id': 'Insert-DoplicatePage',
						'type': 'toolbox',
						'children': [
							{
								'type': 'toolitem',
								'text': _UNO('.uno:DuplicatePage', 'presentation'),
								'command': '.uno:DuplicatePage'
							}
						]
					},
					{
						'id': 'Insert-SelectBackground',
						'type': 'toolbox',
						'children': [
							{
								'id': 'selectbackground',
								'type': 'menubartoolitem',
								'text': _UNO('.uno:SelectBackground', 'presentation'),
								'command': ''
							}
						]
					}
				],
				'vertical': 'true'
			},
		];

		return this.getTabPage('Insert', content);
	},
````
This structure as the benefit that it also work if there are more than one command and as @eszkadev  has in mind to simplify the json structure, it will be also very usefull, when the structure is everywhere the same.

**Comment by pedropintosilva** [comment]
Thanks @Andreas-Kainz for pasting that here! as I said in our meeting this sounds very promising and a good direction to aim for. (this, hopefully, all those quirkinesses will be easier to target/fix

**Comment by Andreas-Kainz** [comment]
what would be nice is, that the tab content (all togheter) can be vertical center align. Now there is something like in notebookbar.css, which should be removed.

```
#table-File.notebookbar
{
	margin-top: 10px;
}
```

**Comment by Andreas-Kainz** [comment]
So there is only one open point

```
{
    'type': 'container',
    'children': [
        {
            'type': 'toolbox',
            'children': [
                {
                    'type': 'toolitem',
                    'text': _UNO('.uno:InsertTable', 'text'),
                    'command': '.uno:InsertTable'
                }
            ]
        },
        {
            'type': 'toolbox',
            'children': [
                {
                    'type': 'toolitem',
                    'text': _UNO('.uno:InsertGraphic'),
                    'command': '.uno:InsertGraphic'
                },
                {
                    'type': 'toolitem',
                    'text': _UNO('.uno:InsertPagebreak', 'text'),
                    'command': '.uno:InsertPagebreak'
                }
            ]
        }
    ],
    'vertical': 'true'
},
```
the first row with only one element and is 28px height, the second row with two elements is 32px height.

![Screenshot_20210502_173157](https://user-images.githubusercontent.com/8517736/116819154-021b5f80-ab6f-11eb-95e0-b33e3b5bec06.png)
![Screenshot_20210502_173227](https://user-images.githubusercontent.com/8517736/116819157-06e01380-ab6f-11eb-8836-d0c93e1e4afe.png)

would be perfect if, when there is only one element the element is also within a cell notebookbar so all elements are always 32px in height.
