### ISSUE TITLE
Mobile: Create new top bar comment icon

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#202]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**

The current icon used in the mobile for comment is with a plus denoting the "insert comment" but now @lpranam is working on a way to also use it to trigger to view comments (it will open the bottom wizard displaying existent comments and with possibility to insert from there) 

:point_right: : Create new icon that replaces the existent "insert comment" asset
:round_pushpin: : `images/lc_insertcomment.svg`
:page_facing_up: : assigned in toolbar.css:765

**Comment by mallikarjun2000** [comment]
Hello,
I would like to work on this issue can you assign it to me please?

**Comment by mrkara** [comment]
> Hello,
> I would like to work on this issue can you assign it to me please?

Hi @mallikarjun2000 ! :)

It is very nice to see that you are interested in solving this issue. Please feel free to go ahead and send a pull request. No need to wait for assignment.

**Comment by pedropintosilva** [comment]
cool @mallikarjun2000 !
Here are some steps to help you get everything setup:
:building_construction:  [How to build it](https://collaboraonline.github.io/post/build-code/)
:speaker:  [Check out our forum for more info](https://forum.collaboraonline.com/t/your-first-pull-request/41)
:speaking_head: [Chat with the community](https://collaboraonline.github.io/post/communicate/)

**Comment by mallikarjun2000** [comment]
I though this was made on windows. I don't have a linux machine couldn't resolve the issue.

**Comment by pedropintosilva** [comment]
oh sorry to hear that @mallikarjun2000 I will update either the Build and maybe the FAQ page as well to avoid this in the future. Thanks anyhow, you already contributed by raising awareness on this : ) !

**Comment by mrkara** [comment]
@mallikarjun2000 You no longer need to be on Linux to work on Collabora Online! :)

Just head over here for quick start instructions please: https://forum.collaboraonline.com/t/start-developing-cool-on-any-platform-in-5-minutes/52

And feel free to ask your questions if you bump into any problems. ;)

**Comment by mallikarjun2000** [comment]
> 
> 
> @mallikarjun2000 You no longer need to be on Linux to work on Collabora Online! :)
> 
> Just head over here for quick start instructions please: https://forum.collaboraonline.com/t/start-developing-cool-on-any-platform-in-5-minutes/52
> 
> And feel free to ask your questions if you bump into any problems. ;)

Thanks, I will once check the instructions and start working.
