### ISSUE TITLE
Help: Create new icons: Keyboard shortcuts, Latest updates

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2026]
Currently, using notebookbar, we have two icons that feel a bit out of place an need some love:
![image](https://user-images.githubusercontent.com/65948705/115019173-1eee3c80-9eb9-11eb-8da0-ead3478ed0f8.png)

- [ ] Create new `loleaflet/images/lc_latest-updates.svg`
- [x] Create new `loleaflet/images/lc_keyboard-shortcuts.svg`

**Comment by pedropintosilva** [comment]
to enable it `loolwsd.xml` turn welcome message to true:

```xml
<welcome>
  <enable type="bool" desc="Controls whether the welcome screen should be shown to the users on new install and updates." default="false">true</enable>
  <enable_button type="bool" desc="Controls whether the welcome screen should have an explanatory button instead of an X button to close the dialog." default="false">true</enable_button>
  <path desc="Path to 'welcome-$lang.html' files served on first start or when the version changes. When empty, defaults to the Release notes." type="path" relative="true" default="loleaflet/welcome"></path>
</welcome>
```

**Comment by Andreas-Kainz** [comment]
icon update isn't a big deal, will update asap.

Would be nice if the commands could use bigtoolitem, we will see if we can fix this also.

**Comment by Andreas-Kainz** [comment]
![Screenshot_20210429_211902](https://user-images.githubusercontent.com/8517736/116606135-8fbd3c00-a930-11eb-8b41-37e44ef74fa9.png)

can I use the collabora online app icon for latest updates? we can use the icon which is left next to File?

**Comment by Andreas-Kainz** [comment]
As Latest Updates linke to the webpage from collabora online, I would prefer to use the collabora brand icon and not depend on if you have code or an enterprise release.
