### ISSUE TITLE
NB: Review: Tacking changes nav buttons are always active

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2027]
**To Reproduce**
1. Open a document with track changes turned off
2. `PreviousTrackedChange` and `#NextTrackedChange` are clickable

**Expected behavior**
Tacking changes nav buttons should be inactive
 
**Screenshots**
![image](https://user-images.githubusercontent.com/65948705/115019984-337f0480-9eba-11eb-8d8d-f488f9106abf.png)

**Comment by Darshan-upadhyay1110** [comment]
Works okay in latest version.

COOLWSD version: 24.04.5.2 (git hash: df56d78c)
LOKit version: Collabora OfficeDev 24.04.5.2 (git hash: b57fd97)
Served by: Ubuntu 23.10
Server ID: 0dc2679d
