### ISSUE TITLE
Writer table formulas not implemented

### ISSUE THREAD

**Issue by glitchnopanic** [CollaboraOnline/online#2044]
**Describe the bug**
Well it is not actually a bug, I suspect it has not been implemented yet: Inability to enter formulas in Writer tables
(Edit: This is the version 6.4.7snapshot git hash: f914d9d)

**To Reproduce**
Online > Writer > new document > Insert new table 1x3 > 
Enter any number in top and middle cells >
In bottom cell type =sum(  
(see expected behaviour 1 after the = key is pressed)
Then with the mouse select the top and middle cells  (see expected behaviour 2)

**Expected behaviour**
Expected behaviour 1: As soon as = is entered I would expect to see the formula entry bar appear at the top under existing toolbars.
Expected behaviour 2: When the mouse is clicked on the top cell the cell number to appear in the bottom cell

**Actual behaviour**
As described above.

**Desktop (please complete the following information)**
 - Chrome OS
 - Browser: Chrome
 - Version: 89.0.4389.116

**Additional context**
I assume this is not implemented in CODE yet, reporting it for the record.

**Comment by thebearon** [comment]
Yes, there were issues with it, and would have required more work, thus it was disabled for the time being.
A reference: https://bugs.documentfoundation.org/show_bug.cgi?id=130785

**Comment by glitchnopanic** [comment]
Thank you for your reply,  Rob

**Comment by glitchnopanic** [comment]
> Yes, there were issues with it, and would have required more work, thus it was disabled for the time being.
> A reference: https://bugs.documentfoundation.org/show_bug.cgi?id=130785

Hi,  the odd behaviour reported in https://bugs.documentfoundation.org/show_bug.cgi?id=130785 is resolved in 6.4.9, this odd behaviour was my driver to report it. I guess id=130785 got incorporated/backported.

Anyway:   I have just discovered that "Support Formulas in CollaboraOnline textdocuments #736" exists and is worded much better, please will you close this issue as a duplicate of #736.  I'll go away and try to learn how to use the github Search, I don't know why I didn't see it before :-)

**Comment by glitchnopanic** [comment]
I just noticed that I can close the issue myself.  Reason:  duplicate of #736
