### ISSUE TITLE
CODE 6.4.7: Possible data exposure: The common copy/paste keybord shortcut Ctrl-Ins ("Copy") doesn't work properly (at least in Calc)

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#2054]
**Describe the bug**
Usually, in Windows and Linux you can use the hotkeys:

* Ctrl-Ins: Copy selection to Clipboard
* Ctrl-Del: Cut selection and store in Clipboard
* Shift-Ins: Insert Clipboard contents at cursor position (and possibly replace any existing selection)

CODE version:

LOOLWSD
6.4.7 (git hash: 4f68c25)
Angeboten von: 5db4dff8
LOKit
Collabora Office 6.4-33 (git hash: bec78a8)
"Ubuntu 18.04.5 LTS"

**To Reproduce**
1. Enter some text somewhere in Calc
2. Press Ctrl+Ins to copy it to the Clipboard
3. Select different cell or position in some text field in Calc
4. Press Shift+Ins to paste into the cell or text field

**Expected behavior**
The Clipboard content should be defined by the Ctrl+Ins keypress and the Clipboard contents should be pasted by the Shift+Ins keypress.

**Actual behavior**
The Ctrl+Ins keypress is ignored, but Shift+Ins then pastes any previous clipboard contents just fine, possibly exposing sensitive data publicly into the shared sheet.

Ctrl+Del also seem to work to cut to Clipboard, so only Ctrl+Ins seems to be broken - but I'm not sure if those other keys work reliably.

**Desktop (please complete the following information)**
 - OS: Ubuntu 20.04 x64 (KDE neon with KDE Plasma Desktop)
 - Browser: Chromium
 - Version: Version 89.0.4389.90 (Offizieller Build) Built on Ubuntu , running on neon 20.04 (64-Bit)

**Comment by Ezinnem** [comment]
The key combinations work nicely on my end. I tested using LOOLWSD 6.4.10snapshot (git hash: [b373871](https://github.com/CollaboraOnline/online/commits/b373871)).

@gohrner, Please can you test again using the 6.4.10 version?

**Comment by gohrner** [comment]
Indeed, this was fixed, I'll then close this issue.

Somehow, many bugs reported here get fixed "silently", i.e. are probably reported in a different way and get closed, without the report here being noticed... It would be good to have a closer link between this apparent "internal" issue tracking system and the publicly created reports here...
