### ISSUE TITLE
CODE 6.4.7/6.4.8: Pasting a copied column into another column causes table headers to get out-of-sync

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#2057]
**Describe the bug**
See screencast - copy a column, paste it into another column, and the table headers will not be adjusted correctly, losing sync.
Can be re-synced by resizing the column manually.

CODE version:

LOOLWSD
6.4.7 (git hash: 4f68c25)
Angeboten von: 5db4dff8
LOKit
Collabora Office 6.4-33 (git hash: bec78a8)
"Ubuntu 18.04.5 LTS"

**To Reproduce**
See example:

![CODE_Calc_6 4 7_Copy_Paste_Sheet_Header_Out_of_Sync](https://user-images.githubusercontent.com/26199042/115372431-2a987680-a1cb-11eb-964c-0c7191543499.gif)

**Expected behavior**
Sheet headers / table headers should match the table's columns.

**Actual behavior**
Sheet headers / table headers do not match the table's columns.

**Screenshots**
See above.

**Desktop (please complete the following information)**
 - OS: Ubuntu 20.04 x64 (KDE neon with KDE 5 Plasma Desktop)
 - Browser: Chromium
 - Version: Version 89.0.4389.90 (Offizieller Build) Built on Ubuntu , running on neon 20.04 (64-Bit)

**Comment by thebearon** [comment]
I can't reproduce this in a fresh 6.4 build, but I can see that after selecting and resizing a column, the next column's header is incorrectly highlighted (eg. select and increase column A's width, then both column A and B's header appear to be selected).

@gokaysatir, could you check if your experience is the same?

**Comment by gohrner** [comment]
The original misbehaviour is not present any more in 6.4.8, it now misbehaves somewhat differently. ;)

@thebearon , I can confirm that the selection is not correct after pasting.

Much worse, if you "undo" the copy operation then, the headers are totally messed up, i.e. all have standard width, and the cell's also look as if they do, but the cell selection and cursor don't:

![Peek 2021-04-27 18-42](https://user-images.githubusercontent.com/26199042/116279911-6b266000-a788-11eb-8f5c-28a940fc03ef.gif)

**Comment by rpear** [comment]
I confirm that this is still a problem in CODE 6.4.10. Note that double clicking a cell header fixes it all up again. I tested in CODE 6.4.10. I am using Chrome Version 91.0.4472.114 (Official Build) (64-bit) on a Chromebook CODE: 6.4.10snapshot (git hash: 94a1a06) Served by: 492fe155, commits on Jul 5, 2021.
![Screenshot 2021-07-07 10 32 19 AM](https://user-images.githubusercontent.com/80790599/124682753-ee91c980-df0e-11eb-9c3d-ebe8b1e18929.png)

**Comment by gohrner** [comment]
@rpear , @thebearon : Copy-paste seems to be fixed for me in

LOOLWSD
6.4.10 (git hash: 7151e02)
Angeboten von: 5a0f0788
LOKit
Collabora Office 6.4-45 (git hash: a21347f)
"Ubuntu 18.04.5 LTS"


What's your experience?

**Comment by Ezinnem** [comment]
The Copy-paste works fine for me using:

LOOLWSD
6.4.10 (git hash: [d12ab86](https://github.com/CollaboraOnline/online/commits/d12ab86)).
