### ISSUE TITLE
CODE 6.4.7/6.4.8: Wrong Keyboard Focus When Renaming Calc Sheet, Causes Cell Data to be Overwritten

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#2058]
**Describe the bug**
When renaming a Calc sheet by double-clicking the sheet's tab causes the keyboard focus to stay in the sheet cell (which actually if somewhat "grayed out" and should probably be protected against modifications in this state). Entering a new name will then instead overwrite the sheet cell's contents.

CODE versions:

> LOOLWSD
> 6.4.7 (git hash: 4f68c25)
> Angeboten von: 5db4dff8
> LOKit
> Collabora Office 6.4-33 (git hash: bec78a8)
> "Ubuntu 18.04.5 LTS"

> LOOLWSD
> 6.4.8 (git hash: 4aa2794)
> Angeboten von: 933fb759
> LOKit
> Collabora Office 6.4-36 (git hash: 3d919ce)
> "Ubuntu 18.04.5 LTS"

**To Reproduce**
1. Double click sheet tab to rename the sheet.
2. Enter a new sheet name *without* explicitly clicking into the rename dialog to set the focus there manually.

**Expected behavior**
The new sheet name will be entered into the dialog.

**Actual behavior**
The entered text ends up in the sheet cell, the sheet's name in the dialog stays unchanged.
Clicking "Cancel" in the dialog does not help, the sheet cell's contents are still overwritten.

**Screenshots**
![CODE_Calc_6 4 7_Wrong_Focus_and_Overwriting_of_Background_Data_When_Renaming_Sheets](https://user-images.githubusercontent.com/26199042/115373594-52d4a500-a1cc-11eb-80d0-0b9c85b1b929.gif)

**Desktop (please complete the following information)**
 - OS: Ubuntu 20.04 x64 (KDE neon with KDE 5 Plasma Desktop)
 - Browser: Chromium
 - Version: Version 89.0.4389.90 (Offizieller Build) Built on Ubuntu , running on neon 20.04 (64-Bit)

**Comment by rpear** [comment]
@gohrner I have tested this in CODE 6.4.10 and it works OK, perhaps it has now been fixed, can you test it again in 6.4.10?
For the record, I tested renaming a sheet in CODE 6.4.2 and the Chromebook Collabora Office 6.4.3. app and renaming was OK, but that will be because you had to right click to rename, I guess double clicking functionality was probably added after 6.4.3.

**Comment by gohrner** [comment]
> @gohrner I have tested this in CODE 6.4.10 and it works OK, perhaps it has now been fixed, can you test it again in 6.4.10?

I downgraded to 6.4.9 again because 6.4.10 was unusable for me mainly due to the significant cell comment performance regression and the data loss issues.

I'll retry after some bugfix releases...

**Comment by gohrner** [comment]
Addendum: It also works fine at least with 6.4.9, so yes, apparently is was fixed.
