### ISSUE TITLE
Classic mode: Toolbar: Remove extra separators

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2071]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @pedropintosilva 

### Detailed description and rationale
In the toolbar while running classic mode: 
We currently create some toolbar menu items if and only if certain features/actions are available. However separators are wrongly always visible even if they do not separate nothing.
### Code pointers
- Make sure we are running classic mode: by changing `user_interface` in `loolwsd.xml` to `classic` like so:
```
    <user_interface>
      <mode type="string" desc="Controls the user interface style (classic|notebookbar)" default="classic">classic</mode>
    </user_interface>
```
- Only render separators if in presence of those extra menu items

![toolbar-menu-separator1](https://user-images.githubusercontent.com/65948705/115524008-f46ffb00-a28d-11eb-9d11-2178134f1109.png)
![toolbar-menu-separator2](https://user-images.githubusercontent.com/65948705/115524011-f5089180-a28d-11eb-879f-5b8404ab047e.png)

**Comment by codewithvk** [comment]
@pedropintosilva Can check this?
![temp2](https://user-images.githubusercontent.com/61119120/115590058-2add6280-a2ee-11eb-9462-bbedb1d436c1.png)
![temp2](https://user-images.githubusercontent.com/61119120/115590823-0635ba80-a2ef-11eb-9f72-944e3df2803b.png)

If I am wrong , Let me correct.

**Comment by codewithvk** [comment]
![temp2](https://user-images.githubusercontent.com/61119120/115593957-ca045900-a2f2-11eb-8dd4-6498b35d0ed3.png)

![temp](https://user-images.githubusercontent.com/61119120/115593961-cb358600-a2f2-11eb-8462-ef061f961ba6.png)


@pedropintosilva is its good looks for you?

**Comment by pedropintosilva** [comment]
Thanks @codewithvk ! So I think maybe in the File menu we can just do as you did ( to simply remove it ) but I'm afraid in the Tools menu we should test it with some integrator (Nextcloud, Owncloud etc) to make sure the separator appears if there is the additional item(s):

![image](https://user-images.githubusercontent.com/65948705/115663882-6ce3c400-a341-11eb-9cba-67d507dc53a6.png)

you can try to find where this is decided in the code, or I can check it and try to give you some code pointers. But anyhow I will test this PR and if in the File menu we can simply remove the separator then we can merge only that part and open a new PR for the rest.

**Comment by codewithvk** [comment]
@pedropintosilva Okey! I will create new PR for the rest and in this PR I will just change which was pointing you!
