### ISSUE TITLE
Toolbar-down: dropdown: Replace check-marks in favour of an active state

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2072]
* Checkmark icon is too big and stealing attention from the actual value
* We are forced to use smaller font due to the icon
* Suffering: overall alignment

**Where**

Dropdowns:
* tb_actionbar_item_zoom
* tb_actionbar_item_LanguageStatus

![image](https://user-images.githubusercontent.com/65948705/115534269-e7580980-a297-11eb-966f-15c276d69206.png)

**Pointers**
* Active state: remove check-mark, add background style
* Increase font size
* Make sure items are centred aligned

**Comment by rishikeshrane18** [comment]
if this issue is still open, can I work on this?

**Comment by Rash419** [comment]
@rishikeshrane18 sure you can work on it , I have assigned the task to you : )
Build intruction: 
https://collaboraonline.github.io/

If you need any help ping me : )

**Comment by Rash419** [comment]
any updates @rishikeshrane18  ? do you need any help ?

**Comment by akshatakulkarni25** [comment]
Hello @Rash419 is this issue still open?? can i work on it??
