### ISSUE TITLE
Create new Formatting Mark icon

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2073]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @pedropintosilva 

### Detailed description and rationale
Replace existent temporary icon for the dropdown `Formatting Marks`:

![image](https://user-images.githubusercontent.com/65948705/115535495-16bb4600-a299-11eb-9a9c-691f134b817b.png)

Located in Writer: Insert tab

![image](https://user-images.githubusercontent.com/65948705/115535950-88938f80-a299-11eb-9bfa-ad40fb9aa0fb.png)

* Create a completely new icon or improve current one:
  * by make elements more consistent (avoid dwarfing pilcrow)
  * balance out stroke width 
* Make it more at home with the other icons

**Comment by pedropintosilva** [comment]
@rizmut would you like to help with this? : )

**Comment by rizmut** [comment]
Have no idea what improvement should be made. Any clue from other office suites?

**Comment by pedropintosilva** [comment]
@rizmut you have full freedom here  :) this is what we are trying to do:
- Create a new icon that it's aesthetically more balanced
  - using the same radios and border thickness as other icons
  - avoid dwarfing typography elements (example: pilcrow)

> Any clue from other office suites?

No clue : p but feel free to try to hunt that down and if you think it makes sense to even post those screenshots as reference here : )

**Comment by rizmut** [comment]
Looking at the most used office suites, they just make use a standalone pilcrow. The drawback is of course user will associate it with paragraph.

**Comment by rizmut** [comment]
Here some other formatting marks on that could be used if we want to add another symbol

![image](https://user-images.githubusercontent.com/5697991/115999158-f0890380-a614-11eb-933b-87015055812b.png)

**Comment by rizmut** [comment]
WPS Writer:

![image](https://user-images.githubusercontent.com/5697991/115999280-60978980-a615-11eb-8aea-50fe87465183.png)

**Comment by rizmut** [comment]
FreeOffice TextMaker and ONLYOFFICE just use standalone pilcrow
![image](https://user-images.githubusercontent.com/5697991/115999366-9472af00-a615-11eb-814d-126d3437d905.png)

![image](https://user-images.githubusercontent.com/5697991/115999345-8886ed00-a615-11eb-8b15-67daa2d5f4aa.png)

**Comment by pedropintosilva** [comment]
I would be happy with something that conveys more than a pilcrow, be that something as we have now but better materialized or something along the lines of  this: https://github.com/CollaboraOnline/online/issues/2073#issuecomment-826342489

**Comment by rizmut** [comment]
some days ago @Andreas-Kainz made icon updates including this one. Please check it whether the newer icon is satisfying

**Comment by pedropintosilva** [comment]
This has been fixed as part of https://github.com/CollaboraOnline/online/commit/b1865b2b59dcfd55a786010474fe40e3abfee6bb
