### ISSUE TITLE
Can't scroll while on Format Cells Menu

### ISSUE THREAD

**Issue by stavros-k** [CollaboraOnline/online#2077]
**Describe the bug**
While using web editor (integrated with nextcloud)(Not the built in, i use external docker)

On `Format Cells` menu most of the dropdowns are not scrollable (e.g.) 
* on Numbers tab -> Language selection
* on Font Tab -> Family selection.

**To Reproduce**
1. Go to a spreadsheet
2. Right Click on a cell
3. Click Format Cells
4. Try to scroll any dropdown menu.

**Expected behavior**
Scroll to work

**Actual behavior**
Scroll not working

**Screenshots**
![image](https://user-images.githubusercontent.com/47820033/115586239-10e35600-a2d5-11eb-981d-84cef93b737c.png)

**Desktop (please complete the following information)**
 - OS: [e.g. iOS] Win 10
 - Browser: [e.g. chrome, safari] Chrome 
 - Version: [e.g. 22] Version 90.0.4430.72 (Official Build) (64-bit)

**Comment by Ezinnem** [comment]
I can confirm that the scrolling using the mouse scroll wheel does not work on 6.4.10snapshot (git hash: [25b2adb](https://github.com/CollaboraOnline/online/commits/25b2adb))

However, scrolling with dragging or moving the scrollbar works.

**Comment by stavros-k** [comment]
> However, scrolling with dragging or moving the scrollbar works.

Correct

**Comment by timur-g** [comment]
This was old behavior, works OK for me in 23.05.
