### ISSUE TITLE
Notebookbar: Home tab: positioning direct formatting icons

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2085]
We are having holes while not using space to separate different group of icons:
![image](https://user-images.githubusercontent.com/65948705/115679725-29925100-a353-11eb-9e33-e2513adfa1ed.png)

In Calc and Writer (the most flagrant cases) we can:
- add space before and after that specific group with half the size of the icon with (=16px)

In Impress there is not that much we can do without rethink other things
- but for now we could maybe just 2 times the previous space (=32px)

**Comment by Andreas-Kainz** [comment]
![2021-04-22 10_03_38-example ods - Dateien - Nextcloud](https://user-images.githubusercontent.com/8517736/115680826-382d3800-a354-11eb-8841-b4550dcd7893.png)

The plan is to have somewhere an end align element. will have to have a look to the css file.
