### ISSUE TITLE
Alignment of Color Picker preview icons

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2088]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @eszkadev @pedropintosilva @Andreas-Kainz 

The commands Color and Background color show an color preview, but as the svg icon wasn't hidded by the preview the icons are larger and non align.
![2021-04-22 11_35_05-ws-98adfbea-8ab4-4524-85e9-30b032202165_0 - noVNC](https://user-images.githubusercontent.com/8517736/115694120-d9ba8680-a360-11eb-8fbd-7baabcb5412b.png)

code pointer: https://github.com/CollaboraOnline/online/blob/a41ab8ff354900ade97b75a2ed8641140964c2a6/loleaflet/src/control/Control.NotebookbarBuilder.js#L420

**Comment by pedropintosilva** [comment]
Minutes (part just the ones related to this) from our meeting, @Andreas-Kainz :

Elements that needs some adjusting in size:

- [x] Style previews
- [ ] Text dropdown
- [ ] Button dropdown

Let's focus item by item
- Button dropdown
  - We need to add one more CSS class for it `has-dropdown` (Add class to parent of `hasDropdownArrow` element on JS)
  - Use class to adjust:
    - `selected-color` top position 
    - Update icon so it's still 24px but visually is shorter (accounting for `selected-color`)
    - Parent element can then have a height of 24px ensuring that everything is aligned

**Comment by pedropintosilva** [comment]
Unfortunately https://github.com/CollaboraOnline/online/commit/93bc5f6083291f28460ccc7fd6c4e6b6ff55112f add regression in classic mode:
