### ISSUE TITLE
Classic mode: Font and Style dropdown: allow previews

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2089]
this dropdown are on the client-side with text content, it's hard to get previews there but it would be nice to have them there at least in the long run: )

![image](https://user-images.githubusercontent.com/65948705/115708701-9bc55e80-a370-11eb-8337-7ac9b3d09d2b.png)

**Comment by thebearon** [comment]
The new JS-based sidebar has no previews, either.

**Comment by thebearon** [comment]
Tabbed view has a style preview section, and the font list also shows previews, this can be closed.
Compact view stays as is.
