### ISSUE TITLE
iOS App: adding line in writer, line ends are too big

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#2098]
**Describe the bug**
When I try to add a line to a writer document and want to change it into an arrow I run into the situation, that the line ends are too big.

![image](https://user-images.githubusercontent.com/1211300/115736829-e2748200-a38b-11eb-9491-fe0558d727bb.png)

**To Reproduce**
1. Open a writer document using the iOS app
2. Insert a line
3. Select the line and open the sidebar
4. Click on the selection for the line ends (arrows)

**Expected behavior**
The line endings should show completely

**Actual behavior**
The line endings are too big and don't show completely

**Tabplet**
 - OS: iPadOS 14.4.2
 - Version: 6.4.9 (1)

**Comment by nikslor** [comment]
FWIW: cant test with 21.6.1 (1) as the app crashes when inserting lines (#3297); I'll recheck with a later version as I expect, that this bug may be fixed thanks to the HTML/JS sidebar.

**Comment by nikslor** [comment]
Fixed in 21.6.1 (2)

![image](https://user-images.githubusercontent.com/1211300/135448686-11042432-df0d-46e9-b392-bccd176683b0.png)

Thanks a lot to the Collabora team for taking care of this and especially Tor to get "Draw > Line" working again (#3297)!

**Comment by nikslor** [comment]
@tml1024 do you want to close this one too?

**Comment by tml1024** [comment]
OK, closing.
