### ISSUE TITLE
Regular page crashes

### ISSUE THREAD

**Issue by floxxvi** [CollaboraOnline/online#2102]
Hello,

I've been using CODE through the cloud provider Webo hosting for some weeks now. The tool is great but I'm facing regular issues with its stability (whatever computer, internet provider, web browser etc I use). 

2 or 3 times a day (sometimes more, depending on how much time I spend on it), the page that I was working on - say a writer document - becomes unreponsive. The text cursor won't move where I click, and there's litterally nothing I can do to fix it, besides reloading the page. 

The problem is: since CODE only automatically saves documents every few minutes (sometimes very often, sometimes every 5-7 minutes), it may happen that I lose 5 minutes of work, because the page reloads the document to its state of the last save prior to the crash. And that can be a lot of work (meaning sometimes modifications on different parts of the document that I cannot track back). 

There doesn’t seem to be any action that triggers it, it looks like it happens randomly. 

Do you know of this issue and (if you do) is any fixing planned?

Thanks a lot for your help.
Best regards, 
Flo

**Comment by Ezinnem** [comment]
Closing this issue due to no response from the author.
