### ISSUE TITLE
Bugs in Themes and opening Documents from Telegram 

### ISSUE THREAD

**Issue by Ezee1015** [CollaboraOnline/online#2107]
Hello! I love the initiative of this app. In my experience I have found these bugs (at least with the application in Spanish):

         1.- When you change the theme of the application (Example: from light to dark) the box and the entire application are blocked. In order to continue using the application, you have to exit and re-enter.

         2.- When I try to open a .docx file from my personal Telegram channel, the first time it said "One moment please" or something like that. I left it for half an hour and it was still the same, so I closed it and left. The next day I tried again, but this time the application was blank. And from then on, the same thing always happens: the screen goes blank. In order to open a Telegram document, I have to open the document I want from the Telegram download folder from the Collabora application, and trying to guess which one it is.

I forgot to say that theses bugs I have it in Android 6.0. I hope that this bugs gets fixed. Thank you and greetings!

**Comment by nikslor** [comment]
I can't reproduce the first one on Android 10 using [todays](https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/collabora-office-mobile-6.4-snapshot-arm64-v8a-2021-05-27.apk) snapshot.

**Comment by nikslor** [comment]
I can't reproduce the second one on Android 8.1 using 6.4.8 (17 May 2021) from the Play Store.

**Comment by Ezee1015** [comment]
I'm using Android 6.0 in a Moto G3 and both still the same (With the application from Play Store), I tried to reinstall it, but it didn't changed anything. At the moment I'm using Onlyoffice, but I'm here to try anything you want to solve the problem with Collabora office.

**Comment by Ezinnem** [comment]
This issue does not seem reproducible on my end.


@Ezee1015, Please can you test again using the updated version of the Collabora Office app. 

You can also test using the daily snapshot from https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/

**Comment by Ezee1015** [comment]
I'm sorry. I forgot this open Issue. I've changed the phone to a newer one and I can't reproduce it. And, since I don't have my old phone anymore, I can't test this out again, so I will close this issue since I can't reproduce it anymore. Thank you and greetings!
