### ISSUE TITLE
uno:BasicShapes string Basic Shapes -> Shapes

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2111]
**Describe the bug**
`.uno:BasicShapes` use as Label _Basic Shapes_ but contain:
- Basic Shapes
- Symbol Shapes
- Block Arrows
- Stars and Banners
- Callouts
- Flowchart

so way more than "only" Basic Shapes.

![2021-04-23 10_52_23-ws-b2262f6f-0d2a-4b68-b23b-2ad56157e4a1_0 - noVNC](https://user-images.githubusercontent.com/8517736/115846424-2c0fac00-a422-11eb-8bee-d070900dae2f.png)

I suggest to rename the string from _Basic Shapes_ to _Shapes_ only, cause if there are Basic Shapes, where are the non basic shapes?

**Comment by Andreas-Kainz** [comment]
@pedropintosilva in Addition shorter strings are always better.

**Comment by pedropintosilva** [comment]
yup it makes sense, I completely agree with you
