### ISSUE TITLE
Notebookbar better markup and css

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2121]
Thanks @Andreas-Kainz for creating this issue, let me give some context (from our meeting) so it's recorded somewhere:

This is a long term goal where at the end would be good to simplify the Notebookbar HTML structure so we can also move from fixed values to a more smart approach on the CSS side using for example CSS Grids or Flexbox.

- [ ] Simplified HTML (no tables)
- [ ] Cleanup the notebookbar.css (remove fixed values where possible)
- [ ] CSS: move to a smarter approach using CSS grids or Flexbox

**Comment by Andreas-Kainz** [comment]
### Icon size

For example the size of an icon should come from `bigtoolitem` which is defined as 32px icon
```
#SearchDialog.notebookbar img {
	height: 32px !important;
	width: 32px !important;
}
```

**Comment by pedropintosilva** [comment]
Thanks @Andreas-Kainz for creating this issue, let me give some context (from our meeting) so it's recorded somewhere:

This is a long term goal where at the end would be good to simplify the Notebookbar HTML structure so we can also move from fixed values to a more smart approach on the CSS side using for example CSS Grids or Flexbox.
