### ISSUE TITLE
Notebookbar selected item layout

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2126]
If there is an command selected at the notebookbar, the icon background is gray and the label is black

![2021-04-24 00_41_44-ws-cdb0e9e9-e710-4615-863b-cac4f19fb659_0 - noVNC](https://user-images.githubusercontent.com/8517736/115936589-f3a9b580-a495-11eb-8b93-92441b9c3ffb.png)
Automatic Spell Check is selected and Word Count not

I suggested to a better layout for selected items

**Comment by Andreas-Kainz** [comment]
In classic mode the icon has a frame, which look similar to the dropdown for font name.

![2021-04-24 00_44_58-ws-cdb0e9e9-e710-4615-863b-cac4f19fb659_0 - noVNC](https://user-images.githubusercontent.com/8517736/115936723-513e0200-a496-11eb-924a-696a2f2cad5d.png)

**Comment by Andreas-Kainz** [comment]
The Notebookbar selection brand on the default nextcloud client

![2021-04-24 00_46_50-Welcome to Nextcloud Hub docx - Dateien - Nextcloud](https://user-images.githubusercontent.com/8517736/115936860-ada12180-a496-11eb-9bff-4e7d88b883f3.png)

**Comment by Andreas-Kainz** [comment]
I prefer how it look in LibreOffice, an blue frame with an transparent area fill setting. Maybe cool can use the app color for selection so blue in writer, green in calc, ...

![2021-04-24 00_47_56-Untitled 1 - LibreOfficeDev Writer](https://user-images.githubusercontent.com/8517736/115936902-cdd0e080-a496-11eb-82a8-bd09104e4f81.png)

**Comment by Andreas-Kainz** [comment]
additional space like in #1212 would be cool

**Comment by Andreas-Kainz** [comment]
Which color or variable should be used for select command? 

### App dependent color
*writer*
![2021-04-26 10_12_21-ws-1922949a-db85-4014-a53b-8917a344ad5b_0 - noVNC](https://user-images.githubusercontent.com/8517736/116051072-7f7b3780-a678-11eb-9a73-a0fefaf6cd60.png)
*calc*
![2021-04-26 10_13_41-ws-1922949a-db85-4014-a53b-8917a344ad5b_0 - noVNC](https://user-images.githubusercontent.com/8517736/116051080-8144fb00-a678-11eb-82f7-de872aa76759.png)
*impress*
![2021-04-26 10_10_47-ws-1922949a-db85-4014-a53b-8917a344ad5b_0 - noVNC](https://user-images.githubusercontent.com/8517736/116051047-79855680-a678-11eb-9770-c76900e96fec.png)

### use the highlight-color
![2021-04-26 11_00_46-ws-1922949a-db85-4014-a53b-8917a344ad5b_0 - noVNC](https://user-images.githubusercontent.com/8517736/116057099-bfddb400-a67e-11eb-93ec-9e506ea5041e.png)

**Comment by Andreas-Kainz** [comment]
code for notebookbar.css
```
.hasnotebookbar .ui-content.unotoolbutton.selected:not(.has-label):not(.inline) {
	border-radius: 2px;
	border: 1px solid rgb(30, 139, 205);
	background-color: rgb(30, 139, 205, 0.2);
}
```

**Comment by Andreas-Kainz** [comment]
What I like is, that the layout is similar to what our LibreOffice Windows users already know.

**Comment by pedropintosilva** [comment]
I think it's a nice idea : ) I just wonder how this can clash with current theming we are allowing integrators to have via the css vars (that currently affects that accent colour). we currently listened to the primary color from let's say NC and use it exactly in that place.

and I also wonder if changing that accent colour used here for communicating select status could go wrong (example when on impress things that are on will be somehow more near to red is might not be that good but maybe I'm being overly cautious)

and is it using the same colour from the TAB? (it should be using the css var) and how would it look on the switcher buttons?:

![image](https://user-images.githubusercontent.com/65948705/116061661-6926a900-a683-11eb-88f4-19db6b763447.png)

**Comment by Andreas-Kainz** [comment]
Select and switcher buttons should use the same color/layout. Hover the same. Like it's on LibreOffice desktop. 

The question is, shoul the color be app specific or use the primary color let's say NC.
