### ISSUE TITLE
Thesaurus work only in writer

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2129]
In the Notebookbar implementation at the Review Tab there is Thesaurus in writer, calc, impress/draw, but it work only in writer. Should Thesaurus be deactivated in calc, impress/draw @eszkadev?

### writer
![2021-04-24 21_30_31-ws-7186a37c-b705-423d-8e1a-05592518c0fa_0 - noVNC](https://user-images.githubusercontent.com/8517736/115970690-5e192f00-a544-11eb-966f-73d21975e586.png)

### calc
![2021-04-24 21_30_46-ws-7186a37c-b705-423d-8e1a-05592518c0fa_0 - noVNC](https://user-images.githubusercontent.com/8517736/115970693-62dde300-a544-11eb-802d-751568f0a788.png)

**Comment by Andreas-Kainz** [comment]
remove Thesaurus command and have it ony in writer, where it work @pedropintosilva ?

**Comment by pedropintosilva** [comment]
good catch @Andreas-Kainz , yes it should
