### ISSUE TITLE
Notebookbar Find and Replace command which Tab?

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2136]
The Find and Replace command is most of the time at the home tab (very right place). Should it be there everywhere or is there some better place?

![Screenshot_20210425_230724](https://user-images.githubusercontent.com/8517736/116009626-0a2d4980-a61b-11eb-9290-95dcebc1f009.png)

**Comment by pedropintosilva** [comment]
@Andreas-Kainz yup I think it should be everywhere in that tab, so currently writer is missing that (calc, impress and draw ave it)
