### ISSUE TITLE
CJK characters broken after Collebora 4.2 -> 6.4.

### ISSUE THREAD

**Issue by SeanKi** [CollaboraOnline/online#2139]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots**

**Desktop (please complete the following information)**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information)**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

We can't see CJK fonts chracters from sudden point.
I suspect it's point is where we update Collebora 4.2 -> 6.4.
All Korean fonts look like box, Changing the font was useless
![nextcloud_CJK_broken](https://user-images.githubusercontent.com/10428299/116019780-ee0fc380-a67f-11eb-8d82-a6ac5c666fdc.PNG)
(I am not sure this is right place to ask this, but collabora forum has no reaction for my question more than one week.)

Thank you in advance.

**Comment by thebearon** [comment]
Yes, this is the correct place to report bugs. However, when I checked a sample document with Korean text, it showed fine. Can you please share a sample that exhibits the bug?

**Comment by Ezinnem** [comment]
Closing this issue due to lack of response.
