### ISSUE TITLE
Port to Util::make_unique()

### ISSUE THREAD

**Issue by vmiklos** [CollaboraOnline/online#214]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @vmiklos 

https://github.com/CollaboraOnline/online/pull/211 introduces the Util::make_unique() function, which has some benefits: (quoting the PR description):

> In the old code, if the evaluation first allocates the memory for the raw pointer, then calls firstLine() and an exception is thrown before the std::unique_ptr construction, then the memory is leaked. Using make_unique() has the benefit of avoiding this problem.

However, that PR only converts a single usage. The task is to find all cases where a unique_ptr is constructed or reset: `std::unique_ptr<Foo> foo(new Foo());` or `foo.reset(new Foo())` and replace those with `Util::make_unique()`.

Example places which are not converted at the moment:

https://github.com/CollaboraOnline/online/blob/08f80fe7f618cfed7142fe07adc5431e25134353/wsd/DocumentBroker.cpp#L893

https://github.com/CollaboraOnline/online/blob/08f80fe7f618cfed7142fe07adc5431e25134353/kit/Kit.cpp#L1263

**Comment by bgbenzer** [comment]
Hi, I would like to work on this issue but I have a question. Should I make the changes in one place or all places that  I find with git grep.

**Comment by vmiklos** [comment]
I suggest some middle ground, e.g. handle only one file or one directory / PR.

And sure, you can use clang-tidy or git grep to find the places, up to you.

**Comment by bgbenzer** [comment]
@vmiklos, Thanks for your answer. Then I will work on kit.

**Comment by vmiklos** [comment]
Reopen, not all cases are fixed yet.
