### ISSUE TITLE
Fix lc_insertgraphic.svg

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2151]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @Andreas-Kainz 

Replace in `/loleaflet/images/` the `lc_insertgraphic.svg` with the respective correct asset from core

![image](https://user-images.githubusercontent.com/65948705/116061185-db4abe00-a682-11eb-85b9-0c10d4a8c937.png)

**Comment by Andreas-Kainz** [comment]
Thank's for open the bug report. 

There are some icons that are one color dark only. I wasn't sure if this icons should be one color dark only (maybe for mobile theming). Buf if not, sure the colibre icons should be used.
