### ISSUE TITLE
Fix insert line and shape icons

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2152]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @Andreas-Kainz 

![image](https://user-images.githubusercontent.com/65948705/116062511-41841080-a684-11eb-8b9d-b8cf579056a7.png)

- Insert Line icon: is really really tiny (rendering issues)
- Insert Shape icon: some rendering issues as well

location: `loleaflet/images/`

**Comment by pedropintosilva** [comment]
Thanks  @Andreas-Kainz !
Does this https://github.com/CollaboraOnline/online/pull/2159 fixes it? 

![image](https://user-images.githubusercontent.com/65948705/116227179-2385e100-a754-11eb-88b4-6b75eb403f7b.png)

It seems so, maybe the shape outline could get better render when increasing outline but anyhow I think it's better, and if it's ok with you I can close this issue

**Comment by Andreas-Kainz** [comment]
Instead of an ellipse I can use an rectangular shape, which will have less troubles with rendering.
