### ISSUE TITLE
loleaflet-api.html: Copy documentation into source code as comments

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2160]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**

### Detailed description and rationale
We have documentation in `loleaflet/loleaflet-api.html` it would be great to transfer those bits directly to source code via comments in front of declarations for self documenting purposes. Please start small, picking one option at the time per PR

##### 1. Pick one
`tileWidthTwips` is documented in `loleaflet/loleaflet-api.html`:
![image](https://user-images.githubusercontent.com/65948705/116096540-abfb7780-a6a9-11eb-9963-71924e8ad599.png)

##### 2. Find where that is declared in the code
Search for `tileWidthTwips` using terminal or your favourite IDE and hunt where is firstly declared. In this case is in `loleaflet/src/map/Map.js` `:40`

##### 3. Add comment

![image](https://user-images.githubusercontent.com/65948705/116098283-3d1f1e00-a6ab-11eb-8ad4-ddc3391617f6.png)

##### 4. Push Pull request
In your commit message please follow this `Copy loleaflet-api.html into code: [option/command/etc]`. So in our example that would be `Copy loleaflet-api.html into code: tileWidthTwips`

### Code pointers

 where: `loleaflet/loleaflet-api.html`

##### Options
- [ ] doc
- [ ] server
- [ ] webserver
- [ ] permission
- [ ] timestamp
- [ ] documentContainer
- [ ] toolbarContainer
- [ ] renderingOptions
- [ ] print
- [ ] autoFitWidth
- [ ] zoom
- [x] tileWidthTwips https://github.com/CollaboraOnline/online/pull/2749
- [x] tileHeightTwips https://github.com/CollaboraOnline/online/pull/2205
- [x] defaultZoom https://github.com/CollaboraOnline/online/pull/2830
- [x] cursorURL https://github.com/CollaboraOnline/online/pull/3121

##### General Methods
- [ ] search()
- [ ] highlightAll()
- [ ] setPermission()
- [ ] getDocSize()
- [ ] getDocType()
- [ ] getPageSizes()
- [ ] scroll()
- [ ] scrollDown()
- [ ] scrollRight()
- [ ] scrollTop()
- [ ] scrollLeft()
- [ ] scrollOffset()
- [ ] getPreview()
- [ ] getCustomPreview()
- [ ] removePreviewUpdate()
- [ ] fitWidthZoom()

##### ScrollOptions
...
##### PreviewOptions
...

#### Toolbar
...

**Comment by codewithvk** [comment]
Can I work on this?

**Comment by pedropintosilva** [comment]
awesome! sure @codewithvk  : )

as I stated in the description pick one and create a PR just with that : ) thanks!

**Comment by urvimitra** [comment]
Can  I work on this too?

**Comment by mrkara** [comment]
> Can I work on this too?

Sure. Please go ahead and pick one from the list. :)

**Comment by siddharth25pandey** [comment]
Shall I work on this ?

**Comment by siddharth25pandey** [comment]
@pedropintosilva Instead of creating PR for each single Options, General Methods, etc. Can I create a single PR ? It will definitely save the time and PR Review

**Comment by pedropintosilva** [comment]
@siddharth25pandey : yes definitely : ) thanks! Please check my comment under your PR.

**Comment by siddharth25pandey** [comment]
@pedropintosilva I was exploring the options present in loleaflet directory. I wasn't able to find out a single match for `toolbarContainer` except in the **loleaflet-api.html page**. Please let me know, where I can search for this.
Thanks!

**Comment by pedropintosilva** [comment]
> @pedropintosilva I was exploring the options present in loleaflet directory. I wasn't able to find out a single match for `toolbarContainer` except in the **loleaflet-api.html page**. Please let me know, where I can search for this.
> Thanks!

Sure, when that happens it can mean that does not exist any more, what to do?

1. Search within git history to find what happen. Example: 
```bash
git log --all --grep="toolbarContainer"
```
it gives you
```bash
commit 4358d2a04ec5465d55e336aa826788c17df96d71
Author: Henry Castro <hcastro@collabora.com>
Date:   Wed Nov 20 10:41:16 2019 -0400

    loleaflet: remove the function removeControls
    
    There is no toolbarContainer element anymore, it is better
    to remove dead code.
    
    Change-Id: Iac401698ee06223c5af3a69ac18f4bdc8f8c71b4
    Reviewed-on: https://gerrit.libreoffice.org/83321
    Reviewed-by: Henry Castro <hcastro@collabora.com>
    Tested-by: Henry Castro <hcastro@collabora.com>
```
2.  Double check the code either in the https://github.com/CollaboraOnline/online/search?q=4358d2a04ec5465d55e336aa826788c17df96d71&type=commits or by doing
```bash
git show 4358d2a04ec5465d55e336aa826788c17df96d71
```
3. In this case it was indeed removed, so time to do a pull request removing that from `loleaflet-api.html, page
  - And ideally explain that in the commit message and add there `4358d2a04ec5465d55e336aa826788c17df96d71` to reference the commit that removed that

**Comment by greenthings** [comment]
Can i try on option autoFitWidth ??

**Comment by edenison** [comment]
Hi, I was hoping to contribute to this, but I don't see loleaflet/loleaflet-api.html. Has it been moved?

**Comment by kendy** [comment]
@edenison: Hello, thank you for that!  The file has been moved & renamed in the meantime, now it is: browser/cool-api.html
