### ISSUE TITLE
Windows: ie/edge: report test results

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2174]
**Tests**

- [ ] Notebookbar: is there any visible difference between ie/edge and chrome?
- [ ] Pick an issue at time from https://github.com/CollaboraOnline/online/labels/bug and try to reproduce it 
  - [ ] Write your findings in the respective issue with information on your windows and browse version plus where did you tested (which server/ local build which hash)
  - [ ] When writing your findings there, please mention back this one (https://github.com/CollaboraOnline/online/issues/2174) so it remains linked

**Comment by Andreas-Kainz** [comment]
![2021-04-27 09_13_42-text docx - Files - Nextcloud ‎- Microsoft Edge](https://user-images.githubusercontent.com/8517736/116200745-fd067c80-a738-11eb-884d-e7aa2b5ac168.png)

Microsoft Edge 41.16299.1004.0
Microsoft EdgeHTML 16.16299
@ 2017 Microsoft

**Comment by pedropintosilva** [comment]
Pedro Pinto Silva, [27.04.21 09:36]
[In reply to Andreas Kainz]
I see, could you please try and change in the browser webtools  the css properties of #closebutton { as it shown here https://github.com/CollaboraOnline/online/pull/2176/commits/e35388689dbcf119a8c6e5a92a0f5fff89274e2e

-------

Pedro Pinto Silva, [27.04.21 09:36]
and see if it solves it?

-------

Pedro Pinto Silva, [27.04.21 09:39]
1. by doing something like` Control+Shift+I`
2. and select the #closebutton or by searching for #closebutton
3. and changing the css

-------

Pedro Pinto Silva, [27.04.21 09:39]
https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/css/

-------

Andreas Kainz, [27.04.21 09:48]
checked, the patch work, but the tab height didn't change it look like it was before 24px height and now 32px

-------

Pedro Pinto Silva, [27.04.21 09:50]
can you send a screenshot, I'm not sure I got it

-------

Andreas Kainz
![image](https://user-images.githubusercontent.com/65948705/116219736-38f70d00-a74c-11eb-9ac5-3e71f9b2a800.png)

-------

Pedro Pinto Silva
Ok, cool so we have discovered two problems, the close button PR has been merge https://github.com/CollaboraOnline/online/pull/2176 and should solve one of the problems the other one might be related with `scrollIntoView` function as stated by @eszkadev :

> I guess it's a problem with scrollIntoView  function used for style previews... it has different effect in every browser... it works well in firefox and chrome also, but in firefox has smooth scrolling for example

**Comment by thebearon** [comment]
I assume this can be closed (also, IE 11 is unsupported in 21.11). If there's still an issue with Edge, it can be reported separately.
