### ISSUE TITLE
Help: Check and Update screenshots 

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2194]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @pedropintosilva 

### Detailed description and rationale

- [ ] Check `Online Help` needs text updates
- [ ] Update `Online Help` screenshots 
  - No need to setup build, just request an account via `https://www.collaboraoffice.com/demo/` and you will receive the credentials  

### Code pointers
- HTML file is located in: `loleaflet/html/loleaflet-help.html`
- Images located in: `loleaflet/images/help`

**Comment by SvA1** [comment]
Hey, I'd like to work on this, could you assign it to me?

**Comment by kendy** [comment]
@SvA1 Hello, great to hear you are interested - thanks in advance for sorting this out!
