### ISSUE TITLE
CODE 6.4.8: Calc: Cell Comments are (partially) shown also in "wrong" tables  / worksheets

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#2197]
**Describe the bug**
Most Calc Workbooks have several worksheets / tables.

If you add comments to worksheet / table 1, and switch to another worksheet / table, many cell comments (but not all...) will also be shown there - even though they don't belong to this sheet.

See screen recording:

![CODE 6 4 8 Calc Comments in wrong table](https://user-images.githubusercontent.com/26199042/116526060-79d05c80-a8d9-11eb-8a48-d10e58816883.gif)

**Expected behavior**
Comments should only be shown when hovering over a cell which actually has a comment.

**Actual behavior**
Comments are often shown when hovering over a cell which does NOT have a comment, but where a cell at similar / same location in another worksheet has a comment instead.

**Screenshots**
See above.

**Desktop (please complete the following information)**
 - OS: Ubuntu 20.04 x64 (KDE neon)
 - Browser: Chromium
 - Version: 90.0.4430.72 (Offizieller Build) Built on Ubuntu , running on neon 20.04 (64-Bit)

**Comment by pedropintosilva** [comment]
I think this has been fixed on Master but I can confirm that I obtained the same behaviour with
6.4.8 (git hash: [99985b91](https://github.com/CollaboraOnline/online/commits/99985b91))

Maybe a missing backport? cc @thebearon

**Comment by pedropintosilva** [comment]
Thanks @gohrner for reporting it! Much appreciated :)

**Comment by thebearon** [comment]
Seems like this started with c85c9956455543743e0a0838a239e58fe7caf976. @lpranam can you please check?

Simplest reproducer is to:
- add a comment to a sheet,
- insert a new sheet,
- switch to it,
- hover over the same cell where the comment was added previously.

**Comment by lpranam** [comment]
#2305 will fix this problem :D
