### ISSUE TITLE
Notebookbar: Buttons missing disable status 

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2204]
Tracking elements that should not be always active. (to be updated with the PR numbers repectively)

### Home

- ~Paste icon should not be enabled if there is nothing to paste~
  - This issue does **not** include clipboard related buttons, see @mmeeks comment for more info

### Insert

- [ ] Delete Pivot table (should not be visible if a pivot table is not selected
  - ![image](https://user-images.githubusercontent.com/65948705/116549057-54e9e280-a8f5-11eb-8b8d-f42c3af9f0d0.png)

**Comment by codewithvk** [comment]
@pedropintosilva Hey, can I try this one?

**Comment by thebearon** [comment]
For pointers, first the UNO commands for the buttons have to be found out, and added similarly as done here:
https://cgit.freedesktop.org/libreoffice/core/commit/?id=27381dc1b76e4aee5459b3d85e6fc5919d2b8f98

**Comment by codewithvk** [comment]
> For pointers, first the UNO commands for the buttons have to be found out, and added similarly as done here:
> https://cgit.freedesktop.org/libreoffice/core/commit/?id=27381dc1b76e4aee5459b3d85e6fc5919d2b8f98

I am tried to understand this, but not getting much.
Here is I found something

When there is nothing copied (Buffer is empty) still `.uno:paste` state is enabled
![temp2](https://user-images.githubusercontent.com/61119120/116822466-81735800-ab9c-11eb-8241-b9cb74bca938.png)

Can anyone help me that how can I take the problem?

Also if how can I check (Debug) value of `itemState` code pointer:- https://github.com/CollaboraOnline/online/blob/master/loleaflet/src/control/Control.Menubar.js#L1324

Maybe we can solve it by the above condistion.

**Comment by pedropintosilva** [comment]
good work in investigating this @codewithvk ! But I wonder if that `enabled` means that or (like with `DisableCopy`) is just meant to tell us if the function or enabled or disabled in the backend..hm..I'm afraid I cannot be of any further help here. Come to the community meeting today and we can discuss that : ) ( maybe @lpranam will be able to help or @eszkadev )

**Comment by eszkadev** [comment]
1. for Paste we should not depend on itemState for .uno:Paste   but rather get the information about clipboard state from Clipboard.js
so in NotebookbarBuilder.js in `_clipboardButtonControl`   handle case for paste button and set some class for the result html element

2. you can see state handling for uno buttons here:
loleaflet/src/control/Control.JSDialogBuilder.js : 2404   `_unoToolButton`  function
there you can console.log('...')

**Comment by mmeeks** [comment]
Oh - so this task is I'm afraid ~impossible. On many systems we cannot get at the state of the browser's clipboard at all - hence we show the dialog, and we cannot get this state from the core at all, since ... we put bogus stuff on the clipboard there anyway to ensure that the items give us a positive state from the core to allow us to show these things as enabled.

So - I'm sorry, this is one horrible issue to solve - in a perfect world where browser clipboard APIs don't suck - it might be possible, but - we are very far from that world. Sorry ! lets drop the 'Paste' bit from this ticket.

**Comment by pedropintosilva** [comment]
Thanks @mmeeks , _updated_
