### ISSUE TITLE
Notebookbar: Home: Height is taller taller than the other tabs

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2207]

**Comment by Andreas-Kainz** [comment]
The Color Control commands are to height cause the icon was drawn on top of color preview, so that the height was instead of 24px for a simple icon, 24 + 7 px. In addition the dropdown menues for font name, font size are larger in height as an simple icon.

**Comment by eszkadev** [comment]
see also: https://github.com/CollaboraOnline/online/issues/2088

**Comment by Andreas-Kainz** [comment]
There are two issues
1. #2088 
2. comboboxes are to height (was used in classic and notebookbar mode)

**Comment by Andreas-Kainz** [comment]
### Before
![photo5800921811280574064](https://user-images.githubusercontent.com/8517736/116881005-03a65f80-ac23-11eb-8a1e-e457cabbc06c.jpg)

### After
![photo5800921811280574063](https://user-images.githubusercontent.com/8517736/116881024-0a34d700-ac23-11eb-8864-937b44f55a5d.jpg)
