### ISSUE TITLE
Styles preview box width depand on window size

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2210]
It would be cool if the width of the previews can be flexible so that you can see 2 - 20 previews.

![Screenshot_20210429_205738](https://user-images.githubusercontent.com/8517736/116603783-9dbd8d80-a92d-11eb-8fb3-79b10e9399b7.png)

**Comment by thebearon** [comment]
Sounds reasonable, probably something to consider in desktop LO as well.

**Comment by Andreas-Kainz** [comment]
I think at COOL this can be done with .css on LO I don't know.

**Comment by Andreas-Kainz** [comment]
@pedropintosilva do you have an idea how to make an flexbox that flexible? Or maybe @eszkadev you have an idea.

**Comment by pedropintosilva** [comment]
yes, similar as I did in some mobile wizard panes (shapes, maybe?) or I think even on the fontwork dialog (you can play with width of #FontworkGalleryDialog in the jsdialog.css and you will see that the grid auto adjusts etc)
