### ISSUE TITLE
CODE 6.4.8: Calc: Offers "Add New Column" options in Column Context Menu even in case of active filter

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#2230]
**Describe the bug**
Calc does not allow "Add New Column Before / After" if a filter is active and hides some rows.

[This is annoying, but is the case](https://bugs.documentfoundation.org/show_bug.cgi?id=57351), and the corresponding menu entries are not available then.

In CODE, the menu entries are always visible, and simply do nothing in case of an active filter. That's even more confusing than the behaviour in the Desktop application...

**To Reproduce**
1. Create Calc sheet and fill it with some data.
2. Activate auto filters and select some filter which filters at least one row.
3. Right-click the column header to open the column context menu.

**Expected behavior**
1. Either, no "Add Columns Before/After" menu entries should be shown, [as in the Desktop application](https://bugs.documentfoundation.org/show_bug.cgi?id=57351).
1. Alternatively, if they are shown, they should work as expected (i.e. add new columns before or after the selected column).

**Actual behavior**
1. The Context Menu will show "Add Columns Before/After" menu entries.
1. If these menu entries are clicked, nothing will happen.

**Comment by Ezinnem** [comment]
The fix will be made in the 2022 version.

**Comment by Ezinnem** [comment]
The bug has been fixed.

No longer reproduicble in LOOLWSD 6.4.10snapshot (git hash: [788e0aa](https://github.com/CollaboraOnline/online/commits/788e0aa)).
