### ISSUE TITLE
Notebookbar Help Tab commands bigtoolitem

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2232]
the help commands are only available as menutoolitem. Would be great to have them available as bigtoolitem (32px icon + bottom label)

![Screenshot_20210430_212222](https://user-images.githubusercontent.com/8517736/116744213-4c2f0480-a9fa-11eb-9d68-2e20e5fe61c6.png)

**Comment by thebearon** [comment]
@pedropintosilva, what do you think?

**Comment by pedropintosilva** [comment]
yup, I think a single menutoolitem line should be avoided. We should use menutoolitem when in double row.

So we have two options here:

1. Either turn all of them `bigtoolitem`
2. Or select one as a `bigtoolitem` and the rest remain as `menutoolitem` but not in a single line. 

The 1st options is the easiest and less code-intrusive. The 2nd would require some further testing and maybe extra conditions (not all buttons in Help tab appear always, depending on config and integrator)

**Comment by pedropintosilva** [comment]
- [ ] Update Notebookbar Builder
  - [ ] Apply to Writer https://github.com/CollaboraOnline/online/pull/2297
  - [ ] Apply to Calc
  - [ ] Apply to Impress
  - [ ] Apply to Draw
