### ISSUE TITLE
Document container: Background has two colours 

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2250]
**Describe the bug**
Document container: Background has two colours 

**Expected behavior**
The background behind the page document should have only one colour

**Actual behavior**
It seems there are two elements with different colours : 
- `#f7f7f7`
- `#f8f9fa`

**Screenshots**
![image](https://user-images.githubusercontent.com/65948705/116872567-62191100-ac16-11eb-9cd6-73537ceddd29.png)

**Desktop**
 - Master: https://github.com/CollaboraOnline/online/commits/e3538868

**Comment by gokaysatir** [comment]
Is this still relevant?
