### ISSUE TITLE
(Chinese Input Bug) Duplicate characters keep appearing when I am choosing the right character.

### ISSUE THREAD

**Issue by jimlinntu** [CollaboraOnline/online#2251]
**Describe the bug**
Duplicate characters keep appearing when I am choosing the right character.

**To Reproduce**
1. Open a `.odt` file and then start to type Chinese characters.

**Expected behavior**
It should not produce characters when I am choosing them.

**Actual behavior**
It keeps generating characters!

**Screenshots**
This video explains everything.

Chrome: I can choose the right character but it will keep generating duplicate characters

https://user-images.githubusercontent.com/31609554/116881150-7c261400-ac55-11eb-835d-08f3957fc354.mov

Firefox: I can't even choose a character

https://user-images.githubusercontent.com/31609554/116884111-f1471880-ac58-11eb-8a13-532e4845d065.mov

**Desktop (please complete the following information)**
 - OS: macOS Mojave 10.14.6
 - Browser: Chrome Version 90.0.4430.93 (Official Build) (x86_64), Firefox 87.0 (64-bit)

**Additional context**
Collabora Online Development Edition (CODE): 6.4.8
Nextcloud version: 18.0.12

**Comment by jimlinntu** [comment]
For anyone who struggles with this issue, sadly, I have switched to OnlyOffice because there are just too many bugs in Collabora.

**Comment by Ezinnem** [comment]
This issue seems resolved in the recent Collabora Online 6.4.13.

@jimlinntu, please can you update your CODE version and test it again?

**Comment by Ezinnem** [comment]
Closing this issue due to response from the Author
