### ISSUE TITLE
Scrollbar layout update

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2277]
I would suggest an scrollbar layout update 

## Before

Notebookbar:
![image](https://user-images.githubusercontent.com/65948705/114835766-343c6b80-9dd2-11eb-9239-030c50e49a13.png)

## After

![scrollbar](https://user-images.githubusercontent.com/8517736/117135201-e39fa900-ada6-11eb-9ae8-ac77152151ff.png)

left/right click commands icon in the tab area of the notebookbar.
- pro: no hidden commands
- less disturbing

when there is enough space for all commands the icons are hidden and you could shown an icon to hide the notebookbar commands.

![small](https://user-images.githubusercontent.com/8517736/117135386-28c3db00-ada7-11eb-86ae-023c71e85695.png)

move left/right, hide notebookbar and show/hide sidebar are all command's for the app UI so they are well grouped together.

**Comment by Andreas-Kainz** [comment]
@pedropintosilva sugestions from you?

**Comment by pedropintosilva** [comment]
discussion is already started here : https://github.com/CollaboraOnline/online/issues/2005 closing this but feel free to add comments there.

Nevertheless I not sure I understand how this would work
> pro: no hidden commands

But if there is `<` and `>` there will be always
* stuff hidden on not so wide screens
* it will be hidden sometimes on the left, sometimes on the right and sometimes both
* plus the other downsides presented in https://github.com/CollaboraOnline/online/issues/2005
