### ISSUE TITLE
CODE: erros in devTools

### ISSUE THREAD

**Issue by mahsashadi** [CollaboraOnline/online#2301]
Running CODE docker and trying it with Owncloud, NextCloud or my own WOPI host, I get the following errors in devtools:

![Screenshot from 2021-05-09 10-05-48](https://user-images.githubusercontent.com/70196035/117561682-2b2b7b00-b0ae-11eb-996b-6c6acb91014a.png)

**Comment by thebearon** [comment]
Even if these messages are in the logs, they shouldn't cause any issues.
