### ISSUE TITLE
Notebookbar file rename

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2310]
can we update the layout of the file title rename widget at the notebookbar.

![2021-05-10 09_19_13-text docx - Files - Nextcloud](https://user-images.githubusercontent.com/8517736/117630753-cd656480-b17b-11eb-8f88-ec601e32a615.png)

**Comment by Andreas-Kainz** [comment]
I propose something that is less noisy like show only the filename and with hover you will see that there is the posibility to edit the file name.

![2021-05-10 09_24_34-text docx - Files - Nextcloud](https://user-images.githubusercontent.com/8517736/117631053-21704900-b17c-11eb-891b-68605fcdabde.png)

In addition there is an command in the File tab to open an dialog to rename the file.

**Comment by Andreas-Kainz** [comment]
I like as it was in Collabora Online 4.x. In google docs there is also nothing more than the string and with hover you see that you can edit it.

In addition I would have an Rename command in the File tab see #2313

**Comment by pedropintosilva** [comment]
some quick iterations:
![image](https://user-images.githubusercontent.com/65948705/117647892-dd863f80-b18d-11eb-9c24-264a6c0a8dfd.png)

![image](https://user-images.githubusercontent.com/65948705/117648066-10303800-b18e-11eb-92cd-a6f61ac38c30.png)

![image](https://user-images.githubusercontent.com/65948705/117648505-951b5180-b18e-11eb-8ee1-d565df6b39da.png)

https://user-images.githubusercontent.com/65948705/117648646-c3992c80-b18e-11eb-9bcf-3c95588bbeb1.mp4

**Comment by Andreas-Kainz** [comment]
and when you "pin" the filename like an tab to the header?

**Comment by pedropintosilva** [comment]
https://user-images.githubusercontent.com/65948705/117664599-411a6800-b1a2-11eb-9d10-60729e36bcfc.mp4

**Comment by rizmut** [comment]
![gambar](https://user-images.githubusercontent.com/5697991/117764214-551fa180-b256-11eb-9bf2-3ac509f2735c.png)
A drop down arrow would be nice, but more effort

**Comment by Andreas-Kainz** [comment]
that would be very cool and would work also for #2313

**Comment by Andreas-Kainz** [comment]
Hi I'm sorry but I'm not 100 % happy cause:
- new shape layout you don't have somewhere else
- font size is different

So I played around. 
1. What if we use the tab layout for the filename
2. What if we use the filename for the file tab than we can have there not only rename, we have there all file related commands?
3. when the `filename` is used instead of `file` we have the same layout (we don't have to use the selected color style) and reduce space cause the file string wasn't needed.

### Before
![before](https://user-images.githubusercontent.com/8517736/118883681-cd8cff00-b8f5-11eb-953c-9f16ee412e5c.png)

### After
![after](https://user-images.githubusercontent.com/8517736/118883669-cb2aa500-b8f5-11eb-892f-e232c3256a21.png)
