### ISSUE TITLE
Notebookbar File Tab: Add Close Document command

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2312]
In LibreOffice there is a close document command within the File tab and also in the File Menubar there is a close document command.

![FileTab](https://user-images.githubusercontent.com/8517736/117635825-80d05800-b180-11eb-8564-6967077d65cf.png)

I suggest to add an close document command in the file tab.

**Comment by Andreas-Kainz** [comment]
@pedropintosilva I think an close button would be an improvement in the File tab.

**Comment by pedropintosilva** [comment]
good idea : )
I wonder if in that case wouldn't better to:
- have another icon
  - still with a x on it (for easy recognition) but
  - on a document type of icon so to feel more at home with the neighbouring icons in the NB 

What do you think?

**Comment by Andreas-Kainz** [comment]
sure will have another icon, it's only an quick mockup.

**Comment by Darshan-upadhyay1110** [comment]
This `X` close document at top right corner seems enough. I would suggest we should not add this option as it makes structure more complicated for users.

![image](https://github.com/user-attachments/assets/0de73028-56e5-47be-afb5-0ddd8841e437)
