### ISSUE TITLE
Notebookbar File Tab: Add Rename command

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2313]
There is an rename feature when click to the file title at the tab area of the notebookbar. I'm suggest to add an rename command in addition to the file tab.

![FileTab](https://user-images.githubusercontent.com/8517736/117636035-b1b08d00-b180-11eb-9416-c923582a9f0e.png)

**Comment by pedropintosilva** [comment]
This sounds good, do you want to tackle this down?

**Comment by pedropintosilva** [comment]
code pointer:
- where: **loleaflet/src/control/Control.DocumentNameInput.js**
- Function: `documentNameConfirm`
  - which renames it `renameFilename` (loleaflet/src/control/Toolbar.js)
  - and then saves it `this.map.saveAs(value)` (loleaflet/src/control/Control.DocumentNameInput.js)

**Comment by Andreas-Kainz** [comment]
As I don't have cool with NC integration it will be very difficult to fix this issue. sorry.

**Comment by pedropintosilva** [comment]
To setup NC or oC docker for testing with local built CO
1. `sudo apt install docker.io`
1. `docker pull nextcloud` or `owncloud`
1. `docker run -d -p 80:80 nextcloud`
  - it will print in the terminal its id like `341f28ef0ca471489d5bb91fe9f50d2de44ddabd8bbea9ae8b1787f10d04cab7`
1. Web browser: go to `http://192.168.your.ip` (find what's your local ip) and set up your Nextcloud/owncloud
1. In Nextcloud/Owncloud go to Apps install Collabora Online app (richdocuments)
1. Edit `loolwsd.xml` and disable ssl (false)
1. Open terminal in the directory where you have Collabora Online and do a make run like so `make -jxx run` (xx number of threads of your processor)
1. Web browser: back to your NC/owncloud: go to the settings of Collabora and set up the Collabora Online server to `http://192.168.your.ip:9980`

To stop and start a container just do:
- `docker stop id`
- `docker start id`
