### ISSUE TITLE
Calc Sheet Tabs selected sheet use calc branding color

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2320]
As in the notebookbar layout the selected tab string use the calc green color. I suggest to use the calc green color also for the selected sheet tab.

![Screenshot_20210510_162118](https://user-images.githubusercontent.com/8517736/117674458-f998d980-b1ab-11eb-8dc6-10f76e6447b6.png)

**Comment by thebearon** [comment]
@pedropintosilva, what would be your thoughts on this?

**Comment by Andreas-Kainz** [comment]
Thank's @thebearon I would also recommend to make the tabs smaller in height so that the height come from the buttons on the right. Than it will look more balanced AND we can save vertical height for content.
