### ISSUE TITLE
Notebookbar Color Theme Support

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2331]
The idea is to use var colors from loleaflet.css in notebookbar.css so that all colors for notebookbars come from loleaflet and can than be themed (dark theme mode could be also possible).

**Comment by Andreas-Kainz** [comment]
@merttumer Pedro told me you work on the link between NC and COOL, so maybe you can give some feedback which color names should be used for color theme support.

**Comment by Andreas-Kainz** [comment]
![photo5823293690335048813](https://user-images.githubusercontent.com/8517736/117927387-6de19300-b2fa-11eb-9720-99bef383eac0.jpg)

**Comment by pedropintosilva** [comment]
- Avoid using the same `--co` prefix
- keep creating the same place `loleaflet.css`

**Comment by pedropintosilva** [comment]
https://sdk.collaboraonline.com/docs/theming.html?highlight=theming

**Comment by Andreas-Kainz** [comment]
Noteboolbar has now 100% style support .

I'm thinking on reduce the different shadow usage.

Should we make a separate styles.ccs file where the colors are defined? @pedropintosilva

**Comment by pedropintosilva** [comment]
@Andreas-Kainz yes I think we can, maybe something names `color-palette.css` and the contents encapsulated by:
```css
:root {
/* variables here*/
}
```

**Comment by Andreas-Kainz** [comment]
Noteboolbar use var colors.
