### ISSUE TITLE
Android - no file contents shown

### ISSUE THREAD

**Issue by licaon-kter** [CollaboraOnline/online#2335]
...there's just white space, also buttons don't do anything.

F-Droid repo
Online a28ee1bac & core 796e85624b78

**Comment by licaon-kter** [comment]
Stable 6.4.8 ( 55560182da110cc83368c7589303c06e8c3faada / core https://hub.libreoffice.org/git-core/8c14f17 ) appears to work fine.

**Comment by licaon-kter** [comment]
This has not been reproduced internally yet?

**Comment by timur-g** [comment]
This may have been some temp. glitch? Or specific to some file? 
I do not see that in current 21.11. or tesing 23.05. https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/

**Comment by licaon-kter** [comment]
I guess
