### ISSUE TITLE
Can't select row or column in Writer table in 6.4.8 on Android device

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#2352]
**Describe the bug**
Can't select row or column in Writer table in Collabora Office App or Collabora Online on Android device.
- fails on Android in Collabora Office 6.4.8 (55560182) when using touch.
- (edit: disabled on newer version, see note) fails on Android in Collabora Online 6.4.8 (6a844e4) when using touch.

It works on a Chromebook using Collabora Online 6.4.8 (git hash: 6a844e4) using touch or mouse. 
BTW, the new way of selecting rows or columns is great.

**To Reproduce**
1. Android device, using Collabora Online or the Collabora Office App
2. Create a new table in Writer
3. Try to select a row or column by touching the -----{}-----

**Expected behavior**
The row or column would be highlighted.

**Actual behavior**
Nothing gets highlighted. 
This may help: In Android the cursor jumps to the **first** row or column if it wasn't already there, whereas on a Chromebook in Collabora Online the cursor jumps to the **last** row or column and highlights it.

**Screenshots**
None

**Smartphone (please complete the following information)**
 - Samsung Galaxy S8+
 - OS: Android 9
 - Collabora Office App 6.4.8 (55560182) or Collabora Online 6.4.8 (6a844e4)

**Comment by glitchnopanic** [comment]
Now on Collabora Online 6d63249 and the new selection buttons now turned off on my Android phone.  But I can't select cells rows or columns,  or I don't know how to.

**Comment by nikslor** [comment]
I think I can reproduce this issue with the snapshot from (today)[https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/collabora-office-mobile-6.4-snapshot-arm64-v8a-2021-05-27.apk].

How to reproduce:
* Add a table in a writer document in Android, e.g 3x3 (rows x columns)
* Try to select the column "A" using a finger e.g. do make content bold, change background, etc.

There seems not to be a way to select a columt (or a row) currently.

**Comment by rpear** [comment]
@nikslor, this behaves as expected now with the Android C-Office app on a Chromebook, and also when using C-Online from a Chromebook. So this bug is fixed; However when using the iPad C-Office app or using C-Online from an iPad there is odd behaviour, so maybe this ticket's label should be changed, or close the ticket and create a new ticket?

It tested OK with the C-Office app 23.05.5.2 installed on ChromeOS 119.0.6045.214, and it was OK with C-Online 23.05.6.4 accessed from the same Chromebook. In both cases it was tested using the trackpad to select, I did not have a touchscreen to test it with.

**Issues observed when using an iPad (9th gen):**
- With the C-Office app 23.05.5.2 installed on iPad OS 17.2 when using the touchscreen to select, the row/column selection buttons appear OK when the table is selected, but selecting a column or row just moves the cursor to the first cell in that line, it doesn’t highlight anything.
- When using C-Online 23.05.6.4 from the iPad the row/column selection buttons do NOT appear when the table is selected, so can’t highlight anything. But please note that this was tested at the same time as the document was being accessed online from another device, ...just in case this is actually the cause of this peculiarity.

**Comment by nikslor** [comment]
@rpear I didn't test Android/Chromebook but can reproduce the issue with the iOS app. As you correctly describe:

> when using the touchscreen to select, the row/column selection buttons appear OK when the table is selected, but selecting a column or row just moves the cursor to the first cell in that line, it doesn’t highlight anything.

I think we should close the original issue and create a new one.

@rpear: would you like to do it?

**Comment by rpear** [comment]
This behaves as expected now with the Android C-Office app on a Chromebook, and also when using C-Online from the same Chromebook. So this bug is fixed.  But the problem appears on iPad and iPhone, a new ticket was created #7998
