### ISSUE TITLE
Sidebar icons have a different styling

### ISSUE THREAD

**Issue by juliushaertl** [CollaboraOnline/online#236]
The sidebar buttons and select boxes seem to have a different styling compared to the ones in the menu bar:

![image](https://user-images.githubusercontent.com/3404133/95558073-fc64fd80-0a15-11eb-8855-328dbdcf8c7a.png)

I think it would be good to have a unified button design all over the place.

LOOLWSD
6.4.0 (git hash: 6ad9d47)
Served by: 8464063a
LOKit
Collabora Office 6.4-6 (git hash: 16aec96)
"Ubuntu 18.04.4 LTS"

**Comment by DarkknightAK** [comment]
Unified button design isn't that easy but will be solved when sidebar is a real html element issue #164 

The icons were synched meanwhile with LibO 7.0

**Comment by kendy** [comment]
In the meantime, we could potentially introduce a custom core theme that includes the same icons as the notebookbar, if it is too bad currently. @pedropintosilva - what do you think?

**Comment by pedropintosilva** [comment]
@kendy yes I have that task lurking around but still didn't manage to do it. It's a quick fix and it will do for now until better solution arrives :+1:

**Comment by timar** [comment]
Actually it is a bug. Brand package provides the sidebar icons as well, and they should be the same as on the notebookbar. Of course I see differences even in the correctly branded case.

![image](https://user-images.githubusercontent.com/290614/98235780-9a3ee000-1f62-11eb-8bb6-1275ca6c563f.png)

See e.g. Paragraph and Indent sections on sidebar. Some icons are from the theme, some are not.

**Comment by nikslor** [comment]
I think we can also close this one now? In "Online" both icons are consistent and also e.g. on iOS it's the same style in both locations now.

### Online
![image](https://user-images.githubusercontent.com/1211300/134745092-121c00d9-c77d-478c-b4d0-036cc08b7120.png)

### iOS
![image](https://user-images.githubusercontent.com/1211300/134745179-846a5327-ba09-4b9a-ac82-213cff7243a9.png)

**Comment by juliushaertl** [comment]
The highlight style is still different, not sure if it would be wanted to also unify that across all UI sections:
 
![image](https://user-images.githubusercontent.com/3404133/135804660-477bea80-7254-43b4-b4b3-5ce6ba82c750.png)
![image](https://user-images.githubusercontent.com/3404133/135804672-c1491382-cb3d-4504-aecf-51f62326f967.png)

**Comment by pedropintosilva** [comment]
closing this issue as is quite old and now we have native sidebar etc so many if not all issues should have now been fixed
