### ISSUE TITLE
Menu bar buttons are not properly middle aligned

### ISSUE THREAD

**Issue by juliushaertl** [CollaboraOnline/online#237]
With the new notebookbar, some icons in the tab line are not properly middle aligned. I've tried to highlight the affected ones with some blue lines compared to the rest:

![image](https://user-images.githubusercontent.com/3404133/95558382-6ed5dd80-0a16-11eb-8d42-5ece1655e55e.png)

LOOLWSD
6.4.0 (git hash: 6ad9d47)
Served by: 8464063a
LOKit
Collabora Office 6.4-6 (git hash: 16aec96)
"Ubuntu 18.04.4 LTS"

**Comment by pedropintosilva** [comment]
Thanks @juliushaertl ! yup I'm aware, anyhow it's good to have an issue for that :+1:
