### ISSUE TITLE
Flickering text for a second after scrolling

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#2373]
**Describe the bug**
Text flickers on the screen for a second after scrolling up or down with the mouse scroll-wheel, by dragging the vertical scrollbar, or by touch. It is cosmetic as still usable, it does not look good. This occurs in both CODE Writer and CODE Calc, 6.4.9snapshot git hash: 6d63249, it is still occuring in 6.4.10snapshot 51b8716 1 July 2021, I have a feeling it is improving with newer releases. In my case the server ping time is 375 - 600ms if that is relevant and compounding the problem (I am in Australia and the server is in the UK).

**To Reproduce**
Steps to reproduce the behaviour:
1. CODE Writer or Calc on Chromebook.
2. Load document, with lots of text / table to make the problem visible.
3. Use mouse Scroll-wheel, or drag the vertical scrollbar, or drag the screen with touch, it is irrelevant how far.
4. If already at the top of the document and scroll up with dragging by touch or the mouse scroll wheel it flickers, even though there is nowhere for the document to scroll to.  Draw and Impress have a similar behaviour.
5. Note that this is not a problem with the locally installed Collabora Office app 6.4.3.

**Expected behaviour**
No flicker.

**Actual behaviour**
Writer:
- The text/tables flicker mostly towards the top of the screen, the toolbar, sidebar or comments do not flicker.  
- If a new line is added or deleted, all tiles are all re-written, it does not flicker.
- If I scroll up or down with the keyboard cursor keys or pgup/pgdn keys it does not flicker.

Calc
- The flicker is mostly in the middle horizontal 3rd of the screen.
- Unlike Writer, if I scroll up or down with the keyboard cursor keys it does flicker.
- Scrolling with pgup/pgdn keys it does not flicker.

**Desktop**
 - Chromebook: all so far including HP x360 and Acer R13.  
 - Google Chrome: all so far including 90.0.4430.100 (Official Build) (64-bit) and 90.0.4430.218 (Official Build) (32-bit).
 - Screen resolutions: all so far including internal screen 1536x864 and external 1920 x 1080.

**Smartphone**
 - It is OK on my Android smartphone, Samsung Galaxy S8+, Android 9, Chrome Version 90.0.4430.210.

**Comment by rpear** [comment]
@Ezinnem   The amount of flickering I see has reduced significantly since I reported this.  I have seen by developer comments that they were reducing unnecessary browser refreshes, so I think this bug can be closed.
I retested it using Chromebook Version 91.0.4472.147 (Official Build) (32-bit), CODE: LOOLWSD 6.4.10snapshot (git hash: 25b2adb) Served by: 557df1a3 LOKit Collabora Office 6.4-44 (git hash: eb38177) "Ubuntu 18.04.5 LTS"

**Comment by Ezinnem** [comment]
Alright. It is fine to close the issue.
