### ISSUE TITLE
Show previews in the Android app's recent files list

### ISSUE THREAD

**Issue by Thewisem** [CollaboraOnline/online#2379]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
CollaboraOffice New Update came and they improve a lot.
1)I mean the app size is considerably smaller
2)I can finally edit docx files
3)Files load times are faster
4)The UI improved
They upgraded from garbage to usable. ( Sorry about being rude. But it was not great)
Now this is what is needed to be improved
1) Fix that droplet bug. Like that droplet icon on the place we are supposed to write. Make it so that when we move that, it moves the position of where we are writing.Like to go back and fix
something
2)There is a significant lag between typing a letter and it being shown in the document, that needs to be fixed.
3)The app should scan the storage for documents and display them so that we can easily choose.
4)Little bit more faster loading times.
4)When minimizing (aka pincing away) the document instead of the document minimizing on the middle minimizes on the left side, it should be in the middle. But it only does that later.
Last but not least, support for keyboard swiping. :)

**Comment by Thewisem** [comment]
This is on the android side.

**Comment by Ezinnem** [comment]
It's best that the issues are filed separately as individual reports; that way they can be tracked easier. In this issue let's focus on the Preview feature you suggested.
I think the Preview feature for files will be a nice enhancement to have.

When you file new reports for the other enhancement features that you have listed, you can provide more details like the device and Andriod version you use.
That would be helpful.

Also, it will be helpful if you share a screencast showing the lagging issue in its new issue report.

For the slow file loading issue, you can provide a sample file and the estimate of load time that you feel is reasonable.

**Comment by Thewisem** [comment]
I am using the latest version on the fdroid repository. And I am running android 7. Architecture armeabi v7a. Device: Samsung Galaxy Tab A

**Comment by Thewisem** [comment]
Sorry for late response. Somehow this came in spam folder

**Comment by timur-g** [comment]
This report cannot move forward as it is not focused on a single issue that is well explained. 
Reporter, you may take Collabora 23.05 and see if some issue still remains and report separately. 
Always write exxact version you report to, not just saying 'latest" as now it is not clear what it was.
