### ISSUE TITLE
NB: Draw: Missing tabs

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2384]
Draw has very few tabs:
- File
- Home
- Insert
- Format
- Draw (contextual, it's not always there)
- Help

Missing Tabs:
- Layout
- Review (as on desktop, Spelling icons, comment icons)
- Draw (make it always visible)

**Comment by Andreas-Kainz** [comment]
Add **Review tab** (from impress) would be useful, yes.

**Comment by Andreas-Kainz** [comment]
**Draw tab** is only usefull when something is selected, so I would say no for always visible (maybe in the future, when there is more content). It's also not visible at LibreOffice.

**Comment by Andreas-Kainz** [comment]
**Layout tab** isn't available at impress, should be available for impress and draw. 
Is the master view available at cool?

**Comment by Andreas-Kainz** [comment]
Than we have a similar tab layout for all apps. I like it.

**Comment by Andreas-Kainz** [comment]
all added.
