### ISSUE TITLE
Sidebar button isn't available on tablets

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2386]
![2021-05-17 12_49_02-text docx - Files - Nextcloud](https://user-images.githubusercontent.com/8517736/118477105-9e686900-b70e-11eb-9dd7-de204cdcee4d.png)

property sidebar icon is missing.

on smaler screens I would hide the filename.

**Comment by Andreas-Kainz** [comment]
still an issue

**Comment by Rash419** [comment]
This has been fixed : master - https://github.com/CollaboraOnline/online/pull/5261, co-21-11 - https://github.com/CollaboraOnline/online/pull/5278
