### ISSUE TITLE
Enable reverting to previous versions using F-Droid

### ISSUE THREAD

**Issue by davidskalinder** [CollaboraOnline/online#2411]
**Is your feature request related to a problem? Please describe.**

At the moment, only one version of each release is available at a time in the F-Droid repo.  This makes updating via F-Droid a white-knuckle experience, since any update with broken functionality cannot be reverted.  The [snapshots download page](https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/) provides a handful of snapshot versions, but to use that as a backup still requires a user to identify a broken snapshot within a few days, and doesn't help at all for problems with stable releases.

**Describe the solution you'd like**

Make more previous versions available on the F-Droid repo (or, failing that, on a download page elsewhere).  One previous version of the stable release should be available at a bare minimum, ideally three or four.  Making snapshots available for a few weeks would be ideal, or perhaps it would be sensible to do something like keeping each Sunday's snapshot for a month?

**Describe alternatives you've considered**

At the moment, the only workarounds I know of are to manually download each known-good APK to my device so I can reinstall them if needed once they disappear from the repo, or to go hunting for dodgy third-party mirrors.  With luck, F-Droid's cache might have kept the old APK after an update, but I've never had success retrieving one this way.

As mentioned above, if for some reason it's impossible to make previous versions available in the F-Droid repo, an alternative might be to put them on a discoverable public webpage somewhere else.

**Comment by jejo86** [comment]
I would like to extend this idea to all repositories, not only the F-Droid one.

The latest updates in the [CentOS 8 repository](https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-centos8/) broke my installation and the lack of old versions prevents me to revert easily to an earlier build, I knew was working.

**Comment by timur-g** [comment]
Main issue with F-Droid is that is not updated, it is correctly 21.11 for stable, but worngly 6.4 for snapshot, we can say that is #3251.
So let me confirm this as Enhancement, to be checked after F-Droid repo is updated. 
Note: New 23.05 snapshots are released here: https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/.

**Comment by timur-g** [comment]
F-Droid now has multiple stable versions, although snapshots are not regularly updated. 
That would mean we can close this issue.
OTOH, F-Droid in latest version disabled downgrade, citing new Android versions that do not allow it anymore, disregarding power users.
