### ISSUE TITLE
Notebookbar Fullscreen collapsed tabs

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2416]
On Laptops the content space is very limited cause cool run in a browser so you have
- Tab toolbar
- URL toolbar
- Nextcloud toolbar
- COOL tabs
- COOL tabs content (2 rows)
- **Content Space**
- cool statusbar
- OS taskbar

### Example Laptop Screen 1920x1080
![Fullscreen](https://user-images.githubusercontent.com/8517736/118947317-7fa8e300-b957-11eb-91e5-78019a071f6e.png)

Left default layout and right fullscreen mode with collapsed tabs. Content height:
- 700 px default layout
- 920 px fullscreen mode with collapsed tabs

**Comment by Andreas-Kainz** [comment]
my request is that in fullscreen mode tabs will collapse by default.

**Comment by Andreas-Kainz** [comment]
@pedropintosilva your feedback is welcome

**Comment by pedropintosilva** [comment]
In this one I would prefer to not collapse them, I'm afraid of:

1. User hits full-screen icon so he can edit better
2. Tabs suddenly get collapsed 
3. User gets annoyed that now there is always the extra task to open collapsed tab
4. Bug reports start to rain : p

**Comment by Andreas-Kainz** [comment]
Good point.

Thanks.
