### ISSUE TITLE
Notebookbar Shortcut bar add Fullscreen

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2417]
### Impress
![2021-05-20 10_23_44-impress odp - Files - Nextcloud](https://user-images.githubusercontent.com/8517736/118953774-6a36b780-b95d-11eb-825d-fdfacb8f3d94.png)

### Writer
![2021-05-20 10_24_53-writer odt - Files - Nextcloud](https://user-images.githubusercontent.com/8517736/118953781-6c007b00-b95d-11eb-99b3-9d1a1f9e43af.png)

### Proposal
As Fullscreen mode can be very usefull #2416 to save space, I suggest to add Fullscreen command to the Shortcut bar at writer, calc and draw. So also the number of items in the shortcut bar is always the same.

**Comment by Andreas-Kainz** [comment]
@pedropintosilva feedback?

**Comment by pedropintosilva** [comment]
It makes total sense, confirming this!
