### ISSUE TITLE
Notebookbar add collapse tab button

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2418]
Cool classic toolbar has an collaps arrow to hide the menubar. MS Word, AutoCad, ... most applications that has ribbons, have an collapse arrow (top right).

Cool can collapse the tabs by click on the selected tab, so collapse feature is available but I think it's a bit hidden.

### Suggestion

show the collapse arrow (from classic toolbar mode) at notebookbar also.
![collapse](https://user-images.githubusercontent.com/8517736/118956907-504aa400-b960-11eb-9fd4-926041365546.png)

**Comment by Andreas-Kainz** [comment]
@pedropintosilva ^

**Comment by pedropintosilva** [comment]
Great, thanks for thinking about that.

Possible it is but:

- In the classic mode the upwards chevron (next to the sidebar icon)  is actually hiding what is above the toolbar buttons (menu) so, using the same component in the same place to hide something different can be misleading and confusing (specially if user are transitioning from one to another mode)
- The fact that we have tabs in the Notebookbar mode has given us the possibility to trim down those icons and improve **space efficiency** on no so large screens
  - Specially on impress: as we start to run out of space when using NB in Impress with one more extra icon on the right
- While removing an icon that was in turn **bringing ambiguous semantics** (is it related to the sidebar? Does it hide the top integrator bar [NC, oW], etc)

I would rather:
1. Add keyboard shortcut
2. Add an entry to the hamburger menu (near to Show/Hide Ruler menu item)
3. And maybe a nice little rippling dot that would appear upon hovering any tab title
  - Hovering that dot would show a tooltip `Tap to collapse`

**Comment by Andreas-Kainz** [comment]
> I would rather:
> 
>     1. Add keyboard shortcut

For a shortcut I think it's not that important in addition a shortcut can be selected by mistake and than the user wouldn't know how to change the collapsed toolbar back.
 
>     2. Add an entry to the hamburger menu (near to Show/Hide Ruler menu item)

could be useful.
 
>     3. And maybe a nice little rippling dot that would appear upon hovering any tab title
>        
>        * Hovering that dot would show a tooltip `Tap to collapse`

Tooltip would be great. 

Maybe show an arrow when hover to the tabs?
