### ISSUE TITLE
COOL mobile resizing

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2454]
If you test Cool on mobile browser like Firefox and Chrome, show/hide the keyboard, the page resizing isn't well.

As you can see at the screenshot on the bottom, cool height didn't fit perfect. Some of the "background" content from the cloud storage was shown.

![20210525090619](https://user-images.githubusercontent.com/8517736/119454943-68903980-bd39-11eb-9840-d5cf7e84e361.jpg)

**Comment by Ezinnem** [comment]
The behavior is not within Collabora Online. It has been reported in https://github.com/nextcloud/richdocuments/issues/1608

**Comment by Andreas-Kainz** [comment]
This issue is still open. See before
![2021-09-20 12_50_49-spreadsheet ods - Dateien - Nextcloud](https://user-images.githubusercontent.com/8517736/133992019-41a4ae23-5c7f-457b-bcae-4c1addd6f2d0.png)

if you uncheck the fixed height the view is correct
![2021-09-20 12_50_34-Unternehmens Matrix](https://user-images.githubusercontent.com/8517736/133992064-866417a4-80f7-4164-969f-a3b37285900d.png)

as the difference is 50px at #richdocumentsframe I think the issue is within https://github.com/nextcloud/richdocuments/blob/f63e8b1a63820890f3b714f1b71ec7fa54869d9f/css/viewer.scss at #richdocumentsframe height: calc (100vh-50px).
