### ISSUE TITLE
Compatibility Issue with fdroid repository even though going to the repo and downloading actually works

### ISSUE THREAD

**Issue by Thewisem** [CollaboraOnline/online#2472]
**Describe the bug**
Basically the title. In the fdroid app when I added your repository, the app in it said it was incompatible. But when I go to the repository directly and download the ,apk. It works. Please fix this issue
**To Reproduce**
1. Go to fdroid
2. Click on collaboration Office 6.4
3. See error

**Expected behavior**
Being able to download and install without issue both stable and unstable one.

**Actual behavior**
A clear and concise description of what actually happens.
Downloaded but not able to install.

**Screenshots**

**Desktop (please complete the following information)**
 - OS: 
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information)**
 - Device: [e.g. iPhone6] Samsung Galaxy Tab A
 - OS: [e.g. iOS8.1] Android
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22] 6.4.8

**Additional context**
I use armeabi v7a type device.

**Comment by florencebiree** [comment]
Same problem here.

The last collabora mobile version I was able to install through F-Droid was 6.4.3. Newer version failed to install (saying the app is incompatible with my device). Using the method described by Thewisem (going to the repo with a browser, and downloading the apk) works well, no incompatibility, and collabora mobile is working.

Device : Samsung Galaxy S5 SM-G900F
OS : LineageOS 18.1 (Android 11)
armeabi-v7a architecture

**Comment by florencebiree** [comment]
Still the same problem, but now I can't install new version by downloading the apk. Android starts to install the file, and says the installation fails at the end of the progress bar.

**Comment by krushia** [comment]
Confirmed here as well.

**Comment by Itsalltext** [comment]
Same on Samsung Galaxx A3 Android 6.0.1

![Screenshot_2023-02-06-14-39-36](https://user-images.githubusercontent.com/1583047/216987009-d18b4aa6-397f-46e1-9871-3b9bcb7791d5.png)

When ignoring the error and try to install installation failed.

![Screenshot_2023-02-06-14-39-21](https://user-images.githubusercontent.com/1583047/216987529-5c18060b-18ff-408c-9466-f139a2c004cf.png)

**Comment by timur-g** [comment]
Fdroid now has 23.05. can you please check if you can install?

**Comment by timur-g** [comment]
No response, and it works for me, so I close.
