### ISSUE TITLE
Edit.ods file. It will not save properly and will crash

### ISSUE THREAD

**Issue by tangdoul** [CollaboraOnline/online#2482]
Platform: iOS
LOOLWSD:6.4.8
collabora office 6.4-38
See the latest version of the AppStore for details

How to solve it?

**Comment by nikslor** [comment]
@tangdoul did you forget to add your file (Edit.ods)? I can't reproduce your issue with iOS 6.4.10 (1). Can you be more specific?

**Comment by tangdoul** [comment]
https://user-images.githubusercontent.com/12131871/119919865-e81e4280-bf9d-11eb-962e-c01e2836c7b9.MP4



As you can see from the video, when I create the table, edit it, save it, and return to the parent page, the contents of the table are not saved

**Comment by Ezinnem** [comment]
Closing this issue because it is not reproducible on my end and there has been no response from the user.
