### ISSUE TITLE
Mobile BottomToolbar context related

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2484]
The BottomBar on mobile show always content for context-text, but there are other context related stuff. 

Can the BottomBar show context related commands. For Impress and Draw where you aren't by default at context-text it is very strange, but the workflow can be improved everywhere with context related commands.

**Comment by Andreas-Kainz** [comment]
@eszkadev how can I add context related toolbar commands?

**Comment by eszkadev** [comment]
we don't have possibility for that now. I had PR for that in the past (you can look in the history) but then you decided to abandon that because you wanted to focus on improving notebookbar.

**Comment by Andreas-Kainz** [comment]
And now notebookbar is improved so I can work on the toolbars. So the old PR will give the option to have context related stuff?

**Comment by eszkadev** [comment]
yes, it added "context: xxxx" property to the toolbar item

**Comment by Andreas-Kainz** [comment]
@eszkadev can you please make me one example how it work?

**Comment by Andreas-Kainz** [comment]
Context for Table and Graphic work. But context for default|Text|DrawText didn't work (Like it was defined for the notebookbars).

**Comment by Andreas-Kainz** [comment]
There are two open questions to fix this issue:

1. initial reload toolbar cause when I make context ['Text'] in writer, they should be shown by default, cause default = Text (in writer).
2. context ['Draw|DrawLine|3DObject|MultiObject|Graphic|DrawFontwork'] should be possible. So a command was visible at more than one context entry. Like we have at Notebookbar

**Comment by Andreas-Kainz** [comment]
As @pedropintosilva is in charge of UX, I add him. In addition mybe he can help ;-)
