### ISSUE TITLE
Mobile read only TopBar

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2485]
On Mobile the default setting is to show an file at read only mode and the user has to activate edit mode.

Instead of gray out all commands at the Mobile TopBar, it would be cool to have a separate defined read only mode TopBar, cause than you can show read only (view mode) specific commands.

![Mobile_Mode_View](https://user-images.githubusercontent.com/8517736/118647894-28353680-b7e2-11eb-937e-6b8fd248e3ed.png)

**Comment by Andreas-Kainz** [comment]
@pedropintosilva what do you think?

**Comment by pedropintosilva** [comment]
@Andreas-Kainz I think it makes total sense. Actually we are even doing that on desktop* and, if I remember correctly, the intend was indeed to expand that everywhere. So yes :+1: !

BTW notes:
`*` append `&permission=readonly` tot he address bar to see what I mean:
on classic and notebookbar(nb) mode we show only top menu, probably we could also have a nb that displays only readonly related commands

**Comment by Andreas-Kainz** [comment]
how can I add the document-title (file title) at the top toolbar?

**Comment by pedropintosilva** [comment]
those items are set in the `browser/src/control/Control.MobileTopBar.js` and then use this._map.isReadOnlyMode() to show or hide UI as done in `browser/src/control/Control.Menubar.js`
