### ISSUE TITLE
Security check fails, does not detect running as a container in Kubernetes pod

### ISSUE THREAD

**Issue by ftab** [CollaboraOnline/online#2496]
**Describe the bug**
I am attempting to run Collabora Online as a part of Nextcloud, which I have running as a container in Kubernetes.

I've downloaded the built-in CODE server app but it didn't seem to be working, and additionally caused my Nextcloud install to lock up.

I fiddled around with proxy.php, and enabled debug logging to try to get a better look at things. I think I've narrowed it down to the code in this repository.

The server aborts, due to not detecting that it's running in a container.

```
Security: loolforkit incorrect user-name, other than 'lool'
Security: --disable-lool-user-checking failed, loolforkit has some capabilities set.
Aborting.
```

**To Reproduce**
1. Install Nextcloud in Kubernetes
2. Install Collabora Online & built in CODE server from the Nextcloud apps section
3. Attempt to use document collaboration
4. See above error in the log output of the nextcloud pod when it attempts to start the loolwsd, indicating it is aborting due to the security check.
5. Collaboration features don't work / Nextcloud gets sluggish / settings -> Collabora Online section of the admin area reports it is unable to connect to the server.

**Expected behavior**
Expected to detect it's running in a container and proceed with startup

**Actual behavior**
The /proc/self/cgroup information has no occurrence of the `docker` string it is looking for (according to common/security.h ). Instead, it has `kubepods`:

```
$ cat /proc/self/cgroup
11:net_cls,net_prio:/kubepods/besteffort/pod0e774406-5e73-470e-9b1c-77c63f13a732/8ddde4eca7758e4d7ae03ca353b0ebb9bf0bda613d99fd992c8b1453e6eced4a
10:freezer:/kubepods/besteffort/pod0e774406-5e73-470e-9b1c-77c63f13a732/8ddde4eca7758e4d7ae03ca353b0ebb9bf0bda613d99fd992c8b1453e6eced4a
9:blkio:/kubepods/besteffort/pod0e774406-5e73-470e-9b1c-77c63f13a732/8ddde4eca7758e4d7ae03ca353b0ebb9bf0bda613d99fd992c8b1453e6eced4a
8:rdma:/
7:memory:/kubepods/besteffort/pod0e774406-5e73-470e-9b1c-77c63f13a732/8ddde4eca7758e4d7ae03ca353b0ebb9bf0bda613d99fd992c8b1453e6eced4a
6:perf_event:/kubepods/besteffort/pod0e774406-5e73-470e-9b1c-77c63f13a732/8ddde4eca7758e4d7ae03ca353b0ebb9bf0bda613d99fd992c8b1453e6eced4a
5:cpu,cpuacct:/kubepods/besteffort/pod0e774406-5e73-470e-9b1c-77c63f13a732/8ddde4eca7758e4d7ae03ca353b0ebb9bf0bda613d99fd992c8b1453e6eced4a
4:cpuset:/kubepods/besteffort/pod0e774406-5e73-470e-9b1c-77c63f13a732/8ddde4eca7758e4d7ae03ca353b0ebb9bf0bda613d99fd992c8b1453e6eced4a
3:devices:/kubepods/besteffort/pod0e774406-5e73-470e-9b1c-77c63f13a732/8ddde4eca7758e4d7ae03ca353b0ebb9bf0bda613d99fd992c8b1453e6eced4a
2:pids:/kubepods/besteffort/pod0e774406-5e73-470e-9b1c-77c63f13a732/8ddde4eca7758e4d7ae03ca353b0ebb9bf0bda613d99fd992c8b1453e6eced4a
1:name=systemd:/kubepods/besteffort/pod0e774406-5e73-470e-9b1c-77c63f13a732/8ddde4eca7758e4d7ae03ca353b0ebb9bf0bda613d99fd992c8b1453e6eced4a
0::/system.slice/containerd.service
```

I suspect adding the search term `:/kubepods/` to the `isInContainer()` function would suffice, or perhaps `/system.slice/containerd` (I think Kubernetes has switched over to using containerd as the runtime, rather than Docker itself)

**Additional context**

I am using the latest Nextcloud docker image, 21.0.2-apache

Source for the helm chart: https://github.com/nextcloud/helm

Source for the built in CODE server: https://github.com/CollaboraOnline/richdocumentscode

**Comment by ftab** [comment]
I was able to build and successfully run unit tests with a modified isInContainer() function, but I'm not familiar with how to build it into the AppImage format that the nextcloud app wants to run. If there's an easy way to do that, I'll give it a shot with my setup and see if it works, and create a PR.

**Comment by Darshan-upadhyay1110** [comment]
hii @ftab this issue is too old. I am closing this for now. But feel free to reopen if it is still reproducible with newer COOL version.

Thanks
