### ISSUE TITLE
Mobile Select Objects

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#2507]
It's not possible to select more than one element on mobile UI. For example at Draw you can't align more elements vertical, ...

**Comment by Andreas-Kainz** [comment]
See  #2321

**Comment by Ezinnem** [comment]
The behaviour is not a bug. The objects are meant to be selected one at a time.

**Comment by Andreas-Kainz** [comment]
And how do you use vertical align at more symbols?
