### ISSUE TITLE
Slow on Android

### ISSUE THREAD

**Issue by another-sapiens** [CollaboraOnline/online#2509]
**Describe the bug**
The app's performance suffers upon opening any document (.docx, .odt, etc)

**To Reproduce**
1. Open the app
2. Open any document
3. Any operation will produce lag, most notably scrolling and zooming
4. App may become unresponsive

**Expected behavior**
Document can be scrolled and zoomed without much performance loss

**Actual behavior**
Document lags until any operation is rendered impossible

**Smartphone (please complete the following information)**
 - Device: [Samsung Galaxy A10S]
 - OS: [Android 10  - arm-v7abi]
 - Browser: [None, in-app]
 - Version: [Collabora Office 6.4]

**Additional context**
I should note that my phone is arm-v7abi, so it's not a 64 bit device. Could that have something to do?

Other than the performance loss after opening a file, the app seems to work perfectly.

**Comment by thebearon** [comment]
>     * Version: [Collabora Office 6.4]

Could you add the exact version number, possibly with the git hash from the About dialog?

**Comment by another-sapiens** [comment]
> Could you add the exact version number, possibly with the git hash from the About dialog?

Version: 6.4.9
online git-hash: ed79b031c
core git-hash: 2f8a1c873a82

**Comment by thebearon** [comment]
Indeed, this and #2542 are probably the same, please follow that one for updates.
