### ISSUE TITLE
How do I disable the option to save a document to a new file when the orginal file has changed?

### ISSUE THREAD

**Issue by objectivejs** [CollaboraOnline/online#2538]
The WOPI server I'm working on deals with timestamps. If I edit a file, touch it on the server then try to save it, a box pops up with the option to overwrite the file, abandon the modifications in which case the file is reloaded, or to save the file to another file. This last option should not be possible since UserCanNotWriteRelative is set to true on the original file. If I do save it to another file, the original file is overwritten.

**Comment by Ezinnem** [comment]
Fix on #3750
