### ISSUE TITLE
loolwsd --version doesn't return the actual version nor hash.

### ISSUE THREAD

**Issue by mhow2** [CollaboraOnline/online#2556]
**version**: collabora/code image from dockerhub / version 6.4.9

**Describe the bug**
`loolwsd --version` doesn't return the actual version nor hash.

**To Reproduce**
```
docker exec -it collabora bash
lool@8f6840e95ee2:/$ loolwsd --version
wsd-00452-00452 2021-06-04 09:35:55.142152 [ loolwsd ] INF  Initializing wsd. Local time: Fri 2021-06-04 09:35:55+0000. Log level is [8].| common/Log.cpp:325
wsd-00452-00452 2021-06-04 09:35:55.142202 [ loolwsd ] INF  Setting log-level to [trace] and delaying setting to configured [warning] until after WSD initialization.| wsd/LOOLWSD.cpp:1079
wsd-00452-00452 2021-06-04 09:35:55.142348 [ loolwsd ] INF  Initializing loolwsd server [].| wsd/LOOLWSD.cpp:1099
...
(looks like a regular startup)
```

**Expected behavior**
version number and hash displayed, like `--version-hash` (which is working) but including regular version.

**Actual behavior**
Seems to start the daemon instead of output version

**Comment by printminion** [comment]
@mhow2 Looks like there are no version output. See https://github.com/CollaboraOnline/online/blob/3a048ea/wsd/LOOLWSD.cpp#L1748

Only `--version-hash` is vailable

**Comment by timur-g** [comment]
Seems like this is WontFix.
