### ISSUE TITLE
Android fails to open XLSX spreadsheet that LibreOffice Desktop does

### ISSUE THREAD

**Issue by tlhackque** [CollaboraOnline/online#2558]
The attached .xlsx file opens successfully with LibreOffice, but not Collabora.

Transfered file from Win10 Desktop via usb to internal SD card on my Android smartphone (Moto X-4), Collabora 6.6.99 (as released today from F-Droid).  
git hashes `086b4f4c / 667264c967b1`

Open with Collabora Office (from Android "Files"), see "loading", then"Read only" (which it isn't), then a blank screen.

Waiting several minutes doesn't help.

The hamburger menu doesn't respond; the other menu-bar items are grayed-out, except the left arrow does exit.

FWIW, the file is created with a Perl script using `Excel::Writer::XLSX`, not Office or LibreOffice.

[Residents_2021_Jun.xlsx](https://github.com/CollaboraOnline/online/files/6603065/Residents_2021_Jun.xlsx)

**Comment by Ezinnem** [comment]
I am able to open the attached file in the Collabora Office app.

Device: Andriod Version 10
Version: Collabora Office 6.4.8 (git hash: ba528af9a).

@tlhackque, please,  can you share a screen recording showing the behavior you mentioned?

**Comment by tlhackque** [comment]
I have a Motorola X-4 - Android 9, which doesn't have a screen recorder.  This is the latest version available for the X-4.

Not clear that a screen recording would would help. 

I click on the file.  I see the loading... bar.  And the read-only notice.  Then I get a white screen - with the frame & blue pencil.  No data.

The blue pencil rotates slightly if touched then snaps back, but doesn't seem to do anything.  The hamburger menu and comment icons are dead.  Forward and reverse arrows are greyed out.  The left < causes an exit.

This may be an issue with how you work with Android 9/the X-4 display.  Issue #2451 seems to report the same thing.

I tried to capture some screenshots, but they didn't get the Loading... or read-only overlays.

I'm using the latest F-Droid release as shown below.
![Screenshot_20210629-103453](https://user-images.githubusercontent.com/332018/123817308-09888c00-d8c6-11eb-93ca-d4bd0760754c.png)
![Screenshot_20210629-102613](https://user-images.githubusercontent.com/332018/123816206-1eb0eb00-d8c5-11eb-9407-c099cae781c0.png)
![Screenshot_20210629-101625](https://user-images.githubusercontent.com/332018/123816208-1f498180-d8c5-11eb-85b2-a5afab687623.png)
![Screenshot_20210629-101646](https://user-images.githubusercontent.com/332018/123816210-1f498180-d8c5-11eb-9d08-2acee8e02f32.png)
![Screenshot_20210629-101904](https://user-images.githubusercontent.com/332018/123816212-1f498180-d8c5-11eb-92ba-c0e0a32011d6.png)
![Screenshot_20210629-102346](https://user-images.githubusercontent.com/332018/123816213-1fe21800-d8c5-11eb-8c5d-d36d7fb5d640.png)

**Comment by Ezinnem** [comment]
Thanks for sharing the screenshots.

The behaviour has been reproduced.

**Comment by Ezinnem** [comment]
The fix will available in the next update of the Android app, which will be released shortly.
