### ISSUE TITLE
iOS App: Collabora Calc on iPad - Sheet Menu not accessible

### ISSUE THREAD

**Issue by kcpvwill** [CollaboraOnline/online#2567]
**Describe the bug**
I’ve recently installed Collabora Office on my iPad & I’ve been trying to use the spreadsheet but I’ve run into a problem. I can create new sheets but I can’t rename a sheet, move it or delete it. On the Android version, a long touch on a sheet tab brings up the menu which allows me to do all the things I want to a sheet, but a long touch on a sheet tab on my iPad does nothing.
Is there a different method on the iPad for accessing the sheet menu or is it a bug?
.

**To Reproduce**
1. Open new or existing spreadsheet in Collabora Office app om iPad
2. Long touch on sheet tab at bottom of screen

**Expected behavior**
Menu should open to allow rename sheet, move sheet left or right  or delete sheet. This is what happens in Android

**Actual behavior**
Nothing happens

 - Device: iPad Pro 10.5"
 - OS: iPadOS 14.6
 - Browser: N/A
 - Version: Collabora Office 6.4.8

**Comment by Ezinnem** [comment]
I can confirm this issue. We will look into it

**Comment by tml1024** [comment]
When you say it works on Android, do you mean on Android phones, or on Android tablets?

**Comment by tml1024** [comment]
For what it's worth, I do get a menu when I long-press on a sheet name in the iOS app on iPhone. So most likely this is not a bug about iOS, but a bug about tablets. (In general it has been somewhat unclear in what ways the UI is supposed to be different on tablets compared to mobile phones.)

**Comment by kcpvwill** [comment]
Hi Tor,

I tested it on an Android phone (Samsung J6). Afraid I don’t have an Android tablet to try it on.

Thanks

Keith

**Comment by kcpvwill** [comment]
Hi Tor,

Thanks for the update. I guess Apple don’t want to give much information away.

Cheers

Keith

**Comment by tml1024** [comment]
I meant that this bug is specific to how the Collabora Online code works on tablets. Not that there would be some bug in iOS itself that causes the problem here.

**Comment by hack-char** [comment]
This bug is still in the latest iOS app on iPad. Is there any further info needed to fix it?

**Comment by nikslor** [comment]
@tml1024 I can reproduce this issue on 21.11.1 (2) on my tablet. I run the app, open a spreadsheet and try to rename the current sheet - no matter how long I press on the sheet, there is no popup. FWIW: the tablet is docked horizontally on the keyboard.

Happy to provide more details or a video if this helps.

**Comment by nikslor** [comment]
Still present in 22.05.11 (22.5.202303212054)
