### ISSUE TITLE
Mounting new fonts to the docker container's /usr/share directory

### ISSUE THREAD

**Issue by Lithimlin** [CollaboraOnline/online#2571]
**Describe the bug**
When mounting fonts into the `/usr/share/fonts` directory of the container, they will be shown in the font list and can be selected to be used, however they won't display. Instead, the font has to be mounted into `/opt/collaboraoffice<version>/share/fonts/local` so it can be displayed correctly. This can easily break when a new/different version of Collabora is used in the container.

**To Reproduce**
1. Download any (Truetype) font (which is not already installed in Collabora)
2. Mount it into the docker container's `/usr/share/fonts`
3. Open a document in Nextcloud with Collabora. This document can either already have something written with that font in it or be a new one.
4. Be greeted by empty space where the new font should be

**Expected behavior**
The font is displayed in the document

**Actual behavior**
The font is not displayed in the document despite being in the font list and being selectable.

**Screenshots**
Here, you can see some text using the "Inter" font which was mounted into the container, displayed correctly. Here, the font was mounted into `/opt/collaboraoffice6.4/share/fonts/truetype/local/inter`.
![image](https://user-images.githubusercontent.com/25646100/121146159-f68f1880-c83f-11eb-8722-5276d1f2bf29.png)

![image](https://user-images.githubusercontent.com/25646100/121147459-2d196300-c841-11eb-8143-816c2de20899.png)
Despite being still in the list of fonts to choose from, the text is now blank. This is when the font is mounted into `/usr/share/fonts/truetype/inter`

**Desktop**
 - OS: Linux (any)
 - Browser: Firefox
 - Version: 89.0

**Docker**
 - Image: collabora/code:latest

**Nextcloud**
- Version: 21.0.2
- On OS: NixOS 20.09.4302.17a455ce5a2 (Nightingale)

**Comment by joergmschulz** [comment]
had this as well. 
Needed to do the following in my derived Dockerfile:

(...)
COPY fonts /usr/share/fonts/truetype/

RUN cp -rv /usr/share/fonts /opt/lool/systemplate/usr/share
(...)

owner of that fonts directory: 101

**Comment by Lithimlin** [comment]
Not sure which version this happened in, but in the currently latest image (21.11.1.0.1), the directory is now just called `/opt/collaboraoffice` without the version number, fixing this issue.
It is not `/usr/share/fonts` but it does the job and now depends mostly on personal preference.

**Comment by MarcelWaldvogel** [comment]
Instead of creating a derived `Dockerfile`, you can also use a `Dockerfile` inheriting from the official image (probably the `chown` is superfluous), with the fonts in `./fonts/`:

```dockerfile
FROM collabora/code

COPY --chown=104:106 fonts /usr/share/fonts/truetype/more/
COPY --chown=104:106 fonts /opt/cool/systemplate/usr/share/fonts/truetype/more/
```

And the `docker-compose build --pull && docker-compose up -d` (`docker-compose up -d --build` does not seem to update the base image).
