### ISSUE TITLE
pep8 coding style conformance for the Python files

### ISSUE THREAD

**Issue by mrkara** [CollaboraOnline/online#258]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @mrkara 

Check the Python files in the project for pep8 coding style conformance, and fix the found issues.

Install the code style checker:
```bash
pip install pycodestyle
```

Check the messages on this issue to see which files have already been taken, and choose one of the files below:
```bash
ALL DONE. Thanks to everyone who contributed! :)
```

**Drop a message on this issue, stating which file you have chosen, to avoid merge conflicts and productivity losses.**

Run the check on it (taking `po2json.py` as example):
```bash
pycodestyle loleaflet/util/po2json.py
```

Fix the listed style issues, and **send one pull request for each file checked**.

**Comment by corleone77** [comment]
Hi @mrkara 
Let me try it ¡¡¡
;)

**Comment by mrkara** [comment]
> Hi @mrkara
> Let me try it ¡¡¡
> ;)

Hi @corleone77 !

Please go ahead, and send your PR. :)

Don't forget to take a look at #259 first, which is a PR for the same issue, to avoid merge conflicts and productivity loss. ;)

**Comment by yusufketen** [comment]
Hi, I will work on scripts/unocommands.py.

**Comment by bgbenzer** [comment]
Hi, I will try scripts/untranslated.py

**Comment by alanverdugo** [comment]
Hi, I will work on `wsd/lint-discovery.py`
:)

**Comment by mrkara** [comment]
Thank you to all who have worked on this issue. It seems completed now. :)
