### ISSUE TITLE
Calc - Can't create a hyperlink when text contains an apostrophe

### ISSUE THREAD

**Issue by siccovansas** [CollaboraOnline/online#2628]
**Describe the bug**
I can't create a hyperlink when the selected text contains an apostrophe, both on Firefox and Chromium.

**To Reproduce**
1. Open a .ods file using Collabora (NB I'm using Nextcloud)
2. Type some text containing an apostrophe in a cell, e.g. "this won't work"
3. Select the word "won't" and press CTRL+K and insert a URL to create a hyperlink
4. See that the word isn't changed into a hyperlink

**Expected behavior**
The word should become a hyperlink

**Actual behavior**
The word isn't changed into a hyperlink

**Desktop (please complete the following information)**
 - OS: Ubuntu 18.04
 - Browser: Firefox 89.0 and Chromium 91.0.4472.101
 - Version: Nextcloud 21.0.2 using Collabora Online 4.1.1 and  Collabora Online - Built-in CODE Server 6.4.806

**Comment by Ezinnem** [comment]
I can add a hyperlink to a word with an apostrophe in a .ods file.

Browser: Chrome Version 87.0.4280.141 and Firefox 75.0
OS: Ubuntu 20.04
Version: Collabora Online 6.4.10 snapshot (git hash: [7de5c3b](https://github.com/CollaboraOnline/online/commits/7de5c3b)).


@siccovansas, can you share a screen recording showing the behavior you mentioned?

**Comment by siccovansas** [comment]
Thanks for your reply @Ezinnem!

I've tried to replicate the problem on [try.nextcloud.com](https://try.nextcloud.com) which seems to run Collabora Online 6.4.10 snapshot (git hash: 465bfb9) as well. The problem doesn't happen over there! I'll wait for Collabora Online 6.4.10 to be released and test it again on my instance to see if that version solves the problem on my instance as well.

**Comment by Ezinnem** [comment]
The behaviour described is not reproducible.

**Comment by siccovansas** [comment]
@Ezinnem I just updated 'Collabora Online - Built-in CODE Server' to version 6.4.1003 which uses Collabora Online 6.4.10 (git hash: 2c4ce99). The problem still exists though, so could you reopen this issue? I made screen recording showing the problem:

https://user-images.githubusercontent.com/696839/124758269-aedada00-df2e-11eb-9711-b26862da6f41.mp4

I again tried to replicate the problem on a demo instance on https://try.nextcloud.com/, but the problem doesn't occur there. This is in the information in the about dialog of the demo instance:

> **LOOLWSD**
> 6.4.10snapshot (git hash: 2c4ce99)
> Served by: cec93599
> **LOKit**
> Collabora Office 6.4-44 (git hash: 34ade20)
> "Ubuntu 18.04.5 LTS"

And this is the information in the about dialog on my instance:

> **LOOLWSD**
> 6.4.10 (git hash: 2c4ce99)
> Served by: aed9858f
> **LOKit**
> Collabora Office 6.4-44 (git hash: 2b31b2e)
> "Debian GNU/Linux 10 (buster)"
> "Slow Proxy"

**Comment by siccovansas** [comment]
@Ezinnem could you reopen this issue? Thanks :)!

**Comment by Ezinnem** [comment]
It seems that when the user clicks on the word with an apostrophe, the hyperlink shows up.

@siccovansas, does this occur for you?

**Comment by siccovansas** [comment]
@Ezinnem thanks for reopening! The link doesn't show up on words with an apostrophe. As you can see in the video I made above, nothing happens when I create a link on a word with an apostrophe. When I create a link on another word that word is then clearly contains a link.

**Comment by timur-g** [comment]
This stays as Unconfirmed for a long time. I tested Online 22.05 and I do not reproduce. 
I did not test  Built-in CODE Server but if it happens only there, it should be reported against https://github.com/CollaboraOnline/richdocumentscode/issues.
I see an issue with making link for a single word in newer Online, that I will report separetely.

**Comment by siccovansas** [comment]
Thanks for looking into this issue @timur-g! I indeed can't reproduce this issue in 23.05.7.5 because there seems to be another you found in #8184. I don't have access to 22.05, so I can't check if I still encounter my bug there. I'll keep track of that #8184 . If that is fixed I'll check again if my bug will happen again.
