### ISSUE TITLE
loolwsd performance api

### ISSUE THREAD

**Issue by bpavesi** [CollaboraOnline/online#2639]
**Is your feature request related to a problem? Please describe.**
I need to query loolwsd performances without login into admin interface, cause i would like to integrate that informations into an Owncloud app.

**Describe the solution you'd like**
It would be nice to access loolwsd perfomances information with an api.

**Comment by thebearon** [comment]
What kind of performance information are you looking for?
Several kinds of metrics are available already, here's a list: https://github.com/CollaboraOnline/online/blob/master/wsd/metrics.txt
