### ISSUE TITLE
links.txt support from LibO

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#269]
In LibreOffice the icon themes are done that way that if you have an icon twice, you draw the icon once and the second, ... icon you wrote into the links.txt file (which is in the root folder of the icon theme).

This solve icon work, disk space, ...

For better usage of icon theme (easier sync between COOL and LibO) it would be great to have links.txt support for icons.

**Comment by DarkknightAK** [comment]
@rizmut @pedropintosilva

**Comment by rizmut** [comment]
+1000 from me

**Comment by DarkknightAK** [comment]
the good thing is that with links.txt and the already wip move of the cool image files to the LibO icon folder structure, COOL can use all LibO icon themes without additional work and the other way around.

**Comment by pedropintosilva** [comment]
Closing this as we already have a bultin `iconURLAliases` that not only avoid icon duplication but allows us to have a clear view of what is what
