### ISSUE TITLE
clone didn't copy Style

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#270]
If you use clone at a header1 to a Text Body element, the Text Body element will get the same formating than Header 1, BUT it stay Text Body and all Formating was now direct formating instead the use of Styles.

**Comment by thebearon** [comment]
That is the normal behavior in LibreOffice as well, paragraph styles are copied as style if you hold Ctrl when copying the formatting. For reference please see https://bugs.documentfoundation.org/show_bug.cgi?id=59029
