### ISSUE TITLE
Grey/dark document viewer when using customized dark mode in Mozilla Firefox after latest update of Collabora/Code in Nextcloud

### ISSUE THREAD

**Issue by synlic** [CollaboraOnline/online#2727]
**Describe the bug**
When using Mozilla Firefox (currently on 89.0.1 64-bit on ArchLinux) and having changed the default background color on new pages the editing view when using Collabora/Code in Nextcloud is grey/dark so you can't see anything.  This happend after I updated both my Nextcloud servers today. This was not an issue before.

I can still see the toolbar and looks like I can select text, but I can't see any text.

**To Reproduce**
1. Open a document in Collabora/Code in Firefox while using dark mode and editing the default page color.
2. Only see a grey box in hte document viewing area. 

**Expected behavior**
I expect to see the text in the document viewing area.

**Actual behavior**
I don't see any text in the document viewing area.

**Screenshots**
[https://nextcloud.levin.blog/index.php/s/NfxfagSYWD2g2LH](https://nextcloud.levin.blog/index.php/s/NfxfagSYWD2g2LH)

**Desktop (please complete the following information)**
 - OS: ArchLinux
 - Browser: Firefox 89.0.1 64-bit

**Comment by synlic** [comment]
Still error on updating to latest Collabora/Code Docker and Nextcloud plugin.

**Comment by pedropintosilva** [comment]
Hi @synlic and thanks for reporting this (and sorry for the delay)! I think this has been fixed meanwhile, right?

https://user-images.githubusercontent.com/65948705/166426887-0ab55a50-1197-4753-bfe5-77e4e34a6071.mp4

**Comment by gitgt** [comment]
Problem with this report is that we don't know exactly what it refers to, screenshots are not available. 
I assume it's about font color when using dark background in a document, set via Page Styles/Area.
Font is not visible because it's black. It should be Automatic color for new documents so this should be Enhancement request, not a bug.
