### ISSUE TITLE
Notebookbar switch to compact layout

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#273]
The Notebookbar layout has now two rows which cause a big issue, cause some commands are merged in both rows and others not.

If you use an one row layout (Notebookbar compact) it would have the following advantages:

- way easier implementation, cause the js/ui file don't have to respect the arrangement (command over two rows, ...)
- compare to MSO Collabora Online didn't has that much commands so there are not two rows needed (see menubar items)
- MSO has also a simplified ribbon approach
- easier shrinking options possible (hide labels if width isn't enough)

I prepare in LibO the tabbed and tabbed compact layout and have to say, tabbed layout isn't needed and the drawbacks from dev point of view are in any relation to the benefits (be more compatible to MSO).

**Comment by DarkknightAK** [comment]
@eszkadev you know the codebase best.
