### ISSUE TITLE
CODE 6.4.10 Writer: Style panel:  Scrollbar, Spacing, Alignment

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#2751]
Scrollbar:  I can see 5 styles, it isn't obvious that there are more styles to choose from to new user. Would it be possible to have an indication that there are more styles without having to click it first for a scrollbar to appear? Perhaps an arrow, or perhaps the scrollbar is always visible.  On occasions I have seen 2 scrollbars a fat one and a skinny one, I am not sure why it varies, I haven't tried to reproduce.

Spacing:  A small cosmetic: The sample style examples may be truncated because they do not fit in the allocated space, I get why this may not be fixable; However, it appears that more is missing than is necessary. i.e. there is a overly big white gap between one style example and the style next to it.

Alignment: The example styles and the respective text below look centred in most cases, but not all.  e.g. for "Text Body" and "Quotations" look a bit messy because not aligned consistently.

btw I really like the new toolbars in all the apps, they are very clean, responsive and relevant.

**Comment by rpear** [comment]
[](url)
![Screenshot 2021-07-04 5 45 28 PM](https://user-images.githubusercontent.com/80790599/124377539-b95b6080-dcef-11eb-94c1-31f16dfde77a.png)
Screenshot of Styles toolbar options

**Comment by Ezinnem** [comment]
@eszkadev, @pedropintosilva, Please can you check this?

**Comment by eszkadev** [comment]
@rpear which browser (and version) do you use?

**Comment by rpear** [comment]
@eszkadev  Hi, I am using an Acer R13 Chromebook running the latest Google Chrome Version 91.0.4472.147 (Official Build) (32-bit).  Maybe related: The toolbar sometimes gets an arrow on the right side, for scrolling the toolbar as if it has become a pixel or 2 too long, see attached screenshot
![Screenshot 2021-07-06 9 30 16 AM](https://user-images.githubusercontent.com/80790599/124524137-2e887c00-de3d-11eb-8941-46b0e993b598.png)

**Comment by rpear** [comment]
Hi, I am happy for you to delete this one, I checked it out again and no longer feel it needs any changes, I am not sure if that is me or if it has improved a bit since Jul.  However, I still think it would benefit if the narrow scrollbar was always visible or became visible when the mouse hovers over the styles, currently the scroll bar only appears after you start scrolling.

**Comment by rpear** [comment]
Closed this

**Comment by rpear** [comment]
Closed this issue
