### ISSUE TITLE
Loolwsd 6.4.10 - Debian 9 - SNI enforced on OwnCloud/NextCloud instance get a 403 reply on CODE

### ISSUE THREAD

**Issue by Athar42** [CollaboraOnline/online#2752]
**Describe the bug**
With the latest update to Loolwsd 6.4.10 (and other collabora updates related), the server can't work anymore on a client which used the "SSLStrictSNIVHostCheck" setting to ON.
This setup was working prior the latest updates.

**To Reproduce**
1. On the client (hosting the NextCloud application for example), just set the "SSLStrictSNIVHostCheck" to ON
2. Try to open a document which Collabora would open, it will fail with an access denied.
3. Set the previous setting to off, test again, and it'll pass.

**Expected behavior**
Should work.

**Actual behavior**
Document can't load as the loolwsd service didn't comply with this Apache directive "SSLStrictSNIVHostCheck".

**Desktop (please complete the following information)**
 - OS: Debian 9.13
 - CODE : 
```
 # loolwsd --version-hash
51b8716
# loolwsd --version
terminate called after throwing an instance of 'std::runtime_error'
Abandon
```
**As you may see, even the "--version" is broken there**
But in the log, we have this : 
`wsd-20943-20943 2021-07-04 15:30:34.621808 [ loolwsd ] INF  Loolwsd version details: 6.4.10 - 51b8716 - on "Debian GNU/Linux 9 (stretch)"| wsd/LOOLWSD.cpp:4069`

**Additional context**
On the webserver : 
Error.log
`[Sun Jul 04 17:04:41.466646 2021] [ssl:error] [pid:tid] AH02033: No hostname was provided via SNI for a name based virtual host`

Access.log
```
CODE SERVER IP - - [04/Jul/2021:17:04:39 +0200] "GET /index.php/apps/richdocuments/wopi/files/32_odfl?access_token=WXYZ&access_token_ttl=0 HTTP/1.1" 403 2255 "-" "LOOLWSD HTTP Agent 6.4.10"
CODE SERVER IP - - [04/Jul/2021:17:04:41 +0200] "GET /index.php/apps/richdocuments/wopi/files/32_odfl?access_token=WXYZ&access_token_ttl=0&permission=edit HTTP/1.1" 403 2255 "-" "LOOLWSD HTTP Agent 6.4.10"
```

On CODE server log : 
`wsd-00546-18244 2021-07-04 14:24:23.325579 [ docbroker_010 ] ERR  Failed to add session to [/index.php/apps/richdocuments/wopi/files/32_odfl] with URI [https://TLD/index.php/apps/richdocuments/wopi/files/32_odfl?access_token=WXYZ&access_token_ttl=0&permission=edit]: WOPI::CheckFileInfo failed: <!DOCTYPE html>`

The SNI setting is enforced like this since a few months now, and was working at least 3 weeks back, so something might got broken in the recent update, hope you have all the needed infos.

Edit : This issue happen only on a multiple domains server (several virtual hosts).
I just did a test : 

NextCloud Virtual Host : SSLStrictSNIVHostCheck On
OwnCloud Virtual Host : SSLStrictSNIVHostCheck Off

This setup is working and both can use the same CODE server.
As soon as I put the "OwnCloud" to On, both fail.

Previously, this was a global variable, for the whole server, and this was working (so both to "On").
CODE updated to 6-4-10.2 without change.

**Comment by canuckdev** [comment]
Yup, exact same problem on Ubuntu 20.04 with same configuration as Athar42. To circumvent I had to put:

`SSLStrictSNIVHostCheck Off`

in both the default vhost config **and** the ownCloud vhost config, since the default for this directive is On on my servers for enhanced security.

**Comment by vedatbotuk** [comment]
I have the same issue after the upgrade yesterday to 6.4.10. Collabora-Office not working on owncloud.
```
Jul 05 22:11:57 debian-kammer loolwsd[12019]: | wsd/DocumentBroker.cpp:1854
Jul 05 22:11:57 debian-kammer loolwsd[12019]: wsd-12019-12843 2021-07-05 20:11:57.531665 [ docbroker_01a ] ERR  Failed to add session to [/apps/richdocuments/wopi/files/xxx] with URI [https://xxxx.xxx.xxx/apps/
Jul 05 22:11:57 debian-kammer loolwsd[12019]: No server is available to handle this request.
Jul 05 22:11:57 debian-kammer loolwsd[12019]: </body></html>
```

**Comment by canuckdev** [comment]
I believe this issue is about the following apache response appearing in the loolwsd log:

`The client software did not provide a hostname using Server Name Indication (SNI), which is required to access this server.`

**Comment by vedatbotuk** [comment]
Tried with HaProxy and it sends SNI. In this case gives loolwsd the same issue.

**Comment by bruno666** [comment]
Same issue on Debian 10 with latest Collabora debian packages 6.4.10-2

**Comment by phormanns** [comment]
same here - Debian 10

**Comment by atj** [comment]
Apologies for the "+1" comment, but hopefully the log output might be helpful:

```
$ cat /etc/debian_version
10.10
$ dpkg -l |grep collabora |head -n1
ii  collaboraoffice6.4                           6.4.10.44-44                  amd64        Brand module for Collabora Office 6.4-44
```

loolwsd log shows Apache returning the SNI error:

```
loolwsd[14497]: wsd-14497-28065 2021-07-14 09:03:44.535419 [ docbroker_009 ] ERR  WOPI::CheckFileInfo failed for URI [https://nextcloud.example.com/index.php/apps/richdocuments/wopi/files/27597_oc24syfgmejq?access_token=<redacted>&access_token_ttl=0]: 403 Forbidden. Headers:         Date: Wed, 14 Jul 2021 09:03:44 GMT /         Server: Apache /         Content-Length: 337 /         Content-Type: text/html; charset=iso-8859-1 /         Body: [<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
loolwsd[14497]: <html><head>
loolwsd[14497]: <title>403 Forbidden</title>
loolwsd[14497]: </head><body>
loolwsd[14497]: <h1>Forbidden</h1>
loolwsd[14497]: <p>You don't have permission to access this resource.Reason: The client software did not provide a hostname using Server Name Indication (SNI), which is required to access this server.<br />
loolwsd[14497]: </p>
loolwsd[14497]: </body></html>
loolwsd[14497]: ]| wsd/Storage.cpp:723
loolwsd[14497]: wsd-14497-28065 2021-07-14 09:03:44.537007 [ docbroker_009 ] ERR  loading document exception: Access denied, 403. WOPI::CheckFileInfo failed on: https://nextcloud.example.com/index.php/apps/richdocuments/wopi/files/27597_oc24syfgmejq?access_token=<redacted>&access_token_ttl=0| wsd/DocumentBroker.cpp:1854
loolwsd[14497]: wsd-14497-28065 2021-07-14 09:03:44.537553 [ docbroker_009 ] ERR  Failed to add session to [/index.php/apps/richdocuments/wopi/files/27597_oc24syfgmejq] with URI [https://nextcloud.example.com/index.php/apps/richdocuments/wopi/files/27597_oc24syfgmejq?access_token=<redacted>&access_token_ttl=0]: Access denied, 403. WOPI::CheckFileInfo failed on: https://nextcloud.example.com/index.php/apps/richdocuments/wopi/files/27597_oc24syfgmejq?access_token=<redacted>&access_token_ttl=0| wsd/DocumentBroker.cpp:1816
loolwsd[14497]: wsd-14497-28065 2021-07-14 09:03:44.538109 [ docbroker_009 ] ERR  Unauthorized Request while starting session on /index.php/apps/richdocuments/wopi/files/27597_oc24syfgmejq for socket #20. Terminating connection. Error: Access denied, 403. WOPI::CheckFileInfo failed on: https://nextcloud.example.com/index.php/apps/richdocuments/wopi/files/27597_oc24syfgmejq?access_token=<redacted>&access_token_ttl=0| wsd/LOOLWSD.cpp:3582
```

**Comment by stavros-k** [comment]
> **Edit:** It looks to me like PR #2716 will resolve this issue as it modifies calls to `SslStreamSocket` to pass a hostname instead of a file descriptor.

I does not seem to have fixed it, (using the 6.4.10.5 image)

**Comment by atj** [comment]
> > **Edit:** It looks to me like PR #2716 will resolve this issue as it modifies calls to `SslStreamSocket` to pass a hostname instead of a file descriptor.
> 
> I does not seem to have fixed it, (using the 6.4.10.5 image)

Yep, looks like I was wrong - it's not fixed in 6.4.10.5:

```
 $ dpkg -l |grep collabora |head -n1
ii  collaboraoffice6.4                           6.4.10.45-45                  amd64        Brand module for Collabora Office 6.4-45
```

Log output shows the same SNI error:

```
loolwsd[417]: wsd-00417-01030 2021-07-21 07:48:39.175060 [ docbroker_005 ] ERR  WOPI::CheckFileInfo failed for URI [https://nextcloud.example.com/index.php/apps/richdocuments/wopi/files/27502_oc24syfgmejq?access_token=<redacted>&access_token_ttl=0]: 403 Forbidden. Headers:         Date: Wed, 21 Jul 2021 07:48:39 GMT /         Server: Apache /         Content-Length: 337 /         Content-Type: text/html; charset=iso-8859-1 /         Body: [<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
loolwsd[417]: <html><head>
loolwsd[417]: <title>403 Forbidden</title>
loolwsd[417]: </head><body>
loolwsd[417]: <h1>Forbidden</h1>
loolwsd[417]: <p>You don't have permission to access this resource.Reason: The client software did not provide a hostname using Server Name Indication (SNI), which is required to access this server.<br />
loolwsd[417]: </p>
loolwsd[417]: </body></html>
loolwsd[417]: ]| wsd/Storage.cpp:703
loolwsd[417]: wsd-00417-01030 2021-07-21 07:48:39.175233 [ docbroker_005 ] ERR  loading document exception: Access denied, 403. WOPI::CheckFileInfo failed on: https://nextcloud.example.com/index.php/apps/richdocuments/wopi/files/27502_oc24syfgmejq?access_token=<redacted>&access_token_ttl=0| wsd/DocumentBroker.cpp:1893
```

**Comment by Aejoh** [comment]
I have the same problems.

**Comment by Athar42** [comment]
Hope this will help.

Last CODE update did break the workaround on NextCloud (even if SNI isn't enabled).
Still working fine with my OwnCloud instance and SNI off (on the same web server of course).

**Comment by mmeeks** [comment]
It is possible that a recent fix that removes the port-number (which was un-conditionally to the Host: even for 80 & 443) might help here - that's merged & will ship next week.

**Comment by Athar42** [comment]
Since at least 2 releases, this seems fixed already (at least for me, it's working again).

For me, it's all good so far ;)
