### ISSUE TITLE
CALC: no horizontal scrollbar

### ISSUE THREAD

**Issue by paedk** [CollaboraOnline/online#2773]
A have a very wide sheet in CALC and there's no horizontal scrollbar popping up. The button to scroll left and right don't seem to do anything. 
CODE  6.4.10  (git hash: 51b8716); Chrome Version 91.0.4472.124 in Win10 on a Lenovo Thinkpad L13.

**Comment by rpear** [comment]
When I move the mouse to the bottom row the scrollbar pops up OK, I don't think that there ever were scroll arrows, I have checked 6.4.3 as well. I think that the scroll arrows at the bottom left are for switching through sheets? However these don't switch through sheets in 6.4.3 or 6.4.10 !   I am using Chrome Version 91.0.4472.114 (Official Build) (64-bit) on a Chromebook CODE: 6.4.10snapshot (git hash: 94a1a06) Served by: 492fe155    Note that my popup scrollbar in 6.4.10 is comparable to the older version 6.4.3 except that the scrollbar is now fatter and more usable. Screenshot of 6.4.10:
![Screenshot 2021-07-07 8 47 34 AM](https://user-images.githubusercontent.com/80790599/124676801-8b019f00-df02-11eb-90cf-2bba69eedc33.png)

**Comment by thebearon** [comment]
@paedk please check if you can find the horizonal scrollbar as shown by @rpear.

**Comment by paedk** [comment]
Thanks, but that's kind of what I meant. When I move the mouse to the rightmost side, a grayish vertical scroll bar pops up. But nothing pops up when I move the mouse to the bottom row. 
![Unbenannt](https://user-images.githubusercontent.com/43025993/124708172-2e01eb00-defa-11eb-833a-6f6c896b4aee.png)

I'm using version 6.4.10

**Comment by rpear** [comment]
@paedk It works on my Chromebook, it could be the way it works with your OS, web browser and web browser version, etc.  What are you using, I might be able to try it here.

**Comment by paedk** [comment]
@rpear Win10,  Chrome Version 91.0.4472.124 on a Lenovo Thinkpad L13.

**Comment by rpear** [comment]
@paedk I have tried it on a friends laptop (Acer Predator Triton 500), Win10 Home, Chrome Version 91.0.4472.124, it pops up OK. So in your screenshot the mouse would need to be roughly where row 222 is, and the scrollbar would be short like in my image.  Assuming that's what you've done, hopefully someone else can help with this further.

**Comment by rpear** [comment]
@paedk    fyi:  re: "there's no horizontal scrollbar popping up",  I just noticed the following commit made on 11th July:   "Make vertical and horizontal scroll bars always visible on desktop when the file size is larger then the view size"
https://github.com/CollaboraOnline/online/commit/24b67719472fe30f70fadd864b48895da8b32416  I am testing a very new release of CODE and indeed the scroll bars are now always visible in Calc.  Maybe this will fix the problem you are experiencing?

**Comment by paedk** [comment]
ok maybe this will help, but atm it is still unchanged. Guess I have to wait for our IT department to install this new release. Will keep you posted.

**Comment by Ezinnem** [comment]
The scroll buttons and horizontal scrollbar issues have been fixed.

Issues are no longer reproducible in LOOLWSD 6.4.10 snapshot (git hash: [788e0aa](https://github.com/CollaboraOnline/online/commits/788e0aa))
