### ISSUE TITLE
Ignoring an underlined unknown word in the dictionary resets the modification of the document and sends the cursor to the beginning

### ISSUE THREAD

**Issue by RegisPerdreau** [CollaboraOnline/online#2777]
Ignoring an underlined unknown word in the dictionary resets document modification and sends the cursor to the first page.

**To Reproduce**
1. load test-file (but any document seems to work )
2. do some random modifications
3. go to page 2
4. put cursor on an unknown underlined word
5. in the right click menu, select "ignore all" option
6. after few seconds, Cool will send you to the beginning of the document and all modifications are lost.
7. underlined word is not ignored..
[test-file.odt](https://github.com/CollaboraOnline/online/files/6768808/test-file.odt)

6.4.9 (git hash: 0b3211b)
LOKit Collabora Office 6.4-41

**Comment by mmeeks** [comment]
Sounds like a server-side crash; can you get a trace from the logs - should be a 'SEGV' there

**Comment by rpear** [comment]
In case this helps eliminate some things: "ignore all" works OK for me using an existing document I have on on a Chromebook accessing CODE 6.4.10snapshot (git hash: 94a1a06) Served by: 492fe155 (commits on Jul 5, 2021) LOKit Collabora Office 6.4-43

**Comment by mmeeks** [comment]
Struggling to reproduce this; the logs would really help. Thanks!

**Comment by mmeeks** [comment]
I think Miklos just fixed this here: https://gerrit.libreoffice.org/c/core/+/119006 =)

Thanks for reporting!
