### ISSUE TITLE
CODE 6.4.10 and 6.4.2: Calc: Sheet scroll arrows are not working

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#2787]
The 4 sheet scroll arrows at the bottom left for navigating Calc sheets do not work. Possibly related to #2567.
Tested in CODE 6.4.10, 6.4.2 and the Chromebook Collabora Office 6.4.3 app.  For 6.4.10:  I am using Chrome Version 91.0.4472.114 (Official Build) (64-bit) on a Chromebook CODE: 6.4.10snapshot (git hash: 94a1a06) Served by: 492fe155, commits on Jul 5, 2021.
![Screenshot 2021-07-07 9 25 04 AM](https://user-images.githubusercontent.com/80790599/124678570-26484380-df06-11eb-940f-999a476a2dc5.png)

**Comment by Ezinnem** [comment]
I can confirm this behavior in CODE 6.4.10 snapshot (git hash: [94a1a06](https://github.com/CollaboraOnline/online/commits/94a1a06))

**Comment by Ezinnem** [comment]
The fix has been made.

The buttons work fine in 6.4.10 (git hash: [187bec40](https://github.com/CollaboraOnline/online/commits/187bec40)).

**Comment by rpear** [comment]
@Ezinnem, the 4 buttons still don't work for me, I am accessing CODE 6.4.10-10 (14 Aug 2021) from an up to date Chromebook. How about for you?  CODE: LOOLWSD 6.4.10 (git hash: d12ab86) Served by: 4d6109a4

**Comment by Ezinnem** [comment]
@rpear, the buttons works fine on LOOLWSD 6.4.10 (git hash: [d12ab86](https://github.com/CollaboraOnline/online/commits/d12ab86)).

You may need more sheets in your Calc file to test using the buttons.

When there are more sheets, the buttons help the user to navigate through the sheets more efficiently.

**Comment by rpear** [comment]
@Ezinnem I have about 7 or 8 sheets.  I can reproduce these buttons not working on a Ubuntu 20.04.2 laptop running latest Firefox and Chromium as well. I tried an 8" Android tablet but it does not show these 4 buttons, I expect this is due to the limited screen size.  If they works for you, what is your OS/browser? or could it be an oddball and due to the fact that I am doing this on a spreadsheet that has been shared with me. I might update the main description with these additions.
Opinion: It is low priority, as it is unlikely to prevent someone from working.

**Comment by Ezinnem** [comment]
@rpear, If the sheets are up to 25 or more, the buttons help the user to navigate through the sheets more efficiently.

**Comment by rpear** [comment]
@Ezinnem, on the devices I tried the buttons do not navigate between the sheets. I have uploaded a video, am I misunderstanding it? https://user-images.githubusercontent.com/80790599/130074137-7254984d-8c80-4f3e-b221-3d286d68ad28.mp4

**Comment by Ezinnem** [comment]
https://user-images.githubusercontent.com/54344301/130085978-b5b89956-917b-42f4-a048-ceef3272edb5.mp4


@rpear, the buttons help with scrolling the sheet list buttons.; they do not navigate directly.

**Comment by rpear** [comment]
OK.... I get it now!   Not as I expected, I thought it would change the focus to the next tab, oops.  btw it's not 25 or more sheets it appears to be if the sheet tabs are wider than the current screen width then it scrolls.
I'll add these 4 buttons to a list of buttons that could be greyed out when they are irrelevant.
