### ISSUE TITLE
Add outline to color indicator in the Classic mode

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2809]
1. build it locally : https://collaboraonline.github.io/post/build-code/ or use [gitpod](https://github.com/CollaboraOnline/online#gitpod) 
2. Switch the ui mode in the `coolwsd.xml`
  - in `<user_interface>` change the value to `classic`  like so:
```xml
    <user_interface>
      <mode type="string" desc="Controls the user interface style. The 'default' means: Take the value from ui_defaults, or decide for one of classic or notebookbar (default|classic|notebookbar)" default="default">classic</mode>
    </user_interface>
```
3. Do a `make run` and observe the problem
4. Try to fix it :)
 - Make the colour rectangle be visible even when there is no colour (via some sort of outline etc)

_______

Right now our toolbar colour dropdown components ( `tb_editbar_item_fontcolor` `tb_editbar_item_backcolor`) look like this if:

- no text is selected
- the text that is selected has is black and has no backcolor (https://github.com/CollaboraOnline/online/issues/2810)

![image](https://user-images.githubusercontent.com/65948705/124913889-faa18800-dfef-11eb-88e6-b1dbc0c11ed2.png)

This is how it looks when we select a text with back color:
![image](https://user-images.githubusercontent.com/65948705/124913935-0725e080-dff0-11eb-8469-1455ee0ab125.png)

**Comment by georg480** [comment]
![image](https://user-images.githubusercontent.com/79664365/131212665-77b640a1-5c67-4bd0-a696-a570f63834ba.png)

**Comment by pedropintosilva** [comment]
@georg480 sorry for the delay.

The problem only when using classic mode. In the Notebookbar mode we already have that border : ) (that's why it's a easy hack )

-----

Switch to classic mode

1. Via `loolwsd.xml` change `notebookbar`
 to `classic` 
 
 ```
    <user_interface>
      <mode type="string" desc="Controls the user interface style (classic|notebookbar)" default="classic">notebookbar</mode>
    </user_interface>
```

**Comment by pedropintosilva** [comment]
Hi @georg480 , are you still working or intend to work on this?
