### ISSUE TITLE
Text color is not being set by default

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2810]
**Describe the bug**
When selecting default text (black text) the drop-down is still not showing the colour indicator
![image](https://user-images.githubusercontent.com/65948705/124913889-faa18800-dfef-11eb-88e6-b1dbc0c11ed2.png)

**Comment by timur-g** [comment]
I am not sure what this refers to, I assume text color did not show last selected color, the one that applies next time,
Now it is shown: 
![image](https://github.com/CollaboraOnline/online/assets/7240617/fa1a2522-e39f-4581-9847-bee645cf0212)
I close based on that.
