### ISSUE TITLE
Mobile: Word Count...

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2811]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @pedropintosilva 

- Remove unnecessary bottom borders (from values while keeping the ones from labels)
- Fix padding

| Word count on mobile | 
:-------------------------:
| <img src="https://user-images.githubusercontent.com/65948705/124916446-fb87e900-dff2-11eb-96c7-b606389f7de7.png" width="411"> |

_on distro/collabora/co-6-4 it's ok or at least much better_

**Comment by brittanyjoiner15** [comment]
@pedropintosilva sorry i actually won't be able to take this one anymore 😭 Got kinda overcommited with other issues! Sorry!

**Comment by ArshErgon** [comment]
hey @pedropintosilva !
can you tell me where I can find that file and how I will be running this locally? I think I can fix this.

**Comment by Andreas-Kainz** [comment]
![image](https://user-images.githubusercontent.com/8517736/183300818-ebce61f4-9b82-48dd-9ed4-e5e3a6629acb.png)

Dialog was already updated.
