### ISSUE TITLE
Mobile: do not use span inside of a button element

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2812]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @pedropintosilva 

On master we have now a bug where buttons have an additional unnecessary span, which in turn doesn't get properly styled:

![image](https://user-images.githubusercontent.com/65948705/124917511-39394180-dff4-11eb-93a0-efbda4dd0921.png)

_on distro/collabora/co-6-4 it's ok_

**Comment by Arkadipta-Chatterjee** [comment]
Can i work on this please?

**Comment by pedropintosilva** [comment]
unfortunately this seems a bit more complex than what I originally thought https://github.com/CollaboraOnline/online/pull/2974

**Comment by Darshan-upadhyay1110** [comment]
It's fixed in latest version.

COOLWSD version: 24.04.5.2
(git hash: 
df56d78c)
LOKit version: Collabora OfficeDev 24.04.5.2
(git hash: 
b57fd97)
Served by: Ubuntu 23.10
Server ID: 0dc2679d
