### ISSUE TITLE
Sidebar should be under toolbar-down

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2814]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @pedropintosilva 

branch: master

![image](https://user-images.githubusercontent.com/65948705/124918401-473b9200-dff5-11eb-834d-d77a5012d220.png)

**Comment by Arkadipta-Chatterjee** [comment]
Can i work on this please??

**Comment by pedropintosilva** [comment]
ah it seems that someone already fixed that (maybe even me :thinking: ) sorry
