### ISSUE TITLE
Tablet: toggleMenubar has wrong icon

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#2816]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @pedropintosilva 

1. Use tablet or test it with F12 -> device -> tablet
2. The icon of the farthest right (hamburger) works as a toggle to hide/show the top menubar (File, Edit, etc..)

![image](https://user-images.githubusercontent.com/65948705/124927119-8fab7d80-dffe-11eb-8111-0e17c2b8a7f1.png)

Use the same icon as in the desktop:
 `.w2ui-icon.fold` (`background: url('images/fold.svg') no-repeat center center / 19px !important`) visible in `toolbar.css`

**Comment by ViAsmit** [comment]
I would like to work on this issue. May I know which folder should I look for the source code of this page.

**Comment by Arkadipta-Chatterjee** [comment]
Can i work on this issue?

**Comment by kendy** [comment]
@pedropintosilva: Is this actually fixed by that commit?

**Comment by shrikanta8** [comment]
@pedropintosilva is this issue being assigned to someone?

**Comment by pedropintosilva** [comment]
@shrikanta8 : Are you still working or intend to work on this?

**Comment by Ayushbajpai19** [comment]
I would like to take this issue for hacktoberfest

**Comment by callmetushar123** [comment]
@pedropintosilva Hello since no one is working on it please assign it to me. I will fix it :D

**Comment by pedropintosilva** [comment]
Fixed with https://github.com/callmetushar123/online/commit/f762ee0904b0efafd693454e7f7cf8169b9f04f2, thanks! :partying_face:

**Comment by callmetushar123** [comment]
@pedropintosilva i wanted to work on some medium level issue. Can you please be my mentor?
