### ISSUE TITLE
ERR  Session::handleInput: Exception after upgrade

### ISSUE THREAD

**Issue by rheman** [CollaboraOnline/online#2829]
**Describe the bug**
I just upgraded to the latest release(collaboraonline CODE)
- loolwsd 6.4.10-3
- code-brand 6.4-19

Before the upgrade, everything was functional. But after upgrade, when the user save the changes made to a file, the following error is generated in loolwsd.log and the changes are not saved.

`**ERR  Session::handleInput: Exception while handling [dialogevent busypopup {"id":"__POPOVER__", "cmd": "close", "data": "null", "type": "popover"}]: stoull| common/Session.cpp:275**`

**To Reproduce**
So I made a fresh installation of collaboraonline code. But I have the same behavior. Users cannot save changes to files and the same error is generated in the log file.

`**ERR  Session::handleInput: Exception while handling [dialogevent busypopup {"id":"__POPOVER__", "cmd": "close", "data": "null", "type": "popover"}]: stoull| common/Session.cpp:275**`

**Desktop (please complete the following information)**
 - OS: Ubuntu server 20.04
 - Browser: Chrome, Firefox, Edge and Opera

Could someone help me ?

Regards,

**Comment by stardust342** [comment]
I have the same issue. Downgrading to 6.4.9.3 solved the issue, but I am now getting this warning (as expected):
[ websrv_poll ] WRN  client - server version mismatch, disabling browser cache. Expected: 0b3211b| wsd/FileServer.cpp:285

**Comment by rheman** [comment]
Hi @stardust342 thanks a lot for your answer.

Please could you help me ? How can I downgrade to 6.4.9.3.

Regards,

**Comment by stardust342** [comment]
I'm using docker so I just used the 6.4.9.3 tag. If you're using a Ubuntu package, try following this guide https://linoxide.com/install-specific-version-package-apt-get/

**Comment by rheman** [comment]
Thanks @stardust342.
unfortunately, I am using the provided packages for linux, and the only version available from apt-cache is the latest release (6.4.10-3).

**Comment by stardust342** [comment]
Looks like you might have to wait for a fix or switch to Docker, unfortunately.

**Comment by thebearon** [comment]
Strange, I didn't encounter that during save when using the 6.4.10-3 packages.

**Comment by rheman** [comment]
I don't know how to face it.

**Comment by stardust342** [comment]
I did some further testing and can confirm 6.4.9-3 is the last working version. 6.4.10-1, 6.4.10-2, & 6.4.10-3 do not work.

**Comment by stavros-k** [comment]
> I did some further testing and can confirm 6.4.9-3 is the last working version. 6.4.10-1, 6.4.10-2, & 6.4.10-3 do not work.

That is correct, but apparently Collabora claims that manually tested it and it is more stable and fast, which is either a joke, or a change is needed for the setup, but there is nowhere documented.

https://forum.collaboraonline.com/t/collabora-online-weekly-meeting-32/450

**Comment by thebearon** [comment]
This should be fixed now, please check again with CODE 6.4.10-6.

**Comment by rheman** [comment]
It works now. Thanks a lot
