### ISSUE TITLE
text area does not use complete width of the screen

### ISSUE THREAD

**Issue by ferdiga** [CollaboraOnline/online#2834]
**Describe the bug**
right of the text window remains empty space - probably the size of the sidebar or discussion 

**To Reproduce**
1. create a landscape doc document in google docs 
2. add a comment
2. export it as docx and save it into a nextcloud folder
3. open the doc in nextcloud browser (chrome)
4. there is a unused space on the right side between the text area and the comment
Even after deleting the comment the empty area remains
[20210711 test doc (1).docx](https://github.com/CollaboraOnline/online/files/6797081/20210711.test.doc.1.docx)

After editing the file in nextcloud/collabora code server the empty space disappears

**Expected behavior**
use the "empty" space
<img width="716" alt="20210711 162904 20210711 test doc (1) docx - Files - Storage Share" src="https://user-images.githubusercontent.com/6248560/125199169-33966280-e265-11eb-95c1-41b65919b5c2.png">

**Actual behavior**
cuts off part of the text box

**Screenshots**

**Desktop (please complete the following information)**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information)**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by ferdiga** [comment]
Additional information
it mostly happens if the document is opened via a shared link

**Comment by Ezinnem** [comment]
The behaviour is not reproducible in LOOLWSD 6.4.10 snapshot (git hash: 788e0aa).

@ferdiga, please can you share more details of the device and version of the CODE where you encountered this behaviour?

**Comment by ferdiga** [comment]
works with last docker
image id 09795926aafc

**Comment by Ezinnem** [comment]
Great.
