### ISSUE TITLE
CODE 6.4.10 In Calc the Text Box button on the Insert tab switches back to the Home tab ...and breaks other things

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#2857]
In in CODE Calc the Insert > Text Box button switches back to the Home tab. Should it show the text box as other apps do?

Using the Text Box button leaves Symbol button in a strange state:
**Issue:** After using the Insert > Text Box button, then changing back to the Insert tab again the Symbol button does not work. 
**Reproduce:** click on a cell, click Insert > Symbol button to verify symbol pop-up appears, click Text Box button, click back on Insert > Symbol button, the pop-up does not work. 
**Fix:** Click Home tab, then Insert > Symbol button works again.

Same symptoms in on iPadOS device running Collabora Office 6.4.8 app.

CODE 6.4.10 Help About says: LOOLWSD 6.4.10snapshot (git hash: ac1a7de)* Served by: 2e2ccc07
LOKit Collabora Office 6.4-44 (git hash: 4151286) "Ubuntu 18.04.5 LTS"
*ac1a7de is 404 page not found. It was released about 13 July 2021.

**Comment by Ezinnem** [comment]
The behaviour is not reproducible on my end using CODE 6.4.10snapshot (git hash:[ 788e0aa](https://github.com/CollaboraOnline/online/commits/788e0aa)).

@rpear, please can you share a screen recording showing the behaviour?

**Comment by rpear** [comment]
@Ezinnem Hi, I checked it again, it still changes to the Home tab from the Insert tab when Text Box is clicked; However the other adverse behaviour afterwards no longer occurs.
https://user-images.githubusercontent.com/80790599/126467058-c9459d7c-3ee6-4573-aa94-ee988f4c2897.mp4

**Comment by Ezinnem** [comment]
@rpear, Thanks for sharing the screen recording.

I can confirm that Clicking on Textbox takes the user back to the Home Tab but it does not break anything else.

**Comment by rpear** [comment]
I can again reproduce clicking on Textbox takes the user back to the Home Tab AND breaks things.  See video below.  These are the steps I took on a Chromebook accessing CODE 6.4.10 snapshot (git hash: 25b2adb) Commits on Jul 20, 2021.

Click Insert > Text Box
 Odd behaviour:  It didn’t show the Text box and…
 Odd behaviour:  It jumped back to the Home tab
Don’t click anything else, just click back on the Insert tab
 Odd behaviour:  the Comment box button is greyed out and …
 Odd behaviour:  the  buttons Define and Manage do nothing
Click on any cell
 Odd behaviour:  It jumped back to the Home tab
Click Insert tab
 Comments is no longer greyed and works
 The  buttons Define and Manage now work again

https://user-images.githubusercontent.com/80790599/126924776-9395fe64-3afa-4a2f-87c1-8aa4d752a741.mp4

**Comment by Ezinnem** [comment]
This issue has been fixed and it is no longer reproducible on the COOLWSD version: 6.4.22 git hash: [ae3a57c0]( https://github.com/CollaboraOnline/online/commits/ae3a57c0)

**Comment by rpear** [comment]
I have tested this once again and it is working. 
Tested OK on CODE 22.05.10.1.
Tested OK on Chromebook app 21.11.6.1 git hash:  6706dd45.
So Closed this issue
