### ISSUE TITLE
CODE 6.4.10 Insert Image... wheel spins forever when there is no access to storage

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#2859]
When I am editing a file that has been shared with me, clicking "Insert Image..." displays a pop-up titled 'Insert from Nextcloud' with a spinning wheel, the wheel spins forever and does not display files or time out. Clicking X at the top-right closes the screen. This occurs in all apps.

Expectation: To be quickly alerted with a relevant message, possibly also with a button 'Try Inserting a Local Image instead'.  Or the option to be greyed out.

Opinion: This shouldn't prevent anyone from working, but 1) People might expect to be able to install from the web or somewhere. 2) Spinning wheels forever is not good.

CODE 6.4.10 Help About says: LOOLWSD 6.4.10snapshot (git hash: ac1a7de)* Served by: 2e2ccc07
LOKit Collabora Office 6.4-44 (git hash: 4151286) "Ubuntu 18.04.5 LTS"
*ac1a7de is 404 page not found. It was released about 13 July 2021.

**Comment by Ezinnem** [comment]
I can reproduce this behaviour in LOOLWSD 6.4.10 (git hash: [d12ab86](https://github.com/CollaboraOnline/online/commits/d12ab86)).

**Comment by rpear** [comment]
Tested in Collabora Online 23.05.6.4,  in a file that has been shared with me, I clicked "Insert > Image" it now shows me a file selection dialogue that allows me to insert an image, works great.
