### ISSUE TITLE
CODE 6.4.10 Impress toolbars do not always load in certain situations

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#2860]
**Describe the bug**
I frequently open documents of all 4 types in CODE, they have always opened reliably.  Recently I started opening these documents is quick succession, about a second apart, and now occasionally part or parts of the toolbar do not appear in Impress. To the best of my knowledge all 4 documents are on the same CODE server.

1. More often missing the row of text (File Home Insert...).
2. Rarely two rows are missing.  (File Home Insert...  and  Paste Cut Copy...)
3. I think.... once it was missing just the row of buttons (Paste Cut Copy...), but can't reproduce this.

Refreshing the browser always fixes this.

**To Reproduce**
To easily reproduce I added these 4 documents (Writer, Impress, Calc, Draw) to a Chrome Bookmark folder and then opened them in one click using the browsers "Open all" feature.

If I change the order in the Bookmark folder so that Impress is 2nd 3rd or 4th > frequently the Impress toolbars don't all appear;  However if I change the order in this Bookmark folder to (Impress, Writer, Calc, Draw) > all the toolbars always appear in all apps.

Opinions:   Could this be a multi-user related thing?   Could this be a problem compounded by the fact that my CODE server is in the UK, and my browser is in AU?  I am not worried by this at all, so not to worry if not repeatable or too rare.

![Screenshot 2021-07-14 3 21 28 PM](https://user-images.githubusercontent.com/80790599/125567296-c6637838-c0d2-436b-bb0a-3e281deb6a10.png)

![Screenshot 2021-07-14 3 23 54 PM](https://user-images.githubusercontent.com/80790599/125567352-585b27c8-0cdb-4403-9676-f99278358760.png)

Help About says: LOOLWSD 6.4.10snapshot (git hash: ac1a7de)* Served by: 2e2ccc07
LOKit Collabora Office 6.4-44 (git hash: 4151286) "Ubuntu 18.04.5 LTS"
*ac1a7de is 404 page not found. It was released about 13 July 2021.

**Comment by Ezinnem** [comment]
The behaviour is not reproducible on my end using 6.4.10snapshot (git hash: [788e0aa](https://github.com/CollaboraOnline/online/commits/788e0aa)).

@rpear, Please, can you share a screen recording showing the issue you described?

**Comment by rpear** [comment]
@Ezinnem I can't reproduce this now. I don't know why. All that has changed is that my device has been restarted and it is a newer version of CODE. 
Chromebook Version 91.0.4472.147 (Official Build) (32-bit), CODE: LOOLWSD 6.4.10snapshot (git hash: 25b2adb) Served by: 557df1a3 LOKit Collabora Office 6.4-44 (git hash: eb38177) "Ubuntu 18.04.5 LTS"

**Comment by Ezinnem** [comment]
Alright.

This issue can be closed since it is no longer reproducible.
