### ISSUE TITLE
This is not a LibreOffice core build directory

### ISSUE THREAD

**Issue by Namdh1212** [CollaboraOnline/online#2950]
having problems This is not a LibreOffice core build directory i want to ask about --with-lo-builddir where is this path?

**Comment by Rash419** [comment]
what are you trying to do?

**Comment by thebearon** [comment]
Are you properly following the steps on building CODE?
Ie. here: https://collaboraonline.github.io/post/build-code/

**Comment by Namdh1212** [comment]
> what problem is the problem ? what are you trying to do? Can you describe ?

I'm following the build instructions on android:
https://collaboraonline.github.io/post/build-code-android/
Go to step: Configure the online.git
Then there is an error: This is not a LibreOffice core build directory

**Comment by thebearon** [comment]
What is your `--with-lo-builddir` parameter?

**Comment by Namdh1212** [comment]
> What is your `--with-lo-builddir` parameter?

Thank you for responding
I cloned LibreOffice at: https://github.com/LibreOffice/core
--with-lo-builddir = cloned LibreOffice dir

**Comment by thebearon** [comment]
And have you built LibreOffice first?

**Comment by Namdh1212** [comment]
> And have you built LibreOffice first?

follow the docs i have Create a file called autogen.input
Then run ./autogen.sh && make

**Comment by canoeCat** [comment]
> > And have you built LibreOffice first?
> 
> follow the docs i have Create a file called autogen.input
> Then run ./autogen.sh && make
Hello, can you tell me whether your LibreOffice core is successfully compiled?  
![clipboard](https://user-images.githubusercontent.com/75819117/128669977-0309f89e-9eac-4150-a286-e5376a26c97e.png)

I encountered this error during compilation. My  autogen.input configuration is:
`--build=x86_64-unknown-linux-gnu
--with-jdk-home=/usr/lib/jvm/java-11-openjdk-amd64
--with-android-ndk=/home/$USER/Android/Sdk/ndk-bundle
--with-android-sdk=/home/$USER/Android/Sdk
--with-distro=CPAndroid
--enable-sal-log`

**Comment by Ezinnem** [comment]
@Namdh1212, you can checkout to the `distro/collabora/cp-6.4` branch in the LibreOffice repo and compile from the branch.

That should help.

However, if it fails, you can give us a more detailed build output.
