### ISSUE TITLE
Regression CODE 6.4.10 (fcb0905) Calc: Context Menu Not Available on Cells With Cell Comments

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#2960]
**Describe the bug**
If you right click a cell, a popup menu opens. This does not happen if the cell has a cell comment - no popup menu is available in this case at all.

**To Reproduce**
1. Open a new Calc spreadsheet
2. Add a comment to a cell
3. Right click the cell.

**Expected behavior**
The cell popup menu opens.

**Actual behavior**
Nothing happens.

**Desktop (please complete the following information)**
Chromium
Version 91.0.4472.101 (Offizieller Build) Built on Ubuntu , running on neon 20.04 (64-Bit)

**Additional context**
LOOLWSD
6.4.10 (git hash: fcb0905)
Angeboten von: 57f5f1cf
LOKit
Collabora Office 6.4-45 (git hash: a21347f)
"Ubuntu 18.04.5 LTS"

**Comment by rpear** [comment]
I see the same on a Chromebook accessing CODE on 6.4.10snapshot (git hash: 25b2adb) Commits on Jul 20, 2021 Served by: 557df1a3

**Comment by pedropintosilva** [comment]
Thanks everyone for reporting and @Rash419 for fixing it :+1:
