### ISSUE TITLE
Regression CODE 6.4.10 (fcb0905) Calc: CODE Freezes After Being in Background For a While

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#2961]
**Describe the bug**
After being in background for quite a while, the CODE view will be frozen and will not recover. The page has to be reloaded manually and the file has to be reopened.

**To Reproduce**
1. Open a CODE Calc sheet in a browser tab.
2. Switch to another browswer tab.
3.  Work there for a (long) while.
4.  Go back to the tab showing the CODE Calc spreadsheet.

**Expected behavior**
The Calc sheet is still editable (and maybe needs a second to refresh if the session timed out and needs to be refreshed). It worked like this until CODE 6.4.9.

**Actual behavior**
The CODE Calc view is frozen and not usable. It does not recover, the tab has to be reloaded / closed & reopened.

**Desktop (please complete the following information)**
Chromium
Version 91.0.4472.101 (Offizieller Build) Built on Ubuntu , running on neon 20.04 (64-Bit)

**Additional context**
LOOLWSD
6.4.10 (git hash: fcb0905)
Angeboten von: 57f5f1cf
LOKit
Collabora Office 6.4-45 (git hash: a21347f)
"Ubuntu 18.04.5 LTS"

**Comment by thebearon** [comment]
Can you please give this a try after 6.4.10-6 update? The likely relevant timing here is the session idle timeout, which is the timeout for closing a session after inactivity. It is one hour by default, and can be controlled by the following setting in `/etc/loolwsd/loolwsd.xml`:
`<per_document>` / `<idle_timeout_secs>` (eg. set default from `3600` to a shorter period, like `60`).

**Comment by gohrner** [comment]
The problems might be related to #3015, so no actual permanent freeze, but "just" half an hour waiting time before anything happens...

I'll continue to monitor this.

**Comment by Ezinnem** [comment]
This issue may have been fixed.

@gohrner, please does this issue still occurs at your end?

**Comment by gohrner** [comment]
@Ezinnem: CODE now does recover, but it's still frozen for quite a while (10 - 15 seconds maybe?) after reactivation.

Interestingly, scrolling is already possible during that time, just the cursor / cell selection rectangle is not available.

After quite a bit of waiting, CODE recovers and the sheet can be edited again.

**Comment by gohrner** [comment]
Doesn't seem to happen any more - will report a new issue if I notice it again.
