### ISSUE TITLE
Whilst adding a comment saves itself after a 2 – 3 second pause

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#2963]
Usually after first opening Calc, when adding a new Comment it saves itself after a 2 – 3 second pause.

To reproduce click add Comment, maybe type some chr/s after a few seconds it Save itself.  If you don't type it Cancels.   Not always, closing the Calc browser tab and reopening it again and it repeats.
This was on a Chromebook accessing CODE on 6.4.10snapshot (git hash: 25b2adb) Commits on Jul 20, 2021 Served by: 557df1a3
See video:  https://user-images.githubusercontent.com/80790599/127123366-62d40e62-e77e-4ed6-a5d9-51e83383c1e5.mp4

**Comment by Ezinnem** [comment]
I can confirm this behavior occurs in 6.4.10 (git hash: [534b088e](https://github.com/CollaboraOnline/online/commits/534b088e)).

A very similar issue is #757. 

I believe a regression may have occurred.
@eszkadev, @gokaysatir, Please would you like to take a look?

**Comment by Ezinnem** [comment]
The behaviour has been fixed on #3020.
