### ISSUE TITLE
Calc: Keyboard is not focused on pop-up for Insert > Define, Manage or Comment

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#2965]
Insert > Define or Manage  
Odd behaviour: Esc key will not close pop-up, need to click on their pop-up, then Esc works.

Insert > Comment
Odd behaviour: Esc key will not close pop-up, need to click anywhere on the pop-up except the data entry area, then Esc works.

Also I would expect the highlighting of the Cancel and Save buttons to display differently too.  Insert > Symbol is a good example which closes with the Esc key, mouse clicking or by touching Cancel.

This was on a Chromebook accessing CODE on 6.4.10snapshot (git hash: 25b2adb) Commits on Jul 20, 2021 Served by: 557df1a3

**Comment by Ezinnem** [comment]
@pedropintosilva, please can you take a look at the button display suggestions?

**Comment by pedropintosilva** [comment]
> Insert > Comment
> Odd behaviour: Esc key will not close pop-up, need to click anywhere on the pop-up except the data entry area, then Esc works.

I have tested and I think this has been fixed, could you please confirm?

**Comment by pedropintosilva** [comment]
> Insert > Define or Manage Odd behaviour: Esc key will not close pop-up, need to click on their pop-up, then Esc works.

- I have tested and I think ` Data > Name Ranges and Expressions > Insert... ` has been fixed (escape key correctly closes the modal window) but
- ` Data > Name Ranges and Expressions > Manage... ` still suffers from this issue (pressin `esc` key does nothing)
