### ISSUE TITLE
Calc: Home > Conditional button not behaving as expected.

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#2967]
Hamburger > Tools > Conditional is the same as Format > Conditional. Is Home > Conditional supposed to display the same pop-up?  It displays a dropdown of Arrows, smiley faces etc but they don't appear to do anything.

This was on a Chromebook accessing CODE on 6.4.10snapshot (git hash: 25b2adb) Commits on Jul 20, 2021 Served by: 557df1a3

**Comment by Ezinnem** [comment]
In Calc,  when the user selects a row and applies Conditional using Home > Conditional; the colors are applied on the cells based on the range of values, whether they're in the top 1/3, mid 1/3, or bottom 1/3 based on how many icons are in the icon set.
