### ISSUE TITLE
CODE 6.4.10 Calc: Cell In Edit Mode While Adding New Sheet Writes Text to Wrong Sheet

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#2975]
**Describe the bug**
If a Calc cell is in edit mode while adding a new sheet, the cell's contents will be copied to the new sheet instead of the sheet the cell belongs to...

**To Reproduce**
1. Edit cell and leave it focused with cursor
2. Click "+" below the sheet to add a new sheet

**Expected behavior**
The new sheet is empty and the edited cell contents can be found in the original cell in the old sheet.

**Actual behavior**
The new sheet contains the edited cell contents in one cell, and the original sheet is unmodified.

**Desktop (please complete the following information)**
Chromium
Version 91.0.4472.101 (Offizieller Build) Built on Ubuntu , running on neon 20.04 (64-Bit)

**Additional context**
LOOLWSD
6.4.10 (git hash: fcb0905)
Angeboten von: 57f5f1cf
LOKit
Collabora Office 6.4-45 (git hash: a21347f)
"Ubuntu 18.04.5 LTS"

**Comment by thebearon** [comment]
This bug originates from LibreOffice core, and needs to be resolved there: https://bugs.documentfoundation.org/show_bug.cgi?id=119620

**Comment by Darshan-upadhyay1110** [comment]
Looks good in latest version.

COOLWSD version: 24.04.5.2 (git hash: df56d78c)
LOKit version: Collabora OfficeDev 24.04.5.2 (git hash: b57fd97)
Served by: Ubuntu 23.10
Server ID: 0dc2679d
