### ISSUE TITLE
Toolbar scroll arrows can disappear

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#2992]
**Describe the bug**
The toolbar scroll arrows can disappear, it is the same for all 4 apps.  These arrows appear when the window is narrower than the toolbar.

**To Reproduce**
1. Start CODE Calc (in this example)
2. Make sure on the Home tab (in Calc it is a wide toolbar)
3. Reduce the size of the browser window until "Conditional" is last on the right, the toolbar scroll arrow appears on the right. The left and right toolbar scroll arrows work perfectly.
4. Optionally click the Insert tab. The left and right toolbar scroll arrows still work perfectly.
5. Click the Layout tab. The toolbar scroll arrows will disappear if clicked as not needed as toolbar is narrower than the browser window. (In testing the following problem only arises if the arrow is clicked when here, I am not sure how I stumbled upon the problem)
6. Click either the Home or Insert tab. The toolbar scroll arrows no longer appear.

**To fix it**
No need to refresh the browser, just adjust the browsers width.
Video: https://user-images.githubusercontent.com/80790599/127442254-49e7280c-15cc-42ab-bcbf-d15c5d3a84fa.mp4

This was tested on a Chromebook accessing CODE (released about 28/7/2021) LOOLWSD 6.4.10snapshot (git hash: b4fa48ef which gives a 404) Served by: 73881885 LOKit  Collabora Office 6.4-45 (git hash: 38caa5c) "Ubuntu 18.04.5 LTS"

**Comment by Rash419** [comment]
Thanks for the report : )

**Comment by rpear** [comment]
Tested again in CODE 23.05.6.4 and it appears to work perfectly, so closing the ticket. Probably been fixed since July 2021  !
