### ISSUE TITLE
insert image does not work CODE 6.4.10

### ISSUE THREAD

**Issue by tobefrank1** [CollaboraOnline/online#2995]
**Describe the bug**
Try to insert an image with "insert image" does work.

This does not work with the docker image for nextcloud 21.0 and the build in online version. 
 
**To Reproduce**

Try to insert an image with "insert local image" does work!

1. Try to insert an image with "insert image" opens the dialog box of nextcloud.
2. Select a picture e.g  .jpg 2 Mb
3. Press Choose
4. dialog box closes, but nothing happens.

**Expected behavior**
Loading image

**Desktop (please complete the following information)**
- Nextcloud server 21.0.03 Ubuntu
 - OS: Windows
 - Browser:  Firefox/ Vivaldi 
 - 

**Smartphone (please complete the following information)**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by Ezinnem** [comment]
Inserting a picture using the Insert Image option works using LOOLWSD 6.4.10 (git hash: [d12ab86](https://github.com/CollaboraOnline/online/commits/d12ab86)).

@tobefrank1, please, can you share a screen recording showing what you encountered?
