### ISSUE TITLE
Lots of Disconnects and account duplication

### ISSUE THREAD

**Issue by mcenderdragon** [CollaboraOnline/online#3001]
**Describe the bug**
When you open a document you instantly get the message "connection to server lost" but it loads and works anyway. When you open a document and edit it and leave it open for a while you will see yourself several times. As sson as a copy of yourself "owns" this collum&row you can no longer edit it.

**To Reproduce**
1. Open a Excel table document
2. edit it a fww times
3. wait for a few hours 
4. change selected colum/row a few times
5. you will see your account name lots of time, I had it over 10 at one point

**Expected behavior**
When the same accoutn recconects instantly disconnect all previous account & also not disconnect at all.

**Actual behavior**
Disconnects and account name duokication

**Screenshots**
![grafik](https://user-images.githubusercontent.com/6342933/127560928-f68d85bb-503e-4421-bd38-d96c7eb9ce81.png)

 - OS: win 10
 - Browser: firefox
 - Version: 6.4.10 (git hash: 2afbc52)

**Additional context**
it gets worse when multiple people atre just viewing the same file.

**Comment by mcenderdragon** [comment]
Also while writing it discconects you and then reconnects you to a random cell int the first sheet. this removes all of your progress & overwrites whatever was there previously - that is super annoying.

**Comment by Ezinnem** [comment]
The issue is not reproducible using LOOLWSD 6.4.10 (git hash: [d12ab86](https://github.com/CollaboraOnline/online/commits/d12ab86)).

@mcenderdragon, please can you update and retest again?
