### ISSUE TITLE
Writer: There are 2 "Lists" buttons on the Format toolbar 

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#3002]
**Describe the bug**
There are 2 "Lists" buttons on Writers Format toolbar.
![Screenshot 2021-07-30 12 39 14 PM](https://user-images.githubusercontent.com/80790599/127591624-3e9224d6-c55e-4b92-be00-70aadaf8ea49.png)

**Version**
Chromebook accessing CODE 6.4.10snapshot (git hash: b4fa48ef)  this link gives a 404, there is a 404 on some releases, updated a couple of days ago around 6.4.10-6 release.

**Comment by thebearon** [comment]
Indeed, #2847 is a PR to fix this. Thanks!

**Comment by kendy** [comment]
@rpear - thanks for the find, and @thebearon, thanks for the fix! :-)
