### ISSUE TITLE
Writer File > Share should not be available if cannot be used

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#3003]
**Describe the bug**
I am accessing a Writer document that has been shared with me via a URL, if I click File > Share nothing happens.

**Expected behaviour**
A pop-up allowing me to share or The button to be greyed out or a pop-up explaining that document sharer 'x' has not given me permission to on-share or whatever the reason actually is.

**Opinion**
Maybe the mechanisms used for determining the appropriate feedback will be useful to the "Insert Image wheel spins forever" https://github.com/CollaboraOnline/online/issues/2859

**Version**
Chromebook accessing CODE 6.4.10snapshot (git hash: b4fa48ef) this link gives a 404, there is a 404 on some releases, updated a couple of days ago around 6.4.10-6 release.

**Comment by Ezinnem** [comment]
The behavior of the Share button is as expected.

When the file is shared with a user through the URL, then that user should not be able to use the Share button.
Only the owner should be able to generate a share URL for the document.

**Comment by rpear** [comment]
I had a quick look for other toolbar buttons that provide feedback:  Review > Comment and Review > Delete Comment toggle between normal and greyed depending on whether the button is relevant or not.  When looking it did highlight that other buttons do not.
Opinion: I think this is a minor UI improvement and consistency throughout the toolbars could be looked at.

**Comment by rpear** [comment]
Tested in CODE 23.05.6.4, in a file that was shared with me,  Share is no  longer an option under File. So this issue appears to have been resolved. Closing.
