### ISSUE TITLE
Mouse click Bold button when no highlighted text, keyboard focus is lost and button has no effect.

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#3004]
**Describe the bug**
Without having any text highlighted, if you use the mouse to change to Bold the toolbar indicates this action, but you can‘t carry on typing as the keyboard focus is lost, if you mouse-click back to where you were typing the B button remains highlighted but un-highlights when typing resumes and the typed text is not bold. It is the same for Italics, Underline, Strikethrough, Subscript, Superscript, Increase Size and Decrease Size.

**Expected behaviour**
1. click B and carry on typing in Bold.
2. If you press Ctrl+B etc whilst typing it behaves as expected.
3. If you highlight the text then click B button it behaves as expected.
4. LibreOffice running on Crostini behaves as expected.
5. CODE 6.4.2 misbehaves in a similar way too, with the exception that the B button un-highlights when you mouse-click back to the screen, not when you start typing.

**Opinion**
1. If you change the Font using the mouse the behaviour is as expected, I mention this only because it may be useful to help identify where things are going wrong.
2. In case it is useful: there are other areas of the interface that misbehave with keyboard focus such as https://github.com/CollaboraOnline/online/issues/2965

**Version**
This occurred in Writer, a quick test showed the same in Calc, I didn't test Impress or Draw.
Chromebook accessing CODE 6.4.10snapshot (git hash: b4fa48ef) this link gives a 404, there is a 404 on some releases, updated a couple of days ago around 6.4.10-6 release.

**Other similar toolbar issues where keyboard focus is lost**
Are these worth another ticket? Formatting Marks, Line Spacing, Background colour.  And many others on other toolbars.

**Comment by Ezinnem** [comment]
I can confirm this behavior 6.4.10snapshot (git hash: b4fa48ef).

**Comment by Ezinnem** [comment]
The fix for this issue has been made on https://github.com/CollaboraOnline/online/pull/3196
