### ISSUE TITLE
Build CODE for Android error: used LinkTarget Library/libclucene.a not defined。

### ISSUE THREAD

**Issue by canoeCat** [CollaboraOnline/online#3044]
Hello! I compiled android from this article:https://collaboraonline.github.io/post/build-code-android/
But I'm getting an error while compiling the LibreOffice core
![clipboard](https://user-images.githubusercontent.com/75819117/128660465-4b1e19ad-4db2-4c73-b93e-923863e8a340.png)
My  autogen.input configuration is as follows:
`--build=x86_64-unknown-linux-gnu
--with-jdk-home=/usr/lib/jvm/java-11-openjdk-amd64
--with-android-ndk=/home/$USER/Android/Sdk/ndk-bundle
--with-android-sdk=/home/$USER/Android/Sdk
--with-distro=CPAndroid
--enable-sal-log`
My operating system version： Ubuntu 18.04.3 LTS
Please tell me what to do,Thanks!

**Comment by thebearon** [comment]
As I could read on the forums, your build has succeeded, therefore let me close this.

**Comment by linhnv106** [comment]
@canoeCat are you able to fix this issue, I'm facing this one too
