### ISSUE TITLE
Calc: 100% CPU spin ...

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#3091]
Sometimes (unknown reproduction steps) - calc can get stuck in an fast spinning loop whereby it consumes endless CPU until killed. Trace 
[perf.txt.gz](https://github.com/CollaboraOnline/online/files/7002153/perf.txt.gz)

    98.53%     3.98%  kitbroker_6e65  libc-2.17.so       
            |          
            |--92.22%--__libc_start_main
            |          main
            |          forkLibreOfficeKit
            |          0x539e7b
            |          lokit_main
            |          lo_runLoop
            |          soffice_main
            |          ImplSVMain
            |          desktop::Desktop::Main
            |          Application::Execute
            |          ImplYield
            |          SvpSalInstance::DoYield
            |          KitSocketPoll::kitPoll
            |          Document::drainQueue
            |          Document::forwardToChild
            |          Session::handleMessage
            |          ChildSession::_handleInput
            |          ChildSession::unoCommand
            |          doc_postUnoCommand
            |          comphelper::dispatchCommand
            |          comphelper::dispatchCommand
            |          SfxDispatchController_Impl::dispatch
            |          SfxDispatcher::Execute
            |          SfxDispatcher::Execute_
            |          SfxDispatcher::Call_Impl
            |          ScTabViewShell::ExecuteSave  *** hmm? ***
            |          ScInputHandler::EnterHandler
            |          ScValidationData::DoError
            |          SalInstanceDialog::run
            |          Dialog::Execute        ********** here is our problem - but why 100% CPU **********
            |          |          
            |          |--91.59%--ImplYield

This spins infinitely - at very high speed and burns great chunks of CPU. Not entirely clear why.

Dennis - if I can't see what's up here in the next hour or two would be good to have this on your queue =)

**Comment by mmeeks** [comment]
I would expect this to be fixed by core commit cda7357a82b3be7b60cc314cecbc59922beda629
Author: Noel Grandin <noelgrandin@gmail.com>
Date:   Sat Mar 13 09:36:46 2021 +0200

    check for quit when calling Yield in loop

    so we don't get stuck threads when the main application
    quits

    // Yield util EndDialog is called or dialog gets destroyed
    // (the latter should not happen, but better safe than sorry
    while ( !xWindow->IsDisposed() && mbInExecute && !Application::IsQuit() )
        Application::Yield();

Then again - it is really unfortunate to have this happening during save:

sc/source/ui/view/tabvwsha.cxx:void ScTabViewShell::ExecuteSave( SfxRequest& rReq )

We should (I guess) ignore and/or not commit data that is not valid in this case somehow cleanly; hmm ...

**Comment by jmdeboer-surfsara** [comment]
Per @mmeeks request, the exact version:

![about](https://user-images.githubusercontent.com/23337494/129857094-b0c8f1f8-2af9-4404-bd03-ce8f600a70b3.png)

**Comment by timur-g** [comment]
Unknown stepsl old issue, possible fix, I think this could be closed.
