### ISSUE TITLE
Calc 6.4.10-9, 6.4.10-10 UI rendering, first 3 lines of spreadsheet overlapped by top toolbar

### ISSUE THREAD

**Issue by ryba84** [CollaboraOnline/online#3092]
**Describe the bug**

In Calc bottom bar have sheet switch button in wrong place. Because of this document area is shifted 3 lines behind toolbar. The same behavior is with classic ui and notebookbar ui.

**Screenshots**
![calc](https://user-images.githubusercontent.com/1330628/129876184-b5d46d9e-d1e4-4787-8744-915639246cc3.png)

**Desktop (please complete the following information)**
 - OS: Windows 10
 - Browser: Firefox, Microsoft Edge

In Android browser there is no problem.

**Comment by thebearon** [comment]
Which CODE version is this?

**Comment by ryba84** [comment]
Current on picture 6.4.10-10, but on 6.4.10-9 there was the same.

**Comment by thebearon** [comment]
Can you share your resolution, and whether you have display scaling set?

**Comment by ryba84** [comment]
Sorry for late response, but I've no time.
After trying several different versions, all newer then 6.4.9-4 had this problem.
Problem was not in CODE but in browser. Clearing Firefox cache resolved problem.
