### ISSUE TITLE
Add missing lc_checkboxoff icon

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#3111]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @Andreas-Kainz @rizmut 

### Detailed description and rationale
Refrain from trying to style the checkbox (off state) and instead (has many advantages)
* Create another SVG icon for the unchecked status (off)

### Code pointers
Folder: loleaflet/images/
Where is the existing one: loleaflet/images/lc_checkbox.svg

**Comment by cgrandworks** [comment]
I prepared two examples: 
[lc_checkboxoff.zip](https://github.com/CollaboraOnline/online/files/7033923/lc_checkboxoff.zip)
What do you think :)

**Comment by rizmut** [comment]
> I prepared two examples:
> [lc_checkboxoff.zip](https://github.com/CollaboraOnline/online/files/7033923/lc_checkboxoff.zip)
> What do you think :)

I am for lc_checkboxoff2.svg. The other one still reflects active state while in dark mode. Dark mode does not means negative value anyway.
