### ISSUE TITLE
Classic mode: Add back removed space between selectors and icons

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#3184]
**Describe the bug**
In the classic mode there is a new regression that effectively removed the essential space between dropdowns (selectors) and the following icons: 
* Clear direct formatting icon
* bold  icon

**To Reproduce**
1. Run it locally with ```make run```
2. Make sure you set the respective interface mode (only needed if you have changed before since it is the default): 
  * in your ```loolwsd.xml``` change the ```<user_interface>``` like so:
```xml
    <user_interface>
      <mode type="string" desc="Controls the user interface style (classic|notebookbar)" default="classic">classic</mode>
    </user_interface>
```
3. Notice the lack of space
4. Get acquainted with git commands and find where the regression comes from (from which commit)
5. Add back the removed spaces 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/65948705/132022537-5bed5847-f0a1-44cc-8bf1-3c9aaed747c2.png)

**Desktop (please complete the following information)**
 - branch: master

**Comment by pedropintosilva** [comment]
pointer:
```bash
git log --grep="toolbar.*.breaks" -i
```

**Comment by codewithvk** [comment]
@pedropintosilva can I take this issue?

**Comment by pedropintosilva** [comment]
@codewithvk yes ! :)

**Comment by pedropintosilva** [comment]
@codewithvk  : are you still working on this? If so please let me know and I will reassigned that to you :)

**Comment by Andreas-Kainz** [comment]
> pointer:
> 
> ```shell
> git log --grep="toolbar.*.breaks" -i
> ```

I see two PR's but both aren't related to .css changes.

**Comment by Andreas-Kainz** [comment]
I can add margin-left and margin-right of 2px but than the toolbar commands need way more space see

#### before
![image](https://user-images.githubusercontent.com/8517736/154795047-3634d574-ff7a-48cb-904f-23f22cf63ccb.png)

#### after
![image](https://user-images.githubusercontent.com/8517736/154795037-6aa8197e-5de6-4fa2-9d32-008e8bb216fb.png)

In the sidebar there is a `margin-right: 5px` setting

**Comment by pedropintosilva** [comment]
https://github.com/CollaboraOnline/online/pull/4438
