### ISSUE TITLE
CODE yields http ressources although using ssl.termination=true

### ISSUE THREAD

**Issue by nursoda** [CollaboraOnline/online#3186]
### Describe the bug
Due to resource URLs delivered with `http://` proto, I cannot use CODE without TLS in the backend (behind a terminating reverse-proxy).

#### Server setup

- Minimal setup on one single Arch Linux machine: NGINX, PHP-FPM, Nextcloud and CODE (as Docker collabora/code latest).
- HSTS Preload is activated for my domain.
- I access the document server via reverse-proxy using its cloud server domain:
  - Nextcloud: https://MYDOMAIN/apps/files etc
  - CODE: https://MYDOMAIN/lool/(.*)/ws etc.
- This setup works 100% fine as long as I stick to Docker image defaults concerning SSL and use "1. SSL on both ends" in the [proposed NGINX reverse proxy config](https://www.collaboraoffice.com/code/nginx-reverse-proxy/).

#### Collabora Configuration

- To minimize computation, I want to use "2. SSL terminates at the proxy" instead and changed my NGINX config accordingly.
- I stop and rm the CODE container and re-run it with `-e 'extra_params=--o:ssl.enable=false ssl.termination=true"'`.

### Expected behavior

- CODE should work just as it did using SSL on both ends. The assumption for that is `ssl.termination=true` does make sure that URLs in ressources are written as `https://` although the server itself runs without SSL. I deduct that from the comment within `/etc/loolwsd/loolwsd.xml` (from the container):

> Connection via proxy where loolwsd acts as working via https, but actually uses http

### Actual behavior

- Issuing `ps ax` I see the proper extra_params:
```
/usr/bin/loolwsd --version --o:sys_template_path=/opt/lool/systemplate --o:child_root_path=/opt/lool/child-roots --o:file_server_root_path=/usr/share/loolwsd --o:logging.color=false --o:user_interface.mode=notebookbar --o:ssl.enable=false ssl.termination=true
```
- I also get "OK" for `curl http://localhost:9980` within the container and on the host, and a green check mark within my Nextcloud page /settings/admin/richdocuments – so that part works as expected.
- But opening any document in Nextcloud yields a "white screen" (except for the Nextcloud menu bar) in Firefox and Chrome.

### Additional context / Possible cause

- The browser's JS console (here: Chrome) shows

> Mixed Content: The page at 'https://MYSERVER/apps/files/?dir=/&fileid=6' was loaded over HTTPS,
> but requested an insecure form action 'http://MYSERVER/loleaflet/…/loleaflet.html?
> WOPISrc=https%3A%2F%MYSERVER%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F…
> &title=test.odt&lang=de&closebutton=1&revisionhistory=1'.
> This request has been blocked; the content must be served over HTTPS.

- The cause seems to be, that /hosting/discovery yields `http://…`-URLs that due to the `ssl.termination=true` parameter really should be `https://…`-URLs like `http://MYSERVER/loleaflet/…`

<details>
<summary>Complete listing of https://MYSERVER/hosting/discovery</summary>
<wopi-discovery>
    <net-zone name="external-http">

        
        <app favIconUrl="http://MYSERVER/loleaflet/d12ab86/images/x-office-document.svg" name="writer">
            <action default="true" ext="sxw" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="odt" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="fodt" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            
            <action default="true" ext="stw" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="ott" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            
            <action default="true" ext="doc" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="dot" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            
            <action default="true" ext="docx" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="docm" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="dotx" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="dotm" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            
            <action default="true" ext="wpd" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="pdb" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="hwp" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="wps" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="wri" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="lrf" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="mw" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="rtf" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="txt" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="fb2" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="cwk" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="pages" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="abw" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="602" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        <app name="writer-global">
            
            <action default="true" ext="sxg" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="odm" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            
            <action default="true" ext="otm" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        <app name="writer-web">
            <action default="true" ext="oth" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app favIconUrl="http://MYSERVER/loleaflet/d12ab86/images/x-office-spreadsheet.svg" name="calc">
            <action default="true" ext="sxc" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="ods" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="fods" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            
            <action default="true" ext="stc" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="ots" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            
            <action default="true" ext="xls" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="xla" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            
            <action default="true" ext="xltx" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="xltm" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="xlsx" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="xlsb" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="xlsm" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            
            <action default="true" ext="dif" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="slk" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="csv" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="dbf" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="wk1" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="gnumeric" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="numbers" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app favIconUrl="http://MYSERVER/loleaflet/d12ab86/images/x-office-presentation.svg" name="impress">
            <action default="true" ext="sxi" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="odp" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="fodp" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            
            <action default="true" ext="sti" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="otp" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            
            <action default="true" ext="ppt" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="pot" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            
            <action default="true" ext="pptx" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="pptm" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="potx" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="potm" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="ppsx" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            
            <action default="true" ext="cgm" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="key" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app name="draw">
            <action default="true" ext="sxd" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="odg" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="fodg" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            
            <action default="true" ext="std" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="otg" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            
            <action ext="svg" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="dxf" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="emf" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="wmf" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="cdr" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="vsd" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="vsdx" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="vss" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="pub" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="p65" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="wpg" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action default="true" ext="fh" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action ext="bmp" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action ext="png" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action ext="gif" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action ext="tiff" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action ext="jpg" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action ext="jpeg" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
            <action ext="pdf" name="view_comment" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        

        

        <app name="image/svg+xml">
            <action ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.ms-powerpoint">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.ms-excel">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app name="application/vnd.sun.xml.writer">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.oasis.opendocument.text">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.oasis.opendocument.text-flat-xml">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app name="application/vnd.sun.xml.calc">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.oasis.opendocument.spreadsheet">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.oasis.opendocument.spreadsheet-flat-xml">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app name="application/vnd.sun.xml.impress">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.oasis.opendocument.presentation">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.oasis.opendocument.presentation-flat-xml">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app name="application/vnd.sun.xml.draw">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.oasis.opendocument.graphics">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.oasis.opendocument.graphics-flat-xml">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app name="application/vnd.oasis.opendocument.chart">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app name="application/vnd.sun.xml.writer.global">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.oasis.opendocument.text-master">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        
        
        <app name="application/vnd.sun.xml.writer.template">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.oasis.opendocument.text-template">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app name="application/vnd.oasis.opendocument.text-master-template">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app name="application/vnd.sun.xml.calc.template">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.oasis.opendocument.spreadsheet-template">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app name="application/vnd.sun.xml.impress.template">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.oasis.opendocument.presentation-template">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app name="application/vnd.sun.xml.draw.template">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.oasis.opendocument.graphics-template">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app name="application/msword">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/msword">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app name="application/vnd.ms-excel">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app name="application/vnd.ms-powerpoint">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app name="application/vnd.openxmlformats-officedocument.wordprocessingml.document">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.ms-word.document.macroEnabled.12">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.openxmlformats-officedocument.wordprocessingml.template">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.ms-word.template.macroEnabled.12">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app name="application/vnd.openxmlformats-officedocument.spreadsheetml.template">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.ms-excel.template.macroEnabled.12">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.ms-excel.sheet.binary.macroEnabled.12">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.ms-excel.sheet.macroEnabled.12">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app name="application/vnd.openxmlformats-officedocument.presentationml.presentation">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.ms-powerpoint.presentation.macroEnabled.12">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.openxmlformats-officedocument.presentationml.template">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.ms-powerpoint.template.macroEnabled.12">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        
        <app name="application/vnd.wordperfect">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/x-aportisdoc">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/x-hwp">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.ms-works">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/x-mswrite">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/x-dif-document">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="text/spreadsheet">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="text/csv">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/x-dbase">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.lotus-1-2-3">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="image/cgm">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="image/vnd.dxf">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="image/x-emf">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="image/x-wmf">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/coreldraw">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.visio2013">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.visio">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.ms-visio.drawing">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/x-mspublisher">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/x-sony-bbeb">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/x-gnumeric">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/macwriteii">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/x-iwork-numbers-sffnumbers">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.oasis.opendocument.text-web">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/x-pagemaker">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="text/rtf">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="text/plain">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/x-fictionbook+xml">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/clarisworks">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="image/x-wpg">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/x-iwork-pages-sffpages">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.openxmlformats-officedocument.presentationml.slideshow">
            <action default="true" ext="" name="edit" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/x-iwork-keynote-sffkey">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/x-abiword">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="image/x-freehand">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/vnd.sun.xml.chart">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/x-t602">
            <action default="true" ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="image/bmp">
            <action ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="image/png">
            <action ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="image/gif">
            <action ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="image/tiff">
            <action ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="image/jpg">
            <action ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="image/jpeg">
            <action ext="" name="view" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>
        <app name="application/pdf">
            <action ext="" name="view_comment" urlsrc="http://MYSERVER/loleaflet/d12ab86/loleaflet.html?"/>
        </app>

        

        <app name="Capabilities">
            <action ext="" name="getinfo" urlsrc="http://MYSERVER/hosting/capabilities"/>
        </app>
    </net-zone>
<proof-key exponent="…" modulus="…" oldexponent="…" oldmodulus="…" oldvalue="…" value="…"/></wopi-discovery>
</details>

- As far as I can see this is NOT Docker specific as the only thing the container does in that respect is to pass the extra_params to loolwsd.

**Comment by nursoda** [comment]
I found the solution myself as I re-read the [SSL configuration documentation](https://sdk.collaboraonline.com/docs/installation/Configuration.html#ssl-configuration) again. It would have been helpful to have an example there… So the solution is:

- wrong: `-e 'extra_params=--o:ssl.enable=false' -e 'extra_params=--o:ssl.termination=true"'`
- wrong: `-e 'extra_params=--o:ssl.enable=false ssl.termination=true"'`
- correct: `-e 'extra_params=--o:ssl.enable=false --o:ssl.termination=true"'`

In case anyone else stumbles upon this, I leave the description as it was.

**Comment by stevek-pro** [comment]
Would be great having someone proof-reading this and put into README. E.g., I spoted a coulple of extra `"`s, which are not necessary.

**Comment by mike-lloyd03** [comment]
I'm having this same problem and I have my environment  variables set up the same as yours. I've confirmed these are being passed to the web server with `ps`. But I still get the "mixed active content" error and Collabora fails to load. I might just set up TLS between code and Nextcloud just to get this working but that seems like a pain. Is there a quick way to do that?

ps aux output:
```
UID          PID    PPID  C STIME TTY          TIME CMD
cool           1       0  0 22:29 ?        00:00:05 /usr/bin/coolwsd --version --o:sys_template_path=/opt/cool/systemplate --o:child_root_path=/opt/cool/child-roots --o:file_server_root_path=/usr/share/coolwsd --o:logging.color=false --o:ssl.termination=true --o:ssl.enable=false
```

Relevant sections of docker compose file:
```
app:                                        
  image: nextcloud:22-apache                
  hostname: HOSTNAME               
  restart: unless-stopped                   
  ports:                                    
    - 8082:80                               
  volumes:                                  
    - /etc/localtime:/etc/localtime:ro      
    - /mnt/data/nextcloud/data:/var/www/html
  environment:                              
    - POSTGRES_HOST=db                      
    - REDIS_HOST=redis                      
  env_file:                                 
    - .env                                  
  depends_on:                               
    - db                                    
    - redis                                 
  networks:                                 
    - proxy-tier                            
    - default                               
    - code                                  

code:                                                             
  image: collabora/code:21.11.1.4.1                               
  restart: unless-stopped                                         
  networks:                                                       
    - default                                                     
    - code                                                        
  env_file:                                                       
    - .env                                                        
  ports:                                                          
    - 9980:9980                                                   
  volumes:                                                        
    - /etc/localtime:/etc/localtime:ro                            
  depends_on:                                                     
    - app                                                         
  cap_add:                                                        
    - MKNOD                                                       
  environment:                                                    
    - "extra_params=--o:ssl.termination=true --o:ssl.enable=false"
```

**Comment by stevek-pro** [comment]
I came to the same conclusion and left to another project. The kind of error handling of the setup told me to run.
