### ISSUE TITLE
Docker image for version 6.4.11 is missing from Docker Hub

### ISSUE THREAD

**Issue by mhow2** [CollaboraOnline/online#3188]
Docker image for version 6.4.11 is missing from [Docker Hub](https://hub.docker.com/r/collabora/code/tags?page=1&ordering=last_updated)

**Comment by Ezinnem** [comment]
@mhow2, the CODE version 6.4.11 is yet to be released.

**Comment by mhow2** [comment]
oh sorry... what's about https://github.com/CollaboraOnline/online/releases/tag/cp-6.4.11-1 then ?

**Comment by mhow2** [comment]
Let's wait for the release then...
