### ISSUE TITLE
Unresponsive UI on both opening .odt and creation of new document

### ISSUE THREAD

**Issue by eobet** [CollaboraOnline/online#3207]
**Describe the bug**
On both an iPhone 6 and a 2020 iPad Pro, CollaboraOffice is unresponsive when I both try to create a new text document or open an existing one. The only thing that happens is that the pen icon in the bottom right corner animates when pressed, the speech bubble in the top right corner highlights when pressed and I can go back. Nothing else.

**To Reproduce**
1. Download the app
2. Open the app
2. Create a new document or open an existing one

**Expected behavior**
I should be able to type something... or at least see the contents of the opened document.

**Actual behavior**
Just a blank screen with unresponsive icons.

**Screenshots**
![bild](https://user-images.githubusercontent.com/3254196/132558992-432206e8-f33c-4188-b0ad-6ae775815f1f.png)

**Smartphone (please complete the following information)**
 - Device: iPhone 6 or iPad Pro 2020
 - OS: iOS 13 on iPhone, iOS 14 on iPad
 - Browser: I used the app, not a browser?
 - Version: 6.4.11

**Comment by Ezinnem** [comment]
@tml1024 , Please can you take a look?

**Comment by tml1024** [comment]
Did you tap the round button with the pen in it? That is needed to make the document editable.

**Comment by tml1024** [comment]
There must be something special on your devices. Nobody else has reported anything like this. Can you think of something that is different on your iPhone and iPad? Have you tweaked some uncommon settings in iOS?

**Comment by eobet** [comment]
I have not tweaked anything to my knowledge, but incredibly:

Today, I can both open and edit contents on both devices again!

They haven't even been restarted or anything, they both just started working... so... this makes me think, could there have been an iCloud Drive hickup yesterday?

Either way, probably going to be very difficult to track down so I'm closing this. Thanks for looking!
