### ISSUE TITLE
[WOPI] Missing HTTP header `X-WOPI-Lock` when issuing a `RENAME_FILE` operation

### ISSUE THREAD

**Issue by drupol** [CollaboraOnline/online#3208]
**Describe the bug**
Hello,

I'm trying to implement the WOPI protocol with PHP and Symfony. I also created a demo Symfony app to test those packages.
This demo application has been published on Heroku at: https://wopi-app.herokuapp.com/

When I try to rename a document:

![image](https://user-images.githubusercontent.com/252042/132562818-f58087cf-2022-4571-97ce-dc819bd92886.png)

It fails.

In order to debug what's wrong, I enabled the Symfony Profiler in the demo application so we can debug the requests and responses online.

The request sent by Collabora is something like this:

![image](https://user-images.githubusercontent.com/252042/132563303-9b559028-27ae-4306-9617-8a725719e787.png)

As we can see, this is the `RENAME_FILE` operation, and the `X-WOPI-Lock` header is missing.
According to the [WOPI documentation](https://docs.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/rest/files/renamefile), it should be there.

**To Reproduce**
1. Go to https://wopi-app.herokuapp.com/
2. Login to the app
3. Edit a document
4. Rename the filename
5. Check the Symfony Profiler in the bottom and check the last requests
6. Identify the `RENAME_FILE` requests

**Expected behavior**
The request must have a `X-WOPI-Lock` header.

**Actual behavior**
The request does not have a `X-WOPI-Lock` header.

**Desktop (please complete the following information)**
 - OS: Linux / docker
 - Browser: Firefox
 - Version: Collabora 6.4.10

Note: I tested the `RenameFile` operation with the WopiValidator and the tests are passing: https://imgur.com/a/UGVkiur

**Comment by kendy** [comment]
@Ashod: Any ideas, please?

**Comment by drupol** [comment]
Going to retry this on latest version.

**Comment by drupol** [comment]
Same issue with latest version from today:

![image](https://user-images.githubusercontent.com/252042/135465357-38059b0d-1c37-4118-baa9-b46fd081beb3.png)

**Comment by Ashod** [comment]
This issue is fixed and should be available in the next release. Please reopen if the issue persists after testing (with a release post Oct 14th). Thanks!

**Comment by Ashod** [comment]
Thanks for confirming, @drupol.
