### ISSUE TITLE
Impress: leaflet-control-scroll doesn't work

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#321]
**Describe the bug**
.Both opening a pdf with comments or odp, ppt etc the scroll navigation controls (up and down) do not seem to work. It does not navigate between slides, it remains in the same slide. If the current slide has multiple comments than it scrolls **only** between them.

* What:
![image](https://user-images.githubusercontent.com/65948705/96247504-81b65800-0faa-11eb-8dd0-4f4a50120cbe.png)

* Where : Impress

**Comment by pedropintosilva** [comment]
Editing PDF; Adding Comments; Saving; (tried to reopen) but the nav. arrows never worked for me.

Tried to investigate a bit

It seems that the respective logic and maybe the problem would be somwhere in **AnnotationManagerImpress.js**:
* `loleaflet/src/control/Control.Scroll.Annotation.js` calls ˇ 
* `loleaflet/src/layer/AnnotationManagerImpress.js` (this was created with code moved from `ImpressTileLayer.js` [3141ba240377059a7709a445bb6041e4ed18b58f](https://git.libreoffice.org/online/+/3141ba240377059a7709a445bb6041e4ed18b58f))
* in `AnnotationManagerImpress.js` it fires `onAnnotationScrollDown`

Also it can be related with how we are limiting boundaries and scrolling. In Writer this does not happen (the document has a scroll that encompasses all the pages as opposed to impress where we have a scroll per slide)

**Comment by pedropintosilva** [comment]
[Uploading Making Online Trivial to Setup_commented.pdf…](document used in these tests)

**Comment by eszkadev** [comment]
@pedropintosilva this control is not for switching the pages but comments. It is useful when you have more comments than can be visible next to the slide. Then we use it to scroll the comments up/down to be able to see last comment for example. Please notice it is shown only when comments are present in the document (not page, what could be improved). Maybe it is not the best design and it results in misunderstanding but it works as expected.

**Comment by pedropintosilva** [comment]
pasting here what was already discussed somewhere else:

* I am aware that those buttons should navigate between comments
* I have inspect all the major commits on scrolling and annotations
* the problem is that those buttons are intended to navigate between comments , but they do not work outside of the current slide (even if you have multiple comments in the next slide)

for example if you open a odt with a couple of comments in different pages those controls will show up and will correctly navigate you through comments (encompassing the whole document, not just the current page)

but if you try with that document I attached there, you will see that this will not work

* so the next step, and if the controls are only for comments within the current page,  would be to show the controls only if the current page has multiple comments;
* good to have future step: ideally we would make those controls encompassing the whole document (multiple pages)

**Comment by pedropintosilva** [comment]
I have tested #406 :

- controls scroll to other pages with comments **successfully** 
- controls also scroll within the page when in presence of a page with multiple comments **successfully**
- controls do not show up when the document has no comments, **successfully** so

However in a document with only one comment in the first page:
- controls are still present when the document has only one comment and we are already in that page 
- control are present in the 2nd, 3rd page but upon pressing the up arrow (previous) they disappear and the page does move to the 1st page

**Comment by eszkadev** [comment]
Added new issue with easy hack - cover the feature with cypress tests
