### ISSUE TITLE
convert-to return file incomplete when source file is large

### ISSUE THREAD

**Issue by YanJun0512** [CollaboraOnline/online#3223]
**Describe the bug**
I try to use "convert-to" api to export a .ppt file as a .pdf, but when the source file is large(>50M), the file stream returned by the api is incomplete. And the http download time is always ~2s.

After reading trace log and searching source code, I notice socket data will be flush and socket will be stop after 2s, whether polling is continue or not. That will cause file stream in http response body incomplete.

```
wsd-00055-00569 2021-09-13 10:28:29.103085 [ docbroker_001 ] INF  Flushing socket for doc [/tmp/convert-to/tmp55aaaaaa/54M.pptx] for 2000000 us. stop: true, continuePolling: true, ShutdownRequestFlag: false, TerminationFlag: false. Terminating child with reason: [Finished saveas handler.].| wsd/DocumentBroker.cpp:515
wsd-00055-00569 2021-09-13 10:28:31.103284 [ docbroker_001 ] INF  Finished flushing socket for doc [/tmp/convert-to/tmp55aaaaaa/54M.pptx]. stop: true, continuePolling: true, ShutdownRequestFlag: false, TerminationFlag: false. Terminating child with reason: [docisdisconnected].| wsd/DocumentBroker.cpp:529
```

![image](https://user-images.githubusercontent.com/26226506/133084699-9cd5b159-bb2c-47fe-b5ff-024bfee2f888.png)

**To Reproduce**
```
curl --location --request POST 'http://10.225.116.76:9947/lool/convert-to/' --header 'Connection: Keep-Alive' --form 'data=@"/tmp/large_ppt/54M.pptx"' --form 'format="pdf"'
```

**Expected behavior**
return a complete pdf file.

**Actual behavior**
the return file is incomplete and cannot be open

**Screenshots**
content-length in response header is greater than real response body size.
![image](https://user-images.githubusercontent.com/26226506/133083430-6b74ccce-6a74-4b97-a939-bd50974f5040.png)

and the output pdf file cannot be open.
![image](https://user-images.githubusercontent.com/26226506/133083905-a56c5ee9-37b3-4f48-8e82-6eecddb5bc98.png)

http download time is always 2s, even the file stream is not finished.
![image](https://user-images.githubusercontent.com/26226506/133084414-a8a1bf26-c03f-41bc-9ef8-113cc8b9e8a3.png)

**Comment by Ezinnem** [comment]
This may be a load timeout related issue. 

@YanJun0512, you can try increasing the `limit_load_secs` in the loolwsd.xml file and see if that helps.

**Comment by Ezinnem** [comment]
Closing this issue due to no response from the author.
