### ISSUE TITLE
`Page...` Button under Layout does nothing.

### ISSUE THREAD

**Issue by stavros-k** [CollaboraOnline/online#3264]
**Describe the bug**

`Page...` Button under Layout does nothing.

**To Reproduce**
1. Go to `Layout
2. Click on `Page...`
3. See error

**Expected behavior**

Open Page Layout window to configure

**Actual behavior**
A clear and concise description of what actually happens.

Button does nothing, also nothing appears in console when I click it

**Screenshots**

![Screenshot 2021-09-20 232012](https://user-images.githubusercontent.com/47820033/134069951-745ce28c-e182-4d10-a76a-eef7128373e4.jpg)

**Desktop (please complete the following information)**
 - OS: [e.g. iOS] `Windows 10`
 - Browser: [e.g. chrome, safari] `Chrome`
 - Version: [e.g. 22]  `93.0.4577.82`

**Additional context**

Using Docker `6.4.11.3` on Nextcloud `21.0.4` and Collabora Online (App) `4.2.3`

**Comment by Andreas-Kainz** [comment]
Thanks for the bug report @stavros-k.

As Page Dialog was in the Layout tab of writer, impress, draw it should be also in the calc Layout tab, but sure with the correct uno command.

My suggestion. Update the uno command. @stavros-k as you found the issue, do you want to fix it by update the uno command name?

**Comment by stavros-k** [comment]
> My suggestion. Update the uno command. @stavros-k as you found the issue, do you want to fix it by update the uno command name?

I haven't worked in this project ever, so I think would best for someone else to push the fix. 
Thanks anyway :)

**Comment by Andreas-Kainz** [comment]
in the Control.NotebookbarClac.js file the command .uno:PageDialog has to be replaced by .uno:PageFormatDialog. That's the easiest way to leave your footprint at cool git history ;-)

https://github.com/CollaboraOnline/online/blob/0b1f5f6defe8fd46cb06f4cc2b2d60f6e6283b58/loleaflet/src/control/Control.NotebookbarCalc.js#L640

**Comment by stavros-k** [comment]
@Andreas-Kainz  Thanks for this opportunity. And guiding me through that!
Might not been a huge code change, but I learned how to add `Change-ids` which I never did before! 

PR is up :)

**Comment by Andreas-Kainz** [comment]
So you learn the most important thing. It's very easy to change things in cool.

That's not always true, but .js .css .xml habe some benefits.

**Comment by thebearon** [comment]
There's a small issue with the fix, @stavros-k, would you be up for doing a follow-up, based on https://github.com/CollaboraOnline/online/issues/3264#issuecomment-924339052 ? It needs those missing parameters, that's all.
