### ISSUE TITLE
Writer table, Columns, "Adapt table width" and "Adjust columns proportionally" do not work

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#3269]
**Describe the bug**
"Adapt table width" and "Adjust columns proportionally" do not work.

**To Reproduce**
Steps to reproduce the behaviour:
Writer > Select a Table  (I also tested by highlighting the entire table)
Table > Properties > Columns > "Adapt table width" or "Adjust columns proportionally" > OK.
Video demo:  https://user-images.githubusercontent.com/80790599/134491740-77d91ee5-d226-4ef9-bb61-bae98550e49d.mp4

**Expected behaviour**
I'd expect to see the column widths change. 
In Google it is Format > Table > Distribute rows, or Format > Table > Distribute columns.

**Actual behaviour**
the column widths do not change.

**Desktop**
Chrome OS, Chrome, Version 93.0.4577.69 (Official Build) (64-bit)
 
**Server**
LOOLWSD 6.4.12snapshot (git hash: c1e85d9) Served by: 88ee2642 LOKit Collabora Office 6.4-48 (git hash: 3edd452) "Ubuntu 18.04.6 LTS"

**Comment by thebearon** [comment]
Those buttons don't do anything by themselves if you are not adjusting the individual column sizes in the dialog. Have you done that as well?

**Comment by rpear** [comment]
@thebearon I have prepended "Select a Table",  and also added a video.

**Comment by thebearon** [comment]
@rpear Right, you need to adjust the individual column widths in the dialog for those check boxes to have effects. If you do that, you will see it behaves differently based on whether they're checked or not.

**Comment by rpear** [comment]
OK that makes sense, it does say: "adjust columns proportionally". I was expecting it to behave like the "distribute columns" and "distribute rows" in Google Docs and Microsoft 365.  I see that the desktop LibreOffice doesn't have "distribute columns" or "distribute rows", so I won't add it as a feature request. 
The "Adapt table width" doesn't seem to have any effect, but not to worry I didn't play around with it long, so probably me.

**Comment by thebearon** [comment]
If you have "Adapt table width" checked, and make changes to individual column widths, you will see that the "Remaining space" value (and with that, the size of the table) will change, otherwise it will take the difference from (or add it to) a different column's width.

**Comment by rpear** [comment]
Thank you, I see now, "Remaining space" is what is the remaining space available for the table to grow on the page.

I just found the LibreOffice equivalents of "distribute columns" and "distribute rows" that are in Google Docs and Microsoft 365. These are under Table > Size. They only appear in the context menu if they are applicable. I'll add a feature request for these in Online.
