### ISSUE TITLE
Add "Table Properties" to context menu when right clicking on a table in Writer

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#3270]
**Is your feature request related to a problem? Please describe.**
I often right click on a table to see the table properties to make changes, but the option is not there.  It is only in the Table toolbar.

**Describe the solution you'd like**
"Table Properties" to be on the context menu when right clicking on a table in Writer.

**Additional context**
- Whilst editing a table the toolbar can still be on Home, as the Properties button is under the Table toolbar it is not visible.
- See also #3329

**Comment by reos-rcrozier** [comment]
Seems like this can be closed? CODE 22.05

![image](https://user-images.githubusercontent.com/91322120/217803085-5773a41b-6539-494f-928f-3a0f6e512129.png)

**Comment by rpear** [comment]
Thanks for update, I have just tested in CODE 22.05.10.1 and can confirm the option is there and it works.
