### ISSUE TITLE
Certificate not more reading SSL Problem

### ISSUE THREAD

**Issue by gueniewie** [CollaboraOnline/online#3273]
**Describe the bug**
Hello everyone

After the last update, loolwsd no longer works on the installations that have been working up to now? loowsd can simply no longer read in the certificate files (permission denied), someone could look up why this is getting more and more annoying

**To Reproduce**
I have a centos 8 (oracle 8)
1. Go to 'install the RPM from  your repository'
change the path to the correct certivicates this is working with apache
4. See error SSL context exception: Error loading private key from file /etc/pki/tls/private/XXXX.XXX_ec.key: error:0200100D:system library:fopen:Permission denied

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots**

**Desktop (please complete the following information)**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information)**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by thebearon** [comment]
Perhaps best to follow up on this by provinding more details in the existing forum thread: https://forum.collaboraonline.com/t/access-to-file-denied-cert-chain/498
