### ISSUE TITLE
iOS App: Fullscreen button has no effect

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#3294]
**Describe the bug**
The "fullscreen" button in the iOS app has no effect and should be removed if possible.

**To Reproduce**
1. Open/create a writer document in the iOS app
2. Click on the "fullscreen" button next to the "save" button in the "global menu"

**Expected behavior**
As the button has no effect on iOS I expect to not have that button.

**Actual behavior**
The button is shown but has no use.

**Screenshots**
![image](https://user-images.githubusercontent.com/1211300/134738016-da2f3879-c265-4622-b056-d465949e4670.png)

**Tablet**
 - OS: iPadOS 14.6
 - Version: 21.6.1 (1)

**Comment by tml1024** [comment]
For you, @pedropintosilva ?

**Comment by tml1024** [comment]
In Safari on iPad, against "make run", clicking the "fullscreen" button does attempt to do something. The browser tab does switch to some different full-screen state. But then it immediately switches back to as it was, hmm.

But in the app, the button has no effect indeed, and should not be shown.

**Comment by tml1024** [comment]
I now notice that also the hamburger menu has a "Full Screen" entry in it. Why do we need to have such a menu entry when there is a button for the same functionality so close? But I digress. Will remove that, too, in the mobile apps.

**Comment by tml1024** [comment]
Suggested fix in https://github.com/CollaboraOnline/online/pull/3338
