### ISSUE TITLE
Online (and also iOS App): "Layout > Show Ruler" doesn't work

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#3295]
**Describe the bug**
In the current "online" version on https://staging.eu.collaboraonline.com/nextcloud/index.php the button "Layout > Show Ruler" doesn't work

**To Reproduce**
1. Open/create a writer document in online
2. Tap on "Layout > Show Ruler"

**Expected behavior**
The ruler should be shown.

**Actual behavior**
The ruler doesn't show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/1211300/134739586-e9a8eb7b-629b-4ca3-8163-8d21403c5b82.png)

**Online**
 - Browser: FF/Linux 92.0
 - Version: 21.06.1 (git hash: fa083863), Served by: a8c4837f

**Additional context**
This also happens on iOS, but I think it's best to report it against Online?

**Comment by thebearon** [comment]
Ah yes, this was fixed in 6.4 by @pedropintosilva with the following PR, it just needs to be ported to the development branch: https://github.com/CollaboraOnline/online/pull/3221

**Comment by nikslor** [comment]
This now works on my iPad (21.11.1 (2)), I expect it's fixed, let's close this one.
