### ISSUE TITLE
iOS App: crash when editing slide

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#3296]
**Describe the bug**
When one tries to edit a slide in a presentation the iOS app crashes instantly.

**To Reproduce**
1. Create/open a presentation using the iOS app
2. Enter edit mode
3. Tap into an area to edit some text on the slide

**Expected behavior**
I should be able to edit text.

**Actual behavior**
The app crashes.

**Tablet**
 - iPadOS: 14.8
 - Version: 21.6.1 (1)

**Comment by tml1024** [comment]
This will also be fixed by https://gerrit.libreoffice.org/c/core/+/122720

**Comment by nikslor** [comment]
Fixed in 21.6.1 (2) thanks a lot @tml1024. Do you want to close?

**Comment by tml1024** [comment]
Thanks for testing, closing.
