### ISSUE TITLE
iOS App: insert "Fontwork", "Text Box", "Line" or "Shapes" in a writer document leads to crash

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#3297]
**Describe the bug**
Insert "Fontwork", "Text Box" or "Shapes" into a writer document in the iOS app leads to a crash.

**To Reproduce**
1. Open/create a writer document using the iOS app
2. Tap on "Insert > Fontwork..." or "Insert >Text Box" or "Inser > Line" or "Insert > Shapes"
3.1 Fontwork: Choose any of the presets then tap "OK"
3.2 Text Box: no further action needed
3.3 Line: no further action needed
3.4 Shapes: Choose any of the presets then tap "OK"

**Expected behavior**
A "Fontwork", "Text Box", "Line" or "Shape" element should be added to the document.

**Actual behavior**
The app crashes

**Tablet**
 - iPadOS: 14.8
 - Version: 21.6.1 (1)

**Comment by nikslor** [comment]
The crash also happens when inserting "Text Box" or "Shapes" - I'm happy to add separate bugs but maybe it has the same root cause? I'll change the bug accordingly.

**Comment by tml1024** [comment]
This was also fixed by https://gerrit.libreoffice.org/c/core/+/122720

**Comment by nikslor** [comment]
Fixed in 21.6.1 (2). Thanks a lot Tor!

Do you want to close the issue?

**Comment by tml1024** [comment]
Thanks for testing, closing.
