### ISSUE TITLE
iOS App: Tap on a chart in a calc sheet crashes the app

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#3298]
**Describe the bug**
Tapping on a chart in a spreadsheet crashes the iOS app.

**To Reproduce**
1. Create/open a spreadsheet in the iOS app
2. Tap on "Inser > Chart" or tap on an existing chart in the spreadsheet

**Expected behavior**
A chart should be added or it should be possible to interact with the chart.

**Actual behavior**
The app crashes

**Tablet**
 - iPadOS: 14.8
 - Version: 21.6.1

**Comment by tml1024** [comment]
Apparently this was also fixed by https://gerrit.libreoffice.org/c/core/+/122720

**Comment by nikslor** [comment]
Fixed in 21.6.1 (2) thanks a lot @tml1024. Do you want to close?

**Comment by tml1024** [comment]
Thanks for testing, closing.
