### ISSUE TITLE
iOS App: crash when adding an animation effect for an element in a slide

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#3321]
**Describe the bug**
The iOS app crashes, when inserting an animation effect.

**To Reproduce**
1. Create/open a slide deck using the iOS app
2. Tap on the "Star" image in the right upper corner to open the "Animation" part in the sidebar
3. Tap on an element in the slide - for example, the title text of the slide
4. Tap on the "(+)" (plus) button in the Animation sidebar
5. Tap on "Basic"

**Expected behavior**
The "Basic" animation effect should be set on the "title text"

**Actual behavior**
The app crashes

**Tablet**
 - iPadOS: 14.8
 - Version: 21.6.1 (2)

**Comment by tml1024** [comment]
Fix in https://gerrit.libreoffice.org/c/core/+/123046 .

(Unclear whether that slide transition animation functionality actually works in the iOS app; but at least this fixes the crash as described here.)

**Comment by nikslor** [comment]
Fixed in 21.11.1 (2), thanks @tml1024
