### ISSUE TITLE
HTML/JS sidebar: shipped slide templates don't work

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#3322]
**Describe the bug**
In the impress sidebar of online (and also iOS, probably other platforms as well) there is a section where a user can choose an integrated slide master template. However, since the HTML/JS rework, those templates can't be selected.

**To Reproduce**
1. Create/open a slidedeck in online
2. Open the "Master Slides" sidebar 
3. Scroll down to 'Available for use'
4. Select one of the integrated templates

**Expected behavior**
The selected template should be applied

**Actual behavior**
The template doesn't get applied

**Screenshots**
![image](https://user-images.githubusercontent.com/1211300/135458338-b483f521-8850-4a3d-a9f7-b9b2bf4ea543.png)

**Online**
 - Firefox: 92.x
 - OS: Linux
 - Version: current version on https://staging.eu.collaboraonline.com/nextcloud/index.php - 21.06.1.0 (git hash: e5bbfc63) Served by: 7d76d5c7

**Comment by eszkadev** [comment]
fix in core: https://gerrit.libreoffice.org/c/core/+/123037

**Comment by eszkadev** [comment]
fixed in core, should be visible in the next snapshot
