### ISSUE TITLE
Writer tables: Add "Distribute Columns Evenly" and "Distribute Rows Evenly" to menu/s

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#3329]
**Is your feature request related to a problem? Please describe.**
I can not easily distribute columns and/or rows evenly.

**Describe the solution you'd like**
In Writer tables add the options to "Distribute Columns Evenly" and "Distribute Rows Evenly".
In LibreOffice, these options are under Table > Size, and also in the context menu under "Size". 
In Google and Microsoft, these options are known as "Distribute Columns" and Distribute Rows".

**Additional context**
To the credit of Collabora Online, it already has the options "Optimal Column Width" and "Optimal Row Height", and both Microsoft and Google do not have these options.

**Comment by Ezinnem** [comment]
The options Distribute Columns Evenly and Distribute Rows Evenly are seen on the Table propertied on the sidebar.


Tested using COOLWSD version: 22.05.0.1 git hash: [2163e2f0](https://github.com/CollaboraOnline/online/commits/2163e2f0)(E)

**Comment by Ezinnem** [comment]
https://user-images.githubusercontent.com/54344301/182581952-aabaa52d-febc-49cf-8763-31e0e3a60c9a.mp4
