### ISSUE TITLE
Time showing in comment/annotation is wrong on calc (ok in writer)

### ISSUE THREAD

**Issue by BigTwoProduction** [CollaboraOnline/online#3348]
Hello,

I have just noticed a bug, the date of a comment in a cell of a workbook is not read in the right format. Entering a date format in the cell does not change anything.
When the comment is filled in, the visible date is in the correct format and has the current date. As soon as the comment is saved the date shown is not the previous one.
In addition, each comment is changed to the current date and not to the date of the comment.
This bug is not present in writer only in calc.
This bug is present in my compiled version of CODE on docker but also with the official image provided.
Screenshots will be more telling.
For information the language of my installation is French. Changing the profile language to English fixes the bug. Even if locate is French.

1. Create a workbook through Nextcloud and open it 
2. Click on a Cell, go to menu Insert -> Comment
3. See date, write comment and save
4. Put the cursor on the commented cell, see the date, is not same as before.

**Screenshots**
Timezone on server:
![TimeZone](https://user-images.githubusercontent.com/19799334/136184161-cc53fb68-df27-4f1c-82c4-5d74a4bc763b.PNG)

Date of comment before saving:
![Comment1](https://user-images.githubusercontent.com/19799334/136184178-a315b6b7-39a0-4211-816b-c8b1943ccfbb.png)

Date of comment after saving:
![Comment2](https://user-images.githubusercontent.com/19799334/136184188-d9b678ad-adb9-4dd5-8c5d-c22cda9f7669.png)

Date of comment after saving and after change language profile from french to english
![Comment3_After_Change_LanguageFR_To_EN](https://user-images.githubusercontent.com/19799334/136184199-57bf9e4e-c0e9-4154-a90f-7814f7906047.png)

Information of both CODE docker of my two instances:
![Own_CODE_Docker](https://user-images.githubusercontent.com/19799334/136184212-33b444e5-d7a6-46a8-98aa-97731f06ac59.PNG)
![Official_CODE_Docker](https://user-images.githubusercontent.com/19799334/136184224-f456c31c-b38c-4e7e-9cef-c085c397c14a.PNG)

**Desktop/Server**
 - OS: Linux And Windows
 - Browser: Chrome and Firfox
 - Version Nextcloud : 19.0.3 and 22.2.0
 - LOOLWSD : 6.4.6 (44a46d7) and 6.4.11 (ae8d93b6)
 - LOKit : 6.4-23(77bfdb8) and 6.4-47 (85a46d2)
 - Ubuntu Server : 18.04.6 LTS and 20.04.2 LTS
 - Docker Version : Docker version 20.10.8, build 3967b7d and Docker version 20.10.7, build 20.10.7-0ubuntu1~20.04.2

I remain at your disposal for testing if needed.
Sincerely,
Jordan.

**Comment by tml1024** [comment]
One question, when you say "the language of my installation is French", what installation do you mean?

**Comment by Ezinnem** [comment]
Reproduced in LOOLWSD 6.4.11 snapshot (git hash: e251816).

**Comment by BigTwoProduction** [comment]
Hello,

This issue was fixed but seem to be bad now on 
Version COOLWSD : 21.11.0.6 git hash: 1e92cc5
Versison LOKit :Collabora Office 21.06.10.1 git hash: d382e7c
Servi par : Ubuntu 18.04.6 LTS f877c3fe

Any idea why ?
Best regards,
Jordan

**Comment by Ezinnem** [comment]
It seems a regression may have occured

**Comment by BigTwoProduction** [comment]
Hello @Ezinnem,

Maybe I open to much issues on this topic, but it's was fix as I said here https://github.com/CollaboraOnline/online/issues/3947

Best Regards,
Jordan.
