### ISSUE TITLE
Mobile: Annotations disappear (co-6-4 branch)

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#3356]
**Describe the bug**
(probably a regression or missing backporting)
This might be a combination of a regression and/or missing backporting. Upon entering a comment thread all the other comments disappear when we navigate back to the main list.

**To Reproduce**
1. Open on mobile mode
2. Click the view comments icon (at the top in the "actionbar") 
3. Navigate back and forward between comment thread and the main list

https://user-images.githubusercontent.com/65948705/136349859-95f19ea5-4ed3-4b57-8e7d-3c14bea106fa.mp4

**Expected behavior**
Comments shouldn't disappear 

**Actual behavior**
Comments disappear

**Smartphone (please complete the following information)**
 - OS: OS-independent
 - Browser: browser-independent
 - Version: <div id="loolwsd-version">6.4.13 (git hash: <a href="javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/10dfa431'));">10dfa431</a>)</div>

**Comment by Ezinnem** [comment]
I can confirm this issue occurs in LOOLWSD 6.4.13 (git hash: [809b194f](https://github.com/CollaboraOnline/online/commits/50399b20)).

**Comment by Darshan-upadhyay1110** [comment]
Works fine in latest version.

Closing this as too old.

COOLWSD version: 24.04.5.2
(git hash:
https://github.com/CollaboraOnline/online/commit/df56d78ca292018f51edd1e5b58a3be801f183f7)
LOKit version: Collabora OfficeDev 24.04.5.2
(git hash:
b57fd97)
Served by: Ubuntu 23.10
Server ID: fb8273cf
