### ISSUE TITLE
Mobile: Annotations' thread number disappear

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#3357]
**Describe the bug**
On mobile when the user navigates inside of a comment thread and then goes back the total number of comments in that thread disappears 

**To Reproduce**
1. Open on mobile mode
2. Click the view comments icon (at the top in the "actionbar") 
3. Navigate back and forward between comment thread and the main list

https://user-images.githubusercontent.com/65948705/136350857-1401eaba-ec7b-4e33-9a9b-11ae0b1f7447.mp4

**Expected behavior**
The total number of comments in that thread shouldn't disappear 

**Actual behavior**
The total number of comments in that thread disappear

**Smartphone (please complete the following information)**
 - OS: OS-independent
 - Browser: browser-independent
 - Version: <div id="loolwsd-version">21.06.1.0 (git hash: <a href="javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/408cf154'));">408cf154</a>)</div>

**Comment by Ezinnem** [comment]
I can confirm this issue ocurs in LOOLWSD 21.11.0.0 (git hash: [50399b20](https://github.com/CollaboraOnline/online/commits/50399b20)).

**Comment by Darshan-upadhyay1110** [comment]
Works fine in latest version.

Closing this as too old.

COOLWSD version: 24.04.5.2
(git hash: 
df56d78c)
LOKit version: Collabora OfficeDev 24.04.5.2
(git hash: 
b57fd97)
Served by: Ubuntu 23.10
Server ID: fb8273cf
