### ISSUE TITLE
Menu setting problem

### ISSUE THREAD

**Issue by lbzt2017** [CollaboraOnline/online#336]
If I only need to preview, but cannot download and copy files, how do I set it up?thanks

**Comment by mrkara** [comment]
@lbzt2017 , Hi! :)

Thank you for your question, but issues are not for questions and technical support. They are for reporting bugs, and enhancement requests like adding new features etc. Sorry if that was somehow not clear enough.

Please feel free to sign up on [our forum](https://forum.collaboraonline.com), and ask your questions there.
