### ISSUE TITLE
Add more actions per extension in discovery

### ISSUE THREAD

**Issue by drupol** [CollaboraOnline/online#3368]
Hi,

I'm working on finding a standard way to "view" a document using a WOPI Host ([Collabora](https://demo.eu.collaboraonline.com/hosting/discovery), [Office365](https://onenote.officeapps.live.com/hosting/discovery), ... etc etc).

To find the URL that I need to use, I have to make a query on the endpoint `hosting/discovery` and find the appropriate `action`.

In order to illustrate my message here, I will consider the discovery endpoint to be a SQL database that I can query, the SQL would be:

```sql
SELECT * FROM discovery WHERE name = "view" and extension = "doc"
```

I noticed that doing this exercise with [Office365](https://onenote.officeapps.live.com/hosting/discovery) is an easy task because it provide multiple actions per extension.

If you open the XML and search for the string `"doc"`, you will find the following actions:

<details>

```
<action name="view" ext="doc" default="true" urlsrc="https://word-view.officeapps.live.com/wv/wordviewerframe.aspx?<ui=UI_LLCC&><rs=DC_LLCC&><dchat=DISABLE_CHAT&><hid=HOST_SESSION_ID&><sc=SESSION_CONTEXT&><wopisrc=WOPI_SOURCE&><showpagestats=PERFSTATS&><IsLicensedUser=BUSINESS_USER&><actnavid=ACTIVITY_NAVIGATION_ID&>"/>
<action name="imagepreview" ext="doc" urlsrc="https://word-view.officeapps.live.com/wv/WordPreviewHandler.ashx?<ui=UI_LLCC&><rs=DC_LLCC&><dchat=DISABLE_CHAT&><hid=HOST_SESSION_ID&><sc=SESSION_CONTEXT&><wopisrc=WOPI_SOURCE&><showpagestats=PERFSTATS&>"/>
<action name="interactivepreview" ext="doc" urlsrc="https://word-view.officeapps.live.com/wv/wordviewerframe.aspx?embed=1&<ui=UI_LLCC&><rs=DC_LLCC&><dchat=DISABLE_CHAT&><hid=HOST_SESSION_ID&><sc=SESSION_CONTEXT&><wopisrc=WOPI_SOURCE&><showpagestats=PERFSTATS&>"/>
<action name="mobileView" ext="doc" urlsrc="https://word-view.officeapps.live.com/wv/wordviewerframe.aspx?<ui=UI_LLCC&><rs=DC_LLCC&><dchat=DISABLE_CHAT&><hid=HOST_SESSION_ID&><sc=SESSION_CONTEXT&><wopisrc=WOPI_SOURCE&><showpagestats=PERFSTATS&>"/>
<action name="embedview" ext="doc" urlsrc="https://word-view.officeapps.live.com/wv/wordviewerframe.aspx?embed=1&<ui=UI_LLCC&><rs=DC_LLCC&><dchat=DISABLE_CHAT&><hid=HOST_SESSION_ID&><sc=SESSION_CONTEXT&><wopisrc=WOPI_SOURCE&><showpagestats=PERFSTATS&>"/>
<action name="attend" ext="doc" urlsrc="https://broadcast.officeapps.live.com/m/ParticipantFrame.aspx?a=1&<e=EMBEDDED&><fs=FULLSCREEN&><rec=RECORDING&><thm=THEME_ID&><na=DISABLE_ASYNC&><vp=DISABLE_BROADCAST&><ui=UI_LLCC&><rs=DC_LLCC&><dchat=DISABLE_CHAT&><hid=HOST_SESSION_ID&><sc=SESSION_CONTEXT&><wopisrc=WOPI_SOURCE&><showpagestats=PERFSTATS&>"/>
<action name="convert" ext="doc" targetext="docx" urlsrc="https://word-edit.officeapps.live.com/we/WordConvertAndEdit.aspx?<ui=UI_LLCC&><rs=DC_LLCC&><dchat=DISABLE_CHAT&><hid=HOST_SESSION_ID&><sc=SESSION_CONTEXT&><wopisrc=WOPI_SOURCE&><showpagestats=PERFSTATS&>"/>
<action name="rtc" ext="doc" urlsrc="https://collabrtc.officeapps.live.com/rtc2/"/>
<action name="preloadview" ext="doc" urlsrc="https://word-view.officeapps.live.com/wv/StaticLoad.aspx?wx=w&wv=v&usescript=1&<ui=UI_LLCC>"/>
<action name="documentchat" ext="doc" urlsrc="https://word-edit.officeapps.live.com/we/SkypeProxy.ashx"/>
<action name="open" ext="doc" urlsrc="https://word-view.officeapps.live.com/wv/wordviewerframe.aspx?<ui=UI_LLCC&><rs=DC_LLCC&><dchat=DISABLE_CHAT&><hid=HOST_SESSION_ID&><sc=SESSION_CONTEXT&><wopisrc=WOPI_SOURCE&><showpagestats=PERFSTATS&><IsLicensedUser=BUSINESS_USER&><actnavid=ACTIVITY_NAVIGATION_ID&>"/>
```
</details>

The action names are:
* `view`
* `open`
* `documentchat`
* `preloadview`
* `rtc`
* `convert`
* `attend`
* `embedview`
* `mobileview`
* `interactivepreview`
* `imagepreview`

Thanks to all those actions available for the `doc` extension, it is simple to query the discovery and select the appropriate action to do on the document. Anyway, that's the purpose of the discovery endpoint!

Do you think we could do the same with Collabora?

IMHO, I think we should provide multiple actions per extension. I don't know yet if the name of those actions are standardized through all the clients, but maybe we could use the same as the one provided by Microsoft?

Right, now, the [Collabora discovery](https://demo.eu.collaboraonline.com/hosting/discovery) only provides 1 single action per extension (`edit`). It is then impossible to provide a way to `view` a document using the discovery endpoint.

During the Collabora meeting on Thursday, I've been told that I could add a query parameter to make it `readonly`, but this is not something standard and I think we should not do that, but use the discovery endpoint, that's the purpose of it.
On top of that, the discovery endpoint is built from [this XML file in the repository](https://github.com/CollaboraOnline/online/blob/master/discovery.xml) and it seems that the `urlsrc` xml attribute is dynamically generated by some process, so, it's not something that we can change quickly in that file.

**Comment by dagnelies** [comment]
While I understand that adding all actions may be overkill. At least adding the `view` action would be tremenduously beneficial for integration use cases and WOPI compatibility since it is the most common action by far.

Ideally, it should also open a read-only view of the document. But even would be a secondary concern since tweaking the "CheckFileInfo" flags can be used  to adapt the viewer/editor accordingly. (Flags ReadOnly, UserCanWrite, WebEditingDisabled ...dunno exactly which one caused what, but the result was corresponding to a "view")
