### ISSUE TITLE
Page border style and background changed from 6.4 to master

### ISSUE THREAD

**Issue by jancborchardt** [CollaboraOnline/online#3403]
**Describe the bug**
From 6.4 to master:
- The background behind the page got darker
- The border color got darker too
- There is a harsher box shadow
- There is no border-radius

**To Reproduce**
1. Open a document
2. Look at the borders of the page

**Expected behavior**
The style of 6.4 was much nicer actually, so maybe it was a bug to change to that?
Ideally I would even remove the box-shadow completely, and put in a bit more border-radius like 4px.

**Screenshots**
![image](https://user-images.githubusercontent.com/925062/136950118-578cffea-4ac4-4a95-ad5f-c8ce03bbe220.png)

cc @eszkadev @juliushaertl as discussed :)

**Comment by jancborchardt** [comment]
Thank you @eszkadev! :)

**Comment by eszkadev** [comment]
merged

**Comment by pedropintosilva** [comment]
thanks @eszkadev 
I have tested and I somehow still see a quite strong shadow and no border radius:
![page-shadow-123572-200](https://user-images.githubusercontent.com/65948705/137469618-e2738b36-0232-466b-b314-845916d586a1.png)
![page-shadow-123572](https://user-images.githubusercontent.com/65948705/137469619-9c0232c1-f649-44f2-bd15-5b31d3c33d32.png)

**Comment by pedropintosilva** [comment]
this has been fixed
