### ISSUE TITLE
Adding new comment animation flying from left looks a bit strange

### ISSUE THREAD

**Issue by jancborchardt** [CollaboraOnline/online#3412]
**Describe the bug**
In the Collabora Online master, the comment box is flying in from the left, which looks a bit weird.

**To Reproduce**
1. Open a document
2. Click the "Comment" button

**Expected behavior**
The animation makes sense in relation to the button or the action.

**Actual behavior**
The comment box flies in from the left of the content area.

**Screenshots**

**Animation in 6.4**
![Comment animation 6 4](https://user-images.githubusercontent.com/925062/137133164-55c008db-fab4-4532-9dd9-babfb13479d1.gif)

**Animation in master**
https://user-images.githubusercontent.com/925062/137133518-387a688a-8f57-476a-915d-8dd5fad58141.mp4

**Comment by pedropintosilva** [comment]
I understand that the animation can be improved but I have read this issue and patch 3 times and for the life of me I cannot understand it 100% : p maybe some :coffee: would help me : p :

> In the Collabora Online master, the comment box is flying in from the left, which looks a bit weird.
ok so master is wrong, right?

> Animation in 6.4
> Adds animation from 6.4
> Animation in master
> Adds animation from master

ok

but @eszkadev creates PR against 6-4 https://github.com/CollaboraOnline/online/pull/3422
@jancborchardt : nods

@pedropintosilva : is confused : p

**Comment by pedropintosilva** [comment]
Thanks @eszkadev and @Ezinnem for the clarification : ) 
_sorry for the noise_
