### ISSUE TITLE
Disable autocomplete in spreadsheets (mobile app)

### ISSUE THREAD

**Issue by htsmi** [CollaboraOnline/online#3432]
Apologies if this has been addressed elsewhere but I couldn't find it if it has been. I know the goal is not to have all the customization in the mobile app as on desktop or web, but I would like to have the option to disable the autocomplete function when editing cells. It's something that really gets in my way when I am repeating similar but different lines. I'm also not sure if the entries get kept between documents but if they do that's a real privacy concern as I could inadvertantly enter private information in a place I did not intend to.

**Comment by Darshan-upadhyay1110** [comment]
![image](https://github.com/user-attachments/assets/bb85b9be-2a07-4742-b4c9-39d68e9c319d)

Done

COOLWSD version: 24.04.6.1
(git hash: 
9dfee827)
LOKit version: Collabora OfficeDev 24.04.6.1
(git hash: 
8b00f3a)
Served by: Ubuntu 23.10
Server ID: 83043426
