### ISSUE TITLE
Can't open docs from Nextcloud in Android App

### ISSUE THREAD

**Issue by ganttview** [CollaboraOnline/online#3453]
In the Collabora Office Android app, I can browse my Nextcloud folders and see xlsx, docx & odt files there. However, if I try to open one, I get the message "Couldn't open the document."

If I create a new file within the app and save it in a Nextcloud folder, it creates the blank odt file but fails to open it for editing.

I can open and create files in local folders with no problems.

Files on Dropbox also work OK.

I can open and edit files within the nextcloud app's editor, but not in the Collabora Office app.

 - Device: Samsung Galaxy A20
 - OS: Android 11
 - Collabora App version: 6.4.3

Server:
Nextcloud 22.2.0
Collabora Online App (in nextcloud) 4.2.3
Collabora CODE server (in nextcloud) 6.4.1303

**Comment by Ezinnem** [comment]
Closing this issue due to no response from the author.

**Comment by brtptrs** [comment]
I would like to reopen this issue.
We are seeing this problem on:
 NC 22.2.x
 Collabora 21.11.1.0
Richdocuments App 4.2.3
Nextcloud Android app 3.18.1

**Comment by brtptrs** [comment]
I can create a edit a new file in Android, but after closing the file it can not be reopened and edited.
