### ISSUE TITLE
CODE 6.4.13 Calc Regression: Cannot insert Comments

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#3478]
In CODE 6.4.13 it does not seem to be possible to add comments to a calc table.

Clicking "Insert -> Comment" simply does nothing.

CODE version in use (self-built Docker image, using the provided Dockerfile):

Collabora Online Development Edition (CODE)
Diese Version von Collabora Online Development Edition (CODE) wird bereitgestellt von

LOOLWSD
6.4.13 (git hash: 3a048ea)
Angeboten von: ee831d72
LOKit
Collabora Office 6.4-49 (git hash: 70f6522)
"Ubuntu 18.04.6 LTS"
Copyright © 2021, Collabora Productivity Limited.

**Comment by joergmschulz** [comment]
confirmed. 
It is fixed now. Issue can be closed.

**Comment by thebearon** [comment]
Great, closing.
