### ISSUE TITLE
Spreadhseet restarts after editing cell

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#3487]
**Describe the bug**
While editing (typing into) a cell spreadsheet restarts (happens with and without parallel editing)

**To Reproduce**
1. Open https://staging.eu.collaboraonline.com/nextcloud/index.php/s/B7W9LLFcWZQn64G
2. Edit a cell
3. while inside of that cell, wait (focus)
4. The document "restarts" (is re-rendered)
5. Edits are lost

**Expected behavior**
Editing a spreadsheet without loosing unsaved data

**Actual behavior**
A clear and concise description of what actually happens.

**Desktop**
LOOLWSD
* 21.11-0 (git hash: 81ea2266)
* Served by: 94c16d16

LOKit
* built on a great technology base
* Collabora Office 21.06.5.1 (git hash: 1d54cb6)

**Comment by Ezinnem** [comment]
Fixed.

The issue is no longer reproducible using LOOLWSD 21.11.0.0 (git hash: [0ce564d9](https://github.com/CollaboraOnline/online/commits/0ce564d9)).
