### ISSUE TITLE
Android: Spreadsheets: Hamburger menu doesn't go full height when in readonly mode

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#3488]
**Describe the bug**
When viewing the document (before tapping the edit button) the hamburger menu panel doesn't go full length in height 

**To Reproduce**
1. Open app
2. Choose a file
3. Open hamburger menu
4. See the bad behaviour (previous top bar is still visible)

**Expected behavior**
The hamburger panel should go full height 

**Screenshots**
![image](https://user-images.githubusercontent.com/65948705/138860774-0ab402d0-56fa-4b4a-a46c-e2ae4b960886.png)

**Smartphone**
 - Device: Fairphone 3+
 - OS: Android 10
 - apk
 - Version: 6.4.13
online git-hash: cea7112d2
core git-hash: 70f652274508
**but it is also present in latest snapshot**:
``collabora-office-mobile-6.4-snapshot-arm64-v8a-2021-10-26.apk``

**Additional context**
This only occurs in calc
----

https://github.com/CollaboraOnline/online/discussions/3461

**Comment by Ezinnem** [comment]
This is not reproducible on Collabora office app version: 6.4.13
online git-hash: 809b194f1
