### ISSUE TITLE
Hide text boundaries by default

### ISSUE THREAD

**Issue by juliushaertl** [CollaboraOnline/online#3491]
**Describe the bug**
When discussing the general UI with @jancborchardt and @pedropintosilva we noticed that the the text boundaries add some distraction to the document view and it would be good to hide them by default if possible.

![image](https://user-images.githubusercontent.com/3404133/138888477-ff55e5a8-1aa1-4ae7-ac8b-e34e554fead1.png)

Also it is already possible to get a boundary view with the "View > Formatting Marks" option:

![image](https://user-images.githubusercontent.com/3404133/138888632-8ae8f715-9b46-41d1-9412-6fd8aa2998c1.png)

core seems to have a dedicated option for this as "Text Boundaries", so it would make a cleaner document view when hiding those by default.

**Comment by timar** [comment]
This fix does not work with CODE/COOL 23.05.
```
warn:configmgr:52415:52415:configmgr/source/xcuparser.cxx:337: unknown item "/org.openoffice.Office.UI/ColorScheme/ColorSchemes/org.openoffice.Office.UI:ColorScheme['Collabora Office']/DocBoundaries" in "file:///home/timar/MOVE/online/coolkitconfig.xcu"
warn:configmgr:52415:52415:configmgr/source/xcuparser.cxx:337: unknown item "/org.openoffice.Office.UI/ColorScheme/ColorSchemes/org.openoffice.Office.UI:ColorScheme['Collabora OfficeDev']/DocBoundaries" in "file:///home/timar/MOVE/online/coolkitconfig.xcu"
warn:configmgr:52415:52415:configmgr/source/xcuparser.cxx:337: unknown item "/org.openoffice.Office.UI/ColorScheme/ColorSchemes/org.openoffice.Office.UI:ColorScheme['LibreOffice']/DocBoundaries" in "file:///home/timar/MOVE/online/coolkitconfig.xcu"warn:configmgr:52415:52415:configmgr/source/xcuparser.cxx:337: unknown item "/org.openoffice.Office.UI/ColorScheme/ColorSchemes/org.openoffice.Office.UI:ColorScheme['LibreOfficeDev']/DocBoundaries" in "file:///home/timar/MOVE/online/coolkitconfig.xcu"
```
all items are unknown, the correct item seems to be:
```
<item oor:path="/org.openoffice.Office.UI/ColorScheme/ColorSchemes/org.openoffice.Office.UI:ColorScheme['COLOR_SCHEME_LIBREOFFICE_AUTOMATIC']/DocBoundaries"><prop oor:name="IsVisible" oor:op="fuse"><value>false</value></prop></item>
```

**Comment by caolanm** [comment]
I imagine https://gerrit.libreoffice.org/c/core/+/149244 was at least when the name stopped getting recognized.

A downside of not having these corners is that I think it is then difficult to know if you are in a header or main body text

**Comment by mmeeks** [comment]
I was totally confused by this myself the other day and found myself unable to understand the behavior; turned out I was editing a footer under a table, and it was a feature-not-bug-but-very-carefully-hidden - because of the lack of those text boundaries.

As a compromise - I suggest we render text boundaries when there is a footer present, and not when there is not (?)
