### ISSUE TITLE
Impress: spell checking: status bar keeps showing EN USA

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#3492]
**Describe the bug**

**To Reproduce**
1. Open a presentation document
2. Write some text in another idiom (other than EN)
3. Change the spell checking to that idiom (in this case Portuguese (Portugal))
4. Noticed that the status bar still shows English

**Expected behavior**
The status bar should change and show Portuguese (Portugal)

**Actual behavior**
Shows English (USA) even though, when opening, the other one is checked

**Screenshots**
![image](https://user-images.githubusercontent.com/65948705/138903087-cd797519-9e13-4d05-b42d-6f767f58cdaa.png)

**Desktop**
LOOLWSD
* 21.11-0 (git hash: 81ea2266)
* Served by: 94c16d16

LOKit
* built on a great technology base
* Collabora Office 21.06.5.1 (git hash: 1d54cb6)

**Additional context**
https://github.com/CollaboraOnline/online/discussions/3461

**Comment by Ezinnem** [comment]
This issue does not seem reproducible anymore.

I tested using the COOLWSD version: 21.11.4.1snapshot git hash: [5e2e1b6](https://github.com/CollaboraOnline/online/commits/5e2e1b6)
