### ISSUE TITLE
Impress: sidebar: sometimes more than one icon stays activated

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#3493]
**Describe the bug**
Some times when changing quickly between sidebar modes using impress we reach a state where 2 buttons stay selected. However the only way I can describe it in a reproducible way is to just do it right at the beginning when the document opens like so:

**To Reproduce**
1. Open presentation document (in this case I use smartart-test_CO41.pptx from the public demo documents)
2. right after openng the document go quick to the right top and click any other sidebar icon
3. Now we have two active sidebar icons there

**Screenshots**

https://user-images.githubusercontent.com/65948705/138907545-faf077af-35a2-4355-adb8-7be84e28a309.mp4

**Desktop (please complete the following information)**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information)**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**
https://github.com/CollaboraOnline/online/discussions/3461

**Comment by Ezinnem** [comment]
I can confirm it occurs in LOOLWSD 21.11.0.0snapshot (git hash: [570c31d](https://github.com/CollaboraOnline/online/commits/570c31d))
