### ISSUE TITLE
Drop down list doesn't work on Calc

### ISSUE THREAD

**Issue by moshpirit** [CollaboraOnline/online#3495]
**Describe the bug**
If we create [drop down lists on Calc](https://www.techrepublic.com/blog/diy-it-guy/diy-add-drop-down-lists-to-libreoffice-spreadsheets/) they don't work on Collabora on Android since nothing happens if we press the :arrow_down_small: arrow icon

**To Reproduce**
It happens on created drop down lists on Collabora Android as well as already made ones.

**Expected behavior**
a drop down list is shown

**Actual behavior**
nothing happens, the :arrow_down_small: icon doesn't do anything.

**Smartphone (please complete the following information)**
 - Device: Samsung Tab S4
 - OS: Android 10
 - Browser: not using any 
 - Version: 6.4.13 (F-droid)

**Comment by brtptrs** [comment]
I'm also seeing a problem with dropdown lists in the normal browser view when testing 21.11.0.0.
The dropdown opens but only shows en empty (white) space. 
Clicking on this empty space does select the option that should be shown at that position.
Tested on the latest Firefox and Chrome versions.

**Comment by Ezinnem** [comment]
@brtptrs, the fix for the issue has been made on #3697.

**Comment by brtptrs** [comment]
I can confirm that, for us, the problem is solved in 21.11.1.0

**Comment by danir-de** [comment]
#close please.
