### ISSUE TITLE
Can not insert image from nextcloud

### ISSUE THREAD

**Issue by NISZOpenSourceTeam** [CollaboraOnline/online#3511]
Inserting image from Nextcloud doesnt work.
To Reproduce

Try to insert an image with "insert image" opens the dialog box of nextcloud.

- 1 Select a picture 
- 2 Press Choose
- 3 dialog box closes

Expected behavior
Image should be inserted

Actual result
Nothing happens

Desktop

- Nextcloud server 22.1.1 Ubuntu
- OS: Windows
- Browser: Chrome
 - Collabora online version:
21.06.1.0 (git hash: 5a0738f)
Served by: b7a30aab
LOKit
Collabora Office 21.06.4.1 (git hash: 90aa650)
"Ubuntu 20.04.3 LTS"

**Comment by Ezinnem** [comment]
I am able to insert images from the NextCloud using LOOLWSD 21.11.0.1 (git hash: [a8bb765](https://github.com/CollaboraOnline/online/commits/a8bb765)).

@NISZOpenSourceTeam, please can you update your Collabora Online version and test it again?

If you still experience difficulty inserting image from the Nextcloud, you can share a screen recording showing the issue.

**Comment by joergmschulz** [comment]
same here - it works perfectly with such a recent master.

**Comment by Ezinnem** [comment]
Good to know it works fine at your end.

**Comment by JRGonz** [comment]
Hate to bring up a blast from the past but I think this should be re-opened. I still can't seem to insert local images from Nextcloud but I can upload Local images just fine.

**Comment by Ezinnem** [comment]
I am able to insert images both locally and from Nextcloud using:

COOLWSD version: 23.05.2.2 (git hash: [ccb20f1e](https://github.com/CollaboraOnline/online/commits/c9e7591) (E))
LOKit version: Collabora Office 23.05.2.3 (git hash: [d34a7f1](https://git.libreoffice.org/core/+log/352bcab))

Please can you share more details regarding your setup and version? Also, feel free to share a screen-recording showing the issue.

**Comment by Joehein** [comment]
same here: insert local image works fine, image from nc does not. 

COOLWSD: 23.05.4.2 (git hash: 0b27e85)
LOKit 23.05.4.2 (git hash: 78039c5)
install from rpm repo, on same machine as NC (Version 27.1.1)
both: ssl termination via haproxy

any solutions?
