### ISSUE TITLE
Calc:Comment button active when it should have not

### ISSUE THREAD

**Issue by NISZOpenSourceTeam** [CollaboraOnline/online#3513]
Describe the bug
After a Chart insertion, comment button is active. When clicking on it nothing happens.
1. Insert a chart
2. Click on chart
3. Go to Review
4. Click on the comment button

**Expected behavior**
It should not be active the button

**Actual behavior**
Comment button is active

**Desktop
 - OS: Windows
 - Browser: Chrome
 - Collabora online version:
              LOOLWSD
              21.06.1.0 (git hash: 5a0738ff)
              Served by: b7a30aab
              LOKit
              Collabora Office 21.06.4.1 (git hash: 90aa650)
              "Ubuntu 20.04.3 LTS"
              Nextcloud version 22.1.1

**Comment by pedropintosilva** [comment]
Thanks @NISZOpenSourceTeam for reporting it!
