### ISSUE TITLE
Calc: Can not insert comment below 9. row

### ISSUE THREAD

**Issue by NISZOpenSourceTeam** [CollaboraOnline/online#3514]
Describe the bug

After scrolling down below 9. row can not add comment . Comment box only appear above 9.row.

1. Make a new calc sheet
2. Scroll down below 9. row
3. Try adding a comment

**Expected behavior**
Comment box should be appear

**Actual behavior**
Comment box doesnt appear

**Desktop (please complete the following information)**
 - OS: Windows
 - Browser: Chrome
 - Collabora online version:
                 21.06.1.0 (git hash: 5a0738ff)
                Served by: b7a30aab
                LOKit
                Collabora Office 21.06.4.1 (git hash: 90aa650)
                "Ubuntu 20.04.3 LTS"

**Comment by Ezinnem** [comment]
The issue has been fixed. Works fine on LOOLWSD 21.11.0.0 (git hash: [b84071c6](https://github.com/CollaboraOnline/online/commits/b84071c6)).
