### ISSUE TITLE
Loading/Editing a spreadsheet file full with comments is slow.

### ISSUE THREAD

**Issue by gmasei11** [CollaboraOnline/online#3520]
**Describe the bug**
Loading/Editing a specific spreadsheet file full with comments is slow. This seems to be a regression when compared to 6.4.0.

**To Reproduce**
1. Open the [Test71.ods](https://forum.collaboraonline.com/uploads/short-url/btgFJMKR6vHBa24RixYKZNiV0at.ods)
2. Select multiple times cells, rows, columns

**Expected behavior**
The load is slow but the UI works fine.

**Actual behavior**
After the load spinner disappears the page hangs for a while with a partially loaded UI, then cells appear but without data and then, after a while, the cells are filled with the data. Selecting cells, rows, columns is slow. In general, the edit is slow.

**Desktop (please complete the following information)**
 - OS: Ubuntu 20.04.3 LTS
 - Browser: chrome, firefox
 - Version: 6.4.10 debug, 2021 debug

**Additional context**
https://github.com/CollaboraOnline/online/discussions/3461
In 6.4.0 works fine.
The problem was mentioned first here: https://forum.collaboraonline.com/t/collabora-weekly-meeting-46/687#test-fest-gabriel-1 where you can find attached the file for testing.

**Comment by Ezinnem** [comment]
I did not notice any slowness with the loading of the file using LOOLWSD 6.4.13 (git hash: [4e5bac7f](https://github.com/CollaboraOnline/online/commits/4e5bac7f)).

**Comment by pedropintosilva** [comment]
thanks @Ezinnem  but did you try with **Version: 6.4.10** as reported by @gmasei11 ?

**Comment by gmasei11** [comment]
Thanks @Ezinnem for your feedback. I still think that there is a drop in performance in 6.4.10 in comparison with 6.4.0. Indeed it is not so dramatic like in co 2021 and it is more visible in Firefox than Chrome. This could suggest that the root of the issue comes from an earlier version than co 2021. See the videos below:

6.4.0 Firefox


https://user-images.githubusercontent.com/73231749/139674778-55941671-0210-43b4-a2db-419a6417e5a7.mp4

6.4.10 Firefox


https://user-images.githubusercontent.com/73231749/139674981-f4eb293e-a9b0-4c54-88da-78eb60b8f17f.mp4

**Comment by Ezinnem** [comment]
The performance issue has been worked on recently. Please see #3205.
I think that is the reason this issue is not reproducible using the recent 6.4.13 version.

@gmasei11, Please can you test with the newer version 6.4.13?

The performance issue in the new version 21.11 may require further investigation.

**Comment by gmasei11** [comment]
@Ezinnem, I've tested with a build in debug mode based on latest revisions of core cp-6.4 and online co-6-4. In Chrome it works fine. However, in Firefox (93.0 (64-bit)) it is much worse than in 6.4.10, it hangs indefinitely at initializing step:

![firefox_cool_freeze](https://user-images.githubusercontent.com/73231749/140047098-80927b17-832a-4100-8226-cda1639bf789.jpg)

This is the tested version:

![cool_version](https://user-images.githubusercontent.com/73231749/140047150-187b06dc-9aef-48c2-ba60-59a270ebd48f.jpg)
