### ISSUE TITLE
Impress: Wrong labelling of buttons in Layout tab

### ISSUE THREAD

**Issue by SustReal** [CollaboraOnline/online#3527]
**Describe the bug**

I noticed some inconsistencies in the labellings of some buttons in the Layout Tab of the NotebookBar in Impress Online 21.11:

This concerns:

- The "New Page" & "Duplicate Page" buttons should be labelled "Slide"
- "Slide Layout" button
-  The "Reset zoom" button has inconsistent capitalization  

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a presentation in Online 21.11
2. Click on the Layout tap in the NotebookBar

**Expected behaviour**
- The "New Page" & "Duplicate Page" buttons should be labelled "New Slide" & "Duplicate Slide"
- "Slide Layout" should be named "Sidebar" (like in the other modules)
- "Reset zoom" should be "Reset Zoom" for consistent capitalization across the buttons 

**Actual behaviour**
Currently, inconsistent/ambiguous labelling of buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/51329893/139649641-31652451-8161-4245-871b-3a9bf9648ce3.png)

**Desktop (please complete the following information)**
 - Browser: [Firefox on Linux]
 - Version: [90.0.2]

**Smartphone (please complete the following information)**
 - 

**Additional context**
-

**Comment by Ezinnem** [comment]
@pedropintosilva, @Andreas-Kainz
