### ISSUE TITLE
About button is not removed on collabora online (desktop branding)

### ISSUE THREAD

**Issue by printminion** [CollaboraOnline/online#3528]
**Describe the bug**
According the code. It is possible to remove about dialog.
`<!-- Remove if you don't want the About dialog -->`
https://github.com/CollaboraOnline/online/blob/master/loleaflet/html/loleaflet.html.m4#L241

when one removes the about dialog. The about  button still present on desktop and thows an error when one pushes it

```
bundle.js:formatted:97520 Uncaught TypeError: Cannot read properties of undefined (reading 'outerHTML')
    at NewClass.showLOAboutDialog (bundle.js:formatted:97520)
    at Object._executeAction (bundle.js:formatted:79621)
    at HTMLDivElement.<anonymous> (bundle.js:formatted:95677)
    at HTMLDivElement.dispatch (bundle.js:formatted:4025)
    at HTMLDivElement.elemData.handle (bundle.js:formatted:3913)
```

**To Reproduce**
1. patch loleaflet.html to remove about dialog
2. open collabora online (desktop branding)
3. click on Help.

**Expected behavior**
* mobile
   * about menu item is not present
* desktop
   * about button is not present 

**Actual behavior**
* mobile
   * about menu item is not present
* desktop 
  * about button is present
  * klick on click button does nothing and throws an error in console log.

**Screenshots**
![Selection_20211101_001](https://user-images.githubusercontent.com/320529/139708589-ca636282-5fa0-4840-9214-55a5019a5224.png)

![Selection_20211101_002](https://user-images.githubusercontent.com/320529/139708602-c3b55919-ebae-4cbd-acc8-0064982d3f18.png)

**Desktop (please complete the following information)**
 - Browser: chrome

**Additional context**
adding branding in docker image

**Comment by pedropintosilva** [comment]
I can confirm, this is happening on:
- 21.11.X
- only when using Notebookbar mode
