### ISSUE TITLE
Easier creation of bulleted lists via * or -

### ISSUE THREAD

**Issue by jancborchardt** [CollaboraOnline/online#3536]
LibreOffice has a function to do it similar to Google Docs that using * and - automatically creates bulleted lists which is a super nice quality of life enhancement. It would be nice to enable this feature by default:
**Tools → AutoCorrect → AutoCorrect Options → Options tab → Bulleted and numbered lists check**

Google Docs also does it a bit more obviously: They format it as list as soon as you press space after the * or - (if a line starts with it). LibreOffice currently only does it as soon as you type something after it and press enter. Adjusting it to how Google Docs does it would be nice on top. :)

@kendy @eszkadev as discussed

**Comment by eszkadev** [comment]
I prepared a patch for it (in LO core): https://gerrit.libreoffice.org/c/core/+/124966
Needs some testing.

**Comment by eszkadev** [comment]
decided to merge it to the master first so we do more testing: https://gerrit.libreoffice.org/c/core/+/135059

**Comment by Darshan-upadhyay1110** [comment]
Already done with PR: https://github.com/CollaboraOnline/online/pull/7215
