### ISSUE TITLE
Calc: selecting initial cells: selection jumps

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#3548]
**Describe the bug**
Cell selection seems to work fine until you try to select the initial cells (top left), selection jumps (unselecting a part of what was initially selected by the user)

**To Reproduce**
1. Open .ods document
2. Select the 1st 4 cells (top left)

**Expected behavior**
Selection shouldn't change 

**Actual behavior**
Selection changes without user's input

**Screenshots**
Document: [Nueva Hoja de cálculo.ods](https://github.com/CollaboraOnline/online/files/7467084/Nueva.Hoja.de.calculo.ods)

https://user-images.githubusercontent.com/65948705/140049484-9ef443cf-e081-4c64-8bcd-c0d49d955fc4.mp4

**Desktop (please complete the following information)**
 - OS: Linux
 - Browser: Firefox
 - Version: 21.11

**Additional context**
https://github.com/CollaboraOnline/online/discussions/3461

**Comment by joergmschulz** [comment]
confirming for 

COOLWSD version:
21.11.0.1 (git hash:2a2f567d)
LOKit version:
Collabora Office 21.06.6.1 (git hash:8037a24)
