### ISSUE TITLE
Sidebar downloads/renders as CODE starts then it disappears.

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#3552]
**An area for improvement**
When CODE is starting up the sidebar appears before the document, it can take several seconds to download/render the icons, when it has rendered it then hides, and lastly the document loads. There seems to be no point in downloading/rendering the sidebar if it is toggled off, can the downloading be done later?

It is not a big problem, I really like the new sidebar and toolbars. On slower computer/networks like mine it may be more profound.

**Desktop / browser / version**
Chromebook, Chrome, Version 94.0.4606.104 (Official Build) (32-bit)

**CODE version**
LOOLWSD 21.11.0.0snapshot (git hash: 570c31d) Served by: 5ebf03b4
LOKit built on a great technology base Collabora Office 21.06.5.2 (git hash: d1a0bb1) "Ubuntu 18.04.6 LTS"

**Comment by Ezinnem** [comment]
@eszkadev

**Comment by eszkadev** [comment]
Yes, it could be improved by using strategy where we start without sidebar and then we open it only when needed.

**Comment by Andreas-Kainz** [comment]
I think we can close this issue.
