### ISSUE TITLE
Calc: "Find & Replace" input dialog not working as expected

### ISSUE THREAD

**Issue by SustReal** [CollaboraOnline/online#3615]
**Describe the bug**
The input field of the "Find & Replace" dialog does not seam to work as expected. In the "Find" field, I was not able to type ongoing search terms but had to click into the input field after every single letter

**To Reproduce**
1. Open a spredsheed
2. Click on 'Find and Replace' (via Hometab or Burger menu)
3. Try to type more than a letter into the "Find" field

**Expected behavior**
It should be possible to type more than a letter without having to clink into the field

**Actual behavior**
After typing a letter into the "Find" field the cursur exits the search field. The same wrong behaviour happens when deleting a character using backspace

**Screenshots**
![grafik](https://user-images.githubusercontent.com/51329893/141495799-82fa4599-929e-4cd6-b2e7-33b54b40aed2.png)

**Desktop (please complete the following information)**
 - OS: [Ubuntu 21.04]
 - Browser: [firefox 94.0]
 - Version: Collabora Online 21.11.0.1

**Smartphone (please complete the following information)**
 - 

**Additional context**
-

**Comment by joergmschulz** [comment]
This is not restricted to spreadsheets, but also happens in text documents.
21.11.0.0 (git hash: e6a2a43e)
Collabora Office 21.06.5.2 (git hash: b3dace9)

**Comment by fenris** [comment]
I can confirm this still happened in 21.06.6.1

after entering the character, we need to click on the Find field back to enter the next character

**Comment by joergmschulz** [comment]
confirming: in the latest master this doesn't happen any longer.
