### ISSUE TITLE
Compleing issues

### ISSUE THREAD

**Issue by Gsinfotech** [CollaboraOnline/online#3622]
hey sir can u tell some error is showing for compiling what the error
Thats 2 error is showing can someone help to solve it

<img width="1552" alt="Screenshot 2021-11-14 at 11 53 04 PM" src="https://user-images.githubusercontent.com/36947388/141693564-7c55e9d1-e75d-4f05-8974-934ca8094770.png">
<img width="1552" alt="Screenshot 2021-11-14 at 11 53 08 PM" src="https://user-images.githubusercontent.com/36947388/141693570-c315e5a5-1a9b-449c-82a2-265dea116666.png">

**Comment by pedropintosilva** [comment]
Hi, could you please add some more info? What where you trying to build and which steps did you follow? Thanks : )

**Comment by Gsinfotech** [comment]
m following github online collabora can u tell me it that build on mac os
or i think we have to download translations of 9.9 gb may i kwn can u we
build on linux or before compile can we have to download libreoffice build
dep ??
*Thanks*

*Regards* <http://gsinfotech.in/>
*Gsinfotech* <http://gsinfotech.in/>
*8847213434* <http://gsinfotech.in>

**Comment by Gsinfotech** [comment]
Any update??
