### ISSUE TITLE
Collabora Online 21.11 Brand Redundant / Overlap Logo

### ISSUE THREAD

**Issue by fenris** [CollaboraOnline/online#3623]
Collabora Online 21.11 Brand Redundant (About) Button

Loolwsd version:
21.11.0.1snapshot

CO version:
21.06.6.1

As per attached screenshot:
![Screenshot 2021-11-15 160911](https://user-images.githubusercontent.com/405473/141745786-e8bad239-7aff-450b-ac86-13b8c6b4f746.jpg)

**Comment by thebearon** [comment]
I think this should be fixed now, right, @pedropintosilva?

**Comment by Ezinnem** [comment]
The issue has been fixed.

I tested using the LOOLWSD 21.11.0.1 (git hash:[f486abaf](https://github.com/CollaboraOnline/online/commits/f486abaf))
