### ISSUE TITLE
The date in the comments/annotations on Calc is always the current date when file is an xlsx (ok for .odt/.ods)

### ISSUE THREAD

**Issue by BigTwoProduction** [CollaboraOnline/online#3625]
Hello,

This bug is not new, I make a ticket to you in order to show you the bug.

When you put a comment in a cell on a spreadsheet, following the ticket 
https://github.com/CollaboraOnline/online/issues/3348 
the date is well that of the day with the good format.

However unlike Writer where if you put a comment on a word/phrase/etc in a month for example the date of the comment will always be the date of a month ago, for Calc all comments regardless of the date of affixing take the current date.

1. Create a workbook through Nextcloud and open it
2. Click on a Cell, go to menu Insert -> Comment
3. Keep in mind or writer somewhere the date.
4. Put the cursor on the commented cell, see the date, same as today.
5. Save and close workbook.
6. Open the workbook 1/2 day later after saving.
7. Put the cursor on the commented cell, see the date, same as today.

**Screenshots:**
Comments in Writer
![image](https://user-images.githubusercontent.com/19799334/141771935-728e69cb-13de-46fd-a7ce-0d02dba1d770.png)

Comments in Calc (was set on 03/11/2021)
![image](https://user-images.githubusercontent.com/19799334/141772087-6ce6ae41-451f-47a6-b8b1-77dbcbf01b73.png)

**Desktop/Server**

- OS: Linux And Windows
- Browser: Chrome and Firfox
- Version Nextcloud : 19.0.3 and 22.2.0
- LOOLWSD : 6.4.6 (44a46d7) and 6.4.14 (2a2d1af3)
- LOKit : 6.4-23(77bfdb8) and 6.4-50 (ead2aa7)
- Ubuntu Server : 18.04.6 LTS and 20.04.2 LTS
- Docker Version : Docker version 20.10.10, build b485636 and Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2

I remain at your disposal for testing if needed.
Sincerely,
Jordan.

**Comment by Ezinnem** [comment]
The issue you described does not seem reproducible on my end.

Using LOOLWSD 6.4.14 (git hash: [e30c297b](https://github.com/CollaboraOnline/online/commits/e30c297b) )

@BigTwoProduction, Please can you test again?

**Comment by BigTwoProduction** [comment]
Yes of course, I've just build today a docker image of CODE with LOOLWSD version: 6.4.14 (git hash: 3fd1bca9).
I've created a new .ods file, write in a cell some text and put a comment on this cell and save this file.

I will tell you tomorrow if the date will change with any modification.

Best regards,
Jordan.

**Comment by BigTwoProduction** [comment]
Hello,

This issue was on my mind again last night.
Fortunately, I can now confirm this outcome by insisting, so I'm opening this ticket again.

So I summarize, you create a spreadsheet type file by setting CODE so that the file is natively in ODS format. The comments are well on the dates indicated there is no problem. See screenshot below.
![image](https://user-images.githubusercontent.com/19799334/142617692-a9c42823-0d9a-47c5-9d70-a2917ad4d4b8.png)
![image](https://user-images.githubusercontent.com/19799334/142617763-5abdcef6-c40a-439a-9965-b4ce5d936677.png)

However if the file is natively created in xlsx. The dates to which the comments are affixed will always be the date on which the file is consulted.
See screenshot below.
![image](https://user-images.githubusercontent.com/19799334/142617921-c49742cc-47ae-4138-97e2-dac88ac0f6e4.png)
![image](https://user-images.githubusercontent.com/19799334/142617976-a70338f4-aacf-4dfa-b68a-4ead617e4561.png)

By the way, in XLSX, the name of the author of the comment disappears for past comments.
Can be reproduce using LOOLWSD version: 6.4.14 (git hash: 3fd1bca).
@Ezinnem , Can you confirm ?

Best regards,
Jordan.

**Comment by BigTwoProduction** [comment]
Hello,

Nobody can confirm this bug?

Best regards,
Jordan.

**Comment by Ezinnem** [comment]
I still cannot reproduce the issue.

@BigTwoProduction, maybe you can share a sample file?

**Comment by BigTwoProduction** [comment]
Yes of course with pleasure !

I just tested on another instance, with these files downloaded from the first and imported into the second. The bug is exactly the one described in this issue.
[test.odt](https://github.com/CollaboraOnline/online/files/7595352/test.odt)
[Test_Date.xlsx](https://github.com/CollaboraOnline/online/files/7595354/Test_Date.xlsx)
[Test_Date.ods](https://github.com/CollaboraOnline/online/files/7595355/Test_Date.ods)

Jordan.

**Comment by Ezinnem** [comment]
Thanks for sharing the test files.

I can reproduce using 21.11.0.2 (git hash: [417dd2e7](https://github.com/CollaboraOnline/online/commits/417dd2e7))

**Comment by BigTwoProduction** [comment]
Hello,

Seem to be still reproducable in 
LOOLWSD : 6.4.16 (176bbabc)
LOKit : 6.4-52(6bdb8b7)

![image](https://user-images.githubusercontent.com/19799334/146354986-6286fb67-3dfc-4c4f-af96-fa790b750a2e.png)

Any progress on this issue?

Best Regards,
Jordan.

**Comment by BigTwoProduction** [comment]
Hello @Ezinnem,

Maybe I open to much issues on this topic, but it's was fix as I said here https://github.com/CollaboraOnline/online/issues/3947

Best Regards,
Jordan.

**Comment by thebearon** [comment]
For the record, creation dates aren't stored in comments in XLSX format, so not much could be done about that anyway.
