### ISSUE TITLE
Search with Ctrl-F doesn't work if status bar is hidden

### ISSUE THREAD

**Issue by juliushaertl** [CollaboraOnline/online#3629]
**Describe the bug**
When the status bar is hidden, there is no way to search with Ctrl-F

**To Reproduce**
1. Hide the status bar
2. Press Ctrl-F to search

**Expected behavior**
The status bar shows and the search input is focussed

**Actual behavior**
Nothing happens

**Desktop (please complete the following information)**
 - OS: Linux
 - Browser: Firefox
 - Version: 93

**Additional context**
Happens on master and 6.4

**Comment by thebearon** [comment]
Indeed, issue confirmed.
