### ISSUE TITLE
spaces between words will be removed, when inserting a hyperlink

### ISSUE THREAD

**Issue by edmundlaugasson** [CollaboraOnline/online#3645]
**Describe the bug**
When selecting multiple words to inser hyperlinks, quite often spaces between words will be removed automatically.

**To Reproduce**
1. Insert multiple words
2. select them
3. open "Insert hyperlink" dialog either with CTRL+K or via appropriate button
4. Insert the hyperlink and press OK or Enter
5. even hyperlink is created, spaces between words might be removed - not all of them, but at least some

**Expected behavior**
No spaces are removed between words.

**Actual behavior**
At least some spaces are removed between words. This is random behaviour, which spaces.

**Desktop (please complete the following information)**
 - OS: [EndeavourOS](https://en.wikipedia.org/wiki/EndeavourOS) with [KDE](https://en.wikipedia.org/wiki/KDE)
 - Browser: Chromium
 - Version: 95.0.4638.69
 - Nextcloud 22.2.3
 - Collabora Online 4.2.3
 - Collabora Online - Built-in CODE Server 6.4.1303

**Additional context**
Sentences are written often in Estonian language, which contains [appropriate characters](https://en.wikipedia.org/wiki/Estonian_language#Alphabet).

**Comment by Ezinnem** [comment]
The issue you described is not reproducible on my end using the 6.4.14 (git hash: e30c297b).

**Comment by eszkadev** [comment]
I prepared a patch for this issue: https://gerrit.libreoffice.org/c/core/+/125482

**Comment by eszkadev** [comment]
Patch was just merged, it should be fixed in the next CODE release
