### ISSUE TITLE
Writer: hyperlink pop-up window will be closed, when to click outside and back to it

### ISSUE THREAD

**Issue by edmundlaugasson** [CollaboraOnline/online#3647]
**Describe the bug**
E.g. selecting word, opening hyperlink creation dialog, then click in another browser window to copy the link and when coming back to Writer, and click to hyperlink dialog window - it will be closed....

**To Reproduce**
1. Insert some words
2. select them
3. open "Insert hyperlink" dialog either with CTRL+K or via appropriate button
4. click to another window, e.g. web browser to copy the link
5. click back to hyperlink dialog window to paste hyperlink, but that window will be closed then and you cannot paste the hyperlink and need to reopen the dialog. Here is no difference, in which cell to click, dialog window will be closed anyway. Certainly I tried to reactivate the Link cell to paste the link.

**Expected behavior**
Opened hyperlink insertion dialog window remains open even, when to click on it, regardless of that another window was activated during the hyperlink insertion dialog window was open.

**Actual behavior**
Currently that hyperlink insertion dialog window will be unexpectedly closed.

**Desktop (please complete the following information)**
- OS: [EndeavourOS](https://en.wikipedia.org/wiki/EndeavourOS) with [KDE](https://en.wikipedia.org/wiki/KDE)
- Browser: Chromium
- Version: 95.0.4638.69
- Nextcloud 22.2.3
- Collabora Online 4.2.3
- Collabora Online - Built-in CODE Server 6.4.1303

**Additional context**
It is very common behaviour to activate another window to copy hyperlink.

**Comment by Ezinnem** [comment]
@eszkadev
