### ISSUE TITLE
 Line breaks in comments get lost on first edit LOOLWSD version: 21.11.0.1 (git hash: f8f6af5e )

### ISSUE THREAD

**Issue by joergmschulz** [CollaboraOnline/online#3658]
LOOLWSD version:
21.11.0.1 (git hash: f8f6af5e) from  Nov 17

When I add comments to writer/calc documents, I can enter line breaks.
These line breaks appear on first save.
<img width="131" alt="image" src="https://user-images.githubusercontent.com/6523646/142250795-0db321f9-d729-4430-b567-732eaef0fa48.png">

When I edit these comments, the line breaks disappear on saving.
<img width="258" alt="image" src="https://user-images.githubusercontent.com/6523646/142250889-fa9bb086-492b-4737-99ee-e2a762760b61.png">

When I add further text, and more line breaks, these line breaks will be saved and will not disappear on further saves.
<img width="258" alt="image" src="https://user-images.githubusercontent.com/6523646/142250983-dff343e9-194f-4bb0-a7c7-5e9fa990450e.png">
<img width="244" alt="image" src="https://user-images.githubusercontent.com/6523646/142251092-c8772d8a-976d-472b-a13a-cb463f442a3b.png">

**Comment by Ezinnem** [comment]
I can confirm this issue is reproducible in LOOLWSD 21.11.0.1 (git hash: [f486abaf](https://github.com/CollaboraOnline/online/commits/f486abaf))

**Comment by joergmschulz** [comment]
confirmed - the fix works as expected. Thank You!
