### ISSUE TITLE
Last save timestamp says X hour even if the file was changed a long time ago

### ISSUE THREAD

**Issue by thebearon** [CollaboraOnline/online#3682]
Open a file that hasn't been changed in several days.
Eg. I have a file here that was last changed 22 days ago.

-> Note how the last save field in the toolbar shows the elapsed time in hours, eg in the above case: `Last saved: 526 hr. ago`

Previously in such case it used to show the date of when the file was last saved, eg. `Last modification: Sep 20, 2021, 10:18 PM`.

This is a regression from 4d22123fc30b18b34c81ff9b22a7ead34755e56d, which added a separate case for hours. That is fine if the elapsed time is less than a day, otherwise it would be good to show the date.

@luka-nextcloud, what do you think?

**Comment by luka-nextcloud** [comment]
Yes, I think that should be fixed. Let me take a look.

**Comment by juliushaertl** [comment]
https://github.com/CollaboraOnline/online/pull/3699 fixed that.

**Comment by thebearon** [comment]
Indeed, thanks for fixing, @luka-nextcloud!
