### ISSUE TITLE
Can't find spreadsheets page layout after upgrading Collabora Online Development Edition to version 6.4

### ISSUE THREAD

**Issue by Sys-Admin889** [CollaboraOnline/online#371]
**Describe the bug**
After upgrading Collabora Online Development Edition from 4.2 to 6.4, I don't have the ability to print with landscape layout. 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/59320357/96690365-e2b3a680-1383-11eb-9b1a-7a166018b72a.PNG)

**Server Information**
Virtual appliance from the Univention App Center with Nextcloud.

**Comment by thebearon** [comment]
A `Format Page...` item has been added to the Sheet notebookbar tab in the most recent CODE build. The Univention app will be upgraded eventually.
