### ISSUE TITLE
Build CODE on Gitpod after fork the main CollaboraOnline/online repo

### ISSUE THREAD

**Issue by bvarga91** [CollaboraOnline/online#3712]
Following the steps "Build CODE on Gitpod" below this link:
https://collaboraonline.github.io/post/build-code/
the 'make run' command will not work because the 'include' and 'instdir'
files will missing after I forked the main repo.

To Reproduce
1. Go to https://collaboraonline.github.io/post/build-code/
2. Choose Operating System: Build CODE on Gitpod
3. Follow the steps, but use a forked repo instead the main Online repo
("Don’t forget to fork the main repo")
4. Try to do 'make run'
5. Probabaly you will got an error: make: *** No rule to make target 'run'.  Stop.
6. Then run './autogen.sh' and './configure'
7.  Error: configure: error: LibreOffice path must be configured: --with-lo-path

Expected behavior
LibreOffice path should be configured and the 'include' and 'instdir'
files should exists.

Actual behavior
LibreOffice path is not configured and the 'include' and 'instdir'
files are not exists.

Screenshots

With Collabora Online main repo (good):
![Collabora_Online_Repo](https://user-images.githubusercontent.com/40356466/143264545-2fdaa346-b172-4aaa-a7ee-be389640aa09.jpg)

With a forked Collabora Online repo (bad):
![Forked_Repo](https://user-images.githubusercontent.com/40356466/143264509-a2648d7a-fa71-45df-bdea-563dd1cc3466.jpg)

Desktop
 - OS: Winows 10
 - Browser: chrome

**Comment by Ezinnem** [comment]
@bvarga91, Collabora Online can only be built on Linux.

**Comment by pedropintosilva** [comment]
Thanks @Ezinnem but via gitpod it is built on that but can be operated from virtually anywhere  via browser

**Comment by pedropintosilva** [comment]
Thanks @bvarga91 for reporting it! I will check that

**Comment by pedropintosilva** [comment]
@bvarga91 I think the documentation needs some improvement there was missing the extract of the zip file and exporting environment variable to be use later on with configure. Here is how I managed to have it up and running (please confirm if you are able to do so on your side as well):

* Fork
* hit the GitPod button
* ``tar xvf core-co-2021-assets.tar.gz``
* ``export LOCOREPATH=$(pwd)``
* ``cd online/``
```
./configure --enable-silent-rules --with-lokit-path=${LOCOREPATH}/include \--with-lo-path=${LOCOREPATH}/instdir \--enable-debug
```
I noticed that we are not installing chromium which is needed for the cypress tests (that's why I didn't add that flag here) (I will add that later to the gitpod)
* ``make run``

**Comment by bvarga91** [comment]
Thanks @pedropintosilva for the quick solution. Now it is working perfectly fine. Thank you. :)

**Comment by bvarga91** [comment]
@pedropintosilva may I have one more related question, please. After I built it without any error, I tried to open an example document with the link I got in the terminal:
https://9980-green-marmoset-b0ezmyvy.ws-eu17.gitpod.io/browser/55ed82d72/debug.html?file_path=/workspace/online/test/data/hello-world.odt
But I get an WebSocket error message:

![error](https://user-images.githubusercontent.com/40356466/143466342-6641bd3d-850d-422b-962b-4254ff877c4c.JPG)
.

May I ask how could I solve it?
Thanks in advance. :)

**Comment by pedropintosilva** [comment]
Yes I noticed that, I was hopping to fix it before your next attempt : p 

* I have fixed the missing dependency for cypress (so it will be possible to also run cypress tests via gitpod)
* I have fixed some deprecated stuff around the setup
* I need now to fix that issue. It seems that it tries to use SSL but maybe webSocket is not using SSL or the opposite. I will keep you posted : )

**Comment by pedropintosilva** [comment]
So the trick here is that you shouldn't click those urls : p because it's localhost urls and we actually have VNC set up for that purpose

1. First you do as you did before:

https://user-images.githubusercontent.com/65948705/143485776-bc18e58a-787d-451f-bfe5-1330c9734ce7.mp4

And
2. Be sure you open the VNC connection in your browser
3.  then instead of clicking those links you copy and open it using firefox
4. Play with it in the VNC's tab

https://user-images.githubusercontent.com/65948705/143486710-9c5c7e6e-6a4a-4eeb-a199-8d555c90898f.mp4

**Comment by pedropintosilva** [comment]
tomorrow I will merge a PR that makes the process a bit easier (no need to extract the archive, maybe disable SSL so to avoid that warning in FF; Include Cypress tests; Include webkit based browser Chromium; etc)

I will also add and clarify the info in the repository and in the community website, thanks again for reporting it !

**Comment by bvarga91** [comment]
@pedropintosilva, thank you very much the very detailed explanation and help. I really appreciate it. I tried it the way as you show in the video. It worked well.

Note: Also I integrated the Online code base into the VS Code desktop and I built (make run) from there. After that, I clicked on those links and everything went well by using firefox and chromium too and the test documents opened without any warning.

![Képkivágás](https://user-images.githubusercontent.com/40356466/143500019-b8bbd76b-a7fd-4dbf-a0b0-afeca188021e.JPG)

**Comment by pedropintosilva** [comment]
beautiful : )

**Comment by pedropintosilva** [comment]
Fixed with #3731

**Comment by bvarga91** [comment]
@pedropintosilva, thank you very much.

**Comment by grantmk** [comment]
Just a note - if you've fired under a different name than "online" then you need to change "cd online" to whatever your fork name is.

FYI, All of the commands that @pedropintosilva laid out are contained in the .gitpod.yml file but don't seem to be executed on startup (causing all these issues!).

Also, thanks @pedropintosilva!
