### ISSUE TITLE
select command fill highlight color which has to big focus

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#3716]
#### Now
![Screenshot_20211124_222841](https://user-images.githubusercontent.com/8517736/143316379-2691761f-fd4a-4024-90ef-47ae7ba538cc.png)

#### Past
![Screenshot_20211124_224028](https://user-images.githubusercontent.com/8517736/143316423-e8ca851e-e5ff-4ca8-a174-a33002ae050e.png)

#### LibreOffic
![Screenshot_20211124_224310-1](https://user-images.githubusercontent.com/8517736/143316584-64c10408-dec8-4bd3-8602-76180a8efa7a.png)

In LibreOffice there is gray with a darker gray border for select and blue for hover. In the past cool also use a gray element for selected, but now the filled highlight color was used which is from my point of view the wrong color, cause the command was selected and not highlighted. With make the icon white, it give a good contrast but from my point of view the selected commands has to much focus.

Other office suited also use gray for selected commands.

**Comment by Ezinnem** [comment]
@pedropintosilva

**Comment by Andreas-Kainz** [comment]
What's the reason to have a different select layout for toggled command's like Auto Spell Check?

I'm for a nice and simple gray selection for everything AND an highlight color hover frame. Like it is in picture **LibreOffice**
