### ISSUE TITLE
Sidebar scrollbar differs from document scrollbar and partly hides icons

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#3725]
Describe the bug
Sidebar scrollbar differs from document scrollbar and partly hides icons: If you select an object that shows a lot of items in the sidebar or when you expand items in the sidebar so the bar gets to large for the screen a scrollbar appears. This scrollbar:
- Has a different look versus the scrollbar used for like the document area. 
- It, probaly cause it is larger then intended, slightly hides the most right icons in the sidebar. 

To Reproduce
- Start a document
- Add an object line an picture or slect something that has a lot of items in the sidebar, or expand all items in the sidebar so that scrollbar in the sidebar appears.
- The scrollbar is thick compared to the scrollbar of the document area. It also partly hides the most right icons in the sidebar.

Expected behavior
I would expect we use the same scrollbars for the sidebar as used in the document area. That would solve the partly hidden icons too.

Actual behavior
Different scrollbar, visually off comparted to scrollbar in document area. Icons are slightly hidden.

Screenshots
![afbeelding](https://user-images.githubusercontent.com/37268999/143536265-184d7a78-5a78-4c32-9d1e-e6ed1ead78b8.png)

Desktop (please complete the following information)
- OS: Windows 10 (2004)
- Browser: Firefox 94.0.2 (64 bit), Chrome  96.0.4664.45 (Officiële build) (64-bits)
- Version: Nextcloud staging.eu.collaboraonline.com
- COOLWSD version: 21.11.0.3 git hash: 55ed82d7
- LOKit version: Collabora Office 21.06.8.1 git hash: ceddcf2

**Comment by Ezinnem** [comment]
I do notice that the scrollbar covers an icon as stated.

![scrollbar-outlook](https://user-images.githubusercontent.com/54344301/143580246-02c64ce6-b31a-4e3f-a464-b4c1428ee30b.png)

**Comment by sebastiaanveld** [comment]
@Ezinnem mind you have a small scrollbar in the sidebar just like like the scrollbar that is in the document's frame. In my screenshot the scrollbar in the sidebar is different and wider in size as in using more space.

**Comment by sebastiaanveld** [comment]
Looks fixed in latest CODE, using
COOLWSD versie: 21.11.3.6 git hash: [eb73aa3]
LOKit versie: Collabora Office 21.06.26.1 git hash: [524dda8]

Just to show the difference:
![afbeelding](https://user-images.githubusercontent.com/37268999/163616476-278b31a9-8659-4cf3-97d5-f98ec17010e7.png)

Issue can be closed if anyone agrees.

**Comment by sebastiaanveld** [comment]
Problem is back in Staging:

COOLWSD versie: 22.05.0.1 git hash: [74f39eb1]
LOKit versie: Collabora Office 22.05.0.1 git hash: [3a88519]
Bediend door: openSUSE Leap 15.3 

![afbeelding](https://user-images.githubusercontent.com/37268999/170499284-de2b611b-685b-43a5-8598-01115e0213b8.png)
