### ISSUE TITLE
Hard to see close button in Nextcloud sidebar after opeing in CODE

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#3726]
Describe the bug
Hard to see close button in Nextcloud sidebar after opening in CODE. The NC sidebar show a document preview at the top which make the X-button to clode this sidebar after opening hard to see for users if the background has a lof of information.

To Reproduce
- Open an document with like a picture on the top.
- Open the NC Sidebar from within CODE
- The X-button of the NC Sidebar is hard to see.

Expected behavior
This probably needs to be partly fixed in NC, but I would suggest we hide the document preview part in the NC sidebar which has no function here as we already have this document opened for editing or viewing. 
If one clicks on Detail of a document from within NC itself the preview is nice as it shows a part of the document. 

Actual behavior
The X-button of the NC Sidebar is hard to see.

Screenshots
![afbeelding](https://user-images.githubusercontent.com/37268999/143540475-b105c589-3439-4b44-9eb0-350db7a363f4.png)

Desktop (please complete the following information)
-     OS: Windows 10 (2004)
-     Browser: Firefox 94.0.2 (64 bit), Chrome 96.0.4664.45 (Officiële build) (64-bits)
-     Version: Nextcloud staging.eu.collaboraonline.com
-     COOLWSD version: 21.11.0.3 git hash: 55ed82d
-     LOKit version: Collabora Office 21.06.8.1 git hash: ceddcf2

**Comment by Ezinnem** [comment]
@sebastiaanveld, this issue seems a lot related to https://github.com/nextcloud/richdocuments/issues/1782
