### ISSUE TITLE
Notebookbar disappears when seleting See History button

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#3727]
Describe the bug
When one click the "See history" button on the Notebookbar File tab the Nextcloud sidebar opens as expected, but then Notebookbar disappears also. This is not what one expects, as when clicking "Share" op the Notebookbar File tab this also opens the NC Sidebar but the Notebookbar stays visible as expected.

To Reproduce
- Start a new document
- Click the File tab in the Notebookbar
- Click "See history" button
- NC Sidebar appears, selects the Versions tab over there as expected. The Notebookbar disappears.
- Need to click the "Close Document" "X" to show the Notebookbar again.

![afbeelding](https://user-images.githubusercontent.com/37268999/143550525-20d60ad7-92b3-4278-902e-cacf80e558f2.png)

Expected behavior
One would expect the Notebookbar to stay visable. Just like cliking the Share button does.

Actual behavior
Notebookbaar disappears and one needs to click the button that is at the location that normally would close the document.

Screenshots
![afbeelding](https://user-images.githubusercontent.com/37268999/143550095-b0c97187-1438-489f-8fc5-276e2cd64115.png)

Desktop (please complete the following information)

    OS: Windows 10 (2004)
    Browser: Firefox 94.0.2 (64 bit), Chrome 96.0.4664.45 (Officiële build) (64-bits)
    Version: Nextcloud staging.eu.collaboraonline.com
    COOLWSD version: 21.11.0.3 git hash: 55ed82d
    LOKit version: Collabora Office 21.06.8.1 git hash: ceddcf2

**Comment by eszkadev** [comment]
Notebookbar is hidden because document snapshots in "see history" are opened in read-only mode. When we click close button we go back to the current state where editing is possible.

**Comment by sebastiaanveld** [comment]
Kind of figered that out indeed. Was a bit confused at first as I didn't expect the bar to hidden and that I was supposed to click the versions to preview them. It makes sense and even exporting of the previewed files to different file formats works:)
A thing may be that when you close the preview the NC Version tab stays in place and now clicking the file versions does result in an action performed and the only thing a user could do is Rollback. So I think the workflow may need some ajustments for an end user to make sense.
Maybe hide the NC sidebar again when leaving the Preview mode?
Or make is more clear the user is supposed to click the document versions in Preview mode.

**Comment by eszkadev** [comment]
cc @juliushaertl 
you might be interested :)

**Comment by juliushaertl** [comment]
Hiding the Nextcloud sidebar might be a good idea here. In general improvements for the verison view have already been discussed a bit in https://github.com/nextcloud/richdocuments/issues/1782

It would definitely make sense to make it more obvious that a version is currently being viewed compared to the current editable version.

**Comment by thebearon** [comment]
Let's continue the conversation in https://github.com/nextcloud/richdocuments/issues/1782 .
