### ISSUE TITLE
"Time" in field, cell always shows the time in UTC

### ISSUE THREAD

**Issue by GitWidi** [CollaboraOnline/online#3733]
When I insert a field of type "Time" it always shows the time in UTC, no matter which time zone is chosen on the system.

### Steps to reproduce the behavior:
1. Create a "New document"
2. Insert > Field > Document
    - Type: Time
    - Select: Time
    - Format: 13:37:46
    - [Insert]
The current time is inserted but shown as UTC, not the current local time.

### Screenshot
![image](https://user-images.githubusercontent.com/4623128/143623304-c1446ded-1cad-44ff-87fd-377a99acfe46.png)

### Expected behavior
I excpect the local time, as it works in the desktop variant of LibreOffice.

### Client details:
- OS: Windows 10 Version 20H2 (Build 19042.1348)
- Browser: Vivaldi 4.3.2439.65 (Stable channel) (64-Bit)

### Server details:
- OS: Linux cloud 4.9.0-16-amd64 SMP Debian 4.9.272-2 (2021-07-19) x86_64 GNU/Linux
- Nextcloud: 22.2.3
- PHP: 8.0.13
- App Collabora Online: V4.2.3
- Collabora Online server:
    - Docker image: collabora/code, 21.11.0.3.1
    - Collabora Office 21.06.8.1
    - COOLWSD: 21.11.0.3 

### Further information
This issue occurs not at the desktop editions (standalone) of LibreOffice.
But I don't know if it is due to the software package LibreOffice-Online (LOOL), the package Collabora Online Development Edition (CODE) or rather the integration in Nextcloud (App: Collabora Online).

see also: Statements on [issue tracker for LibreOffice Online](https://bugs.documentfoundation.org/show_bug.cgi?id=136347).
see also: Statement for the [issue report on Nextcloud App Collabora Online](https://github.com/nextcloud/richdocuments/issues/1878#issuecomment-980227921).

Regards,
Friedbert

**Comment by Ezinnem** [comment]
I can confirm this occurs in 21.11.0.3 git hash: 265c275a

**Comment by GitWidi** [comment]
Thanks for this feedback.
However, I wonder if your suggestion ("_browser when Time **is inserted**_") is what we would like to see.
I would rather expect the time zone settings of the browser where we open/view the document.
A short example:
- I had a system whose time zone of the browser was set to Hawaii (HST, UTC-10h) and saved that file at 12/01/2021 10:24 PM@HST.
- A little bit later, I opened this file on this system: 
   - ![grafik](https://user-images.githubusercontent.com/4623128/144388305-acf7fbfe-4248-470f-951d-68c27d8d4731.png)
   - Here you see that the date/time fields are rendered related to UTC.
   - Expected "Document > Date > Date": 12/01/2021
   - Expected "Document > Time > Time": 10:28 PM
   - Expected "DocInformation > Modified > Time" :  10:24 PM
- At about the same time I opened the same file on a second system whose browser was set to Europe/Berlin (CET, UTC+01h).
    -  ![grafik](https://user-images.githubusercontent.com/4623128/144389303-411d436e-808d-4472-9059-a8da543d4025.png)
    - Expected "Document > Date > Date": 12/02/2021
    - Expected "Document > Time > Time": 09:28 AM
    - Expected "DocInformation > Modified > Time" : 09:24 AM

Regards,
Friedbert

**Comment by GitWidi** [comment]
Oh yeah, the other thing I noticed.
This does not only concern the field "Time" the module "Writer". This applies to all dynamically rendered data that refers to timestamps. And not only in the module "Writer" but in all modules ("Calc, ...").

Regards,
Friedbert

**Comment by Darshan-upadhyay1110** [comment]
i tested this in current version, it is working good. I set my timezone IST (Indian Standard time) and it correctly sets right time in document Not UTC

![image](https://github.com/user-attachments/assets/5db9f58a-d78d-4c17-939c-39c1f518f34b)

COOLWSD version: 24.04.6.2 (git hash: 7bb21429)
LOKit version: Collabora OfficeDev 24.04.6.2 (git hash: 321166f)
Served by: Ubuntu 23.10
Server ID: 9fd431d3
