### ISSUE TITLE
Copy and paste multiple non-adjacent cells / rows / columns  does not work - calc

### ISSUE THREAD

**Issue by avatar1024** [CollaboraOnline/online#3744]
Copy and paste multiple non-adjacent cells/rows/columns does not work.

**To Reproduce**
1. Select multiple rows or cells that are not adjacent to each other
2. Press Ctrl+C to copy
3. Go to another sheet in the same file or elsewhere on the same sheet
4. Press Ctrl+V to paste

**Expected behavior**
The copied cells should paste (adjacent to each other like in LO)

**Actual behavior**
Nothing happens

**Screenshots**
Section of multiple non-adjacent cells

![non-adjacent cells selection](https://user-images.githubusercontent.com/18719956/143904450-6ada604a-7045-49da-b98e-9c85f8cff69d.png)

**Desktop (please complete the following information)**
 - OS: KDE neon
 - Browser: Firefox 94 and Brave
 - Version: CODE 6.4.14 server + Nextcloud Collabora Online app 4.2.3

**Comment by Ezinnem** [comment]
Reproducible in CODE 6.4.14 git hash: 6ec2992

**Comment by avatar1024** [comment]
FYI, this is still the case with CODE 21.11.1.0

**Comment by avatar1024** [comment]
Still the case in 21.11.2.2

**Comment by andrsharov** [comment]
Hi, everybody.

I also have this problem.
```
Version COOLWSD:
21.11.4.2
git hash: 
3eff190
```
```
Version LOKit:
Collabora Office 21.06.28.1
git hash: 
f63c415
Works on Ubuntu:
Ubuntu 18.04.6 LTS
7eb6635f
```
![image](https://user-images.githubusercontent.com/44819772/172397126-bed43edd-40ff-4fd9-b179-edaabcc4e377.png)
![image](https://user-images.githubusercontent.com/44819772/172397430-2b6b8b5d-ead8-4dee-a0e9-053f17cff958.png)
![image](https://user-images.githubusercontent.com/44819772/172397947-494e0b04-42bc-40c7-aaa1-95718a309c0a.png)

**Comment by x4IPx** [comment]
<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 600;">Describe the bug</strong><br style="box-sizing: border-box;">Doesn't copy cells while filtering a column. If all filters are disabled, the data is copied without problems.</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 600;">To Reproduce</strong><br style="box-sizing: border-box;">Steps to reproduce the behavior:</p><ol dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-left: 0px;">Create excel file</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Create a simple table like :</li></ol>

Name | Price
-- | --
one | 300
two | 2000
three | 39999
four | 2000
five | 300
six | 300
seven | 200

<ol start="3" dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-left: 0px;"><p dir="auto" style="box-sizing: border-box; margin-top: 16px; margin-bottom: 16px;">Filter Price by 300 (Data -&gt; Autofilter.)</p></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><p dir="auto" style="box-sizing: border-box; margin-top: 16px; margin-bottom: 16px;">Try to copy text</p></li></ol><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/58852253/172189366-ffa3709a-7e16-4243-8ced-707959650f85.png" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; transition: color 80ms cubic-bezier(0.33, 1, 0.68, 1) 0s, background-color, box-shadow, border-color;"><img src="https://user-images.githubusercontent.com/58852253/172189366-ffa3709a-7e16-4243-8ced-707959650f85.png" alt="image" style="box-sizing: content-box; border-style: none; max-width: 100%; background-color: var(--color-canvas-default);"></a></p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px !important; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Collabora Online Development Edition<br style="box-sizing: border-box;">Version COOLWSD:<br style="box-sizing: border-box;">21.11.4.2<br style="box-sizing: border-box;">LOKit:<br style="box-sizing: border-box;">Collabora Office 21.06.28.1<br style="box-sizing: border-box;">Version COOLWSD:<br style="box-sizing: border-box;">21.11.4.2<br style="box-sizing: border-box;">Version LOKit:<br style="box-sizing: border-box;">Collabora Office 21.06.28.1<br style="box-sizing: border-box;">Works for:<br style="box-sizing: border-box;">Ubuntu 18.04.6 LTS</p>
</body>
</html>

**Comment by Darshan-upadhyay1110** [comment]
Fixed in the latest version.
COOLWSD version: 24.04.6.2 (git hash: 7bb21429)
LOKit version: Collabora OfficeDev 24.04.6.2 (git hash: 321166f)
Served by: Ubuntu 23.10
Server ID: 48c29b42
