### ISSUE TITLE
Cannot select multiple rows / columns with mouse drag

### ISSUE THREAD

**Issue by avatar1024** [CollaboraOnline/online#3745]
**Describe the bug**
Trying to select multiple row or column by dragging the mouse cursor does not work.

**To Reproduce**
1. click on a row / column header
2. stay with the click and drag to attempt to select multiple rows / columns (like in LO calc / Gdocs / OnlyOffice / MS Office, etc.)

**Expected behavior**
The selection get extended to the rows below

**Actual behavior**
Nothing or the row / column gets resized larger

**Desktop (please complete the following information)**
 - OS: KDE Neon
 - Browser: Firefox 94 and Brave
 - Version: CODE 6.4.14 server + Nextcloud Collabora Online app 4.2.3

**Additional context**
I don't know if this is a bug or a missing feature - if the latter then feel free to move this in the feature request section bu this would be strange as selecting multiple rows / columns is a very basic feature of spreadsheets.

**Comment by Ezinnem** [comment]
Reproducible in 6.4.14 git hash:  6ec2992f

**Comment by avatar1024** [comment]
This is still the case on 21.11.1.0.

This seems like a big usability issue compared to other collaborative documents apps (Gdocs, OnlyOffice, etc.) which might also be responsible for other bugs like this one: #4001

**Comment by avatar1024** [comment]
Still the case in 21.11.4

**Comment by avatar1024** [comment]
Is there any plans regarding addressing this? This is such a basic behaviour of spreadsheet software it feels really odd when using collabora.

**Comment by avatar1024** [comment]
Still the same in 22.05.3.1
