### ISSUE TITLE
Add tooltip to hide menu button (compact view)

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#3751]
# Context

we have two UI modes: compact view and tabbed view. You can change the view either via the `coolwsd.xml` or via the UI itself.

## coolwsd.xml

Switch to compact view by changing the value in `<mode>`:
```
      <mode type="string" desc="Controls the user interface style. The 'default' means: Take the value from ui_defaults, or decide for one of compact or tabbed (default|compact|tabbed)" default="default">compact</mode>
      <use_integration_theme desc="Use theme from the integrator" type="bool" default="true">true</use_integration_theme>
    </user_interface
```

## UI

Or switch to compact view (in the case you have it set to tabbed view) by going to View tab > Compact

# Issue

There is a `#tb_editbar_item_fold` button (up/down chevron) that hides the top menu. Add the missing tooltip `Hide menu` and `Show menu` to that button.

![2021-11-30 09_26_43-ws-6932f3ba-1c04-4573-b4e8-562ea98c256c_0 - noVNC](https://user-images.githubusercontent.com/8517736/144011903-df08fbab-8981-4d47-857c-be04f8b9974c.png)

## Code pointers
* button is created in `browser/src/control/Control.TopToolbar.js`
* the button calls `map.uiManager.toggleMenubar();` (from `browser/src/control/Control.Toolbar.js`
* Top menu is hidden or shown in `browser/src/control/Control.UIManager.js`

(Renamed and edit by @pedropintosilva at 17Feb 2023)

**Comment by callmetushar123** [comment]
@Andreas-Kainz I didn't quite get it. What do we have to do, can you give me some directions?

**Comment by pedropintosilva** [comment]
Hi @callmetushar123 I have made it easier to understand and also I have added code pointer. Would you like to work on this?

**Comment by callmetushar123** [comment]
Yes I will working on it.
