### ISSUE TITLE
Editing cursors are out of place when using browser zoom

### ISSUE THREAD

**Issue by juliushaertl** [CollaboraOnline/online#3758]
**Describe the bug**
When using the browser zoom other users editing cursors are out of place if using a different zoom level than 100%

**To Reproduce**
1. Have multiple users editing
2. Change the browser zoom level (e.g. clicking the toolbar and using ctrl+scrollwheel)
3. See that the other users cursors are out of place

Happens on both master, 21.11 as well as 6.4

As seen today in the call with @pedropintosilva

**Comment by Ezinnem** [comment]
Confirmed on COOLWSD 21.11.0.3 git hash: 265c275a

**Comment by Ezinnem** [comment]
Confirmed on COOLWSD 21.11.0.3 git hash: 265c275a

**Comment by eszkadev** [comment]
should be fixed now
