### ISSUE TITLE
ios saving unreliable

### ISSUE THREAD

**Issue by kr4z33** [CollaboraOnline/online#3760]
Trying out Collabora Office via testflight on ios, ran into some kind of issue with saving an ods file on my nextcloud

Version is reported in help/about as  21.06.1.0 and 21.06.4.1

Using the spreadsheet editor on a new ods file: saving to Nextcloud was unreliable, with the following behavior:

I was able to get an early revision saved, good times. After working a while, I noticed the disk icon in the upper left would get a green dot overlaid, consistent with indicating there was unsaved work. After tapping the disk icon, the dot would go away, consistent with an indication that work done to the file was saved. Sounds good. After a few hours working this way. I put the device away for other tasks.

The following day I went to reopen the file to make further edits, and found that only a very early version of the file existed in the Nextcloud storage. apparently tapping the disk icon in Collabora was not actually saving the work, as visual indications in Collabora would have suggested.

I would prefer Collabora to be very noisy about unsuccessful saving and unsaved work and to keep a local cache of recent work to avoid this kind of loss.

**Comment by sebastiaanveld** [comment]
Was testing this also and found is works reliably for me on an iPhone but not using an iPad. On iPad i get an save error when saving the modified file. After the error message appears, the Save button in the Collabora Office App still shows there are changes the need to be saved (blue circle still appears). 

Steps to duplicate:
- Start the Nextcloud App on the iPad
- On an .odt document select from the menu Open In > Collabora Office
- File opens in the local Collabora Office App
- Click the Edit button, make a modification to the document

![image](https://user-images.githubusercontent.com/37268999/224551488-053aeadb-c1c8-4e6a-8624-e6cbf3b4f63c.png)

- From the top menu bar, select the Save button
- Error appears Server ran into a savefailed-error while performing saving (Dutch localized in the screenshot)

![image](https://user-images.githubusercontent.com/37268999/224551499-2646eeeb-c8dd-4933-aa00-d03631e4ca2a.png)

-After a few second the error message goes away automatically, if not clicking the OK button. Mind the Save button still the shows modifications are made that need to be saved (blue circle still shows). The file in Nextcloud does not shows it's updated, but could be this is down after the file in the Collabora App is closed?
- Close the file using the close X-button
- Go back to the Nextcloud App, file shows is modified
- Reopen the file using the Collabora Online/Nextcloud Office just by cicking the file, this makes sure the "updated" file is used that in the App's silo.
- The modification shows up so the file was, despite the shown error, saved correctly.

![image](https://user-images.githubusercontent.com/37268999/224551520-3910eb1b-3565-40f0-a116-5b28ad70623e.png)

If I do the same test:
- Start the Nextcloud App on the iPad
- On an .odt document select from the menu Open In > Collabora Office
- File opens in the local Collabora Office App
- Click the Edit button, make a modification to the document
- From the top menu bar, select the Save button
- Error appears Server ran into a savefailed-error while performing saving (Dutch localized in the screenshot)
- After a few second the error message goes away automatically, if not clicking the OK button.
- The Save button still the shows modifications are made that need to be saved (blue circle still shows). The file in Nextcloud does not shows it's updates
- Now wait for around 100 second, then the blue circle form the Save button disappears.
- Switch to the Nextcloud App, the file now shows it changed less than a minute ago.

iPadOS 16.3.1 on iPad 5th gen (model MP2G2NF/A), language set to Dutch Localization
Nextcloud App 4.7.0
Collabora Office 22.05.10 (22.5.202303070027) in Testflight

**Comment by sebastiaanveld** [comment]
Tested and works for me in Collabora Office 22.05.10 (22.5.202303132008) in Testflight

**Comment by plubius** [comment]
Excellent. I'll close this bug. Please reopen if there are still any issues.
