### ISSUE TITLE
Sidebar button looks misaligned 

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#3766]
**Describe the bug**
This might be a regression or simple a bug coming from some of the rework around those parent elements. The sidebar and the close button are not aligned between each-other. It seems close button is center aligned within the bar but not the sidebar icon

**Expected behavior**
it should be Center aligned 

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots**
![image](https://user-images.githubusercontent.com/65948705/144253058-7d8b26f9-f46f-4122-b0f4-7f61d6a341df.png)

**Desktop (please complete the following information)**
 - Version: Master

**Comment by thebearon** [comment]
Actually, this looks like a branding issue, at least I see no issue in the screenshot here. I'm closing now, but please correct me if I'm mistaken.
