### ISSUE TITLE
Sidebar dropdown and insert field design

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#3770]
**Describe the bug**
In the sidebar we have ordinary left align a label and right align a dropdown menu or an insert field element.

**To Reproduce**
1. open sidebar
2. select an object

**Expected behavior**
if the dropdown menu and the insert field element have the same width the alignment of the sidebar elements would be perfect. 
1. This is easy doable with the .css file, but as the insert field element has a (language specific) unit, it would look perfect, only when the unit will be shown inside the insert field.
2. In additon have an +/- elment left and right to the insert field would make the up/down buttons as they are now easier to select by mouse AND by touch.

**Screenshots before**
![2021-12-01 15_47_01-](https://user-images.githubusercontent.com/8517736/144255870-3de3bd05-96a6-42d8-a932-e12ce4004b49.png)

**Screenshots after**
![2021-12-01 15_47_01-](https://user-images.githubusercontent.com/8517736/144258117-b573e4da-2c53-4857-a14a-160d0a5fdace.png)

**Comment by Andreas-Kainz** [comment]
maybe it's not good to mix two ideas.

This issue is about to have the measurement unit inside the insert feeld.

![2021-12-06 09_12_46-Präsentation1 - PowerPoint](https://user-images.githubusercontent.com/8517736/144810710-94b03a11-eb83-468a-95ec-0e4e445d6d76.png)

have the measurement inside the insert field would make the UI more align.

**Comment by pedropintosilva** [comment]
Yeah maybe for that other issue just visit : https://github.com/CollaboraOnline/online/issues/3324

**Comment by pedropintosilva** [comment]
> maybe it's not good to mix two ideas.
> 
> This issue is about to have the measurement unit inside the insert feeld.
> 
> ![2021-12-06 09_12_46-Präsentation1 - PowerPoint](https://user-images.githubusercontent.com/8517736/144810710-94b03a11-eb83-468a-95ec-0e4e445d6d76.png)
> 
> have the measurement inside the insert field would make the UI more align.

I have no objection to it
