### ISSUE TITLE
click saved time in menubar open in view mode

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#3775]
![2021-12-02 12_10_11-Nextcloud](https://user-images.githubusercontent.com/8517736/144411330-0b8756cf-c2ba-4164-bb62-f5b1470f8242.png)

when click on the saved time, the page switch to the read only mode so all commands, toolbars, sidebar are hidden.

**Comment by Ezinnem** [comment]
Reproducible on COOLWSD version: 21.11.0.5 git hash: abc15917

**Comment by Darshan-upadhyay1110** [comment]
Not reproducible in latest version.

COOLWSD version: 24.04.6.1 (git hash: 9dfee827)
LOKit version: Collabora OfficeDev 24.04.6.1 (git hash: 8b00f3a)
Served by: Ubuntu 23.10
Server ID: 83043426
