### ISSUE TITLE
remove ambiguity

### ISSUE THREAD

**Issue by yashpalgoyal1304** [CollaboraOnline/online#3776]
I know this article is old and so is bound to have outdated and possibly confusing info too (like even stable having same major.minor number as snapshot version mentioned in this fdroid article), but it can still useful 
* if the stable package is described more precisely (e.g. using app id) rather than inherently temporary parameters (latest version), AND
* by mentioning the stable explicitly in the description of app on the repo, AND
* by giving some hint to direct to the stable version in the description of the snapshot app's description

https://www.collaboraoffice.com/releases-en/collabora-office-on-mobiles-supporting-password-protected-documents-and-available-on-f-droid/

![image](https://user-images.githubusercontent.com/19423063/144411587-0c8ddd40-0cab-49c3-acb8-61fda287946b.png)

**Comment by pedropintosilva** [comment]
thanks @yashpalgoyal1304 for taking an interest on Collabora Online and for your input. I think it makes sense to have a more generic article that stays easy to follow no matter the current version. I will pass this on!

CC: @cornouws @SustReal @wget
