### ISSUE TITLE
Toolbar-down: Arrow icons are too harsh

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#3778]
**Describe the bug**
These arrow icon to go prev/next page and search result looked a bit out of place when compared with the other icons and a bit harsh 

**Screenshots**
![image](https://user-images.githubusercontent.com/65948705/144426533-717c44b5-9f07-41c5-b33c-474e1be75ca1.png)

**Desktop (please complete the following information)**
Master

**Additional context**
The culprit might be the combination of very tiny outline with too dark of a colour and the size

**Comment by Andreas-Kainz** [comment]
What I'm also afraid of is, that two different commands use the same icon.
