### ISSUE TITLE
Toolbar-down: Zoom: minus and plus icons are too big

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#3779]
**Describe the bug**
Toolbar-down: Zoom: minus and plus icons are too big and do not share the same dark color as the other icons ( for example the neighbouring magnifying glass)

**Expected behavior**
Maybe a bit smaller and not so dark

**Screenshots**
![image](https://user-images.githubusercontent.com/65948705/144427208-f871d581-e835-4671-a5ce-d948f2376aa0.png)

**Desktop (please complete the following information)**
Master

**Comment by Andreas-Kainz** [comment]
- and + aren't icons they are font elements.
