### ISSUE TITLE
COOL Onboarding

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#3789]
**first draft**
![photo5857392406360602384](https://user-images.githubusercontent.com/8517736/144586496-1a3fc74f-51d7-423d-8463-7dc396d77c7e.jpg)

**code**
```
- browser/images/welcome
- browser/html/cool.html.m4
```

**content**
And for the content I would go according your list
1. Collabora Online 21.11 release
    Show the improved sidebar
2. Mobile UI
    Show the UI of cool on a mobile device with links to the app stored
3. Different Collabora Online versions (enterprise ready) with button to click to the webpages
4. OSS Support use
    buttons to the different channels or the webpage
5. Have fun
    with the new release you have more fun than before

**Comment by Andreas-Kainz** [comment]
@pedropintosilva plase for discuss the layout

@mmeeks maybe for the final review before bring to master and that you are informed

**Comment by Andreas-Kainz** [comment]
**Goals**

- should work on mobile and desktop
- use the cooperate design language from the [collaboraoffice.com](www.collaboraoffice.com) webpage
- show our users what we do and what we offer
- join the community and tweak Collabora Online for there neads.

**Comment by mmeeks** [comment]
Looks very pretty to me =) but really this is Pedro's domain =)

**Comment by Andreas-Kainz** [comment]
we already talked about it. 

My boss always want to be informed about company related stuff, so this is the Information for you Michael.

**Comment by pedropintosilva** [comment]
@Andreas-Kainz could you please add your draft as a comment to the https://github.com/CollaboraOnline/online/issues/3790 ? : )

**Comment by mmeeks** [comment]
Thanks Andreas ! =)
