### ISSUE TITLE
Improve Welcome screen

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#3790]
- [Intro](#intro)
- [What we have](#what-we-have)
  - [Desktop](#desktop)
  - [Mobile](#mobile)
- [Room for improvement](#room-for-improvement)
  - [on Desktop](#room-for-improvement-on-desktop)
  - [on Mobile](#room-for-improvement-on-mobile)
- [CO logo](#co-logo)

<h3 id="intro">Intro</h3>
We now have better revamped welcome screen both on desktop and on mobile. The main direction of any improvement here is to make sure we keep it clean and simple, any over the top elements or extra wording should be carefully thought out with these CTA in mind:

1. Communicate that this is a new release
* Make more discoverable that we do have Apps (Android, ChromeOS, iOS)
  * To get more downloads and users to test those 
2. Communicate the release notes
* In a succinct way (a short paragraph)
* Make more discoverable the web page where all those release notes are at
  * To get more people involved in the insides of CO
    * So to avoid outdated bug reports or questions in the forum
    * So they can share them with everyone else
    * So they can start to test those new improvements/features 
5. Get involved
* Make more discoverable our community website
* Attract more people to contribute and hack in all the different fronts
6. Show that there are an option for enterprise-ready versions
* To decrease the number of unaware CODE users that end up choosing other tools. Basically to about "Oh that's cool but I really need some enterprise/professional version with official support for my company/organization"

Note: very important to use active verbs and to avoid to avoid multiple colors per screen with different elements fighting for attention

<h3 id="what-we-have">What we have</h3>

<h4 id="desktop">Desktop</h4>
https://user-images.githubusercontent.com/65948705/144588044-5e9c0601-9646-414a-ae31-67f2fc327d56.mp4

<h4 id="mobile">Mobile</h4>
https://user-images.githubusercontent.com/65948705/144588040-f48e0fde-2d4f-41aa-b5d4-85ce9a1990de.mp4

https://user-images.githubusercontent.com/65948705/144588043-c9bb34dc-d58e-44e8-8706-cfcb5fdab9b9.mp4

<h3 id="room-for-improvement">Room for improvement</h3>
As seen above there are still room for improvement:

<h4 id="room-for-improvement-on-desktop">Room for improvement on Desktop</h4>
- [ ] Desktop: Next btn: Maybe re-using the buttons from the JSdialogs are not as good as I thought, maybe we can use arrows instead
- [ ] Desktop: Next btn: add hover and press state
- [ ] Desktop: Pref btn: Maybe adding a previous button would be wise
- [ ] Desktop: the bubbles could have an additional discreet CSS animation 

<h4 id="room-for-improvement-on-mobile">Room for improvement on Mobile</h4>
On mobile it's nice that already works almost out of the box and even on landscape but there are some more improvements that could be done:

- [ ] Vex dialog needs some rework regarding the button on landscape mode
- [ ] [bug] Those multiple scroll bars should be easy enough to fix by making sure we do not have hardcoded weird heights somewhere in its parents elements
- [ ] [bug] The indicator does not change the position on mobile

<h3 id="co-logo">CO logo</h3>

Maybe we could ensure that at least the CO logo is visible:

- [ ] Add Initial full dialog animation with CO logo
- [ ] And/or use the logo throughout the welcome dialog; If we would do this then it really needs to be discreet because:
  - User is already using the app he/she knows that, no need to flash the logo in a distasteful size every time
  - Depending on how we do it it would be one more element for the user to scan, and one more element with miss-clicks 

### Where

- browser/images/welcome
- browser/html/cool.html.m4

**Comment by Andreas-Kainz** [comment]
I suggest that the Welcome screen use the collaboraonline.com branding so that you have a visual link between the welcome screen and the webpage (where all the links will link).

![photo5857392406360602384](https://user-images.githubusercontent.com/8517736/144586496-1a3fc74f-51d7-423d-8463-7dc396d77c7e.jpg)

**Comment by Andreas-Kainz** [comment]
How can I force to run the welcome screen?

**Comment by meonkeys** [comment]
> How can I force to run the welcome screen?

https://github.com/CollaboraOnline/online/issues/2021#issuecomment-823952743

**Comment by meonkeys** [comment]
Also related: #4489
