### ISSUE TITLE
Mobile select DrawText, Graphic, Shape, ... is difficult or not possible

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#3803]
**Describe the bug**
On mobile it's not possible to select an DrawText element I mean the Text inside the Draw element.

**To Reproduce**
1. Go to 'writer'
2. Click on 'DrawText' element
3. Prepare to select the text inside the 'DrawText' element

It's also very difficult to select an Draw|DrawLine|3DObject|MultiObject|Graphic|DrawFontwork element.

**Expected behavior**
With double click or long click on the text, the text should be in the focus and can be edited.

**Actual behavior**
You can't select the text from a 'DrawText' element, so it's not possible on mobile to edit the text.

**Screenshots**
![image](https://user-images.githubusercontent.com/8517736/145107228-5fc3cc95-489f-45d5-906f-39fff258fb45.png)

**Desktop (please complete the following information)**
 - Browser: chrome, firefox

**Comment by Andreas-Kainz** [comment]
I tested and if I make the Text higher and bold, I can select and edit it. 

So it look like that the selection need a bit of tuning.

**Comment by Ezinnem** [comment]
This does not seem reproducible on my end. I can select and edit the text in the shape.

**Comment by Andreas-Kainz** [comment]
if it's not reproducible, than it's fine.
