### ISSUE TITLE
Sidebar Color Dropdown text is to long

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#3804]
Sidebar color drop down menu need an adjustment cause the text is sometimes to long (even in English).

![image](https://user-images.githubusercontent.com/8517736/145109838-0f4c22f1-b7ab-47d2-80f5-cc2ab1b02d4b.png)

**Comment by Ezinnem** [comment]
@pedropintosilva

**Comment by Andreas-Kainz** [comment]
I think I can fix this bug myself.

**Comment by Ezinnem** [comment]
This issue seems to have been fixed.

It does not seem reproducible using COOLWSD version: 21.11.2.1 git hash: [55dc6af](https://github.com/CollaboraOnline/online/commits/55dc6af)
