### ISSUE TITLE
Mobile calc: Hide BottomToolbar when cell and inputbar has focus

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#3808]
**Describe the bug**
Hide BottomToolbar in writer mobile when a cell is selected and the focus is at the inputbar.

**To Reproduce**
1. Go to 'calc - mobile'
2. Click on 'cell'

**Expected behavior**
When selected a cell, BottomToolbar isn't needed, cause you can't edit a cell input. Inputbar and the keyboard has the focus everything else isn't needed.

**Actual behavior**
when selected an cell item the toolbar is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/8517736/145117865-81e46f6c-255d-474c-a057-f4849b81109f.png)

**Desktop (please complete the following information)**
 - Browser: [e.g. chrome, firefox]

**Comment by Ezinnem** [comment]
@pedropintosilva

**Comment by Darshan-upadhyay1110** [comment]
![image](https://github.com/user-attachments/assets/c8c753c1-1b49-4808-87dc-5a3f56bddc8a)
