### ISSUE TITLE
Enable Save As feature for document formats that can be viewed but not edited/saved (VSD, VSDX etc) to ease edit workflow

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#3817]
**Is your feature request related to a problem? Please describe.**
With LO one can open and (like) Visio VSD/VSDX file which is then opened in Draw. You can start editing but but when hitting the Save buttot you are forced to write the result in ODG. That's fine as we do not support writing to the originally opened document format.

In COOL/CODE such document format that can be opened, but not saved to, is opened in View mode with limited menu options.

![afbeelding](https://user-images.githubusercontent.com/37268999/145252881-a28d92a1-c345-416d-8686-d9a2c915c87d.png)

You can use the Download As> save to ODG, then upload the document to Nextcloud (or other file sharing solution). This is not the most friendly solution for end users, like ask a not so tech savvy end user to do such to be able to quick edit such document...

**Describe the solution you'd like**
What would better here is to leverage the Save As function that generally is available in the menu. As an example hitting the Save As in other document that writes the document with the newly selected name to the file store, then silently opens it in the background for the user so one can start editing in the new document.

With that in mind I think it would be nice to:

- When a document is opened in View mode, enable the Save As feature in the File menu so the user can Save As to a format that COOL/CODE supports for editing. In case of my VSD/VSDX file that would be and ODG.
- The document then in backend is loaded and the module (Draw in my case) showd the Notebookbar so the user can start editing.
- To make it more easy for the user, or more obvious one has to perform a Save As before editing is possible with the opened document format an Edit document-icon should be visible for the user. Once clicked on the Edit icon, the Save As dialog should be shown as desciped in the first step. 

Example: Open a PPTX, click Save As opens the dialog to enter a new file name. Likewise clicking the Edit button would show this/a similar dialog making it clear we need the user to save the file before the editing can be started:

![afbeelding](https://user-images.githubusercontent.com/37268999/145257285-66708606-6e08-4849-b12e-ce8fff01d204.png)

The Saving in the background progress bar is shown and the new document is loaded for the user:

![afbeelding](https://user-images.githubusercontent.com/37268999/145257632-14898460-3c70-4c5d-865d-c34ee58e5919.png)

The Saved document is loaded and the user can start editing:

![afbeelding](https://user-images.githubusercontent.com/37268999/145257764-62500eb0-03fa-428c-bf96-a5e9784c3d8e.png)

**Describe alternatives you've considered**
The Alternative is having the user use Download As, Save locally, the upload to the file sharing solution, then reopend the document again. Well, this is doable for me but not sure if my family or customers agree with that:) 

**Additional context**
This worksflow keeps the source and destination document in the file sharing datastore withoud the need of downloading the document locally first, to be able to edit. Also it makes it more clear we can edit siuch documents after saving it first to a supported document format.

**Comment by pedropintosilva** [comment]
Thank you @sebastiaanveld for reporting this up, I have good news!
We already have some document type mappings in places (were a non-editable document format is mapped/possible to be saved as a regular editable file) such as CSV to ODF but we were missing some other formats. Plus we didn't have a nice generic solution that would be easy to expand by "just" add another document format mapping uuuntil @merttumer patch : https://github.com/CollaboraOnline/online/pull/3749

So now with that in place adding more of those should not be that difficult : )

I will keep you posted once more of those get in :+1:

**Comment by pedropintosilva** [comment]
Oh BTW this PR https://github.com/CollaboraOnline/online/pull/3823 also needs to enter for this to be possible on Android  as well
