### ISSUE TITLE
Calc Sidebar: Cell Appearance alignment

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#3835]
The idea is to rearrange the Cell Appearance alignment section at the calc sidebar

**before**
![image](https://user-images.githubusercontent.com/8517736/145457168-f3d1e164-19f2-4590-a38a-6037b1950c82.png)

**proposal**
![image](https://user-images.githubusercontent.com/8517736/145456962-1d273f04-13c6-4b36-a05c-e6a4970f8348.png)

I know I can do the change at LibO, and maybe it's also a good idea there, but first I'd like to have some feedback here.

**Comment by kallejre** [comment]
Not sure, if it's same issue as I'm experiencing, but screenshot looks similar enough i won't create duplicate. When editing in docx-file with lot of tables and modifying several tables one-by-one, then after selecting next table and interacting (sometimes clicking on button, sometimes just hovering mouse over) with side-panel, then the vertical text alignment panel shifts roughly 10-15 pixels down. On screenshot below, situation has got worse after about 5 iterations.

![pilt](https://user-images.githubusercontent.com/22601238/147373922-2d6b320a-1954-425a-a8c9-135aecad4b83.png)

Steps to reproduce: 

1. Create table into word document and insert some text content (I don't know if it matters, but i was using some merged cells).
2. Copy-paste the table some times.
3. Select table by click-and-drag over the cells.
4. Adjust text's vertical alignment
5. Repeat steps 3 & 4 with different table. Do not close side panel, do not deselect current table. Just use mouse wheel for scrolling and then click-and-drag to select next table.

Looks like issue can also replicated by simply alternating between clicking align-to-top and align-to-middle buttons on same panel.

Using COOLWSD version 21.11.0.6 (1e92cc5); Collabora Office 21.06.10.1 (d382e7c); Served by: Ubuntu Core 1852f86478 (came with Ubuntu Snap's Nextcloud container)

**Comment by Andreas-Kainz** [comment]
Issue is known and we work on a fix. Thanks for the report

**Comment by thebearon** [comment]
Let's add @eszkadev and @pedropintosilva to the loop.

**Comment by Andreas-Kainz** [comment]
Cell Appearance was fixed with #4160

**Comment by Andreas-Kainz** [comment]
> Not sure, if it's same issue as I'm experiencing, but screenshot looks similar enough i won't create duplicate. When editing in docx-file with lot of tables and modifying several tables one-by-one, then after selecting next table and interacting (sometimes clicking on button, sometimes just hovering mouse over) with side-panel, then the vertical text alignment panel shifts roughly 10-15 pixels down. On screenshot below, situation has got worse after about 5 iterations.
> 
> ![pilt](https://user-images.githubusercontent.com/22601238/147373922-2d6b320a-1954-425a-a8c9-135aecad4b83.png)
> 
> Steps to reproduce:
> 
>     1. Create table into word document and insert some text content (I don't know if it matters, but i was using some merged cells).
> 
>     2. Copy-paste the table some times.
> 
>     3. Select table by click-and-drag over the cells.
> 
>     4. Adjust text's vertical alignment
> 
>     5. Repeat steps 3 & 4 with different table. Do not close side panel, do not deselect current table. Just use mouse wheel for scrolling and then click-and-drag to select next table.
> 
> 
> Looks like issue can also replicated by simply alternating between clicking align-to-top and align-to-middle buttons on same panel.
> 
> Using COOLWSD version 21.11.0.6 ([1e92cc5](https://github.com/CollaboraOnline/online/commit/1e92cc5cff992ab74985db5c08c1a0a775492819)); Collabora Office 21.06.10.1 (d382e7c); Served by: Ubuntu Core 1852f86478 (came with Ubuntu Snap's Nextcloud container)

was discussed in #3805
