### ISSUE TITLE
Alignment buttons in mobile-wizard changing position

### ISSUE THREAD

**Issue by eszkadev** [CollaboraOnline/online#3849]
**Describe the bug**
Alignment buttons in Impress mobile-wizard are changing positions.

https://user-images.githubusercontent.com/5307369/145783600-b04d2f2b-9be8-4947-979d-7b0075adfdb3.mp4

**To Reproduce**
Open Impress in mobile view eg. in Chrome responsive mode. Select some textbox, go to mobile-wizard -> paragraph.
Use Alignment buttons - you will see they will change positions:

**Expected behavior**
Icons should stay at the same position all the time.

Browser: Firefox
Branch: master

**Comment by eszkadev** [comment]
cc @pedropintosilva @Andreas-Kainz

**Comment by eszkadev** [comment]
it's some recent regression causing CI to fail, here it was ok: https://github.com/CollaboraOnline/online/commit/5d10fb3950f54f4b99ae2054bf42f91c1cc0e085

**Comment by Andreas-Kainz** [comment]
There has to be also an fix on the desktop sidebar see #3805

So I will check and fix it on mobile and desktop.

**Comment by eszkadev** [comment]
it seems it's regression from: https://github.com/CollaboraOnline/online/commit/782fada6c9f326f276b393a7f5e9fca759121e7c
we probably lost some css rule due to id renaming...

**Comment by eszkadev** [comment]
should be ok now
