### ISSUE TITLE
Calc: Pasted content of cells does not show up (immediately)

### ISSUE THREAD

**Issue by SustReal** [CollaboraOnline/online#3853]
**Describe the bug**
When copying content from one cell to another, the pasted content does not show up immediately in the new cell. It is visible in the formulae bar, and will only show up in the cell if the document is manually saved. 

**To Reproduce**
1. Open a spreadsheet
2. Write (text) content into a cell
3. Copy and paste the content into an empty cell
4. See error - no pasted content visible in cell before a manual safe

**Expected behavior**
The pasted conten should be visible in the cell without delay

**Actual behavior**
The pasted content only appears after a manual save or long delay

**Screenshots**
---

**Desktop (please complete the following information)**
 - OS: Ubuntu
 - Browser: firefox
 - Version: Collabora Online 21.11.0.5

**Smartphone (please complete the following information)**
 - 

**Additional context**
-

**Comment by pacomedina** [comment]
Same issue here.. Tried with different browsers and different document type (ODS or XLSX).
Also, if I move a column size or change text, it's only when I click save or wait that the content will appear or change.

Using the docker version of collabora. Everything was working before update.

**Comment by pacomedina** [comment]
Back to version collabora/code:6.4.14.3 it's working fine.

**Comment by Ezinnem** [comment]
Reproducible on COOLWSD 21.11.0.5 git hash: 7566de3a

**Comment by thebearon** [comment]
Should be fixed by the following commit, coming in the next build: https://gerrit.libreoffice.org/c/core/+/126864
Thanks for reporting.
