### ISSUE TITLE
Browser: add file path tooltip so that the user is aware of it

### ISSUE THREAD

**Issue by alessioalex-1and1** [CollaboraOnline/online#3880]
**Is your feature request related to a problem? Please describe.**
When embedding COOL into a project the file path in the URL won't be shown anymore so the user might be confused as to where he loaded the file from.

**Describe the solution you'd like**
Display the file path as a tooltip when he hovers over the file name.

**Describe alternatives you've considered**
none

**Additional context**

How it could look like:

![screenshot](https://cldup.com/vhJtHRtSce.png)

**Comment by Ezinnem** [comment]
@pedropintosilva
