### ISSUE TITLE
iOS app: status bar of the app not visible due to iOS "keyboard bar"

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#389]
**Describe the bug**
When I open a document (e.g.) writer in 6.4.0 (5) with an attached hardware keyboard I can't see the status bar of the app (with e.g. the search field) - the iOS "keyboard bar" is visible instead. This is probably some sort of a regression as it was already a topic in the 4.2.x version, see: https://bugs.documentfoundation.org/show_bug.cgi?id=129380
With 6.4.x (or is it because of an iOS update?) it seems to be an issue again.

**To Reproduce**
1. Open a document using the iOS app
2. Try to reach the search field which should be in the bottom left corner

**Expected behavior**
The status bar should be visible, I should be able to enter something into the search field.

**Actual behavior**
The status bar of the app is not visible because the iOS "keyboard bar" is displayed above it.

**Screenshots**
<img width="1112" alt="keyboard_bar_over_status_bar" src="https://user-images.githubusercontent.com/1211300/96896653-0f53e500-148e-11eb-80d6-0ff3751eb475.png">

**Tablet**
 - OS: iOS, 14.0
 - Version: 6.4.0. (5)

**Additional context**
This already happend in 4.2.x, see: https://bugs.documentfoundation.org/show_bug.cgi?id=129380

**Comment by thebearon** [comment]
I can confirm. Interestingly it's fine when using online together with the Nextcloud app, but also buggy within the browser (Safari).

**Comment by tml1024** [comment]
Also this issue goes away if I revert https://gerrit.libreoffice.org/c/online/+/103714 .

**Comment by tml1024** [comment]
Issue was resolved by above revert. (We then lost the suggestions, which as such could be seen as useful functionality, but oh well, having such should be filed as an enhancement request.)
