### ISSUE TITLE
User settings option

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#3899]
Add options for users and administrators to switch between
- toolbar layouts (classic, notebookbar)
- UI language
- dictionary languages
- RTL / LTR document
- show/hide sidebar

One good reason is that it's easier to test cool.

**Comment by Ezinnem** [comment]
@pedropintosilva @eszkadev

**Comment by eszkadev** [comment]
I don't understand. Where to add these options?
Integrator can specify such options, eg. by adding some parameters to the URL like "&lang=de" or ui_defaults which can open notebookbar or classic mode

**Comment by avatar1024** [comment]
I imagine it is meant to say in the UI where those options are currently missing.
