### ISSUE TITLE
iOS app: hamburger menu seems to show "below" notebook bar

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#390]
**Describe the bug**
The hamburger menu which can be opened by taping on the hamburger menu in the upper right corner seems to be displayed below the notebookbar in the iOS app.

**To Reproduce**
1. Open a document in the iOS app
2. Tap on the hamburger menu in the upper right corner

**Expected behavior**
The menu should be shown (and be visible)

**Actual behavior**
The menu seems to be rendered below the notebookbar

**Screenshots**
<img width="1112" alt="hamburger_menu_below_notebookbar" src="https://user-images.githubusercontent.com/1211300/96898640-40cdb000-1490-11eb-8e36-ed44821afae3.png">

**Tablet**
 - OS: iOS 14.0
 - Version: 6.4.0 (5)

**Comment by thebearon** [comment]
@pedropintosilva  's commit works for me, this is fine in 6.4.0 (11). Please retest.
