### ISSUE TITLE
iOS App: not able to move picture on a slide

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#3926]
**Describe the bug**
I can't find an easy way to move a picture on a slide using a finger.

**To Reproduce**
1. Open a slide deck using the iOS app
2. Add a slide and add a picture to it using Insert > Image ...
3. Try to move the picture on the slide using a finger

**Expected behavior**
The picture should be moveable using a finger

**Actual behavior**
It's not possible to move the picutre (resizing/rotating works)

**Tablet**
 - Device: iPad
 - OS: iPadOS 14.8
 - Version: 21.11.1

**Comment by tml1024** [comment]
Does it work when using a similarly fresh version of Collabora Online in Safari on iOS?

**Comment by nikslor** [comment]
It works using Safari and the online version on staging.eu.collaboraonline.com; so it seems, it's iOS app specific (or I'm doing dumb things).

**Comment by nikslor** [comment]
Hmmm now it works in the iOS app too.. :/
I made an update to iPadOS 15 in between so can't say if this helped or if something else was the issue.

Sorry for the noise, I'll close this issue.
