### ISSUE TITLE
Cannot paste from other sources

### ISSUE THREAD

**Issue by frankknarf** [CollaboraOnline/online#3928]
**Describe the bug**
Cannot paste from other sources. 
Even when i copy the URL from the browser i can't paste it in a document, spreadsheet or presentation.
(I can only paste if it is copied from the file itself so that is useless).

**To Reproduce**
1. open a document, spreadsheet or presentation.
2. copy the URL from your browser for example.
3. try to paste it in the document, spreadsheet or presentation using the recommended menthod. Eg. CTRL+V.

**Expected behavior**
I expect that the copied URL is pasted in to the document, spreadsheet or presentation.

**Actual behavior**
Nothing is pasted or when you copied within the file previously that is pasted.

**Version**
Nextcloud 22.2.3
Collabora Online 4.2.3
Collabora Online - Built-in CODE Server 21.11.6

ALL platforms:
I tested:

**Desktop**
 - OS: Windows 10 20H2
 - Browser: Firefox 95.0.2 (64-bits), Chrome 97.0.4692.71 (64-bits)

**Smartphone**
 - Device: Android 10 and 11
 - OS: LineageOS 17.1 and 18.1
 - Browser: Firefox 96.0.0-beta.5 and NextCloud App 3.18.1

**Comment by Ezinnem** [comment]
I can paste texts from the browser to the writer file using COOLWSD 21.11.1.0 git hash: [4d625f5a](https://github.com/CollaboraOnline/online/commits/4d625f5a).

@frankknarf, please can you test again using a more recent version?

**Comment by frankknarf** [comment]
I have now updated everything I could find.
Collabora Online   5.0.1
Collabora Online - Built-in CODE Server 21.11.6

NextCloud 23.0.1 RC1

And i have still the same problem.
I can copy and paste within the document. But i can't paste the url from the browser in a document e.g.

**Comment by Llazcanoster** [comment]
Hi all,
same problem, cannot paste from outside Collabora

COOLWSD: 21.11.2.4
LOKit: Collabora Office 21.06.20.1 
Ubuntu Server 20.04.4 LTS
Nextcloud 23.0.3

Is there a log or something I can help?

**Comment by dinosmm** [comment]
I am having the same issue (I think).

I cannot paste text or images copied from another tab or program.
However, I *can* paste screenshots taken with the Windows snipping tool - this is the only thing that seems to be pastable.

This is the case both on Chrome and Firefox for me.

**Comment by Ezinnem** [comment]
This issue is not reproducible on my end.

Please can you share a screen recording showing the issue?
That may be helpful in investigating the problem.

**Comment by corincorvus** [comment]
@Ezinnem 
Here is a Video. I everytime try Strg-V. 
https://www.youtube.com/watch?v=VNHlzPtduNY

**Comment by Llazcanoster** [comment]
Indirectly my problem has been solved, I can now copy and paste from outside Collabora.

I recently moved the Nextcloud instance from xx.ddns.net/nextcloud/index.php to new-xx.ddns.net/index.php.

And I have included only one change in apache2 -> sites-enabled -> nextcloud.conf, which is "Options -Indexes".

I leave below the file in case by comparison it can be of help to someone:

    <IfModule mod_ssl.c>
    <VirtualHost new-xxxx.ddns.net:443>
         ServerAdmin info@new -xxxx.com
         DocumentRoot /var/www/nextcloud/
         ServerName new-xxxx.ddns.net
         ServerAlias new-xxxx.ddns.net
         SSLEngine on
         SSLCertificateFile xxxxxx
         SSLCertificateKeyFile xxxxxxx
    #########################################################################################
    # Apache2 reverse proxy configuration for Collabora Online
    # Internet <-- SSL --> Reverse Proxy <-- No SSL --> coolwsd
    # Make sure that you enable the following Apache2 modules: proxy, proxy_wstunnel, and proxy_http.
    # Create a virtual host for Collabora Online and include this configuration file.
    #########################################################################################
      Options -Indexes
      # Encoded slashes need to be allowed
      AllowEncodedSlashes NoDecode
      # keep the host
      ProxyPreserveHost On
      # static html, js, images, etc. served from coolwsd
      # browser is the client part of Collabora Online
      ProxyPass           /browser http://serverIP:port/browser retry=0
      ProxyPassReverse    /browser http://serverIP:port/browser
      # WOPI discovery URL
      ProxyPass           /hosting/discovery http://serverIP:port/hosting/discovery retry=0
      ProxyPassReverse    /hosting/discovery http://serverIP:port/hosting/discovery
      # Capabilities
      ProxyPass           /hosting/capabilities http://serverIP:port/hosting/capabilities retry=0
      ProxyPassReverse    /hosting/capabilities http://serverIP:port/hosting/capabilities
      # Main websocket
      ProxyPassMatch "/cool/(.*)/ws$" ws://serverIP:port/cool/$1/ws nocanon
      # Admin Console websocket
      ProxyPass   /cool/adminws ws://serverIP:port/cool/adminws
      # Download as, Fullscreen presentation and Image upload operations
      ProxyPass           /cool http://serverIP:port/cool
      ProxyPassReverse    /cool http://serverIP:port/cool
      # Compatibility with integrations that use the /lool/convert-to endpoint
    #########################################################################################
    #End reverse proxy Collabora
    #########################################################################################
        <FilesMatch \.php$>
            SetHandler "proxy:unix:/var/run/php/php7.4-fpm.sock|fcgi://localhost"
        </FilesMatch>
    </VirtualHost>
    <Directory /var/www/nextcloud/>
         Options +FollowSymlinks
         AllowOverride All
         Require all granted
    <IfModule mod_dav.c>
         Dav off
    </IfModule>
         SetEnv HOME /var/www/nextcloud
         SetEnv HTTP_HOME /var/www/nextcloud
    </Directory>

**Comment by Llazcanoster** [comment]
> Okay i use nginx reverse proxy. Any idea what i need to add for testing?

Nop, sorry, I have'nt experience with engine x
But I'm sure someone will eventually figure it out

**Comment by graphius** [comment]
Confirm adding `Options -Indexes` solved copy paste issue with Apache on ubuntu server.
