### ISSUE TITLE
Notebookbar tabs overlap with other buttons on small screensize

### ISSUE THREAD

**Issue by Rash419** [CollaboraOnline/online#3935]
**Describe the bug**
Notebookbar tabs overlap with other buttons on small screensize

**To Reproduce**
1. Start online with Notebookbar UI and select some small screensize

**Screenshots**
![image](https://user-images.githubusercontent.com/26241069/148502321-a4750920-9b15-48f1-b0d7-e943e8c8058c.png)

**Comment by lpranam** [comment]
once this issue is resolved revert this commit: 95fc85e
