### ISSUE TITLE
Time showing in comment/annotation is wrong on calc (ok in writer)

### ISSUE THREAD

**Issue by BigTwoProduction** [CollaboraOnline/online#3947]
Hello,

I've already open an issue for this here https://github.com/CollaboraOnline/online/issues/3348
It's was fixed but now it's happens again.

Version COOLWSD : 21.11.0.6 git hash: 1e92cc5
Versison LOKit :Collabora Office 21.06.10.1 git hash: d382e7c
Servi par : Ubuntu 18.04.6 LTS f877c3fe

Any idea why @Ezinnem ?
Best regards,
Jordan

**Comment by Ezinnem** [comment]
It could have been that regression occurred.


I tested again and could not reproduce on COOLWSD version: 21.11.1.4 git hash: [535278f5](https://github.com/CollaboraOnline/online/commits/535278f5)

@BigTwoProduction, please can you test again?

**Comment by BigTwoProduction** [comment]
@Ezinnem ,Yes of course, let me compil the lastest from source.
I think I can make you a feedback in 2 hours.

**Comment by BigTwoProduction** [comment]
@Ezinnem , I can confirm this issue can no longer be reproducible in lastest docker images from https://hub.docker.com/r/collabora/code
Version COOLWSD :
21.11.1.4 git hash: 739da71
Versison LOKit :
Collabora Office 21.06.13.1 git hash: 242d275
Servi par : Ubuntu 18.04.6 LTS 0a61f89c

And I can not reproduce on my compiled docker image from source

Version COOLWSD :
21.11.1.4 git hash: 535278f5
Versison LOKit :
Collabora Office 21.06.13.1 git hash: 89a98df
Servi par : Ubuntu 20.04.3 LTS 4d6f4edd

Result:
![Img_2](https://user-images.githubusercontent.com/19799334/151806232-5c9f2a1d-3ce2-4dc2-bb5b-a219235f948c.PNG)
