### ISSUE TITLE
automatic update of table of content

### ISSUE THREAD

**Issue by ferdiga** [CollaboraOnline/online#3954]
**Is your feature request related to a problem? Please describe.**
after inserting a table of content it is necessary to manually refresh to be sure that all changes in the structure are represented in the table of content

**Describe the solution you'd like**
automatic update before print/send/save to make sure that the table of content is in sync with the document

**Describe alternatives you've considered**
none - manual update is not user friendly - too easy to forget 
optional a popup should ask "do you want to update the table of content?"
I assume nearly 100% of the answers will be YES.

**Additional context**
good office software should support the user and avoid creating / saving / printing inconsistent documents.

**Comment by gitgt** [comment]
There is 10-years old request for LibreOffice TDF#44448 to add option to auto-update Table of Contents. 
This one depends on that.

**Comment by smehrbrodt** [comment]
Not a duplicate of #3590 - that one was about manual update via context menu not working. This one is about automatic update which needs to be evaluated.

**Comment by rpear** [comment]
Maybe this is just my experience:  Often, but not always, after an edit in a document, I cannot click on ToC headings to jump to a section pages below in a document, they are not clickable links again until I do a manual "Update ToC". I'll try to make this reproducible.
