### ISSUE TITLE
Add user toggle for the ui mode to switch while editing

### ISSUE THREAD

**Issue by juliushaertl** [CollaboraOnline/online#3955]
**Is your feature request related to a problem? Please describe.**
Users have different preferences on the ui mode to either use the notebookbar or the classic toolbar.

**Describe the solution you'd like**
An option to switch while editing a document between the two modes. E.g. through the Menu

View > Switch to classic toolbar

or
 
View > Switch to notebook bar

**Describe alternatives you've considered**
A user setting on the integration side could be used to store the default, but immediate switching would be more intuitive.

**Additional context**
This issue is the outcome of previous discussion with @jancborchardt and @pedropintosilva

**Comment by Ezinnem** [comment]
@eszkadev @pedropintosilva, please can you take a look sometime?

**Comment by eszkadev** [comment]
`this._map.fire('changeuimode', {mode: msg.Values.Mode, force: false});`   from browser/src/map/handler/Map.WOPI.js
switches the mode.
for more info see: browser/src/control/Control.UIManager.js   `onChangeUIMode`

**Comment by eszkadev** [comment]
Switching the mode should also notify the integrator by post message. In UIManager we should send in  `onChangeUIMode`:
eg. `map.fire('postMessage', {msgId: 'UI_ChangedMode', args: {Mode: 'notebookbar'}});`
