### ISSUE TITLE
No option to split the table cells in classic mode main menu

### ISSUE THREAD

**Issue by Rash419** [CollaboraOnline/online#3964]
**Describe the bug**
In classic mode, we don't have Split Cells menu in Table option of main menu
But we have in sidebar so this not huge issue but it is inconsistent wiht notebookbar

**To Reproduce**
1. Add table in classic mode
2. Click on Table on main menu

**Comment by Ezinnem** [comment]
Confirmed in COOLWSD version: 21.11.1.4 git hash: [535278f5](https://github.com/CollaboraOnline/online/commits/535278f5)

**Comment by Darshan-upadhyay1110** [comment]
Now we have split cells in classic menu as well

![image](https://github.com/user-attachments/assets/7ed9763f-349f-428e-b0eb-9b282735b0c8)

COOLWSD version: 24.04.6.1 (git hash: 9dfee827)
LOKit version: Collabora OfficeDev 24.04.6.1 (git hash: 8b00f3a)
Served by: Ubuntu 23.10
Server ID: 83043426
