### ISSUE TITLE
Open CSV or TSV files in Collabora Online integrated with Nextcloud

### ISSUE THREAD

**Issue by marado** [CollaboraOnline/online#3984]
**Is your feature request related to a problem? Please describe.**
Collabora Online supports opening CSV and TSVs. However, if a Nextcloud+Collabora user tries to open a CSV or TSV, it will open up in the text editor instead of using Collabora.

**Describe the solution you'd like**
Trying to open the CSV or TSV file should open up Collabora (showing the import options, probably).

**Describe alternatives you've considered**
Nowadays, one has to download the CSV or TSV, convert it to ODS locally (assuming they have Collabora, LibreOffice or another program that does the conversion locally), and then upload the converted file, so they can finally edit it on Collabora.

**Additional context**
This was tested (and isn't working) on:
```
Nextcloud Office
COOLWSD version:
21.11.0.6 git hash: 
1e92cc5
LOKit version:
Collabora Office 21.06.10.1 git hash: 
d382e7c
Served by: Debian GNU/Linux 10 (buster) 
21fb1cdf
"Slow Proxy"

Copyright © 2021, Collabora Productivity Limited.
```

**Comment by pedropintosilva** [comment]
@marado Thanks for reporting it! It seems to be a known issue from default mimetypes on NC side. In today's community meeting we have discussed that with @juliushaertl : https://forum.collaboraonline.com/t/collabora-online-weekly-meeting-55/805#nextcloud-bits-julius-9

**Comment by juliushaertl** [comment]
@jancborchardt What do you think about always default opening CSV in Collabora as long as we don't have a way to specify user preferences for file actions? I think this is a much more sane default than displaying them in the plain text editor.

**Comment by jancborchardt** [comment]
> @jancborchardt What do you think about always default opening CSV in Collabora as long as we don't have a way to specify user preferences for file actions? I think this is a much more sane default than displaying them in the plain text editor.

For sure, if Collabora is installed, makes much more sense to use that for opening CSV files. :)

**Comment by juliushaertl** [comment]
FYI we have addressed this in https://github.com/nextcloud/text/pull/2448 to only use the text app if Collabora is not available.

**Comment by pedropintosilva** [comment]
^ already backported to stable23 and stable24 :rocket:

**Comment by pedropintosilva** [comment]
re-opening (kinda miss another status for each issue...) adding testing tag

**Comment by timur-g** [comment]
Not sure why this is open, CSV opens with Collabora Online in NC.

**Comment by BiglifeMatt** [comment]
It will not open csv for me in Collabora Online in NC 27.  It opens the Text Import window and an error box pops up in front of that saying "cmd=blockingcommandstatus kind=nodocloaded".  I can close that message but if I select OK on the Text Import window, the window remains and nothing loads.  If I try to open using the Nextcloud mobile app, it just opens in the NC text editor not Collabora.
