### ISSUE TITLE
iOS app: cursor keys on a hardware keyboard seem not to work

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#399]
**Describe the bug**
Cursor keys on the hardware keyboard seem not to work in many places in 6.4.0. For example:
* move the cursor in a writer document
* move the cusor in a tunneled dialog

However it seems to work in a spreadsheet document.

Regarding the tunneled dialogs: using the cursor keys in tunneled dialogs is sometimes useful. One example I encountered: Format > Paragraph... > Tabs > Position
It's quite hard to move the cursor to a specific position inside this field using the finger, the cursor key on my hardware keyboard would help here.

**To Reproduce**
1. Open writer document
2. Use the cursor keys on a hardware keyboard to move the cursor

Or (for tunneled dialogs):

1. Open writer document a tunneled dialog
2. Click into an input field
3. Use the cursor keys on a hardware keyboard to move the cursor in the field

**Expected behavior**
The cursor key should work and move the cursor

**Actual behavior**
The cursor keys don't move the cursor

**Tablet**
 - OS: iOS 14.1
 - Version: 6.4.0 (5)

**Additional context**
I use an attached Apple Smarty Keyboard on my iPad.

**Comment by tml1024** [comment]
Been working on this today.

**Comment by tml1024** [comment]
If I revert https://gerrit.libreoffice.org/c/online/+/103714 then they work. But then I can't type into tunnelled dialogs with the hw keyboard. I *think* it would make more sense to fix the latter problem, though. After all, the commit message for https://gerrit.libreoffice.org/c/online/+/103714 says "this doesn't make sense".

**Comment by tml1024** [comment]
Fun fact: I am now tempted to remove the CollaboraOnlineWebViewKeyboardManager thing completely... seems that possibly it causes more problems than it fixes.

**Comment by mmeeks** [comment]
I was surprised that it worked so easily TBH =) How do we persuade the browser not to have it's own keyboard integration and/or to integrate with ours - can we completely re-direct all keyboard events into the browser through us ? or do some slip past us ? how do we get events into browser controlled dialogs vs. the app which we control =)

**Comment by tml1024** [comment]
This probably can be closed now, was fixed by the above revert.
