### ISSUE TITLE
iOS app: button "Online Help" does not work

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#400]
**Describe the bug**
The button "Online Help" (menu "Help" in the notebookbar) in the iOS app does not work. In contrast the button "Report an issue" seems to work and opens a browser window pointing to the GitHub issues. I believe "Online Help" should point to a similar page (not sure which one).

**To Reproduce**
1. Open a writer document in the iOS app
2. Menu > Help
3. Tap on "Online Help"

**Expected behavior**
The online help should open in a browser.

**Actual behavior**
Nothing happens.

**Tablet**
 - OS: iOS 14.1
 - Version: 6.4.0 (5)

**Comment by tml1024** [comment]
I wonder if "Online Help" is supposed to mean "Help for Online", or "Help that is 'online', i.e. viewed from the Internet", or maybe even "Help that is 'online', i.e. always available (and in the app case bundled with the app)"?

**Comment by nikslor** [comment]
I believe, the user looks for help about this app and I believe both ways "help that is online (opens a tab in the browser)" or "help that is bundled with the app (works offline but probably opens a browser too?)" would be acceptable/fine.

Btw. I'm happy to write some help content. It would be nice, if we would could have a ~simple editor where at least text + pictures are simple to add/edit and can be version specific.

**Comment by tml1024** [comment]
After some investigation: What the code attempts to open is a HTML page through https, from the same "server" that the web page containing the Collabora Online loleaflet.html has been opened from. In the iOS (and Android) app case, there of course is no such "server", and some modifications are needed both to the JavaScript and Objective-C++ (and, presumably, to the Java in the Android app case).

**Comment by tml1024** [comment]
But even if I modify the code so that it does attempt to open a file URL for the loleaflet-help.html (using the same API as is used to open the "Report and issue" URL), it fails. Wonder if that is because the loleaflet-help.html is not a complete HTML page, it lacks <html>, <head>, and <body>?

**Comment by tml1024** [comment]
Nah, that is not the problem. I can't use the same code
`UIApplication *application = [UIApplication sharedApplication];
[application openURL:url options:@{} completionHandler:nil];`
to open a file URL that is inside the app's bundle, because Safari (which would be used to open it, as it is for other hyperlinks that the JS asks the native code to open) of course doest not have access to the app's data.

**Comment by tml1024** [comment]
Instead, I would need to open a new WKWebView to display the loleaflet-help.html, presumably displayed as a "pop-up window" (don't remember what UIKit calls that way to display a view, etc.

**Comment by nikslor** [comment]
Reopen as the "fix" keyword in the commit message closed the issue "automagically".

**Comment by tml1024** [comment]
Argh. That GitHub "feature" is annoying.

**Comment by tml1024** [comment]
Nah. The "preparatory work" above was completely misguided. This is actually now fixed properly by https://github.com/CollaboraOnline/online/pull/1769
