### ISSUE TITLE
Regression CODE 21.11.1.1 Calc: "Sticky" Comment Popups When Scrolling Sheet While Editing

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#4046]
**Describe the bug**
If a Calc cell comment edit popup is opened, the text was changed, and the sheet is then scrolled using the scroll wheel - most likely to reposition the comment edit field so it gets better readable - the edit popup will leave edit mode, go back to readonly mode, and is "stuck" on the screen in a fixed position, not scrolling with the table and not closing on scroll.

Very confusing.

**To Reproduce**
1. Hover over a cell with a cell comment.
2. Move mouse to the cell comment popup and click "... -> Edit"
3. Change the text
4. Scroll the sheet with the mouse wheel to better position the edit window.

**Expected behavior**
The comment edit window will move synchronously with the scrolled table.

Alternatively, scrolling of the table could be forbidden in this state.

It's probably no good idea to autoclose the popup and either accept or discard the edit, as the user hasn't yet either confirmed nor rejected her edit, so the application does not know whether she wants to keep or discard the modifications to the comment text.

The current behavirour also is no option.

**Actual behavior**
The comment will automatically accept the changes and switch to readonly mode. Additionally, it will be stuck in screen and stay in the same position all the time, independently of the scrolling table.

**Screenshots**
![CODE 21 11 1 1 Calc Stuck Comments](https://user-images.githubusercontent.com/26199042/150639797-5aca1414-ec21-4d31-a716-18f8d71fd93a.gif)

COOLWSD Version:
21.11.1.1
git hash: 
e487386
LOKit Version:
built on 
a great technology base
Collabora Office 21.06.12.1
git hash: 
45f56ee
Angeboten von:
 
Ubuntu 18.04.6 LTS
 
ef3ec9a0

**Comment by pedropintosilva** [comment]
@gohrner : Thanks I will look into this. Oddly enough I couldn't reproduce it :

- both clicking out side
https://user-images.githubusercontent.com/65948705/151338722-1139bf9d-0d28-49d6-ab97-f19be9dbd039.mp4
- and simply scrolling after editing the comment:

https://user-images.githubusercontent.com/65948705/151339349-10dfb5d3-2f6a-497d-ae41-c9d43b40b3bf.mp4


I need to test it further and with different browser. By the way which web browser did you use?

**Comment by gohrner** [comment]
Chromium - hopefully this release:

> Chromium Version 97.0.4692.71 (Offizieller Build) Built on Ubuntu , running on neon 20.04 (64-Bit)

**Comment by gohrner** [comment]
@pedropintosilva: I also cannot reproduce it in 21.1.1.4 indeed. So seems to have been resolved somehow.

However, scrolling with a comment currently being edited causes the comment editor to commit / save all edits - not sure if that's what the user expects, as she didn't actually click "Save"?

**Comment by Ezinnem** [comment]
I tested with COOLWSD version:
21.11.2.2 git hash:  [6bbda3eb](https://github.com/CollaboraOnline/online/commits/6bbda3eb)

The comments are not saved when the user scrolls without Clicking the Save button.


@gohrner. you can test again using a more recent version =)

**Comment by gohrner** [comment]
@Ezinnem : I tested with the following 21.11.2.2 version, and there it's actually saved when scrolling without explicitly saving:

COOLWSD Version:
21.11.2.2
git hash: 
[e4d06c2](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/e4d06c2'));)
LOKit Version:
built on 
[a great technology base](javascript:void(window.open('http://col.la/lot'));)
Collabora Office 21.06.17.1
git hash: 
[b24fd42](javascript:void(window.open('https://hub.libreoffice.org/git-core/b24fd42'));)
Angeboten von:
 
Ubuntu 18.04.6 LTS
 
[59a3f02e](https://docs.ohrner-it.com/hosting/discovery)
