### ISSUE TITLE
Support Math in Collabora Online

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#4049]
Please will you consider adding Math, for the ability to create and edit mathematical formulae, Thinking of LibreOffice-Math, i.e. can be incorporated into other documents in the suite, such as Writer or Calc, thank you. This is based on requests in the user forum https://forum.collaboraonline.com/t/support-math-in-collaboraoffice/820

Please will you estimate how long it would take your team to develop, e,g, days/weeks/months.

**Comment by pedropintosilva** [comment]
Thanks a lot @rpear for creating this feature request  !

**Comment by pedropintosilva** [comment]
Hopefully it works to access and voice all the users who share the same desire : ) As of now I can say that the team has been informed and this has been added to the list of feature requests to take a look into :+1:

**Comment by nikslor** [comment]
I'd love to see this feature as well. It's something schools would benefit from.
Thanks @rpear for reporting.

**Comment by reos-rcrozier** [comment]
Could this be suitable for a GSoC project?

**Comment by reos-rcrozier** [comment]
This seems to be implemented now, except that in compact mode the option to insert a formula object is not present (it is there in tabbed mode).

**Comment by rpear** [comment]
Thanks for update, I have tested in CODE 22.05.10.1 and can confirm the option is there and that it appears to work. I don't use it normally, so not a thorough test. Closed it.

I have added the observation that in Compact View the option to Insert > Formula object is not present and that it only appears in the Tabbed View to https://github.com/CollaboraOnline/online/issues/5820

**Comment by rpear** [comment]
Closing it

**Comment by a-andre** [comment]
Could this issue be re-opened as the functionality still seems to be missing in draw and impress.
