### ISSUE TITLE
Android app doesn't show slides in presentation mode

### ISSUE THREAD

**Issue by moshpirit** [CollaboraOnline/online#4063]
**Describe the bug**
Android app doesn't show slides in presentation mode, just a black screen with the android logo

**To Reproduce**
1. Open any ODP file
2. Click on "play/show slides" button at the top-right corner
3. See error

**Expected behavior**
Viewing the presentation

**Actual behavior**
Only shows a black screen with Android logo

**Screenshots**
![Screenshot_20220126-142622_Collabora Office](https://user-images.githubusercontent.com/7888062/151171267-104817c5-3fcb-4031-97ad-74009cc8b671.jpg)

**Smartphone (please complete the following information)**
 - Device: Samsung Tab S4
 - OS: Android 10
 - Version: 6.4.14

**Comment by Ezinnem** [comment]
Reproducible on the Collabora Office app version 6.4.14
