### ISSUE TITLE
Add last-mod string to notebookbar

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#4070]
#### Classic toolbar layout

![2022-01-27 12_59_51-](https://user-images.githubusercontent.com/8517736/151354866-b6eef67d-1a7e-4405-a564-536a23379a94.png)

#### notebookbar layout

should show also the `Last saved:` (`last-mod`) information in the header area.

**Comment by Ezinnem** [comment]
Confirmed in the Notebookbar UI COOLWSD version: 21.11.1.4 git hash: [739da71](https://github.com/CollaboraOnline/online/commits/739da71)

**Comment by Andreas-Kainz** [comment]
If someone can give me am codepointer, it would be cool. @pedropintosilva ?

**Comment by Andreas-Kainz** [comment]
add .uno:Save next to the last-mod string

![save](https://user-images.githubusercontent.com/8517736/155394797-aa084144-497d-4961-9739-df8f8f3c01c8.png)

**Comment by Andreas-Kainz** [comment]
@eszkadev do you have a codepointer or something like this. It's one of the last todo for https://github.com/nextcloud/richdocuments/issues/1976
