### ISSUE TITLE
PDF downloads from Collabora are blank

### ISSUE THREAD

**Issue by adf-patrickha** [CollaboraOnline/online#4078]
If you open a PDF in OwnCloud with Collabora and download it, the downloaded file is empty. 
The file will be downloaded (filename is also correct), but it's just a blank PDF file. 
The download from the OwnCloud file overview works fine. We are not sure if this error occurred with previous Collabora versions without anyone noticing.

Server OS: Debian 11
CollaboraOffice version: 6.4.10.52-52

![dok_2](https://user-images.githubusercontent.com/84573341/151402836-a0182b9f-4bb7-4240-bdee-f2be5fc06705.PNG)

**Comment by adf-patrickha** [comment]
Can you please give us an update on this? Is this a known issue? Is there a workaround for it until the issue is fixed?

**Comment by gitgt** [comment]
Please update with info if you are still seeing a problem, with which version, is it Collabora server or builtin CODE.
Does it happen with any file, did you try with different fonts? 
If still a problem, please attach the resulting PDF.

**Comment by timur-g** [comment]
No response, I close.
