### ISSUE TITLE
Calc: statusbar not displayed by default. Not available in Layout menu

### ISSUE THREAD

**Issue by joergmschulz** [CollaboraOnline/online#4080]
Version: 21.11.1.4

in CALC, the statusbar is not visible by default.
<img width="409" alt="image" src="https://user-images.githubusercontent.com/6523646/151451972-55f517a5-b930-44ec-a42d-b417a914b0bc.png">

There is no possibility to turn it on via the Layout menu (in writer, there is such a button).
The statusbar only shows when the hotkey for 'search' is pressed.
<img width="437" alt="image" src="https://user-images.githubusercontent.com/6523646/151452098-6814a43c-5cc8-40a9-b45e-0c430a67ca1f.png">

would it be possible to force-open the statusbar by default just like it is possible to force the notebookbar design using a --o:extra_params parameter?

**Comment by Andreas-Kainz** [comment]
good point should be visible and there should be also an option to hide it like in writer.

**Comment by Ezinnem** [comment]
This issue does not seem reproducible on COOLWSD 21.11.1.4 git hash:[ 535278f5](https://github.com/CollaboraOnline/online/commits/535278f5)


@joergmschulz, @Andreas-Kainz, please can you check again?

https://user-images.githubusercontent.com/54344301/151751790-669f098c-6433-424a-bbf9-d6ff0e843e68.mp4

**Comment by joergmschulz** [comment]
interesting. Here, 
21.11.1.4 git hash: 
535278f5 (master of Jan 28)
doesn't show the statusbar.

**Comment by joergmschulz** [comment]
This is perfectly fixed for calc in master of Feb 01 
21.11.1.4 git hash: 01cb40cf
I think for impress it still needs to be done.

**Comment by pedropintosilva** [comment]
@joergmschulz glad to hear, yes indee : )
