### ISSUE TITLE
Don't load Sidebar when it is hidden

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#4081]
when I update cool it look like the first item in the UI which was drawn on the webbrowser was the sidebar. So if I hide the sidebar and click F5, I see that the sidebar was drawn, than hidden and than the toolbar and the rest of the UI was drawn.

When an element was hidden, it should be not drawn at the first element, best would be it wasn't drawn or it was drawn when everything else was already drawn.

**Comment by thebearon** [comment]
Let's close this in favor or #3552.
