### ISSUE TITLE
LanguageMenu available within the Notebookbar tab

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#4083]
LanguageMenu from the Hamburger menu at the notebookbar layout should be available within the notebookbar (mayeb review tab).

![image](https://user-images.githubusercontent.com/8517736/151464055-c804242d-2bea-4d60-9b05-6cb57752c71f.png)

**Comment by Ezinnem** [comment]
@pedropintosilva, @eszkadev, Please can you take a look sometime?

**Comment by eszkadev** [comment]
@pedropintosilva could you prepare some mockup, where to put this? then I can work on it

**Comment by Andreas-Kainz** [comment]
@eszkadev PR is already ready with the correct location. But the PR need some help from you.

**Comment by Andreas-Kainz** [comment]
Thanks to @eszkadev
