### ISSUE TITLE
ctrl+alt+m seems broken in CooL writer

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#4109]
**Describe the bug**

The shortcut ctrl+alt+m is not documented in the shortcuts dialog and seems to be broken. It looks like it creates a comment, but the text input is missing. I stumbled upon this, because in GDocs ctrl+alt+m is used for "add a comment" (in CooL this is ctrl+alt+c).

I see two options:
* remove/fix the code that gets triggered by ctrl+alt+m
* wire ctrl+alt+m to the same code as ctrl+alt+c to mimic GDocs behavior (not sure if this is helpful, but maybe it helps users who also use GDocs) 

**To Reproduce**
1. Open a writer document in CooL
2. Write some words
3. Mark a portion of the text
4. Hit ctrl+alt+m

**Expected behavior**
Nothing should happen as it's not a documented shortcut.

**Actual behavior**
An incomplete comment box is added.

**Screenshots**
![image](https://user-images.githubusercontent.com/1211300/152299349-77f86829-b61f-462d-9647-482f19cff70b.png)

**Desktop (please complete the following information)**
 - Browser: Firefox 96.x
 - Version: 21.11.1.4

**Additional context**
Chat with vmiklos: 
![image](https://user-images.githubusercontent.com/1211300/152299490-227e3e9e-5908-454c-8fcd-4b2042eef755.png)

**Comment by Ezinnem** [comment]
Reproducible in COOLWSD version: 21.11.1.4 git hash:  [739da71](https://github.com/CollaboraOnline/online/commits/739da71)

**Comment by timar** [comment]
ctrl+alt+m was added by Laszlo Nemeth back in 2015, probably he thought of compatibility with GDocs. I don't think it matters much, if we keep ctrl+alt+m, and fix it to behave the same as ctrl+alt+c. My one-liner fix seems to be working, I tried Firefox and Chrome.
