### ISSUE TITLE
iOS App: not possible to end an impress presentation

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#4123]
**Describe the bug**
I can't find a way to end/close an impress presentation on an iPad. The presentation just loops and there is no obvious way to end/close the presentation mode.

**To Reproduce**
1. Open an impress presentation using the iOS app
2. Switch into presentation mode
3. Try to close the presentation

**Expected behavior**
The presentation should end after the last slide or there should be an other simple and obvious way to close the presentation on an iPad.

**Actual behavior**
The presentation loops (jump to the first slide after the last was shown) and there is no simple/obvious way to end the presentation mode.

**iPad**
 - Device: iPad
 - OS: iPadOS 15.2
 - Version: 21.11.1 (2)

**Comment by plubius** [comment]
I'll let @tml1024 decide if it should be closed. I didn't change any iOS code for this bug so I assume that the fix was made in the Online or LibreOffice code.

**Comment by tml1024** [comment]
I trust @nikslor that the bug is gone.
