### ISSUE TITLE
Collabora online - Nextcloud - PDF with landscape and Portrait Modes NOT recognized

### ISSUE THREAD

**Issue by Borja2022** [CollaboraOnline/online#4133]
**Describe the bug**
When opening a pdf document Nextcloud Collabora Online (pages in Landscape and Portrait in the same document) the Landscape pages are shown but when in the same pdf there are portrait pages it shows the page cut by a Landscape Format without posibility to read the end of each portrait page. There is not an automatic orientation when scrolling down.

**To Reproduce**
1. Go to shared link
2. Click on pdf document
3. Scroll down between landscape and portait pages.

**Expected behavior**
See pages in Landscape or Portrait as the pdf (mixed orientation pages)

**Actual behavior**
When in Landscape, the portrait pages are cutted and no possibility to read the end of each page

**Screenshots**

<img width="1428" alt="Nextcloud Orientation" src="https://user-images.githubusercontent.com/99196142/152817949-22946fc5-688b-4620-bd65-239ad0aada45.png">
[Nextcloud Orientation.pdf](https://github.com/CollaboraOnline/online/files/8016490/Nextcloud.Orientation.pdf)

**Comment by Ezinnem** [comment]
Reproducible in: COOLWSD 21.11.1.4 git hash: [739da71]('https://github.com/CollaboraOnline/online/commits/739da71)

**Comment by Borja2022** [comment]
> Reproducible in: COOLWSD 21.11.1.4 git hash: [739da71](https://github.com/CollaboraOnline/online/commit/739da71a9be94175f64a725092c5a2828e537d1f)

Sorry, I am an end user of Nextcloud/Collabora. Do I have to do something? Should I give this to my Tech people?
Best regards

**Comment by Ezinnem** [comment]
@Borja2022, We were able to reproduce the issue that you reported and we have taken note of it.
