### ISSUE TITLE
iOS app: colors in the color picker are cut off in the sidebar

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#414]
**Describe the bug**
Some/many colors in the color picker are not visible when the color picker in the sidebar is opened.

**To Reproduce**
1. Open a writer document in the iOS app
2. Open the sidebar
3. Tap on the "font color" button

**Expected behavior**
The color picker should be fully visible.

**Actual behavior**
The color picker is partially cut of and not fully visible.

**Screenshots**
<img width="1112" alt="color_picker_cut_off" src="https://user-images.githubusercontent.com/1211300/96998646-19c8ba00-1534-11eb-9f22-066b83154208.png">

**Tablet**
 - OS: iOS 14.1
 - Version: 6.4.0 (5)

**Comment by thebearon** [comment]
Not sure what a good soluton would be, but I can confirm.
In the 4.2 version of the app, the color pickers open downwards (they can still be obscured by the keyboard, and as far as I could see can't be scrolled).

**Comment by tml1024** [comment]
Interesting that in the portrait orientation, that colour picker thing opens downward, not upward (and fits fine) 
![669BE75C-802F-423E-AF9E-7F04567D659F_1_105_c](https://user-images.githubusercontent.com/310731/110643234-8af3cb80-81bc-11eb-857f-8556bd700608.jpeg)

**Comment by tml1024** [comment]
By the way, @thebearon , how does it work in the Android app?

**Comment by tml1024** [comment]
Argh, what I wrote above about portrait orientation apparently is true only if you open the document with the iPad in landscape orientation, and then turn it to portrait orientation while the document is open. If you open it with the iPad already in portrait orientation, the colour thing looks like this, it gets truncated at the bottom, even if there would be ample room for it... 
![6085BB96-FF26-4152-B4E8-8E2D136FA103_1_105_c](https://user-images.githubusercontent.com/310731/110796592-cc4daf00-8280-11eb-86e9-2410ffd12f36.jpeg)

**Comment by tml1024** [comment]
When I, as an experiment, make the colour swatches very small (10x10 instead of 30x30 points) and put more of them on each line (10 instead of 4), the colour palette does open downwards from the triangle button. So apparently what happens is that with the normal size swatches, some code notices that it won't fit entirely if opened downwards, and then opens it upwards instead (even if it fits even less then). Would the ideal be to just place it so that it fits, even if it then would cover the triangle button?

**Comment by nikslor** [comment]
@tml1024 is there a UIKit widget (like the font selection we use in iOS) we could use?

**Comment by tml1024** [comment]
Sure. In iOS 14 there is UIColorPickerViewController, and it is gorgeous: https://medium.com/@furkan.vijapura/uicolorpickerviewcontroller-in-ios-14-cbe4fcd78fdc . But I understand that at some stage (when basing the app on core 7.1) the tunnelled dialogs will go away completely anyway, and we will use some JavaScript thing, so I am not sure if it is worth it to start re-engineering them at this stage, to make one part work completely different on iOS. The font selection thing was much more localised in how it affected the code.

**Comment by nikslor** [comment]
Okay, thanks a lot for the information.

Going back to your initial question: "Would the ideal be to just place it so that it fits, even if it then would cover the triangle button?" I think overlapping the triangle is not a big issue as long as it's still possible to close the color-selection-dialog

**Comment by thebearon** [comment]
> By the way, @thebearon , how does it work in the Android app?

Adding the information for reference here as well, in Android the sidebar looks quite different, unfortunately not themed, and takes up more horizontal space than the iOS one. It doesn't have the large color picker icons (though they aren't too small), either, thus the dropdown opened downwards.

**Comment by nikslor** [comment]
This is fixed thanks to the HTML/JS-rework of the sidebar which is now present in 21.6.1 (1). I think we can close this issue :smiley: 

Thanks a lot to the Collabora team for taking care of this and especially to @eszkadev and @tml1024
