### ISSUE TITLE
Regression of issue #2558 Android fails to open document

### ISSUE THREAD

**Issue by jimbolaya** [CollaboraOnline/online#4152]
**Describe the bug**
Regression of issue 2558 in 21.11?
                        
**To Reproduce**                                                         
1. Get 21.11 snapshot from https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/
2. Load APK 
3. Open any document 

**Expected behavior**
I expected to be able to see my documents and edit them
                    
**Actual behavior** 
The document appears to be empty, but doesn't allow editing either. See https://github.com/CollaboraOnline/online/issues/2558

**Screenshots**     
I can add one, but the screenshots in the above mentioned closed ticket are identical.

**Smartphone (please complete the following information)** 
 - Device: Moto X4    
 - OS: Android 9      
 - Browser: N/A
 - Version: 21.11 from 2022-02-08 snapshot

**Comment by Ezinnem** [comment]
@jimbolaya, We have noted the issue with 21.11 apk build.

You can try to download the 6.4 APK build that is appropriate for your device.

The APK starting with the name `collabora-office-mobile-6.4-snapshot-armeabi-v7a...` should work fine with your device.

**Comment by jimbolaya** [comment]
> We have noted the issue with 21.11 apk build.

Thank you for letting me know.

> ﻿You can try to download the 6.4 APK build that is appropriate for your device.

Yes, this works fine.
