### ISSUE TITLE
CODE 21.11.1.4 Calc: Misplaced Cell Contents During Editing

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#4180]
**Describe the bug**
During editing in a cell, often the cell contents are completely "misplaced" such that it's impossible to see what you're actually editing.

**To Reproduce**
1. Test file is attached. Go to one of the cells with text and press F2.

**Expected behavior**
The text can be edited in the cell, and the text cursors shows the position where content is being added or removed when typing on the keyboard.

**Actual behavior**
The text cursor is shown in a big empty area, while the cell's content are displayed in an area left of it.
Typing on the keyboard will insert or remove letters somewhere in this text, but you've no idea where exactly as there is no indication where the current editing position is.

**Screenshots**
![CODE 21 11 1 4 Calc Text Editing Mispositioning](https://user-images.githubusercontent.com/26199042/153735363-85437670-5948-4b0f-aa25-ba66db12cf48.gif)

Unfortunately, it does not seem to be possible to add ODS files as an attachment here...
* I cannot find an "upload" button,
* dragging the file into the text box - which, I think, used to work sometime in the past - just opens a new, empty Chromium browser tab,
* and copy-pasting the file from a file manager just inserts my local directory / path to the file... :-(

So you have to download it from my NextCloud instance: https://nextcloud.ohrner-it.com/s/oRNzpxRq9kWEbAo

**Desktop (please complete the following information)**
 - OS: Ubuntu 20.04 LTS with KDE neon Desktop
 - Browser: Chromium
 - Version: Version 97.0.4692.71 (Offizieller Build) Built on Ubuntu , running on neon 20.04 (64-Bit)

**Additional context**
COOLWSD Version:
21.11.1.4
git hash: 
[739da71](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/739da71'));)
LOKit Version:
built on 
[a great technology base](javascript:void(window.open('http://col.la/lot'));)
Collabora Office 21.06.13.1
git hash: 
[242d275](javascript:void(window.open('https://hub.libreoffice.org/git-core/242d275'));)
Angeboten von:
 
Ubuntu 18.04.6 LTS

**Comment by Ezinnem** [comment]
I can reproduce the issue described using the sample file you provided on the COOLWSD version: 21.11.2.0 git hash: [e179126](https://github.com/CollaboraOnline/online/commits/e179126).

**Comment by gohrner** [comment]
Also still reproducible with:

COOLWSD Version:
21.11.2.2
git hash: 
[e4d06c2](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/e4d06c2'));)
LOKit Version:
built on 
[a great technology base](javascript:void(window.open('http://col.la/lot'));)
Collabora Office 21.06.17.1
git hash: 
[b24fd42](javascript:void(window.open('https://hub.libreoffice.org/git-core/b24fd42'));)
Angeboten von:
 
Ubuntu 18.04.6 LTS
 
[59a3f02e](https://docs.ohrner-it.com/hosting/discovery)
