### ISSUE TITLE
Calc: Cannot paste value of cell to other applications, only formula

### ISSUE THREAD

**Issue by mitohund** [CollaboraOnline/online#4206]
**Describe the bug**
The content of a cell is a formula (e.g. "=B2\*H2") which results in a numeric value (e.g. "15"). When the cell is copied and then pasted into a different application, the result is "=B2*H2" instead of "15".

**To Reproduce**
1. Open a spreadsheet
2. Click on a cell with a formula (e.g. "=B2*H2") that shows as a number (e.g. "15")
3. Copy the cell
4. Switch to different application, e.g. Notepad, Microsoft Office, browser address bar, etc.
5. Paste
6. The result is "=B2*H2" instead of "15"

**Expected behavior**
The pasted content should be the value ("15"), not the formula ("=B2*H2").

**Actual behavior**
The pasted result is "=B2*H2" instead of "15".

**Desktop**
 - OS: Windows 10 & Windows 11
 - Browser: Firefox (97.0) & Brave (1.35.101)
 - Nextcloud: 23.0.1
 - Nextcloud Office: 5.0.2
 - Collabora CODE, COOLWSD version: 21.11.1.4

**Additional context**
The current behaviour makes Calc / Spreadsheets unusable in an environment where the data needs to be moved between applications.

**Comment by Ezinnem** [comment]
Reproducible on: COOLWSD version: 21.11.2.2 git hash: [d48fe4a5](https://github.com/CollaboraOnline/online/commits/d48fe4a5)

**Comment by mitohund** [comment]
Just as additional information: the current behaviour is inconsistent with LibreOffice. And also with Excel, of course.

**Comment by mitohund** [comment]
Behaviour is still the same with COOLWSD 21.11.2.4 and Nextcloud Office 5.0.3.

**Comment by mitohund** [comment]
Now on COOLWSD 21.11.3.6.1, Nextcloud Office 5.0.3 and Nextcloud 23.0.3, and the issue persists.

How can I raise awareness of this issue? Aside from @Ezinnem, nobody seems to care, even though this simply cannot be the intended behaviour, considering LibreOffice and Excel do not behave this way.

**Comment by mitohund** [comment]
On COOLWSD 21.11.4.2, Nextcloud Office 5.0.4 and Nextcloud 23.0.4 now. The issue persists.

**Comment by mitohund** [comment]
Now on COOLWSD 21.11.5.3., Nextcloud Office 6.1.0 and Nextcloud 24.0.2.

The issue persists.

**Comment by mitohund** [comment]
Now on COOLWSD 22.05.5.4, Nextcloud Office 6.2.0 and Nextcloud 24.0.4.

The issue persists.

**Comment by Kexkey** [comment]
This is a major issue with some of my huge spreadsheets where I need to copy formula results (values, not formulas) to an e-mail or any other application.  I need to retype the values one by one instead of being able to copy and paste the whole selection.

**Comment by wchouser3** [comment]
this isn't just an issue with the spreadsheets. It's on the Nextcloud office writer too. Why is this still an issue. It basically makes the document server useless if we can't copy and paste from outside the application. I really have a hard time telling people they should use this instead of google docs if we can't even get the basics nailed down!

**Comment by mitohund** [comment]
It's good to see there are more people becoming aware of this issue. Unfortunately, nothing has changed with the most current versions:

COOLWSD 22.05.9.2
Nextcloud Office 7.0.2
Nextcloud 25.02

**Comment by Quiwy** [comment]
Same problem here with collabora online 22.05.17.

**Comment by Ezinnem** [comment]
The fix for this has been made.

The fix will be available on the next 23.05 version to be released soon.

**Comment by timur-g** [comment]
: https://github.com/CollaboraOnline/online/pull/7601

**Comment by mitohund** [comment]
The fix seems to have needed a while to trickle down to my Nextcloud AIO installation. But now it's here and it works!

Thanks heaps for fixing it! This will make my life so much easier!
