### ISSUE TITLE
Notebookbar Separator lines missing

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#421]
Compare to the toolbar layout in the notebookbar layout the vertical separator lines between different groups are missing see
![CollaboraOnline_Writer_Notebookbar_home_zoom133_20200810_1920x982](https://user-images.githubusercontent.com/8517736/97053529-67204800-1583-11eb-82e4-72bd5d416d28.png)

toolbar layout has vertical separator lines between groups
![CODE_640_Writer_Classic_Toolbar-3](https://user-images.githubusercontent.com/8517736/97053536-6ab3cf00-1583-11eb-8a53-41433c7b016e.png)

**Comment by 22shubh22** [comment]
I would like to help yo with this.

**Comment by ayhanyalcinsoy** [comment]
Hi Andreas,
I want to fix this bug but I couldn't found how I can do it. Can you give me tips about it?

**Comment by Andreas-Kainz** [comment]
Hi,

the issue is, that the tabbs were used from core and sometimes there are groups empty cause the feature isn't yet available in cool. So if you have the separators visible (with Notebookbar.css for example) than it can happen, that there are 2 - 4 Separator lines next to each other.

So in addition to make the separators visible, you have to have something in the codebase that if there are more than one separator, than show only one.

I'm not sure how fare @eszkadev is with his rework of the notebookbar json implementation where this can be improved.

**Comment by Andreas-Kainz** [comment]
After some work on Notebookbar I'm not sure if a separator is really needed, cause with the defined layout a separation was already visible, however in general it would be useful to have the possibility for separators.

**Comment by Andreas-Kainz** [comment]
Separator not needed.
