### ISSUE TITLE
replace floppy disk icon for save

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#4215]
The Save icon is a floppy disk symbol, which was discussed quite often at LibO cause the time when floppy disks was used, is long long ago.

Compare to LibO COOL is an online based office suite. So I suggest to change the save icon from a floppy disk symbol to something else.

![2022-02-16 11_28_22-mobileOfficeApps docx - Dateien - ARSENAL RACE](https://user-images.githubusercontent.com/8517736/154245928-80248368-0bcf-46d5-9436-174b0e863fe4.png)

**Comment by Andreas-Kainz** [comment]
On mobile we use an ✓ symbol.

![2022-02-16 11_29_36-mobileOfficeApps docx - Dateien - ARSENAL RACE](https://user-images.githubusercontent.com/8517736/154246097-60564f4f-db0e-4d9e-9b84-eb0a6e3362b3.png)

Which is from my point of view a bit to generic for desktop, but could be used also than we are more similar between desktop and mobile.

**Comment by Andreas-Kainz** [comment]
As cool data storage is ordinary cloud based, we can use an cloud symbol for save.

![image](https://user-images.githubusercontent.com/8517736/153958180-674ba166-c393-40a3-8947-5caa7d72de1e.png)

**Comment by pedropintosilva** [comment]
ref: https://github.com/CollaboraOnline/online/pull/4200#pullrequestreview-883080023 ; https://github.com/CollaboraOnline/online/pull/4209

Even if after the fact, thanks for creating this issue : )

I'm not opposed to change the save icon but if we do so we probably should think a bit long and hard of what it would be instead.

Classic floppy disc has many advantages to name a few:
* If initially used as a representation of the physical device where you store stuff it then evolved in something else. Not a representation of a floppy disk but as the classic symbol representing the action of saving
* Our user base is not so young that would dramatically benefit them (quite the opposite I would say)
  * But even when asking to kids and pre-teenagers to spot what's the icon for the saving action they will always point to what they call "classic"/"saving" "icon/square"
 
With that been said I think we can do a change and then wait for the feedback (as there are still many users not using branding packages, so just CODE bare-bones and sometimes with their own CSS customizations above) 

## Object VS Action

* I really don't like how the [cloud](https://github.com/CollaboraOnline/online/issues/4215#issuecomment-1041342494) is portrait here, it does not point to the act but instead to the (false) object
  * There is no cloud only computers : p nah just joking
* So I would really focus on the action it self
* The icon should trigger an active action verb in our minds and not an object

## Iterations if going cloud

If we want to keep on this cloud direction maybe we could

* Make sure the cloud looks different, so it invokes the action of "save" (a checkmark or an arrow)
* Re-think how we represent unsaved status, right now the dot looks more like a sun and it's less indicative of a status
* The icon is too small in the toolbar (shortcuts-bar)

## Iterations if going Check-mark

The checkmark has the advantage that it invokes mainly and primarily the action of "confirm"
* As you [pointed out](https://github.com/CollaboraOnline/online/issues/4215#issuecomment-1041341529) that can be quite generic 
* Some would say that the position of where it goes helps to fight the previous point ^

**Comment by Andreas-Kainz** [comment]
As we want to remove the shortcuts-bar saved should be also removed from there. If you have a look at other online office suites there is also NO save icon (at least not in the default UI), cause ordinary the document get autosaved.

![RE3ByzZ](https://user-images.githubusercontent.com/8517736/154256320-30586517-e34b-4826-9fd8-0b6edc9d6b8d.png)

There is also in the header area the visiual feedback, that the document was saved last time. 

![2022-02-16 12_32_51-writer odt - Nextcloud](https://user-images.githubusercontent.com/8517736/154256498-e87395db-ad3d-4b64-85d4-6b11288f4432.png)

maybe we can add to the strange an save "button" and remove the save everywhere else.

for the notebookbar file tab, I would prefer to have there the save command, cause it's not in the default UI, but it's an file related command. And there an floppy disk or cloud icon would be fine.

**Comment by Andreas-Kainz** [comment]
at google docs there is any save command available at all.

**Comment by Andreas-Kainz** [comment]
have the save icon (as floppy cause it's easier to understand) next to the Last saved string, so next to the save information.

![save](https://user-images.githubusercontent.com/8517736/154258056-a91b783d-a5a3-4372-9f2f-9ed958939cdd.png)

**Comment by rizmut** [comment]
Despite getting a lot of criticism, the floppy disk icon for the act of saving has been very embedded in the minds of many people.

I just imagine if I'm a new user and think COOL is like any other cloud based office suite solution that doesn't need any save action I'm likely to miss this icon. Even if there was a helpful tooltip, I'd still be frowning: "cloud icon as a saving icon?"

**Comment by Stefan-U** [comment]
Even though the issue is already closed, I would like to add the following:

**No save icon would also mean that the user could not create a version of the document manually**. Versioning is offered by most file hosts with COOL. And that is exactly why I personally use the save button more often.

I therefore think that the Save button is justified.
And as a somewhat older user, I can live with the diskette symbol. And I think most others can too.

**Comment by Andreas-Kainz** [comment]
good point @Stefan-U I'm also for have the save icon, BUT I would move the save icon (command) next to the last saved string.
