### ISSUE TITLE
Error when loading a document

### ISSUE THREAD

**Issue by tcitworld** [CollaboraOnline/online#4264]
**Describe the bug**
Any document I'm trying to open never loads directly unless I force refresh the Nextcloud files page and in a second step open the document. This issue also doesn't seem to affect Chromium.

I observe the following issue in the browser logs.
```
Uncaught TypeError: app.sectionContainer.getSectionWithName(...) is null
    _hideWizard https://coolwsd.xxx.org/browser/e4d06c2/bundle.js:1
[bundle.js:1:2264150](https://coolwsd.framasoft.org/browser/e4d06c2/bundle.js)
    _hideWizard https://coolwsd.xxx.org/browser/e4d06c2/bundle.js:1
    _hideWizard self-hosted:1184
```

I'm using coolwsd 21.11.2.2-1 from Debian packages, so I think this is similar to the fix at 4764937ad44a5cca99a7d5b962e661f491d18cb1 (which I should already have if I'm reading version information correctly).

**To Reproduce**
1. Load a document

**Expected behavior**
The document being loaded

**Actual behavior**
The loading screen shows indefinitely

**Desktop**
 - OS: Fedora
 - Browser: Firefox
 - Version: 97

**Additional context**

**Comment by XueSheng-GIT** [comment]
I'm still facing this issue on latest Collabora 21.11.3.6. Especially when using Firefox.
> Uncaught TypeError: app.sectionContainer.getSectionWithName(...) is null

Should this issue be re-opend or a new issue created?

**Comment by XueSheng-GIT** [comment]
@tcitworld can you double check whether your fix is still working? I'm still facing this issue... see also comment in your pull https://github.com/CollaboraOnline/online/pull/4265#issuecomment-1075301150
