### ISSUE TITLE
Group download as icons into a dropdown menu for the Notebookbar UI

### ISSUE THREAD

**Issue by alessioalex-1and1** [CollaboraOnline/online#4282]
**Is your feature request related to a problem? Please describe.**
There are a lot of 'download as' icons when clicking on the File tab, Notebookbar UI mode enabled. 

**Describe the solution you'd like**
There needs to be a setting that you can check to enable those into a dropdown so that it's more manageble.

**Describe alternatives you've considered**
none

**Additional context**

This is how the icons look like at the moment:

![How it is at the moment](https://cldup.com/Ir_bPCTKzP.png)

This is how the icons look could like at (via enabling a setting):

![How it should be via a setting](https://cldup.com/nptZ0r-O-R.png)

**Comment by Andreas-Kainz** [comment]
This is how the LibreOffice (writer) File tab look like

![2022-02-24 12_28_40-Untitled 1 - LibreOffice Writer](https://user-images.githubusercontent.com/8517736/155515893-5124c510-7ef0-4c2c-9fb8-7805ae7ad8bb.png)

**Comment by Andreas-Kainz** [comment]
And here is the file (writer) menubar section
![2022-02-24 12_28_09-Untitled 1 - LibreOffice Writer](https://user-images.githubusercontent.com/8517736/155516014-ae086f9f-9848-415e-a378-15ee7cbea636.png)

**Comment by Andreas-Kainz** [comment]
if you click on Export you get a save dialog with the following options
![2022-02-24 12_27_57-Untitled 1 - LibreOffice Writer](https://user-images.githubusercontent.com/8517736/155516206-8261063f-f1ed-4e9a-bb2e-a93503d9f97f.png)

**Comment by Andreas-Kainz** [comment]
what I want to say with the screenshots from LibO
- In LibO there are two groups `Save/SaveAs/SaveRemote` and `Export/PDF/EBUP`
- In Cool there are less commands (available now), but as the Export commands are also available within cool, we could offer the commands from LibO

#### suggestions for cool
![File](https://user-images.githubusercontent.com/8517736/155520843-025bb66a-49e6-470e-a6af-3d0ed298f84b.png)

So we have the benefit for one click download the most often used formats and two clicks for all other options that are available within LibO.

**Comment by Andreas-Kainz** [comment]
is it possible to add Export as PDF (which open first the dialog where you can define settings), export png, jpg, html, ... ? 

Cause for this more exotic downloads an dropdown menu could be very useful.

**Comment by alessioalex-1and1** [comment]
I haven't looked into this yet, not sure to be honest. The dropdown menu just acts like the individual items did before, they have the same id and functionality. I do not know what is needed for those extra exports.
