### ISSUE TITLE
As a user dealing with multiple language I'd like to have a translation service integrated into CooL

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#4285]
**Is your feature request related to a problem? Please describe.**
There is no technical problem that leads to my feature request. I often deal with multiple languages and documents where I need to translate content from EN -> DE or vice versa. It would be nice, to be able to connect CooL to a translation service. There are multiple ones (some are gratis, others do cost) whereas I see deepl.com as the most important one (GDPR compliant, probably the best translation quality).

**Describe the solution you'd like**
I think we should build a translation abstraction that can connect to different services and implement deepl.com as the first implementation. The connection settings (e.g. identifier + API key) must be configurable (especially for users that use the premium features) and there are probably two modes and we should focus on one:
* Mode a): translate the whole document
* Mode b): translate the selection [<- this is the more important mode]

The text formatting should not change when using the translation functionality, let's say I have a title and a paragraph selected and fire "translate" the two elements should not loose their distinct formatting.
One thing I find incredible hard is to easily change the document language - this should become easier too.
In general this should be implemented into LibreOffice as well (not CooL only). iOS/Android would be nice too.

So in general I see the following high level tasks:
- [ ] implement the Deepl API
- [ ] make it possible to configure identifier + API key for Deepl
- [ ] implement a "translate selection..." tab (in the sidebar I guess, offering a list with the supported languages)
- [ ] make it easy to change the document language (e.g. ctrl+a -> German/Switzerland), this is for example not possible if a TOC exists

**Describe alternatives you've considered**
The best alternative is to copy/paste from CooL to the Deepl webpage/app and vice versa which is painful.

**Additional context**
Let me know if I should (temporary) provide a user so you can access the deepl API.

**Comment by vmiklos** [comment]
We'll estimate what would be required here with @kendy .

**Comment by rpear** [comment]
Here are some links relating to LibreOffice language translation.
[Bug 34058](https://bugs.documentfoundation.org/show_bug.cgi?id=34058) - Translation feature through external services
https://extensions.libreoffice.org/en/extensions/show/pagetranslate
https://extensions.libreoffice.org/en/extensions/show/tradutorlibretext

**Comment by rpear** [comment]
@nikslor In case you have not seen, [CODE 22.05.7.2](https://www.collaboraoffice.com/code-22-05-release-notes/) now says it has translate and it uses Deep. I thought that this would be years away, amazing!
![image](https://user-images.githubusercontent.com/80790599/197706524-d6373f80-a7c8-4dcd-92b5-18c9ebf222f2.png)

**Comment by nikslor** [comment]
Thanks for the heads-up @rpear; indeed cool :+1:

**Comment by thebearon** [comment]
@nikslor Can you please check if the current feature tick all the boxes you wanted?

**Comment by nikslor** [comment]
I think we can close this one @thebearon; I'll add new issues for things that don't work or need to be improved. Thanks to the Collabora team for the work on this!

**Comment by thebearon** [comment]
Okay, let's close, thanks!

**Comment by riker513** [comment]
Hi everybody, nice feature, made me sign up for DeepL Pro. There is one catch though. Can you enable possibilities for setting advanced parameters for the DeepL API? I'd like to set the formality to less. Otherwise text is to formal otherwise (usted/Sie/...) and I have to manually edit a lot. Also the API has the option to supply some context (text up to 128kb) that the translater uses to get the flavor. Would it be possible to make room in Collabora Office for these settings?

**Comment by vmiklos** [comment]
This issue is closed already, I suggest to open a new, follow-up issue with your related ideas. Thanks.
