### ISSUE TITLE
As a user dealing with multiple language I'd like to have a spell-, grammar- and style check service integrated into CooL

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#4287]
**Is your feature request related to a problem? Please describe.**
There is no technical problem that leads to my feature request. I often deal with multiple languages and documents where I need to write content in languages that are not my mother tongue. It would be nice, to be able to connect CooL to a spell-, grammar-, and style check service. There are multiple ones (some are gratis, others do cost) whereas I see languagetool.org (LT) as the most important one (GDPR compliant, quality results).

**Describe the solution you'd like**
I think we should build an abstraction layer for different services and implement languagetool.org as the first implementation. The connection settings (e.g. identifier + API key) must be configurable (especially for users that use the premium features).
While there is a languagetool.org extension for desktop LibreOffice it needs Java to run - this feature request strives for a native implementation. The interaction with the user to indicate errors should not differ much from the way languagetool does it in their own implementation. One "popup" is all that is needed to interact with LT:
![image](https://user-images.githubusercontent.com/1211300/155522764-3e23095b-9f9c-44a8-9ddc-31528e9f9d04.png)
![image](https://user-images.githubusercontent.com/1211300/155522957-f5f7db7a-8225-47f4-852b-44f73c84d149.png)

In general this should be implemented into LibreOffice as well (not CooL only). iOS/Android would be nice too.

**Describe alternatives you've considered**
The integrated spellchecker just finds misspelled words, languages like German have several articles and cases, which demands more complex rules for a proper automated proof-reading. So the integrated spellchecker is nor an option and copy/paste content from CooL to the LT browser page is painful.

**Additional context**
 Let me know if I should (temporary) provide a user so you can access the languagetool API.

**Comment by vmiklos** [comment]
We'll look at what would it take to support LT's web service in desktop LO and COOL with @kendy .

**Comment by danir-de** [comment]
Isn't Language-Tool open source? Maybe we can simply implement a server connector so that we can keep everything open-source: 
https://github.com/languagetool-org/languagetool
https://dev.languagetool.org/http-server

**Comment by timur-g** [comment]
LibreOffice and Collabora Office and Collabora Online have LanguageTool integrated. May be not fancy as extension with colors, but it works. .I close this. Note that there are some bugs in using LT, of which we have queued some, but with no priority..
