### ISSUE TITLE
Online (and iOS): picture rotation not working in writer document

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#4289]
**Describe the bug**
In the current "master" of CooL and also in the iOS version 21.11.2 (2) picture rotation leads to a broken state - no editing is possible afterwards.

**To Reproduce**
1. Open a writer document using e.g. the current (today) staging version on https://staging.eu.collaboraonline.com/nextcloud/index.php
2. add a picture
3. rotate the picture
4. try to enter text in the document after the picture was rotated

**Expected behavior**
A user should be able to enter text after a picture was rotated.

**Actual behavior**
Somehow I can't get the focus off the picture and enter text into the document after trying to rotate a picture.

**Screenshots**
n.a.

**Desktop (please complete the following information)**
 - Browser: 21.11.2.2 git hash: [dc0b02da] - https://github.com/CollaboraOnline/online/commits/dc0b02da'
 - Version: FF 97

**Comment by thebearon** [comment]
I'm confused by the title, which says:
> picture rotation not working

While the description is about getting editing focus back to the document.
The description also states it's related to the iOS app, but at the end I see a different version hash and a browser reference.
Can you please clarify?

**Comment by nikslor** [comment]
Hi @thebearon

I can't reproduce it anymore.. I run into this issue multiple times; I'll make sure to have more details at hand as soon as I run into it again. But let's close until then.

**Comment by thebearon** [comment]
Let's reopen, since you mentioned it still occurs randomly.

For the record, there was a similar issue that was fixed recently: in normal online, the caret was missing after inserting image from Nextcloud. Just mentioning because of the slight similarity, but it's definitely different, and you mentioned this still happened after upgrading to the current iOS TestFlight build.
The fix for that issue was #4345.

**Comment by nikslor** [comment]
Tried hard to reproduce, seems to be gone.. let's close (again).
