### ISSUE TITLE
Toolbar / Notebookbar horizontal scroll with mouse

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#4300]
If the toolbar/notebookbar is bigger than the browser window, there popup buttons to scroll horizontal, but it's not possible to use the mouse wheel.

![image](https://user-images.githubusercontent.com/8517736/155757747-0b78b35c-ac4c-4214-86e7-f8f9bbeddacf.png)

additional scroll with mouse wheel would be cool.

**Comment by thebearon** [comment]
Good idea, and in addition being able to drag it around would be nice, too (it can be swiped on mobile devices).
