### ISSUE TITLE
Bullet / Number List Keyboard Shortcut

### ISSUE THREAD

**Issue by MagsMagnoli** [CollaboraOnline/online#4346]
**Is your feature request related to a problem? Please describe.**
My biggest issue with the platform is the lack of support for creating lists via keyboard shortcut

**Describe the solution you'd like**
In Google Docs, cmd + shift + 8,  cmd + shift + 7, `*`, and `-` are ways to create lists.

**Describe alternatives you've considered**
Currently clicking with the mouse is the only way I know of to create lists and it's a huge pain point

**Additional context**
-

**Comment by Andreas-Kainz** [comment]
No problem with add shortcuts, but can you make a review which shortcut should be used. 

- How cool use shourtcuts
- Shortcuts for bullets (and numbering) in other software

**Comment by rpear** [comment]
Google Docs on WIndows, Chrome OS
Numbered list	Ctrl + Shift + 7
Bulleted list	Ctrl + Shift + 8
Checklist		Ctrl + Shift + 9
![image](https://user-images.githubusercontent.com/80790599/156736737-96405d81-4ffc-403d-8dd4-0f58401f0515.png)
Keyboard shortcuts for Google Docs:   https://support.google.com/docs/answer/179738?hl=en&co=GENIE.Platform%3DDesktop

**Comment by MagsMagnoli** [comment]
@Andreas-Kainz Any updates on this?

**Comment by Ezinnem** [comment]
This can be regarded as an enhancement feature

**Comment by pedropintosilva** [comment]
Thank everyone for the inputs :)

## Bullet list toggle shortcut 
I'm afraid  `CTRL`+`SHIFT`+`8` is already quite known (MSO) for toggling formatting marks. Thus, I would rather us `CTRL`+`SHIFT`+`L` to toggle list.

## Enabling auto numbering

What: https://help.libreoffice.org/7.6/en-GB/text/swriter/guide/auto_numbering.html?&DbPAR=SHARED&System=UNIX

It seems to be that this options is disabled by default on core side. If, we want to enable this behaviour, it seems to be that starting from core side would be the ideal first step. I think @eszkadev had a rough idea on how to do this or at least the best strategy to go about it.

**Comment by Darshan-upadhyay1110** [comment]
First stage i am adding low risk patch for CTRL + Shift + L to add bullet list in text paragraph => https://github.com/CollaboraOnline/online/pull/7122

as next step we will add functionality to insert ordered and unordered bullets by  point one mention in above comment https://github.com/CollaboraOnline/online/issues/4346#issuecomment-1058995688 

> Type 1., i., or I. to start a numbered list. Type * or - to start a bulleted list. You can also type a right parenthesis after the number instead of a period , for example, 1) or i).
