### ISSUE TITLE
!!!Impoart!!! !!!Becareful!!! Why the permission is unable to set??? 

### ISSUE THREAD

**Issue by go-maple** [CollaboraOnline/online#4354]
**Describe the bug**
why open the website, It shows the console like "Uncaught TypeError: Cannot set properties of undefined (setting 'permission')...."

**To Reproduce**
!!!Becareful!!!

**If we open the websit like this "https://office.xxx.cloud/loleaflet/6a844e4/loleaflet.html?WOPISrc=https://office.xxx.cloud/api/wopi/files/app_1009_resource_1036_issue_1186?access_token=o1013u1007t4021fed84f124d23bbd6010e60c8753e111", sometime It doesn't work.

We need add a web which contain iframe and add the url , to open the url in the iframe. It works.**

It alway shows loading. please see the screenshots

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots**
chrome:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/97354215/157164186-3d676008-60ed-49c7-ae42-dd345af69f31.png">
safair:
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/97354215/157164293-556c44c9-f14c-4220-a7bf-0d154aeacefe.png">

server logs:
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/97354215/157167295-b476203f-0d2c-41b3-84e2-d7d71f9b35f4.png">

**Desktop (please complete the following information)**
 - Browser: [e.g. chrome, safari]
 - chrome  version: 99.0.4844.51（正式版本） (x86_64) not work
 - safari version: 15.3 (16612.4.9.1.8, 16612) not work

**Additional context**
docker image version: 
collabora/code:6.4.10.10
and
collabora/code:latest

1.There are two docker images which run in centos8.

2.The wapi server that it works well,I can see it, it can get the checkfileInfo and the content of file.

3.Why the frontend page can't store the server version? see the screenshots of server logs.

**Comment by thebearon** [comment]
As I understand you are trying to set up some kind of integration, but there're no details about that in the description.

Please use the forum if you are looking for support:
https://forum.collaboraonline.com/

And refer to the SDK page on help with setting up your WOPI integration, starting from the basics:
https://sdk.collaboraonline.com/
