### ISSUE TITLE
K8S - 404 Not Found at the end of the minikube instructions

### ISSUE THREAD

**Issue by ohemelaar** [CollaboraOnline/online#4360]
**Describe the bug**
When installing Collabora on minikube using [the instructions](https://github.com/CollaboraOnline/online/tree/master/kubernetes/helm), the `curl` command to check if everything is set up correctly returns a 404.

**To Reproduce**
1. Follow [these instructions](https://github.com/CollaboraOnline/online/tree/master/kubernetes/helm) until you run the `curl` command to check if everything is set up correctly.

**Expected behavior**
Like it says in the instructions, the status code should be 200.

**Actual behavior**
The status code is 404.

**Desktop**
 - OS: Ubuntu 21.10
 - Minikube: v1.25.1
 - Helm: v3.8.0
 - curl: 7.74.0

**Additional context**
After manually editing the Ingress to add this annotation it works:
```
kubernetes.io/ingress.class: haproxy
```

**Comment by thebearon** [comment]
@lpranam Can you please comment on this?

**Comment by genofire** [comment]
@ohemelaar how looks your `values.yaml`:

does none of this options works?:
```yaml
ingress:
  enabled: true
  className: "haproxy"
  annotations:
    kubernetes.io/ingress.class: haproxy
```

**Comment by Darshan-upadhyay1110** [comment]
No response from rporter on this thread. Since Kubernetes (k8s) works fine for others, I’ll close this issue. However, feel free to reopen it if the problem persists.
