### ISSUE TITLE
[UI] String for "Clone Formatting" in context menu too long and incorrect

### ISSUE THREAD

**Issue by cornouws** [CollaboraOnline/online#4369]
At many places, the context menu offers clone formatting.
The item now reads "Clone Formatting (double click for multi selection)"

Too long. And more important: the double click obviously refers to starting the feature from a toolbar, rather then the context menu.

**Comment by rizmut** [comment]
I am fully agree, move the "double click for multi selection" to tooltips instead.

**Comment by thebearon** [comment]
The way I understand, the problem originates from here:
https://github.com/CollaboraOnline/online/blob/4f9315fa0578354a37f33cad86dd5d9fa8255362/scripts/unocommands.py#L235

There are different kinds of labels, in this case, for the UNO command `FormatPaintbrush`, those are `ContextLabel` and `TooltipLabel` (plus the `PopupLabel` in the code referenced above):
https://opengrok.libreoffice.org/xref/core/officecfg/registry/data/org/openoffice/Office/UI/WriterCommands.xcu?r=2aa3097f#2911

- `TooltipLabel` is very clearly the tooltip (`Clone Formatting (double click and Ctrl or Cmd to alter behavior)` for this command).
- `ContextLabel` looks more like something for the context menu (`Clone Formatting`).
- not sure what `PopupLabel` is (not defined for this command), or if there are further label categories.

A fix should probably specify further label categories, and transfer those accordingly.

**Comment by timar** [comment]
The label types are defined in `officecfg/registry/schema/org/openoffice/Office/UI/Commands.xcs`. Let's try to change `unocommands.py`. Ideally the generated result (`browser/src/unocommands.js`) would be the same, expect for the long tooltip of  `FormatPaintbrush`, or at least the other differences would be minimal or negligible. I hope that no big conceptual changes are required.
