### ISSUE TITLE
Remove banners

### ISSUE THREAD

**Issue by R7JANV1** [CollaboraOnline/online#4385]
Is it possible to remove the following banners:
![grafik](https://user-images.githubusercontent.com/90777102/157864847-31968a92-5092-4efa-917c-34a6695a5e3f.png)
![grafik](https://user-images.githubusercontent.com/90777102/157864812-78a25acd-4f8c-49a5-91a0-c6a76c9d3117.png)

The request to remove the Collabora banners can be found on GitHub and many forums.
[remove splash/info/survey screens #1902](https://github.com/nextcloud/richdocuments/issues/1902)
[remove banner #239](https://github.com/nextcloud/all-in-one/issues/239)
[customize collabora a bit #252](https://github.com/nextcloud/all-in-one/pull/252)
and much more...

_Alternatively, buttons can be added with which the banners can be opened._

**Comment by Andreas-Kainz** [comment]
In general CODE is the totaly free and easy to use solution. So I think (as a non collabora member), it's ok to ask for feedback in general.

**Comment by thebearon** [comment]
Please see https://github.com/nextcloud/richdocuments/issues/1902#issuecomment-1057087256
