### ISSUE TITLE
Sidebar alignments 

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#4405]
**Describe the bug**
We now have a couple of elements with text forcibly aligned to the right it seems to have started with https://github.com/CollaboraOnline/online/commit/32f5c874e71c347fa0eaad3c7a9489353efb9744

![ksnip_20220314-165555](https://user-images.githubusercontent.com/65948705/158212034-bb61116f-031d-4a8a-8146-74a8f9f97396.png)
![ksnip_20220314-165506](https://user-images.githubusercontent.com/65948705/158212038-0ba8d4c2-9ad1-4324-b3d7-8448b2ab9b60.png)
Additionally this is can also be an issue with when using RTL. Generally speacking we should avoid text-align to right or left and instead use the [logical properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties)
![ksnip_20220314-165434](https://user-images.githubusercontent.com/65948705/158212040-ca6d27f3-77cb-4d65-bb69-f707f0000b5a.png)

**Comment by Andreas-Kainz** [comment]
Will have a look

**Comment by Andreas-Kainz** [comment]
fixed with the new sidebar simplification
