### ISSUE TITLE
debsums: invalid line (1) in md5sums for code-brand:

### ISSUE THREAD

**Issue by iasdeoupxe** [CollaboraOnline/online#4410]
**Describe the bug**
The following code-brand package on Debian:

```
# dpkg -l | grep code-brand
ii  code-brand                                21.11-17                     all          Collabora Online Development Edition (CODE) branding
```

has a partly invalid `code-brand.md5sums` file. This is causing errors when a check of the package via [debsums](https://packages.debian.org/buster/debsums):

```
# debsums -a -s code-brand 
debsums: invalid line (1) in md5sums for code-brand: DEBIAN/copyright
debsums: invalid line (2) in md5sums for code-brand: DEBIAN/md5sums
debsums: invalid line (3) in md5sums for code-brand: DEBIAN/control
debsums: invalid line (4) in md5sums for code-brand: usr/share/coolwsd/browser/dist/branding-mobile.css
debsums: invalid line (5) in md5sums for code-brand: usr/share/coolwsd/browser/dist/images/lc_underline_branding.svg
debsums: invalid line (6) in md5sums for code-brand: usr/share/coolwsd/browser/dist/images/scroll-double-white.svg
debsums: invalid line (7) in md5sums for code-brand: usr/share/coolwsd/browser/dist/images/lc_spacepara15_branding.svg
debsums: invalid line (8) in md5sums for code-brand: usr/share/coolwsd/browser/dist/images/radio-on-disabled.svg
debsums: invalid line (9) in md5sums for code-brand: usr/share/coolwsd/browser/dist/images/lc_text_branding.svg
<truncated>
debsums: missing file /DEBIAN/copyright (from code-brand package)
debsums: missing file /DEBIAN/md5sums (from code-brand package)
debsums: missing file /DEBIAN/control (from code-brand package)
```

Two problems:

1. Lines like `usr/share/coolwsd/browser/dist/branding-mobile.css` are duplicated, one time with the related md5sum and one time without them (the second is causing the errors
2. Probably too much `DEBIAN/*` lines which are not required at all

**To Reproduce**
1. Install CODE from https://www.collaboraoffice.com/code/linux-packages/ on a Debian system
2. Install the `debsums` package ([debsums](https://packages.debian.org/buster/debsums))
3. Run `debsums -a -s code-brand`
4. See errors listed above

**Expected behavior**
No `invalid line` or `missing file` entries reported by `debsums` for the `code-brand` package

**Actual behavior**
`invalid line` and `missing file` entries reported by `debsums` for the `code-brand` package

**Additional context**
This only affects the `code-brand` packages, all other packages like `collaboraoffice` or `coolwsd` are fine.

This has replaced #4395 due to missing issue template and related labels.

**Comment by timar** [comment]
Thanks for reporting, I fixed the generator script. It will be good in the next release (21.11-24 and 22.05-2).
