### ISSUE TITLE
Mobile Dialog Tabs different behaviour than Sidebar tabs

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#4411]
On mobile the sidebar popup from the bottom and each sidebar section is a separate "tab" if there are more than two tabs, the user see an overview page with the different sections.

![Screenshot_20220314_225625](https://user-images.githubusercontent.com/8517736/158267962-c6b6e092-d353-444f-a1a0-7806c37bcef3.png)

When you load on mobile an dialog window it popup from the bottom compare to the sidebar, but if there are three tabs they were shown as tabs.

![Screenshot_20220314_225457](https://user-images.githubusercontent.com/8517736/158268292-b7fcd9ef-5235-407a-8c43-62f7fb3d07dc.png)

The alignment of the tab labels can be fixed, but I would suggest to have the same behaviour for dailogues than for sidebars. If there are more than two tabs, the tabs will be shown in an overview page where the user has to navigate into one tab.

**Comment by Andreas-Kainz** [comment]
Issue was first found from @eszkadev at #4400 @pedropintosilva do you have an suggestion?

**Comment by Ezinnem** [comment]
@eszkadev , @pedropintosilva

**Comment by Darshan-upadhyay1110** [comment]
https://github.com/CollaboraOnline/online/commit/e502d2bcef2bc73c16a15c5574c05dfe2512e118
