### ISSUE TITLE
Dialog was shown with JS on mobile but not on desktop

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#4412]
#### Mobile
![Screenshot_20220314_225457](https://user-images.githubusercontent.com/8517736/158268663-8bffa14c-0c52-41e4-b5c4-9cf292fa2495.png)

#### Desktop
![Screenshot_20220314_225606](https://user-images.githubusercontent.com/8517736/158268678-c6da5f06-bd83-45d4-82a8-6245dc509e39.png)

Why are some screenshots available on mobile with JS and on desktop without, @eszkadev?

**Comment by eszkadev** [comment]
I said on the last community meeting: "we didn't support all the widgets on desktop at that time so we enabled it only for mobile"

**Comment by eszkadev** [comment]
I have something for you :)

https://gerrit.libreoffice.org/c/core/+/131580

**Comment by Andreas-Kainz** [comment]
cool thanks. I use the precompiled cool build will it be added there?

wget https://github.com/CollaboraOnline/online/releases/download/for-code-assets/core-co-2021-assets.tar.gz

**Comment by eszkadev** [comment]
yes, but later. Now it's not even merged
