### ISSUE TITLE
JSdialog: find controls with outdated prefix in their id

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#4443]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @eszkadev 

### Detailed description and rationale
In some cases we add 'table-' prefix for toolboxes due to
some old requirements in the mobile-wizard. We need to find these
modified ids in a fallback on widget update.

In the future we should get rid of 'table-' prefix.
### Code pointers
Example: [jsdialog: find also controls with modified id](https://github.com/CollaboraOnline/online/pull/4436/commits/a57e892b96d58ac15f789bee8e67f74f13e7f1dc)

**Comment by eszkadev** [comment]
Best would be to identify all the CSS rules pointing to 'table-*' ids and replace them with something different.
Then we will be able to change safely the code adding that prefix.

**Comment by pedropintosilva** [comment]
I think this is done, right @eszkadev ?
