### ISSUE TITLE
Collabora Office on Chromebook broken OK/Cancel buttons in dialogue boxes.

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#4463]
Dialogue boxes are broken in Collabora Office on my Chromebook.  e.g.  Find and Replace and Table Properties.

The dialogues open and you can edit their details, but the Cancel and OK buttons do not work, the Esc key and X at the top right allow you to close the dialogue. So it is not possible to use them. See [video](https://user-images.githubusercontent.com/80790599/159684124-74d4b50a-738e-41da-b9fe-bfeedd288908.mp4).

And possibly related: When these dialogues are open, it is still possible to change the keyboard focus to the document behind the dialogue.

Chrome OS: Version 99.0.4844.57 (Official Build) (32-bit) 
App: COOLWSD version: 6.4.14 git hash: 4e4ef7aa LOKit version: built on a great technology base Collabora Office 6.4-50 git hash: bda68f9

**Comment by timar** [comment]
Is it still reproducible with the latest Collabora Office 21.11?

**Comment by rpear** [comment]
This is now fixed, thank you :-)

**Comment by kendy** [comment]
Very good to hear, let me close the bug then.  Thank you @rpear!
