### ISSUE TITLE
Latest Docker Container doesn't work HTTPS Errors

### ISSUE THREAD

**Issue by TheNamelessWonderer** [CollaboraOnline/online#4476]
**Describe the bug**
The latest container doesn't work I get:  Failed to verify the certificate of cloud.server.org. The certificate is valid and from Let's Encrypt.

**To Reproduce**
1. Download the latest docker image
2. Open a document in Nextcloud
3. Look at log

**Expected behavior**
The document should open.

**Actual behavior**
The document fails to open.

**Screenshots**

**Desktop (please complete the following information)**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 98.0.2

**Smartphone (please complete the following information)**
 - Device: iPhone SE Gen 1
 - OS: iOS 14.8.1
 - Browser: Nextcloud App
 - Version: Latest version

**Additional context**
Logs:
[logs.txt](https://github.com/CollaboraOnline/online/files/8346129/logs.txt)

Downgrading to 21.11.2.4.1 makes everything work again with the exact same config.

**Comment by juliushaertl** [comment]
I also see the with 21.11.3.3.1 and can confirm that it does not occur on 21.11.2.4.1. The SSL certificate also seems to be accepted just fine when using curl within the container.

**Comment by gabor-ig** [comment]
I am running the native package (not Docker) and I am getting the exact same issue since the upgrade to the newest version. So confirming not only Docker.

**Comment by SnejPro** [comment]
I have the same error.

**Comment by thebearon** [comment]
Is this the same as #4480, and fixed now with 21.11.3.4-1?

**Comment by TheNamelessWonderer** [comment]
Yep it is fixed for me!
