### ISSUE TITLE
iOS app: sidebar buttons in impress are shown in "read only" mode

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#450]
**Describe the bug**
When opening a presentation (read only mode) using the iOS app, there are three sidebar buttons displayed at the very top of the window. After switching to edit mode the buttons "jump" down and change their position.

I believe those buttons should not be visible in "read only" mode.

Further more I also believe, the sidebar buttons should not overlap content of the notebook bar. So may be the idea is to have them where they are during "read only" mode and the position of the "edit" mode is wrong? I don't know what the intended behavior is.

**To Reproduce**
1. Open a presentation using the iOS app
2. Check the icons drawn in the left upper corner
3. Edit into edit mode
4. Check the icons drawn in the left upper corner

**Expected behavior**
In "read only" mode the sidebar icons should not be visible.

**Actual behavior**
In "read only" mode the sidebar icons are visible.

**Screenshots**
![sidebar_buttons_in_read_only_mode](https://user-images.githubusercontent.com/1211300/97348454-71e22200-188e-11eb-8798-e955ca360241.png)

![sidebar_buttons_in_edit_mode](https://user-images.githubusercontent.com/1211300/97348628-b53c9080-188e-11eb-9380-6e7c58eed597.png)

**Tablet**
 - OS: iOS 14.1
 - Version: 6.4.0 (5)

**Comment by thebearon** [comment]
Can be reproduced in Chrome's responsive view by removing the check on `window.ThisIsTheiOSApp` in the following line:
https://github.com/CollaboraOnline/online/blob/5999a5b7cc7815f88484ff4f55e06406d1add068/loleaflet/src/control/Control.Notebookbar.js#L98

Otherwise, currently if it's opened from the browser, there are no sidebar chooser buttons at all on the notebookbar.

**Comment by tml1024** [comment]
@pedropintosilva Should this be cherry-picked to the co-6-4 branch, too?

**Comment by pedropintosilva** [comment]
@tml1024 yes.
I was planing on doing a round of checking cherry-picking later this week, but sure I can do it now if you need it : )

**Comment by tml1024** [comment]
@pedropintosilva Thanks!

**Comment by tml1024** [comment]
This can be closed now, I assume.
