### ISSUE TITLE
Handle ESC key event in Autofilter

### ISSUE THREAD

**Issue by eszkadev** [CollaboraOnline/online#4515]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @eszkadev 

### Detailed description and rationale
Autofilter dropdown should be closed when we press ESC key on keyboard.

### Code pointers
esc handling in Dialogs : https://github.com/CollaboraOnline/online/blob/master/browser/src/control/Control.JSDialog.js#L398
Autofilter code: https://github.com/CollaboraOnline/online/blob/master/browser/src/control/Control.AutofilterDropdown.js
global key event handler: https://github.com/CollaboraOnline/online/blob/master/browser/src/map/handler/Map.Keyboard.js#L256
we can remember reference to autofilter here: https://github.com/CollaboraOnline/online/blob/master/browser/src/control/Control.UIManager.js#L83

### Additional notes, tips & tricks
![autofilter](https://user-images.githubusercontent.com/5307369/161237796-27410321-c091-43f5-a5ee-f583e31364cf.png)

to create autofilter: select range with data, then use Data -> Autofilter from menubar  or  Data tab in the notebookbar

**Comment by eszkadev** [comment]
This is needed only for Online working with older core versions (< 22.05). In core 22.05 autofilter dropdown was unified with other popups so it is handled by Control.JSDialog.js where ESC key is already handled.

**Comment by pedropintosilva** [comment]
this has been fixed
