### ISSUE TITLE
Document did not open in iOS App

### ISSUE THREAD

**Issue by ZiuTy115** [CollaboraOnline/online#4516]
**Describe the bug**
If i try to open the document i could pass the welcmoe screen but than i have no button with the pen to edit document

**Expected behavior**
Open document and work on.

**Actual behavior**
docment stays open but not possible to edit it 

**Log Error**
wsd-08013-362797 2022-04-01 11:57:27.358594 +0200 [ docbroker_04a ] DBG  Forwarding canceltiles request: canceltiles 221,220,219,218,217,207,206,205,204,203,| wsd/DocumentBroker.cpp:2860
| wsd/ClientSession.cpp:540
handler@https://office.blabla.de/browser/2ea9477/bundle.js:1:1788425
onMessage@https://office.blabla.de/browser/2ea9477/bundle.js:1:2635948
parse@[native code]
JSON Parse error: Unexpected identifier "updatecheck"
}
  "column": 2635948
  "line": 1,
  "source": "https://office.blabla.de/browser/2ea9477/bundle.js",
  "message": "SyntaxError: JSON Parse error: Unexpected identifier \"updatecheck\"",
  "vendor": "apple computer, inc.",
  "userAgent": "mozilla/5.0 (ios) nextcloud-ios/4.3.1",
wsd-08013-362797 2022-04-01 11:57:27.357735 +0200 [ docbroker_04a ] ERR  jserror {
| wsd/ClientSession.cpp:540
handler@https://office.blabla.de/browser/2ea9477/bundle.js:1:1788425
onMessage@https://office.blabla.de/browser/2ea9477/bundle.js:1:2633338
parse@[native code]
JSON Parse error: Unexpected identifier "updatecheck"
}
  "column": 2633338
  "line": 1,
  "source": "https://office.blabla.de/browser/2ea9477/bundle.js",
  "message": "SyntaxError: JSON Parse error: Unexpected identifier \"updatecheck\"",
  "vendor": "apple computer, inc.",
  "userAgent": "mozilla/5.0 (ios) nextcloud-ios/4.3.1",
wsd-08013-362797 2022-04-01 11:57:27.357691 +0200 [ docbroker_04a ] ERR  jserror {

**Smartphone**
 - Device: [e.g. iPhone12]
 - OS: [e.g. iOS15.3.1]
 - Nextcloud app

**Comment by overflow-ITA** [comment]
me too on android

**Comment by thebearon** [comment]
This should be fixed with the latest CODE version, 21.11.3.6, please update and check again.
