### ISSUE TITLE
disconnection prevents editing

### ISSUE THREAD

**Issue by livier** [CollaboraOnline/online#4540]
**Describe the bug**
When trying to open a document, even a new empty one, users can't edit itcan't (CODE integrated as Nextcloud's extention  Collabora Online - Built-in CODE Server 21.11.204 )

**To Reproduce**
1. Go to a folder with odt documents
2. Click on 'one of them
4. Differents things may append
- See error "le serveur a été déconnecté" (in french here) appear very fast
- Document opens, but impossible to edit it

**Expected behavior**
Opening the document and be able to edit it

**Actual behavior**
To be a little more specific. Another test ...  I could begin to edit for about one second, then the message "serveur disconnected" apear, and no more possibility to edit. Other times I did not see the delay beforethe disconnection. 

**Screenshots**

**Desktop (please complete the following information)**
 - Each user with a different config ( linux Neon for me with firefox, others with Windows ...)

**Additional context**
Some days ago, it was a bit dirrerent : We could edit the document, but when people had interuptions on their connexion (or log out for a moment) and come back, their logos appeared several times in the top of the document. Seems deiting became slow when too much of these logos appeared. Usually, we can have 4 to 6 users seeing the document at the same time, While only 2 are editing

**Comment by pedropintosilva** [comment]
Thanks @livier for taking the time to report this,

> their logos appeared several times in the top of the document. Seems deiting became slow when too much of these logos appeared. Usually, we can have 4 to 6 users seeing the document at the same time, While only 2 are editing

In there ^ do you means user avatars?

**Comment by livier** [comment]
Outch, I thaugt that I had answer this a few weeks ago. My message is now flying under old clouds :-o

Yes I think it can be named "user avatars"

Updates have been dones now, I will come back if difficuties come back. Not soon I hope ;-)
