### ISSUE TITLE
Draw Grid and Helplines

### ISSUE THREAD

**Issue by JoshuaPettus** [CollaboraOnline/online#4556]
I realize the draw portion of collaboraonline is extremely new, but one feature I would like to see from the regular LibreOffice is Draw's grid and helplines feature.  Honestly it's a must have if I'm going to use this as a real flowchart/drawing app.

**Comment by Andreas-Kainz** [comment]
at least the setting isn't perfect in LibreOffice, but yes, without any snap option draw isn't usefull.

**Comment by JoshuaPettus** [comment]
Oh definitely...  I feel in general Draw could use some more polish in LO to make it what it truly deserves be.  But it has been slowly making progress and I'm hopeful. I'd love to see this web version be as useful.

**Comment by eszkadev** [comment]
implemented in: https://github.com/CollaboraOnline/online/pull/10147
