### ISSUE TITLE
new 21.11.3.6 not working on Chrome OS on Acer R11

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#4609]
On my Chromebook, Acer R11, the menu, sidebar and statusbar appear but the document does not. It is blank as shown in the following screenshot. It is the same in the 3 apps. This is the same with new files and existing ones. I have tried deleting app cache and storage.

On another Chromebook model, HP X360, logged on as me (same user), it appears to work fine.
On another Chromebook model, HP X360, logged on as a different user, it appears to work fine.
On my Chromebook, Acer R11, logged on as a different user, it appears to work fine.
Then **a ChromeOS update, reboot and it is all OK.... please close this bug**, there must have been a bug in Chrome OS 100 that Google fixed.

Writer:
![Screenshot 2022-04-15 2 01 27 PM](https://user-images.githubusercontent.com/80790599/163516485-594f5349-591e-42d2-90a9-c8425686b311.png)

Calc:
Note: It also does this weird windowing thing when Restore is clicked (the app minimise/max thing at top right.
Note: a cell is highlighted, it is not possible to move the selection highlight.

![Screenshot 2022-04-15 2 43 48 PM](https://user-images.githubusercontent.com/80790599/163519629-5758b8d0-80b3-4b15-b769-dc266f153a5b.png)

Presentation:
![Screenshot 2022-04-15 2 47 50 PM](https://user-images.githubusercontent.com/80790599/163519796-a8a7ad77-fcb8-473d-9de1-a45f51b3c981.png)

**Comment by thebearon** [comment]
As I understand this should be closed. Do clarify if that isn't the case.
