### ISSUE TITLE
Validity drop down not working on android - Calc

### ISSUE THREAD

**Issue by walzmyn** [CollaboraOnline/online#4618]
**Describe the bug**
dropdown menus in a cell via the Validity tool do not work in Android. They do work in iOS. The down arrow is displayed, but cannot be clicked on to drop the list down.

**To Reproduce**
create file with a drop down made with the validity tool
move it to an Android device and try to use it.

**Expected behavior**
the list to drop down when you tap on the arrow

**Actual behavior**
nothing.

**Screenshots**

**Desktop (please complete the following information)**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information)**
 - Device: Onplus 8 Pro, Samsung S22 Ultra, Samsung Tab 8
 - OS: android
 - Browser: 
 - Version: Android 12, Collaboara 21.11.3.6

**Additional context**

**Comment by Ezinnem** [comment]
I get the list when I tap on Collabora Office app 21.11.3.5 git hash: [03806109](https://github.com/CollaboraOnline/online/commits/03806109)

**Comment by walzmyn** [comment]
I've been trying to get this to work for 6 months. It is now working. I did nothing. Who knows.
