### ISSUE TITLE
webpage loading

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#4629]
If you have an webpage you can define which components will be loaded first, second, ...

At cool it look like the loading steps are:

**Comment by Andreas-Kainz** [comment]
1. Sidebar
2. Header area
3. content
![2022-04-20 09_22_56-writer odt - Files - Nextcloud](https://user-images.githubusercontent.com/8517736/164180358-00da8979-71da-490a-a679-96681e6aaea2.png)

**Comment by Andreas-Kainz** [comment]
As the sidebar is for editing stuff (when you see and click to the content), I suggest to show the sidebar as last element.

1. Header area
2. Toolbar / Notebookbar
3. Content
4. Sidebar (if sidebar is visible by the user, cause now the sidebar was loaded than checked if hidden and than hidden, as you first load the toolbar you know the status of the sidebar and can load sidebar ONLY if the command was defined to view the sidebar)

**Comment by Andreas-Kainz** [comment]
@eszkadev do you know how the loading work?

**Comment by Andreas-Kainz** [comment]
This will improve the user experience (it's faster) AND when hide sidebar it's also realy faster.

**Comment by pedropintosilva** [comment]
Thanks @Andreas-Kainz for looking at this, I agree, ideally the sidebar would appear upon content is displayed

**Comment by Andreas-Kainz** [comment]
and ONLY if the sidebar is selected to view.

**Comment by eszkadev** [comment]
I think we can do this just using `visibility: false` or `display: none` in sidebar until we load rest of the UI components.

**Comment by eszkadev** [comment]
^ that was simple solution, better would be to do what I said here: https://github.com/CollaboraOnline/online/issues/3552
"start without sidebar and then open it if needed" instead of "start sidebar and hide if not needed"
