### ISSUE TITLE
Behind reverse proxy collabora generates HTTP urls instead of HTTPS like the rest of nextcloud

### ISSUE THREAD

**Issue by Polve** [CollaboraOnline/online#4641]
I run nextcloud behind a reverse proxy.

The proxy is connected to my instance via normal HTTP while the web server handles the SSL connection.

I set up nextcloud to use HTTPS everywhere (also using overwriteprotocol and overwrite.cli.url) and nextcloud works perfectly, but collabora does not.

When I try to edit a document I get the usual loader but in the console I can see the browser blocking a few urls because some collabora resources are being loaded using http instead of https, for example:

```
Content Security Policy: Il caricamento di una risorsa su http://x.y.z/apps/richdocumentscode/proxy.php?status è stato bloccato dalle impostazioni della pagina (“connect-src”).
```

nexcloud version 23.0.3, collabora version 21.11.306.

Using Firefox 99.0.1

**Comment by aaronschif** [comment]
I think I had the same issue and solved it using `--o:ssl.enable=false --o:ssl.termination=true`.
