### ISSUE TITLE
document structure "sidebar"

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#4643]
Have the document structure like in google docs.

![2022-04-22 12_57_03-Libreoffice Design Session 2017-04-03 - Bullets   Numbering - Google Docs](https://user-images.githubusercontent.com/8517736/164701815-d7dd2625-31ca-4b1b-8a67-3040f23a988b.png)

It's so simple AND easy to understood. Maybe it can be combiled with the scrollbar, at least on mobile.

**Comment by Ezinnem** [comment]
@eszkadev. @pedropintosilva

**Comment by pedropintosilva** [comment]
We now have finally enabled the navigator. The discussion went on in the following issue https://github.com/CollaboraOnline/online/issues/6248#issuecomment-1527143532
