### ISSUE TITLE
No jump to the hit when searching the table

### ISSUE THREAD

**Issue by HappyPony** [CollaboraOnline/online#4651]
**Describe the bug**
when I search for a string “XY123”, the string is found and the marker jumps to that row, but the display does not change.

**To Reproduce**
1. open _.ods_ file
2. search for string 'XY123'
3. Found line is not displayed
4. Scroll to row with  string 'XY123'
5. marker is positioned in the line with the string 'XY123'.
6. the error is that the display does not change, the line with the string 'XY123' is not automatically displayed

**Expected behavior**
the line with the string 'XY123' is automatically displayed as a search result

**Actual behavior**
display does not change, the line with the string 'XY123' is not automatically displayed

**Screenshots**

**Desktop (please complete the following information)**
 - OS: Android 12
 - Browser: --------

**Smartphone (please complete the following information)**
 - Device: Samsung Galaxy Note 10
 - OS: Android 12
 - Browser: -
 - Version: -

**Additional context**
= Collabora Office =
COOLWSD version: 6.4.14
git hash: 4e4ef7aa

LOKit version:
built on a great technology base
Collabora Office 6.4-50
git hash: bda68f9

**Comment by Ezinnem** [comment]
This seems similar to an issue on #4394 

@HappyPony, Please can you confirm that you experience the same issue as reported on #4394

**Comment by HappyPony** [comment]
Yes, my experience the same issue as reported on https://github.com/CollaboraOnline/online/issues/4394

**Comment by thebearon** [comment]
Let's close this as duplicate, then.
