### ISSUE TITLE
21.11.3.6.1 and later: Container doesn't start

### ISSUE THREAD

**Issue by haziegler** [CollaboraOnline/online#4659]
**Describe the bug**
With version 21.11.3.6.1 and later, the container doesn't start.

**To Reproduce**
1. podman pull collabora/code
2. podman run -t -d -p 127.0.0.1:9980:9980 -e 'domain=example.com' --cap-add MKNOD --name collabora-code collabora/code

**Expected behavior**
Container should be running and listed in the output of "podman container ls"

**Actual behavior**
Container is not running (neither listed in "podman container ls" nor is there a "podman" process in "ps" output).

**Server**
 - OS: RHEL 8.5 (all available updates installed)
 - podman-3.4.2-9.module+el8.5.0+13852+150547f7.x86_64

**Workaround:**
Use an older version:
podman pull collabora/code:21.11.3.4.1
podman run -t -d -p 127.0.0.1:9980:9980 -e 'domain=example.com' --cap-add MKNOD --name collabora-code collabora/code:21.11.3.4.1

**Comment by sebastiaanveld** [comment]
Section
-e 'domain=example.com'
changed to
-e aliasgroup1=https://example.com:443

https://sdk.collaboraonline.com/docs/installation/CODE_Docker_image.html

**Comment by thebearon** [comment]
As @sebastiaanveld noted, the `domain` parameter isn't valid anymore, please update your parameters.

**Comment by WhiteBahamut** [comment]
Note sure if this is the only problem. I thought this would also be my problem, but after adding my container is in an endless loop after
> Server: COOLWSD HTTP Server 21.11.4.2
> Upgrade: websocket
> Connection: Upgrade

basically a log flood of

>kit-00040-00038 2022-05-14 21:19:49.257707 +0000 [ kit_spare_001 ] INF  Linking file "/opt/collaboraoffice/program/resource/es/LC_MESSAGES/frm.mo" to "/opt/cool/child-roots/I86IlOlNNOR43hIV/lo/program/resource/es/LC_MESSAGES/frm.mo"| kit/Kit.cpp:296
> .....
> wsd-00001-00037 2022-05-14 21:19:52.029336 +0000 [ prisoner_poll ] TRC  Starting handling poll results of prisoner_poll #21 at index 1 (of 2): 0| net/Socket.cpp:437
> wsd-00001-00037 2022-05-14 21:19:52.029417 +0000 [ prisoner_poll ] TRC  #21: revents: 0x0| ./net/Socket.hpp:1286
> wsd-00001-00037 2022-05-14 21:19:52.029487 +0000 [ prisoner_poll ] TRC  #21: Sending  ping.| ./net/WebSocketHandler.hpp:556
> wsd-00001-00037 2022-05-14 21:19:52.029563 +0000 [ prisoner_poll ] TRC  WebSocketHandler::sendFrame: Writing to #21 1 bytes in addition to 0 bytes buffered.| ./net/WebSocketHandler.hpp:734
> wsd-00001-00037 2022-05-14 21:19:52.029642 +0000 [ prisoner_poll ] TRC  #20: setupPollFds getPollEvents: 0x1| net/Socket.hpp:852
> ...

I have set
        - name: server_name
          value: "collabora.my-domain.de"
        - name: aliasgroup1
          value: "https://my-domain.de:443,https://nc.my-domain.de:443"

I am using 21.11.4.2.1. Reverting everything back to 6.4.14.3 and everything works fine. Sadly no version > 6.4.14.3 worked for me at all.
