### ISSUE TITLE
Basic Shapes should be Shapes only

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#4672]
As you can see in the screenshot, the insert basic shapes didn't contain only basic shapes. The insert command contain ALL shapes which are available within cool / LibO.

So I suggest to rename the string to Shapes (in addition is't shorter).

![grafik](https://user-images.githubusercontent.com/8517736/165109496-2276c41e-b34a-4d81-bda4-9d581fbee4a3.png)

**Comment by pedropintosilva** [comment]
hm I think this was fixed already I think I did 2 times, but probably the unocommands.js got re-updated and reverted back to the original string

**Comment by pedropintosilva** [comment]
maybe better to fix it in another way
