### ISSUE TITLE
No status bar when editing spreadsheets

### ISSUE THREAD

**Issue by u451f** [CollaboraOnline/online#4706]
![desktopview](https://user-images.githubusercontent.com/6314248/166010009-02af0f3b-a1a0-4c95-82cf-fd4e6f2df9a1.jpg)

**Describe the bug**

Well I guess it might be a feature but I haven't found its utility to be honest. On text documents I have a status bar that I can use to search for words. On spreadsheet documents (tried only with ods), there is no status bar.

**To Reproduce**
In the menu, go to View →Status bar. When you have a spread sheet open, this menu entry does not exist at all.

**Expected behavior**
There should be a status bar for spreadsheets which helps searching for words in the sheets.
**Desktop**
 - OS: Debian
 - Browser: Chromium and Firefox ESR
 - Version: 90 and 91.8

We use CODE.

**Comment by u451f** [comment]
Also see #4707

**Comment by Ezinnem** [comment]
In Tabbed UI, I am able to find the Toggle Status bar option under View and also the Show Status bar option in the Compact UI mode.

I tested using COOLWSD version: 21.11.4.1 snapshot git hash: [db0f129](https://github.com/CollaboraOnline/online/commits/db0f129)

**Comment by thebearon** [comment]
Yes, presumably this CODE version is too old, the menu item has been added fairly recently. Please update your CODE and check again.

**Comment by u451f** [comment]
@Ezinnem so you tested this with spreadsheets specifically? @thebearon is there an official version of CODE which includes this essential feature or is this only available using a git snapshot?

**Comment by thebearon** [comment]
@u451f Sure, the latest version should have the fix.
