### ISSUE TITLE
Shortcut to / and search for words in spreadsheets not working on desktop

### ISSUE THREAD

**Issue by u451f** [CollaboraOnline/online#4707]
**Describe the bug**

In the past, Ctrl+F would work to search for words in any kind of document. Now, in text documents, we have to use Ctrl+Command+F and we have to use the status bar to type the word one is searching for. In spreadsheets (tested only with ods), neither Ctrl+F nor Ctrl+Command+F is working. One has to use the complicated Find and Replace dialog when working from a desktop. When I pretend to be a smartphone, I can search in documents with the status bar though, see screenshots below.

**To Reproduce**
Open an ods file. Try to type Ctrl+Command+F → It does not work at all, nothing happens,
Now, look for a search icon, or search entry in the menu. → Neither exists.

**Expected behavior**
When I type Ctrl+Command+F, the status bar or a small popup would open and allow for searching a string in the document. And even show the amount of occurrences and help me navigate from one occurence to the next.

**Actual behavior**
trying the search shortcut: In a spreadsheet nothing happens. In a text file, if the status bar is open, the focus gets to the search field. If the status bar is hidden, nothing happens.
There is also no other way to search in a document except using the complicated find&replace dialog.

**Desktop (please complete the following information)**
 - OS: Debian
 - Browser: Chrome and Firefox
 - Version: 90 and 91.8

My colleagues confirm this behavior using Chrome and Firefox on macOS.

**Additional context**

We run NC 23.0.3. App Collabora Online CODE 21.11.306. And the CODE server installed on a separate machine.

On desktop I don't have a status bar nor a search menu.
![desktopview](https://user-images.githubusercontent.com/6314248/166011920-502c9332-8758-437d-9595-9c8f366a7803.jpg)

On "mobile" I do see "Search" in the menu however:
![mobileview](https://user-images.githubusercontent.com/6314248/166011995-a8637187-0183-4236-bd9a-3b88f9c64461.jpg)

…and when I click "Search" in the menu, suprise, I have a status bar that I can use to search for words, like on a text file.
![mobile view 2](https://user-images.githubusercontent.com/6314248/166011971-0bbcb8a1-54b4-454c-973d-0a97da45ad15.jpg)

**Comment by u451f** [comment]
Might also be linked to #4394

**Comment by Ezinnem** [comment]
Ctrl + F works as expected

I tested using COOLWSD version: 21.11.4.1 snapshot git hash: [db0f129](https://github.com/CollaboraOnline/online/commits/db0f129)

**Comment by pedropintosilva** [comment]
Thanks @u451f for taking the time to not only test it and do just an in-depth report! :clap: So, the good news is these problems should have been fixed already. Could you please update your CODE and report back? Meanwhile I will test the shortcuts problem once again

**Comment by u451f** [comment]
Thanks a lot @Ezinnem and @pedropintosilva! I will try to update the machine but it might take some time, as I'm a bit busy during the next three days. But I will report back as soon as possible.

**Comment by u451f** [comment]
Hi! It was super annoying to upgrade because of https://github.com/nextcloud/richdocuments/issues/1904 but I did manage in the end and indeed it's all there in 33ff190 aka 21.11.4.2-1 and Ctrl+F is working :)
