### ISSUE TITLE
Mobile content space

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#4713]
This issue will show how much space cool will offer on mobile for the real content.

#### Mobile Layour Review - Document open with a web browser
- left COOL running in a webbrowser (firefox mobile or chrome mobile
- right GDocs app (GDoc's didn't start within a webbrowser on my mobile)

| **COOL**                                                                                                                        | **Gdocs**                                                                                                                       |
|-----------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------|
| ![20220501151817.jpg](https://user-images.githubusercontent.com/8517736/166148038-3c8acc9a-3178-45b4-918f-379158a748ea.jpg) | ![20220501153701.jpg](https://user-images.githubusercontent.com/8517736/166148389-3885ef8f-3892-4309-a471-621a4440de00.jpg) |
| ![20220501152921.jpg](https://user-images.githubusercontent.com/8517736/166148127-4d107036-1936-4535-84c3-0757d55b1635.jpg) | ![20220501153701.jpg](https://user-images.githubusercontent.com/8517736/166148389-3885ef8f-3892-4309-a471-621a4440de00.jpg) |
| ![20220501153106.jpg](https://user-images.githubusercontent.com/8517736/166148153-ed834375-26d9-425a-aab9-90babe47e645.jpg) | ![20220501153952.jpg](https://user-images.githubusercontent.com/8517736/166148479-d578e431-c1f4-41ed-a80a-774fae6954d0.jpg) |
| ![20220501153226.jpg](https://user-images.githubusercontent.com/8517736/166148197-69db54d1-7f82-4932-af82-af49850a8af8.jpg) | ![20220501154104.jpg](https://user-images.githubusercontent.com/8517736/166148515-4b88042a-1a3c-4607-81c2-34ea6eb629df.jpg) |

**Comment by Andreas-Kainz** [comment]
#### Gdocs
![20220501153701.jpg](https://user-images.githubusercontent.com/8517736/166148389-3885ef8f-3892-4309-a471-621a4440de00.jpg)
It wasn't possible to use Gdocs online on mobile it was always linked to the mobile app. I also have collabora online installed, but staging didn't ask to edit the file with the mobile app

#### gravel
![20220501153952.jpg](https://user-images.githubusercontent.com/8517736/166148479-d578e431-c1f4-41ed-a80a-774fae6954d0.jpg)

#### gpresent
![20220501154104.jpg](https://user-images.githubusercontent.com/8517736/166148515-4b88042a-1a3c-4607-81c2-34ea6eb629df.jpg)

**Comment by Andreas-Kainz** [comment]
And now with collabora online mobile Android App

#### writer
![20220501154220.jpg](https://user-images.githubusercontent.com/8517736/166148606-3a37ac45-a791-4173-98cc-5bf167b9ba30.jpg)

#### calc
![20220501154250.jpg](https://user-images.githubusercontent.com/8517736/166148616-e2f39e07-c592-4473-8e6c-f42d77370496.jpg)

#### impress
![20220501154409.jpg](https://user-images.githubusercontent.com/8517736/166148656-6061b119-270a-4da2-9d63-163818adcab4.jpg)

**Comment by pedropintosilva** [comment]
@Andreas-Kainz maybe better make these images inside of tables

**Comment by Andreas-Kainz** [comment]
Hide the tabs and page previews when the keyboard was open would be good cause than the user is in write mode and didn't add a spreadsheet or a new slide.
