### ISSUE TITLE
Misplaced cursor and text boxes contents with zoomed spreadsheet

### ISSUE THREAD

**Issue by s8321414** [CollaboraOnline/online#4735]
**Describe the bug**
Misplaced text boxes cursor and contents

**To Reproduce**
1. Set system zoom level to non-100% (Example: 125% or larger)
2. Open a spreadsheet files
3. Scroll to M50 or any other cells not in top left first tile
4. Insert a text box
5. Type some words in that box
6. Check cursor location or exit text box then re-enter it

**Expected behavior**
All contents and cursor are in text box

**Actual behavior**
Cursor is out of text box

**Screenshots**
![VirtualBox_Windows 10_05_05_2022_10_42_29](https://user-images.githubusercontent.com/9457283/166857262-b798e619-3ee1-480d-95be-8d52e0a5f27e.png)

**Desktop (please complete the following information)**
 - OS: Windows 10
 - Browser: Edge, Firefox, Chrome
 - Version: Edge 99, Firefox 100, Chrome 101

**Comment by Ezinnem** [comment]
Seen on 
COOLWSD version: 22.05.0.1 git hash: [2163e2f0](https://github.com/CollaboraOnline/online/commits/2163e2f0)(E)

**Comment by Darshan-upadhyay1110** [comment]
Works OK in spreadsheet

COOLWSD version: 24.04.5.2 (git hash: df56d78c)
LOKit version: Collabora OfficeDev 24.04.5.2 (git hash: b57fd97)
Served by: Ubuntu 23.10
Server ID: f3983cff
