### ISSUE TITLE
Excel sheet: Complete freeze when popup menu of a cell is opened (Introduced 21.11.306)

### ISSUE THREAD

**Issue by jacotec** [CollaboraOnline/online#4757]
**Describe the bug**
When an Excel sheet contains a dropdown menu in a cell, the browser window fully freezes when opening the popup.

This issue was introduced in 21.11.306 and was working befroe

**To Reproduce**
1. Open an Excel Sheet with dropdown cells
2. Click on the cell to open the dropdown
3. The browser window/tab fully freezes, no further action is possible
4. The selected state in the dropdown is however saved and is still there when reloading the browser tab

**Expected behavior**
After choosing a selection the popup should close and the entry should be in the cell

**Actual behavior**
Currently the full browser tab freezes, no actions are possible (no menu actions etc.)

**Screenshots**
![image](https://user-images.githubusercontent.com/3321655/167607943-578d1093-e552-4428-a867-65bd5b050b29.png)

**Desktop (please complete the following information)**
 - OS: Windows 10, Mac OS Big Sur (OS independent)
 - Browser: Chrome, Edge, Safari, Firefox
 - Version: 21.11.4.2  (**Issue started with 21.11.306, was working before!**)

**Smartphone (please complete the following information)**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by Ezinnem** [comment]
This is similar to https://github.com/CollaboraOnline/richdocumentscode/issues/178


Reproducible in:
COOLWSD version: 21.11.4.2snapshot git hash: [c0db238](https://github.com/CollaboraOnline/online/commits/c0db238)

**Comment by jacotec** [comment]
@Ezinnem Yap, I posted it in richdocumentscode before I realized that richdocumentscode is the full Nextcloud app. But it's in fact a core thing (I'm running a CODE server in a VM for my Nextclouds and not the app itself)

**Comment by Ezinnem** [comment]
The fix has been made.

This issue is very similar to #4716

**Comment by jacotec** [comment]
@Ezinnem Should this be in version 21.06.30.1? Because after updating to it, I still see this issue ...

**Comment by thebearon** [comment]
@jacotec It should be part of 21.11.5.3.
