### ISSUE TITLE
Collabora destroying letterhead layout (Position frame issue?)

### ISSUE THREAD

**Issue by jacotec** [CollaboraOnline/online#4758]
**Describe the bug**
When I open my letterhead with CODE, the layout is messed. Once any changes are saved, the original layout is also still messed when opening the .docx with Word.

**To Reproduce**
1. Open my sample in Word
2. Open my sample in CODE
3. See the difference

**Expected behavior**
The original layout should be the same in CODE as in Word. The content in position frames should be at the same position

**Actual behavior**
Content in the upper position frame with the address field is messed and partially lost (underline)

**Screenshots**
Original Layout in Word. Position frames are marked red:

![image](https://user-images.githubusercontent.com/3321655/167612123-bbf9fe99-6fa8-4920-bb04-52ef54b5367f.png)

The same opened in CODE:

![image](https://user-images.githubusercontent.com/3321655/167612830-ad57d680-3677-493c-9229-9a8c07609b4c.png)

**Desktop (please complete the following information)**
 - OS: OS independent
 - Browser: Chrome, Safari, Edge, Firefox
 - Version: 22.11.4.2

**Smartphone (please complete the following information)**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**
The demo file I used here is attached below:

[Test.docx](https://github.com/CollaboraOnline/online/files/8660903/Test.docx)

**Comment by jacotec** [comment]
@thebearon Ugh, I really don't want to create a special account and deal with an ancient issue tracker. But thanks for pointing out!

Could you kindly open a reference in this core tracker thing to this issue here? ;-)

**Comment by thebearon** [comment]
Sure, I've opened the following bug report:
https://bugs.documentfoundation.org/show_bug.cgi?id=149370
