### ISSUE TITLE
convert-to not available

### ISSUE THREAD

**Issue by goncalo-synergy** [CollaboraOnline/online#4759]
Hi!

I have a question about the available features present in hosting/capabilities.

The convert-to functionality appears as not supported for my collabora-online, but what does that mean exactly and how can I make it available?

Can I change this (  "convert-to":{"available":false}  ) to true somewhere?

I'm using the latest docker version of CODE with kubernetes.

Thank you!

**Comment by thebearon** [comment]
Since this is a question and not a bug, let's close this in favor of the forum topic:
https://forum.collaboraonline.com/t/convert-to-not-available/1132
