### ISSUE TITLE
Collabora Office on Chromebooks is broken with Chrome OS upgrade to v101

### ISSUE THREAD

**Issue by flagellatedcucumber** [CollaboraOnline/online#4761]
**Describe the bug**
On a Chromebook, the user can install and launch Collabra Sheets, and create a document.  But when the sheet opens for editing, the sheet is not editable.  The row & column headings do not appear.  No gridlines appear.  A single selected cell in the middle of a blank screen appears; click elsewhere, it disappears.  The cell address (top-left corner) changes with the mouse clicking to select a new (invisible) cell, but the sizes of the (invisible) cells are far from regular.  From the user's perspective, the app is broken.

The user can also uninstall the app.  Tested after numerous installs, re-installed, ChromeOS updates... to no avail.

**To Reproduce**
As above.  Screenshots and a video at https://drive.google.com/drive/folders/1H_48E_ycItI0dw1nY05wM7ramAJTMI_J?usp=sharing .

**Expected behavior**
Sheets to work normally.  Like a spreadsheet program.

**Actual behavior**
As above.

**Screenshots**
As filed at https://drive.google.com/drive/folders/1H_48E_ycItI0dw1nY05wM7ramAJTMI_J?usp=sharing .

**Desktop (please complete the following information)**
Hardware
Acer Chromebook 315
CB315-2H series
Model: N17Q9

Software
Google Chrome: Version 101.0.4951.59 (Official Build)  (64-bit)
Platform: 14588.98.0 (Official Build) stable-channel grunt
Channel: stable-channel
Firmware Version: Google_Grunt.11031.174.0
ARC enabled: true
ARC: 8529499
Enterprise enrolled: false
Developer mode: false

Collabora Office COOLWSD 21.11.3.6, LOKit 21.06.25.1.

**Smartphone (please complete the following information)**
This bug is not replicated on an Android smartphone.  Only the Chromebook as identified above.

**Additional context**
Open to further queries and requests for data/tests.

**Comment by rpear** [comment]
I reckon a Chrome OS update is what is needed to fix it, and I don't know the ETA for that.  As I had similar experience a couple of weeks ago after the upgrade to v100, a Chrome OS update arrived a few days later that fixed it, perhaps that update was a regression.

And now .... I have just updated to Chrome OS v101 (same version as yours) which includes an upgrade to Android v11 I believe, supporting scaleable apps etc, seems to work OK so far on my device, HP X360.

**Comment by flagellatedcucumber** [comment]
Thanks.  Now reported to Google via the ChromeOS device affected, citing this github posting as the start point.  Let's see what happens...!

**Comment by rpear** [comment]
I have just updated an Acre R13 Chromebook to v101, Android v9 not v11, it is broken in the same way that yours.

**Comment by rpear** [comment]
> Thanks. Now reported to Google via the ChromeOS device affected, citing this github posting as the start point. Let's see what happens...!

Hi, could you rename the title of this issue to something like:
 "Collabora Office on Chromebooks is broken with Chrome OS upgrade to v101"

**Comment by flagellatedcucumber** [comment]
Done!

**Comment by flagellatedcucumber** [comment]
Good news!

A periodic re-test on the same Chromebook result returned a successful test result.

The Chromebook updated itself from 101.0.4951.59 to 102.0.5005.75.  Collabora updated itself from 21.06.25.1 to 21.11.3.6.

Test results of both initial bug and successful test (screenshots and videos) are at https://drive.google.com/drive/folders/1H_48E_ycItI0dw1nY05wM7ramAJTMI_J?usp=sharing for the next 30 days.

Closing ticket.

**Comment by rpear** [comment]
I think you'll find it works some days and not others.

**Comment by flagellatedcucumber** [comment]
Oh dear.  As (nearly) predicted, it broke again.  It worked on every use... until Chrome OS updated.

It has now borked again, with nearly the same results with the following:
Chrome 103.0.5060.132
and Collabora office 21.06.25.1.

New screenshots and access to the prior screenshots available from:
https://drive.google.com/drive/folders/1H_48E_ycItI0dw1nY05wM7ramAJTMI_J?usp=sharing

**Comment by rpear** [comment]
I confirm, it was working on mine on Chrome 103, confirmed this, upgraded to v104 and I now get same issue again, same as for you. I have experienced the same cycle of it not working then working since Chrome 100. Google must be making big tweaks :-(

**Comment by flagellatedcucumber** [comment]
Bug report filed with Google from the ChromeOS device.  Screenshots etc at https://drive.google.com/drive/folders/1H_48E_ycItI0dw1nY05wM7ramAJTMI_J?usp=sharing (in "Test #4761 20220821").

**Comment by flagellatedcucumber** [comment]
Re-tested on 06Sep2022.  Same outcome.
Screenshots & video at https://drive.google.com/drive/folders/1H_48E_ycItI0dw1nY05wM7ramAJTMI_J?usp=sharing .

**Comment by flagellatedcucumber** [comment]
Re-tested on 25Sep2022.  New outcome!  Collabora sheets appears to work normally!
Screenshots & video at https://drive.google.com/drive/folders/1H_48E_ycItI0dw1nY05wM7ramAJTMI_J?usp=sharing.

Let's keep this ticket open for a while longer; a future update on Chrome could still bork this.

**Comment by flagellatedcucumber** [comment]
Re-tested on 17Oct2022.  New outcome!  Collabora sheets is borked again.

On this occasion, normal use of Collabora was possible while the ChromeOS device was downloading and pre-installing updates.  Immediately after a re-boot to complete the update, Collabora reverted to its borked state, with the same symptoms.

What options are available to Collabora to bypass the disablement that Google seems keen to keep in its ChromeOS stack?

Updated screenshots & video at https://drive.google.com/drive/folders/1H_48E_ycItI0dw1nY05wM7ramAJTMI_J?usp=sharing.

Feedback to Google via [https://support.google.com/chromebook/answer/3142217](https://support.google.com/chromebook/answer/3142217).

**Comment by rpear** [comment]
I am not sure what can be done, I experience the same thing, after the ~monthly major ChromeOS update it stops working properly for a few days/weeks then it mysteriously gets better ...until the next ChromeOS update.  I wonder if ChromeOS detects it is failing and falls back to the previous way of implementing Android (not the VM) on a later reboot?

**Comment by philma9** [comment]
New Lenovo Chromebook Duet. I have this problem too. Just updated Chrome to V 105....92. Still borked. Uninstalled Collabora Office and re-installed (no version change). Still borked. FAF as it's my wife's and I recommended it...

**Comment by flagellatedcucumber** [comment]
Re-tested on 31Oct2022.  New outcome!  Collabora worked!
Videos and screenshots at https://drive.google.com/drive/folders/11YaoQ8xvjL2wqYwmIPPDBEIAGzDq9tvf?usp=share_link

Re-tested on 14Nov2022.  ChromeOS had an update to do, so test prior to the update and after the update.  Guess what?  Before update, Collabora worked.  After update, Collabora borked.  Same issues.  Seems like Google perceives Collabora as a existential threat to Google's own Google Docs.
Screenshots at https://drive.google.com/drive/folders/1H_48E_ycItI0dw1nY05wM7ramAJTMI_J?usp=share_link .

Whole history of test at
https://drive.google.com/drive/folders/1H_48E_ycItI0dw1nY05wM7ramAJTMI_J?usp=share_link

**Comment by flagellatedcucumber** [comment]
Stop me if you've heard this one before, but...

Re-tested on 29Nov2022.  On the previous test, Chrome OS was 106.0.5249.112.  On this test, Chrome OS had updated itself to 107.0.5304.110.  New outcome!  Collabora worke!

Screenshots for this test at https://drive.google.com/drive/folders/12XIg_lOzVjn9zv2muHWAHg7zEfCdDKBn?usp=sharing .

Whole history of test at
 https://drive.google.com/drive/folders/1H_48E_ycItI0dw1nY05wM7ramAJTMI_J?usp=share_link .

It's bonkers.

**Comment by flagellatedcucumber** [comment]
Re-tested on 21Dec2022.  On the previous test, Chrome was 107.0.5304.110 and Collabora worked.  On this test, Chrome OS had updated itself to 108.0.5359.111.  New outcome!  Collabora is borked (in the same way as previously).

Screenshots for this test at https://drive.google.com/drive/folders/12rx1yEke9IipKhEvf98oR1Zj78NDGKom .

Whole history of test at
https://drive.google.com/drive/folders/1H_48E_ycItI0dw1nY05wM7ramAJTMI_J?usp=share_link .

Issue ticket with Google raised from Chrome OS, being the third logged at https://docs.google.com/document/d/1Jw62T42XsWaWzpIUmWQ7gmO3VcR8g6GmbOZHoJLvO14 .  There have been more tickets raise, just not logged on this document.

**Comment by rpear** [comment]
For me the last few ChromeOS  ugrades breaks it, I then restart the
Chromebook and then it is OK.   As if Google are still trying something, it
senses the fail and after a restart it reverts to a previous known working
state.

**Comment by flagellatedcucumber** [comment]
Re-tested this morning from a cold start.  I replicated only the bork, not the self-repair.  (Hopes dashed....!)

**Comment by philma9** [comment]
Lenovo Chromebook Duet. Now at 107.0.0.0.0 after a 2 mth layoff. Collabora has never worked, same symptoms as others. Still waiting for the ##### thing to update to 108.3539 with little hope of success. On top of that the latest update has screwed the Bluetooth. After 35 yrs in IT I'm so disappointed. Do they do ANY regression testing at all?

**Comment by rpear** [comment]
Make sure you report the problem to Google, they are in the progress of
migrating Chromebooks to ArcVM  for Android apps, I think this is the cause
(I am just a user).  I find that mine works again a day or so after
ChromeOS upgrades every 4 weeks.

**Comment by flagellatedcucumber** [comment]
Two more re-tests since 22Dec2022, screenshots of which both filed at https://drive.google.com/drive/folders/1H_48E_ycItI0dw1nY05wM7ramAJTMI_J?usp=share_link .

In short, a test on 23Jan2023 found it failed.  And a test on 12Mar2023 found it worked again.

**Comment by flagellatedcucumber** [comment]
Two more tests since 13Mar2023, screenshots of which are both filed at https://drive.google.com/drive/folders/1H_48E_ycItI0dw1nY05wM7ramAJTMI_J?usp=share_link .

In short, a test on 26Mar2023 found it failed.  And a test on 07May2023 found it worked again.

**Comment by flagellatedcucumber** [comment]
This issue has now been superseded by an upgraded package.  Issue closed.
