### ISSUE TITLE
DOMException: Failed to execute 'send' on 'XMLHttpRequest' on Chrome only

### ISSUE THREAD

**Issue by ndr-88** [CollaboraOnline/online#4766]
Hello everyone,

Referred to this issue: #857 we have seen the same problem on Chrome:

```
bundle.js:1 Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://app.test.domain.it/browser/eb73aa3/l10n/uno-localizations.json'.
    at request_JSON (https://app.test.domain.it/browser/eb73aa3/bundle.js:1:766277)
    at String_ctr.<computed> (https://app.test.domain.it/browser/eb73aa3/bundle.js:1:766621)
    at https://app.test.domain.it/browser/eb73aa3/bundle.js:1:770033
    at https://app.test.domain.it/browser/eb73aa3/bundle.js:1:770592
```

the problem is solvable with the transformation of this [line](https://github.com/CollaboraOnline/online/blob/a8a0ce22c2dee5927f4a3d9c4625f68a884b6b69/browser/js/l10n.js#L61) to this:

```javascript
req.open("GET", uri, true);
```

This problem is only visible in Chrome browser, we have also a warning in Firefox, but app works fine. 

CollaboraOnline  version: `21.11.3-6`
Chrome version: `101`

Can it be fixed in this way? Could we open a pull request?

Thank you

**Comment by thebearon** [comment]
This is the same as #857, closing as duplicate.

Unfortunately the mentioned change isn't an actual fix, the execution just moves on, not waiting for the GET to finish.
