### ISSUE TITLE
Update English dictionary

### ISSUE THREAD

**Issue by MagsMagnoli** [CollaboraOnline/online#4768]
**Is your feature request related to a problem? Please describe.**
There are a number of common English words not recognized by the dictionary. Also acronyms are considered invalid but capitalizations should be ignored such as: SSN, SSL, PWA

**Describe the solution you'd like**
Update or change the provider used for the English dictionary

**Describe alternatives you've considered**
Allowing users to add custom words to the dictionary

**Additional context**
Here are some example words not recognized:
- [strategize](https://www.dictionary.com/browse/strategize)
- [redline](https://www.dictionary.com/browse/redline)
- [clickbait](https://www.dictionary.com/browse/clickbait)
- [e.g.](https://www.dictionary.com/browse/e-g)
- [accelerant](https://www.dictionary.com/browse/accelerant)

**Comment by thebearon** [comment]
The English dictionaries are the same used in LibreOffice, and are external to both that and Collabora Online. Please report your suggestions regarding US English dictionary here: https://github.com/en-wl/wordlist/issues
