### ISSUE TITLE
Speed Optimization: css files

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#4783]
If someone could give me some tools how to find out where our speed limitations will be located, let me know.

### CSS
There are a huge number of .css files which will be a good place to improve and optimize the page speed.

In general the css files will be "separated" between toolbar/sidebar/dialog, mobile/desktop, branding, ...

- [ ] What I didn't understood is the reason that the *mobile.css files will be loaded at the desktop. From my point of view it's not needed.

**Comment by Andreas-Kainz** [comment]
### branding Icons

- [ ] When use branding icons the icons from cool will be loaded and than the branding ones. So in general each icon (and that are a lot) will be loaded twice. #4736 should solve this issue cause than only the correct icon will be loaded.

**Comment by pedropintosilva** [comment]
Thanks for taking the time to test and ultimately hunt these things down :)

As I wrote in the IRC I think we are conflating two things here. We have many customers that have their own branding, the admin and at the end the user can always turn off integrator's theme or even not use branding at all.

I would focus primarily on testing what happens with a clean COOL build (make clean)

**Comment by pedropintosilva** [comment]
by looking at it myself (2 min) I'm already noticing odd behaviours:
- We now have an additional CSS file `color-palette-dark.css`, why we need it when using light mode?
  - To do: load it conditionally -> [see how](https://github.com/CollaboraOnline/online/pull/4750#issuecomment-1127515639)
- where is writer-mobile.css and why do we need it?
  - To do: remove it from the building process within the code
- Why `impress-mobile.css` is loaded on desktop, and do we needed it?
  - To do: add that file to the list of files to load conditionally 
- Why `toolbar-mobile.css`is loaded on desktop, and do we needed it?
  - To do: I think there was some bug that forces us to use it, but probably now we can load it conditionally 
- Why we load an extra file just for one rule? `leaflet-spinner.css`
  - To do: make it part of `leaflet.css`
- By far the biggest file seems to be `jquery-ui-lightness.css` and there are many classes there that we probably we don't make use of currently
  - To do: check if we can live without that file or if we can reduce those lines
