### ISSUE TITLE
Two svg (image) files are missing

### ISSUE THREAD

**Issue by gogle7** [CollaboraOnline/online#4795]
**Description**
Two svg files are missing
1. lc_insertcontentcontrol.svg
2. lc_insertcheckboxcontentcontrol.svg

**To Reproduce**
1. Load the docx file.
2. Go to Insert Tab
3. On the right part of the tool bar image is not loaded. 

**Actual behavior**
Image files are not loaded as they are missing
![image](https://user-images.githubusercontent.com/40571061/169445778-e89e11a8-6cd2-47f0-a4e0-2915d01e87bc.png)

**Expected behavior**
Some icons for that images

**Desktop**
 - OS: All
 - Browser: All
 - Version: Latest Master Branch

**Smartphone**
 - Device: All
 - OS: All
 - Browser:All
 - Version:Latest Master Branch

**Additional context**
Addition of those files `browser/images` folder

**Comment by vmiklos** [comment]
Yes, simply nobody added icons for these new commands yet. There will be a few more content control commands:

- insert dropdown content control (@Rash419 is working on this)
- insert picture content control
- insert date content control
- content control properties

@pedropintosilva what is the best way to handle this, do you prefer to wait till all of them are available and you add all these icons in one go or would you perhaps create such icons incrementally? Thanks.

**Comment by Andreas-Kainz** [comment]
best is to add Rizal or me to the PR so someone know that icons are needed (or you take the icons from core).

**Comment by Andreas-Kainz** [comment]
as this kind of stuff is (I think) form related, I would to suggest to have a separate Form menubar entry and a separate Form tab as we have in LibO. There would than be also enough space for all the future controls.

**Comment by pedropintosilva** [comment]
> Yes, simply nobody added icons for these new commands yet. There will be a few more content control commands:
> 
>     * insert dropdown content control (@Rash419 is working on this)
> 
>     * insert picture content control
> 
>     * insert date content control
> 
>     * content control properties
> 
> 
> @pedropintosilva what is the best way to handle this, do you prefer to wait till all of them are available and you add all these icons in one go or would you perhaps create such icons incrementally? Thanks.

Hi thanks for pinging me :) hm maybe it would be better to wait because we might end up, in some cases`*`, not needing all the icons but just a few.

`*` Example: in the classic view within menu entries; in the tabbed view if we end up using in one of the tabs a menubuttonControl instead of all actions in separated buttons

**Comment by pedropintosilva** [comment]
> as this kind of stuff is (I think) form related, I would to suggest to have a separate Form menubar entry and a separate Form tab as we have in LibO. There would than be also enough space for all the future controls.

yup we would use the menubuttonControl as I mentioned above (tyoe: menubutton)
