### ISSUE TITLE
Top bar menu collapses when resizing windows

### ISSUE THREAD

**Issue by goncalo-synergy** [CollaboraOnline/online#4810]
Hi!

When opening a document using collabora online, if we resize the window to a certain point, the topbar glitches, and the icons don't behave properly. They align vertically and some are not visible while others go down and cover the actual document.

The best solution for my case (just preview the document in read-only), would be to completely remove de top bar menu, maybe by changing something on the CheckFileInfo parameters. If that's not possible, is there any other way to overcome this situation?

Thank you!

![Capturar](https://user-images.githubusercontent.com/102959909/169984082-896d953e-df96-4abe-ba93-704f42e7bad4.JPG)
![Capturar](https://user-images.githubusercontent.com/102959909/169984233-d05fc956-4e9e-4ae0-9eeb-0160120c1c47.JPG)

**Comment by sebastiaanveld** [comment]
From Help> About... what is the version and build info you are testing?
What browser(s) and version on which platform?

**Comment by goncalo-synergy** [comment]
From Help > About:

Versão COOLWSD:
21.11.4.2 (git hash: 3eff190)

Versão LOKit:
built on a great technology base
Collabora Office 21.06.28.1 (git hash: f63c415)
Servido por: Ubuntu 18.04.6 LTS 3b07c86d

I'm using Chrome (version: 102.0.5005.63 64 bits) on Windows 10.

Also, I'm using the docker version of CODE.

**Comment by sebastiaanveld** [comment]
I cannot duplicate this using the same CODE version, also not with a newer build leveraging Nextcloud as a file store. What do you use to host your files in?

**Comment by goncalo-synergy** [comment]
The document is inside one iframe, that just opens the collabora link
