### ISSUE TITLE
Cannot execute Macros even if enabled

### ISSUE THREAD

**Issue by frdidonato** [CollaboraOnline/online#4819]
**Describe the bug**
I've downloaded the docker image of collabora development edition (latest) and modified coolwsd.xml to enable macros. I'm now able to launch macro dialog but I cannot view and select any Macros. What's going wrong ?
![Immagine](https://user-images.githubusercontent.com/81362592/170281948-7b0df105-1f0d-4928-ad7c-035e2faa4054.png)

**Comment by Ezinnem** [comment]
@frdidonato, Please can you test again using the latest docker image?

**Comment by Ezinnem** [comment]
I am closing this issue due to no feedback from the author.

However, the issue can be reopened if the issue still occurs in the recent docker image
