### ISSUE TITLE
Speed-up callbacks ....

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#4837]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @Ashod 

### Detailed description and rationale
When we send messages across threads (one thread per SocketPoll) we have to use 'addCallback' or 'insertSocket' these queue up the work to be done in the main thread and they also send a 'wakeup'.

Since we take a lock anyway here, we should check whether we actually need to send a wakeup and if so, not send another one - otherwise we just fill up the internal wakeup socket with data for no good reason, spin the main-loop pointlessly and waste CPU, scheduler cycles and goodwill from developers tracing the code =)

We should not add locking to wakeup() itself. Quite probably though we should do a larger read from the wakeup pipe to empty it inside our ::poll function though - since there is no benefit in spinning and waking up again if there have been multiple wakeups.

### Code pointers

```
net/Socket.hpp see:
    /// Protects _newSockets and _newCallbacks
    std::mutex _mutex;
    std::vector<std::shared_ptr<Socket>> _newSockets;
    std::vector<CallbackFn> _newCallbacks;

```
And uses of _newSockets and _newCallbacks. We should have a function that checks if _newSockets and _newCallbacks is empty before doing a 'wakeup()'.

Thanks ! =)

**Comment by callmetushar123** [comment]
Hello. Can you point out where this part of the code is present in the file?

**Comment by thebearon** [comment]
For the record, #6467 causes a slight regression in coolwsd shutdown times (5-10 s in a debug build).

While that won't affect users, it could be frustrating for devs, who start up and shut down builds often.
