### ISSUE TITLE
Cannot type in formula bar (excel)

### ISSUE THREAD

**Issue by gogle7** [CollaboraOnline/online#4855]
**Describe the bug**
Cannot type on the formula bar on the latest master branch.

**To Reproduce**
1. Open xlsx document
2. Select cell and type something
3. It doesn't synchronize with formula bar
4. Also cannot type on formula bar.

**Actual behavior**
Cannot type anything on formula bar.
![image](https://user-images.githubusercontent.com/40571061/171837082-4cdf1635-304d-4357-8eb6-c509b3b3fd03.png)

**Expected behavior**
Whenever we type something on cell, it is expected to be on formula bar as well.

**Desktop (please complete the following information)**
 - OS: Any
 - Browser: Probably all (Test performed on Firefox)
 - Version: Latest master branch 0b73614cfbf33790464186aa73e95a04bb5c1801

**Additional context**
This issue is not present on the docker image. It happens on latest master branch. 
It used to work (not sure about particular commit) when there was no dropdown option for formula bar.

**Comment by gogle7** [comment]
Used the latest core 
`wget https://github.com/CollaboraOnline/online/releases/download/for-code-assets/core-co-22.05-assets.tar.gz`
as mentioned in https://collaboraonline.github.io/post/build-code/#build-code-on-ubuntu

**Comment by Go-rom** [comment]
Hi @gogle7 

could you please confirm that this bug is fixed ?

I've got the same issue with CODE 22.05.8.2
