### ISSUE TITLE
Convert specific pages

### ISSUE THREAD

**Issue by goncalo-synergy** [CollaboraOnline/online#4863]
Hi!

Using the convert-to feature (word to pdf for example) it would be nice to select only a certain number of pages to be converted. As present in your documentation, you use JODConverter, which has the PageSelectorFilter option available.

In my case, I would be converting only the first page of office documents to pdf, so I wouldn't want to have to convert the whole document every time.

**Comment by vmiklos** [comment]
See https://vmiklos.hu/blog/pdf-convert-to.html, does that PageRange trick work for you?

**Comment by Ezinnem** [comment]
Closing this issue due to no response from the author.
