### ISSUE TITLE
Dropdown with conditional formatting freezes CODE in Nextcloud

### ISSUE THREAD

**Issue by tosigus** [CollaboraOnline/online#4870]
**Describe the bug**
Applying conditional formatting, color, with dropdown text options halts CODE. Only reload of the page helps.

**To Reproduce**
1. Create dropdown with text options
2. Create conditional with colors for text options ("Homeoffice" = yellow, "Office" = green)
3. Select text option from dropdown
4. Selection is displayed, but the dropdown menu isn't closed

**Expected behavior**
Closed dropdown menu. Desktop works, CODE in Browser doesn't work.

**Actual behavior**
Dropdown menu is shown after selection. No input is possible.

**Screenshots**
![Screenshot 2022-06-07 145231](https://user-images.githubusercontent.com/1965213/172602010-0cc6cb50-78f9-4e61-bcb2-8fa34c6ec9a0.png)

**Desktop (please complete the following information)**
 - OS: Windows 10 Enterprise
 - Browser: Microsoft Edge / Firefox / Brave
 - Version: 102.0.1245.33 / 101.0 / V1.39.111
 - COOLWSD: 21.11.4.2 (git hash: 3ef190)
 - LOKIT Version: Collabora 21.06.28.1 (git hash: f63c415), Ubuntu 18.04.6

**Additional context**
[Test_Kalender.ods](https://github.com/CollaboraOnline/online/files/8860979/Test_Kalender.ods)

**Comment by danir-de** [comment]
Have you tried updating? Seems to be similar to #4757.

**Comment by thebearon** [comment]
Yes, good point, this is #4757.
