### ISSUE TITLE
i can not view docx extension files  full page size on 6.4 version

### ISSUE THREAD

**Issue by hmdgms** [CollaboraOnline/online#489]
**can not view docx extension files  full page size**

I installed the verison 6.4 from https://collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/ 
I can not view correctly the files having extension of docx.  All the pages are small  stuck center in a single page and i can not enlarge the page.

I installed every new release, and the problem also continued. After all i installed version 4.2 from the same link. And everything is fine, at the end i can view full page.
**Test OS:** LineageOS (Android 10)
![Screenshot_20201101-152612_Collabora_Office](https://user-images.githubusercontent.com/2501849/97815729-4651a400-1ca1-11eb-9c84-4f83c8c85719.png)
![Screenshot_20201101-004458_Collabora_Office](https://user-images.githubusercontent.com/2501849/97815731-4a7dc180-1ca1-11eb-86ab-89f38621a92b.png)

**Comment by hmdgms** [comment]
The files i tried to view


[files.tar.gz](https://github.com/CollaboraOnline/online/files/5471815/files.tar.gz)

**Comment by hmdgms** [comment]
The files i try to view
[files.tar.gz](https://github.com/CollaboraOnline/online/files/5471822/files.tar.gz)

**Comment by thebearon** [comment]
Right, there's a bug in `master` branch that affects zoomed and mobile views (and any view where the device pixel ratio isn't 1). Version 6.4 (branch `distro/collabora/co-6-4`) is actually free from that, but the 6.4 mobile snapshot currently uses the `master` branch.

The naming of the mobile snapshots will be corrected, and there will be a true 6.4 snapshot. And separately this bug will be fixed, too.

**Comment by thebearon** [comment]
This was fixed a long time ago, let's close.
