### ISSUE TITLE
F-droid repo

### ISSUE THREAD

**Issue by hmdgms** [CollaboraOnline/online#490]
Does The Community have future plan about loading apk to F-droid repos?

**Comment by cornouws** [comment]
Hi hmdgms,
This blog shows the situation around F-Droid
 https://www.collaboraoffice.com/releases-en/collabora-office-on-mobiles-supporting-password-protected-documents-and-available-on-f-droid/

**Comment by hmdgms** [comment]
Thanks, it worked

**Comment by tml1024** [comment]
Any reason to keep this open as an issue?

**Comment by cornouws** [comment]
> Any reason to keep this open as an issue?

nope. Sorry.

**Comment by marek22k** [comment]
Why is Collabora not included in the official F-Droid Repo?
