### ISSUE TITLE
Improvements for following another person's cursor.

### ISSUE THREAD

**Issue by gokaysatir** [CollaboraOnline/online#4920]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @pedropintosilva @eszkadev 

### Detailed description and rationale
- [ ] The "follow cursor" feature should stop following other user's cursor when the current user types something.
- [x] There should be an indicator to show which user's cursor is being followed. 

### Code pointers
Here is the function which setups the "following" of a user:
https://github.com/CollaboraOnline/online/blob/master/browser/src/map/Map.js#L1803

### Links to related documentation
...

### Additional notes, tips & tricks
...

**Comment by Rimuruweeb** [comment]
sir, can please provide code pointers ? and can you guide me ?.

**Comment by eszkadev** [comment]
@Rimuruweeb hi, here is function which setups the "following" of a user:
https://github.com/CollaboraOnline/online/blob/master/browser/src/map/Map.js#L1803

**Comment by pedropintosilva** [comment]
> There should be an indicator to show which user's cursor is being followed. 
this was done by me and already pushed

**Comment by pedropintosilva** [comment]
I think @Rimuruweeb is not work on this so, I'm assigning this to you @Minion3665 if that's ok :)

**Comment by pedropintosilva** [comment]
@GulsahKose is on this now, thanks !
