### ISSUE TITLE
Calc shows wrong zoom factor after editing with CO 

### ISSUE THREAD

**Issue by monochromec** [CollaboraOnline/online#4921]
**Describe the bug**
After editing an ODS with CO, the zoom factor is at 180% when opening the offline copy on the local NC mirror with LO (where it was 100% prior).

**To Reproduce**
1. Open an ODS with CO
2. Change something and save the modified version
3. Open the local copy with LO after NextCloud synchronisation with online copy
4. Observe 180% zoom factor

**Expected behavior**
Zoom factor should stay at 100%

**Actual behavior**
Zoom factor is at 180%

**Desktop (please complete the following information)**
 - OS: Debian Bullseye
 - Browser: Error can reproduced with FF 101.01, Opera 88.04412 and Chromium 102.0.5005.115
 - Versions: CODE 21.11.402, LO 7.3.3.2

**Additional context**
More than happy to provide additional info.

**Comment by Ezinnem** [comment]
This issue does not seem to occur on my end.

@monochromec, Please can you share a screen recording showing the issue?

**Comment by monochromec** [comment]
Here you go. This time it's even 200%.
![Screenshot 2022-06-25 at 09 27 42](https://user-images.githubusercontent.com/606567/175763578-bf28e2d8-e97b-4998-95a9-f51c1382ab30.png)

**Comment by thebearon** [comment]
Actually, this is pretty much the same as #4250, let's close as duplicate.
