### ISSUE TITLE
Replace magic numbers with keycode constants

### ISSUE THREAD

**Issue by eszkadev** [CollaboraOnline/online#4929]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @eszkadev 

### Detailed description and rationale
There are directly provided numbers for key codes in some places. We can use already defined constant variables. This makes code more readable and obvious. We don't have to comment every place with human readable label.

### Code pointers
Example: instead of 112 -> KeyCode.F1
in https://github.com/CollaboraOnline/online/blob/master/browser/src/map/handler/Map.Keyboard.js#L331

### Links to related documentation
Here is example map with number (KeyCode) -> UNOCode binding: https://github.com/CollaboraOnline/online/blob/master/browser/src/map/handler/Map.Keyboard.js#L20
we want something similar but rather:
`Name -> KeyCode number` like: `F1: 112` so later we can use `KeyCode.F1` instead of 112

**Comment by kakkarot0** [comment]
hey can i work on this issue??
we only need to change it to KeyCode.F1??

**Comment by callmetushar123** [comment]
@eszkadev Please assign it to me. I think this would be doable as I am a complete newbie

**Comment by eszkadev** [comment]
done with: https://github.com/CollaboraOnline/online/pull/5319

Thanks @callmetushar123
