### ISSUE TITLE
cannot retrieve spreadsheet. no gridlines. single cell contents displayed in formula field

### ISSUE THREAD

**Issue by claytonclent** [CollaboraOnline/online#4941]
**Describe the bug**

**To Reproduce**
1. Open Spreadsheet document in ChromeBook
2. no gridlines. single cell contents displayed in formula field

**Expected behavior**
spreadsheet opens

**Actual behavior**
blank page with no gridlines opens with the contents of a single cell displayed in the formula field

**Screenshots**
![image](https://user-images.githubusercontent.com/65948705/175888434-17c229b0-9bfa-4414-86b9-d521ab43bcd2.png)

**Desktop (please complete the following information)**
device:chromebook
- OS: android
- Browser: chrome
- Collabora 21.11.3.6

**Additional context**
See @rpear 's comment

**Comment by claytonclent** [comment]
expected behaviour: spreadsheet opens
actual behaviour: blank page with no gridlines opens with the contents of a single cell displayed in the formula field
![Screenshot 2022-06-23 08 29 40](https://user-images.githubusercontent.com/108033871/175167349-13785df5-2c64-4828-86ce-3179ffd057dc.png)
device:chromebook
OS: android
Browser: chrome 
Collabora 21.11.3.6

**Comment by rpear** [comment]
Hi, this broke for me with Chrome OS update 100 (then got better), then 101 (then got better), now 102. I believe this broke when Google intruduced the new [ArcVM](https://chromeos.dev/en/posts/making-android-more-secure-with-arcvm) way of hosting Android on Chromebooks. I think it would be a good idea to report this as an issue to Google as well. via Chrome > Help

**Comment by claytonclent** [comment]
Thanks. Will do.

**Comment by claytonclent** [comment]
Issue now resolved. Many thanks.

**Comment by pedropintosilva** [comment]
Thanks for reporting this @claytonclent, and as always thanks @rpear  for your valuable hep :)

Let me edit the issue description to include the missing bits and then close this.
