### ISSUE TITLE
Can’t change table border in tablet fullscreen layout from sidebar

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#4942]
**Describe the bug**
Initially reported https://forum.collaboraonline.com/t/cant-change-table-border-in-tablet-fullscreen-layout/1174/3 by `guylife`

**To Reproduce**
1. Open any spreadsheet file
2. Search for `Miscellaneous` group in the sidebar where you would expect to see the options to switch border color etc via sidebar
3. `Miscellaneous` group does not exist anymor

**Screenshots**
In the past, when the sidebar was tunnelled we used to have that group of actions:
![image](https://user-images.githubusercontent.com/65948705/175264702-046e814b-3601-457e-b946-4de038b9f509.png)
Now we don't
![image](https://user-images.githubusercontent.com/65948705/175264770-4168c505-f524-4da6-b7a3-6c670eaf14a6.png)

**Desktop (please complete the following information)**
 - Browser: any browser and mobile app
 - Version: Master but also latest stable

**Comment by eszkadev** [comment]
it was intentional: https://github.com/CollaboraOnline/online/commit/1aed5dd
commit said it was not supported/not working

**Comment by thebearon** [comment]
I assume this can be closed, thanks for fixing, @eszkadev!
