### ISSUE TITLE
"Document loading failed" - NGINX, no Docker

### ISSUE THREAD

**Issue by natrius** [CollaboraOnline/online#4966]
**Describe the bug**
Updated from Ubuntu 18.04 to 20.04 and now run into quite some problems with collabora.

**Details:**
Ubuntu 20.04 LTS
NGINX 1.18
PHP 8.1.7
Nextcloud 24.0.2
Richdocuments 6.1.0

Nextcloud shows me in the "Office" Tab that it is connected to the Collabora server. 
![grafik](https://user-images.githubusercontent.com/7243447/175827117-926ad4ed-4e9f-4426-b93d-c51ca63fa90e.png)

Its just, when i try to open a file it waits for some time and ends in "Document loading failed". Log in Nextcloud itself does not show anything for the time when trying to open a file. 

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
sudo tail data/nextcloud.log did not show anything in the timeframe i tried to access the file.
```

Here is the nginx. I had to switch https to http so it works or the coolwsb service would even start at all.
```
server {
    listen       443 ssl;
    server_name  office.example.home;
    ssl_certificate /etc/letsencrypt/live/office.example.home/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/office.example.home/privkey.pem; # managed by Certbot

   # static files
   location ^~ /browser {
       proxy_pass http://127.0.0.1:9980;
       proxy_set_header Host $http_host;
   }

   # WOPI discovery URL
   location ^~ /hosting/discovery {
       proxy_pass http://127.0.0.1:9980;
       proxy_set_header Host $http_host;
   }

   # Capabilities
   location ^~ /hosting/capabilities {
       proxy_pass http://127.0.0.1:9980;
       proxy_set_header Host $http_host;
   }

   # main websocket
   location ~ ^/cool/(.*)/ws$ {
       proxy_pass http://127.0.0.1:9980;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "Upgrade";
       proxy_set_header Host $http_host;
       proxy_read_timeout 36000s;
   }

   # download, presentation and image upload
   location ~ ^/(c|l)ool {
       proxy_pass http://127.0.0.1:9980;
       proxy_set_header Host $http_host;
   }
   # Admin Console websocket
   location ^~ /cool/adminws {
       proxy_pass http://localhost:9980;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "Upgrade";
       proxy_set_header Host $http_host;
       proxy_read_timeout 36000s;
   }

    add_header Strict-Transport-Security "max-age=31536000" always; # managed by Certbot

    ssl_trusted_certificate /etc/letsencrypt/live/office.example.home/chain.pem; # managed by Certbot
    ssl_stapling on; # managed by Certbot
    ssl_stapling_verify on; # managed by Certbot
}

```

</details>

When using the nginx from here https://sdk.collaboraonline.com/docs/installation/Proxy_settings.html with the `https` instead of the `http` i'm using i will get the following error with `sudo journalctl -eu coolwsd`:
`ERR  Looks like SSL/TLS traffic on plain http port| wsd/COOLWSD.cpp:3373`

So currently i use it with `http` instead of `https` and its OK in the Nextcloud Office Check, but the documents do not open. In this issue tracker i found https://github.com/CollaboraOnline/online/issues/4828 but i obviously don't have a 

```
 location ^~ / {
     proxy_pass http://192.162.172.100:9980;
     proxy_set_header Host $http_host;
   }
```

in my config. 

- https://office.example.server/hosting/discovery  
- https://office.example.server/browser/dist/admin/admin.html  

Both are working, but the admin-UI does not show anything when i'm trying to connect or open a file, even when setting the log-settings to "debug". 

It seems this exact issue is splattered all over the internet, Nextcloud Forum, Reddit selfhosted, nextcloud/richdocuments Github-Issues, this Issue tracker. It may be worth collection various stuff to check for this and collect it together in the documentation? 
I used an old installation and updated finally, it was nowhere mentioned everything changed from lool to cool - a member of the nextcloud-chat i'm in mentioned this.

EDIT: Just to be sure - i posted already https://github.com/nextcloud/richdocuments/issues/2287 because i didn't get that this is an separate tracker. This one might be better suited? (The CollaboraOnline/online one)

**Comment by Rash419** [comment]
@natrius thanks for the report. Can you give us coolwsd logs ? Can you share command with which you start the CODE ?

**Comment by s1m-e0n** [comment]
I am also experiencing this, same setup as natrius, though I have had this problem for a while now also with older Nextcloud and Richdocuments versions. I could get document loading to work though when setting "Enable HTTPS-Only Mode in all windows" in Firefox. I am also getting the error in the Nextcloud mobile apps.

**Comment by natrius** [comment]
Right now i found `/etc/cron.weekly/collabora_certs` to still look like its old with `lool` instead of `cool`

```
#!/bin/bash
cp /etc/letsencrypt/live/kraw.eu/cert.pem /etc/loolwsd/cert.pem
cp /etc/letsencrypt/live/kraw.eu/privkey.pem  /etc/loolwsd/key.pem
cp /etc/letsencrypt/live/kraw.eu/chain.pem /etc/loolwsd/ca-chain.cert.pem
chown lool /etc/loolwsd/cert.pem
chown lool /etc/loolwsd/key.pem
chown lool /etc/loolwsd/ca-chain.cert.pem
systemctl restart loolwsd.service
exit 0
```

I changed it to `cool` and restarted the server, as expected no change - unfortunately. Still "Document failed to load".

**Comment by Rash419** [comment]
@natrius 
Can you share <wopi>...</wopi>config part from coolwsd.xml ?

**Comment by s1m-e0n** [comment]
@Rash419 CODE version is 22.05.3.1 but also had the problem on earlier versions. 
I'm using the official docker image from https://hub.docker.com/r/collabora/code/, which uses https://github.com/CollaboraOnline/online/blob/master/docker/from-packages/scripts/start-collabora-online.sh in CMD

Here's my docker-compose.yml, if that's any help
``` yml
version: "3.7"

networks:
  internal:
    driver: bridge

services:
  collabora:
    image: collabora/code
    restart: unless-stopped
    networks:
      - internal
    environment:
      - "extra_params=--o:ssl.enable=false"
    cap_add:
      - MKNOD
    logging:
      driver: journald
      options:
        tag: docker-nextcloud-collabora
```

**Comment by Rash419** [comment]
@natrius 
`ERR Looks like SSL/TLS traffic on plain http port| wsd/COOLWSD.cpp:3373`
can you share config.php  ?

**Comment by natrius** [comment]
So, the `/etc/coolwsd/coolwsd.xml` as followed

```
<wopi allow="true" desc="Allow/deny wopi storage.">
                        <max_file_size desc="Maximum document size in bytes to load. 0 for unlimited." type="uint">0</max_file_size>
                        <locking desc="Locking settings">
                                <refresh default="900" desc="How frequently we should re-acquire a lock with the storage server, in seconds (default 15 mins) or 0 for no refresh" type="int">900</refresh>
                        </locking>
                        <alias_groups desc="default mode is 'first' it allows only the first host when groups are not defined. set mode to 'groups' and define group to allow multiple host and its aliases" mode="groups">
                                <group>
                                        <host allow="true">https://nextcloud.example.home</host>
                                </group>
                                <!-- If you need to use multiple wopi hosts, please change the mode to "groups" and
                    add the hosts below.  If one host is accessible under multiple ip addresses
                    or names, add them as aliases. -->
                                <!--<group>
                    <host desc="hostname to allow or deny." allow="true">scheme://hostname:port</host>
                    <alias desc="regex pattern of aliasname">scheme://aliasname1:port</alias>
                    <alias desc="regex pattern of aliasname">scheme://aliasname2:port</alias>
            </group>-->
                                <!-- More "group"s possible here -->
                        </alias_groups>
                        <host>nextcloud.example.home</host>
                </wopi>

```

and the `/var/www/nextcloud/config/config.php`

```
<?php
$CONFIG = array (
  'instanceid' => 'anId',
  'passwordsalt' => 'AnPasswordalt',
  'secret' => 'ANiceSecret',
  'trusted_domains' =>
  array (
    0 => 'nextcloud.example.home',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '24.0.3.2',
  'overwrite.cli.url' => 'https://nextcloud.example.home',
  'dbname' => 'nextcloud_db',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud_db_user',
  'dbpassword' => 'DBPASSWORD',
  'installed' => true,
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'overwriteprotocol' => 'https',
  'logtimezone' => 'Europe/Berlin',
  'theme' => '',
  'loglevel' => 1,
  'app_install_overwrite' =>
  array (
    0 => 'calendar',
    1 => 'forms',
    2 => 'souvenirs',
    3 => 'flowupload',
  ),
  'mail_from_address' => 'kraw',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'email.eu',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'user@email.eu',
  'mail_smtppassword' => 'wassswoooorrrd',
  'mail_smtphost' => 'email.eu',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpport' => '465',
  'default_phone_region' => 'AT',
  'updater.secret' => 'UpdaterSecret',
);
```

If thats what you mean @Rash419 (i hope i left no password...)

**Comment by Rash419** [comment]
@natrius
I think its ssl thing only can you try using having nextcloud and code without ssl 
make sure you configure overwrite parameters correctly
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html#overwrite-parameters

**Comment by natrius** [comment]
It seems i have solved it. I got in there with a fresh mind and tried to check it step by step: https://www.collaboraoffice.com/code-4/linux-packages/ 

and i think due to the distribution update from 20.04 to 22.04 the `/etc/apt/sources.list.d/collaboraonline.sources` was still wrong and due to that nothing worked. Suddenly i was now also able to use the nginx config i used in my first post (https://github.com/CollaboraOnline/online/issues/4966#issue-1289753523) - with the correct https (like in the documentation) instead of the (wrong) http - reminder, the result was nextcloud stating collabora was connected but the document still not loading. 

I hope you can refer to others to this issue. 

- Check if `sudo apt install fuse && sudo apt install fontconfig && sudo apt install libfuse2` is installed
- Doublecheck with https://www.collaboraoffice.com/code-4/linux-packages/ if the `/etc/apt/sources.list.d/collaboraonline.sources` is correct
- Check in your nginx config https://sdk.collaboraonline.com/docs/installation/Proxy_settings.html#reverse-proxy-with-nginx-webserver that you are using the correct URL **WITH** https and not http

Thats all i have written down for now. If there are questions, feel free to ask.
