### ISSUE TITLE
Back button warning before closing the mobile app (Android)

### ISSUE THREAD

**Issue by SustReal** [CollaboraOnline/online#4989]
## Bug report
**Is your feature request related to a problem? Please describe.**
Typically, by using the back button on Android, I accidentally close the app. This is not ideal.

**Describe the solution you'd like**
Other apps, for instance the [Mattermost app for Android](https://play.google.com/store/apps/details?id=com.mattermost.rn&gl=US) trigger a warning before allowing to close the app with a second touch of the back button. This feels like a better user experience to me.

**Additional context**
Here is a screenshot of the way this is implemented in the [Mattermost app](https://user-images.githubusercontent.com/51329893/177613695-d792b84c-373e-4648-92dc-bd98fea76c26.png)

### Possible mentors
@merttumer 

### Code pointers
https://github.com/CollaboraOnline/online/blob/master/android/app/src/main/java/org/libreoffice/androidapp/ui/LibreOfficeUIActivity.java#L505

### Links to related documentation
https://collaboraonline.github.io/post/build-code-android/

**Comment by pedropintosilva** [comment]
Thanks @SustReal I think this would be fairly simply to do to anyone with a bit of experience with Android development maybe we can turn this into a easy hack

**Comment by pedropintosilva** [comment]
What do you think @merttumer ? Is it easy enough to be classified as easy hack?

**Comment by pedropintosilva** [comment]
@mert confirmed: it's an excellent candidate for an easy hack, thanks!

**Comment by pedropintosilva** [comment]
Maybe let's rethink this. Maybe this is not so useful when it's impossible to accidentally close the app when editing it (the user needs to tap first the checkmark  and just then he/she can tap the back button)

**Comment by SamarthAsthan** [comment]
it is still available ? can I work on it?

**Comment by pedropintosilva** [comment]
Let's close this as per my comment above the user during edit mode needs actually to tap the checkmark first -> the document will not be close it will just save and change to read only mode and then the user can tab once again the same area (this time on the chevron) to exit
