### ISSUE TITLE
Docker image is missing branding

### ISSUE THREAD

**Issue by juliushaertl** [CollaboraOnline/online#4993]
The latest docker images seem to be missing the branding assets. [22.05.3.1.1](https://hub.docker.com/layers/code/collabora/code/22.05.3.1.1/images/sha256-cb1e8855ced342033956552fb9d5034533ee1526918dde84022b9f3a3f9c5146?context=explore)

COOLWSD version:
22.05.3.1 git hash: https://github.com/CollaboraOnline/online/commit/dcae5fa613077201283335df2731addaf0e3b252
LOKit version:
Collabora Office 22.05.3.1 git hash: 10ffe3b
Served by: Ubuntu 18.04.6 LTS 489a55a2

$ docker pull collabora/code
Using default tag: latest
latest: Pulling from collabora/code
Digest: sha256:bb607fe16199bbb1fb704b2e4f47af41f0130bca7b1342324dfb28b53e956277
Status: Image is up to date for collabora/code:latest
docker.io/collabora/code:latest

Working collabora/code:21.11.3.4.1:
```
cool@56b6a6a2ed9f:/$ find /usr/share/coolwsd/browser -iname 'branding*'
/usr/share/coolwsd/browser/dist/branding.css
/usr/share/coolwsd/browser/dist/nextcloud/branding.css
/usr/share/coolwsd/browser/dist/nextcloud/branding-desktop.css
/usr/share/coolwsd/browser/dist/nextcloud/images/branding_watermark_black_24dp.svg
/usr/share/coolwsd/browser/dist/nextcloud/branding-mobile.css
/usr/share/coolwsd/browser/dist/nextcloud/branding.js
/usr/share/coolwsd/browser/dist/nextcloud/branding-tablet.css
/usr/share/coolwsd/browser/dist/branding-desktop.css
/usr/share/coolwsd/browser/dist/branding-mobile.css
/usr/share/coolwsd/browser/dist/branding.js
/usr/share/coolwsd/browser/dist/branding-tablet.css
cool@56b6a6a2ed9f:/$
```

Missing collabora/code:22.05.3.1.1:
```
cool@7aa725c00a5a:/$ find /usr/share/coolwsd/browser -iname 'branding*'
cool@7aa725c00a5a:/$
```

CC @timar

**Comment by timar** [comment]
I don't know. I have the image from the same hash, and...
```
cool@87f6fa163d9b:/$ find /usr/share/coolwsd/browser -iname 'branding*'
/usr/share/coolwsd/browser/dist/branding-desktop.css
/usr/share/coolwsd/browser/dist/branding-mobile.css
/usr/share/coolwsd/browser/dist/branding-tablet.css
/usr/share/coolwsd/browser/dist/branding.css
/usr/share/coolwsd/browser/dist/branding.js
/usr/share/coolwsd/browser/dist/nextcloud/branding-desktop.css
/usr/share/coolwsd/browser/dist/nextcloud/branding-mobile.css
/usr/share/coolwsd/browser/dist/nextcloud/branding-tablet.css
/usr/share/coolwsd/browser/dist/nextcloud/branding.css
/usr/share/coolwsd/browser/dist/nextcloud/branding.js
/usr/share/coolwsd/browser/dist/nextcloud/images/branding_watermark_black_24dp.svg
```

**Comment by juliushaertl** [comment]
I'm using the ARM docker image, sorry forgot to mention, will check on the x86_64 later.

**Comment by juliushaertl** [comment]
Confirmed that it is only happening on the arm container:

collabora/code                                     latest                                          d24080f0d03b   12 days ago     1.35GB

**Comment by juliushaertl** [comment]
Closing as fixed with the latest published image
