### ISSUE TITLE
Turn off automatic write check permanently

### ISSUE THREAD

**Issue by Elvis2000NC** [CollaboraOnline/online#5005]
Is it possible to turn off the automatic write check permanently? I disable it at every startup. When I restart collbora, it is already active again.

**Comment by gokaysatir** [comment]
I checked it and "automatic spell checking" is not active event after restarting CODE server. You mean below feature right?

![spell-checking](https://user-images.githubusercontent.com/28108660/178995934-5372097a-232a-4a9d-9fe8-7ed61503fe86.png)

**Comment by pedropintosilva** [comment]
@Elvis2000NC  which version do you use and how is it setup? (docker, native packages ?)

**Comment by timur-g** [comment]
Nor reproduced and no response, I close.
