### ISSUE TITLE
Using scroll bars in edit field make fields disapear

### ISSUE THREAD

**Issue by zhivko** [CollaboraOnline/online#5017]
**Describe the bug**

When using scrollbars to move listbox of edit field dialog, collabora hides part of listbox

**To Reproduce**

1. Open Edit fields dialog
2. Use horizontal scrollbars to scroll listbox content where fields are shown (leftmost listbox)
4. See how scroller hides part of listbox

**Expected behavior**
Using scrollbox should not hide contents of listbox

**Actual behavior**
Using scrollbox hides contents of listbox

**Screenshots**
![image](https://user-images.githubusercontent.com/3688966/178970837-8ea49f49-c25e-4908-b764-91b4cd660004.png)

**Desktop (please complete the following information)**
 - OS: using image: collabora/code:6.4.14.3 as docker container
 - Browser: Firefox for Ubuntu Canonical
 - Version: 102.0 (64-bit)

**Smartphone (please complete the following information)**

**Additional context**

**Comment by pedropintosilva** [comment]
https://forum.collaboraonline.com/t/scrollbar-in-editfields-hides-fields-list/1231/3

> [szyklos](https://forum.collaboraonline.com/u/szyklos)
> 
> hi [@zhivko](https://forum.collaboraonline.com/u/zhivko) , it looks like a problem we already fixed in newer versions:
https://cgit.freedesktop.org/libreoffice/core/commit/?h=distro/collabora/co-22.05&id=77f4389f38feea54e6c777e86f7ee4a79331eb75
> 
> 6.4 is quite old I recommend to use newer version.

**Comment by pedropintosilva** [comment]
This has been fixed
