### ISSUE TITLE
Unexpected behaviour when deleting tables in Writer 

### ISSUE THREAD

**Issue by SustReal** [CollaboraOnline/online#5018]
**Describe the bug**
When I right-click on "Delete > Table" it does not delete right away some times. When it does, it jumps to the beginning of the document.

**To Reproduce**
1. Create document with several pages and a table somewhere in the middle
2. Right-click on 'Delete -> Table'
3. See unexpected behaviour

**Expected behavior**
The cursor should stay in the position the deleted document once was. 

**Actual behavior**
see description

**Screenshots**
-

**Desktop (please complete the following information)**
 - OS: Windows 11
 - Browser: Firefox 102.0.1
 - Version: CODE 22.05.4.1

**Smartphone (please complete the following information)**
 - 

**Additional context**
- Deleting single rows of tables does also not seem to work properly...

**Comment by Ezinnem** [comment]
@SustReal, Please can you share a screen recording showing the issue?

**Comment by SustReal** [comment]
@Ezinnem I'm afraid I'm currently not able to replicate the error any longer. If this shows again, I'll be adding a file and/or recording.

**Comment by Ezinnem** [comment]
Thank you.

I will be closing this issue for now. It can be reopened later if the issue reoccurs.
Please feel free to send the recording if it occurs again.
