### ISSUE TITLE
Autofilter on bg, fg color impossible to activate

### ISSUE THREAD

**Issue by yurkobb** [CollaboraOnline/online#5020]
**Describe the bug**

The UI for autofilter based on color doesn't seem to be functional.

**To Reproduce**
1. Open a file containing rows with varying background and/or foreground colors
2. Activate Autofilter
3. Click on the autofilter arrow on the first column
4. (Tested with and without this step - uncheck All)
5. Click on "Background Color";
6. In the popup listing the colors (in hex, but that is another UX issue), enable a checkbox on one of the colors;
7. Click "OK" on the Autofilter popup

**Expected behavior**
Only the rows marked with the specific background color are visible after applying autofilter.

**Actual behavior**
With "All" checked - all rows still visible.

With "All" unchecked - none rows visible (the first row with the autofilter arrows disappears too).

**Screenshots**
![Filter UI](https://user-images.githubusercontent.com/479389/178983646-9403e183-013e-48b6-8afe-95b2285d51be.png)

**Desktop (please complete the following information)**
 - OS: Linux
 - Browser: Firefox 102
 - Version: 22.05.3.1

**Comment by yurkobb** [comment]
A simple test file: [test-colors.ods](https://github.com/CollaboraOnline/online/files/9112042/test-colors.ods)

**Comment by Ezinnem** [comment]
The issue has been fixed with the patch: https://github.com/CollaboraOnline/online/pull/5130

User can no longer Unselect All.
