### ISSUE TITLE
Remove duplicated SVG files and use iconURLAliases instead

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#5052]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @pedropintosilva @eszkadev 

### Detailed description and rationale
We want to use the existent possibility to specify name alias for icons that are  generated via jsbuilder (sidebar, notebookbar) so we can:
-  Avoid having multiple duplicated icons with different names:
  - Example: 142097b3402e0d9aa3221a6e326c6db20137e34a
- Avoid solely removing icons files
  - Even though we want to use the same icon, in some cases the uno commands and thus the generated id are actually different from ones used in writer and elsewhere (uno.AlignLeft <> uno.LeftPara)

### Code pointers
[iconURLALiases](https://github.com/CollaboraOnline/online/blob/master/browser/src/control/Control.JSDialogBuilder.js#L2444)

### Links to related documentation
https://collaboraonline.github.io/post/build-code/

### Additional notes, tips & tricks
...

**Comment by Andreas-Kainz** [comment]
It's nice to have the option to link icons. What I don't understand is, why we can't use the link.txt file from libreoffice. Cause than we can copy the complete colibre/cmd folder from core to use it in cool and no double work is needed and cool didn't have to care about icons in general.
