### ISSUE TITLE
Remove any trace of ID with digit as suffix within CSS files

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#5053]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @pedropintosilva 

### Detailed description and rationale
Elements with a digit at the end. Example #Save1 is generated to make ids unique, but it's not guaranteed to be always in the same place, meaning: sometimes the suffix might be added to the other element instead that shares the same base ID. Moreover, it can also get changed in the future as a result of other changes.

### Code pointers
Example: 160467ac964fbda60da7f72f7ea1e76576a3af3d

### Links to related documentation
...

### Additional notes, tips & tricks
...

**Comment by ArshErgon** [comment]
Hey @pedropintosilva quick question, do we have to change the classes name also? and can you assign this to me?

**Comment by pedropintosilva** [comment]
@ArshErgon Cool, assigned :) hm.. not sure if I understand. No need to change classes, I think. You can use other existing classes already or parent classes. So in the example of `#Save1` it was already fixed with https://github.com/CollaboraOnline/online/commit/160467ac964fbda60da7f72f7ea1e76576a3af3d, but we probably have more of these lying around

**Comment by ArshErgon** [comment]
@pedropintosilva I am asking about this example: `#style1`  like this has a suffix with an integer, but `#style1` is already mentioned as an `<element id="#style1">` do I have to remove this also? I think removing this will cause trouble, they would be many cases like this, Should rename it as `#styleOne`

**Comment by ArshErgon** [comment]
@pedropintosilva please close this issue it has already been solved.

**Comment by pedropintosilva** [comment]
ok @ArshErgon thanks for taking the time to check and test it left and right, I highly appreciated !
