### ISSUE TITLE
Add dark mode toggle

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#5054]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @eszkadev 

### Detailed description and rationale
Currently dark mode kicks in depending on user's system due to
```css
@media (prefers-color-scheme: dark) {
```
https://github.com/CollaboraOnline/online/blob/master/browser/css/color-palette-dark.css#L1

It would be good as a next step to add:
- new icon within View tab (Tabbed view)
- new menu entries to view menu (Compact view)
- Ideally and at least for now it would be good to always load the normal palette and load the dark one only upon user's action (clicking the toggle)
  -  At least for now that the dark mode is not complete
  - 
### Code pointers
https://web.dev/terra-dark-mode/ has a nice JS snippet (using window.matchMedia) that we could use for explicitly loading a piece of CSS in one or the other case.

**Comment by pedropintosilva** [comment]
this seems to be a problem already report on https://forum.collaboraonline.com/t/switch-between-light-dark-theme-code-22-05/1259/3 that people are getting dark mode by default depending on their system and as this is not ready yet would be good to get this easy hack in

**Comment by Pransav290302** [comment]
I would like to add that dark mode toggle button with nice design @pedropintosilva ...

**Comment by pedropintosilva** [comment]
Hi @Pransav290302 and welcome! I think Christopher has already a WIP fix for this but I think we have a couple of nice easy hacks waiting for someone to pick them up ;) like this one: https://github.com/CollaboraOnline/online/issues/4920

**Comment by Pransav290302** [comment]
Yess,i wll help @ChrisGlad by providing him an icon .

**Comment by pedropintosilva** [comment]
Thanks @Pransav290302 I have pinged you in the #5084 feel free to answer so I can assign you (Github doesn't allow to assign people unless they comment first)

**Comment by pedropintosilva** [comment]
fixed with https://github.com/CollaboraOnline/online/pull/5102 and added to feature branch
