### ISSUE TITLE
Mouse and keyboard Input bug

### ISSUE THREAD

**Issue by raghudaw** [CollaboraOnline/online#5055]
Hi, 

I have been using your App for Ipad , its excellent. Love the features. But since I use Ipad for daily use rather than a PC, i find it difficult to interact with Mouse and Keyboard.

Sometimes it just rejects input from peripherals and even if it works, its not accurate. 
I mainly use Spreadsheet and the selecting or typing is big issue.  

Kindly resolve it.

**Comment by Ezinnem** [comment]
@raghudaw, Please can you share more detailed steps on how to reproduce the issue that you experienced?

That would help us investigate the issue better.

**Comment by Ezinnem** [comment]
Closing this issue due to lack of feedback. 
This issue can be reopened when more details are provided

@raghudaw, you are welcome to send more detailed steps to help us investigate the issue better.
