### ISSUE TITLE
Input in percentage formatted cells does not work properly - calc

### ISSUE THREAD

**Issue by avatar1024** [CollaboraOnline/online#5069]
Hello,

If a cell has percentage formatting and we enter a number, say 1, then the input becomes 100% (i.e. 1) instead of 1%. So while it is numerically/mathematically correct, it is at odd with the normal spreadsheet behaviour where you want to enter number as percentages in cells that have percentage formatting (i.e. if I type 1 in such a cell, what I mean is 1% and not 100%). This issue makes it hard to work with percentages in Collabora.

How to reproduce:

1. Open a spreadsheet and format the a as percentage
2. Enter a number in it, say 1

Expected behaviour:
The cell should display 1% (like it does in LibreOffice)

Actual behaviour:
The cell displays 100%

**Comment by Ezinnem** [comment]
Confirmed in:

COOLWSD version:
22.05.4.1snapshot git hash: [dd6c5b1](https://github.com/CollaboraOnline/online/commits/dd6c5b1)

**Comment by thebearon** [comment]
This should now be fixed by #5320 in 22.05.7.
