### ISSUE TITLE
Add dark mode toggle icon

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#5084]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @pedropintosilva 

### Detailed description and rationale
This icon is to be used in the new dark mode toggle #5054 

### Code pointers
* Where: browser/images
* Branch: Please push PR against [feature/dark-mode](https://github.com/CollaboraOnline/online/tree/feature/dark-mode) (not master)

**Comment by pedropintosilva** [comment]
@Pransav290302 ^

**Comment by hanswang123456** [comment]
Can I attempt this issue?

**Comment by pedropintosilva** [comment]
Hi @hanswang123456 yes!

**Comment by pedropintosilva** [comment]
I have just assigned this to you

**Comment by hanswang123456** [comment]
Feel free to work on the issue too @Pransav290302

**Comment by hanswang123456** [comment]
I have made made a prototype for the darkmode icon. let me know if I need to re-title the pull request or change up the design.

**Comment by hanswang123456** [comment]
@pedropintosilva, I've replaced the previous pull request and made sure to only have 1 commit.
