### ISSUE TITLE
Discovery uses non-standard action names

### ISSUE THREAD

**Issue by mikekaganski** [CollaboraOnline/online#509]
ca00470722ec7a7a7b190ca36a1f71da06ed6847 had introduced a `view_comment`
 action name to discovery (used for PDF). But according to [WOPI](https://docs.microsoft.com/en-us/openspecs/office_protocols/ms-wopi/01f8f72c-cb5b-48be-b747-4bb35cbd0d4f), action name has `st_wopi-action-values` simple type, which is an enumeration, having restricted set of values. Although [section 3.1.5.1.1.2.3.1](https://docs.microsoft.com/en-us/openspecs/office_protocols/ms-wopi/429749b7-5ec3-4553-a589-0ec5240121ad) tells that "It is important to note that while the following schema restricts this type, WOPI servers MUST NOT fail when they encounter additional values not included in this schema", this should not be confused with extensibility of the attribute by implementations: rather this is a precondition to further extension of this enumeration *in the standard*, which allows older servers to communicate with newer clients.

So possibly we need to replace the use of non-standard action names in our discovery with some of the standard names - possibly `rest`? or maybe `formedit` (but that's rather stretching the idea).

This needs to provide the required changes related to the mentioned commit, and also to fix possible fallouts in integrations.

**Comment by mikekaganski** [comment]
Or maybe just use the old `view` action, and enable commenting features based on the document type and user permissions on the file?

**Comment by kendy** [comment]
@mikekaganski: I had a look at the documentation too, and actually the closest is I think "interactivepreview"; but I'd keep it as our own extension, as you point out, nothing really bad with a different value. Having said that, we should have also a "view" in addition to that, for the case we'd need to use a different urlsrc fo that at some stage, or anything...

**Comment by kendy** [comment]
I mean, like:

<action name="view_comment" ext="pdf" .../>
<action name="view" ext="pdf" .../>

**Comment by pedropintosilva** [comment]
https://github.com/CollaboraOnline/online/commit/05dba7ad86e4bc5ddde3fcfb3faca2c4458c676b fixed this issue, thanks @mikekaganski
