### ISSUE TITLE
Tile graphic issues during enter words in LibreWolf

### ISSUE THREAD

**Issue by wadaki** [CollaboraOnline/online#5116]
**Describe the bug**
Since the latest update, when I enter words in a document, I get big colored Quadrant in my document.

**To Reproduce**
1. Go to 'Nextcloud, create a new document, open with Nextcloud Office'
2. Write something
3. See error

**Screenshots**
![20220807_205653](https://user-images.githubusercontent.com/8577568/183289703-fb991c18-194e-4f48-8bab-a20838ac8369.png)

**Desktop (please complete the following information)**
 - Server: Debian 11 with Nextcloud 22.03 and latest CollaboraOnline Addon, Client: Manjaro Linux
 - Browser: LibreWolf
 - Version: 103

**Comment by Ezinnem** [comment]
Documents can be opened and edited with any graphics issues using Chrome, Brave, and Firefox browsers.

This issue is only reproducible when using the LibreWolf browser.

@wadaki, please can you test again using any of the browsers?

**Comment by wadaki** [comment]
Yes, correct. I test it with FF and it's works. But with Collabora Online version before was no issues. So this is NOT a browser issue only.
