### ISSUE TITLE
formulabar was shown on mobile after click main-menu-btn

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#5120]
https://user-images.githubusercontent.com/8517736/183301530-4e5688bc-607b-4956-b230-68892a30b63d.mp4

**Comment by Andreas-Kainz** [comment]
On mobile after click top right the hamburger menu the formulabar from calc was shown also in writer, impress, ... you see the bottom border.

![image](https://user-images.githubusercontent.com/8517736/183301593-1df96a7c-b02d-4c0d-87f7-1f18dbf64305.png)

**Comment by Andreas-Kainz** [comment]
@eszkadev any idea?

**Comment by Ezinnem** [comment]
Reproducible in:
COOLWSD version:
21.11.6.1 git hash: [6706dd457](https://github.com/CollaboraOnline/online/commits/6706dd457)

**Comment by Ezinnem** [comment]
Fixed with the patch: https://github.com/CollaboraOnline/online/pull/5668
