### ISSUE TITLE
Stop JSDialogs labels changing color on hover 

### ISSUE THREAD

**Issue by NickWingate** [CollaboraOnline/online#5128]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @pedropintosilva 

### Detailed description and rationale
When hovering over a JSDialog:
* All labels change colour.
  * This isn't noticeable in light mode, but is distracting in dark mode.
* Additionally, the text can be hard to see as it lacks contrast.

#### Examples:
`Home > Find And Replace`
![](https://i.imgur.com/zmD1id3.gif)

### Code pointers
* `browser/css/jsdialogs.css:90`
* `color-palette-dark.css`
* Where to develop, push PR: [feature/dark-mode](https://github.com/CollaboraOnline/online/tree/feature/dark-mode)

### Links to related documentation
[#928](https://github.com/CollaboraOnline/online/pull/928) - PR where style was added

**Comment by hanswang123456** [comment]
Should we change it so the text color matches the lighter shade (#e8e8e8)?

**Comment by pedropintosilva** [comment]
@hanswang123456 yup sounds good

**Comment by hanswang123456** [comment]
Ill try to resolve the issue. From what I see, removing the hover on line 90 makes it less distracting and changing the color in ui-tabs.jsdialog improves contrast:
![image](https://user-images.githubusercontent.com/50556568/186432690-bca5d63c-3b15-4869-8980-115ebc84fa45.png)

**Comment by Omkar0803** [comment]
Het @pedropintosilva  can you assign this issue to me?

**Comment by pedropintosilva** [comment]
Hi @Omkar0803 this got solved with https://github.com/CollaboraOnline/online/pull/5186 but feel free to pick any of the other easy hacks :) also we meet every week https://collaboraonline.github.io/post/communicate/
