### ISSUE TITLE
Cannot copy document comment (unless in Modify mode)

### ISSUE THREAD

**Issue by KiaraGrouwstra** [CollaboraOnline/online#5132]
**Describe the bug**
I sometimes can, sometimes cannot seem to copy comment contents in NextCloud Office.

**To Reproduce**
1. Open an ODT document
2. Open a comment
3. Select (some of) its content
4. Copy it (ctrl-c)
5. Paste clipboard content somewhere
6. Find out the selected comment text wasn't in the clipboard

**Expected behavior**
Selected text is copied

**Actual behavior**
Old clipboard content is retained

**Screenshots**
n/a

**Desktop (please complete the following information)**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 102.0

**Additional context**

-  Nextcloud Office 5.0.6
- Collabora Online - Built-in CODE Server 22.5.502

**Comment by Ezinnem** [comment]
This does not seem reproducible on my end using the:
CODE version:
22.05.5.2 git hash: [358ba77](https://github.com/CollaboraOnline/online/commits/358ba77)(E)

@KiaraGrouwstra, Please can you share a screen-recording of the issue?

**Comment by KiaraGrouwstra** [comment]
Hi @Ezinnem. I'm having trouble with screen recording due to X/Wayland stuff.
Is there any particular doubt you would like to see answered by the screen recording?
For what it's worth, I do seem able to reproduce using Chrome as well, if also on Arch.

**Comment by gitgt** [comment]
This is still "info needed" because description is too general and not normally reproducible. 
Please test again with latest CODE and add minimal screen recording, as asked.

**Comment by KiaraGrouwstra** [comment]
![collabora-5132](https://user-images.githubusercontent.com/3059397/222484866-56c5e86e-8726-4f25-9e94-41d13f685bc2.gif)

**Comment by timur-g** [comment]
This should be possible from https://github.com/CollaboraOnline/online/pull/10239 in 24.04.9.
