### ISSUE TITLE
Language Selection in Status Bar does not behave as expected in MultiLanguage Documents

### ISSUE THREAD

**Issue by SustReal** [CollaboraOnline/online#5136]
**Describe the bug**
It is up to debate, whether this is a missing feature or a bug. Currently, the language selection in the status bar does behave differently than it does on the desktop in Collabora Office or LibreOffice. If you select text and then choose a language from the options in the status bar at the bottom, I would expect **only the selection** to be changed to that language – similarly to the desktop and the “Language -> For selection” option inside the UI on the NotebookBar. However, currently it will change the whole document to the language selected from the status bar. This can cause a big mess to your MultiLanguage documents, if you are used to work with LibreOffice/Collabora Office on the desktop.

**To Reproduce**
1. Create a Writer document with various languages in different paragraphs
2. Select some text
3. Choose a language from the Language Picker in the status bar
4. See the language of all text in the document being changed to that language

**Expected behavior**
Only the language of the selected section of text should be changed

**Actual behavior**
All text in the document is getting changed when you choose an option from the language picker in the status bar – although, a part of the text has been selected…  Additionally, of course, the spell checking for the dokument kicks in and does mark all other segments of the document as misspelled.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/51329893/183934155-c1369b0d-cd1a-4086-8996-486653aa5f00.png)

**Desktop (please complete the following information)**
 - OS: [Ubuntu 22.04]
 - Browser: [Firefox 103]
 - Version: [Collabora Online 21.11.5.3, and Collabora Online 22.05.5.2]

**Smartphone (please complete the following information)**
 - 

**Additional context**

Here is a document with multiple languages to test the behaviour

[Collabora Online_WebCopy_MultiLanguage.odt](https://github.com/CollaboraOnline/online/files/9301090/Collabora.Online_WebCopy_MultiLanguage.odt)

**Comment by Ezinnem** [comment]
Reproducible in:

COOLWSD version:
22.05.5.2 git hash: [4f5845c4](https://github.com/CollaboraOnline/online/commits/4f5845c4)

**Comment by gitgt** [comment]
This possiblity was added with https://github.com/CollaboraOnline/online/pull/6854 as new options in language selector field and will be available in 23.05.2. It wil lnot be available in former versions. With that, I close this ticket. Thanks for reporting.
