### ISSUE TITLE
Copy and Paste not working in Collabora

### ISSUE THREAD

**Issue by corincorvus** [CollaboraOnline/online#5139]
**Describe the bug**
I copy something on my PC, a Link or Text, but i cant paste it in a Document or Sheet.

**To Reproduce**
1. Open Document
2. Copy Link from Browser or other Text
3. Paste it in Document

**Expected behavior**
The Text is in the Document now

**Screenshots**
If i try to use "Paste" in the Menu, i get this Message: 
![grafik](https://user-images.githubusercontent.com/21257329/183834324-ac5ba265-ccde-4836-b67f-678c76ebc8a1.png)

**Client details:**
 - OS: Windows 10, Windows 11, Linux Mint tested
 - Browser Firefox and Chrome
 - Version Firefox: 103.0.2

## Server details

**Operating system**: Debian Bullseye

**Web server:** Apache2 with Nginx Reverse Proxy

**Database:** MariaDB 10.5.15

**PHP version:** 7.4.30

**Nextcloud version:** 24.0.3

**Version of the richdocuments app** 6.2.0

**Version of Collabora Online** 22.5.502 (Code App)

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
No Log
```
</details>

Link: https://github.com/nextcloud/richdocuments/issues/2373#issue-1334162043

**Comment by Ezinnem** [comment]
@corincorvus, does the copied text get pasted when you use CTRL+V as the instruction from the dialog suggests?

**Comment by Ezinnem** [comment]
This may be very similar to the report on https://github.com/CollaboraOnline/online/issues/3928

Since they are similar, I will close this report.

@corincorvus, the issue will be tracked on https://github.com/CollaboraOnline/online/issues/3928

**Comment by corincorvus** [comment]
@Ezinnem 
https://www.youtube.com/watch?v=VNHlzPtduNY
