### ISSUE TITLE
PDF' is always 0kb

### ISSUE THREAD

**Issue by xiaohange** [CollaboraOnline/online#5149]
Question 1:
```shell
curl -F "data=@Conf.txt" http://localhost:9980/lool/convert-to/pdf > out.pdf
```
After execution, the out Pdf, but the file size of 'out. PDF' is always 0kb, and it is blank after opening;

Question 2:
I try to implement the above curl command on the python side. The code is as follows. The request always returns ` Code: 403`;

```python
files = {
        'data': open(file_path, 'rb'),
    }
    response = requests.post('http://localhost:9980/lool/convert-to/pdf > 11.pdf', files=files)
   print(response)  # 403

```

**Comment by thebearon** [comment]
Please use the forum for questions in the future: https://forum.collaboraonline.com/

The problem is that the endpoint has `/cool/`, not `/lool/` in it since version 21.11.
