### ISSUE TITLE
Autofilter doesn't work in Collabora Online 22.05.0.1

### ISSUE THREAD

**Issue by kompilainenn** [CollaboraOnline/online#5150]
**Describe the bug**
Open file from attach in COOL 22.05.0.1 and try use Autofilter, its controls just don't work and the text field for item filter too

**To Reproduce**
1. Open the file from attach in COOL 22.05.0.1
2. try enter Кузне in the text field for filter of the items in Autofilter => it happens nothing
3. try select/deselect options All/Show only current/Hide only current =>it happens nothing
4. 
**Expected behavior**
Autofilter should work 

**Actual behavior**
Autofilter doesn't work

**Desktop (please complete the following information)**
 - OS: macOS 12.5
 - Browser: Firefox 103.0.2 
 - Version COOL : 22.05.0.1 (it's an instance in libreoffice's project nextcloud)

[COOL Autofilter problem.ods](https://github.com/CollaboraOnline/online/files/9331274/COOL.Autofilter.problem.ods)

**Comment by Ezinnem** [comment]
The issue is no longer reproducible in the newer 22.05.5.3 version.

I tested using the COOLWSD version:
22.05.5.3 git hash: [23715f72](https://github.com/CollaboraOnline/online/commits/23715f72)(E)


See the patch on https://github.com/CollaboraOnline/online/pull/5130
