### ISSUE TITLE
DisableCopy does not remove "Save as" menu option

### ISSUE THREAD

**Issue by Raudius** [CollaboraOnline/online#5167]
**Describe the bug**
"Save as" menu option is available even when `DisableCopy` is true.  
This is the case when sharing files on Nextcloud with "Allow download" sharing option disabled.

**To Reproduce**
1. In Nextcloud have 2 users
2. `Alice` shares file with `Bob`
3. `Alice` disables "Allow download" in the share
4. `Bob` opens the shared file
5. "Save as" option available in the menu

**Expected behavior**
"Save as" option should not be available.

**Actual behavior**
"Save as" option is available.

**Nextcloud** 25.0.0-beta1 & 24.0.4
**Nextcloud office:** 6.2.0
**COOLWSD:** 22.05.4.1

**Additional context**
Sample response for `CheckFileInfo` operation in the described scenario. (`GET /wopi/files/<file_id>`) 
```json
{
  "BaseFileName": "New document.odt",
  "Size": 7774,
  "Version": "0",
  "UserId": "bob",
  "OwnerId": "alice",
  "UserFriendlyName": "bob",
  "UserExtraInfo": {
    "avatar": "http://nextcloud.local/index.php/avatar/bob/64"
  },
  "UserCanWrite": true,
  "UserCanNotWriteRelative": false,
  "PostMessageOrigin": "http://nextcloud.local/",
  "LastModifiedTime": "2022-08-18T12:20:23.000000Z",
  "SupportsRename": true,
  "UserCanRename": true,
  "EnableInsertRemoteImage": true,
  "EnableShare": true,
  "HideUserList": "",
  "DisablePrint": true,
  "DisableExport": true,
  "DisableCopy": true,
  "HideExportOption": true,
  "HidePrintOption": true,
  "DownloadAsPostMessage": false,
  "SupportsLocks": false
}
```

**Comment by Raudius** [comment]
@pedropintosilva Here is the issue I was describing in the community call ;)

**Comment by Ezinnem** [comment]
Reproducible in:
COOLWSD version: 22.05.5.3 git hash: [184488b9](https://github.com/CollaboraOnline/online/commits/184488b9)

**Comment by Raudius** [comment]
It was brought to my attention that `DisableCopy` actually disables copy-pasting in the document, not copying the file.

Disabling `UserCanNotWriteRelative` prevents writing files to the server. This also removes the "Save as" option :)
