### ISSUE TITLE
Load specific page/menu when print button clicked

### ISSUE THREAD

**Issue by elhananjair** [CollaboraOnline/online#5185]
**Is your feature request related to a problem? Please describe.**
When I try to print a document with many pages such as >50 it takes longer to convert it into PDF for print. Waiting to print a single page or current page out of all pages costs time. 

**Describe the solution you'd like**
Able to select the current page or specific page (ranges) to print at once.

**Describe alternatives you've considered**
I suggest if it's possible to provide options to select before the whole converting process. By doing that I can easily print customer pages without waiting for whole pages to be converted to PDF. 

**Additional context**
---

**Comment by Ezinnem** [comment]
Closing this issue due to no response from the author

**Comment by elhananjair** [comment]
@Ezinnem sorry that I haven't responded to your suggestions 
Currently, I am using Microsoft Edge and when I press on print Icon print layout of the browser will appear. But in your case I think that layout/UI is generated in Collabora Online. When the document page is too long, it takes a long time to get into the print layout. 

![image](https://user-images.githubusercontent.com/69236638/187914201-6d3116c8-d44a-4773-9732-a25797ac42f0.png)

**Comment by Ezinnem** [comment]
@elhananjair, please can you share a sample file?

**Comment by elhananjair** [comment]
> @elhananjair, please can you share a sample file?

 I tried this on Linux and used Firefox.

https://user-images.githubusercontent.com/69236638/189846015-748e9b36-f49f-4809-a784-59adb4ee9ecc.mp4

**Comment by Ezinnem** [comment]
I can see the issue on the Firefox browser.

@elhananjair, As a workaround, you can make use of the Chrome browser. It will allow for the selection of pages

**Comment by elhananjair** [comment]
> I can see the issue on the Firefox browser.
> 
> @elhananjair, As a workaround, you can make use of the Chrome browser. It will allow for the selection of pages

I am currently testing it with Micorosft Edge and what exactly I am requesting as a feature is native print layout on collabora online.  

https://user-images.githubusercontent.com/69236638/190125654-82dac182-a666-4f75-996a-697c9bd755c1.mp4

**Comment by pedropintosilva** [comment]
Hi @elhananjair  currently it's not possible to do this in an easy way. When the user hits the print we convert the document into PDF and send to the browser so it can handle it with its own native print capabilities. Some browser are better than other, we even thought in the past to disable the print feature for some browsers with less than ideal print handling feature but ended up let it present to allow everyone to use it. Nevertheless your issue is valid so I will let it open because we might end up coming up with something better to improve the print workflow for everyone.

**Comment by elhananjair** [comment]
@pedropintosilva currently for document files it's okay but when you can come to the spreadsheet it's really needed, e.g. you might need to print specific selections on a spreadsheet just like Microsoft Excell.

**Comment by Darshan-upadhyay1110** [comment]
@elhananjair, I've tested this on Firefox, and it works fine now. Additionally, our latest version includes a new option to print the `active sheet` in the spreadsheet file.

I'll close this issue as it's outdated, and everything seems to be working correctly in the latest version.

Thanks,
Darshan

**Comment by elhananjair** [comment]
Thank you I have confirmed and its working.
