### ISSUE TITLE
Invalid Prometheus/OpenMetric Values

### ISSUE THREAD

**Issue by genofire** [CollaboraOnline/online#5206]
**Describe the bug**

OpenMetric does not allow values to be an string: https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#values
(This should be an Label).

@mmeeks you have overseen my comment.

https://github.com/CollaboraOnline/online/pull/5203#discussion_r962158141

Please put the `doc_host`, `doc_key` and `doc_filename` to the Label (suffix, like the pid).

**Comment by mmeeks** [comment]
Sure - I did that - the output for these is:

doc_host{pid=1132173} = "localhost"
doc_key{pid=1132173} = "https://localhost:9980/wopi/files/opt/libreoffice/online/test/data/hello-world.odt"
doc_filename{pid=1132173} = "hello-world.odt"
doc_views{pid=1132173} 1
...

which seems to meet the label spec. or did I miss something (?)

**Comment by mmeeks** [comment]
So - big machines need monitoring - 1k documents or so, we can use a different and better format than prometheus of course. I can't make myself repeat all that per item; does it fly to do:

doc_pid{host="localhost",key="https://localhost:9980/wopi/files/opt/libreoffice/online/test/data/hello-world.odt",filename="hello-world.odt"} 12345

and then have a bunch of (as now)

doc_views_active{pid=12345}  2
doc_is_modified{pid=12345}  2
... etc. ...

So we don't drag all that horror and expense in CPU/memory around with us ? shoe-horning structure into the format is far from pretty; but this might be at least marginally efficient. The choice of 'pid' is just to get the hierarchical data out with a reasonably sensible, unique and short key.

**Comment by mmeeks** [comment]
Fixing it as above here: https://github.com/CollaboraOnline/online/pull/5211 - hopefully that closes this =)

**Comment by genofire** [comment]
Scraping on the new Image works, now.
Thanks
