### ISSUE TITLE
Assertion failure in the iOS app when opening a PDF document

### ISSUE THREAD

**Issue by tml1024** [CollaboraOnline/online#5215]
The assertion failure is in appendBlob() in wsd/TileCache.hpp. 

Backtrace below. Will try to get the JavaScript console output, too.

#4	0x00000001043d8d78 in TileData::appendBlob(unsigned int, char const*, unsigned long) at /Users/tml/lo/online-ios-master/wsd/TileCache.hpp:83
#5	0x00000001043eae54 in TileData::TileData(unsigned int, char const*, unsigned long) at /Users/tml/lo/online-ios-master/wsd/TileCache.hpp:64
#6	0x00000001043eac4c in TileData::TileData(unsigned int, char const*, unsigned long) at /Users/tml/lo/online-ios-master/wsd/TileCache.hpp:63
#7	0x00000001043eab90 in std::__1::__shared_ptr_emplace<TileData, std::__1::allocator<TileData> >::__shared_ptr_emplace<unsigned int, char const*&, unsigned long const&>(std::__1::allocator<TileData>, unsigned int&&, char const*&, unsigned long const&) at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk/usr/include/c++/v1/__memory/shared_ptr.h:298
#8	0x00000001043ea7f8 in std::__1::__shared_ptr_emplace<TileData, std::__1::allocator<TileData> >::__shared_ptr_emplace<unsigned int, char const*&, unsigned long const&>(std::__1::allocator<TileData>, unsigned int&&, char const*&, unsigned long const&) at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk/usr/include/c++/v1/__memory/shared_ptr.h:292
#9	0x00000001043ea6a4 in std::__1::shared_ptr<TileData> std::__1::allocate_shared<TileData, std::__1::allocator<TileData>, unsigned int, char const*&, unsigned long const&, void>(std::__1::allocator<TileData> const&, unsigned int&&, char const*&, unsigned long const&) at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk/usr/include/c++/v1/__memory/shared_ptr.h:1106
#10	0x00000001043d7320 in std::__1::shared_ptr<TileData> std::__1::make_shared<TileData, unsigned int, char const*&, unsigned long const&, void>(unsigned int&&, char const*&, unsigned long const&) at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk/usr/include/c++/v1/__memory/shared_ptr.h:1115
#11	0x00000001043d207c in TileCache::saveDataToCache(TileDesc const&, char const*, unsigned long) at /Users/tml/lo/online-ios-master/wsd/TileCache.cpp:513
#12	0x00000001043d11f4 in TileCache::saveTileAndNotify(TileDesc const&, char const*, unsigned long) at /Users/tml/lo/online-ios-master/wsd/TileCache.cpp:204
#13	0x0000000104326cec in DocumentBroker::handleTileResponse(std::__1::shared_ptr<Message> const&) at /Users/tml/lo/online-ios-master/wsd/DocumentBroker.cpp:3059
#14	0x0000000104324254 in DocumentBroker::handleInput(std::__1::shared_ptr<Message> const&) at /Users/tml/lo/online-ios-master/wsd/DocumentBroker.cpp:2637
#15	0x00000001042d9ba4 in PrisonerRequestDispatcher::handleMessage(std::__1::vector<char, std::__1::allocator<char> > const&) at /Users/tml/lo/online-ios-master/wsd/COOLWSD.cpp:3402
#16	0x00000001042319a4 in WebSocketHandler::handleTCPStream(std::__1::shared_ptr<StreamSocket> const&) at /Users/tml/lo/online-ios-master/net/WebSocketHandler.hpp:478
#17	0x00000001042251c4 in WebSocketHandler::handleIncomingMessage(SocketDisposition&) at /Users/tml/lo/online-ios-master/net/WebSocketHandler.hpp:527
#18	0x00000001042d829c in PrisonerRequestDispatcher::handleIncomingMessage(SocketDisposition&) at /Users/tml/lo/online-ios-master/wsd/COOLWSD.cpp:3281
#19	0x0000000104222024 in StreamSocket::handlePoll(SocketDisposition&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >, int) at /Users/tml/lo/online-ios-master/net/Socket.hpp:1340
#20	0x000000010421b178 in SocketPoll::poll(long long) at /Users/tml/lo/online-ios-master/net/Socket.cpp:442
#21	0x0000000104234b84 in SocketPoll::poll(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> >) at /Users/tml/lo/online-ios-master/net/Socket.hpp:692
#22	0x0000000104301fc4 in DocumentBroker::pollThread() at /Users/tml/lo/online-ios-master/wsd/DocumentBroker.cpp:273
#23	0x00000001043490a4 in DocumentBroker::DocumentBrokerPoll::pollingThread() at /Users/tml/lo/online-ios-master/wsd/DocumentBroker.cpp:106
#24	0x00000001042191e0 in SocketPoll::pollingThreadEntry() at /Users/tml/lo/online-ios-master/net/Socket.cpp:298
#25	0x00000001042395cc in decltype(*(static_cast<SocketPoll*>(fp0)).*fp()) std::__1::__invoke<void (SocketPoll::*)(), SocketPoll*, void>(void (SocketPoll::*&&)(), SocketPoll*&&) at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk/usr/include/c++/v1/type_traits:3859
#26	0x0000000104239510 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (SocketPoll::*)(), SocketPoll*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (SocketPoll::*)(), SocketPoll*>&, std::__1::__tuple_indices<2ul>) at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk/usr/include/c++/v1/thread:287
#27	0x0000000104238c5c in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (SocketPoll::*)(), SocketPoll*> >(void*) at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk/usr/include/c++/v1/thread:298

**Comment by tml1024** [comment]
No, for some reason the JavaScript console is blank when I attach to the Online Editor from Safari on a Mac. Changing the assert() to code that does a sleep(200) instead of causing an assertion failure does not help.

**Comment by plubius** [comment]
I think that this was fixed by commit 6a77255e0348b7aa3b8b6bbff0326fdaac912b73 by removing the assert so I'll close this bug. Please reopen if you think there is still work to do.
