### ISSUE TITLE
Can‘t close documents in iOS App

### ISSUE THREAD

**Issue by HeluSZB** [CollaboraOnline/online#5220]
There is no button to close a odt document in the iOS app.
![A46CC74F-A4DF-44D3-BE25-F1571EA1753D](https://user-images.githubusercontent.com/113041611/188907473-b9c8fb3d-538c-4642-80b4-8e5d2969372b.png)
iOS-Version: 15.6.1
iPad: iPad (9. Generation)

**Comment by Alternativend** [comment]
Same here on different iPads with the following versions:

coolwsd: 22.05.5.3
Collabora OfficeDev 22.05.5.3

**Comment by thebearon** [comment]
When you write iOS app, you mean the Nextcloud app, right? Not the Collabora Office app for iOS.
In which case this would be related to https://github.com/nextcloud/richdocuments/issues/2398

**Comment by HeluSZB** [comment]
Hi, that’s right. It’s in the Nextcloud iOS App. Is there any other solution, than closing the app?

**Comment by matthijsbro** [comment]
Same problem here. There is not even a button for closing the app properly. So a back button or ‘close file’ button is wanted. And/or it should open files in Collabora Office (but that app doesn’t look half as good).

**Comment by PheaNotYou** [comment]
We have the same problem…and it’s even more frustrating for our technologically-less-gifted employees.
So far, opening Collabora-charts and documents in the iOS app is a trap.
Desktop Nextcloud Collabora Online version is running smooth, but on the (different) iPads - all iOS 15.7 - there’s the missing “back-button” when viewing/modifying charts and documents.
There seems to be an invisible button (where there should be a real one - left upper screen corner) but only for a few seconds/actions, then it vanishes.

The issue #2398 addressed the same issue and was closed as solved...which it is not. Still a trap.

**Comment by thebearon** [comment]
> The issue #2398 addressed the same issue and was closed as solved...which it is not. Still a trap.

Unless you were testing with the Nextcloud Office app 7.0.0 beta2, no release has been made containing the fix. Once there is, you will see whether the fix worked or not.

Closing this, as the issue was fixed in richdocuments.
