### ISSUE TITLE
Unable to open documents when shared from one Nextcloud server to another

### ISSUE THREAD

**Issue by DaijoubuKun** [CollaboraOnline/online#5230]
**Describe the bug**
Both my brother and I have our own nextcloud servers that I manage, and they are running the same version. I am using the docker image of CODE for my document editing that I host on my server. When we try to load documents that are on one NC server or the other, they work just fine. However, my bother shared a folder from his NC server to mine and this is where things break. He is able to edit the document fine, but I am not. I can see everything else in the shared folder just fine, only editing doesn't work.

I've gone through several days of testing things around, but it looks like the error just comes down to one I see in my browser where Office.vue has an Async timeout. There is another one above that regarding something being blocked due to the content security policy, but I get those everywhere, and I haven't been able to determine if that really is the issue or not.

I am running CODE through a reverse proxy, and to be safe I have tested both inside my network and outside, and I get the same results, so I doubt that is the issue unless it somehow prevents documents from loading that are stored on another server, but as stated before, my brother can edit documents that are hosted on his server using my CODE Docker.

**To Reproduce**
Create a shared folder from one Nextcloud server to another
Try to open the document for editing on the server receiving the share
Get error that the document is unable to load

**Expected behavior**
Document is able to load and be editable as if it were on my server.

**Actual behavior**
Document appears to be loading, but after a few seconds I get the "Document loading failed" error.

**Screenshots**
![NC_issue](https://user-images.githubusercontent.com/5325300/189232187-1e02be28-6dbe-4dae-b771-148c0962ac22.png)

**Desktop (please complete the following information)**
 - OS: Slackware Linux 15.0 Kernel 5.15.63
 - Browser: Firefox
 - Version: 91.13.0esr

**Smartphone (please complete the following information)**
 - Device: Android
 - OS: 11
 - Browser: Firefox Nightly
 - Version: 106.0a1

**Additional context**
This is also failing when using the Android Nextcloud app where normally I can edit in it without issue.

**Comment by DaijoubuKun** [comment]
UPDATE: I have done some more testing, but still no solution. I was able to setup the built-in CODE server into my brother's server (I can't get it to run on mine, which is weird because they are basically the same software/OS wise). No luck. I then put both server to use the Collabora Online Demo server. No luck, and I've done all possible combinations of using my own (docker), built-in CODE, or the Demo system. As far as I can tell, this shouldn't be a config issue on my side, but I could always be wrong. Again, any help would be greatly appreciated. Thanks,

**Comment by DaijoubuKun** [comment]
UPDATE: I was finally able to get the 2 servers to show as them being trusted in the NC Settings -> Sharing. Now I'm getting an error in the admin log.

`Unable to determine collabora URL of remote server https://nextcloud.myserver.net - Remote is not a trusted server`

Where do I set it as a trusted server besides in the Nextcloud Settings under Sharing? Here is a raw log with some information redacted.

`{"reqId":"RKNkNSYhsUsQYxM2KlKg","level":3,"time":"2022-09-28T21:27:09+00:00","remoteAddr":"IP.REDACTED","user":"USER.REDACTED","app":"richdocuments","method":"GET","url":"/index.php/apps/richdocuments/index?fileId=222561&requesttoken=NoIREMCOK7b3IBft61ajkxkLe94qBR3XGvPT%2BESBYqI%3D%3AXLZ9J4Xvc9i%2FR16cuhDk%2BHdAVIdfaW%2B8cIGbsyvNLus%3D&path=%2FTEST-share%2Ftestfile.docx","message":"Unable to determine collabora URL of remote server https://nextcloud.MYDOMAIN.net - Remote is not a trusted server","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"23.0.9.1","exception":{"Exception":"Exception","Message":"Unable to determine collabora URL of remote server https://nextcloud.MYDOMAIN.net - Remote is not a trusted server","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/richdocuments/lib/Service/FederationService.php","line":220,"function":"getRemoteCollaboraURL","class":"OCA\\Richdocuments\\Service\\FederationService","type":"->"},{"file":"/var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php","line":162,"function":"getRemoteRedirectURL","class":"OCA\\Richdocuments\\Service\\FederationService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"index","class":"OCA\\Richdocuments\\Controller\\DocumentController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1015,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/richdocuments/lib/Service/FederationService.php","Line":107,"CustomMessage":"--"},"id":"6334bc364d3a0"}`

**Comment by thebearon** [comment]
I see you have also opened https://github.com/nextcloud/richdocuments/issues/2471 , which looks like a better place for this issue. Closing this one.
