### ISSUE TITLE
CODE stops working after a few minutes

### ISSUE THREAD

**Issue by tildezero** [CollaboraOnline/online#5234]
**Describe the bug**
After starting the CODE docker image, and going to the admin panel, the server works and documents load in nextcloud, but after a minutes, it stops working again in nextcloud office until I go back to the admin panel 

**To Reproduce**
1. Install CODE docker image
2. Go to admin panel 
3. Set server, and open document in nextcloud 
5. it works
6. try again in few minutes
7. it no longer works (unless you go back to the admin panel, and open the document after that)  
**Expected behavior**

**Actual behavior**
it should open the document without having to reopen the admin panel

**Desktop (please complete the following information)**
 - OS: MacOS
 - Browser: Safari
 - Version: 15.4

**Comment by gitgt** [comment]
Normally it doesn't happen. Please write CODE version, try with the new one and write here logs with that error.

**Comment by thebearon** [comment]
No reply.
