### ISSUE TITLE
Using mail address as username environment variable doesn't work

### ISSUE THREAD

**Issue by and-kal** [CollaboraOnline/online#5251]
When starting a new container with 
`docker run -t -d -p 127.0.0.1:9980:9980 -e "aliasgroup1=https://<domain1>:443,https://<your-dot-escaped-aliasname1>|<your-dot-escaped-aliasname2>:443" -e "aliasgroup2=https://<domain2>:443" -e "username=admin" -e "password=S3cRet" --restart always collabora/code` 
as suggested [here](https://sdk.collaboraonline.com/docs/installation/CODE_Docker_image.html), using an email address for the username enviroment variable (like so: `-e "username=admin@<domain1>`) causes login errors. 

For example, logging in at `https://<domain1>/browser/dist/admin/admin.html` with that mail address won't work.

`docker logs [CONTAINER]` throws a wrong user error.

Username probably needs to be a alphanumeric or special characters need to be escaped in the `docker run` command.

**Comment by timar** [comment]
Yes, it's annoying. We had special character escaping issues in the past (#1235, #1264), therefore I fear to touch this area. A workaround can be: `-e "username=admin\\@example.com"`.
