### ISSUE TITLE
Collabora freezes @ dropdown menu selection

### ISSUE THREAD

**Issue by thane984** [CollaboraOnline/online#5257]
I built a series of charts using LibreOfficeCalc and am trying to work with it using Collabora (21.11.3) on my iPhone (SE 2020, iOS 15.7) but the app keeps freezing up on me when I open up one of the dropdown lists (a cell with data validation). It doesn't happen every time but about half of the time.  I dont have this problem at all using Collabora on my iPad or when using LibreOffice on either of my laptops (Mac or PC). Do you know what might be causing this? I've tested a very scaled down version to see if its just too much processing demand, but it still happens even with a small simple file.

I see in the Developer Edition release notes that this was a known bug and was fixed in 21.11 (also this is confirmed in [this thread](https://github.com/CollaboraOnline/online/issues/3495)) but I'm not sure if that has been pushed through to the regular edition?

Thanks!

**Comment by Ezinnem** [comment]
@thane984 , Thank you for reporting.

Please can you send a sample file?

**Comment by thane984** [comment]
Yes, here you go, thanks.

**Comment by Ezinnem** [comment]
Closing this issue because there is no response from the author and the issue does not seem reproducible.
