### ISSUE TITLE
spelling suggestions don't fix on click

### ISSUE THREAD

**Issue by KiaraGrouwstra** [CollaboraOnline/online#5263]
**Describe the bug**
I make spelling errors, and expect for Collabora to help correct these.

**To Reproduce**
1. Make a spelling mistake
2. See red squiggly underlining
3. Right-click it
4. Click on the correcting suggestion
5. Find no change

**Expected behavior**
The misspelled word is replaced with the selected correcting suggestion.

**Actual behavior**
The misspelled word is left intact.

**Screenshots**
![image](https://user-images.githubusercontent.com/3059397/190854579-d133b139-7dd6-4537-89ee-a2bd7d78c627.png)

**Desktop (please complete the following information)**
 - OS: Arch Linux
 - Browser: Firefox 103.0.2
 - Version: `Nextcloud Office `6.2.0`, Collabora Online - Built-in CODE Server `22.5.502`

**Additional context**
For what it's worth, my document language here was Dutch.

**Comment by Ezinnem** [comment]
This does seem to occur on my end.
COOLWSD version: 22.05.7.0 git hash:  [1cddb21b](https://github.com/CollaboraOnline/online/commits/1cddb21b)(E)

Clicking on the correction suggestion updates the spelling on the document as expected.

**Comment by KiaraGrouwstra** [comment]
i've updated.
i notice now that this issue also appears dependent on the suggestion selected.
specifically, under document language `Dutch (Netherlands)`, a word `officiele` will yield suggestions:

- `officieel`, which works
- `officiële`, which does not work

**Comment by Ezinnem** [comment]
Actually selecting either of them works on my end

See recording:

https://user-images.githubusercontent.com/54344301/195695579-1f2dccfa-7876-4e85-98bf-fe81cce971f2.mp4

**Comment by KiaraGrouwstra** [comment]
interesting! i'm not sure how i can help reproduce this then. i'll close until i get new ideas on this.

**Comment by KiaraGrouwstra** [comment]
hm, I still seem able to reproduce this issue for spelling mistakes for documents (and words) in Dutch.

Versions tested with now:
- Nextcloud: 24.0.4
- Collabora Online - Built-in CODE Server:  22.5.702
- Nextcloud Office: 6.3.1
- Browser: Firefox 103.0.2 (64-bit) for Arch Linux

I'm not seeing any messages in the JavaScript console about this.

What versions did you use that made it work?

**Comment by timur-g** [comment]
I do not reproduce with 23.05. @KiaraGrouwstra please test again with current version 22.05.17 and check if hunspell-nl is installed and nl (or nl-NL) added to Allowed languages, and if you can check in log if really dictionary is added for nl nl-NL nl-SR nl-AW (or just nl-NL).

**Comment by timur-g** [comment]
Let me close unless there is further explanation.
