### ISSUE TITLE
CODE 22.05.6.3 Calc: Deleting in formula bar using backspace does not work if other cells in same column share common prefix

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#5302]
**Describe the bug**
You cannot delete text using backspace in the formula bar if another cell in the same column shares a common prefix with the text you try to delete.

**To Reproduce**
1. Open the attached [commenttest.ods](https://github.com/CollaboraOnline/online/files/9649134/commenttest.ods)
2. Click on Cell C7
3. Click in the formula bar, placing the cursor at its end
4. Try to delete the text using backspace

**Expected behavior**
The text can be deleted.

**Actual behavior**
Only the 4 and the space char can be deleted, then the formula bar magically shows the highlighted number "3" and gets stuck.

**Comment by Ezinnem** [comment]
Thanks for sharing the sample file.

I can reproduce in COOLWSD 22.05

**Comment by Ezinnem** [comment]
Fixed with https://github.com/CollaboraOnline/online/pull/6770

Fine on:

COOLWSD version:
22.05.16.1 git hash: [955dc4f5](https://github.com/CollaboraOnline/online/commits/955dc4f5)
