### ISSUE TITLE
Sheets not changeable V 6.2.0

### ISSUE THREAD

**Issue by KuBGrub** [CollaboraOnline/online#5306]
Hi there,
before Update to V 6.2.0 it was possible to switch between the sheets in excel files.
Now the Sheets Menubar is away.

![grafik](https://user-images.githubusercontent.com/114590879/192795774-5df41418-2fb7-4e3c-92a5-50df354dcc36.png)

**Comment by timar** [comment]
Hi @KuBGrub this looks bad. However, we have not seen this issue before. What browser do you use? Also, could you please clarify the CODE version, v 6.2.0 does not sound familiar to me. Our recent release was 22.05.6.3.

**Comment by KuBGrub** [comment]
Hi timar,
i tried different browser (Firefox, Edge..). CODE Version is **now** Up-to-Date (Docker image). Seems like a Version Problem with Nextcloud Office 6.2.0 and older CODE Docker Image. Thx for your reply
