### ISSUE TITLE
first and last values in "allowed_languages" are ignored

### ISSUE THREAD

**Issue by dvdjaco** [CollaboraOnline/online#5307]
**Describe the bug**
When running the official Docker image (22.05.6.3.1), the first and last languages in the `dictionaries` environment variable are ignored. The whole list is copied to `/etc/coolwsd/coolwsd.xml`, but the dictionaries corresponding to the first and last values are not loaded.

If we add a leading and a trailing space to the `dictionaries` list, all dictionaries are loaded.

**To Reproduce**
1. Create an environment file `lool.env`
2. Add a list of dictionaries to the file, e.g. 
`dictionaries="en_US fr_FR es_ES ca_ES"`
3. Run the docker image with the environment file:
`docker run -t -d -p 127.0.0.1:9980:9980 --env-file lool.env collabora/code:22.05.6.3.1`
4. Check the logs of the running container:
```
(...)
Allowlisted languages: "en_US fr_FR es_ES ca_ES"
Preloading dictionaries: fr-FR es-ES
(...)
```
5. Add leading and trailing spaces to the list in the env file:
`dictionaries=" en_US fr_FR es_ES ca_ES "`
6. Start the container and check the logs:
```
Allowlisted languages: " en_US fr_FR es_ES ca_ES " 
Preloading dictionaries: ca-ES en-US fr-FR ca-ES-valencia es-ES
```

**Expected behavior**
The whole list of dictionaries should be loaded.

**Actual behavior**
The first and last items in the list are read from the env file and written to the configuration file, but the corresponding dictionaries are not loaded. If we add a leading and a trailing space to the `dictionaries` list, all dictionaries in the list are loaded.

**Comment by timar** [comment]
In the bad case your first and last items are literal `"en_US` and `ca_ES"`, instead of `en_US` and `ca_ES`. I'm not sure how I should fix this in the code, you should not pass `"` marks in the first place. We use `"` marks in the command line example, where the shell consumes them and the value of the environment variable is the list without quotes.

**Comment by timar** [comment]
It works with the env file, if you don't use quotes, so I guess it's a reasonable workaround.
`dictionaries=en_US fr_FR es_ES ca_ES`
