### ISSUE TITLE
Cannot connect from multiple WOPI hosts

### ISSUE THREAD

**Issue by lukasmu** [CollaboraOnline/online#5332]
**Describe the bug**
It seems that only one WOPI host can be used at a time.

**To Reproduce**
1. The _/etc/coolwsd/coolwsd.xml_ file contains the following: 
```
<wopi allow="true" desc="Allow/deny wopi storage.">
    <max_file_size desc="Maximum document size in bytes to load. 0 for unlimited." type="uint">0</max_file_size>
    <locking desc="Locking settings">
        <refresh default="900" desc="How frequently we should re-acquire a lock with the storage server, in seconds (default 15 mins) or 0 for no refresh" type="int">900</refresh>
    </locking>
    <alias_groups desc="default mode is 'first' it allows only the first host when groups are not defined. set mode to 'groups' and define group to allow multiple host and its aliases" mode="groups">
        <group>
            <host allow="true">host1.example.org</host>
        </group>
        <group>
            <host allow="true">host2.example.org</host>
        </group>
    </alias_groups>
</wopi>
```
2. You open a document from _host1.example.org_. This works.
3. Then you open a document from _host2.example.org_. This does not work.

**Expected behavior**
Opening documents from both hosts should work.

**Actual behavior**
Only documents from a single host can be opened.

In the error log you see something like this:
```
ERR  Only allowed host is: host1.example.org, To use multiple host/aliases check alias_groups tag in configuration| wsd/HostUtil.cpp:220
ERR  No acceptable WOPI hosts found matching the target host [host2.example.org] in config.| wsd/Storage.cpp:263
ERR  loading document exception: No acceptable WOPI hosts found matching the target host [host2.example.org] in config.| wsd/DocumentBroker.cpp:2263
ERR  Failed to add session to [https://host2.example.org:443/index.php/apps/richdocuments/wopi/files/7127_oc4965xvrise] with URI [https://host2.example.org/index.php/apps/richdocuments/wopi/files/7127_oc496
ERR  Unauthorized Request while starting session on https://host2.example.org:443/index.php/apps/richdocuments/wopi/files/7127_oc4965xvrise for socket #30. Terminating connection. Error: No acceptable WOPI hosts found mat
ERR  #30: Socket write returned -1 (EPIPE: Broken pipe)| net/Socket.hpp:1431
ERR  Invalid or unknown session [008] to remove.| wsd/DocumentBroker.cpp:2308
```

The order in which steps 2 & 3 are executed matters: Only documents from the first host that connects to the Collabora server can be opened (if after restarting the coolwsd service you connect to Collabora server from _host2.example.org_ first, then this works, but you cannot connect from _host1.example.org_). 

**Details**
 - OS: Ubuntu 18.04
 - Coolwsd Version: 22.05.6.3-1 amd64

**Comment by joergmschulz** [comment]
see here https://help.nextcloud.com/t/important-changes-that-seem-to-affect-cool-docker-versions-from-v21-11-3-6-on-multiple-domains-setup/137867/2?u=wwe and follow the links

**Comment by lukasmu** [comment]
The issue apparently was that I did not specify scheme and port in the hosts section of the _/etc/coolwsd/coolwsd.xml_ file.
It should look like:
```
<group>
        <host allow="true">https://host1.example.org:443</host>
</group>
<group>
        <host allow="true">https://host2.example.org:443</host>
</group>
```
Then it works as it should
