### ISSUE TITLE
kubernetes deployment doesn't work

### ISSUE THREAD

**Issue by scrummie02** [CollaboraOnline/online#5336]
**Describe the bug**
Follow tutorial here:
https://sdk.collaboraonline.com/docs/installation/Kubernetes.html
and here:
https://github.com/CollaboraOnline/online/tree/master/kubernetes/helm

**To Reproduce**
Install HAProxy ingress controller
`kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/master/deploy/haproxy-ingress.yaml`
Prepare the namespace in the Kubernetes cluster with this command
`kubectl create namespace collabora`
Install collabora online helm chart
`helm install collabora-online ./kubernetes/helm/collabora-online/`

**Expected behavior**
collbora to be accessible when testing with curl and hostname instead get this
HTTP/1.1 404 Not Found
date: Thu, 13 Oct 2022 02:40:40 GMT
content-type: text/plain; charset=utf-8
content-length: 9

**Actual behavior**
error 400, can't access coabora

**Screenshots**

**Desktop (please complete the following information)**
 - OS: Debian microk8s
 - Browser: chrome, brave firefox
 - Version: latest

**Additional context**
proper DNS name entered in values.yaml

**Comment by lpranam** [comment]
did you add the appropriate entry in /etc/hosts file?
do collabora pods come online?

**Comment by scrummie02** [comment]
yes and yes.  I ended up just using the node port and changing the service template and the values.yaml.  

unfortunately when being used with NGINX reverse proxy SSL doesn't work.  NGINX is on an external node and is proxying back to nextcloud.  I get an error when using collabora because it says to use the same protocol but if i deploy with SSL is also fails.

**Comment by genofire** [comment]
i am not sure if it works to deploy multiple ingress operatoren on an microk8s - i believe both want to bind the same port (on same ip address).
