### ISSUE TITLE
docker container won't start

### ISSUE THREAD

**Issue by martyd1901** [CollaboraOnline/online#5341]
I'm getting the below error when trying to start my docker container in unraid

`Failed to initialize COOLWSD: SAXParseException: Invalid token in '/etc/coolwsd/coolwsd.xml', line 247 column 166
-00001 2022-10-13 22:28:46.005179 +0100 [ coolwsd ] FTL  Failed to initialize COOLWSD: SAXParseException: Invalid token in '/etc/coolwsd/coolwsd.xml', line 247 column 166| wsd/COOLWSD.hpp:490
SAXParseException: Invalid token in '/etc/coolwsd/coolwsd.xml', line 247 column 166`

any ideas on how to fix this?

**Comment by gitgt** [comment]
Please update if you managed to resolve, write your configuration un/priviledged container, version.

**Comment by thebearon** [comment]
No reply.
