### ISSUE TITLE
Percentage formatted cells: missing % upon pressing the escape key

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#5342]
**Describe the bug**

This is a corner case yet to be solved and last reported on #5320.

Within a spreadsheet document pressing `Esc` key it results in something unexpected:
- Make sure the cell is formatted as **%**
- typing 1
- The percentage is added automatically
- But pressing `Esc` and then typing again 1 the percentage is not added anymore
- Furthermore by then pressing "Enter" key it gives different result when compared to the other cases

Maybe a video is easier to understand:

https://user-images.githubusercontent.com/65948705/195557986-67a78368-ab61-431f-8993-5792222d266d.mp4

The same doesn't happen on core side:

https://user-images.githubusercontent.com/65948705/195559016-1a529f72-d56c-4040-a93e-6e9e054e7eb1.mp4

**Expected behavior**
The **%** should be added even if the escape was pressed and then a digit was enter.

**Actual behavior**
The **%** is never added again after pressing escape key

**Comment by GulsahKose** [comment]
There is a conrol browser/src/layer/marker/TextInput.js  _onInput

            if (this._map.getDocType() === 'spreadsheet' &&
                content.length === 1 && ev.inputType === 'insertText' &&                                                                                                                                                                                     
                this._isDigit(newText)) {
                this._sendKeyEvent(newText, this._unoKeyMap[newText], 'input');
            }
When we press esc and start to write again content.length should be 1 but actual result is 2 and problem occurs. 
We should update the content somewhere we pressed the escape i think. I hope that pointers helps.
