### ISSUE TITLE
Publish Helm Chart

### ISSUE THREAD

**Issue by genofire** [CollaboraOnline/online#5371]
**Describe the solution you'd like**
Create a helm chart repository, for easy use of your helm chart.

https://helm.sh/docs/helm/helm_repo/

**Additional context**
Publish also on https://artifacthub.io/

**Comment by genofire** [comment]
Setup an extra Repo (just for helmchart) and put there the github-actions in for autoreleasing: https://github.com/helm/chart-releaser-action -> [commit](https://github.com/genofire/collaboraonline-helm/commit/86ddc58010b242e29f6283a112e7d3307625dddb)

https://github.com/genofire/collaboraonline-helm

So i could use it as an Helm Repository like:
```bash
helm repo add collabora-online https://genofire.github.io/collaboraonline-helm/
helm install collabora-online collabora-online/collabora-online
```

**Comment by genofire** [comment]
@Rash419 @lpranam @timar whould you take an look to this repo and reuse it?

normally you use other ci pipeline tools and i do not know how you would release binary on an website (like an helm-.tgz and there index.yaml - the github-actions use github-releases for storing *.tgz and deployed an github-page for the index.yaml)

it would be really nice, if you support also an helm repository like this (or on another way).

**Comment by Rash419** [comment]
@genofire thanks I will checkout

**Comment by genofire** [comment]
huhu @Rash419 ...

**Comment by genofire** [comment]
FYI, it should be reachable with:
```bash
helm repo add collabora https://collaboraonline.github.io/online/
helm install --create-namespace --namespace collabora collabora-online collabora/collabora-online -f my_values.yaml
```

see: https://collaboraonline.github.io/online/index.yaml

---

it is still not publish on: https://artifacthub.io/
(but i believe i will do it)

**Comment by Rash419** [comment]
> it is still not publish on: https://artifacthub.io/ (but i believe i will do it)
maybe we want publish it on behalf of collabora
for example: https://artifacthub.io/packages/helm/haproxytech/kubernetes-ingress

**Comment by genofire** [comment]
Here it is: https://artifacthub.io/packages/helm/collabora-online/collabora-online
(on artifacthub you could claim and change ownership really easy ... so please create an organisation and i transfer it).

excatly, we should fill some informations in the chart, like an README and soon.

or annotations for the different images e.g. collabora, nginx (in dynamicConfig).

here is documentation:
https://artifacthub.io/docs/topics/annotations/helm/

**Comment by genofire** [comment]
you have claim it :) nice

**Comment by genofire** [comment]
nice #6928  is published automaticaly:
and here we the the README on artifacthub now.

https://artifacthub.io/packages/helm/collabora-online/collabora-online
