### ISSUE TITLE
Collabora Online unusable on Firefox Linux

### ISSUE THREAD

**Issue by narcotix88** [CollaboraOnline/online#5376]
**Describe the bug**
Scrolling a document is very slow on Firefox Linux (106.0 (64 bits)).
Tiles takes forever to load and scrolling is not smooth at all, making it barely unusable.
Same document, same server is very fluid on chromium based browser.

**To Reproduce**
1. Open a 30 pages writer document.
2. Scroll the document to last page.
3. See your Firefox browser struggling.

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots**
![image](https://user-images.githubusercontent.com/10205342/197965740-1d4a23ad-eace-45d5-96fc-db91bda50403.png)

**Desktop (please complete the following information)**
 - OS: Linux Fedora 37
 - Browser: Firefox
 - Version: 106

**Comment by MagsMagnoli** [comment]
Firefox on macos is also noticeably slower than brave (chrome)
Here is a side by side video

https://user-images.githubusercontent.com/4146037/198886640-88f687c2-2cc2-48f7-97c9-c6d99c181b7a.mov

**Comment by Ezinnem** [comment]
This could be related to https://github.com/CollaboraOnline/online/issues/4475

@MagsMagnoli, please can you confirm that https://github.com/CollaboraOnline/online/issues/4475 is similar to this report

**Comment by caolanm** [comment]
firefox-115.0-2.fc38.x86_64
google-chrome-stable-114.0.5735.198-1.x86_64

[ChromeAndFirefox-wheel-scroll-CO-22.05.16.1.webm](https://github.com/CollaboraOnline/online/assets/833656/22c4e13a-4d28-44a0-bfad-fcbdafc292e2)

chrome wheel scrolling then firefox, seems reasonable to me, taking into account firefox's apparently smaller wheel scroll distance.

**Comment by timur-g** [comment]
Let us close. Seems duplicate to https://github.com/CollaboraOnline/online/issues/4475 , plus not unusable.
