### ISSUE TITLE
LanguageTool only works for English.

### ISSUE THREAD

**Issue by narcotix88** [CollaboraOnline/online#5377]
**Describe the bug**
The LanguageTool grammar checker is a great feature, but it only works for English. 

**To Reproduce**
1. Write a text with grammar mistakes with paragraph language configured in en_Us
2. See your mistakes underlined.
![image](https://user-images.githubusercontent.com/10205342/197968534-99496bf6-4d3b-47da-ba2e-13e273973172.png)
4. Change the language to "French France"
5. Make grammar mistakes
6. Nothing happens.
![image](https://user-images.githubusercontent.com/10205342/197969061-f2140d4f-acd7-4f60-af82-7c03533281e4.png)

**Expected behavior**
The errors should be underlined. This is the same text checked on the LangageTool website.
![image](https://user-images.githubusercontent.com/10205342/197969481-37edbf49-1d49-4fb5-9f40-9fe584b6bded.png)

**Desktop (please complete the following information)**
 - OS: Fedora 37
 - Browser: Brave
 - Version: v1.45.113 

**Additional context**
To track the problem, I configured a local LanguageTool server. When you check a French sentence, the request to LanguageTool is badly formatted. It uses "en-US" instead of "fr-FR"

Here is the LanguageTool log for a request in French :
`org.languagetool.server.TextChecker Check done: 13 chars, en-US, requestId: null, #1, null, 0/1 matches, 6800ms, agent:-, sent, q:0, h:1, dH:1, r:1, m:all, premium: false`

The same issue is also present in LibreOffice. 
_Using coolwsd 22.05_

**Comment by nikslor** [comment]
Hi @narcotix88

I'm aware of some similar issues with the LT integration and reported them to the devs on a different channel. I raised some more budget to work on the LT integration - those changes should land in the code in a not so distant future and may also fix the issue described here. Feel free to ping me in ~three months time so we can sync about the status of this work.

**Comment by timur-g** [comment]
I tested with current Online 23.05 and LT is working fine.
