### ISSUE TITLE
Calc: Freeze row/column header is ignored on load

### ISSUE THREAD

**Issue by relikd** [CollaboraOnline/online#5383]
**Describe the bug**
I run Collabora from a Docker inside Nextcloud. I have certain spreadsheets that "forget" their row headers when I close and re-open a file. As far as I can see, this issue only happens if the spreadsheet has three or more tables.

**To Reproduce**
1. Create & open new Spreadsheet file
2. Create two additional tables
3. For all three tables set the cursor on B2 and select "freeze row/column"
4. Close and reopen the file.
5. The table that is visible at launch will have the frozen header, the other two tables will not.

**Expected behavior**
The frozen table header should stay consistent during file save/load.

**Actual behavior**
The frozen table header is ignored for all tables except a single one.
If table A has a row header, table B a column header, and table C a row+column header, upon reopening the spreadsheet on table A or B, then table C will show the opposite orientation (either row or column, not both).
Additionally, If you click unfreeze on one of the tables, the other table headers are magically restored.

**Screenshots**

**Desktop (please complete the following information)**
 - OS: macOS
 - Browser: Firefox
 - Version: 106

**Additional context**
N/A

**Comment by Ezinnem** [comment]
The issue does not seem reproducible on my end.

I tested on:

COOLWSD version:
22.05.8.0 git hash: [b43544da](https://github.com/CollaboraOnline/online/commits/b43544da)(E)

@relikd, please can you share the COOLWSD version you encountered the issue with?

**Comment by relikd** [comment]
I initially tested it with:

LOOLWSD
6.4.10 (git hash: d12ab86)

but now, after a sucessful update, I can reproduce the same issue with.

COOLWSD
22.05.7.2 (git hash: b639546)

**Comment by relikd** [comment]
I dont know if its relevant but this is with the currently latest docker image collabora/code:latest

**Comment by rpear** [comment]
I get a different experience, similar, it is livable with. I have tested with COOLWSD version: 22.05.10.1 snapshot, git hash: 23082d8

- When I re-open the prepared spreadsheet only one of the 3 sheets behaves properly with its Frozen rows and columns, the other 2 sheets scroll away even though the Freeze rows and columns button is still highlighted, so this is wrong.
- Note that it was inconsistent which sheet was open when I re-opened the spreadsheet, i.e. if I closed it with sheet3 highlighted it might open again on sheet2, ...it is possible that I had not made any changes and saves though.
- **However, note this:** if I click on another sheet (let's call it sheet 4) that does not have the Freeze rows and columns button highlighted, then go back to the misbehaving sheet, the Frozen rows and columns starts behaving correctly again.  Repeat this for the other sheets that are misbehaving.

**Comment by RegisPerdreau** [comment]
Still on 22.05.12.4

**Comment by Ezinnem** [comment]
I can confirm the issue

**Comment by gitgt** [comment]
Should be fixed in COOLWSD version: 22.05.14-3.
