### ISSUE TITLE
Tabbed view: bigtoolitem has decreased in size

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#5395]
**Describe the bug**
The `bigtoolitem` went from `32px` to `24px`. 

**To Reproduce**
1. View > tabbed view
2. Look at the icons that have label underneath 
3. Observe their size (they are not bigger than the icons with inline labels)

**Expected behavior**
`bigtoolitem` should be bigger than the icons with inlined labels

**Actual behavior**
Has exactly the same size as the rest (24px)

**Screenshots**

https://user-images.githubusercontent.com/65948705/198964693-5a97cd26-bb81-465a-ae0b-f756f06c8844.mp4

**Desktop (please complete the following information)**
Master

**Additional context**
`.hasnotebookbar .ui-content .unobutton` is not being applied. Plus, probably worth to change the way we are targetting those buttons from CSS side

```html
<div class="unotoolbutton notebookbar ui-content unospan-Insert unoInsertGraphic has-label has-dropdown" id="InsertGraphic1" tabindex="0"><img class="ui-content unobutton" src="lc_insertgraphic.svg" id="InsertGraphic1img" alt="InsertGraphic1"><span class="ui-content unolabel">Image</span><i class="unoarrow"></i></div>
```

**Comment by sharmadhiraj86** [comment]
Hii @pedropintosilva, I would like to solve this issue. Please assign me this issue.

**Comment by 2022H1030042G** [comment]
Hi @pedropintosilva, I would like to work on this issue. Can you assign it to me?

**Comment by Andreas-Kainz** [comment]
Nobody has to assign to an issue. Go for it and submit a PR.

**Comment by pedropintosilva** [comment]
@sharmadhiraj86 are you still interested in working on this? Otherwise I can assign to @2022H1030042G

**Comment by 2022H1030042G** [comment]
Can you share the details where do I have to make the changes (under which directory/file)?

**Comment by pedropintosilva** [comment]
@2022H1030042G the first step would be to have Collabora Online working locally on  your computer so you can work and test your changes : https://collaboraonline.github.io/post/build-code/ do you have it? Alternatively you can use GitPod are you familiar with that?

**Comment by 2022H1030042G** [comment]
@pedropintosilva, I'm using Gitpod for now.

**Comment by pedropintosilva** [comment]
ok, so the file is notebookbar.css and it seems  `.hasnotebookbar .ui-content .unobutton` rules are being overruled

**Comment by 2022H1030042G** [comment]
So, all I need to do is change the width and height to 24px?

**Comment by 2022H1030042G** [comment]
@pedropintosilva, Can you please confirm?

**Comment by 2022H1030042G** [comment]
Do you the know the corresponding html file where this css is used?

**Comment by pedropintosilva** [comment]
It seems @Andreas-Kainz went ahead and created a PR for that

**Comment by rizmut** [comment]
Is this change accompanied by support for SVG icons that actually have dimensions of 32px*32px?

**Comment by rizmut** [comment]
> Is this change accompanied by support for SVG icons that actually have dimensions of 32px*32px?

Anyone?
