### ISSUE TITLE
Font SimSun doesn't work

### ISSUE THREAD

**Issue by sidey** [CollaboraOnline/online#540]
**Describe the bug**
docx with SimSun font can't render normally after I put a SimuSun font into the docker container and restart it

**To Reproduce**
1. start up collabora office online with docker image 6.4.0.14
2. download font SimSun
[simsun.zip](https://github.com/CollaboraOnline/online/files/5498220/simsun.zip)

3. put  **SimSun.ttc**  into  /usr/share/fonts/ of the container.
4. execute `fc-cache -fv` and `fc-list :lang=zh`
  > /usr/share/fonts/simsun.ttc: SimSun,宋体:style=Regular,常规
  /usr/share/fonts/simsun.ttc: NSimSun,新宋体:style=Regular,常规

5. restart container
6. trying to open a docx of characters with a SimSun font.
[test_utf-8.docx](https://github.com/CollaboraOnline/online/files/5498236/test_utf-8.docx)

**Expected behavior**
the document cant be opened in browser normally.
![document view in MS office](https://user-images.githubusercontent.com/3940510/98312861-88fedd80-200d-11eb-9059-0d8f4fac634e.png)

**Actual behavior**
an empty documents
![document view in collabora online](https://user-images.githubusercontent.com/3940510/98313269-6d480700-200e-11eb-9d5e-47ef9244199a.png)

**Desktop (please complete the following information)**
 - OS: docker docker.io/collabora/code:6.4.0.14
 - Browser:  chrome  86.0.4240.111
 - Version: 6.4.0.14

**Additional context**
I think the SimSun font file works,because characters with other fonts are rendered normally,except collabora  changed their fonts to **sans-serif**

**Comment by sidey** [comment]
I've solved this problem according to this article:
https://help.nextcloud.com/t/collobora-online-and-docker-how-to-add-new-fonts/65750/9
In fact:
**the font files must put in folder container:/opt/collaboraoffice{version}/share/fonts/truetype/
but not container:/usr/share/fonts/truetype/**

**Comment by mrkara** [comment]
@sidey Thank you for creating the issue report, and then also sharing the solution. :)

This looks like a very good fit for our forum where COOL installation and configuration topics belong to: https://forum.collaboraonline.com/c/installation-configuration/10

I'll try to move your question, along with the solution, to the forum soon, but if you would like to do it yourself, please feel free to beat me to it. That's very welcome.

Thank you again! :)

**Comment by sidey** [comment]
@mrkara Please help yourself to create a topic on collaboraonline forum about this solution.
And thanks for your work on CODE :)
