### ISSUE TITLE
Accentuated letters entered with dead keys can't be typed in Calc 22.05.6.3

### ISSUE THREAD

**Issue by tech-sesum** [CollaboraOnline/online#5400]
**Describe the bug**
As I try to type an accentuated letter as a dead key combination (Accent + vowel) in an existing cell, partially filled, it is deleted right away.

**To Reproduce**
1. Observed in Collabora 22.05.6.3
2. Have a spreadsheet created in XLSX format in Microsoft Excel first
3. Enter some text values
4. Transfer the spreadsheet to where you can access it with Collabora and open it there.
5. See error as you edit an existing cell

**Expected behavior**
Diacritic-laden letters should type transparently, wether entered as dead key combination or directly from keyboard.

**Actual behavior**
Typed letter is immediately deleted. Rest of the text is unaffected.

**Desktop (please complete the following information)**
 - OS: irrelevant. This is a web-based app.
 - Browser: Vivaldi
 - Version: 5.4

**Additional context**
Collabora installed alongside Nextcloud in a VPS

**Comment by Ezinnem** [comment]
@tech-sesum please can you attach a sample file?

**Comment by tech-sesum** [comment]
Here it is (names are fictitious of course ;)). 
[liste_des_CE_anon-sample.xlsx](https://github.com/CollaboraOnline/online/files/9913040/liste_des_CE_anon-sample.xlsx)

Plus there's this annoying flashing every time I move over the sheet:

https://user-images.githubusercontent.com/117135983/199312211-e224d927-664b-4c45-877a-0cfbbaa01969.mov

**Comment by timur-g** [comment]
I tested this and could not reproduce neither issue in 22.05 or 23.05. Tested with Firefox. I do not have all French settings ,just added FR keyboard but used dead keys (right Alt)..
Based on that, I will close - although I cannot be sure if there is some additional requirement. 
 @tech-sesum please retest this and write if reproducible for you with a newer version. If so, please test with different browsers.
