### ISSUE TITLE
“Ignore all” in Collabora Online on Nextcloud AIO 

### ISSUE THREAD

**Issue by karlemilnikka** [CollaboraOnline/online#5401]
**Describe the bug**
Nothing happens when clicking on “Ignore all” in Collabora Online on Nextcloud AIO. Each word has to be ignored every time it appears. 

**To Reproduce**
1. Create a new document in Collabora Online on Nextcloud AIO.
2. Write something that is clearly misspelled. 
3. Right-click on the misspelled word and select “Ignore all”.

**Expected behavior**
All instances of a particular word in the document is no longer indicated as misspelled. 

**Actual behavior**
Nothing.

**Screenshots**
<img width="724" alt="Skärmavbild 2022-11-01 kl  09 51 58" src="https://user-images.githubusercontent.com/20514810/199196201-423905dc-1966-4496-b248-1712ab8e7282.png">

**Desktop (please complete the following information)**
 - OS: macOS 13.0
 - Browser: Firefox 
 - Version: 106.0

**Additional context**
- COOLWSD 22.05.6.3
- Nextcloud 24.0.6
- Nextcloud AIO v2.0.4 (on Ubuntu 22.04)

**Comment by Ezinnem** [comment]
This issue does not seem reproducible on my end. I tested on: 

COOLWSD version:
22.05.8.0 git hash:  [b43544da](https://github.com/CollaboraOnline/online/commits/b43544da)(E)

@karlemilnikka, please can you test again with an updated COOLWSD version?

**Comment by karlemilnikka** [comment]
I can confirm the same issue on 22.05.7.2 now (using Nextcloud AIO 2.1.1).

**Comment by karlemilnikka** [comment]
I can confirm the same issue on 22.05.7.3 (using Nextcloud AIO 2.1.2).

**Comment by karlemilnikka** [comment]
I can confirm the same issue on 22.05.8.2 (using Nextcloud AIO 3.0.0).

**Comment by karlemilnikka** [comment]
I can confirm the same issue on 22.05.8.4 (using Nextcloud AIO 3.2.0).

**Comment by karlemilnikka** [comment]
Same issue on 22.05.9.2 (using Nextcloud AIO 4.0.1).

**Comment by karlemilnikka** [comment]
The issue is [partially confirmed](https://github.com/nextcloud/all-in-one/discussions/1652) by a Nextcloud AIO maintainer who suspects that it’s related to the Collabora Docker container (not a Nextcloud AIO problem).

**Comment by karlemilnikka** [comment]
Same issue on 22.05.9.2 (using Nextcloud AIO 4.2.0).

**Comment by karlemilnikka** [comment]
Same issue on 22.05.10.8 (using Nextcloud AIO 4.6.2).

**Comment by karlemilnikka** [comment]
Same issue on 22.05.14.3 (using Nextcloud AIO 6.0.0 with Nextcloud 26.0.2.)

**Comment by timur-g** [comment]
Confirmed in CODE docker 23.05.

**Comment by karlemilnikka** [comment]
Interesting. No, I’m not using LanguageTool or any similar service such as Grammarly.

**Comment by karlemilnikka** [comment]
Same issue on 23.05.3.1 (using Nextcloud AIO 7.2.1 with Nextcloud 27.1.0.

**Comment by karlemilnikka** [comment]
With COOLWSD 23.05.9.3 on Nextcloud 28.0.3 (Nextcloud AIO 8.0.0), “ignore all” works as intended. Unfortunately, the ignored errors don’t get stored so I have to ignore them every time I open a document. Since that’s another issue, I close this ticket as completed.
