### ISSUE TITLE
Improve connectors popup dropdown

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#5418]
**Describe the bug**
Connectors dropdown
- Remove header (no need for a category header when there is no categories)
- Convert into 2 column dropdown (as it happens on core side)
![image](https://user-images.githubusercontent.com/65948705/199525494-4547d42f-b3c2-4335-88f4-bc1b2e9730c0.png)

**Comment by sharmadhiraj86** [comment]
Hii @pedropintosilva, I would like to contribute to solve this issue. Please assign this issue to me.

**Comment by pedropintosilva** [comment]
Awesome @sharmadhiraj86 !

**Comment by sharmadhiraj86** [comment]
@pedropintosilva Please share the file name where the changes need to be made.

**Comment by pedropintosilva** [comment]
hi @sharmadhiraj86 are you still on this issue?
