### ISSUE TITLE
Go back out from an Word or Excel after editing from iPad fails

### ISSUE THREAD

**Issue by Giusemx** [CollaboraOnline/online#5419]
**Describe the bug**
When open a Word doc or Excel from an iPad (new model) only touch the nextcloud logo to go back, out from the collabora editor works. But if open the document, and edit it, after finish edit and safe, the nextcloud logo dont work anymore, so its not possible to leave the document. Only can close nextcloud completely and reopen it.
From Mac OS and iPhone OS, the problem is not there. Only iPad.

**Smartphone (please complete the following information)**
 - Device: iPad
 - OS: 16
 - Browser: Nextcloud App
 - Version: last

An X to close the editor is not there. So i need many time, to know that i need to touch the nextcloud logo to go back... no arrow or like this actually.

**Comment by thebearon** [comment]
This should be fixed in the Nextcloud Office app, please see https://github.com/nextcloud/richdocuments/issues/2398
