### ISSUE TITLE
Comments flow out of screen / comment text does not break

### ISSUE THREAD

**Issue by EDRi-org** [CollaboraOnline/online#5422]
**Describe the bug**
When replying to a comment in a rich text document, both the reply field and the original comment text are too wide and flow out of the screen.

**To Reproduce**
1. Open a rich text document with Collabora Online (CODE) in Nextcloud
2. Add a long comment, like 180+ characters, don't forget spaces
3. Click on "Reply" to add a reply 
4. See how the whole comment box becomes super wide, flows out of the screen on the right side and is really unusable

**Expected behavior**
The comment box should only be so wide as to remain entirely visible on the screen, any text (both original comment and reply) should be broken to the respective next line.

**Actual behavior**
Comment box becomes super wide and flows out of the visible screen while the reply is in editing mode.

**Screenshots**
![Screenshot for Collabora bug](https://user-images.githubusercontent.com/40486598/199686515-65046b66-394b-417d-adf3-6f4cac2eecc4.png)

**Software**
 - Browser: Firefox 106.0.2 (64-bit) on Ubuntu 20.04 LTS
 - Nextcloud Hub II (23.0.4)
 - Nextcloud Office 5.0.9
 - COOLWSD version: 21.11.0.6 
 - LOKit version: Collabora Office 21.06.10.1

**Comment by thebearon** [comment]
21.11.0.6 is an old version, please update to the most recent 22.05 version, and test again.
