### ISSUE TITLE
Add icon for send feedback button

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#5435]
We used to have repeated icons for two different action (both using ?) and I "fix" it by using the tips icon from core:
https://github.com/CollaboraOnline/online/pull/5434/commits/b3702f2a54375b11a6c03448d07756a17c7221e8

But probably better to have something more related to "send feedback"... maybe a dialog bubble behind of a user icon. What do you think?

Here is where the button is at (help tab):
![image](https://user-images.githubusercontent.com/65948705/200338715-ff64defb-f5a4-43d5-b6cd-cab6aaf63274.png)

**Comment by rizmut** [comment]
> But probably better to have something more related to "send feedback"... maybe a dialog bubble behind of a user icon. What do you think?

Pretty much like Office 365 do. :D

**Comment by rizmut** [comment]
How about using current envelope/mail icon from core (sc_sendfeedback.svg)? I just need to make a 24px version.
