### ISSUE TITLE
Sheet selection tab of spreadsheet does not appear on smart phone

### ISSUE THREAD

**Issue by Bables55** [CollaboraOnline/online#5446]
**Describe the bug**

**To Reproduce**
1. Open a spreadsheet file with sheets on smart phone.
2. Nowhere is there an area to view sheets or select sheets.

**Expected behavior**
Sheet tabs appear to switch between sheets.

**Actual behavior**
The sheet is not displayed, so it is not possible to switch to another sheet.
I remember being able to do that in older versions.

**Smartphone (please complete the following information)**
 - Device: iPhone SE 3gen
 - OS: iOS 15.7.1
 - Browser: Safari

**Comment by SakshiT25** [comment]
@Bables55 Hi, I'm interested in working on this issue. please guide me on how to start with it.

**Comment by Bables55** [comment]
When users access spreadsheet documents on their smartphones, they cannot switch sheets.
For example, with Firefox on Android, some devices even the "+" circular icon in the lower right corner is covered by the URL location bar and cannot even be touched. Is it a CSS issue?

**Comment by thebearon** [comment]
I assume this is with Nextcloud integration, in which case there's a chance this is a richdocuments bug, and the problem is with the sizing of the iframe.

**Comment by Bables55** [comment]
@thebearon , You were correct. I used another app called WOPI to connect to Collabora and the sheet showed up on smart phone.

**Comment by thebearon** [comment]
@Bables55 Please report this in https://github.com/nextcloud/richdocuments/issues .
