### ISSUE TITLE
X-COOL-WOPI-IsModifiedByUser is always true with always_save_on_exit

### ISSUE THREAD

**Issue by TijZwa** [CollaboraOnline/online#5450]
**Describe the bug**
If I enable the option 'always_save_on_exit', the X-COOL-WOPI-IsModifiedByUser is always true when uploading the document, even if the document is not modified.
When the option always_save_on_exit is off, the document is not uploaded (because it is not changed).

**To Reproduce**
1. Enable always_save_on_exit
2. Open a document, do not change a thing.
3. Close the browser
4. The header X-COOL-WOPI-IsModifiedByUser  is true.

**Expected behavior**
X-COOL-WOPI-IsModifiedByUser should be False.

**Actual behavior**
X-COOL-WOPI-IsModifiedByUser is true.

**Comment by AndrewG10i** [comment]
We also experience the same issue. Confirmed with versions: CODE v22.05.6.1, CODE v22.05.7.2.
Collabora team, FYI: it is also reported as Ticket #1003292 via support.
Thanks!
