### ISSUE TITLE
User multiply without reason

### ISSUE THREAD

**Issue by michelleDeko** [CollaboraOnline/online#5452]
Describe the bug
After some time of editing a document in Nextcloud Office, users start to multiply.

Pictures:
Users:
![grafik](https://user-images.githubusercontent.com/83840564/201307182-66239ded-19f7-420d-8a52-7062f7464b53.png)

**Comment by JB1985** [comment]
I think you are wrong here. Please reopen to Nextcloud Office -> https://github.com/nextcloud/richdocuments
