### ISSUE TITLE
[Gitpod] Bug when setting up project for contribution

### ISSUE THREAD

**Issue by hungleba** [CollaboraOnline/online#5465]
**Describe the bug**
The Gitpod console failed to run `make -j$(nproc) run` during project setup

**To Reproduce**
1. Go to the GitHub repository 
2. Click on the Gitpod green button
3. Gitpod will run and open a VCN tab (port 6080) on a separate tab
4. The error is in the terminal where make failed to run

**Expected behavior**
`make -j$(nproc) run`  runs successfully, and the developer should see an URL ending with: "hello-world.odt" in the same terminal

**Actual behavior**
An error log is printed out `make: *** No rule to make target 'run'.  Stop.`

**Screenshots**
![image](https://user-images.githubusercontent.com/51266998/201574839-04429ae3-1cf0-4230-be27-2a73ea176a20.png)

**Additional context**
* I also tried to do the setup in Ubuntu and got the same error. 
* I also referenced  [Issue 3712](https://github.com/CollaboraOnline/online/issues/3712) (closed), but it didn't help

**Comment by pedropintosilva** [comment]
Thanks @hungleba for reporting it, fixed with #5478 also Ubuntu build instructions were updated: https://collaboraonline.github.io/post/build-code/#dependencies-3

**Comment by hungleba** [comment]
@pedropintosilva thanks for looking into this. I still got an error in Gitpod when trying to run `make run`:

> CXX      tools/mount.o
>   CXX      tools/coolstress-Stress.o
>   CXX      common/coolstress-DummyTraceEventEmitter.o
> In file included from kit/Kit.cpp:77:
> ./common/RenderTiles.hpp: In function ‘bool RenderTiles::doRender(std::shared_ptr<lok::Document>, DeltaGenerator&, TileCombined&, ThreadPool&, bool, const std::function<void(unsigned char*, int, int, long unsigned int, long unsigned int, int, int, LibreOfficeKitTileMode)>&, const std::function<void(const char*, long unsigned int)>&, unsigned int, int)’:
> ./common/RenderTiles.hpp:236:78: error: no matching function for call to ‘lok::Document::paintPartTile(unsigned char*, int, int, const size_t&, const size_t&, int, int, int, int)’
>   236 |                                 renderArea.getWidth(), renderArea.getHeight());
>       |                                                                              ^
> In file included from kit/ChildSession.hpp:16,
>                  from kit/Kit.cpp:60:
> /workspace/include/LibreOfficeKit/LibreOfficeKit.hxx:605:10: note: candidate: ‘void lok::Document::paintPartTile(unsigned char*, int, int, int, int, int, int, int)’
>   605 |     void paintPartTile(unsigned char* pBuffer,
>       |          ^~~~~~~~~~~~~
> /workspace/include/LibreOfficeKit/LibreOfficeKit.hxx:605:10: note:   candidate expects 8 arguments, 9 provided
>   CXX      common/coolstress-FileUtil.o
>   CXX      common/coolstress-JailUtil.o
>   CXX      common/coolstress-Log.o
>   CXX      common/coolstress-Protocol.o
>   CXX      common/coolstress-StringVector.o
>   CXX      common/coolstress-Session.o
> make[2]: *** [Makefile:2734: kit/Kit.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[2]: Leaving directory '/workspace/online'
> make[1]: *** [Makefile:5861: all-recursive] Error 1
> make[1]: Leaving directory '/workspace/online'
> make: *** [Makefile:1652: all] Error 2

Looks like a function was called but received too many arguments

**Comment by donmor** [comment]
A param 'nMode' was added in LibreOfficeKit.hxx without any overloading, which breaks the compatibility and sucks.
