### ISSUE TITLE
I can't read Korean

### ISSUE THREAD

**Issue by ideook** [CollaboraOnline/online#5467]
![image](https://user-images.githubusercontent.com/3469152/201680211-71ca5d31-2caa-4dd7-a9b1-ca63ceef9bf5.png)

[sample pptx]
https://cloud.brdg.kr/s/sMZ65HsQ8Z2egEL/download

Documents written in Korean look broken as in the image.

**Comment by Ezinnem** [comment]
Thank you for reporting @ideook .

I tested with the sample file that you shared, I can view the Characters displayed well.
I tested on:

COOLWSD version:
22.05.8.2 git hash: [c3ac1ef0](https://github.com/CollaboraOnline/online/commits/c3ac1ef0)

![Screenshot from 2022-11-15 10-57-29](https://user-images.githubusercontent.com/54344301/201889856-68a6d136-3f74-4502-933d-f6e68012440a.png)


Please can you share the COOLWSD version you are using?

**Comment by pedropintosilva** [comment]
@ideook also worth to check if you have the respective language resources installed
> For complete user interface localization you need to install Collabora Office language resources. 
https://sdk.collaboraonline.com/docs/installation/Installation_from_packages.html#localization

**Comment by timar** [comment]
@ideook also worth to check if you have Korean fonts installed on server side.
https://sdk.collaboraonline.com/docs/installation/Fonts.html
As we cannot reproduce your problem, it does not seem like a bug in our code.
