### ISSUE TITLE
Cannot insert / delete cells since 6.4.0

### ISSUE THREAD

**Issue by avatar1024** [CollaboraOnline/online#549]
**Describe the bug**
Since installing Collabora CODE 6.4.0, I cannot see anywhere the option to insert or remove cells (I don't mean row or column which still work fine).
It's not present on a mouse right click, it's not present in the tool bar, it's not present in the Menu > Sheet, or anywhere else on the menu.

I am using it with Nexcloud but I have noticed that in [Collabora's one screenshot](https://www.collaboraoffice.com/wp-content/uploads/2020/09/CODE64_Calc_FreezeRows_NoCopy.png) the option is not there either

I am using Collabora CODE 6.4.0-14, and everything works well otherwise

**Comment by cornouws** [comment]
Hi,
Could you pls explain me where in the previous version of Online insert/delete cell was ?
I can use Ctrl+- and Ctrl++ .. but that both in 6.4.0 and the previous version..
thanks!

**Comment by Andreas-Kainz** [comment]
I will add .uno:InsertCell to the menubar->sheet-> menu. I have a patch request for menubar in master, so after that I will fix it.

**Comment by avatar1024** [comment]
@Andreas-Kainz Brilliant thank you! 

@cornouws It's true the shortcut works, thanks. For some reason I tried the other day and it didn't work (and then could not find anyway to insert / delete cells). Now it's fine though. Thank you
