### ISSUE TITLE
ColaboraOnline UI Layout

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#55]
Colabora Online is a great product but I don't understood the need of an tabbed UI in the online release. I would prefer to have an layout that follow the UX guidelines of the software Colabora Online was used (Nextcloud, ...).

![LibreOffice Online Layout](https://user-images.githubusercontent.com/8517736/94802320-bab9ce80-03e7-11eb-9e8b-c5da8f6df8b3.png)
The idea is to use the UX guidelines of Nextcloud. There markdown editor has one smale toolbar and as everywhere in Nextcloud you can open and close an Sidebar. Here is the layout of the build-in markdown editor:
![Markdown Editor Layout](https://user-images.githubusercontent.com/8517736/94802441-fd7ba680-03e7-11eb-80ed-fe77742b76cb.png)

ColaboraOnline layout mockup
- menubar where in the markdown editor the filename is.
- one toolbar where you have commands that are not available with the sidebar (default toolbar stuff from LibO)
- sidebar open by default where you have all the contextual commands for formating, image, ...

**Comment by DarkknightAK** [comment]
As I wrote also an LOOL bug report there is additional information: https://bugs.documentfoundation.org/show_bug.cgi?id=137176

**Comment by mmeeks** [comment]
Hah - so, that's a bit silly, thanks FarkknightAK =) Let me paste my response here; it's a nice mockup.

Interesting idea  =) To confirm - you want a simplified toolbar, and to move the menu in Nextcloud up over the header ?

If you fire up online and play with F12 in the browser - you can see how the iframe interacts with the Nextcloud surround; unfortunately it's really tough to get much outside the iframe - so possibly we'd need to do our own surround - but then the PHP/JS code re-use is harder; so a bit tricky.

Any ideas for things inside the frame ? (and do have a poke at it).

**Comment by pedropintosilva** [comment]
Thanks @DarkknightAK ! As @mmeeks pointed out it's kinda hard to achieve that from within the app iframe. Nevertheless your mockup made me wonder... if making the NC top bar collapsible wouldn't be advantageous for someone working with complex documents or simply for someone wanting a more immersive experience. I think that would be really cool : ) what do you think?

notes:
- the previous layout didn't got deleted and it's actually the default on NC
- the notebookbar layout is just a somewhat requested feature and now the users use to on other tools have no excuse to avoid migrating : p
- the notebookbar is also collapsible (just tab on the tab again and it will work as a toggle)

**Comment by DarkknightAK** [comment]
> Nevertheless your mockup made me wonder... if making the NC top bar collapsible wouldn't be advantageous for someone working with complex documents or simply for someone wanting a more immersive experience. I think that would be really cool : ) what do you think?

I don't understood, cause the toolbar + menubar layout is collapsible (menubar was shown/hidden).

**Comment by DarkknightAK** [comment]
However I would like to discuss about the default layouts of COOL (I know there is notebookbar too).

As long as the sidebar isn't a native html element #164 I'm not sure to show the sidebar at least for writer I don't see the big benefit.

In LibO I made an tabbed compact and a contextual toolbar layout which was really the fastest layout I have ever done for LibO. The reason is simple. Tabbed compact and contextual toolbar are nearly the same
- tabbed compact has tabs and one toolbar row
- contextual toolbar has menubar + one toolbar row
the contextual toolbar's are the same in tabbed compact and contextual.

**Comment by DarkknightAK** [comment]
tabbed compact layout
![2020-10-07 23_05_18-Untitled 1 - LibreOfficeDev Writer](https://user-images.githubusercontent.com/8517736/95388329-684e4580-08f2-11eb-90fc-4846bb161156.png)
contextual single layout
![2020-10-07 23_06_14-Untitled 1 - LibreOfficeDev Writer](https://user-images.githubusercontent.com/8517736/95388353-74d29e00-08f2-11eb-995e-d5e44d585358.png)

compare to the ribbon like UI which was done, an tabbed compact layout has the great advantage, that you don't have to care about the layout it's always one "toolbar" within a tab. You only can play with show/hide label.

**Comment by DarkknightAK** [comment]
tabbed compact layout - image context
![2020-10-07 23_05_27-Untitled 1 - LibreOfficeDev Writer](https://user-images.githubusercontent.com/8517736/95388571-c3803800-08f2-11eb-8315-6ad3235433d9.png)
contextual single layout - image context
![2020-10-07 23_06_18-Untitled 1 - LibreOfficeDev Writer](https://user-images.githubusercontent.com/8517736/95388604-d5fa7180-08f2-11eb-83ad-76a0b28999d6.png)

The context toolbar can be shared between tabbed or non tabbed layout. Less dev work (specific style previews, ONLY for ribbon UI, can be used in tabbed compact AND toolbar layout), less UI work and the user can choose between toolbar + menubar or tabbs.

**Comment by DarkknightAK** [comment]
The biggest problem of notebookbar implementation in LibO is that you edit .ui files compare to xml files which are way easier to edit and within LibO the only layout where the user can customize the layout.
If you have in COOL also two different implementations, it will cause you a lot of issues at a long run.
COOL (and also LibO) didn't has that much features, that it need a two row tabbed UI.

**Comment by DarkknightAK** [comment]
@eszkadev you know best the maintenance problem of different UI's.

**Comment by juliushaertl** [comment]
FIY we are currently working on an modified viewer mode for file editors in Nextcloud (https://github.com/nextcloud/text/issues/82 for the previous design discussion), to make the general look and feel similar between different apps like Text and Collabora. Here is a current mockup of what our designer @jancborchardt proposed.

![image](https://user-images.githubusercontent.com/3404133/95419780-922b5a80-093a-11eb-9e20-694308d67129.png)

This of course still has some minor issues:
- The header bar takes quite some space and is otherwise empty
- The title is kind of duplicate with the rename input in COOL

I see the technical limitation, that there is probably no easy way to move the menu bar (or other components of Collabora Online outside of the iframe into the header. 

We could of course consider to just show the COOL iframe, but then we would lack the quick and easy access to current editor avatars and the sharing sidebar:

![image](https://user-images.githubusercontent.com/3404133/95419920-d0c11500-093a-11eb-9094-552410ceab26.png)

**Comment by DarkknightAK** [comment]
> ![image](https://user-images.githubusercontent.com/3404133/95419780-922b5a80-093a-11eb-9e20-694308d67129.png)

yes it would be nice to have on top the menubar, in addition there would be enough space for the quick and easy access to sharing sidebar, but I also understood that if there is some limitation (iframe), it shouldn't be that a problem.

**Comment by Andreas-Kainz** [comment]
Ok I'll play around a bit with notebookbar and classic layout.

I don't think that Collabora should go that direction and the reason is simple, cause you have to maintain two different layouts with two different coding backends. Please keep your codebase as small and simple as possible. You have to maintain all that stuff, fix bugs, ...

So my proposal is to streamline the code as much as possible and have the flexibility of choise.

**Comment by Andreas-Kainz** [comment]
## classic and tabbed layout look very similar

![Classic-Layout-Contextual-Toolbars](https://user-images.githubusercontent.com/8517736/100483985-f1b41400-30fa-11eb-9cea-3b0d74b958c9.png)
![Tabbed-Layout-Default-Context](https://user-images.githubusercontent.com/8517736/100483988-f37dd780-30fa-11eb-8205-3ff182921492.png)

1. "Titlebar" with the filename
2. Menubar or Tabbar
3. Toolbar

##  Menubar transform to Toolbar 

![Menubar](https://user-images.githubusercontent.com/8517736/100484203-bb2ac900-30fb-11eb-97be-c037837797da.png)
![Tabbed-Layout-Reuse-File-Menubar](https://user-images.githubusercontent.com/8517736/100484240-d3024d00-30fb-11eb-8868-b7f93fea4e1f.png)

1. Menubar contain of .uno: commands
2. Export .uno: command contains subcommands
3. File Menubar can be reused in, writer, calc, impress, ...
4. File Menubar can be reused in File Tab of tabbed layout
   - Menubar is a drop down widget
   - Notebookbar tab show the menubar items horizontal
   - separator in menubar = separator in tabbedbar


## Resizing depend on the window width

![Tabbed-Layout-Small-Window-Size](https://user-images.githubusercontent.com/8517736/100484377-72274480-30fc-11eb-9985-c00f5236da51.png)

1. .uno: commands with subcommands can be collapsed to drop down button

## Configure

1. .uno: command can be shown as
   - Icon
   - Icon + Label left
   - Icon + Label bottom
   - Label only

Icon only view is needed for classic layout and home tab of tabbed layout (maybe for small devices)
Icon + Label left is needed for tabbed layout everywhere excl. Home tab

## Pro 

+ Simple UI, cause only one toolbar row.
+ Layout similar to google docs
+ Everything is JS, classic and notebookbar use the same backend, less code maintanance
+ In the code you define arrays with .uno: commands which can be reused in tabbs, menubars, ... -> less code maintanance

## Con

- It didn't look like MS Office 365 -> simplyfied ribbons

**Comment by Andreas-Kainz** [comment]
@eszkadev I tested `context: ['Table']` which is ok to add context related command to an toolbar. The problem is that Control.TopToolbar.js will become very very complex and non maintable if you add everything content related that way.

I suggest to separate context stuff like it was done with Control.Menubar.js so that it is possible to have an 
`getToolItems: function() { }` separated into sections for the different apps (text, spreadsheet, presentation) and context maybe also separate sections for mobile, ... Now `getToolItems: function() { }` is really difficult to read.

Maybe we can define specific "arrays" and mix them in `getToolItems: function() { }` with apps and context specific stuff. I'm for simple maintenance as always.

**Comment by Andreas-Kainz** [comment]
the notebookbar.js files are easy to maintain and work well and the UI in general was updated with every release. So I can close the issue.
