### ISSUE TITLE
Blank rotation option in impress/presentation

### ISSUE THREAD

**Issue by siccovansas** [CollaboraOnline/online#5528]
**Describe the bug**
 The slide layout panel shows a 'rotation' option when selecting an object, but it contains no options to adjust (see first screenshot). I can rotate an object directly in the slide via de round button at the top of the object, but it would be nice to also change the rotation by entering a value like is possible in LibreOffice Impress (see second screenshot).

**To Reproduce**
1. Open a slide
2. Open the 'Slide Layout' panel (at the top right)
3. Click on an object
4. Press escape
5. Look under 'Position & Size' in the 'Slide Layout' panel
6. See 'Rotation' without any options

**Expected behavior**
Allow users to change the rotation via de 'Slide Layout' panel.

**Actual behavior**
There are no options shown for 'Rotation'.

**Screenshots**
_Collabora_
![Screenshot from 2022-08-24 14-40-24](https://user-images.githubusercontent.com/696839/186422946-1298d3e4-17ad-44c3-85fe-9bec2c8e2b76.png)
_LibreOffice Impress_
![Screenshot from 2022-08-24 14-54-55](https://user-images.githubusercontent.com/696839/186423701-d07fb4d5-a87f-4eb6-94c7-5270da90d80c.png)

**Desktop**
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Version: 107.0
 - Device: Desktop

**Server details**
 - Operating system: Ubuntu 22.04
 - Nextcloud: 25.0.1
 - Collabora Online - Built-in CODE Server: 22.05.802

**Comment by timar** [comment]
Commit	1fac2846b2cbfc4773d1a3db3f517c5088b5ac5a disabled the 'Rotation' label. The original problem was that this special angle selector widget was not supported in COOL. Maybe it wil be supported later.
