### ISSUE TITLE
IOS App 22.05.8 (2) crashes opening (larger) files

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#5532]
**Describe the bug**
Running the beta IOS App 22.05.8 (2) which crash opening (larger) files (PDF, PPTX, etc). Just small files seem to work open fine.

**To Reproduce**
1. Go to 'Collabora Office' App, start the App
2. Select a file to open, for example a PPTX (or PDF)
3. Progress bar shows the files is "imported", at the end of the bar App just shuts down 
4. App crashes/stops
5. Can still switch back to the Collabora App file explorer screen to select anoter file for opening, so the app is not fully crashed but just not able to display the file I guess

**Expected behavior**
File should be openend and displayed

**Actual behavior**
App crashes/stops opening the file

**Screenshots**
-

**Smartphone (please complete the following information)**
 - Device: iPhone 14
 - OS: iOS 16.1.1

**Additional context**
Shared several crash documents from the app to the beta address.

**Comment by sebastiaanveld** [comment]
[FOSDEM_2022_Gtk4.odp](https://github.com/CollaboraOnline/online/files/10105115/FOSDEM_2022_Gtk4.odp)
Example document to duplicate the issue.

**Comment by sebastiaanveld** [comment]
Still an issue in Testflight App 22.05.8 (22.5.202302092239)

**Comment by plubius** [comment]
@sebastiaanveld I think that I have fixed this bug in the latest TestFlight version. I am now able to open your [FOSDEM_2022_Gtk4.odp](https://github.com/CollaboraOnline/online/files/10105115/FOSDEM_2022_Gtk4.odp).

Is the bug fixed for you?

**Comment by sebastiaanveld** [comment]
Looks fixed @plubius, thx! Tested multiple document formats I had issues with and all open now. 
Ticket can be closed for me.

**Comment by plubius** [comment]
@sebastiaanveld Thank you for testing my fix. I will keep this open for now so that I remember to retest the fix when we eventually release a version in the regular App Store.

**Comment by plubius** [comment]
If the crash is still not occurring in the latest TestFlight build, feel free to close the bug.

I included the latest Online JavaScript code changes in the latest TestFlight build and it appears to me that you sample document loads all the slide a lot faster than even the last TestFlight build.

**Comment by sebastiaanveld** [comment]
Tested and works for me in Collabora Office 22.05.10 (22.5.202303132008) in Testflight

Thx!
