### ISSUE TITLE
Shared editing doesn't work in Nextcloud 25

### ISSUE THREAD

**Issue by osscombat** [CollaboraOnline/online#5537]
Hi!

I was playing around with rebuilding the code (as per https://collaboraonline.github.io/post/build-code/#build-code-on-debian), and noticed that Shared editing of the files is not working the way it is explained [here](https://www.collaboraoffice.com/wp-content/uploads/2016/06/collabora_online_v1_shared_editing.pdf).

The shared files open in the Editor mode for every user, so there's no Viewer/Editor mode at all!

COOLWSD: 22.05.9.0

LOKit: Collabora Office 22.05.8.3

What's the cause of this?

**Comment by thebearon** [comment]
That is a very old document. When you share a file in Nextcloud, next to the user, or to the Share link entry, there's an `Allow editing` checkbox that controls this.
