### ISSUE TITLE
Add code of conduct and contributor guides, Socials links

### ISSUE THREAD

**Issue by ADITYADAS1999** [CollaboraOnline/online#5550]
**Is your feature request related to a problem? Please describe.**
When someone try to contribute or try to connect with socials, search in the repo for more info

**Describe the solution you'd like**
Easy to contribute for new contributors, beginners. By adding socials collaborate with more people.

**Comment by pedropintosilva** [comment]
Hello @ADITYADAS1999 and thanks for taking the time to report :)

It seems we already have many of those things in or referenced in the repository itself:
* reference to the detailed building steps, easy hacks (nice bugs to start with) also info on translations, chat and forum https://github.com/CollaboraOnline/online#website
* https://github.com/CollaboraOnline/online/blob/master/CODE_OF_CONDUCT.md
  * https://github.com/CollaboraOnline/online/blob/master/README.CONTRIBUTING.md
  * https://github.com/CollaboraOnline/online/blob/master/CONTRIBUTING.md
* The direct links for IRC and Forum : https://github.com/CollaboraOnline/online#developer-assistance
* More dev bits: https://github.com/CollaboraOnline/online#development-bits
* More info:  https://github.com/CollaboraOnline/online#further-recommended-reading-with-build-details

We are missing social media links, thanks for the heads up!
