### ISSUE TITLE
Bibliography icons

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#5555]
add 2 icons for the new Zotero integration as seen in https://github.com/CollaboraOnline/online/pull/5521

**Comment by Andreas-Kainz** [comment]
@lpranam can I get a screenshot where the icons were needed and what they do. Thanks

**Comment by pedropintosilva** [comment]
this ended up being done by @rizmut :)

**Comment by rizmut** [comment]
Nice finding @pedropintosilva
