### ISSUE TITLE
Icons Not Showing in Nextcloud App

### ISSUE THREAD

**Issue by Fleench** [CollaboraOnline/online#5579]
When using the editor on my nextcloud server the icons for function such as bold or underline are not visible.

**To Reproduce**
1. Open a document
2. Look at the top bar

**Expected behavior**
Icons to be visible

**Actual behavior**
Icons are hidden

**Screenshots**
![image](https://user-images.githubusercontent.com/47568518/206499499-a3af0211-7874-4d30-8afe-b1d315829c52.png)
**Additional context**

**Comment by Fleench** [comment]
@Ezinnem Collabora Online - Built-in CODE Server V22.5.802
Nextcloud V25.0.0

**Comment by isdnfan** [comment]
might be related to

https://github.com/nextcloud/richdocuments/issues/2227

https://github.com/nextcloud/richdocuments/issues/2228

**Comment by Ezinnem** [comment]
I was not able to reproduce the issue.

I tested using CODE 22.5.802 with the Nextcloud V 25.0.3

See recording:

https://user-images.githubusercontent.com/54344301/223062465-2f4dc995-4f78-482c-876a-bbb15cb8ab5b.mp4

**Comment by Fleench** [comment]
I solved this issue. One day it just randomly fixed itself.
