### ISSUE TITLE
Not updated tiles/area when resizing image

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#5580]
**Describe the bug**
When resizing the picture in the attached bug doc, it seems, that parts of the document are not updated (re-rendered) as needed in Collabora Online 22.05.8.4.

**To Reproduce**
1. Open the attached document "resizing_leads_to_outdated_tiles.odt" in Collabora Online
2. Resize the picture and pull the right bottom corner over the line above the picture

**Expected behavior**
The text which previously was below the image fully stays below the image.

**Actual behavior**
The text is "visually" broken because the area left of the image is not re-rendered after the image resize action.

**Screenshots**
Before the resize:
![image](https://user-images.githubusercontent.com/1211300/206644402-693666eb-96c8-4aa6-b806-06ffab00a20b.png)

After the resize:
![image](https://user-images.githubusercontent.com/1211300/206644434-5af92136-6053-45c5-81db-3b41b9bad7aa.png)

**Desktop (please complete the following information)**
 - Browser: Firefox 106
 - Version: Collabora Online 22.05.8.4 (COOLWSD: git hash: `2d5b312` / LOKit version: git hash: `6b68488`)
[resizing_leads_to_outdated_tiles.odt](https://github.com/CollaboraOnline/online/files/10192543/resizing_leads_to_outdated_tiles.odt)

**Comment by Ezinnem** [comment]
Reproducible with the sample provided.

**Comment by timur-g** [comment]
I could not reproduce in 22.05.22, 23.05.9. Thanks @nikslor .
