### ISSUE TITLE
How to "import" PDF into Collabora Online

### ISSUE THREAD

**Issue by WarpinWolf** [CollaboraOnline/online#5592]
Using
Nextcloud [Nextcloud Hub 3](https://nextcloud.com/) (25.0.2)
Nextcloud Office	7.0.2
COOLWSD Version: 22.05.8.4
Collabora Office 22.05.8.4

Here:

- https://en.wikipedia.org/wiki/List_of_PDF_software and here
- https://www.collaboraoffice.com/wp-content/uploads/2019/12/MMeeks_ownCloud2019_ownCloud_lowres.pdf

it is stated that Collabora Office can import PDF files.

If I upload a PDF to Nextcloud and - via context menu - I "open in Nexcloud Office" then I am not able to edit or paste anything. The status bar says "write protected". How would I be able to "import" and edit / merge PDF files using COOL & Nextcloud - or is this simply not possible?

Thanks
Wolf

**Comment by timar** [comment]
Editing PDF text is not (yet) possible. You can add comments to PDF though.
