### ISSUE TITLE
Document title over menu bar on small screens

### ISSUE THREAD

**Issue by vincentkoevoets** [CollaboraOnline/online#5621]
Hello, 

I'm trying out Collabora on Nextcloud install. Seems to work very well, but on my small laptop screen (10 inch I believe) the document title falls over the menu bar, making some of the menu buttons unreachable. I will add a screenshot. I would like to try changing some settings, but the Extra menu button is not reachable so this will not work. 
Thanks for any help!
![Screenshot 2022-12-22 16 05 10](https://user-images.githubusercontent.com/43203114/209163054-585d2c54-5763-4536-9374-9ea64a49a5c9.png)

**Comment by pedropintosilva** [comment]
Thanks @vincentkoevoets for reporting. I have tested and I can confirm, this seems to happen only when using Compact view. Tabbed view seems to work well. So while this gets fixed you could try to switch to View -> Use tabbed view. 

Note: When using tabbed view you can click once again the active tab to hide it so you can free more vertical space

**Comment by Ezinnem** [comment]
Fixed using patch: https://gitlab.collabora.com/productivity/online-branding/-/commit/15ca01a55d957d9df79b5d453aec70dd7e0733fd

**Comment by Ezinnem** [comment]
Fixed using patch: https://gitlab.collabora.com/productivity/online-branding/-/commit/15ca01a55d957d9df79b5d453aec70dd7e0733fd
