### ISSUE TITLE
Tell coolwsd to return utf-8 encoded csv when calling /cool/convert-to/csv

### ISSUE THREAD

**Issue by steinm** [CollaboraOnline/online#5666]
Converting a spreadsheet to csv by calling the endpoint /cool/convert-to/csv of coolwsd works perfectly but it always seems to return latin1 encoded text and I can't see how to switch to utf-8. Either this isn't documented or it is a missing feature !?

**Comment by timar** [comment]
It is documented but it's a bit cryptic.
First, please refer to [LibreOffice help page for magic numbers (CSV export options)](https://help.libreoffice.org/latest/en-GB/text/shared/guide/csv_params.html).
For example the following command returned UTF-8 encoded CSV file for me:
`curl -F "data=@data.ods" -F "format=csv" -F "options=44,34,76" http://localhost:9980/cool/convert-to`
