### ISSUE TITLE
No URL Hyperlinks Available with ods or odt shared as link in NC

### ISSUE THREAD

**Issue by skykingisepic** [CollaboraOnline/online#5672]
**Describe the bug**
Sharing an ods or odt doc via shared link in NC doesn't allow clicking or `<Ctrl>` clicking on link to go to that URL link. Publishing a document full of URL hyperlinks for users to access is useless since they don't work. Sharing as editable is NOT an option.

**Comment by thebearon** [comment]
This is a duplicate of #1248.

**Comment by RainerBielefeld** [comment]
This is a really **[annoying](https://help.nextcloud.com/t/nextcloud-office-hyperlink-in-spreadsheet-does-not-work-in-readonly-mode/201118)** bug!

**Comment by RainerBielefeld** [comment]
And why is it "not planned" to fix an annoying bug?

**Comment by thebearon** [comment]
@RainerBielefeld As noted:
> This is a duplicate of https://github.com/CollaboraOnline/online/issues/1248.

Please see there. And it's supposed to be resolved now.
