### ISSUE TITLE
Writer -> Content Control Properties Dialog overlapping buttons

### ISSUE THREAD

**Issue by hmeeks-dot** [CollaboraOnline/online#5787]
**Describe the bug**
Writer->Form->Properties

**To Reproduce**
1. Writer->Form->Insert Dropdown (ONLY FOR THIS TYPE)
2. Go to Form->Properties
3. See dialog
4. See error - Messy dialog

**Expected behavior**
Normal Dialog

**Actual behavior**
Overlapping buttons

**Desktop (please complete the following information)**
 - OS: Linux
 - Browser: chrome
 - Staging Server: COOLWSD version: 22.05.10.0
  git hash: [52633056](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/52633056'));)
(E)
 

[Screenshot from 2023-01-30 11-24-35.odg](https://github.com/CollaboraOnline/online/files/10536513/Screenshot.from.2023-01-30.11-24-35.odg)

**Comment by thebearon** [comment]
Indeed, and this is a regression from the following commit:
c6e28eee58d5b62ceb52f7ecb67845d8c6b20ec6
```
Author:     Pedro Pinto Silva <pedro.silva@collabora.com>
AuthorDate: Thu Jan 5 11:00:22 2023 +0100
Commit:     Szymon Kłos <eszkadev@gmail.com>
CommitDate: Mon Jan 9 10:26:27 2023 +0100

    Add float logical values fallback for buttonboxes
```

This is what the dialog looks like now:
![dropdown_properties_current](https://user-images.githubusercontent.com/19438782/216829130-6bd6d351-9bc8-4b38-a7f1-2178be0653bf.png)

This is what it used to look like (this is an unthemed screenshot, so there are other smaller visual differences):
![dropdown_properties_previous](https://user-images.githubusercontent.com/19438782/216829190-0f2c72a8-ea6b-4b5a-9c98-3660ff7258d3.png)

And this is what it looks like in a core desktop build, with 'gen' VCL plugin:
![dropdown_properties_LO_gen](https://user-images.githubusercontent.com/19438782/216829322-eade4297-b71f-4c6f-ba2d-0ee2321b8e00.png)

**Comment by thebearon** [comment]
CC @pedropintosilva @eszkadev
