### ISSUE TITLE
Powerpoint Master corrupted

### ISSUE THREAD

**Issue by Flo-63** [CollaboraOnline/online#5798]
**Describe the bug**
Saving a PowerPoint .pptx  file results in corrupted slide master and lost slide assignments. 

**To Reproduce**
1. Create a slide deck with MS PowerPoint, using your custom slide master.
2. Assign slides from the deck to specific layouts
3. Upload it to nextcloud / owncloud
4. Edit something and save it
5. Sync it to your PC
6. Open the deck with MS PowerPoint
7. Go to View Master and see the mess.

**Expected behavior**
The Slide Master shall not be modified, assignments of slides to layout not be changed.

**Actual behavior**
Slide Master is corrupted, slide assignnents to layouts are lost.

**Screenshots**

Expected: 
![image](https://user-images.githubusercontent.com/6236477/216165319-598c44b5-b564-4598-ac12-0a5c4400e3c8.png)

Corrupted: 
![image](https://user-images.githubusercontent.com/6236477/216165975-38066a79-9e5f-479c-bb55-e4d31b46a9af.png)

**Desktop (please complete the following information)**
 - OS: Windows 10 and 11, MAC
 - Browser: Chrome, Edge, Firefox
 - Version: (doesn't matter)

**Comment by thebearon** [comment]
Please attach a sample PPTX created in PowerPoint.

**Comment by timur-g** [comment]
Online is based on Core and this is the bug in LibreOffice, so no point to have it reported here.
Please follow https://bugs.documentfoundation.org/show_bug.cgi?id=144459 but that is no simple bug because the while feature is missing in LO. 
Should it be resolved there, then report may be opened here.
