### ISSUE TITLE
Unusual extremely large tile combine of size ......

### ISSUE THREAD

**Issue by Gardosen** [CollaboraOnline/online#580]
**Describe the bug**
when working on macos with a 4k monitor which runs in scale mode, i get a block or error messages in the logs of collabora online.

**To Reproduce**
Requirements: 4k monitor (i use a Dell one) connected to the macbook
1. Set your scale mode on macos Monitor Settings to the 2nd left left
2. open a excel sheet with collabora online on nextcloud
3. observe logs of collabora online 

**Expected behavior**
all should be fine

**Actual behavior**
this logoutput

> collabora     | kit-00155-00179 2020-11-10 10:01:27.590627 [ thread-pool ] ERR  #25 Invoked from foreign thread. Expected: 0x7fdad5fe5780 but called from 140576930379520 (179).| ./net/Socket.hpp:305
collabora     | kit-00155-00179 2020-11-10 10:01:27.590659 [ thread-pool ] ERR  #25 Invoked from foreign thread. Expected: 0x7fdad5fe5780 but called from 140576930379520 (179).| ./net/Socket.hpp:305
collabora     | kit-00155-00179 2020-11-10 10:01:27.590666 [ thread-pool ] ERR  #25 Invoked from foreign thread. Expected: 0x7fdad5fe5780 but called from 140576930379520 (179).| ./net/Socket.hpp:305
collabora     | kit-00155-00179 2020-11-10 10:01:27.590990 [ thread-pool ] ERR  #25 Invoked from foreign thread. Expected: 0x7fdad5fe5780 but called from 140576930379520 (179).| ./net/Socket.hpp:305
collabora     | kit-00155-00179 2020-11-10 10:01:27.591005 [ thread-pool ] ERR  #25 Invoked from foreign thread. Expected: 0x7fdad5fe5780 but called from 140576930379520 (179).| ./net/Socket.hpp:305
collabora     | kit-00155-00179 2020-11-10 10:01:27.591020 [ thread-pool ] ERR  #25 Invoked from foreign thread. Expected: 0x7fdad5fe5780 but called from 140576930379520 (179).| ./net/Socket.hpp:305
collabora     | kit-00155-00179 2020-11-10 10:01:27.591097 [ thread-pool ] ERR  #25 Invoked from foreign thread. Expected: 0x7fdad5fe5780 but called from 140576930379520 (179).| ./net/Socket.hpp:305
collabora     | kit-00155-00179 2020-11-10 10:01:27.591109 [ thread-pool ] ERR  #25 Invoked from foreign thread. Expected: 0x7fdad5fe5780 but called from 140576930379520 (179).| ./net/Socket.hpp:305
collabora     | kit-00155-00179 2020-11-10 10:01:27.591118 [ thread-pool ] ERR  #25 Invoked from foreign thread. Expected: 0x7fdad5fe5780 but called from 140576930379520 (179).| ./net/Socket.hpp:305
collabora     | kit-00155-00038 2020-11-10 10:01:27.896984 [ kitbroker_008 ] WRN  Unusual extremely large tile combine of size 4352x512| ./common/RenderTiles.hpp:515
collabora     | kit-00155-00038 2020-11-10 10:01:28.087713 [ kitbroker_008 ] WRN  Unusual extremely large tile combine of size 4352x512| ./common/RenderTiles.hpp:515
collabora     | kit-00155-00038 2020-11-10 10:01:28.266376 [ kitbroker_008 ] WRN  Unusual extremely large tile combine of size 4352x512| ./common/RenderTiles.hpp:515
collabora     | kit-00155-00038 2020-11-10 10:01:28.442520 [ kitbroker_008 ] WRN  Unusual extremely large tile combine of size 4352x512| ./common/RenderTiles.hpp:515
collabora     | kit-00155-00038 2020-11-10 10:01:28.610488 [ kitbroker_008 ] WRN  Unusual extremely large tile combine of size 4352x256| ./common/RenderTiles.hpp:515
collabora     | kit-00155-00038 2020-11-10 10:01:28.806402 [ kitbroker_008 ] WRN  Unusual extremely large tile combine of size 4352x512| ./common/RenderTiles.hpp:515
collabora     | kit-00155-00038 2020-11-10 10:01:28.970551 [ kitbroker_008 ] WRN  Unusual extremely large tile combine of size 4352x512| ./common/RenderTiles.hpp:515
collabora     | kit-00155-00038 2020-11-10 10:01:29.125283 [ kitbroker_008 ] WRN  Unusual extremely large tile combine of size 4352x512| ./common/RenderTiles.hpp:515
collabora     | kit-00155-00038 2020-11-10 10:01:29.280301 [ kitbroker_008 ] WRN  Unusual extremely large tile combine of size 4352x512| ./common/RenderTiles.hpp:515
collabora     | kit-00155-00038 2020-11-10 10:01:29.433476 [ kitbroker_008 ] WRN  Unusual extremely large tile combine of size 4352x256| ./common/RenderTiles.hpp:515

**Desktop (please complete the following information)**
 - OS: Catalina 10.15.7
 - Browser:  chrome
 - Version: 85.0.4183.102

**Additional context**
the issue dissapears when i set my macos to use native resolution on the second monitor. but this is a resolution which is super tiny and not very handy to work with in this scenario.

**Comment by mmeeks** [comment]
Interesting; I guess we have a limit that is too small - with a 4k screen we can have 3840 pixels wide - and then two 512 tiles one on each side - so we should bump that check to (3840 + 512 * 2) I guess.
Can you patch:

common/RenderTiles.hpp-        if (pixmapWidth > 4096 || pixmapHeight > 4096)
common/RenderTiles.hpp:            LOG_WRN("Unusual extremely large tile combine of size " << pixmapWidth << 'x' << pixmapHeight);

To change the limit and submit a patch ? =) shouldn't be hard; and please do use the arithmetic form above so we can see how that is constructed later =)

Thanks !

**Comment by Ezinnem** [comment]
This issue does not occur at my end using the 6.4.10 (git hash: [b3738719](https://github.com/CollaboraOnline/online/commits/b3738719)).

@Gardosen, Please can you check if the issue still occurs at your end?

**Comment by Ezinnem** [comment]
Closing this issue due to no response from the author.
