### ISSUE TITLE
Missing Fonts dialog close button overlaps text if GUI language is Dutch (Netherlands)

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#5815]
**Describe the bug**
Missing Fonts dialog close button overlaps text if GUI language is Dutch (Netherlands). the X to close the box overlaps the message text.

**To Reproduce**
1. Go in Nextcloud to User> Settings > Language
2. Set the Language to "Dutch" ("Nederlands").
3. Go to the Files section
4. Open an document (ODT) for editing with COOL
5. Popup shows font "Montserrat" is missing
6. the X button to close the box overlaps the top border text "Ontbrekende lettertypes".

**Expected behavior**
Box should probably best (auto) resize according to the test length to avoid the overlap issue.

**Actual behavior**
The close button overlaps the message header if there are a limited amounts of missing fonts.
If there are multiple missing fonts, the Dialog resizes according to that and there is no overlap between the close button and the text.

**Screenshots**

![image](https://user-images.githubusercontent.com/37268999/216907784-5ef5eed8-c15d-4a1d-b0a0-f84b612e0ac7.png)

If there are multiple missing founts the Dialog seems to resize fine:

![image](https://user-images.githubusercontent.com/37268999/216909342-70d69155-3806-4276-8af4-b7a34b948583.png)

**Desktop (please complete the following information)**
 - OS: WIndows 11, latest patches
 - Browser: Firefox 109.0.1, 64 bit, Dutch (Nederlands)

**Additional context**
-

**Comment by Darshan-upadhyay1110** [comment]
COOLWSD version: 24.04.10.1(git hash: dc930ffa6d)
LOKit version: Collabora OfficeDev 24.04.10.1(git hash: 8b2330d)
Served by: Ubuntu 23.10
Server ID: eab785be
WOPI host:
