### ISSUE TITLE
sum cells in frozen rows and columns are not always updated

### ISSUE THREAD

**Issue by ferdiga** [CollaboraOnline/online#5818]
CODE - Collabora Office 22.05.10.1 
**Describe the bug**
sum cells in frozen rows and columns are not updated, if rows/columns between sum cell and changed data cell are invisible due to scrolling
**To Reproduce**
1. create a sheet with sum cells in frozen rows
2. lines or columns between data entry cells and sum cells must be "invisible" because of scrolling
3. change a cell content in the sum area (rows 43-45 in the test.xlsx) - some rows must be invisible due to scrolling.  
the row sum is updated, the column sum not - can also be tested with zoom in/out
4. the content of sum cells wich are "separated" by hidden rows/columns due to scrolling are  not updated
5. close the sheet and reopen - the sum is correct.

**Expected behavior**
sum cells must always be updated

**Actual behavior**
certain sum cells  are not updated - see above

**Screenshots**

**Desktop (please complete the following information)**
 - OS: maxOS 13.1
 - Browser: Brave
 - Version: 1.47.186
[test.xlsx](https://github.com/CollaboraOnline/online/files/10667687/test.xlsx)

**Additional context**

**Comment by Ezinnem** [comment]
Reproducible in:

COOLWSD version:
22.05.10.1 git hash: [23082d8](https://github.com/CollaboraOnline/online/commits/23082d8)(E)


However, the sum updates once the Save button is clicked.

**Comment by ferdiga** [comment]
thanks - nevertheless clicking the save button is a (strange) workaround for those how know the problem

**Comment by GulsahKose** [comment]
I can reproduce too. Working on this now. Thanks @ferdiga

**Comment by Darshan-upadhyay1110** [comment]
Fixed:
COOLWSD version: 24.04.10.1(git hash: dc930ffa6d)
LOKit version: Collabora OfficeDev 24.04.10.1(git hash: 8b2330d)
Served by: Ubuntu 23.10
Server ID: 2aa938f2
WOPI host:
