### ISSUE TITLE
Crash when opening presentation document in iOS app

### ISSUE THREAD

**Issue by plubius** [CollaboraOnline/online#5831]
In the 2022-02-10 TestFlight build, the iOS app will crash when opening some, but not all, .odp documents.

Steps to reproduce:
1. Put the attached [preso.odp](https://github.com/CollaboraOnline/online/files/10713753/preso.odp) in your iCloud Drive
2. Open the attached document in the iOS app
3. Crash

Interestingly, opening some .odp documents does not crash so one possible factor may be that the attached  document contains a media object (i.e. a link to an external video in this case).

**Comment by plubius** [comment]
After more testing, I found that this bug also occurs when you create a new presentation document via the iOS app's "Create Document" icons.

**Comment by sebastiaanveld** [comment]
This is probably the same issue as #5532

**Comment by plubius** [comment]
Marking this issue as a duplicate of issue #5532.

**Comment by plubius** [comment]
I have fixed this bug in the latest TestFlight version. I am now able to open my [preso.odp](https://github.com/CollaboraOnline/online/files/10713753/preso.odp) file.
