### ISSUE TITLE
Pressing the "next slide" or "previous slide" icons in the iOS app fails

### ISSUE THREAD

**Issue by plubius** [CollaboraOnline/online#5832]
In the 2022-02-10 TestFlight build, the iOS app will not allow you to move between slides in .odp documents.

Steps to reproduce:
1. Put the attached [gradient.odp](https://github.com/CollaboraOnline/online/files/10713786/gradient.odp) in your iCloud Drive
2. Open the attached document in the iOS app
3. Tap either the "next slide" or "previous slide" icons in the bottom right corner

What happens:
The displays a dialog with "The server encountered a syntax error while parsing the setclientpart command." and fails to change the current slide.

**Comment by sebastiaanveld** [comment]
If gradient.odp rendered at all before, it doesn't anymore in the latest Testflight App 22.05.10 (22.5.202302180032) or in Collabora Online (COOLWSD  22.05.10.1 git hash: [719ae9b]).

* File opens in the App (from either local iPhone storage or from Nextcloud App exposed folders)
* Content of the file does not render in the App nor does it render opening it in Collabora Online (sceenshot taken), just an empty screen is shown (only the editor space shows). File opens fine in LibreOffice 7.5.0.3.

![image](https://user-images.githubusercontent.com/37268999/219946255-f1047af3-ccff-4c59-9b85-70c314e4bdef.png)

**Comment by plubius** [comment]
Using the patch in pull request #5988, the "next slide" and "previous slide" icons now work so it appears this bug is a duplicate of issue #5887 (the code marked the document as read-only).
