### ISSUE TITLE
iOS App: dialogs not working

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#5840]
**Describe the bug**
All (?) dialogs seem not to work properly in the current TestFlight version (22.05.202302092239); they all show the same behavior:
* Insert > Title Page
* Insert > Section
* Insert > ...
* Referemces > Table of Contents and Index
* Review > Thesaurus

Only a grey area will be shown in the dialog.

**To Reproduce**
1. Open a writer document using the TestFligh iOS app
2. Change to the "Insert" tab
3. Tab on e.g. "Title Page"

**Expected behavior**
The dialog should be shown.

**Actual behavior**
Only a dialog with a grey area is shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/1211300/218399951-1c0b0b22-f185-4bfe-afc7-e7b9d8acc392.png)

**Tablet**
 - OS: iPadOS 15.6.1
 - Version: 22.05.202302092239

**Comment by plubius** [comment]
I see this too in Writer, Calc, and after I fixed issue #5831 last night, Impress.

**Comment by nikslor** [comment]
Works now, tested with 22.05.10 (22.2.202302182232).
Should I close it, or do you want @plubius?

**Comment by plubius** [comment]
@nikslor Thank you for testing my fix. I think I will leave the bug open until the fix is released in the regular App Store. I added a milestone as a hacky way to note that the bug is fixed and tested but is still in TestFlight.

**Comment by plubius** [comment]
Closing as the fix is in the latest TestFlight release.
