### ISSUE TITLE
Applying borders in a spreadsheet can't be undone

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#5844]
**Describe the bug**
Applying borders on some cells can't be undone.

**To Reproduce**
1. Open a calc sheet in online
2. Mark some cells
3. Apply borders to the cells
4. Tab undo to remove the borders again

**Expected behavior**
The borders are removed by tapping undo

**Actual behavior**
Borders are not removed

**Screenshots**
![image](https://user-images.githubusercontent.com/1211300/218407550-4334f125-c50e-45b1-8530-b09e7ce4d0f5.png)

**Desktop**
 - OS: Linux
 - Browser: Firefox
 - Version: 22.05.10.1

**Comment by gitgt** [comment]
I reproduce this but not always, there's some additional detail here.

**Comment by gitgt** [comment]
Actually, this is LibreOffice bug, regression in 7.4. Reported as TDF#153644 with offending commit. 
I'll close this one as it's Moved now. It's still tracked in Collabora T40584 until fixed in Online. 
https://bugs.documentfoundation.org/show_bug.cgi?id=153644
