### ISSUE TITLE
iOS app: the expand icon in the calc inputbar is displayed wrong after usage

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#585]
**Describe the bug**
After using the button to expand the inputbar into a multiline edit form in calc on iOS, the button will change into a blue square instead of showing the up/down arrow.

**To Reproduce**
1. Open a spreadsheet using the iOS app
2. Click on the button right next to the input bar (rectangle pointing down)

**Expected behavior**
The button should change and show a upwards pointing rectangle.

**Actual behavior**
The button becomes a blue square.

**Screenshots**
<img width="1112" alt="expand_symbol_broken_after_usage" src="https://user-images.githubusercontent.com/1211300/98675827-0fdbef00-235b-11eb-8c8b-dc64ce423eae.png">

**Tablet**
 - OS: iOS
 - Version: 6.4.0 (10)

**Comment by thebearon** [comment]
Confirmed with 6.4.0 (11). Possibly an iOS theming bug in core. @pedropintosilva?

**Comment by tml1024** [comment]
The Calc input bar is a tunneled dialog, and this is thus likely a complicated and hard to fix bug.

**Comment by tml1024** [comment]
Looking at this now, maybe it isn't complicated after all.

**Comment by tml1024** [comment]
The fun thing is that if you keep tapping the button, occasionally the blue square does not show up but you see the expander arrow (up or down). (But in those cases the action is not performed, the button just shows up correctly.) That probably is a sign of something, but don't know what yet.

https://user-images.githubusercontent.com/310731/133243544-476e1e77-7ebb-4f08-8008-16931c0164e5.mp4

**Comment by tml1024** [comment]
Debugging the JS to figure out what is going in. Code pointer: loleaflet/src/control/Control.LokDialog.js , _setupCalcInputBarGestures() might be related.

**Comment by tml1024** [comment]
The blue thing probably is a marker for a selection that is horribly wrongly positioned. Like the ones you get when select something inside the input bar. If you have the blue square showing up and tap inside the input bar, the blue square goes away. Interesting.

**Comment by nikslor** [comment]
FWIW: still present in 21.6.1 (1)

**Comment by nikslor** [comment]
Fixed in 22.05.10 (22.5.202302180032)
@plubius I'll also let you close this one, okay?

**Comment by plubius** [comment]
I'll let @tml1024 decide if it should be closed. I didn't change any iOS code for this bug so I assume that the fix was made in the Online or LibreOffice code.

**Comment by tml1024** [comment]
I trust @nikslor that the bug is gone.
