### ISSUE TITLE
Impress document with gradient shapes in won't render

### ISSUE THREAD

**Issue by plubius** [CollaboraOnline/online#5858]
When the [gradient.odp](https://github.com/CollaboraOnline/online/files/10745047/gradient.odp) file is opened in the iOS app, no document content is rendered. This document contains transparent shapes filled with gradients.

However, if you top the View > Presentation toolbar button, all content including the gradients do render.

**Comment by sebastiaanveld** [comment]
Issue is not specific to IOS, the document also does not render in CODE (Staging). Also here starting playing the presentation does show it's content.
COOLWSD version: 23.05.0.1 git hash: [https://github.com/CollaboraOnline/online/commit/d3518f7fe000984a72a9ef4b1cbaf188b973d23f]
LOKit version: built on Collabora Office 23.05.0.1 git hash: [ff9a1ba]
Served by: openSUSE Leap 15.3 [6e930f1a]

![image](https://user-images.githubusercontent.com/37268999/219947601-83fd91db-9ba9-4f7d-9339-cb6629d79f55.png)

**Comment by plubius** [comment]
@sebastiaanveld Thank you for testing this in Collabora Online. I think we can conclude that this is a bug in the Online code so I have removed iOS from the bug title and label. I am not familiar with the Online JavaScript code (I work mostly on macOS and a little iOS) so I think we'll have to wait for the Online group to take a look at this bug.

**Comment by thebearon** [comment]
The sample is saved in Outline view, and is opened as such not only in Collabora Online and the iOS app, but in Collabora Office/LibreOffice as well, except there the user is able to switch back to normal view.

The fix would be to show such presentations in normal view in online, and I believe the following patch from @hcvcastro would achieve that once merged:
https://gerrit.libreoffice.org/c/core/+/147095
(patch is for co-23.05, needs to be ported to co-22.05 after review+merge)

**Comment by plubius** [comment]
I cherry-picked @hvcastro's fix to the distro/collabora/co-22.05 branch in https://gerrit.libreoffice.org/c/core/+/147354. All works as intended so as soon as it is merged, I will include the fix in the next iOS app TestFlight build.

**Comment by plubius** [comment]
Closing as the fix is in the latest TestFlight release.
