### ISSUE TITLE
Typing on first line/new line is not working on firefox

### ISSUE THREAD

**Issue by elhananjair** [CollaboraOnline/online#5867]
**Describe the bug**
This is a problem am facing with Firefox, I create a new document and started writing something right away, unfortunately, it doesn't put the letter I type on the first line instead after I pressed space the words I type start to appear on the screen, check out the attached short video.

**To Reproduce**
1. Go to firefox 
2. Create a new document and start to type something as nextcloud office opens the document 
3. The first letter you type won't appear 

**Expected behavior**
As in other browsers, it should appear as you type any letter. 

**Actual behavior**
It skips the first letter I enter and shows the second or third letter I type. 

**Screenshots**

https://user-images.githubusercontent.com/69236638/219594715-29b69165-de06-4b21-a4d2-0c1964bcdeab.mp4

**Desktop (please complete the following information)**
 - OS: Fedora server
 - Browser Firefox
 - Version 109.0.1

**Additional context**

**Comment by gitgt** [comment]
Not reproducible for me with COOLWSD version: 23.05.0. Can you share Help-About? Can you try with new Firefox profile?

**Comment by elhananjair** [comment]
@gitgt I have just updated Firefox to version 110 and still facing the problem,  tried with new firefox profile to and still the problem there, but the COOLWSD version I am testing on is 22.05.10.1, isn't this the latest version?


https://user-images.githubusercontent.com/69236638/219648104-ce950489-744e-4b9f-ab9c-f963e48291d5.mp4

**Comment by elhananjair** [comment]
@gitgt my bad the problem was with the keyboard I was using, ibus-typing-booster.
