### ISSUE TITLE
Endless retry to refresh lock

### ISSUE THREAD

**Issue by juliushaertl** [CollaboraOnline/online#5870]
We just had a heavy request spam from our Collabora to the Nextcloud server which seemed to have been caused by attempts to refresh the lock while the WOPI token was no longer valid.

```
Feb 17 11:41:07 office1 coolwsd[675]: wsd-00675-606110 2023-02-17 11:41:07.116094 +0000 [ docbroker_09e ] ERR  Un-successful WOPI::Lock with status 403 and response: []| wsd/Storage.cpp:984
Feb 17 11:41:07 office1 coolwsd[675]: wsd-00675-606110 2023-02-17 11:41:07.116410 +0000 [ docbroker_09e ] ERR  Failed to refresh lock| wsd/DocumentBroker.cpp:1877
Feb 17 11:41:07 office1 coolwsd[675]: wsd-00675-606110 2023-02-17 11:41:07.175313 +0000 [ docbroker_09e ] ERR  Un-successful WOPI::Lock with status 403 and response: []| wsd/Storage.cpp:984
Feb 17 11:41:07 office1 coolwsd[675]: wsd-00675-606110 2023-02-17 11:41:07.175671 +0000 [ docbroker_09e ] ERR  Failed to refresh lock| wsd/DocumentBroker.cpp:1877
```

The Nextcloud server responded with a 403 but it seems that Collabora just keeps retrying to refresh the lock.

From a quick look at the `DocumentBroker::refreshLock` it seems that the error there is logged but not further passed, so `DocumentBroker::pollThread` would just continue and on the next iteration trigger the lock refresh again.

https://github.com/CollaboraOnline/online/blob/1da8d6dd24bf747295c387aa1ca49f1ac18260d4/wsd/DocumentBroker.cpp#L351-L352

https://github.com/CollaboraOnline/online/blob/1da8d6dd24bf747295c387aa1ca49f1ac18260d4/wsd/DocumentBroker.cpp#L1811-L1815

Version in use:

<div id="about-dialog-info">
            <div id="coolwsd-version-label">COOLWSD version:</div>
            <div style="margin-inline-end: auto;"><div id="coolwsd-version" dir="ltr">21.11.8.3 <span>git hash:&nbsp;<a href="javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/914bfd2'));">914bfd2</a></span></div></div>
            <div class="spacer"></div>
            <div id="lokit-version-label">LOKit version:</div>
            <div style="margin-inline-end: auto;"><div id="lokit-version" dir="ltr">Collabora Office 21.06.35.2<span> git hash:&nbsp;<a href="javascript:void(window.open('https://hub.libreoffice.org/git-core/76e5d30'));">76e5d30</a><span></span></span></div></div>
            <div id="served-by"><span id="served-by-label">Served by:</span>&nbsp;<span id="os-info">Ubuntu 22.04.1 LTS</span>&nbsp;<wbr><span id="coolwsd-id"><a target="_blank" href="https://collabora.nextcloud.com/hosting/discovery">7220169b</a></span></div>
            <div id="slow-proxy"></div>
            <p style="margin-inline-end: auto;"><span dir="ltr">Copyright © 2022, Collabora Productivity Limited.</span></p>
          </div>

**Comment by Ashod** [comment]
Thanks for reporting this, @juliushaertl.

_Is it safe to assume the 403 return means the token in question is expired?_

We do not use expired tokens to refresh the lock or upload the document. We interpret 401, 403, and 404 from _PutFile_ to mean the token is expired, and we stop using it from then on.

It seems the issue here is that we never expected/supported getting 401/3/4 from a lock request. If you confirm my assumption, then it's straightforward fix.

Thanks.

**Comment by juliushaertl** [comment]
> Is it safe to assume the 403 return means the token in question is expired?

Currently we return 403 but looking at the WOPI spec it should rather be 401 from https://learn.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/rest/files/refreshlock, so best might be to handle both.

> We do not use expired tokens to refresh the lock or upload the document. We interpret 401, 403, and 404 from PutFile to mean the token is expired, and we stop using it from then on.

I would assume it may have happened that on put file the token was still valid but once the RefreshLock request was made the token was then expired.

From Nextclouds perspective the 403/401 could happen on any WOPI request as authentication with the access token is handled globally by a middleware that would just always return those status codes if the token is invalid/expired.

**Comment by Ashod** [comment]
> I would assume it may have happened that on put file the token was still valid but once the RefreshLock request was made the token was then expired.

Right, that's my assumption as well.

> From Nextclouds perspective the 403/401 could happen on any WOPI request as authentication with the access token is handled globally by a middleware that would just always return those status codes if the token is invalid/expired.

We now handle 401/403/404 to mean 'token expired'.

Thank you.

**Comment by juliushaertl** [comment]
Thanks as well for the quick fix.
