### ISSUE TITLE
Wrong column width after save .xlsx file

### ISSUE THREAD

**Issue by JohnRock0422** [CollaboraOnline/online#5880]
(Tested on nextcloud)
Create a new Spreadsheet with specifying .xlsx file extension. (Or Import a .xlsx file into spreadsheet editor)
Make some change on the document (such as input "A" in A1 cell). 
Save and Reopen the document.
All the columns width may be different than before. (May become bigger or smaller)

![column-width](https://user-images.githubusercontent.com/26728661/220256142-321fe7a4-2a42-4d9c-9444-1b626bbf4a7b.png)

PS: Tested on .ods file, seems no such problem.

**Comment by gitgt** [comment]
Yes. I reproduce with Staging 23.05.0.1. Not with LO 7.6+. Should be also tested in older and core versions.

**Comment by eszkadev** [comment]
When I created new file it had columns with size: 0.89, after every save it was decreasing and after many times I got 0.83 in all columns.
But I needed to repeat the process many times.

**Comment by eszkadev** [comment]
patch merged to core: https://gerrit.libreoffice.org/c/core/+/156576

**Comment by timur-g** [comment]
Fixed in 23.05.4. Also will be backported to 22.05. @JohnRock0422 thanks for reporting.
