### ISSUE TITLE
iOS app: switching from compact view to tab view sets the font name combobox to "Carlito" 

### ISSUE THREAD

**Issue by plubius** [CollaboraOnline/online#5886]
Steps to reproduce:

1. Open a Writer document and put the cursor in some text. The font name combobox will be set to the font of the text at the cursor as expected.
2. Switch to Compact view by tapping View > Compact view
3. Switch back to Tabbed view by tapping View > Use Tabbed view

Result: the cursor has not moved but the font name combobox will be set to "Carlito".

Expected result: the font name should not change.

**Comment by Darshan-upadhyay1110** [comment]
Works fine in latest version 
COOLWSD version: 24.04.6.2 (git hash: 7bb21429)
LOKit version: Collabora OfficeDev 24.04.6.2 (git hash: 321166f)
Served by: Ubuntu 23.10
Server ID: 9fd431d3
