### ISSUE TITLE
Impress : Wrong text color in presenting

### ISSUE THREAD

**Issue by JohnRock0422** [CollaboraOnline/online#5891]
The white text is shown in black while presenting.
Seems the problem relates to the Autofit Text option (which available in LibreOffice desktop version, but seems not available in Collabora Online)
![AutofitText-in-presenting](https://user-images.githubusercontent.com/26728661/220866189-f431ca7b-ef26-4afa-91eb-2900ecede619.png)

Can be repeated on attached .odp file
[AutofitText.odp](https://github.com/CollaboraOnline/online/files/10811977/AutofitText.odp)

PS:
The problem happens on page-3
Seems cannot repeat the problem, if deleted page-1, or deleted page-2, or moving page-3 to be 2nd page.

**Comment by Ezinnem** [comment]
I tested with the sample file, the text appeared in during presentation.

Please can you provide more specific steps to reproducing this issue @JohnRock0422

**Comment by Ezinnem** [comment]
I am closing this issue because the issue does not seem reproducible and there is no response from the author.
