### ISSUE TITLE
Impress: Font may be missing in slideshow

### ISSUE THREAD

**Issue by JohnRock0422** [CollaboraOnline/online#5899]
Font may be missing in slideshow
![MissingFont](https://user-images.githubusercontent.com/26728661/221086479-8e5b2f36-97ba-4a1f-adf8-fd8b77a290b1.png)

**Comment by Ezinnem** [comment]
@JohnRock0422 

Please can you attach a sample file?

**Comment by Ezinnem** [comment]
Closing this issue as there is no response from the author.

**Comment by JohnRock0422** [comment]
Sorry for late reply
here is a sample
https://github.com/CollaboraOnline/online/files/11464587/OSWALD.TEST.odp
