### ISSUE TITLE
Collabora Online's "Add Citation" Zotero-Dialog wrongly displays the author's name as "undefined undefined" if it only consists of one element  

### ISSUE THREAD

**Issue by SustReal** [CollaboraOnline/online#5902]
**Describe the bug**
The Zotero library offers two ways of entering the name of an author: First & Last Name – or as a single Word via a switch in Zotero (see screen below). Although Collabora Online seems to be handling these entrys well in the actual citation footnote or the bibliography, the citation dialog displays the single fielded athor entries as "undefined, undefined)

I've attached the problematic document (Which had been created or worked on in an offline version of LibreOffice). I'm also sharing my Zotero API Key here: 11070520

**To Reproduce**
1. Go to 'References'
2. Click on 'Add Citation'
3. See "undefined undefined" output for single fielded author entries

**Expected behavior**
The dialog should display the author's name as in the zotero library 

**Actual behavior**
Instead of the author's name, the dialog displays "undefined, undefined" as a first & last name of the entry

**Screenshots**
![grafik](https://user-images.githubusercontent.com/51329893/221181373-1a91f884-69a9-4077-94f4-f48fa112e03c.png)
_"undefined undefined" output in Collabora Online's citation dialog_

![grafik](https://user-images.githubusercontent.com/51329893/221181882-eaa743c7-e46b-4182-961e-5591e0dd1777.png)
_Single field author entry in Zotaro_

**Desktop (please complete the following information)**
- OS: Ubuntu 22.04.1 LTS
- Browser: Firefox
- Version: Collabora 22.05.10 (23.05.0.1)

**Smartphone (please complete the following information)**
 - 

**Additional context**
- 

[Quotations_Wikipedia_Zotero_DejaVu.odt](https://github.com/CollaboraOnline/online/files/10824235/Quotations_Wikipedia_Zotero_DejaVu.odt)

**Comment by Ezinnem** [comment]
Retest using:
COOLWSD version: 24.04.6.2 (git hash: [4fd2181](https://github.com/CollaboraOnline/online/commits/4fd2181) (E))
LOKit version: Collabora Office 24.04.6.2 (git hash: [47680e0](https://git.libreoffice.org/core/+log/47680e0))


![image](https://github.com/user-attachments/assets/5b298432-a4bc-40de-a852-053119a7148b)


It seems resolved now.

@SustReal please can you retest and add a comment if it still occurs at your end?
