### ISSUE TITLE
Convert-to from pdf to txt fails: cmd=saveas kind=savefailed

### ISSUE THREAD

**Issue by UltimateByte** [CollaboraOnline/online#5924]
**Describe the bug**
Even though txt or .doc to .pdf conversion works as expected, .pdf to .txt appears to always fail.

**To Reproduce**
1. Get a pdf on your coolwsd server like: `wget https://sdk.collaboraonline.com/CO-SDK-manual.pdf`
2. Run a conversion like `curl -F "data=@CO-SDK-manual.pdf" http://localhost:9980/cool/convert-to/txt > out.txt`

**Expected behavior**
Curl should output the resulting .txt file.

**Actual behavior**
1. Curl is slowing down upload speed more and more as the upload goes
2. Result is either a timeout or an empty reply.
3. Logs show:
```
wsd-78682-78682 2023-02-28 16:29:41.127368 +0100 [ coolwsd ] INF  WSD initialization complete: setting log-level to kit-78692-78690 2023-02-28 16:29:51.881421 +0100 [ kitbroker_001 ] ERR  ToMaster-001: error: cmd=saveas kind=savefailed| common/Session.hpp:165
kit-78715-78690 2023-02-28 16:35:29.771886 +0100 [ kitbroker_002 ] ERR  ToMaster-002: error: cmd=saveas kind=savefailed| common/Session.hpp:165
```

**Server Info**
 - OS: Debian 11.6
 - Coolwsd: coolwsd/unknown,now 22.05.10.2-1 amd64 [installed]

**Additional details**
Config file sets max_file_size to 0 (unlimited), and my test PDF is around 2.4MB.

I remain available for further details or testing.

**Comment by gitgt** [comment]
I tested and reproduced but not sure if it is really expected to convert from PDF, in COOL PDF cannot be saved to other format.

**Comment by UltimateByte** [comment]
If the feature is missing, it would be a useful addition.
Shall the feature not be added, it would be good to have a more explicit error message.

As a workaround, I use the poppler-utils (linux package) for now for this purpose.

**Comment by timar** [comment]
As a matter of fact, Collabora Online 25.04 can convert PDF to txt, odt, png, and txt. At least these formats worked for me. (Just in case someone finds this error report in a Google search, as I did.)
