### ISSUE TITLE
iOS app: after tapping into input bar, vertical alignment not centered anymore

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#594]
**Describe the bug**
When tapping into the input bar in calc, the vertical alignment will be lost and some elements "jump up".

**To Reproduce**
1. Open a spreasheet in the iOS app
2. Tap into the input bar

**Expected behavior**
The vertical alignment of all elements should be kept.

**Actual behavior**
Some elements "jump up", notably the red cross, the green checkmark and the input bar.

**Screenshots**
This demonstrates before tapping into the input bar and after:
<img width="1112" alt="input_bar_not_centered" src="https://user-images.githubusercontent.com/1211300/98701320-6fe18e00-2379-11eb-9ae1-bb6ef991321b.png">

**Tablet**
 - OS: iOS
 - Version: 6.4.0 (10)

**Comment by thebearon** [comment]
I noticed that as well. Must be that oversized dropdown not taking up the space anymore that messes things up.

**Comment by nikslor** [comment]
Fixed in 22.05.10 (22.5.202302180032)
@plubius I'll also let you close this one, okay?

**Comment by plubius** [comment]
I'll let @tml1024 decide if it should be closed. I didn't change an iOS code for this bug so I assume that the fix was made in the Online or LibreOffice code.

**Comment by tml1024** [comment]
I trust @nikslor that the bug is gone.
