### ISSUE TITLE
Dialog canvas not refreshed/repainted

### ISSUE THREAD

**Issue by HolgerHees** [CollaboraOnline/online#5944]
First I was thinking that clicks inside a dialog are not working.

- I was not able to scroll some areas and select some values. e.g. in calc, I was able to choose the category in cell formating, but only some formats are clickable/selectable

- In writer / page template, I was not able to select following template.

But after a while, I realized that it must be related to not refreshed/repainted canvas views.

e.g. If I choose "following template", nothing happens. But if I open the selectbox a second time. The right value was selected. Also if I switch to a different browser tab and back. The right value was displayed. Also if I changed the tab inside the dialog and was switching back, the right value was displayed.

everywhere in dialogs where I had similar symthoms, It was always related to a not repainted canvas dialog.

My setup is richdocuments version 7.1.1,  nextcloud version 25.0.4 and collabora docker container in version 22.05.10.8.1.

I tested it in firefox version 110.0 and chrome version 110.0.5481.177

My OS is openSUSE Leap 15.4.

any Idea how can I debug it more. Could it be somehow related to my graphic driver?

---- UPDATE ----

I tested it also in Edge Browser in Windows 10 running on VirtualBox with the same behavior. So it seams not related to my graphics driver.

---- HOW to reproduce ----
1. Create a new odt document in nextcloud
2. This opens the collabora editor
3. Click on Layout / Sitetemplate (Tabbed Menu)
4. Change "follow-up template" (Folgevorlage in german) from standard to enything else
5. This closes the selectbox
6. But There is still "standard" visible until 
  6.1. I switch to a different tab and back
  6.2  or I choose the selectbox again. Then I see that the new value was selected
  6.3  or If my cursor is moved outside the canvas area / dialog, a second later it is updated too.

This is just an example. The behavior happens on a lot of canvas based dialogs.

The problem with the non clickable values in formatting cells in calc, behaves differently. It is not refreshed when my mouse cursor leave the canvas area immediately. Currently I have not observed an exact behavior. If my cursor moves around, between 5 and 15 seconds later this value is selected and updated.

**Comment by Ezinnem** [comment]
I can confirm this experience on my end.

COOLWSD version:
22.05.11.0 git hash: [e0e7e9cd](https://github.com/CollaboraOnline/online/commits/e0e7e9cd)

**Comment by HolgerHees** [comment]
it is fixed in version 22.05.12.1.1

in the release notes I see just Bugfixes, but no link to more details. It would be interesting to know which commit was fixing it.

**Comment by HolgerHees** [comment]
Version 22.05.12.2.1 reduced the drawing issues again a bit => the bold lines glitches are only in the first 15 lines 

![grafik](https://user-images.githubusercontent.com/5681988/226295018-00e024e4-a465-4971-bed6-ade687fbf3c7.png)
