### ISSUE TITLE
Hide_Menu_Item and Hide_Button not working

### ISSUE THREAD

**Issue by ErikDW1** [CollaboraOnline/online#5957]
Hello I’m trying to hide some menu options by using the PostMessage API, however nothing seems to work.

I’m sending these messages right after receving the “App_LoadingStatus” “Document_Loaded” feedback:
{“MessageId”:“Hide_Menu_Item”,“SendTime”:1677600490227,“Values”:{“id”:“help”}}
{“MessageId”:“Hide_Menu_Item”,“SendTime”:1677600490227,“Values”:{“id”:“file”}}

Also I made a JS function called by a button as in the https://github.com/CollaboraOnline/online/tree/629b25b27a299ae5eea182e5e58a89a10678c680/browser/html/framed.doc.html, but it's not working too.
If I call the "Hide_Menubar" and the "Action_Save" action these work seamlessly.

The version I'm working with is the latest COOLWSD version: 22.05.10.8 [ef89c82]

**Comment by ErikDW1** [comment]
I want also to add that an optimal way of handling UI customization would be through the "CheckFileInfo" response properties, as it is for Save and Print options.
This way we can have the ability to customize the UI according to the users' capabilities on our hosting platform (ex. I might want to display an user just the Review controls and nothing else, since it has the role "Reviewer" on my hosting platform).

**Comment by nadirlouati** [comment]
yes i confirm your diagnosis

Override CheckFileInfo is only for DownloadAsPostMessage propertery for now
https://sdk.collaboraonline.com/docs/advanced_integration.html#override-checkfileinfo

**Comment by robmv** [comment]
I can confirm this problem. Even if the user has switched to the compact view, the button is hidden, but if the user switch to the notebook mode and reverts back to compact, the button is again visible.

As @ErikDW1 said, I wish too UI customization could be done at CheckFileInfo time, even locking UNO actions, these can only be done currently by host for example, not based on the specific user requesting the editing.

**Comment by useresd** [comment]
I confirm this bug. The tabbed view UI is not affected by the postMessage API for Hide_Menu_Item

**Comment by dan-aridhia** [comment]
I can confirm this is also in 23.05.4.

**Comment by hfiguiere** [comment]
I file #7517 recently.

**Comment by nadirlouati** [comment]
any news ?
