### ISSUE TITLE
iOS App: Saving not working

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#5960]
**Describe the bug**
Saving a document (tested writer and calc) doesn't work with 22.05.10 (22.5.202303070027) - the error message I get is:
"The server encountered a savefailed error while parsing the save command."

**To Reproduce**
1. Open a document in the current test flight version 22.05.10 (22.5.202303070027)
2. Change the content
3. Tap on the "Save" icon in the top-toolbar

**Expected behavior**
The document should be saved.

**Actual behavior**
An error is shown and the document is not being saved.

**Screenshots**
Can provide one if needed - but I guess it doesn't help a lot to screenshot the error message.

**Tablet**
 - Device: IPad
 - OS: IPadOS 15.6.1
 - Version: 22.05.10 (22.5.202303070027)

**Comment by plubius** [comment]
Not sure why I was assigned this bug. Is there some new data that I don't know about?

Look, I am just a retired guy working to see if I can iron out any native iOS bugs. I work a little bit here and there as this project competes with my volunteer macOS work at LibreOffice and my other retirement hobbies. So assigning everything that is seen on iOS to me won't speed up fixing these bug. In fact, it will likely slow it down as it will get likely get filtered out by many of JavaScript developers.

I am happy to take a look at the native iOS code if the JavaScript developers notice a bug only on iOS, but you got to give me some data to work with. Debugging anything on iOS is painfully slow. It usually takes several minutes to compile and launch the app after each change. And if I touch any JavaScript code, the time is double and I can only debug with the compressed bundle.js. Hence my reluctance to work on the JavaScript code.

**Comment by nikslor** [comment]
Sorry, my bad. Let me remove the assignment.

**Comment by thebearon** [comment]
This seems to be the same as #5887.
