### ISSUE TITLE
IOS App: Spell Check does not allow to select a suggested word from the list in the suggestion box

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#5999]
**Describe the bug**
IOS App: Spell Check does not allow to select a suggested word from the list in the suggestion box

**To Reproduce**
1. Collabora Office App
2. Open and new or existing document
3. Type a sentence and a wrong word in there
4. Click on Spell Check button
5. Try to select a word as listed in the suggestion box, this is not possible 

**Expected behavior**
It should be possible to select a word from the suggestion box

**Actual behavior**
Selecting a word in the suggestion box does not function and the up-down slider does not seem to work either

**Screenshots**

![image](https://user-images.githubusercontent.com/37268999/224556301-3b9acd6c-318f-4eeb-9fd1-627cc2113d37.png)

**Smartphone (please complete the following information)**
iPadOS 16.3.1 on iPad 5th gen (model MP2G2NF/A), language set to Dutch Localization
Collabora Office 22.05.10 (22.5.202303070027) in Testflight

**Comment by plubius** [comment]
I cannot reproduce this with my latest build so I have a feeling (hoping) that this bug is another symptom of issue #5887.

**Comment by sebastiaanveld** [comment]
Ok, lets test it again in the next build.

**Comment by plubius** [comment]
I just encountered a related bug. After pressing the "Correct" button in the Spellcheck dialog, the app will sometimes crash when pressing the dialog's "Close" button.

The stack below indicates it is in the LIbreOffice code. It appears to me that one of the dialog's C++ children has been deleted out from underneath the dialog:

#0	0x0000000108f5253c in SwSpellDialogChildWindow::LockFocusNotification(bool) at /Volumes/LOBuilds/lode/dev/ios-co-22.05.10-6/sw/source/uibase/dialog/SwSpellDialogChildWindow.cxx:824
#1	0x0000000108f51648 in SwSpellDialogChildWindow::GetNextWrongSentence(bool) at /Volumes/LOBuilds/lode/dev/ios-co-22.05.10-6/sw/source/uibase/dialog/SwSpellDialogChildWindow.cxx:415
#2	0x000000010160ec04 in svx::SpellDialog::GetNextSentence_Impl(std::__1::unique_ptr<UndoChangeGroupGuard, std::__1::default_delete<UndoChangeGroupGuard> >*, bool, bool) at /Volumes/LOBuilds/lode/dev/ios-co-22.05.10-6/cui/source/dialogs/SpellDialog.cxx:1003
#3	0x000000010160dc6c in svx::SpellDialog::SpellContinue_Impl(std::__1::unique_ptr<UndoChangeGroupGuard, std::__1::default_delete<UndoChangeGroupGuard> >*, bool, bool) at /Volumes/LOBuilds/lode/dev/ios-co-22.05.10-6/cui/source/dialogs/SpellDialog.cxx:363
#4	0x000000010161022c in svx::SpellDialog::ChangeHdl(weld::Button&) at /Volumes/LOBuilds/lode/dev/ios-co-22.05.10-6/cui/source/dialogs/SpellDialog.cxx:553
#5	0x000000010160c244 in svx::SpellDialog::LinkStubChangeHdl(void*, weld::Button&) at /Volumes/LOBuilds/lode/dev/ios-co-22.05.10-6/cui/source/dialogs/SpellDialog.cxx:542
#6	0x000000010a9982e0 in Link<weld::Button&, void>::Call(weld::Button&) const at /Volumes/LOBuilds/lode/dev/ios-co-22.05.10-6/include/tools/link.hxx:111
#7	0x000000010ac480b8 in weld::Button::signal_clicked() at /Volumes/LOBuilds/lode/dev/ios-co-22.05.10-6/include/vcl/weld.hxx:1431
#8	0x000000010a8c7940 in SalInstanceButton::ClickHdl(Button*) at /Volumes/LOBuilds/lode/dev/ios-co-22.05.10-6/vcl/source/app/salvtables.cxx:2701
#9	0x000000010a8c6df0 in SalInstanceButton::LinkStubClickHdl(void*, Button*) at /Volumes/LOBuilds/lode/dev/ios-co-22.05.10-6/vcl/source/app/salvtables.cxx:2689
#10	0x000000010a312714 in Link<Button*, void>::Call(Button*) const at /Volumes/LOBuilds/lode/dev/ios-co-22.05.10-6/include/tools/link.hxx:111
#11	0x000000010a3126c8 in Button::Click()::$_0::operator()() const at /Volumes/LOBuilds/lode/dev/ios-co-22.05.10-6/vcl/source/control/button.cxx:130
#12	0x000000010a312684 in decltype(static_cast<Button::Click()::$_0&>(fp)()) std::__1::__invoke<Button::Click()::$_0&>(Button::Click()::$_0&) at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/c++/v1/type_traits:3918
#13	0x000000010a31263c in void std::__1::__invoke_void_return_wrapper<void, true>::__call<Button::Click()::$_0&>(Button::Click()::$_0&) at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/c++/v1/__functional/invoke.h:61
#14	0x000000010a312614 in std::__1::__function::__alloc_func<Button::Click()::$_0, std::__1::allocator<Button::Click()::$_0>, void ()>::operator()() at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/c++/v1/__functional/function.h:178
#15	0x000000010a310f60 in std::__1::__function::__func<Button::Click()::$_0, std::__1::allocator<Button::Click()::$_0>, void ()>::operator()() at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/c++/v1/__functional/function.h:352
#16	0x00000001006e63a0 in std::__1::__function::__value_func<void ()>::operator()() const at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/c++/v1/__functional/function.h:505
#17	0x00000001006cdb14 in std::__1::function<void ()>::operator()() const at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/c++/v1/__functional/function.h:1182
#18	0x000000010a3391e8 in Control::ImplCallEventListenersAndHandler(VclEventId, std::__1::function<void ()> const&) at /Volumes/LOBuilds/lode/dev/ios-co-22.05.10-6/vcl/source/control/ctrl.cxx:313
#19	0x000000010a2f8e54 in Button::Click() at /Volumes/LOBuilds/lode/dev/ios-co-22.05.10-6/vcl/source/control/button.cxx:130

**Comment by sebastiaanveld** [comment]
Did some more testing as to your findings, issue is that highlighting the selection seems not to work, but in the background the word is selected anyway.

Steps to reproduce the behavior:
- Collabora Office App
- Open and new or existing document
- Type a sentence and a wrong word in there
- Click on Spell Check button
- Try to select a word as listed in the suggestion box, this is not possible as the selected word from the list does not get highlighted
- But if you now click the Correct button
- Then click the Close button, the adjustment is made correctly anyway

**Comment by sebastiaanveld** [comment]
I have the same behavior in the Thesaurus Alternatives dialog. Also here words cannot be selected, they do not highlight, but when clicking Replace button the selected Alternative is applied anyway.

**Comment by plubius** [comment]
The fix for this bug is now in the latest TestFlight build. Please close if the bug is fixed for you.

BTW, I created issue #6010 for the crash when closing the Spellcheck dialog.

**Comment by sebastiaanveld** [comment]
Works for me in Collabora Office 22.05.10 (22.5.202303132008) in Testflight

Thx!
