### ISSUE TITLE
Search (Ctrl+F) Does not work in cheets (excel docs)

### ISSUE THREAD

**Issue by Eugene7219** [CollaboraOnline/online#6013]
------------------------
Search (Ctrl+F) Does not work in cheets (excel docs). In read-only and full access

**To Reproduce**
1. Export any sheet (excel or ods) file
2. Share as link
3. Make shared file file read only (full access not work too)
4. Open as other user with read only-access
5. Try to do search in document (for example press Ctrl+f)
6. Not work

**Expected behavior**
Must open window for entering text for search

**Actual behavior**
nothing happens

**Screenshots**
no need

**Desktop (please complete the following information)**
 - OS: Linux and Windows
 - Browser: Chrome, Firefox
 - Version: 22.05.10.8

**Smartphone (please complete the following information)**
 not tested

**Additional context**
none

**Comment by Ezinnem** [comment]
I am not able to reproduce this issue on my reproduce this issue described.
CTRL+F works in sheets as expected.

Please can you test again using an updated version? Send us a recording showing the issue if it persists in the newer version.
