### ISSUE TITLE
Collabora problem with NextCloud

### ISSUE THREAD

**Issue by MERP-Solutions** [CollaboraOnline/online#6038]
We have a nextcloud running which works perfect. We are trying to open documents and this does not work.

**To Reproduce**
1. Install Nextcloud through snap
2. Add Nextcloud office with collabora
3. Use the "built in " server

**Expected behavior**
Open documents without problems.

**Actual behavior**
No documents can't be opened.

**Screenshots**
The error we get in the browser:
`{
  "message": "Network Error",
  "name": "AxiosError",
  "code": "ERR_NETWORK",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {
      "FormData": null
    },
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "requesttoken": "vQJzhoGtT1zVrIVSFyP0y7MjKH4Qg43frvD5G13XP5M=:iFUl8OjZNiyd1sZnXkTDv8ZFXSdf7t3p7KTPdDiRc7g="
    },
    "method": "get",
    "url": "http://cloud.tectonic-3d.com/extra-apps/richdocumentscode/proxy.php?status"
  },
  "request": {},
  "response": {}
}`

**Desktop (please complete the following information)**
 - OS: Ubuntu 22.04
 - Browser: Edge, Safari, Chrome, FireFox
 - Version: 22.5.802

**Comment by Ezinnem** [comment]
To use the option, "Use the built-in CODE" server, you may need to install the Collabora Online Built-in CODE server from the Profile > apps > Office & text option.
 
 @MERP-Solutions, please can you try that and see if that helps.

**Comment by MERP-Solutions** [comment]
@Ezinnem Thanks for your response. I tried that. It says it works when I click it again after saving and going back (read somewhere on google this sometimes wasn't the case).  We are trying to use the built in server, which is already installed.

**Comment by gitgt** [comment]
So, is this resolved?

**Comment by MERP-Solutions** [comment]
Sadly it is not. I have tried a lot of things, but it just doesn't seem to work.

**Comment by gitgt** [comment]
Good that it's solved. I guess we can close now.
