### ISSUE TITLE
1 character left of the cursor is deleted editing a text document

### ISSUE THREAD

**Issue by ferdiga** [CollaboraOnline/online#6040]
**Describe the bug**
1 character left of the cursor is sometimes deleted.
"sometimes" means, that at the beginning of editing (new or open existing) it usually does not happen, but once it happens, it happens always.
closing and reopening the document seems to solve the problem for a while.

**To Reproduce**
1. Open a docx document
2. place the cursor somewhere in the text
3. start typing
4. at least one "character" left of the cursor is deleted - like using a manual backspace delete

**Expected behavior**
Characters must not deleted 

**Actual behavior**
see "to reproduce"

**Screenshots**

**Desktop (please complete the following information)**
 - OS: iOS 13.2.1
 - Browser: brave 
 - Version: v1.49.120 (Mar 9, 2023)

**Additional context**
this behaviour is not new

**Comment by plubius** [comment]
It may not be related, but this sounds very similar to what happens after you enter an emoji character:

https://github.com/CollaboraOnline/online/issues/5837#issuecomment-1466844418

**Comment by ferdiga** [comment]
FYI - I am using UTF-8 (German keyboard, english, german and french text - no emoji) and very often bullet point lists.

**Comment by ferdiga** [comment]
similar in collabora sheets:
- open a cell to edit 
- do NOT close it
- go to another app (to copy a text)
- go back to the open edit of the cell to paste the text
- characters are deleted

**Comment by juliushaertl** [comment]
I can also reproduce this issue with Safari on macOS. Other browsers don't show this behaviour, so maybe it is related to WebKit since as far as I remember brave or chrome also only use WKWebView on iOS due to apple restrictions.

I often have this when typing bullet lists, pasting a link at the end and then pressing enter. Typing a space character after pasting will work as expected.

**Comment by thebearon** [comment]
@ferdiga Can you please check if this bug is still reproducible for you?

**Comment by ferdiga** [comment]
No, works fine now
