### ISSUE TITLE
Remove unused requestloksession

### ISSUE THREAD

**Issue by Ashod** [CollaboraOnline/online#6048]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @Ashod

### Detailed description and rationale
The protocol provisioned a command, called `requestloksession`, to "requests the initialization of a LOK process in an attempt to predict the user's interaction with the document". This command _seems_ to have been provisioned for unloading a document in the background and leaving a client-side-only view of the document until the user starts editing the document.

Unfortunately, this command doesn't seem to be used and, anyway, we do load the document in question upon connecting to coolwsd. Therefore, it seems noisy to have this command in the code.

### Code pointers
requestloksession in protocol.txt, Permission.js, CanvasTileLayer.js, ChildSession.cpp, ClientSession.cpp.

### Links to related documentation
protocol.txt

### Additional notes, tips & tricks
There seems to be empty handlers in both ChildSession.cpp and ClientSession.cpp that explicitly ignore this command.

**Comment by aegisxxx** [comment]
I have a pull request to resolve this issue #6049 
Feedback is appreciated.
Thank you.
