### ISSUE TITLE
UX Improvement: Review > Manage

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#6062]
**Describe the bug**

The dialog that shows changes that can be accepted/rejected doesn't look as nice as it should.

The following things should be discussed and eventually get improved:
- [ ] scrolling to the right, leads to an overlap
- [ ] borders thickness and missing border line
- [ ] "Help" button doesn't work

See below for screenshots:

### Before scrolling to the right
![image](https://user-images.githubusercontent.com/1211300/226572431-d8d4c2b2-36e2-4b8c-ab5f-b38cf669fc3b.png)

### After scrolling to the right
![image](https://user-images.githubusercontent.com/1211300/226572360-20beed31-2533-43c0-b5a0-480dc4111952.png)

### Missing border line

![image](https://user-images.githubusercontent.com/1211300/226572723-a0ea1458-fc49-468f-bf35-23a9c5d28b71.png)

### Border thickness

Green = good (thin)
Red = not good (thick)

![image](https://user-images.githubusercontent.com/1211300/226573185-ed64f941-e375-43ef-9a6a-62bf16cb0e1c.png)

## "Help" button doesn't work

![image](https://user-images.githubusercontent.com/1211300/226573601-66eb9069-5fb8-4f62-89d9-4aba165fb493.png)

**Comment by pedropintosilva** [comment]
Thanks @nikslor 

- I think those problems should be fixed (if not all at least easy to fix) once we convert that to jsdialog 
- Help button: We do have some bug around help buttons but (and without any additional PR) I just tested help button from master branch and it seems to work

**Comment by nikslor** [comment]
Still an issue in 23.05, so setting the label here

**Comment by Darshan-upadhyay1110** [comment]
Converted to jsDialog. Looks okay now
