### ISSUE TITLE
Copying formulas to adjacent cells using the fill handle does not work

### ISSUE THREAD

**Issue by MagsMagnoli** [CollaboraOnline/online#6065]
**Describe the bug**
Formulas are unable to be extended to other cells using the click and drag technique on the cell that contains the formula

**To Reproduce**
1. Add a formula to a cell
2. Click and drag down

**Expected behavior**
The selection stays within the column and on release applies the formula to all selected columns with the input values adjusted to the cells

**Actual behavior**
The selection expands to other columns and does nothing

**Screenshots**
https://user-images.githubusercontent.com/4146037/226622131-9ad4721b-6242-4779-bd1c-23c6b5bfc7db.mov

**Desktop (please complete the following information)**
 - OS: MacOS
 - Browser: Firefox
 - Version: 22.05.10.8

**Comment by Ezinnem** [comment]
This issue does not seem reproducible on my end.

@MagsMagnoli , please can you test again with an updated version?

**Comment by Ezinnem** [comment]
Closing this issue as it does not seem reproducible on my end. Also, there is no response from the author.
