### ISSUE TITLE
Error when I try to open doc from Nextcloud: Invalid or unknown request.| wsd/COOLWSD.cpp:3958

### ISSUE THREAD

**Issue by Iwios** [CollaboraOnline/online#6085]
Hello Collabora Team :)

**Describe the bug**
When I try to open a doc from enxtcloud, I have this error message:

coolwsd[1832]: wsd-01832-02081 2023-03-23 10:14:48.440393 +0100 [ websrv_poll ] ERR  #26: #26 bad request: [GET /cool/https%3A%2F%2Fmycloud.fr%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F3490_oc3xkqjqis6w%3Faccess_token%/ws?WOPISrc=https%3A%2F%2Fmycloud.fr%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F3490_oc3xkqjqis6w&compat=/ws HTTP/1.0#015...]: Invalid or unknown request.| wsd/COOLWSD.cpp:3958

**Desktop (please complete the following information)**
 - Browser: Firefox

**Additional context**
This configuration work fine since server reboot

**Other Info:**
I have a complex infra.
My collabora is a VM, behind 2 reverseproxy Nginx
Each Reversproxy work with HTTPS, only VM with CODE are in HTTP.

**Comment by Iwios** [comment]
When I open the debug console on firefox I have an error 400 with this url:

wss://collabora.mycloud.fr/cool/https%3A%2F%2Fmycloud.fr%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F3490_oc3xkqjqis6w%3Faccess_token%3D0rhhGcGBWKLjThegg%26access_token_ttl%3D1670%26permission%3Dedit/ws?WOPISrc=https://mycloud.fr/index.php/apps/richdocuments/wopi/files/3490_oc3xkqjqis6w&compat=/ws

**Comment by gruenerstein** [comment]
> When I open the debug console on firefox I have an error 400 with this url:
> 
> wss://collabora.mycloud.fr/cool/https%3A%2F%2Fmycloud.fr%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F3490_oc3xkqjqis6w%3Faccess_token%3D0rhhGcGBWKLjThegg%26access_token_ttl%3D1670%26permission%3Dedit/ws?WOPISrc=https://mycloud.fr/index.php/apps/richdocuments/wopi/files/3490_oc3xkqjqis6w&compat=/ws

Are you sure that your Reverse Proxy are able to handle Websocket connections ?

**Comment by thebearon** [comment]
What is your reverse proxy setup like? You say:
> Each Reversproxy work with HTTPS, only VM with CODE are in HTTP.

This requires a terminating reverse proxy setup, but I see no mention of that.

**Comment by thebearon** [comment]
Closing due to lack of reply.
