### ISSUE TITLE
IOS App: Using the Font Name menu for the first time results in mixed up menu

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#6092]
**Describe the bug**
Using the Font Name menu for the first time results in mixed up menu en leads to white menu without options shown
Issue can also be duplicated for the Character> Style or Character>  Font Size menu options. Just before trying any of those restart the app and reopen the document as the issue only is there the first time you try.

**To Reproduce**
1. Open a .odt document, go to edit mode
2. Put your cursor in front of a word in the document
3. Go to the Character menu> select Font Name
4. List of fonts is shows, just click the Back button now without selecting a font in the list
5. Now the Character menu is empty...
6. Click the Paragraph tab, features shows up correctly
7. Click now the Character tab... the font list shows up instead of the expected Character features
8. Click in the document to close the menu
9. Repeat step 2 to  4 again, now the Character menu shows correctly.

**Expected behavior**
The Character menu should behave correctly

**Actual behavior**
Case you use the the described feature for the first time the font menu seems to be still on top of the character menu
 
**Screenshots**
1. Open a .odt document, go to edit mode
2. Put your cursor in front of a word in the document
![image](https://user-images.githubusercontent.com/37268999/227343254-bbf3fd66-64e9-4f36-b8c2-2ea6653cc128.png)

3. Go to the Character menu> select Font Name
![image](https://user-images.githubusercontent.com/37268999/227343353-2eee98aa-1f5f-4048-8d20-fef754a88e03.png)

4. List of fonts is shows, just click the Back button now without selecting a font in the list
![image](https://user-images.githubusercontent.com/37268999/227343483-f7f6768b-491c-4aca-a73c-7ffaab0469d7.png)

5. Now the Character menu is empty...
![image](https://user-images.githubusercontent.com/37268999/227343558-41474de3-a416-4068-a471-6fd55ab75903.png)

6. Click the Paragraph tab, features shows up correctly
![image](https://user-images.githubusercontent.com/37268999/227343648-c45dab09-13e2-45a8-a6ba-681c9d009dd7.png)

7. Click now the Character tab... the font list shows up instead of the expected Character features
![image](https://user-images.githubusercontent.com/37268999/227343706-fae813b8-3f78-49e3-a3ef-810294dee664.png)

8. Click in the document to close the menu
9. Repeat step 2 to  4 again, now the Character menu shows correctly.

**Smartphone (please complete the following information)**
 - Device: [e.g. iPhone14
 - OS: 16.3.1
 -Collabora Office App 22.05.11 (22.5.202303212054)

**Additional context**

**Comment by thebearon** [comment]
Confirmed, and happens with Chrome's responsive mode as well, so not specific to iPhone (iOS). And it's a regression as far as I can see. Thanks for reporting!

**Comment by thebearon** [comment]
This started with the following commit:
https://github.com/CollaboraOnline/online/commit/b835a68a442789f47e8e9ed324a5d15d8f94d7e4
```
Author:     Szymon Kłos <szymon.klos@collabora.com>
AuthorDate: Wed Nov 23 11:41:28 2022 +0100
Commit:     pedropintosilva <65948705+pedropintosilva@users.noreply.github.com>
CommitDate: Fri Nov 25 17:30:39 2022 +0100

    mobile-wizard: don't use close events from tunneled dialogs
```

CC @eszkadev @pedropintosilva.

**Comment by thebearon** [comment]
I could repro this in 22.05.13-1, but not in 22.05.14-3. It did occur once with some random steps, but wasn't reproducible. Let's close, @sebastiaanveld if the bug is still there for you, comment here or open a new issue.

**Comment by sebastiaanveld** [comment]
@thebearon the version in Testflight is still 22.05.13 (22.05.202304231947), can someone update that so I can test?
