### ISSUE TITLE
Presentations "Apply Transition to all Slides" button is not legible

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#6093]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @eszkadev 

### Detailed description and rationale
Apply Transition to all slides button is cramped up

![image](https://user-images.githubusercontent.com/65948705/227490910-167d64ab-2fd0-41c5-8afb-2c375a4c6fdc.png)

### Code pointers
* We could target the #apply_to_all and apply a `width: auto` this would for now fix the issue of not being able to read it
* But maybe better would be to adjust the xml structure in the core side: sd/uiconfig/simpress/ui/slidetransitionspanel.ui

**Comment by eszkadev** [comment]
Pointers:
button is inside button box. That button box has property: `layoutstyle: "center"`. It should then put button in centered container, not right one.

Button box implementation:
https://github.com/CollaboraOnline/online/blob/master/browser/src/control/Control.JSDialogBuilder.js#L626

**Comment by ansh-kalucha** [comment]
Is this task still open?

**Comment by pedropintosilva** [comment]
@ansh-kalucha yes :) should I assign this to you? Feel free to start to work on this ;) Thanks!

**Comment by judith-n** [comment]
Is this issue still not taken by anyone? :)

**Comment by codewithvk** [comment]
Hey @pedropintosilva , I checked. I think someone already fixed this issue. Can you please confirm once and change the status of this issue?
