### ISSUE TITLE
iOS App: Read only mode -> File > Export as > PDF Document (PDF) leads to "crash"

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#6103]
**Describe the bug**
In the read only mode (e.g. after opening a document) the function under File > Export as > PDF Document (PDF) leads to "crash". Well the app doesn't crash, but it is stuck and a user can't exit from there.

**To Reproduce**
1. Open a writer document, don't change to edit mode
2. Tap on File > Export as > PDF Document (PDF)

**Expected behavior**
The file dialog should show up, where a user can select the target folder.

**Actual behavior**
The app is stuck in an operation (probably converting or saving).

**Tablet**
 - OS: iPadOS 16.3.1
 - Version: TestFlight 22.05.11 (22.5.202303212054)

**Comment by Ezinnem** [comment]
I can confirm this experience.

**Comment by Ezinnem** [comment]
I can confirm this experience.

**Comment by plubius** [comment]
I can reproduce this as well. It appears that the iOS C++ code or the LibreOffice code is sending the following message so I will see if I can find which code generates this message:

2023-03-30 18:59:58.164631 -0400 [ app2js ] TRC  To JS: blockui: | CODocument.mm:99

**Comment by plubius** [comment]
Note to myself: the LibreOffice PDF Export Options dialog is appearing in the current TestFlight build but not in the 21.x release so I need to see if suppressing display of that dialog changes anything.

**Comment by plubius** [comment]
The fix for this bug is in the current TestFlight. Does the fix work for you?

**Comment by nikslor** [comment]
Tested again in 22.05.12 (22.5.202304051456); works as expected now :)
Thanks a lot @plubius I think you can close this issue as fixed.
