### ISSUE TITLE
iOS App: Read only mode -> File > Export as > EPUB (.epub) doesn't work

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#6104]
**Describe the bug**
In the read only mode (e.g. after opening a document) the function under File > Export as > EPUB (.epub) doesn't work. Nothing seems to happen (from a user pov).

**To Reproduce**
1. Open a writer document, don't change to edit mode
2. Tap on File > Export as > EPUB (.epub)

**Expected behavior**
The file dialog should show up, where a user can select the target folder.

**Actual behavior**
Nothing seems to happen (from a user pov).

**Tablet**
 - OS: iPadOS 16.3.1
 - Version: TestFlight 22.05.11 (22.5.202303212054)

**Comment by plubius** [comment]
The fix for this bug is in the current TestFlight. Does the fix work for you?

**Comment by nikslor** [comment]
Tested again in 22.05.12 (22.5.202304051456); works as expected now :)
Thanks a lot @plubius I think you can close this issue as fixed.
