### ISSUE TITLE
Opening documents asks for nickname

### ISSUE THREAD

**Issue by G-T100** [CollaboraOnline/online#6105]
Collabora asks for nick name when opening or creating a document on the iOS app.

‘Please choose your nickname to continue as guest user’

Opening or creating documents from the Nextcloud webinterface works well.

**To Reproduce**
1. Open or create a document in Nextcloud iOS app

**Expected behavior**
Just open the document

**Client details:**
Device: Tested on iphone 6s and iphone 13, latest avaliable OS

## Server details
Litespeed server

**PHP version:**
8.1

**Nextcloud version:**
Nextcloud 26.0

**Version of the richdocuments app**
Latest

**Version of Collabora Online**
Latest

**Comment by Ezinnem** [comment]
I can confirm this issue.

**Comment by G-T100** [comment]
22.05.12.4
8.0.0

**Comment by G-T100** [comment]
No. Opening documents in browser on mobile and desktop works well. This is related to the iOS app.

No problem before upgrading to latest versions.

**Comment by thebearon** [comment]
https://github.com/nextcloud/ios/issues/2380 is the correct place for this issue, it's related to the Nextcloud iOS app and/or richdocuments.

**Comment by G-T100** [comment]
Sorry, I meant

Is it related to this issue [nextcloud/richdocuments #2873](https://github.com/nextcloud/richdocuments/issues/2873)

**Comment by thebearon** [comment]
The two descriptions seem completely different, I see no obvious connection between the two.
