### ISSUE TITLE
cannot print

### ISSUE THREAD

**Issue by snetAT** [CollaboraOnline/online#6106]
**Describe the bug**

**To Reproduce**
i open a document, click on file and print - nothing happens

**Expected behavior**
the print dialog appears

**Desktop (please complete the following information)**
 - OS: does not matter
 - Browser:  only chrome, Firefox and Edge works
 - Version: *

**Smartphone (please complete the following information)**

**Additional context**

Chrome Console Log:
`bundle.js:22587 Uncaught DOMException: Blocked a frame with origin "https://office.domain.com" from accessing a cross-origin frame.
    at NewClass._onIframeLoaded (https://office.domain.com/browser/bcbca64/bundle.js:22587:34)`

i have set access-control-allow-origin to https://office.domain.com and a curl -vvv shows it too.

the nextcloud instance runs on domain.com
office.domain.com (code) runs in its own vm

I use haproxy in the following configuration:

domain.com -> haproxy (tls termination) -> nextcloud container 
office.domain.com -> haproxy (tls termination) -> container port 9980

**Comment by gitgt** [comment]
This is not a bug. Rather you are looking for help with configuration which should be done differently: either with Collabora for customers or at forum.collaboraonline.com.
