### ISSUE TITLE
Hide slides in Collabora Online Impress

### ISSUE THREAD

**Issue by rriemann** [CollaboraOnline/online#6110]
**Describe the bug**

Create a new slide deck in Impress with 3 slides. You cannot hide any slides unlike in Collabora Office.

**To Reproduce**
1. create a new slide deck in Impress with 3 slides.
2. there is no way to hide slides (I checked if the slide preview in the left sidebar has a context menu, but it does not.)

**Expected behavior**

I can hide or unhide slides.

**Actual behavior**
I cannot hide or unhide slides.

**Desktop (please complete the following information)**
 - OS: openSUSE
 - Browser: Firefox
 - Version: 110

Version: Collabora Online 22.05.12.4

**Comment by Stefan-U** [comment]
+1
I also need the function frequently and have to go to the desktop version for it.
Good suggestion.

**Comment by gitgt** [comment]
Hiding will be soon in  COOL 23.05.1-1. So I close this one. Note: it may not include hiding of multiple slides at once.
