### ISSUE TITLE
[ websrv_poll ] WRN convert-to: Requesting address is denied:

### ISSUE THREAD

**Issue by jonas740** [CollaboraOnline/online#6116]
I get an error/warn message when I read  the docker container log for collabora.

Installed for nextcloud with Swag and redis.

[ websrv_poll ] WRN convert-to: Requesting address is denied: <my public ip address>

That is the message that goes on and on..

But the nextcloud office work and I can use it but this message is bothering me.

**Comment by thebearon** [comment]
That is likely Nextcloud's preview generation, which, if not on the same server, has to be allowed in Collabora Online, ie. the IP has to be added in the list of `net.post_allow.host` entries in the config.

In case of Docker containers, this can be done via the following `extra_params` parameter:
`-e "extra_params=--o:net.post_allow_host[0]=xxx\.yyy\.zzz\.aaa"`

This replaces the first entry, you can use a larger index to replace a different one, or amend to the default list. The pattern can also be more sophisticated, eg. `192\.168\.[0-9]{1,3}\.[0-9]{1,3}`, but it has to be an IP or IP range, and mustn't be a host name.

You can check if you were successful by looking for `Adding trusted POST_ALLOW host:` in the logs.
I haven't tested the above, so it might need smaller corrections, but the principle is as described.
If you have further questions, please use the forum: https://forum.collaboraonline.com/
