### ISSUE TITLE
collabora becomes very slow - not responsive - sometimes 

### ISSUE THREAD

**Issue by ferdiga** [CollaboraOnline/online#6120]
**Describe the bug**
Sometimes - typically if more users open the document -  typing is not possible any more - difficult to place the cursor and type on the correct position and after a while the screen is not or randomly refreshing.

**To Reproduce**
1. open a docx file - let someone else (on a different device) also open the document 
2. try to type / edit / insert - probably copy some text.

**Expected behavior**
refresh and correctly position the cursor with minimal delay

**Actual behavior**
everything is delayed - text is not updated, cursor not positioned - sometimes after some seconds often more than 10-20 the screen refreshes but all operations are very unresponsive.

**Screenshots**

**Desktop (please complete the following information)**
 - OS: ios 13.2.1
 - Browser: brave
 - Version: [Version 1.49.132 Chromium: 111.0.5563.147 (Official Build) (arm64)](https://brave.com/latest/)
 - collabora docker 
 COOLWSD version:
22.05.12.4
git hash: 
[bcbca64](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/bcbca64'));)
(E)
LOKit version:
built on 
[a great technology base](javascript:void(window.open('http://col.la/lot'));)
Collabora Office 22.05.12.3
git hash: 
[416b470](javascript:void(window.open('https://hub.libreoffice.org/git-core/416b470'));)
Served by:
 
Ubuntu 18.04.6 LTS
 
[5453f180](https://he22-collabora.chricar.at/hosting/discovery)

**Smartphone (please complete the following information)**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**
need to restart the docker ( sometimes the server )

**Comment by ferdiga** [comment]
sometimes a restart of the browser solves the problem

**Comment by gitgt** [comment]
Can you please turn on logging, preferably trace level just when problem happens, and attach here logs giving some clue on the problem?

**Comment by ferdiga** [comment]
no more issues with the last versions
