### ISSUE TITLE
paste text from the clipboard into a table (.xls or .ods

### ISSUE THREAD

**Issue by username345678** [CollaboraOnline/online#6129]
hi,
i would like to paste text from the clipboard into a table (.xls or .ods). this is not possible. (text copied from the table can be pasted though. only text from other sources cannot be pasted). 

is it possible to make this work?

thanks a lot for the help!

best regards
thiemo

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots**

**Desktop (please complete the following information)**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information)**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by thebearon** [comment]
The description isn't clear to me, what kind of text do you want to paste? I have no trouble pasting text into spreadsheets.

**Comment by username345678** [comment]
i just want to past "normal" text from other mediums like email, .doc, 
or websites...


Am 07.04.23 um 22:39 schrieb thebearon:

**Comment by Ezinnem** [comment]
I am able to paste from the website into cells of a .ods sheet.

See a screen recording:

https://user-images.githubusercontent.com/54344301/232802976-bde0cfa6-a02a-4da0-98af-64b7d86c4e70.mp4

@username345678, Please can you share the Collabora Online version that you are using?

**Comment by Ezinnem** [comment]
I am closing this issue because it is not reproducible on my end and there is no response from the author.
