### ISSUE TITLE
iOS App: PDF and EPUB icons missing

### ISSUE THREAD

**Issue by Ezinnem** [CollaboraOnline/online#6145]
**Describe the bug**
The PDF and EPUB icon seem missing

**To Reproduce**
1. Open a .odt file from Collabora office app on TestFlight 22.05.12 (22.5.202304051456)
2. Click on the pencil icon to edit
3. Go to File menu
4. See the PDF and EPUB icons are missing

**Expected behavior**
The icon should be visible

**Actual behavior**
THe icons are missing

**Screenshots**
![missing-icons](https://user-images.githubusercontent.com/54344301/230355878-991e9383-51da-41b6-b058-a1efdb17b8c1.PNG)

**Device (please complete the following information)**
 - Version: [e.g. 22.05.12 (22.5.202304051456]

**Comment by plubius** [comment]
The fix for this bug is in the today's TestFlight build. Feel free to reopen this bug if the fix does not work for you.

**Comment by Ezinnem** [comment]
Thanks for the fix @plubius.   The PDF and EPUB icons are now visible.


I can confirm the fix on the latest TestFlight build:

COOLWSD Version:
22.05.12.4 (22.5.202304132141)
