### ISSUE TITLE
Collabora not generating formatiing data, Only plain text on Saving to storrage

### ISSUE THREAD

**Issue by DanBrown47** [CollaboraOnline/online#6153]
**Describe the bug**
I have Collabora in iframe with a WOPI Host; after editing a document with formatting like bold or heading, The data that shows that is part of formatting are not being sent to the backend.

**To Reproduce**
1. Setup Collabora and a WOPI Host
2. Open a Document to edit, add some formatting data, and save
3. Intercept the request in WOPIHost to find the request body
4. See an error, Request body will contain plain data

**Expected behavior**
It should have formatting data

**Actual behavior**
Only plain text; on reloading the document all the data regarding the formatting are lost.

**Screenshots**
![image](https://user-images.githubusercontent.com/45515141/230824311-b511fd02-451e-4786-aed5-0d5c4a737a53.png)

**Desktop (please complete the following information)**
 - OS: Linux 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - Browser: Chrome v108
 - Version: [22.05.12.4.1](https://hub.docker.com/layers/collabora/code/22.05.12.4.1/images/sha256-e913ae3f4e24ea6af36151818b222e7eb75c2619c84c6126ed79f6777fb6df98?context=explore)

**Additional context**
Using custom code by editing paperless-ngx as WOPI Host

**Comment by DanBrown47** [comment]
@pedropintosilva Is this caused by any misconfigurations on setting up collabora ?

**Comment by thebearon** [comment]
What is the file's extension, and its format?

**Comment by thebearon** [comment]
Closing due to lack of reply.
