### ISSUE TITLE
iOS app: button to show/hide sidebar is missing

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#616]
**Describe the bug**
In the testflight version 6.4.0 (13) the button to show/hide the sidebar is missing.

**To Reproduce**
1. Open (e.g.) a writer document using the iOS app
2. Try to toggle the visibility of the sidebar

**Expected behavior**
The button to show/hide the sidebar is missing.

**Actual behavior**
The button should be shown in the right upper corner, next to the "x" button.

**Screenshots**
<img width="1112" alt="sidebar_toggle_button_missing" src="https://user-images.githubusercontent.com/1211300/98948491-c9bb9280-24f6-11eb-861c-bfeefb575016.png">

**Tablet**
 - OS: iPad OS 14.2
 - Version: 6.4.0 (13)

**Comment by tml1024** [comment]
Investigating using Safari's Develop menu shows that the button is there, but it is apparently located outside the visible part of its parent element, or something. If I in the Safari debugger modify the width attribute of the img element that shows the lc_sidebar.svg, it does show up 
![image](https://user-images.githubusercontent.com/310731/98948978-cf69a600-24ff-11eb-88ee-fda6a4a208d4.png)

**Comment by nikslor** [comment]
Tested with 6.4.0 (14); issue is gone/fixed.

Thanks a lot for taking care of this!

@tml1024 do you close this bug?
