### ISSUE TITLE
Comments in Writer don't get removed with their respective "remove" context menu action when track changes are recorded

### ISSUE THREAD

**Issue by rriemann** [CollaboraOnline/online#6178]
**Describe the bug**
Comments in Writer don't get removed with their respective "remove" context menu action when track changes are recorded.

**To Reproduce**
1. Create a new writer document
2. Add a comment
3. enable recording of track changes
4. select the context option to remove the comment
5. The Comment is not removed.

In LibreOffice on the desktop, the comment seems to be marked as deleted, but is still in the document.

In Collabora Online, disabling and enabling the display of track changes seems to remove the comment eventually.

Unrelated other bug here: The active tab in "tabbed view" changes when twice clicking on "Show".

https://user-images.githubusercontent.com/111932/231511084-bc85e971-b4ca-479f-aaf4-1e50dd2f5e8b.mp4

**Expected behavior**
Comment is removed.

**Actual behavior**

Comment stays after being removed.

**Screenshots**

**Desktop (please complete the following information)**
 - OS: openSuse Tumbleweed
 - Browser: Firefox
 

COOLWSD version:
22.05.12.4 git hash: bcbca64 (E)
LOKit version: built on a great technology base
Collabora Office 22.05.12.3 git hash: 416b470
Served by: Ubuntu 18.04.6 LTS c149d022

**Comment by Ezinnem** [comment]
I can confirm this issue

**Comment by Ezinnem** [comment]
The fix is already made: https://github.com/CollaboraOnline/online/pull/8251

https://github.com/CollaboraOnline/online/assets/54344301/6f459cca-516e-4623-b158-92a8ec2e5eb9
