### ISSUE TITLE
Spreadsheet border dropdown not showing what each border option does.

### ISSUE THREAD

**Issue by DonPedro92** [CollaboraOnline/online#6199]
**Describe the bug**
Buttons for selecting different cell borders are missing pictures/text describing what they do.

**To Reproduce**
1. Go to any spreadsheet new or existing, I have tried .ods and .xlsx.
2. Click on 'Borders dropdown'
3. See error

**Expected behavior**
I'd expect there to be buttons showing what types of borders each button will generate..

**Actual behavior**
The border function works but I have to try each one until I get the border style I'm looking for.

**Screenshots**
![Nextcloud spreadsheet problem](https://user-images.githubusercontent.com/61293849/232434961-95fea678-1bef-4521-9ae6-f907439d3a58.png)

**Desktop (please complete the following information)**
 - OS: (1) Windows 11 & (2) Ubuntu 22.04 LTS
 - Browser: (1) Chrome & (2) Firefox
 - Version: Latest for both computers including newest version of each browser as of today. (2023-04-17)

**Additional context**
I'm self-hosting on a Turnkey Linux Nextcloud LXC container, everything there is also updated as of today. Everything else in Nextcloud <--> Collabora works perfectly fine.

**Comment by DonPedro92** [comment]
@Ezinnem. I'm using the exact same version:
![Collabora version](https://user-images.githubusercontent.com/61293849/232679619-6c92609e-1d07-4f7a-8d18-f9b40218b7fb.png)

**Comment by Ezinnem** [comment]
@pedropintosilva @eszkadev

**Comment by DonPedro92** [comment]
@Ezinnem @pedropintosilva @eszkadev 
I can confirm that this issue has somewhat been solved in the latest version 23.05.0.5.

Icons are there now except when you hover over them.
![Skärmbild 2023-06-19 130826](https://github.com/CollaboraOnline/online/assets/61293849/a5a154d6-27a2-40cf-92ac-f40de36a16e7)

**Comment by gitgt** [comment]
Fixed with https://github.com/CollaboraOnline/online/pull/6603.
