### ISSUE TITLE
Collabora drop down menu issue

### ISSUE THREAD

**Issue by Maddog987** [CollaboraOnline/online#6205]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots**

**Desktop (please complete the following information)**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information)**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by Ezinnem** [comment]
It is not very clear which drop-down menu issue that you refer to.

@Maddog987, Please can you share a description of the issue you experienced?
You can also share a screen-recording if you'd like.

**Comment by Ezinnem** [comment]
Just like #6206, I will close this too.

@Maddog987, Please feel free to add the details when you encounter the issue again.
