### ISSUE TITLE
[Android] Collabora Office crashes when opening files from Total Commander

### ISSUE THREAD

**Issue by dardoor** [CollaboraOnline/online#6227]
I can open files with Collabora Office or from the stock "Files" app, but when I try to open them from Total Commander it doesn't work. I get an error: "Collabora Office has stopped".

Collabora Office version 21.11.6.1, Android 8

**Comment by dardoor** [comment]
I reproduced this on another phone But not on a phone with Android 11.

So this looks like a combination of older Android and TC (or another 3rd party file manager.)

**Comment by gitgt** [comment]
I saw this with File Manager Plus in older Collabora Office 4.2.8, so it must have been some older Android.
No crash for me in Android 11 with MiXplorer.

**Comment by timur-g** [comment]
I do not reproduce with Total Commander and Collabora 21.11 or 23.05 in Android 11. 
It is well possible that issue happens in older Android, but for that I will close as WontFix.
Not that older Android cannot be userd, but it is not reasonable to expect fixing specific combinations of software from a product that works well in current and many other combinations.
