### ISSUE TITLE
Tabbed view : Dropdown arrows are misplaced

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#6236]
**Describe the bug**

![image](https://user-images.githubusercontent.com/65948705/234613772-648fbf8f-f9cf-415d-b61a-a5b4bb983482.png)

They should be placed in paralleled with the icons as seen in 22.05

**Versions**
| Where | branches |
| -- | -- |
| Online | master |
| Core | distro/collabora/co-23.05 |

**Comment by GulsahKose** [comment]
This commit  be04111173dfa85f7f20cc0eb0e5babbe220a665 caused the regression.

**Comment by thebearon** [comment]
@pedropintosilva This seems fine to me, is anything left to do here?

**Comment by timur-g** [comment]
Seems good to me, not clear if there was something else here to do with icons. I close.
