### ISSUE TITLE
dark mode -> dark icons

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#6246]
At file LOUtil.js the images path was defined.

https://github.com/CollaboraOnline/online/blob/c6ddeca2d5cdfd3ee999e57d2a7faf734a1fee09/browser/src/core/LOUtil.js#L112

When switch between dark and light theme instead of images/ there should be a value depand on 

https://github.com/CollaboraOnline/online/blob/c6ddeca2d5cdfd3ee999e57d2a7faf734a1fee09/browser/src/control/Control.UIManager.js#L73

In addition there has to be a fallback mode, when there is no icon at images/dark the images/ icon will be used.

**Comment by Andreas-Kainz** [comment]
@pedropintosilva did I miss something (I know there is toolbar.css where icons will be load separate)?

**Comment by pedropintosilva** [comment]
hm (warning in advanced I didn't thought long and hard about this but) couldn't we just change the images path within `loadDarkMode` function in uimanager?

**Comment by pedropintosilva** [comment]
cc: @ChrisGlad @eszkadev

**Comment by gitgt** [comment]
Sorry, is this it? Existing values should be visibly white, not black on dark. Here is Sidebar but similar for Toolbar.
![image](https://github.com/CollaboraOnline/online/assets/7240617/56d2f1bc-95de-4941-b5c9-0a7ca3b232cd)

**Comment by Andreas-Kainz** [comment]
Can we close this issue? The icon loading work really well when select dark/light mode.

At the image it look like nextcloud theming use a filter to theme the icons black when selected, which is fine for light mode but the css should be updated for dark mode. However nextcloud theming is not part of online repository.
