### ISSUE TITLE
Is Collabora for Android dead?

### ISSUE THREAD

**Issue by moshpirit** [CollaboraOnline/online#6259]
It's been almost 9 months since its last release. Is this project dead?

**Comment by user8446** [comment]
I came here wondering the same as I have noticed the android version not advancing.

**Comment by PeterKW** [comment]
@user8446 @moshpirit 

This is what I've found: 
https://github.com/CollaboraOnline/online/issues/7149

**Comment by Rash419** [comment]
@PeterKW and @moshpirit No, Android is not dead. We plan to release it asap blockers are fixed
more info on: https://forum.collaboraonline.com/t/community-weekly-meeting-132/2015

**Comment by moshpirit** [comment]
That's fantastic news!! :partying_face:
