### ISSUE TITLE
JSDialog: Error on console when opening a dialog with tab control

### ISSUE THREAD

**Issue by thebearon** [CollaboraOnline/online#6271]
Open a document, and then File -> Properties.

Check browser console, and note the following error:
```
cannot get focus for widget: "tabcontrol"

addHandlers @ Control.JSDialog.js:339
onJSDialog @ Control.JSDialog.js:531
fire @ Events.js:152
_onJSDialog @ Socket.js:1448
_onMessage @ Socket.js:1140
_emitSlurpedEvents @ Socket.js:342
(anonymous) @ Socket.js:292
setTimeout (async)
_queueSlurpEventEmission @ Socket.js:290
_slurpMessage @ Socket.js:390
```

No noticeable problem otherwise.

CC @eszkadev @GulsahKose.

**Comment by Darshan-upadhyay1110** [comment]
Working okay in current version.
COOLWSD version: 24.04.5.2 (git hash: df56d78c)
LOKit version: Collabora OfficeDev 24.04.5.2 (git hash: b57fd97)
Served by: Ubuntu 23.10
Server ID: 6379dd51
