### ISSUE TITLE
Texts in Page Number dialog needs some padding 

### ISSUE THREAD

**Issue by Ezinnem** [CollaboraOnline/online#6285]
**Describe the bug**

**To Reproduce**
1. Open a new .odt file
2. Go to Insert > Page Number

Notice that the `Preview` text needs some padding

**Expected behavior**
![Screenshot from 2023-05-04 20-51-03](https://user-images.githubusercontent.com/54344301/236400749-0f04ba7f-2120-48d7-9935-483e2a6c6ce5.png)

**Actual behavior**
![Screenshot from 2023-05-04 20-50-01](https://user-images.githubusercontent.com/54344301/236402295-a63ed038-eb1e-4f2b-aa86-4169a3d446c5.png)

**Desktop (please complete the following information)**
 COOLWSD version:
23.05.0.1 git hash: [9de01e11](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/9de01e11'));)

**Comment by Ezinnem** [comment]
@pedropintosilva @eszkadev

**Comment by pedropintosilva** [comment]
I'm afraid the problem here is not the padding, but rather the `Preview` label is now misplaced (and then yes it both columns should have a gap)

**Comment by GulsahKose** [comment]
Current window looks like this. Is is OK? 

![Screenshot from 2023-05-09 17-59-26](https://github.com/CollaboraOnline/online/assets/2954981/2c3369d2-f1b6-472b-98a0-4460236070b4)
