### ISSUE TITLE
Overlay with color name of the gradient in chart sidebar looks misplaced

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#6293]
**Describe the bug**
The color name of a gradient in the chart sidebar looks misplaced in 23.05.x

![image](https://user-images.githubusercontent.com/1211300/236550133-040ca7cb-8067-484b-bab6-51de7f3632eb.png)

**To Reproduce**
1. Open a writer document
2. Add a chart
3. Edit the chart
4. Scroll to the "Area" part in the sidebar
5. Choose "Gradien" as "Fill:"
6. Hover over the color
7. See error

**Expected behavior**
The color name should not overlay the actual color.

**Actual behavior**
The color name overlays the actual color.

**Comment by thebearon** [comment]
Confirmed, and it's the same in 22.05, the oldest I tested with is 22.05.3-1.
Looks like a bug specific to JS sidebar.

CC @eszkadev @pedropintosilva.
