### ISSUE TITLE
Macro Security dialog doesn't get dismissed when choosing Enable Macros

### ISSUE THREAD

**Issue by thebearon** [CollaboraOnline/online#6317]
This bug is 23.05 only.

- First enable macros by setting `security.enable_macros_execution` in `/etc/coolwsd/coolwsd.xml` to `true`,
- Open a macro-enabled document/spreadsheet, eg. the `macro.ods` from the repo:
https://github.com/CollaboraOnline/online/blob/master/cypress_test/data/desktop/calc/macro.ods
- In the dialog, pick `Enable Macros`.

-> The dialog doesn't get dismissed.

This is a regression from the following commit's `distro/collabora/co-23.05` port:
https://cgit.freedesktop.org/libreoffice/core/commit/?id=09976bda9c196b2426b8826941f21384a58bf536
```
author		Szymon Kłos <szymon.klos@collabora.com>	2023-03-06 11:33:08 +0100
committer	Szymon Kłos <szymon.klos@collabora.com>	2023-03-07 09:29:50 +0000

jsdialog: don't close dialog on tab page destroy
```

@eszkadev, let me assign it directly to you.

**Comment by eszkadev** [comment]
fix in core: https://gerrit.libreoffice.org/c/core/+/151602

**Comment by eszkadev** [comment]
merged
