### ISSUE TITLE
Calc- Every click triggers the flickers the keyboard on iPad

### ISSUE THREAD

**Issue by Ezinnem** [CollaboraOnline/online#6319]
**Describe the bug**

**To Reproduce**

1. Open a .ods file using online 23.05  build on iPad 
2. Try to add a new sheet

Notice that each click triggers the keyboard to Flicker.

**Expected behavior**
The keyboard should not flicker

**Actual behavior**
The keyboard flickers

**Screenshots**

https://github.com/CollaboraOnline/online/assets/54344301/77c3c1fd-c08b-4c4c-9ea2-aca785d5a167

**Smartphone (please complete the following information)**
 - Device: iPad
 - OS: iOS 16
 - Browser: Chrome
 
**Additional context**
Tracked internally on [T42314](https://phabricator.collabora.com/T42314)

**Comment by Darshan-upadhyay1110** [comment]
@Ezinnem i think in the latest version this flicker this gets addressed. I am closing this as this report is old and with 24.04 it works okay with anroid tab.

Unfortunately i do not have the iPad so need your comment here on that.
