### ISSUE TITLE
Validity message dialog is tunneled

### ISSUE THREAD

**Issue by thebearon** [CollaboraOnline/online#6327]
Open the attached spreadsheets, and enter an invalid value in one of the cells with the described validity checks, eg. 20 in A2.

There is a message dialog, but the dialog is tunneled, and not a JSDialog.

This is for version 23.05.

[validity.xlsx](https://github.com/CollaboraOnline/online/files/11447896/validity.xlsx)

![validity_tunneled](https://github.com/CollaboraOnline/online/assets/19438782/dd3f3d9d-181d-4917-94fd-c73b06e01a03)

**Comment by thebearon** [comment]
CC @pedropintosilva

**Comment by pedropintosilva** [comment]
@shehr please take a look at this. I have tried to assign this to you but couldn't find you as shehr here on github

**Comment by shehr7** [comment]
@pedropintosilva yes my username is shehr7 on github, that's why.

**Comment by eszkadev** [comment]
This is not a JSDialog, this is dialog in desktop LibreOffice app. Bug is about Collabora Online, not LibreOffice :)

**Comment by shehr7** [comment]
@eszkadev My bad, I'm gonna recheck it.

**Comment by eszkadev** [comment]
fix: https://gerrit.libreoffice.org/c/core/+/151915
