### ISSUE TITLE
Ctrl-S after full screen presentation is not catched

### ISSUE THREAD

**Issue by juliusknorr** [CollaboraOnline/online#6328]
**Describe the bug**
I created the New Presentation file, added some text and save the text using ctrl+s keys its worked, but when i clicked on Fullscreen presentation and go back for editing text and using ctrl+s keys for save the text but its start downloading.

**To Reproduce**
1. Open a presentation
2. Start the full screen presentation
3. Exit it
4. Press Ctrl-S

**Expected behavior**
The file is saved

**Actual behavior**
The browser save as dialog is showing up for the html page

**Desktop (please complete the following information)**
 - OS: macOS
 - Browser: Chrome

**Comment by Ezinnem** [comment]
Reproducible in:

COOLWSD version:
22.05.15.2 git hash: [a13f33b7](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/a13f33b7'));)

**Comment by Darshan-upadhyay1110** [comment]
Works ok with version

COOLWSD version: 24.04.10.1(git hash: dc930ffa6d)
LOKit version: Collabora OfficeDev 24.04.10.1(git hash: 8b2330d)
Served by: Ubuntu 23.10
Server ID: 2aa938f2
WOPI host: 


@juliusknorr can you confirm ? maybe something related to MaoOS

**Comment by juliusknorr** [comment]
Can confirm that it is no longer reproducable on master from today

COOLWSD version: 24.04.10.1(git hash: d1fee3efa2 (E))
