### ISSUE TITLE
Dialog window opens more than one times

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#6329]
If you click an dialog botton more often (cause the responce isn't that good) the dialog window opens more than one time.

![image](https://github.com/CollaboraOnline/online/assets/8517736/98150251-8cb5-42bd-9b2c-465c0f0b3cc2)

**Comment by Andreas-Kainz** [comment]
And when we show a spinner on top of the icon, when the command was clicked? 

Or do we know the "id" of the dialog and if it's shown more than once, it will be hidden?

We can also close the issue. It was only a bit strange.

**Comment by thebearon** [comment]
> From the other hand: it does exactly what the user wants, if he requests 3 times the same thing, he will receive 3 instances :)

What if it's like: they click on it once, nothing happens, click on it again, nothing happens, click on it a hird time, and then they start showing up? ;)

**Comment by Darshan-upadhyay1110** [comment]
COOLWSD version: 24.04.10.1(git hash: dc930ffa6d)
LOKit version: Collabora OfficeDev 24.04.10.1(git hash: 8b2330d)
Served by: Ubuntu 23.10
Server ID: 2aa938f2
WOPI host:
