### ISSUE TITLE
Impossible de verrouiller certaines cellule d'une feuille de calcul 

### ISSUE THREAD

**Issue by ProfTIM86** [CollaboraOnline/online#6360]
Bonjour

Nous avons plusieurs feuilles de calculs sous Résana.

Les collaborateurs doivent pouvoir saisir des données dans certaines cellules MAIS ils ne doivent pas pouvoir modifier les cellules contenant des formules de calcul.

Après avoir voulu protéger les cellules concernées, cela indique que cette protection sera active UNIQUMENT lorsque le feuille de calcul sera protégée.

Après plusieurs recherches, il n'as pas été possible de verrouiller ou protéger la feuille de calcul.

En vous remerciant pour la solution.

Cordialement

**Comment by ProfTIM86** [comment]
![image](https://github.com/CollaboraOnline/online/assets/77763776/1c141583-68e5-43a2-b1f4-223d17f772b5)

La fonctionnalité entourée n'est pas disponible

**Comment by timur-g** [comment]
Duplicate of #551 .
