### ISSUE TITLE
"Help > About" Copy Button

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#6381]
**Is your feature request related to a problem? Please describe.**

Right now, it's hard to copy/paste out of Collabora Online's:

- **Help > About** page.

Making this easier would:

- Get more users to include/post their info

for:

- bug reports
  - Github, Forum posts
- when they need help
  - reporting bugs, configuration issues, missing features, etc.

I think it indirectly would make QA/debugging much easier too, because many users:

- Currently take screenshots instead.
- Don't include the info at all.
   - (And this would help have consistent formatting of About text too! With exact git commits, etc.)

**Describe the solution you'd like**

Add a:

- Copy button

similar to LibreOffice's **Help > About LibreOffice**:

![LibreOffice 7 5 3 - Help About Info - Copy Button](https://github.com/CollaboraOnline/online/assets/5774324/b5d4ba75-c5e9-46db-b130-ee8eb06de5c2)

**Describe alternatives you've considered**

Making the formatting better when you:

- Highlight the text in the "About" window.
- `Ctrl+C` + `Ctrl+V`

Right now, it outputs in an ugly text too (with odd linebreaks, etc.).

Hopefully the button will do much better + make this much easier though. :)

**Comment by pedropintosilva** [comment]
additional iteration https://github.com/CollaboraOnline/online/issues/6764
