### ISSUE TITLE
Viewing tiff file with multiple pages only shows first page

### ISSUE THREAD

**Issue by vimal7370** [CollaboraOnline/online#6403]
**Describe the bug**
CODE does not detect multiple pages inside a tif/tiff file, and only displays the first page. 

**To Reproduce**
1. Try to view a tiff file with multiple pages

**Expected behavior**
All pages in the file should be viewed

**Actual behavior**
Only the first page is displayed. It says 'Page 1 of 1' when clearly there are more pages in the file.

**Screenshots**
![6dbbe4900833834dd5b3b91ad23a9905fd037841](https://github.com/CollaboraOnline/online/assets/8141345/f80d74da-64ef-47d0-b354-ec3920d09d83)

**Desktop (please complete the following information)**
 - OS: Mac OS X 12.6.1
 - Browser: Chrome
 - Version: latest

**Additional context**

For testing: [Sample tiff file.tiff.zip](https://github.com/CollaboraOnline/online/files/11539756/Sample.tiff.file.tiff.zip)

**Comment by Tex2002ans** [comment]
Multi-Page TIFF support was added into LibreOffice by @Rash419:

- [Bug #155444: "Support opening TIFF image containing multiple images in Draw showing one image per page"](https://bugs.documentfoundation.org/show_bug.cgi?id=155444#c5)

This new feature should be making it into Collabora Office's next release.

Thanks for the initial bug report, vimal7370. :)

- - -

For more info, also see original forum topic:

- [forum.CollaboraOnline.com: "Tiff file with multiple pages only shows first page"](https://forum.collaboraonline.com/t/tiff-file-with-multiple-pages-only-shows-first-page/1820/7)
