### ISSUE TITLE
23.05 - Draw - In Compact View, the Page Layout icon highlights Slide Layout

### ISSUE THREAD

**Issue by Ezinnem** [CollaboraOnline/online#6406]
**Describe the bug**

**To Reproduce**

1. Open .odg file
2. Switch to compact View

Hover on the Page Layout Icon, see that it highlights Slide Layout

**Expected behavior**
Hover text should be "Page Layout"

**Actual behavior**
Hover text reads "Slide Layout"

**Screenshots**

https://github.com/CollaboraOnline/online/assets/54344301/31956e1e-5160-4919-88a5-f11f77eea8f4

**Desktop (please complete the following information)**

COOLWSD version:
23.05.0.1snapshot git hash: https://github.com/CollaboraOnline/online/commit/012b00d6d4530fb7e74fac5c32696c82de028036(E)

Phabricator link: [T42483](https://phabricator.collabora.com/T42483)

**Comment by pedropintosilva** [comment]
@codewithvk was interested in fixing this , I think

**Comment by codewithvk** [comment]
I can work on it.

**Comment by codewithvk** [comment]
![image](https://github.com/CollaboraOnline/online/assets/61119120/ca3c25d0-a992-4500-ace0-c626820c1e7f)
It seems like, We did intentionally use the text "Slide Layout" as in `View` we have text "Slidebar".

@pedropintosilva @Ezinnem

**Comment by pedropintosilva** [comment]
@codewithvk true. But now that I think about it's probably best to change it (specially because the sidebar's contents can change depending on the object selected)

I have assign this to you :)

**Comment by codewithvk** [comment]
One more doubt, 
![image](https://github.com/CollaboraOnline/online/assets/61119120/6115c0b9-7c3d-432d-8e3b-7908a719b7e2)
Why do we have Page Layout and Sidebar both?
