### ISSUE TITLE
Closing dialog doesn't return focus to the document, needs extra click to focus

### ISSUE THREAD

**Issue by thebearon** [CollaboraOnline/online#6419]
- Open a document,
- Open Format Character dialog,
- Close it by pressing Cancel, and type into the document.

-> No character is entered.

This is a regression from the following commit, which was an accessibility-related change:
0f41b9cd1d277820b7fbe6b8a0627e9cd1742349 / #6146
```
Author:     Gökay Şatır <gokaysatir@collabora.com>
AuthorDate: Thu Apr 6 16:17:25 2023 +0300
Commit:     Gökay Şatır <gokaysatir@gmail.com>
CommitDate: Fri Apr 7 22:22:00 2023 +0300

    Set focus to last element after a popup window is closed.
```

@gokaysatir, let me assing this directly to you.

**Comment by gokaysatir** [comment]
Thank you @thebearon.

Hopefuly this one fixes the issue:
* https://github.com/CollaboraOnline/online/pull/6427

**Comment by thebearon** [comment]
I can confirm it is fixed, thanks for that, Gökay!
