### ISSUE TITLE
pre-cache impress slides on client 

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#6423]
We should improve impress online performance by pre-caching the content of the previous and next slide, and keeping that up-to-date in the JS / client side; then switching to the next slide should be instant - and done purely on the client side; giving us time to load the next slide before switching to that - for repeated page-down.

This should hide lots of latency at a reasonably low cost I believe.

**Comment by mmeeks** [comment]
Possible a regression here - we used to pre-cache tiles for all slides, and somehow these seem not to be stored anymore even in the absence of edits in 23.05

**Comment by codewithvk** [comment]
Hello, @mmeeks I noticed that we are currently making server calls to retrieve slides. Have you considered utilizing indexedDB as an alternative approach? Storing all the slides in indexedDB could potentially offer faster access compared to making server requests. Of course, this suggestion assumes that we don't rely on socket calls for the site, among other assumptions. Please take my thoughts with a grain of salt as I'm still getting familiar with the codebase and may not have a complete understanding. I just wanted to mention that I'm a junior developer, and I'm eager to contribute and learn more. Any feedback or guidance you can provide would be greatly appreciated.

**Comment by codewithvk** [comment]
Hello @mmeeks,

I noticed that we are currently making server calls to retrieve slides. Have you considered utilizing indexedDB as an alternative approach? Storing all the slides in indexedDB could potentially offer faster access compared to making server requests. Of course, this suggestion assumes that we don't rely on socket calls for the site, among other assumptions. Please take my thoughts with a grain of salt as I'm still getting familiar with the codebase and may not have a complete understanding.

Additionally, I wanted to mention that I have experience working on a similar caching layer on the client side, although the codebase was smaller in that case. However, I would be enthusiastic about working on these kinds of issues and expanding my skills. Any feedback or guidance you can provide would be greatly appreciated.

**Comment by caolanm** [comment]
I think this used to work but a series of changes and modifications resulted in 2 or more problems that make it no longer work

**Comment by mmeeks** [comment]
> I noticed that we are currently making server calls to retrieve slides.
Since the server has the information - the client necessarily has to fetch it somehow.

> Have you considered utilizing indexedDB as an alternative approach?
Not really - it's interesting to read about indexedDB. One of the things we particularly like however is not sharing the content of documents in the client wherever possible. As a potentially larger data-store for stashing tiles that we could use - it might be interesting I guess - currently we mostly keep them in memory.

For now - fixing the issues we have with caching and pre-loading would be the quickest way to solve this; I imagine I broke them with the delta work somehow ... Thanks Caolan !

**Comment by mmeeks** [comment]
@caolanm Great catch checking for el.src in error (which doesn't work for new canvas tiles - quite possibly there are other instances of that snafu around the codebase).

**Comment by caolanm** [comment]
@plubius it occurs to me that after this that there will likely be more HTMLCanvasElement alive at the same time than there was before, e.g. https://github.com/caolanm/online/commit/a6aace63983fc004a1aca8899d9b8068143a8400 and https://github.com/caolanm/online/commit/53d8f75cd556b2225fd11bd6e0b9a85b982d1fff

I wonder if that is going to be a problem when I see iOS specific cases trying to reduce over all canvas memory use? There is I guess the option of converting to IMG before adding to the cache if needs be.

**Comment by mmeeks** [comment]
Hmm - the conversion to img is pretty horribly expensive now I think about it; another option might be to keep the zstd compressed original blob around, and the deltas that go on top of that (they are size limited in aggregate) collapsing that when we ge ta new keyframe; a zstd compressed thing is around 4k or so AFAIR, not the 256k of a canvas; so we should get a biggish win there for free. I fear that the convert-to-img is going to be very clunky - deflate is far from fast as we convert to PNG, and then storing it as a base64 encoded image URL is also not that cute ;-)

**Comment by plubius** [comment]
I think @mmeeks idea looks really promising. My current solution in 22.05 basically subjects an existing tile to the slow canvas-to-img conversion until enough canvas memory has been reclaimed and canvas.getContext('2d') succeeds. So once a tile becomes an img, it remains an img for its remaining life.

So saving the zstd compressed data looks pretty easy to do in browser/src/layer/tile/CanvasTileLayer.js. In  _applyDelta(), tile.el is where I store the img created from the canvas so we can just assignment the functions rawData parameter in say tile.rawData, skip the conversion to an img.

Of course, the big question is where are the codepoints where we have to test for a "reclaimed canvas" tile and invoke _applyDelta() with the tile and its rawData to recreate its canvas (and reclaim others if needed)?

I am happy to build and test if you implement anything. And, if you can't get to it this, I can maybe take a stab at this next week.

**Comment by mmeeks** [comment]
Ah - so images actually get converted back into canvases when we need to apply a delta; in this case:

				if (initCanvas && tile.el) // render old image data to the canvas
					ctx.drawImage(tile.el, 0, 0);

To ressucitate the image from its deltas; we just need to do 'applyDelta' on the tile - with the keyframe, and then any concatenated deltas we have after that I guess. The data & deltas should stay as UInt8Bytes (?) arrays I think.

I imagine TileSection.ts does this the actual rendering of tile.el there (either an image or a canvas), and we prolly want to have some method called before the (various) drawImage calls there to call a helper that de-hydrates it before rendering with applyDelta. Is that do-able ? I expect jamming the arrays onto tile.rawKeyframe, tile.rawDeltas; and appending deltas as they come in (and clearing on a new keyframe) should be reasonably do-able: its normal for JS  to just add members to objects all the time late in the day ;-)

Would be awesome =)
