### ISSUE TITLE
Dark mode button does not trigger reliably in Firefox

### ISSUE THREAD

**Issue by juliushaertl** [CollaboraOnline/online#6431]
The dark mode button does not switch the mode reliably when clicking on the text label, only clicking the icon directly switches the mode.

This seems only an issue on firefox, chromium works as expected

COOLWSD version: m23.05.0.1
git hash:  [5d165648](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/5d165648'));)
LOKit version: Collabora Office 23.05.0.1[e21f2c8](https://hub.libreoffice.org/git-core/e21f2c8)

**Comment by gitgt** [comment]
I do not reproduce this. @juliushaertl can you make a small screencast? maybe try with hard page cache reset?

**Comment by juliushaertl** [comment]
https://github.com/CollaboraOnline/online/assets/3404133/0a50fcab-65c0-4411-9574-c85f255fb816

**Comment by juliushaertl** [comment]
Seems to be fixed already in Collabora Office 23.05.0.3 git hash: 
[7dbb601](javascript:void(window.open('https://hub.libreoffice.org/git-core/7dbb601'));)
