### ISSUE TITLE
Add UI defaults parameter for dark/light mode

### ISSUE THREAD

**Issue by juliushaertl** [CollaboraOnline/online#6432]
It would be great if the integrator could pass the current user option for dark/light mode to the collabora frame.

From the Nextcloud side we have the following different modes
- Browser default
- Forced light / forced dark 
- High contrast option which will apply on top of the above three (could be skipped for the first iteration imo)

My proposal would be to have a ui_defaults values like this to start with:

- UITheme=default -> picks up browser default
- UITheme=light
- UITheme=dark

An additional enhancement would be if the page would already have the `[data-theme="dark"]` set when being delivered from the server which would avoid flickering with the bright theme until the value is set by the JS code.

cc @pedropintosilva since we talked about that already

**Comment by pedropintosilva** [comment]
Thanks @juliushaertl for the heads up. That sounds good.

Last person working around dark-mode JS bits was @Darshan-upadhyay1110 and @eszkadev with https://github.com/CollaboraOnline/online/pull/6356 .

**Comment by juliushaertl** [comment]
I was looking around and ended up preparing a small pull request to implement this with #6436
