### ISSUE TITLE
23.05 Writer: Weird menu items outlook when user switches to Compact View when the dark mode is switched on

### ISSUE THREAD

**Issue by Ezinnem** [CollaboraOnline/online#6434]
**Describe the bug**
The menu items look weird when the user switches to Compact view

**To Reproduce**
1. Open a .odt file
2. When the dark mode is on, Switch to Compact View

See the look
![Screenshot from 2023-05-25 15-22-22](https://github.com/CollaboraOnline/online/assets/54344301/6a26b70a-21fb-4cdb-a96b-8a86c75ca204)

**Expected behavior**
The icons should be visible as in Tabbed View.

**Actual behavior**
The icons should are not visible as in Tabbed View.

**Screenshots**

https://github.com/CollaboraOnline/online/assets/54344301/034a0028-53f7-4cc1-b740-25a7c9891415

**Desktop (please complete the following information)**
 - OS: Linux Ubuntu
 - Browser: Chrome

Phab Link: [T42561](https://phabricator.collabora.com/T42561)

**Comment by Ezinnem** [comment]
@gitgt @pedropintosilva

**Comment by gitgt** [comment]
Ezinne thanks for adding me.
I would clear site cache, Shift+F5 or similar, I also had to do Site Hard Reset once.
Please leave Unconfirmed until clarified.

**Comment by Ezinnem** [comment]
This seems fixed now. as it is no longer reproducible in the recent 23.05 build

**Comment by gitgt** [comment]
This was not reproduced so closing as not planned.
