### ISSUE TITLE
23.05 - Paste from on Writer document to another does not work

### ISSUE THREAD

**Issue by Ezinnem** [CollaboraOnline/online#6438]
**Describe the bug**
Copy and paste from one writer document to another does not work

**To Reproduce**
Open a .odt file (first.odt)
Cope the content
Paste into another .odt file (second.odt)

Notice that the content is not pasted into the second file.

**Expected behavior**
The content should be pasted into the second file.

**Actual behavior**
The content is not pasted into the second file.

**Screenshots**

https://github.com/CollaboraOnline/online/assets/54344301/3c963f20-b50a-4bf9-ae26-6dba69a427de

**Desktop (please complete the following information)**
 - OS: Linux
  - Browser: Chrome
 - Version 23.05

**Comment by gitgt** [comment]
Should be fixed with https://github.com/CollaboraOnline/online/pull/6448.
