### ISSUE TITLE
Dark Theme with light page color setting

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#6449]
as libreoffice has two settings for dark mode
1. dark mode of the UI elemnts
2. dark dokument page color

Can we have two UI elements one for dark mode (as it is now) which change 1. and 2. and a second UI element if the user want to switch 2. So by default dark mode mean 1. and 2. are dark but the user can overrule the dokument page color with light?

#### Office Dark Theme
![image](https://github.com/CollaboraOnline/online/assets/8517736/951185c3-3d47-4721-affb-d85e396c857d)

#### Dark/Light document page color
![image](https://github.com/CollaboraOnline/online/assets/8517736/1808aa0e-fa81-4dae-aceb-b8074036f30b)

I would prefer to have two buttons 
- one toggle for dark theme and 
- one toggle for dark background color

**Comment by Tex2002ans** [comment]
> Can we have two UI elements one for dark mode [...]

Yes. Fully agree.

Separating out the:

- UI + Page Color

for Dark Mode is key.

In [LibreOffice's Bug #153334: "Support/default to a non-white page background in Dark Mode"](https://bugs.documentfoundation.org/show_bug.cgi?id=153334), I wrote:

> Having an easy-to-access "page color" toggle would help, because all 4 options could be taken:
> 
> - Light UI + White Page
> - Light UI + Dark Page
> - Dark UI + White Page
>    - (This is what I prefer most of the time.)
> - Dark UI + Dark Page
> 
> This is especially helpful when dealing with colors + contrast issues.

Automatically turning on a DARK PAGE as well, is just asking for all sorts of color/contrast troubles too.

(Already see black-on-black text or very-dark-text-on-dark-background issues.)

- - -

**Side Note:** Over the years, I've written extensively about this "black-on-black text" problem in ebooks:

- [2020: "Colored Text, EPUB, Android Dark Mode"](https://www.mobileread.com/forums/showthread.php?p=4041908#post4041908)
- [2020: "eBook Formatting in Sigil"](https://www.mobileread.com/forums/showthread.php?p=4040943#post4040943)

and, related:

- [/r/LibreOffice: "Viewing textbook pdfs in dark mode"](https://www.reddit.com/r/libreoffice/comments/yx1iqv/viewing_textbook_pdfs_in_dark_mode/iwn5pvk/)

where I described "Inverting Colors" properly or "Dark Moding" your PDFs. For example, see:

- [IMAGE showing Default/White vs. Inverted vs. YCC-Inverted pages](https://i.ibb.co/dfZ8hsv/Invert-Image-or-Page-Colors-via-YCC.png)

You can look to many of these other projects for:

- inspiration
- \+ warnings of what type of issues/complaints are coming down the pipeline when you flip background colors. :)

**Comment by derei** [comment]
I see the last discussion on this topic is from June 2023, and I wanted to ask if is it possible to have dark theme with white page, or not just yet?
As many others have suggested, white page is a necessity for any document processor. Usually people want to print on paper their documents, and working on a dark page, even if output is reversed, makes it extremely difficult to work with images, charts, colours in general, in an intuitive and predictable manner.

Perhaps from developer perspective this may not seem as an urgent matter, but from user perspective it can easily become a deal breaker, especially in professional environments.

**Comment by Ornanovitch** [comment]
I believe there is a recent PR that solve this: https://github.com/CollaboraOnline/online/pull/8564

Would be nice to see this merged :)

**Comment by derei** [comment]
> I believe there is a recent PR that solve this: #8564
> 
> Would be nice to see this merged :)

I hope it will. I'm not very familiar with the specifics of Collabora code, but judging by that snippet alone, I see no reason why it shouldn't be merged.

**Comment by timur-g** [comment]
This should be resolved in 24.04 with the new View-Invert Background button, that should be seen in Dark mode. 
It still has some bugs, but do you think it is an adequate solution?

**Comment by Ornanovitch** [comment]
Thanks for this update! IMO this could be an adequate solution only if it is off by default (ie it should be an opt-in preference, because it is not standard at all, particularly on the desktop office suites)

**Comment by timur-g** [comment]
Invert Background was improved to remember user choice and to work in different scenarios of collaborative work, so I think this can be closed.
