### ISSUE TITLE
When Disable Macros clicked in Macro Security dialog file does not open

### ISSUE THREAD

**Issue by timur-g** [CollaboraOnline/online#6461]
To reproduce, enable macros by setting security.enable_macros_execution in /etc/coolwsd/coolwsd.xml to true, keep macro_security_level to 1.

Open a macro-enabled document/spreadsheet, eg. the macro.ods from the repo:
    https://github.com/CollaboraOnline/online/blob/master/cypress_test/data/desktop/calc/macro.ods
In the dialog, pick Disable Macros.

Experienced in Online 22.05 and 23.05: file does not open
Expected: file opens with macros disabled.

**Comment by thebearon** [comment]
I'd consider this an enhancement.

**Comment by timur-g** [comment]
Fixed in 24.04.2 and 23.05.11 with  https://github.com/CollaboraOnline/online/pull/8884 and https://github.com/CollaboraOnline/online/pull/8929.
