### ISSUE TITLE
Writer: In Compact View Align Left and Align right has a different icon

### ISSUE THREAD

**Issue by Ezinnem** [CollaboraOnline/online#6472]
**Describe the bug**
 Compact View Align Left and Align right have a different icon.

**To Reproduce**

Open a .odt file
Notice the Align Right and Alighn Left icons in Tabbed

Switch to the Compact view and see that the Align Right and Align Left icons are different

**Expected behavior**
 Align Left and Align right have similar icons in both Compact and Tabbed View

**Actual behavior**
 Align Left and Align right have different icons in both Compact and Tabbed View

**Screenshots**

https://github.com/CollaboraOnline/online/assets/54344301/2f2022f5-1a94-4f74-9637-ba573a164baa

**Desktop (please complete the following information)**
 - OS: iOS
 - Browser: Chrome
 - Version:  23,05
 
Linked in phabricator: [T42621](https://phabricator.collabora.com/T42621)

**Comment by Darshan-upadhyay1110** [comment]
Okay in normal collabora build.
[Screencast from 2024-11-11 18-08-55.webm](https://github.com/user-attachments/assets/494ec280-1086-45e8-97d6-4804d3c9e2ab)

COOLWSD version: 24.04.10.0(git hash: 7751e086c6 (E))
LOKit version: Collabora OfficeDev 24.04.9.1(git hash: b14098b)
Served by: Ubuntu 23.10
Server ID: 7da8a2ef
WOPI host:
