### ISSUE TITLE
23.05: Design bits - Hover and Primary color makes the text not visible

### ISSUE THREAD

**Issue by Ezinnem** [CollaboraOnline/online#6483]
**Describe the bug**
Hover and Primary color makes the text not visible

**To Reproduce**
Open a file
Hover through the menu items.

Notice that the text becomes unreadable as the user hovers

**Expected behavior**
Hover and Primary color makes the text not visible

**Actual behavior**
Text should be visible

**Screenshots**
![Screenshot from 2023-05-31 07-50-36](https://github.com/CollaboraOnline/online/assets/54344301/b5bc2704-c241-4f08-b12c-f4780233bcff)

https://github.com/CollaboraOnline/online/assets/54344301/700f854b-e5e1-4b56-8970-d5427e853561

**Desktop (please complete the following information)**
 - OS: Linux Ubuntu
 - Browser: Chrome
 - Version: 23.05
 
 Phab [link](https://phabricator.collabora.com/T42641)

**Comment by Darshan-upadhyay1110** [comment]
Fixed :tada:
