### ISSUE TITLE
23.05 : Draw - Smart Picker does nothing on Compact view Missing on Tabbed View

### ISSUE THREAD

**Issue by Ezinnem** [CollaboraOnline/online#6489]
**Describe the bug**

**To Reproduce**

1. Open a .odg file
2. In Compcat View; go to Insert > Smark Picker

Notice that clicking on it does nothing

In Tabbed View, the menu item seems to be missing
![Screenshot from 2023-05-31 10-23-30](https://github.com/CollaboraOnline/online/assets/54344301/57059734-e45e-47fa-953e-ccbcc2ebf6d2)

**Comment by GulsahKose** [comment]
I can confirm that Smart Picker does nothing but couldn't find what should it do. Couldn't find corresponding core feature or core menu item to understand. Can you help me to understand?

when i trace the code it triggers following lines
browser/src/control/Toolbar.js-879-             case 'remotelink':
browser/src/control/Toolbar.js:880:                     this.fire('postMessage', { msgId: 'UI_PickLink' });
but couldn't find any listeners for that message.

**Comment by eszkadev** [comment]
UI_PickLink is a postmessage sent to the integrator (Nextcloud). So it should be handled in richdocuments (Nextcloud plugin for Collabora Online: https://github.com/nextcloud/richdocuments)

**Comment by pedropintosilva** [comment]
I think that menu entry should be there when testing it locally. Meaning, it should only be visible if integrator has that funcitonality
