### ISSUE TITLE
Strange validity check for field in dialog

### ISSUE THREAD

**Issue by thebearon** [CollaboraOnline/online#6494]
Then hovering over the width/height field in the Format -> Page Styles dialog in Writer, I see this, not sure why (no such tooltip is shown in LO desktop):

![dialog validity](https://github.com/CollaboraOnline/online/assets/19438782/12cd38f2-76c6-4240-9d92-ef6ad849bb9f)

**Comment by thebearon** [comment]
CC @eszkadev

**Comment by eszkadev** [comment]
This is validation done by the browser, we set for the field min,max and step values.
I think in this case the content doesn't match step. Step in LO is used only to increase/decrease, but here browser requires to round the value...
