### ISSUE TITLE
First character in the line is lost with Japanese input (Firefox-specific) 

### ISSUE THREAD

**Issue by thebearon** [CollaboraOnline/online#6504]
- I switched to Japanese (Mozc) input and Hiragana input mode,
- in an empty document, I started typing `kakakaka` on my keyboard, which should have appeared as `かかかか` and it resulted in `あかかか` instead. (it also showed an input suggestion box for possible variations, I disregarded that as not relevant for the reproducer)

**Comment by Ezinnem** [comment]
Fix on https://github.com/CollaboraOnline/online/commit/9ef29ba5567de8b214d7ea22316b70f75ebe6cba

Tested using COOLWSD version:
22.05.15.2 git hash: [b5924811](https://github.com/CollaboraOnline/online/commits/b5924811)
