### ISSUE TITLE
perf: handling TileQueue more effectively ...

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#6514]
When we get a lot of queued messages and/or tiles - we seem to spend lots of time processing and re-parsing the tiles as we go - which burns time we need to spend doing something useful =)

            |--28.15%--0xffffffffffffffff
            |          |          
            |          |--6.87%--WebSocketHandler::handleTCPStream
            |          |          KitWebSocketHandler::handleMessage
            |          |          |          
            |          |          |--6.83%--MessageQueue::put
            |          |          |          MessageQueue::put
            |          |          |          TileQueue::put_impl
            |          |          |          |          
            |          |          |          |--4.97%--std::remove_if<__gnu_cxx::__normal_iterator<std::vector<char, std::allocator<char> >*, std::vector<std::vector<char, std::allocator<char> >, std::allocator<std::vector<char, std::a
llocator<char> > > > >, TileQueue::put_impl(std::vector<char, std::allocator<char> > const&)::$_0>
            |          |          |          |          std::__remove_if<__gnu_cxx::__normal_iterator<std::vector<char, std::allocator<char> >*, std::vector<std::vector<char, std::allocator<char> >, std::allocator<std::vector<char, std
::allocator<char> > > > >, __gnu_cxx::__ops::_Iter_pred<TileQueue::put_impl(std::vector<char, std::allocator<char> > const&)::$_0> >
            |          |          |          |          std::__find_if<__gnu_cxx::__normal_iterator<std::vector<char, std::allocator<char> >*, std::vector<std::vector<char, std::allocator<char> >, std::allocator<std::vector<char, std::
allocator<char> > > > >, __gnu_cxx::__ops::_Iter_pred<TileQueue::put_impl(std::vector<char, std::allocator<char> > const&)::$_0> >
            |          |          |          |          std::__find_if<__gnu_cxx::__normal_iterator<std::vector<char, std::allocator<char> >*, std::vector<std::vector<char, std::allocator<char> >, std::allocator<std::vector<char, std::
allocator<char> > > > >, __gnu_cxx::__ops::_Iter_pred<TileQueue::put_impl(std::vector<char, std::allocator<char> > const&)::$_0> >
            |          |          |          |          __gnu_cxx::__ops::_Iter_pred<TileQueue::put_impl(std::vector<char, std::allocator<char> > const&)::$_0>::operator()<__gnu_cxx::__normal_iterator<std::vector<char, std::allocator<c
har> >*, std::vector<std::vector<char, std::allocator<char> >, std::allocator<std::vector<char, std::allocator<char> > > > > >
            |          |          |          |          operator() (inlined)
            |          |          |          |          |          
            |          |          |          |          |--4.01%--std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find
            |          |          |          |          |          |          
            |          |          |          |          |          |--3.93%--std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find
            |          |          |          |          |          |          |          
            |          |          |          |          |          |          |--2.11%--std::char_traits<char>::find
            |          |          |          |          |          |          |          |          
...
           |          |          |          |--1.08%--TileQueue::removeTileDuplicate
            |          |          |          |          |          
            |          |          |          |          |--0.33%--std::vector<std::vector<char, std::allocator<char> >, std::allocator<std::vector<char, std::allocator<char> > > >::erase
            |          |          |          |          |          |          
            |          |          |          |          |          |--0.29%--std::vector<std::vector<char, std::allocator<char> >, std::allocator<std::vector<char, std::allocator<char> > > >::_M_erase
            |          |          |          |          |          |          std::move<__gnu_cxx::__normal_iterator<std::vector<char, std::allocator<char> >*, std::vector<std::vector<char, std::allocator<char> >, std::allocator<std::vector<char, std::allocator<char> > > > >, __gnu_cxx::__normal_iterator<std::vector<char, std::allocator<char> >*, std::vector<std::vector<char, std::allocator<char> >, std::allocator<std::vector<char, std::allocator<char> > > > > >
            |          |          |          |          |          |          std::__copy_move_a2<true, __gnu_cxx::__normal_iterator<std::vector<char, std::allocator<char> >*, std::vector<std::vector<char, std::allocator<char> >, std::allocator<std::vector<char, std::allocator<char> > > > >, __gnu_cxx::__normal_iterator<std::vector<char, std::allocator<char> >*, std::vector<std::vector<char, std::allocator<char> >, std::allocator<std::vector<char, std::allocator<char> > > > > >
            |          |          |          |          |          |          std::__copy_move_a<true, std::vector<char, std::allocator<char> >*, std::vector<char, std::allocator<char> >*>
            |          |          |          |          |          |          std::__copy_move<true, false, std::random_access_iterator_tag>::__copy_m<std::vector<char, std::allocator<char> >*, std::vector<char, std::allocator<char> >*>
            |          |          |          |          |          |          |          
            |          |          |          |          |          |           --0.21%--std::vector<char, std::allocator<char> >::operator=
            |          |          |          |          |          |                     |          
            |          |          |          |          |          |                      --0.17%--std::vector<char, std::allocator<char> >::_M_move_assign
            |          |          |          |          |          |                                |          
            |          |          |          |          |          |                                |--0.12%--std::_Vector_base<char, std::allocator<char> >::_Vector_impl::_M_swap_data
            |          |          |          |          |          |                                |          std::swap<char*>
            |          |          |          |          |          |                                |          |          
            |          |          |          |          |          |                                |           --0.04%--std::move<char*&>
            |          |          |          |          |          |                                |          
            |          |          |          |          |          |                                 --0.04%--std::_Vector_base<char, std::allocator<char> >::get_allocator

More details at the bottom of ...  https://github.com/CollaboraOnline/online/files/11634775/perf.txt =)

Thanks

**Comment by caolanm** [comment]
I wonder if that std::remove_if ever gets to actually do anything in practice. I mean, if I get a canceltiles with a seqs of:

...3742,3741,...

the strings "s" tend to be of format

tile nviewid=1000 part=0 width=256 height=256 tileposx=0 tileposy=0 tilewidth=1920 tileheight=1920 oldwid=0 wid=0 ver=3741
tile nviewid=1000 part=0 width=256 height=256 tileposx=1920 tileposy=0 tilewidth=1920 tileheight=1920 oldwid=0 wid=0 ver=3742

so s contains, "nviewid=", "oldwid=" and "wid="

and so

if (s.find("id=") != std::string::npos)
    return false;

happens locally for any s that has a ver=seq_element, so I've yet to see a case that erases a queue entry

**Comment by mmeeks** [comment]
Amusing if in fact it does nothing but waste lots of CPU =)
AFAICS we only ever send a blank 'canceltiles' there is never anything appended to the string from the javascript - from just one call-site:

src/layer/tile/CanvasTileLayer.js:              app.socket.sendMessage('canceltiles');

So   for (size_t i = 0; i < tokens.size(); ++i) - will always have tokens.size() == 0 - and that whole process is a very slow way of returning false I guess =)

Lets kill the canceltiles message entirely for now from the JS and the backend.

I suspect a fair amount of profile distortion by having a completely un-optimized STL - but even so that should be a nice win =)

Thanks !

**Comment by caolanm** [comment]
There is that TileCache::cancelTiles in wsd/TileCache.cpp which does provide a payload. But then there's that find("id=") trap so I feel ends up an expensive noop.

Interestingly, I also see a lot of TileQueue::removeCallbackDuplicate locally if I simulate 25 simultaneous logins with the "Open Multiple URL" extension of https://chrome.google.com/webstore/detail/open-multiple-urls/oifijhaokejakekmnjmphonojcfkpbbh
