### ISSUE TITLE
Canvas tiles color do no change when clicking the dark mode toggle

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#6527]
**Describe the bug**
Background surrounding the documents doesn't change the color when clicking the dark mode toggle

This regression started with 
[--color-main-background CSS variable will be used for canvas backgrou… #6451](https://github.com/CollaboraOnline/online/pull/6451)

**To Reproduce**
1. Open a file
2. change to dark mode by pressing the toggle button under view tab
3. notice the background didn't change to the `-color-main-background` value
4. also noticed that when refreshing the page it this change it correctly

**Mentors**
@gokaysatir 

**CC**
@OFFTKP

**Comment by OFFTKP** [comment]
Note: If you set `useCSSForBackgroundColor` to false, it seems to work as normal last time I tried.

**Comment by Darshan-upadhyay1110** [comment]
Yes i also noticed

**Comment by Darshan-upadhyay1110** [comment]
but if we pass false to every case than that will not work for branding css variables so i am finding more genric way to handle this
