### ISSUE TITLE
Text is getting styled by default with Black colour

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#6546]
# Bug

We are wrongly defaulting to `Black` colour instead of `Automatic` when creating new files. This brakes dark-mode as user ends up with black text on black page.

1. Create a .odt within Nextcloud
2. Type some text
3. Open sidebar
4. Click the style popup icon
5. Navigate to `Font effects` in the Paragraph Style dialog
6. See that `Black` is being used instead of `Automatic`

![image](https://github.com/CollaboraOnline/online/assets/65948705/06d23394-bce9-453a-bd67-a80375091105)

# Where templates are coming

* https://github.com/nextcloud/example-files/pull/28
* https://github.com/nextcloud/richdocuments/tree/main/emptyTemplates

**Comment by caolanm** [comment]
adding a styles.xml with:

```
<office:document-styles xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0">
 <office:styles>
  <style:default-style style:family="paragraph">
   <style:text-properties style:use-window-font-color="true"/>
  </style:default-style>
 </office:styles>
</office:document-styles>
```

might work

**Comment by gokaysatir** [comment]
Updating the template in Nextcloud folder also works.

**Comment by mmeeks** [comment]
@juliushaertl - I was talking to Jan yesterday about templates for Nextcloud-next - we need to review all of those to ensure that they have:
- no language set - so we adopt the default language on load
- use new Theme colors where possible to allow re-theming
- don't use explicit 'Black' style formatting (as original ticket).
How can we best get at and tweak the newly installed Nextcloud templates  =)

Thanks !
