### ISSUE TITLE
Exiting takes too long

### ISSUE THREAD

**Issue by exonas** [CollaboraOnline/online#6559]
When I try to exit the app it takes 3-4 seconds before it exits. What it's doing in background? It shouldn't take that long. I am using google Pixel 7 without GSF

**Comment by mmeeks** [comment]
This should be fixed by: 

commit 25f2581a30cddafb2361f6ee5b0eb6985877121f
Author: Michael Meeks <michael.meeks@collabora.com>
Date:   Fri Jun 9 09:19:36 2023 +0100

    Revert this for now while we think more deeply.
    
    This reverts commit 80b4e6d4ae92445e05eae0206d4dfc25bdff8784.

thanks for reporting =)
