### ISSUE TITLE
Autofilter buttons: keep Autofilter shown pressed

### ISSUE THREAD

**Issue by gitgt** [CollaboraOnline/online#6563]
In Collabora Online, when Autofilter is pressed, it does not show as pressed, which I think should be.
Autofilter can turn on and off filter.  In Libreoffice it stays pressed. 

I am not clear what "Hide Autofilter" buton does then, albeit I also see it in Libreoffice toolbar. Maybe it can be removed
Seen in both 22.05 and 23.05.

**Comment by thebearon** [comment]
Hide Autofilter simply hides the AutoFilter buttons in the cells.
https://help.libreoffice.org/latest/en-US/text/scalc/01/12040500.html

Concerning pressed state of the buttons in LibreOffice, for the record, while it's shown in Windows, it isn't shown in gtk3 under Linux, either. I'm inclined to suggest we shouldn't bother, but it can stay open as an enhancement as well.

**Comment by gitgt** [comment]
Autofilter shows as pressed for a while in Linux. Loosing it after seems a bug. 
![image](https://github.com/CollaboraOnline/online/assets/7240617/beee7760-fbbf-4fcf-b692-b882d30d9403)

**Comment by thebearon** [comment]
I don't see the autofilter menu open in your case, in my interpretation that's the "pressed" state. Could you clarify?

Here's what I see in LibreOffice + gtk3, the autofilter is open, but the button isn't shown pressed.
![autofilter](https://github.com/CollaboraOnline/online/assets/19438782/3f4bcc13-477e-4a6f-afd9-deffd04449c3)

**Comment by thebearon** [comment]
Got it, thanks for clarifying!

**Comment by lpranam** [comment]
fix: https://gerrit.libreoffice.org/c/core/+/153532

**Comment by gitgt** [comment]
Thanks.
