### ISSUE TITLE
Tabbed view: Undo icon in menu row

### ISSUE THREAD

**Issue by gitgt** [CollaboraOnline/online#6568]
In Tabbed view, I would personally like to see Undo icon in menu row, after Save and Open in Local Editor.

**Comment by thebearon** [comment]
That used to be a case, and they were moved to the Home tab intentionally. to make the header row cleaner, and also the buttons larger. If you have further questions or comments, please contact @pedropintosilva.

**Comment by gitgt** [comment]
@pedropintosilva isit possible that this be a setting?
