### ISSUE TITLE
Strange uneditable horizontal lines - what are they?

### ISSUE THREAD

**Issue by LorenAmelang** [CollaboraOnline/online#6573]
**Describe the bug**
In the row of icons below the Compact View Format menu items, I tapped the short horizontal line between the circle “shapes” dropdown and the “insert hyperlink” button. It drew a horizontal line 3.5 columns wide and 1/3 of the way up the row at a random location in the middle of the sheet. Tried again, it drew another one lower and to the right. Maybe this is not a bug, but I asked on the Forum and nobody explained what they are - and I can't select them or delete them. 

**To Reproduce**
![image](https://github.com/CollaboraOnline/online/assets/1297090/47a597af-9edf-4377-b110-1d9c3635eebc)

**Expected behavior**
No idea...  What is that button supposed to do? 

**Actual behavior**
Interesting that the upper one (when I reopen the sheet) is now on the line between 14 and 15… It used to be 1/3 of the way up 14, like the lower one is 1/3 of the way up 32. 

I tried many times to select the lower one, and nothing happened. But I guess I hit just the perfect part of the left end, and got this:

![image](https://github.com/CollaboraOnline/online/assets/1297090/22a9ba25-c13f-4783-a4fe-4735cb9b9de5)

Now there is yet another line, a bit below row 32 and slightly to the left of the previous one:

![image](https://github.com/CollaboraOnline/online/assets/1297090/d5f8f3f2-28da-4be1-a3c1-f888514a8e28)

Is there some way to delete these? If I delete the row they are in, they stay in the same screen position and another row moves up under them.

**Smartphone (please complete the following information)**
 - Device: iPad 12.9 5Gen
 - OS: iOS 16.5

**Additional context**

**Comment by thebearon** [comment]
That is a line shape, ie. exactly what the button shows. You should be able to select it, though you have to be very precise. Ultimately this is the same as #1462.
