### ISSUE TITLE
Shutting down coolwsd takes longer than before

### ISSUE THREAD

**Issue by thebearon** [CollaboraOnline/online#6576]
This primarily concerns devs, who often start online via `make run`.
In the past, coolwsd shutting down after Ctrl-C was almost instantaneous, now it takes a good 5-10 seconds.

This is a regression from 80b4e6d (#6467), which was for #4837.

I noted @pedropintosilva's comment in the PR:
> hm @Ashod I think I'm noticing some performance hit after this got in, could you please re-check this? If so, please revert it or ping me and I will be happy to do so

**Comment by thebearon** [comment]
CC @shehr7 @Ashod @pedropintosilva.

**Comment by shehr7** [comment]
@thebearon  yes it does take longer now. Let me test it after reverting the changes.

**Comment by shehr7** [comment]
@thebearon by removing the link 617 of net/Socket.hpp, the process runs faster. @Ashod should I remove that line?

**Comment by thebearon** [comment]
As I can see this was temporarily reverted in 25f2581a30cddafb2361f6ee5b0eb6985877121f.

**Comment by thebearon** [comment]
Let's close.
