### ISSUE TITLE
Invalid or unknown request.| wsd/COOLWSD.cpp:3953

### ISSUE THREAD

**Issue by dolphinscorp** [CollaboraOnline/online#6583]
Hi Every one,

I have installed NC 26 running on https://mynextcloud.com/ and I have setup collabora on same server with apache reverse proxy. When i put https://collaboradomain/ in my nextcloud office settings its green bullet there seems all fine. but it opens blank document.

Following is the error:

wsd-482327-482352 2023-06-01 18:33:22.257284 +0000 [ websrv_poll ] ERR #25: #25 bad request: [GET /cool/https%3A%2F%[2Fmynextcloud.com](http://2fmynextcloud.com/)%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F1252904_ocpue9o%3Faccess_token%3DdK9rXrV9T6cK54yRZdzm7OSfLHrrAsf6%26access_token_ttl%3D1685680382000%26permission%3Dedit/ws?WOPISrc=https%3A%2F%[2Fmynextcloud.com](http://2fmynextcloud.com/)%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F1252904_ocpquezrqp9o&compat=/ws HTTP/1.1#015…]: Invalid or unknown request.| wsd/COOLWSD.cpp:3953

my apache reverse proxy VH of apache

![image](https://github.com/CollaboraOnline/online/assets/115947558/f53b9760-7263-415f-8882-6a215c925183)

This is Virtual host for nextcloud

![image](https://github.com/CollaboraOnline/online/assets/115947558/760e8ac8-4310-427e-8f58-9d7cfac12bb6)

Further investigating via browser developer mode: Following logs collected

![image](https://github.com/CollaboraOnline/online/assets/115947558/a21237f9-371a-4fca-8c66-3015ece67298)

![image](https://github.com/CollaboraOnline/online/assets/115947558/1dc5bbc2-f535-44e0-94b7-123f9938efcc)

Apparently it is something with reverse proxy configuration. But i could not resolve it. can anybody help on this?

**Comment by dolphinscorp** [comment]
@thebearon

Can you please help in this?

**Comment by Darshan-upadhyay1110** [comment]
Hi @dolphinscorp,  

I've noticed several forum discussions about reverse proxy configuration issues. Many users have shared their experiences and solutions, so it might be worth checking them out:  

[[Collabora Online Forum](https://forum.collaboraonline.com/)](https://forum.collaboraonline.com/)  

Thanks!
