### ISSUE TITLE
"Failed to load Nextcloud Office" if no nickname is set

### ISSUE THREAD

**Issue by meaz** [CollaboraOnline/online#6590]
**Describe the bug**
If an user that got a public link of a shared document doesn't enter the nickname quick enough, I get "Failed to load Nextcloud Office" and it gets back to the page where the user can only download it.

**To Reproduce**
1. Get a public link of a shared document
2. Do not enter a guest nickname  (page says "Please choose your nickname to continue as a guest user.")
3. Wait like 10-15 seconds

**Expected behavior**
The page that says "Please choose your nickname to continue as a guest user." should wait for the nickname, even if the user takes long to enter it.

**Actual behavior**
The page that says "Please choose your nickname to continue as a guest user." is being closed after 10-15 seconds, and a message appears "Failed to load Nextcloud Office" 

**Screenshots**
![Capture d’écran du 2023-06-10 07-09-15](https://github.com/CollaboraOnline/online/assets/13604424/89b1bb41-e124-4681-a34b-5d77560497d7)
![Capture d’écran du 2023-06-10 07-09-29](https://github.com/CollaboraOnline/online/assets/13604424/38033b60-3267-4b4b-b2c9-e9e20416e0a5)

**Desktop (please complete the following information)**
 - OS: Arch
 - Browser: Firefox
 - Version: 114

**Additional context**
The problem I met is more important when you have a slow connection. As it takes time to load the page asking the nick name, the user has only like 5 seconds to enter his/her username...

**Comment by thebearon** [comment]
Looks like https://github.com/nextcloud/richdocuments/issues/2596 to me, closing this issue.
