### ISSUE TITLE
Impress: Wrong context menu in Slides Pane in master view

### ISSUE THREAD

**Issue by lpranam** [CollaboraOnline/online#6613]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @lpranam 

### Detailed description and rationale
There should be no context menu option for master slide previews as of now those options are not yet supported

### Code pointers
https://github.com/CollaboraOnline/online/pull/6529
...

### Links to related documentation
...

### Additional notes, tips & tricks
...

**Comment by codewithvk** [comment]
I'm working on it.
