### ISSUE TITLE
Switching light-dark mode does not immediatelly switch slide background in slide pane

### ISSUE THREAD

**Issue by timur-g** [CollaboraOnline/online#6614]
Switching light-dark mode and vice-versa does not immediatelly switch slide background in slide pane.
Seems to depend on the number of slides.

![image](https://github.com/CollaboraOnline/online/assets/7240617/b721ab87-6c3d-4d45-9f32-30cb863bcc5b)

**Comment by Ezinnem** [comment]
I can confirm on COOLWSD version:
23.05.0.5 git hash: [7bbdf7c5](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/7bbdf7c5'));)(E)

**Comment by gitgt** [comment]
Let me keep here a reproducer.
[Dark mode test.odp](https://github.com/CollaboraOnline/online/files/12002109/Dark.mode.test.odp)

**Comment by OFFTKP** [comment]
#6985 has been merged, please test

**Comment by timur-g** [comment]
Seems instant to me now. Thanks! So it will be in 23.05.3.
