### ISSUE TITLE
Very very slow to start a presentation in the browser

### ISSUE THREAD

**Issue by JMoVS** [CollaboraOnline/online#6616]
**Describe the bug**
I have a presentation I work in, I scroll through the slides, nothing fancy, no transitions etc. Then clicking on the fullscreen button to have it in presentation mode, it regularly takes 20seconds to 1 minute (!) before the presentation appears. In the meantime only a spinner appears!

**To Reproduce**
1. Work in a presentation
2. click the fullscreen present mode button
3. wait for 20s or more with a spinner

**Expected behavior**
When I already work in the file, I expect a behaviour similar to onlyoffice. When it's already loaded, it should never take more than 5 seconds, ideally less than 2 seconds to switch to fullscreen presentation mode in the browser

**Actual behavior**
20s to 60s delay(I measured it, loading the file took 5, starting the presentation took 60 seconds!)

**Screenshots**
Loading screen
<img width="1440" alt="grafik" src="https://github.com/CollaboraOnline/online/assets/7354506/1e858abe-272e-4848-818d-4e0fa2161a2f">

**Desktop (please complete the following information)**
 - OS: MacOS
 - Browser: Firefox
 - Version: 23.05.0.5.1 and 22.05

**Additional context**
If you need specific logs or details, please let me know

**Comment by gitgt** [comment]
In my test time to run 1st slide was 10 secs, but regardless there is a room for improvement, thanks for filling this.

**Comment by JMoVS** [comment]
well 10sec for 1 slide is I would argue 100x too slow :D Really not sure what the architecture is that it takes that long. It makes it infeasible to use whenin calls. I can't wait for 60 seconds before I see my presentation on screen to start screensharing in a 30minute call. :D

**Comment by JMoVS** [comment]
Also affects 23.05

**Comment by caolanm** [comment]
@timur-g Is there a concrete example to look at for the 10 seconds to see 1st slide issue?

**Comment by timur-g** [comment]
@caolanm, Partner Council prez I counted to 10 but when I measure is it loads in 8 secs both 2205 and 2305, still feels slow.
 It has 59 slides, but I slow start may be due to template used. 

Note: that one also has:
 libpng warning: iCCP: CRC error
debug:435144:435082: Swap in: 0x0(Error Area:Io Class:NONE Code:0)

**Comment by caolanm** [comment]
Given the example timur provided then the above has an excessive amount of BitmapEx::GetChecksum which we can elide for the common case with: https://gerrit.libreoffice.org/c/core/+/155706
Which then gives a flamegraph of:
![reduce-checksums](https://github.com/CollaboraOnline/online/assets/833656/491c4c5a-0220-481a-98f6-e2d55c94bb86)
which for me brings the time from 3.8 seconds to 2.8

**Comment by caolanm** [comment]
Sometimes I find under chome that a second attempt to run a full-screen presentation will appear to hang permanently. https://github.com/CollaboraOnline/online/issues/7102 for that problem and a plausible fix.

**Comment by timur-g** [comment]
> Given the example timur provided then the above has an excessive amount of BitmapEx::GetChecksum which we can elide for the common case with: https://gerrit.libreoffice.org/c/core/+/155706 ...  which for me brings the time from 3.8 seconds to 2.8

With stopwatch (previous 10 secs was approximate), time went down for me from 8 secs to 7 secs. So, definite iimprovement.

**Comment by JMoVS** [comment]
I have a sample that takes around 1 minute to present, can I send that to you in private @timur-g ?

**Comment by timur-g** [comment]
@JMoVS Yes, for test. I will see the time, and if that can be anonymized,

**Comment by JMoVS** [comment]
@timur-g are you still present on matrix?

**Comment by timur-g** [comment]
No. You may send to timur @ libreoffice . org.

**Comment by timur-g** [comment]
PPTX is 51 slides rich with images. 1st slide loads for me in 17 secs in 22.05.18 and in 16 secs in 23.05.

**Comment by JMoVS** [comment]
I think if possible architecturally the time to load the first slide should be decoupled from how large the presentation is (I'm saying this being fully aware that is an armchair generals comment, so please forgive me if it was already clear :) )

**Comment by timur-g** [comment]
Really speeding this up is a large chunk of work so it would not be a bug but an enhancement.
What can be done here as a bug is at least having progress bar.

**Comment by JMoVS** [comment]
@timur-g Okay, indeed, a progress bar would already help to understand where one is. 

BTW Nitpicky details: The loading circle is a bit "egging" (rotating unround) while it's rotating :D

**Comment by timur-g** [comment]
Slideshow rework is being done, now presentation starts fast regardless of it's size. 
Not sure when it will be in release, hopefully soon after some testing and fixing issues found.
