### ISSUE TITLE
collaboraoffice download as pdf from LXC whithout jail chroot

### ISSUE THREAD

**Issue by Jorgepastorr** [CollaboraOnline/online#6620]
**Describe the bug**
(I'm sorry my bad English I'm trying to fix)
Nextcloud CollaboraOffice can't download as PDF from document ODT

I use: 
- debian bullseye 
- collaboraoffice:  22.05.14-4             
- coolwsd:  22.05.14.3-1  
- apache2:  2.4.56-1
- PHP: 7.4.33
- nextcloud: 25.0.2
- richdocuments:  7.1.3
- LXC  unprivileged container

*Config coolwsd without jail*

I use coolwsd without jail chroot because I know problems from LXC unprivileged containers can't create jails with mknod

```
<capabilities desc="Should we require capabilities to isolate processes into chroot jails" type="bool" default="true">false</capabilities>
```

**To Reproduce**
1. into Nextcloud 
2. open some file *.odt with collaboraoffice
3. file -> download as -> pdf

**log coolwsd**

```
  Jun 14 10:43:54 nextcloud-ng coolwsd[219912]: wsd-219912-1756404 2023-06-14 10:43:54.517036 +0000 [ docbroker_b38 ] WRN  Empty download: [id: OUggYNeWXqgAIyhT4K0eitNxPJBniCzkzuuN7Yx4XapKdlazFheAyl2lQ5w6RBHE, url: ../../cool/child-roots/7Li3AVTte4CQQZRj/tmp/user/docs/7Li3AVTte4CQQZRj/About.pdf].| wsd/DocumentBroker.cpp:2898
  Jun 14 10:43:54 nextcloud-ng coolwsd[219912]: wsd-219912-219924 2023-06-14 10:43:54.574459 +0000 [ websrv_poll ] ERR  #55: Download file [/opt/cool/child-roots/7Li3AVTte4CQQZRj/tmp/cool/child-roots/7Li3AVTte4CQQZRj/tmp/user/docs/7Li3AVTte4CQQZRj/About.pdf] not found.| wsd/COOLWSD.cpp:4687

```

The problem is coolwsd try to download file PDF from `/opt/cool/child-roots/7Li3AVTte4CQQZRj/tmp/cool/child-roots/7Li3AVTte4CQQZRj/tmp/user/docs/7Li3AVTte4CQQZRj/About.pdf` and this path not exist, you can see path `tmp/cool/child-roots/7Li3AVTte4CQQZRj` It's duplicate then It causes the failure.

The rigth path is `/opt/cool/child-roots/7Li3AVTte4CQQZRj/tmp/user/docs/7Li3AVTte4CQQZRj/About.pdf`

**Comment by Darshan-upadhyay1110** [comment]
Works with 24.04

COOLWSD version: 24.04.10.0(git hash: 7751e086c6 (E))
LOKit version: Collabora OfficeDev 24.04.9.1(git hash: b14098b)
Served by: Ubuntu 23.10
Server ID: 17a39d58
WOPI host:
