### ISSUE TITLE
Middle-Clicking Stuck Cursor

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#6630]
### Describe the bug

Middle-Clicking in a document gets cursor "stuck" as 2- or 4-pointed cross instead of normal mouse cursor.

### To Reproduce

1. Middle-click in Writer document.
2. Move mouse, then Left-Click or Right-Click.

- - -

**Side Note:** Can't scroll or navigate document either by:

- Middle-Click
- \+Moving your mouse up or down.

Only spinning mouse wheel scrolls document up or down.

- - -

### Expected behavior

Left-Click or Right-Click in document returns mouse cursor to normal.

### Actual behavior

After Middle-Click, the mouse cursor turns into:

- the 4-pointed cross

but you can't go back to the:

- normal mouse cursor

even after Left-Clicking or Right-Clicking.

Only way to get cursor back is refresh entire tab.

### Screenshots

![Middle Click vs Normal Cursor](https://github.com/CollaboraOnline/online/assets/5774324/8c055f36-188d-4845-a7fb-35775c3c72d9)

- Left = Middle scroll icon
- Right = Normal mouse icon.)

### Desktop

- **OS:** Windows 10
- **Browser:** Chrome: Version 114.0.5735.111 (Official Build) (64-bit)
- **Version:**

```
COOLWSD version:
23.05.0.5
git hash: (39be94e8(E))

LOKit version:
built on a great technology base
Collabora Office 23.05.0.5 (git hash: 80a8c48)
Served by: openSUSE Leap 15.3 ba674e43
```

**Comment by Ezinnem** [comment]
I do not see this issue using COOLWSD version:
23.05.0.5 git hash: [7bbdf7c5](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/7bbdf7c5'));)

Please can you test again @Tex2002ans.

Please feel free to share a screen recording of the issue you encounter.

**Comment by Tex2002ans** [comment]
This initially occurred during the COOL Weekly Meeting the previous two weeks. (Did not test it during this week's meeting.)

- - -

I went to retest on my local version of COOL:

```
COOLWSD version:
23.05.0.1 git hash: (012b00d6)
LOKit version:
Collabora Office 23.05.0.1 git hash: (bc5c5de)
Served by: Linux Mint 21.1 e92b9d33
```

And I COULD NOT reproduce in:

- Firefox 114.0.2+linuxmint1+victoria

When I Middle-Clicked:

- I could not get the scroll to appear.

Instead:

- Firefox/COOL pasted text into the document.
   - (Middle-Click is a very common shortcut in Linux systems to quickly copy/paste your recently highlighted text.)

- - -

Strange. Very strange.

Maybe it's a Chrome vs. Firefox + OS-dependent issue.

- - -

> Please feel free to share a screen recording of the issue you encounter.

Next time it occurs, I'll definitely take some screenshots. I'll probably have a status update next Thursday. :)

The symptoms though are:

- That middle-click, round, 4-cross-looking icon just stayed stuck.
- If I hovered mouse over the document's page, the icon appeared "stuck".
   - It would not scroll document up or down.
- If I moved mouse over the top bar / menus, the mouse cursor appeared normal.

Clicking anywhere in the document ACTED as if it was a normal mouse cursor, but it was much tougher to precisely press a location because you didn't have the pointy end. (You had the circle-cross-icon instead!)

**Comment by timur-g** [comment]
Let us close until reproducible.

**Comment by Tex2002ans** [comment]
> Let us close until reproducible.

Agree. Looks like it doesn't occur anymore in:

> COOLWSD version: 23.05.6.4 (git hash: 7c440409)
> LOKit version: Collabora Office 23.05.6.4 (git hash: e03b031)
> Served by: Linux Mint 21.1
> Server ID: 0b5bf1dc

On Windows 10 + Chrome:

- A middle-click doesn't change the cursor at all.

On Linux Mint + Firefox:

- No cursor change either.
- Middle-click = a paste.

so everything looks to be working.
