### ISSUE TITLE
Delete key doesn't remove text when accessibility is disabled (Firefox-specific)

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#6631]
New regressions (it seems)

Problem: I couldn't use the Delete key to remove text

Note: 
- it was experienced during the community call, using an odt: https://staging.eu.collaboraonline.com/nextcloud/index.php/s/A5LSYX8j2ezM6gg
- Multiple users could reproduce it (but it seems not all)
  -  @nikslor could reproduce it
  - I could reproduce it
  - @mmeeks couldn't
- Staging head was on online 39be94e8525aac5b97458d8f7a2e97b390399e8e
- Also nothing strange seemed to pop up in the web console
- Neither when the triple click was enabled (saw blue flashing invalidation but I don't think it was related to these)

**Comment by pedropintosilva** [comment]
Initially I though this could have been related to accessibility patches. But I have re-tested locally and I'm able to use the delete key. Maybe it would be worth it to know if accessibility was turned on

**Comment by mcecchetti** [comment]
Afaics accessibility is not turned on for the document on staging.eu.
In fact, at least for me, the ui is the compact one, so top commit (when the issue occurred) https://github.com/CollaboraOnline/online/commit/39be94e8525aac5b97458d8f7a2e97b390399e8e should not make any difference

**Comment by mmeeks** [comment]
FYI - I'm not hyper-happy to have two implementations of the most complex code we have in Online to test & debug - and then the uncertainty of which one we're using =)
AFAIK there is no real reason why we should need two - we can use the contenteditable just fine for both - and if no new state from the server comes; we can still diff as we used to surely - just wiping it on enter being pressed or arrow keys ? ...
There are hundreds of lines of duplication between the two of these - are they necessary ? I'd like to post-haste remove one of them to kill the maintenance disaster area =)

Can you look at that Marco ?

**Comment by simmstein** [comment]
Same problem in my side (Firefox 114 on Debian and on Windows) in my self hosted instance (`coolwsd/ 23.05.0.5-1 amd64`).

**Comment by thebearon** [comment]
This issue only occurs when using Firefox, and started with d01bedc09cbc6f7089db4db1cf7349ca6c46e282.

**Comment by pedropintosilva** [comment]
@mcecchetti ^

**Comment by mcecchetti** [comment]
@thebearon @pedropintosilva yep I confirm that the problem occurs only on Firefox when accessibility is disabled (and after  d01bedc is disabled by default)
I appended it to my todo list. As a temporary workaround you can enable accessibility in coolwsd.xml.

**Comment by mcecchetti** [comment]
The problem should have been fixed as part of PR: https://github.com/CollaboraOnline/online/pull/6862

**Comment by thebearon** [comment]
Looks good to me, let's consider it fixed, thanks Marco!
