### ISSUE TITLE
Format > Paragraph preview cropped

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#6652]
![Cropped preview](https://github.com/CollaboraOnline/online/assets/65948705/a38fbf20-63bd-421d-b2ab-ea41d73f7b46)

**Comment by Darshan-upadhyay1110** [comment]
COOLWSD version: 24.04.10.1(git hash: dc930ffa6d)
LOKit version: Collabora OfficeDev 24.04.10.1(git hash: 8b2330d)
Served by: Ubuntu 23.10
Server ID: e0c3f2e4
WOPI host:
