### ISSUE TITLE
Download as PDF does not work for read-only documents

### ISSUE THREAD

**Issue by oreinert** [CollaboraOnline/online#6653]
**Describe the bug**
Trying to download a read-only document as a PDF does not work.

**To Reproduce**
1. On my Nextcloud server, I navigate to a Group Folder in which I only have read-only access, and I open a .docx document.
2. Click the "Datei" menu, then "Herunterladen als", then "PDF-Dokument (.pdf)".

**Expected behavior**
After steps 1 and 2 above:
3. A dialog "PDF-Optionen" pops up, allowing me to select various export options.
4. Pressing the "Exportieren" button in the dialog downloads the PDF.

**Actual behavior**
After step 1 and 2 above, nothing happens (except that the menu disappears, of course).

**Screenshots**
none

**Desktop (please complete the following information)**
 - openSUSE Tumbleweed 20230617
 - Browser: Firefox
 - Version: 114.0.1

** Server (please complete the following information)**
 - openSUSE Leap 15.5
 - apache: 2.4.51
 - php: 8.0.28
 - Nextcloud: 25.0.7
 - COOLWSD Version:
22.05.15.2 git hash: 
[458afd2](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/458afd2'));)
(E)
 - Collabora Office 23.05.0.5 git hash: 
[8b92c8b](javascript:void(window.open('https://hub.libreoffice.org/git-core/8b92c8b'));)
 - Angeboten von: openSUSE Leap 15.5 
[4afaf261](https://cloud.test.avellana.ch/hosting/discovery)

**Additional context**
Granting the user write permission to the Group Folder containing the document makes the PDF download work as expected.

**Comment by Ezinnem** [comment]
I can confirm this report.
