### ISSUE TITLE
Text field for renaming a document actually clones the file and leaves collaborators in old file

### ISSUE THREAD

**Issue by johanfrej** [CollaboraOnline/online#6656]
**Describe the bug**
I'm using CollaboraOnline from OwnCloud (ocis). When I use the text field in the tool bar to rename a document that I'm editing it will create a copy of the file instead of renaming the file. The copy is saved in the same folder as the original file. What makes this problem quite big in this context is that any collaborator that has access to the same file will stay in the original file, while I move on to the copy of the file. This essentially forks the document without anyone noticing it. 

**To Reproduce**

In OwnCloud: Go to this text field and rename the document:

<img width="550" alt="image" src="https://github.com/CollaboraOnline/online/assets/6659436/5756582a-1db5-4919-b52b-ee5b0ba7004e">

Go to the folder that contains the file and see how a copy has been created instead of the file being renamed. 

<img width="283" alt="image" src="https://github.com/CollaboraOnline/online/assets/6659436/2a81da9a-9636-48b3-bb2f-c554376733b9">

**Expected behavior**

The original file should have been renamed

**Actual behavior**

A copy with the new name was created. Collaborators still only have access to old file. 

**Screenshots**
See above

**Desktop (please complete the following information)**
 - OS: MacOS Ventura 13.2.1
 - Browser: Chrome
 - Version: 114.0.5735.106 (Official Build) (arm64)

**Smartphone (please complete the following information)**
 -

**Additional context**

Tested in oCIS - ownCloud Infinite Scale

Someone with more knowledge on this technology stack proposed to me: ... this could be difficult. Collabora puts a lock on the file while editing it. You cannot rename a locked file. In this case it would always be a "Copy&Delete". ownCloud never deletes an old file version. So it does a "Copy to new location"

If this could not be solved, may I propose that the text filed for renaming the file is removed from the UI, or could be removed by configuration (maybe it can?). For collaboration this is really dangerous.

**Comment by Ezinnem** [comment]
I can confirm this report

**Comment by Darshan-upadhyay1110** [comment]
COOLWSD version: 24.04.10.1(git hash: dc930ffa6d)
LOKit version: Collabora OfficeDev 24.04.10.1(git hash: 8b2330d)
Served by: Ubuntu 23.10
Server ID: e0c3f2e4
WOPI host:
