### ISSUE TITLE
No Tooltips on "Big" Buttons in Tabbed UI

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#6699]
### Describe the bug
When hovering mouse over some buttons, no tooltip shows.

### To Reproduce

In Writer:

1. Go to "Layout" tab.
2. Hover mouse over all the buttons.

![Collabora Office 23 05 - Layout Tab - No Tooltips](https://github.com/CollaboraOnline/online/assets/5774324/1264644b-7f4d-4743-9852-93a1bf67df4a)

- Tooltip DOES NOT appear on the "big" buttons.
   - Choose any on the left-side, like "Page" + "Page Break".
- Tooltip only appears on the "little" buttons.
   - Choose any on the right-side, like "Left" + "Centered" + "Right".

### Expected behavior
Tooltips show, just like with the "small" buttons.

### Actual behavior
Tooltips DO NOT show.

### Desktop
 - **OS:** Windows 10
 - **Browser:** Chrome
 - **Version:** 114.0.5735.134 (Official Build) (64-bit)

```
COOLWSD version:
23.05.0.5 (git hash: bdf29a53(E))
LOKit version:
built on a great technology base
Collabora Office 23.05.0.5 (git hash: 8afe5d3)
Served by: openSUSE Leap 15.5 63a8b4cf
```

### Additional context

Right now, it feels a little inconsistent that some buttons tooltip, others don't:

- In Compact View, all the buttons are little, so hovering shows all tooltips.
- But when you're in Tabbed UI, you get this half-show + half-don't.

This may also be an Accessibility(?) issue. Unsure how this interacts with:

- Press+Holding on mobile
- Text-to-Speech (JAWS/NVDA) reading buttons out loud
   - (Unsure if tooltip text = ARIA text?)

**Comment by pedropintosilva** [comment]
Thanks for reporting.

>    In Compact View, all the buttons are little, so hovering shows all tooltips.

This is independent of their size. We display a tooltip when they don't have a text label 

>    But when you're in Tabbed UI, you get this half-show + half-don't.

Well we do have buttons with text and without text. For the ones without text we do display a tooltip.
For the buttons compound by icon and text we don't.
  * We could add tooltips to those... but I would refrain from just add a tooltip that is a copy of the text already visible in the first place. For example: having a tooltip `Select All` on top of a button that has already a label `Select All` seems unproductive.


> While a tooltip can be placed on any content, they generally are tips for tools or controls, such as providing additional content for icons that have brief labels (or no labels at all, which is not accessible!).
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tooltip_Role

So I think we get that covered. All buttons have (if not we should add) labels be that within their own elements (and already visible) or via labels that appear via tooltips.


And to answer your question "(Unsure if tooltip text = ARIA text?)" 
> The use of the ARIA tooltip role is a supplement to the normal browser tooltip behavior. An example of a native browser tooltip is the way some browsers display an element's [title attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title)

**Comment by gitgt** [comment]
This seems like a NotABug so I close.
