### ISSUE TITLE
Calc: Formula bar doesnt accept euro-sign

### ISSUE THREAD

**Issue by relikd** [CollaboraOnline/online#6737]
**Describe the bug**
I can type a euro-sign (€) in a **cell** but not in the **formulae bar**.
Inserting the character with copy & paste works. Could be a macOS only issue.

**To Reproduce**
1. Click on the formula bar
2. Type alt+E to insert euro-sign

**Expected behavior**
"€"

**Actual behavior**
""

**Screenshots**
N/A

**Desktop (please complete the following information)**
 - OS: macOS
 - Browser: Firefox
 - Version: v22.05.14.3 

**Smartphone (please complete the following information)**
N/A

**Additional context**
N/A

**Comment by eszkadev** [comment]
Fix merged, should be fine now :)

**Comment by thebearon** [comment]
@eszkadev Can you please note the 23.05 fix as well?

**Comment by relikd** [comment]
does not seem to be fixed in 23.05.1.3
