### ISSUE TITLE
Calc: Extend range not updating formula with display scaling (like 150%) 

### ISSUE THREAD

**Issue by relikd** [CollaboraOnline/online#6738]
**Describe the bug**
Lets say I have three cells, A1: 1, A2: 2, A3: 3.
I want to select those three cells and extend the selection up to cell A10. I would expect Calc to automatically insert 4, 5, ..., 10.
Instead, Calc cancles the previous selection and instead starts a new selection with B4 as the new first cell.

**To Reproduce**
1. Select Cell(s)
2. Try to extend selection with the blue dot in the lower right corner

**Expected behavior**
Auto-increment new cells

**Actual behavior**
Starts a new selection

**Screenshots**

https://github.com/CollaboraOnline/online/assets/1321720/92635b72-b104-4dd8-a34d-d98e8332f886

**Desktop (please complete the following information)**
 - OS: macOS
 - Browser: Firefox + Chrome
 - Version: v22.05.14.3

**Smartphone (please complete the following information)**
N/A

**Additional context**
N/A

**Comment by Ezinnem** [comment]
It works fine on my end.

I tested using:

OS: Linux Ubuntu
Browser: Firefox and Chrome
COOLWSD version:
22.05.16.1 git hash: [ddf59bf](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/ddf59bf'));)

https://github.com/CollaboraOnline/online/assets/54344301/5bdf3b0f-1ff8-48af-8e53-a361cdefad1a

**Comment by relikd** [comment]
Is there something else I can test? I cant test with 22.05.16.1 because it is not on docker hub. I also tried to restart the container which didnt help either. Changing to compact mode also doesnt do anything different.

I can see that for you it changes to the purple selection mode, indicating that it changed to cell expansion. But that mode doesnt get triggered for me. Selection stays blue and starts a new selection.

**Comment by gitgt** [comment]
@relikd  There is a known bug when using 4K monitor with 150% scaling, is that your case? That is with Online 100%, not 150%.

**Comment by relikd** [comment]
I've tested this on Firefox, Chrome, and Safari. None of these browsers work (with Mac). Tested on another Mac (Firefox, Chrome, Safari) – same result. I am fairly certain this is no Browser / OS configuration issue.

**Comment by caolanm** [comment]
I believe this works now in trunk with https://github.com/CollaboraOnline/online/pull/7048 merged
