### ISSUE TITLE
The character count is a thousand times too small for a document with more than a million characters

### ISSUE THREAD

**Issue by tml1024** [CollaboraOnline/online#675]
Load the attached document into Collabora Online.

The bottom row says:

> Page 1 of 276 | 175,321 words, 1,227 characters

which obviously is nonsense, there can't be less than one character per word. The correct number of characters is 1,227,197, so it gets divided by 1000 for some reason.
[Foo.docx](https://github.com/CollaboraOnline/online/files/5553227/Foo.docx)

**Comment by Rash419** [comment]
how to load document ? there is no "open" sub-option in "file" option.

**Comment by tml1024** [comment]
@Rash419 How are you able to have loleaflet.html open without any document being open?

**Comment by thebearon** [comment]
@Rash419, what @tml1024 is referring to, if you run Collabora Online using `make run`, you can see a few hello world samples listed in the following format:
`http(s)://localhost:9980/loleaflet/<hash>/loleaflet.html?file_path=file:///<path>/<file_name+extension>`

You can open any document on your computer with the same patter.

**Comment by Rash419** [comment]
> @Rash419, what @tml1024 is referring to, if you run Collabora Online using `make run`, you can see a few hello world samples listed in the following format:
> `http(s)://localhost:9980/loleaflet/<hash>/loleaflet.html?file_path=file:///<path>/<file_name+extension>`
> 
> You can open any document on your computer with the same pattern.


Thank you , this is what I was asking for

**Comment by 22shubh22** [comment]
Code pointers will be appreciated.

**Comment by Rash419** [comment]
> Code pointers will be appreciated.

After execution of toLocalPattern function of loleaflet/src/control/Control.StatusBar.js  , number of character changes and this function is called by  onCommandStateChanged function ( line number 491).

`			text = pattern.toLocaleString().replace(sub1, parseInt(matches[1].replace(',','')).toLocaleString(String.locale)).replace(sub2, parseInt(matches[2].replace(',','')).toLocaleString(String.locale));`
 
after this specific line of toLocalPattern function number of character changes
