### ISSUE TITLE
Option to access admin console without password

### ISSUE THREAD

**Issue by schklom** [CollaboraOnline/online#6752]
**Is your feature request related to a problem? Please describe.**
I would like to access the admin console (e.g. https://collabora.mydomain/browser/dist/admin/admin.html) without requiring a password.
I prefer 2FA securing https://collabora.mydomain/browser/dist/admin/... behind a dedicated service like Authelia / Authentik.

**Describe the solution you'd like**
An Docker environment variable like `DONT_REQUIRE_CREDENTIALS_ADMIN: true` or a CLI flag like `--no-credentials`.

**Comment by timur-g** [comment]
Duplicate of #5051.
