### ISSUE TITLE
Opening PDF + Switching Apps = "Document cannot be saved" Screen

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#6774]
### Describe the Bug

On Android, every time you:

- Open a PDF in Collabora Office.
- **Swap apps**
- then return to Collabora...

you get an annoying "Document cannot be saved" screen. You have to press "OK" to dismiss every time.

### Steps To Reproduce

1. Open a PDF.
2. Swipe (or use OS button) to switch to another app.
3. Switch back to Collabora Office.

### Expected Behavior

PDF or last page you were on to just appear in viewing mode.

### Actual Behavior

"Document cannot be saved." + OK button screen appears.

You have to:

- Press OK

to return to viewing your PDF every time.

### Screenshots

This was first reported by [Adibuyono in the Collabora forum](https://forum.collaboraonline.com/t/opening-pdf-and-switch-back-to-collabora-apps-warning/1395):

<img src="https://github.com/CollaboraOnline/online/assets/5774324/375553bd-420c-4419-bd7a-e9d6ee1ee479" alt="Collabora Office - Android 21 11 6 1 - PDF Document cannot be saved popup" width="30%" height="30%">

It's their screenshot, but I was able to reproduce exactly the same popup on my end too.

### Version Info

I tested this on Android 11:

> COOLWSD version
> 21.11.6.1
> git hash: 6706dd45
> 
> LOKit version:
> built on a great technology base
> Collabora Office 21.06.32.1
> git hash: e211b5b

### Additional Context

(Maybe the same on iOS too? So it may be a broader mobile OS popup/window?)

**Comment by Ezinnem** [comment]
confirm this

**Comment by Darshan-upadhyay1110** [comment]
COOLWSD version: 24.04.10.1(git hash: dc930ffa6d)
LOKit version: Collabora OfficeDev 24.04.10.1(git hash: 8b2330d)
Served by: Ubuntu 23.10
Server ID: eab785be
WOPI host:
