### ISSUE TITLE
Customize tab not available in Bullets and Numbering dialog

### ISSUE THREAD

**Issue by Rash419** [CollaboraOnline/online#6777]
**Describe the bug**
Customize tab not available in Bullets and Numbering dialog

**To Reproduce**
1. On tabbed view: Format -> Bullets and Numbering

**Expected behavior**
There should a Customize tab like it is available in LibreOffice
![image](https://github.com/CollaboraOnline/online/assets/26241069/6211089e-dfb1-4a1e-ac5d-733128873f31)

**Actual behavior**
Customize tab is not available
![image](https://github.com/CollaboraOnline/online/assets/26241069/62a3085a-f0b5-47a6-8985-bfaf875de347)

**Screenshots**

**Desktop (please complete the following information)**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information)**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**
It was disabled long ago by this patch: https://gerrit.libreoffice.org/c/core/+/79811

**Comment by pedropintosilva** [comment]
@Minion3665 would you like to work on this?

**Comment by Minion3665** [comment]
> @Minion3665 would you like to work on this?

That sounds good! A first step might be to see what happens if we build without that patch nowadays, let me do that

**Comment by Minion3665** [comment]
I've made a gerrit change for this issue here: https://gerrit.libreoffice.org/c/core/+/153806

**Comment by thebearon** [comment]
The tab was hidden to work around this bug:
https://bugs.documentfoundation.org/show_bug.cgi?id=118198

**Comment by Minion3665** [comment]
> The tab was hidden to work around this bug: [bugs.documentfoundation.org/show_bug.cgi?id=118198](https://bugs.documentfoundation.org/show_bug.cgi?id=118198)

thanks for the heads-up, don't quite know how I missed that!

on closer inspection, it seems that pressing either ok or cancel twice closes the dialog as well... I'll take a look and see if I can fix that in my gerrit change too

**Comment by Minion3665** [comment]
The customize tab was re-shown in https://gerrit.libreoffice.org/c/core/+/151188, I've made another issue (#7006) to fix the issue described in https://bugs.documentfoundation.org/show_bug.cgi?id=118198

**Comment by Minion3665** [comment]
https://gerrit.libreoffice.org/c/core/+/153806 was merged yesterday , this is now really done!
