### ISSUE TITLE
hyperlink dialog on chrome

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#6795]
**Describe the bug**
Dialog looks horrible on chrome

![image](https://github.com/CollaboraOnline/online/assets/65948705/324e1bb7-9eba-4371-8ca4-bcbd53730060)

Expected: should look like the same as in FF

**Comment by Darshan-upadhyay1110** [comment]
@pedropintosilva  This seems fixed i am not seeing this design error in local so we can close this issue as fixed 
![image](https://github.com/CollaboraOnline/online/assets/61383886/34de0d81-57a8-4fc7-8af3-8306e751d21b)

**Comment by pedropintosilva** [comment]
ah so it's still weird

**Comment by pedropintosilva** [comment]
the text input field should be full width

**Comment by Darshan-upadhyay1110** [comment]
oh okay i know this one. i think i will add my soultion here for this
