### ISSUE TITLE
Excel table color not shown and dark mode problem

### ISSUE THREAD

**Issue by mr-manuel** [CollaboraOnline/online#6797]
**Describe the bug**
The colors of a table created in Microsoft Excel are not shown in the Collabora Online web version. Additionally in dark mode the cell background is displayed black, but the font not white. The problem is on all devices the same. Tested with Windows PC, iPad and Samsung Smartphone.

**To Reproduce**
1. Create a new Excel document
2. Create a table with colors
3. Open the document in the Collabora Online editor

**Expected behavior**
The colors should be shown correctly for the tables.
The font color in dark mode should be white, if the background is switched to dark.

**Actual behavior**
The colors are not shown

**Screenshots**

### Microsoft Excel
![grafik](https://github.com/CollaboraOnline/online/assets/12592765/fd5cd674-2c07-43af-a533-c52450572c78)

### Collabora Online - Light mode
![grafik](https://github.com/CollaboraOnline/online/assets/12592765/225f65be-1268-40b3-b33d-43a3f03be0ed)

### Collabora Online - Dark mode
![grafik](https://github.com/CollaboraOnline/online/assets/12592765/33f4eb6b-c334-4914-bc74-b75eac0f8f10)

**Desktop (please complete the following information)**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 114.0.2

**Tablet (please complete the following information)**
 - Device: iPad Pro 11" 2020
 - OS: iOS 16.5.1
 - Browser: Nextcloud App
 - Version: 4.8.3

**Smartphone (please complete the following information)**
 - Device: Samsung Galaxy S20+
 - OS: Android 12
 - Browser: Nextcloud
 - Version: 3.25.0

**Additional context**
Test document: [Test.xlsx](https://github.com/CollaboraOnline/online/files/11916633/Test.xlsx)

![grafik](https://github.com/CollaboraOnline/online/assets/12592765/9bf66c48-b726-451f-8a2e-5351bda43d7a)

**Comment by thebearon** [comment]
Something curious, the black color (instead of automatic) is set with the table style in Excel, I wonder how that handles such colors in dark mode.

**Comment by mr-manuel** [comment]
Normally a dark mode handles also the colors, if they are specifically set and convert them from light to dark/dark to light.
