### ISSUE TITLE
Ensure consistent function declaration

### ISSUE THREAD

**Issue by mrkara** [CollaboraOnline/online#68]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @kendy 

Some of the functions use declaration like:

```
blah: function blah(huh) {
    ...
}
```

Instead, we want it to be:

```
blah: function(huh) {
    ...
}
```

without the repeated function name. To find the occurrences of this, you can do:

git grep ': function [^(]+(' loleaflet/src/

**Comment by asi309** [comment]
I can fix this issue. Please assign me

**Comment by kandarppatel28** [comment]
Hi @mrkara I can fix this issue.

**Comment by kandarppatel28** [comment]
Hi @mrkara please review the PR, lets me know if there are any changes required

**Comment by kandarppatel28** [comment]
Hi @mrkara please review the PR and let me know if any changes are required

**Comment by kendy** [comment]
@kandarppatel28: Great stuff there, thank you!

Can you please update the patch that you have pushed to include the Change-Id:?  To do that, you need to do:

cp .git/hooks/commit-msg .git/hooks/commit-msg # this installs the hook to add the Change-Id
git commit --amend # to update the commit miessage; on save, the hook will add the Change-Id

We will merge it then.  After that, you can remove more such occurrences, use the following to find more:

git grep ': function [^(]\+(' loleaflet/src/

**Comment by kandarppatel28** [comment]
Hi @kendy ,thank you, I followed your guidelines and updated the patch and pushed it as well.

I have found out all the occurrence and resolved them, also checked if anyone left with "git grep ': function [^(]+(' loleaflet/src/"

**Comment by mrkara** [comment]
@kandarppatel28 Thank you again for your contribution! Let's close this issue, then.

Btw, we are looking forward to your next pull request. ;)
