### ISSUE TITLE
Calc : format page dialog box overlaps with sparklines drop down options

### ISSUE THREAD

**Issue by Darshan-upadhyay1110** [CollaboraOnline/online#6805]
**Describe the bug**

**To Reproduce**
1. Open .ods document
2. Click on `Format`
3. Then click on `sparklines` option and move cursor to format page and click
4. We can see drop down does not closed

**Expected behavior**
Sparklines drop down should be closed 

**Actual behavior**
Sparklines drop down remains open.

**Screenshots**

[Drop-down-not-closed-29-06-23 06:29:45 PM .webm](https://github.com/CollaboraOnline/online/assets/61383886/d8d7c895-b9f9-46c5-a835-384e67d33f1b)

**Comment by Ezinnem** [comment]
When a user clicks elsewhere, the Sparkline dropdown will close.

https://github.com/CollaboraOnline/online/assets/54344301/044f1a28-db95-4208-8d7d-f5f322cc623f

Tested on:
COOLWSD version: 23.05.2.2 (git hash: [61376360](https://github.com/CollaboraOnline/online/commits/61376360) (E))
LOKit version: Collabora Office 23.05.2.3 (git hash: [934d43c](https://git.libreoffice.org/core/+log/934d43c))
