### ISSUE TITLE
ppt file open failure 

### ISSUE THREAD

**Issue by marzaha** [CollaboraOnline/online#6810]
apk file:  collabora-office-mobile-23.05-snapshot-arm64-v8a-2023-07-04.apk

download url:  https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/

https://github.com/CollaboraOnline/online/assets/23233015/b3bb6983-1662-47d1-a309-a9bf2f1129e2

**Comment by gitgt** [comment]
To nbe sure if the problem is just with Andoid, plese try to open the same PPT in desktop Collabora Office 23.05 snapshot.

**Comment by timur-g** [comment]
Recently was fixed a bug of not opening any ODP. 
Still present is a bug of not opening slide with white background. 
Please retest with multiple files.

**Comment by timur-g** [comment]
No response, so I close. If you can attach trouble PPT, feel free to reopen. PPT files can be open, that is probaby that file issue.
