### ISSUE TITLE
per_document.max_concurrency doesn't work

### ISSUE THREAD

**Issue by templier2** [CollaboraOnline/online#6820]
**Describe the bug**
I have deployed two collabora servers. One has max_concurrency=5, another=2. But I don't see any difference between them. I took 3 users and tried to open a shared folder. All three users were able to work with it.

**To Reproduce**
1. Install Collabora Office.
2. Configure integration through nextcloud office app.
3. Set any value (for example, max_concurrency=1).
4. Test opening file with several users.

**Expected behavior**
I expect that with "max_concurrency=1" second user will get an error while accessing the same shared document.

**Actual behavior**
There isn't limitation, several users can edit the same document.

**Screenshots**

**Desktop (please complete the following information)**
 - OS: Windows 10
 - Browser: Chrome(114.0.5735.199) and Edge (114.0.1823.67)
 - Version:

**Comment by thebearon** [comment]
As the description of the configuration item says: `The maximum number of threads to use while processing a document.`
This has nothing to do with the number of users accessing a document, it is a purely technical setting.
