### ISSUE TITLE
Navigator Sidebar: Headings Do Not Update Nesting Instantly

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#6834]
### Describe the Bug

If Navigator is opened, and you update the heading's level inside the document, the sidebar's nesting level is not updated until you close/reopen sidebar.

### Expected Behavior

After pressing `Ctrl+2` in Step 3, the Navigator sidebar should instantly update.

### Actual Behavior

After Step 3, you have to Step 4 (close/open sidebar). Then it updates nesting.

### Steps to Reproduce

1. Open attached sample document:
   - [Hello.World[4.Levels.of.Headings].odt](https://github.com/CollaboraOnline/online/files/11965075/Hello.World.4.Levels.of.Headings.odt)

2. **View > Navigator**

- - -

![Collabora 23 05 0 - Navigator Sidebar Before](https://github.com/CollaboraOnline/online/assets/5774324/341f7ac8-eacf-439d-b408-87cb26dd47db)

Notice headings in sidebar:

- Testing 1
   - Testing 2
      - Testing 3
	     - Testing 4 `<--- SEE HERE`

- - -

3. Inside document:

- Click on the 4th heading:
   - "Testing 4"
- Press `Ctrl+2` = Set to Heading 2

- - -

**BUG:** In the document... The 4th heading:

- Testing 4

turns into a Heading 2.

But the Navigator still shows it at nested Level 4.

- - -

4. Then:

- **View > Navigator** to close the Navigator.
- **View > Navigator** to open the Navigator.

Now, the sidebar updates and shows the proper nesting:

- Testing 1
   - Testing 2
      - Testing 3
   - Testing 4

![Collabora 23 05 0 - Navigator Sidebar After](https://github.com/CollaboraOnline/online/assets/5774324/89bab1c0-358b-4a1f-b04f-b53842fbe431)

### Desktop
 - OS: Linux Mint 21.1
 - Browser: Firefox
 - Version: 114.0.2 (64-bit)
 
> COOLWSD version: 23.05.1.2 (git hash: 6f34565a)
> LOKit version: Collabora Office 23.05.1.2 (git hash: 9a20ef2)
> Served by: Linux Mint 21.1
> Server ID: c150413d

### Additional context

**Edit:** I first tested on an older version of 23.05.0, so screenshots are old. Updated to today's master, and it's still the same issue (just that 23.05 master looks nicer!).

And another note:

- The indentation of each level seems HUGE inside the Navigator.

Instead of having such an extreme indent, maybe that can be halved?

    Heading 1
       Heading 2
           Heading 3
		  
vs. current: 

    Heading 1
	       Heading 2
                  Heading 3

**Comment by lpranam** [comment]
fix: https://gerrit.libreoffice.org/c/core/+/156239

**Comment by timur-g** [comment]
Thanks Pranam.
