### ISSUE TITLE
"Dark Mode" Button Jumps to "Home" Tab

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#6835]
### Describe the Bug

If you are in the "View" Tab and press the:

- "Dark Mode" button

Collabora Online jumps from:

- "View" Tab -> "Home" Tab

### Expected Behavior

After **Dark Mode** button is clicked, stay on "View" Tab.

### Actual Behavior

After **Dark Mode** button is clicked, UI turns Dark (or Light) and jumps to "Home" tab.

### Steps to Reproduce

1. Open document.
2. Go to "View" tab.
3. Press "Dark Mode" button.

### Desktop
 - OS: Linux Mint 21.1
 - Browser: Firefox
 - Version: 114.0.2 (64-bit)
 
> COOLWSD version: 23.05.1.2 (git hash: 6f34565a)
> LOKit version: Collabora Office 23.05.1.2 (git hash: 9a20ef2)
> Served by: Linux Mint 21.1
> Server ID: c150413d

### Additional context

N/A

**Comment by gitgt** [comment]
True.. Not sure if this is on purpose and why but so far can be considered a low priority bug. @pedropintosilva please see.
