### ISSUE TITLE
Page Color Doesn't Update After Pressing "Dark Mode" Button Multiple Times

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#6837]
### Describe the Bug

If you are in the "View" Tab and press the:

- "Dark Mode" button

**1 time**, then:

- UI and Page Color turns Dark.

Press the "Dark Mode" button 2 or 3 more times, and UI updates correct, but you sometimes get:

- Light UI / **Dark Page Color**
- Dark UI / **Light Page Color**

### Steps to Reproduce

1. Open any document.
2. Go to "View" tab.
3. Press "Dark Mode" button multiple times.

### Expected Behavior

"Dark Mode" and "Light Mode" to stay in sync with user choice:

- Dark/Dark
- Light/Light

### Actual Behavior

Depending on how many times Dark Mode is clicked, you can get mismatched.

### Desktop
 - OS: Linux Mint 21.1
 - Browser: Firefox
 - Version: 114.0.2 (64-bit)
 
> COOLWSD version: 23.05.1.2 (git hash: 6f34565a)
> LOKit version: Collabora Office 23.05.1.2 (git hash: 9a20ef2)
> Served by: Linux Mint 21.1
> Server ID: c150413d

### Additional context

Things get even crazier if you scroll up/down the document.

If you stay in place, you usually get a full White/Dark page.

But if you scroll up/down, you can get partial or "striped" White/Dark pages:

![Collabora 23 05 1 - Dark Mode On and Off Bug](https://github.com/CollaboraOnline/online/assets/5774324/66b8b07d-101f-4073-b1c7-3eb9026d2229)

**Comment by Andreas-Kainz** [comment]
at least I added different icons for dark/light mode toggle at #6887 so it's not so "easy" to click that often.

**Comment by Ezinnem** [comment]
Please can you test again @Andreas-Kainz 

It does not seem reproducible in:
COOLWSD version:
23.05.2.2snapshot git hash:  [c9e7591](https://github.com/CollaboraOnline/online/commits/c9e7591)

**Comment by Ezinnem** [comment]
Closing this issue a it may have been fixed.

Please feel free to post comment if you encounter the issue again.

**Comment by Tex2002ans** [comment]
I think the Light/Dark UI vs. Page mismatch is better.

It's much tougher for me to accomplish this in COOL, so it definitely seems like there's been serious movement in the right direction (or maybe I was just not retesting on a complex enough document?).

- - -

But with that "striping" issue...

I was able to reproduce in latest COOL Weekly Meeting.

Here's the image + the triple-click debug info:

![Collabora 23 05 3 - Dark Mode White Tiles Bug 1](https://github.com/CollaboraOnline/online/assets/5774324/fcb4cbfd-1940-4903-a956-440d126e66e9)
![Collabora 23 05 3 - Dark Mode White Tiles Bug 1 Debug](https://github.com/CollaboraOnline/online/assets/5774324/cad9f2c8-318f-4624-b9ac-761d629eb5e3)

> COOLWSD version: 23.05.3.1 (git hash: 0621aa48 (E))
> LOKit version: Collabora Office 23.05.3.1 (git hash: aaeaa1f)
> Served by: openSUSE Leap 15.5
> Server ID: 81c7e7e1

I mostly just did mixes of:

- "Dark Mode" button
- Scroll slightly
- "Dark Mode" button
- Scroll slightly

Sometimes it even happened on 1 click of "Dark Mode", but I definitely got it to occur on 2+.

**Comment by Darshan-upadhyay1110** [comment]
The transition between dark mode and light mode has significantly improved over time. Given the current stable state, I propose closing this issue.

COOLWSD version: 24.04.5.1 (git hash: 1ecf31df)
LOKit version: Collabora OfficeDev 24.04.5.1 (git hash: e1cfc65)
Served by: Ubuntu 23.10
Server ID: 7a9ed233
