### ISSUE TITLE
Spellcheck dialog has small fonts size

### ISSUE THREAD

**Issue by gitgt** [CollaboraOnline/online#6839]
Spellcheck dialog in Online has small fonts size.
Regression from:
commit 08a7a5b2060a05ca2685b5127f991d524e7fe54d
Author: Pranam Lashkari <lpranam@collabora.com>
Date:   Thu Jun 22 00:36:49 2023 +0700
    jsdialog: fixed dialog content being cut off
    i.e: theme dialog(format->theme)
    Signed-off-by: Pranam Lashkari <lpranam@collabora.com>
    Change-Id: I9a09d52cd2c0d95cfae18ae12995761985d8111d

![image](https://github.com/CollaboraOnline/online/assets/7240617/8d9121a0-d5b2-4d67-8229-b7c319a31c4e)
(background is another issue)

@lpranam please see

**Comment by Andreas-Kainz** [comment]
I can have a look also for the other css stuff at this dialogue

**Comment by gitgt** [comment]
Small size will be fixed in 23.05.2.
There is a dark mode aspect here but it is Core issue so will be dealt with separately, hopefully for 23.05.3.
