### ISSUE TITLE
coolwsd.xml get overwritten on updates

### ISSUE THREAD

**Issue by gstlouisgit** [CollaboraOnline/online#6844]
**Describe the bug**
I have a working copy of CODE in which I have several domains that can use this with alias_groups as mode groups with several of the following

`<group>
        <host allow="true" desc="hostname to allow or deny.">https://domain.ca</host>
</group>`

All those domains are working and can use it.  However, every time CODE needs to be updated, this files gets overwritten.  I assume coolwsd.xml is subject to overwrites for update purposes

Lucky I learned my lesson and keep a copy of this.  But it is not practical.  There must be a solution out there I just can't find?

For instance, fail2ban has a jail.local file that is not subject to overwrites.  Is there such a thing for this?

COOLWSD version:
23.05.1.2
git hash: 
[a708901]

**Comment by gitgt** [comment]
Never happend to me. Overwrite is controlled by Operating System, not CODE.
Which OS is yours, what is your command for upgrade?

**Comment by gstlouisgit** [comment]
that's weird?
I am using a debian VM.  I use virtualmin that provide the apt upgrades.  I could try by the console next time, but since they are both using the same package manager, I do not think this will make a difference.

**Comment by thebearon** [comment]
@gstlouisgit my experience is that the updater asks if you want to keep your changed config or have it overwritten when you install the packages. Which distro and package manager are you using?

**Comment by timur-g** [comment]
He explained before that itz is virtualmin and I explained that it is configurable whethet to overwrite or not.

**Comment by gstlouisgit** [comment]
ok so I had to do updates for all sorts of packages.  It has overwritten my coolwsd.xml file and this time I have found in the change logs the following:

Setting up coolwsd (23.05.2.2-1) ...
Installing new version of config file /etc/coolwsd/coolkitconfig.xcu ...

Configuration file '/etc/coolwsd/coolwsd.xml'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** coolwsd.xml (Y/I/N/O/D/Z) [default=N] ? Installing new version of config file /etc/coolwsd/coolwsd.xml ...

This must be what @timur-g is referring to.  I run the updates using virtualmin, so I am going to assume virtualmin chose this option for me, which was not the default N because we can see it says "Installing new version".

I am going to share this with the virtualmin team and share the outcome.
