### ISSUE TITLE
Menubutton should have disabled state styling different

### ISSUE THREAD

**Issue by eszkadev** [CollaboraOnline/online#6877]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @pedropintosilva 

### Detailed description and rationale
"Menu button" widget (button with dropdown) should have disabled state handled in CSS so user will know that it is disabled.

### Code pointers
Example dialog to test: Writer -> Review -> Manage Changes
[disabled-menubutton-2023-07-11_13.40.41.webm](https://github.com/CollaboraOnline/online/assets/5307369/cf906acc-4339-41db-9571-f21609dc5ee4)

**Comment by codewithvk** [comment]
Can i work on it?

**Comment by eszkadev** [comment]
@codewithvk sure :)

**Comment by Harsh8055** [comment]
@codewithvk you working on it?

**Comment by codewithvk** [comment]
@Harsh8055 Yes.
