### ISSUE TITLE
Build failure on Libreoffice 7.5.4

### ISSUE THREAD

**Issue by hillwoodroc** [CollaboraOnline/online#6881]
[   22s] kit/ChildSession.cpp:3243:10: error: 'LOK_CALLBACK_DOCUMENT_PASSWORD_RESET' was not declared in this scope; did you mean 'LOK_CALLBACK_DOCUMENT_PASSWORD'?
[   22s]  3243 |     case LOK_CALLBACK_DOCUMENT_PASSWORD_RESET:
[   22s]       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   22s]       |          LOK_CALLBACK_DOCUMENT_PASSWORD
[   23s] kit/Kit.cpp: In static member function 'static void Document::ViewCallback(int, const char*, void*)':
[   23s] kit/Kit.cpp:1083:26: error: 'LOK_CALLBACK_DOCUMENT_PASSWORD_RESET' was not declared in this scope; did you mean 'LOK_CALLBACK_DOCUMENT_PASSWORD'?
[   23s]  1083 |         else if (type == LOK_CALLBACK_DOCUMENT_PASSWORD_RESET)
[   23s]       |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   23s]       |                          LOK_CALLBACK_DOCUMENT_PASSWORD
[   23s] kit/Kit.cpp: In member function 'std::shared_ptr<lok::Document> Document::load(const std::shared_ptr<ChildSession>&, const std::string&)':
[   23s] kit/Kit.cpp:1573:25: error: 'using std::__shared_ptr_access<lok::Document, __gnu_cxx::_S_atomic, false, false>::element_type = class lok::Document' {aka 'class lok::Document'} has no member named 'setViewTimezone'
[   23s]  1573 |         _loKitDocument->setViewTimezone(viewId, userTimezone.c_str());
[   23s]       |                         ^~~~~~~~~~~~~~~
[   23s]   CXX      common/TraceEvent.o
[   24s]   CXX      common/SigUtil.o
[   24s]   CXX      common/SpookyV2.o
[   24s]   CXX      common/Unit.o
[   24s] make[2]: *** [Makefile:2754: kit/ChildSession.o] Error 1
[   24s] make[2]: *** Waiting for unfinished jobs....
[   25s] make[2]: *** [Makefile:2754: kit/Kit.o] Error 1

**Comment by gitgt** [comment]
Please explain, what exactly are you building and how and why is this Collabora Online bug, if you build  on Libreoffice?

**Comment by thebearon** [comment]
For the record, current master branch of online can be built against core branch `distro/collabora/co-23.05`.
Keep pulling and rebuilding that when updating your online build.
