### ISSUE TITLE
"Format > Paragraph" Diagrams Are Extremely Large

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#6890]
### Describe the Bug

See the HUGE diagrams in Collabora Online 23.05.1:

<img src="https://github.com/CollaboraOnline/online/assets/5774324/f9752cea-532c-459c-928a-8935edf27f0f" width="45%" height="45%">
<img src="https://github.com/CollaboraOnline/online/assets/5774324/74205a21-3a8f-4d7e-9d0d-640dc7310663" width="45%" height="45%">

compared to the same menus in Collabora Office 23.05.1:

<img src="https://github.com/CollaboraOnline/online/assets/5774324/c4a1773e-9085-4e52-ac0f-f93d76c025ae" width="45%" height="45%">
<img src="https://github.com/CollaboraOnline/online/assets/5774324/e12b3a5a-c4e8-4a05-9ca0-998c6577b5dd" width="45%" height="45%">

### Steps to Reproduce

1. Go to the "Format" tab.

2. Press "Paragraph" button.

3. Then, go to the 2 tabs:

- Indents & Spacing
- Drop Caps

See diagrams along right-hand side of menu.

### Expected Behavior

"Normal" sized diagrams showing you the "simulated" indentation/dropcap settings.

### Actual Behavior

HUGE diagrams which look very fuzzy/upscaled.

(Also looks like the big images are "cut off" below the bottom of the menus too. Once they're resized, it should be okay, but maybe keep that in mind for future submenus.)

### Desktop

> COOLWSD version: 23.05.1.2 (git hash: 6f34565a)
> LOKit version: Collabora Office 23.05.1.2 (git hash: 9a20ef2)
> Served by: Linux Mint 21.1
> Server ID: ab0fb16d

and:

> Version: 23.05.1.20230712 (X86_64)
> Build ID: 0f9ebefd27eb7fbef951a960d9821ca646af3dda
> CPU threads: 4; OS: Linux 5.15; UI render: default; VCL: gtk3
> Locale: en-US (en_US.UTF-8); UI: en-US
> Calc: threaded

**Comment by timur-g** [comment]
Thanks. New dialogs are still WIP for tweaks.
Please check with 23.05.2 (already available in repo-staging, release in couple of days).

**Comment by timur-g** [comment]
Let me close this based on how it looks now. Should you experience again, please explain and test in diff. browsers.
