### ISSUE TITLE
calc performance - getting tiled rendering area

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#6894]
The profile we just took shows that 
![perf-23 05-calc](https://github.com/CollaboraOnline/online/assets/122848/2343d66d-88a6-44c3-b445-4c953af8e40f)

ScModelObj::paintTile consumes a huge amount of its time in 'GetTiledRenderingArea' - which is completely swamping the actual rendering:

![image](https://github.com/CollaboraOnline/online/assets/122848/d3829095-5c03-450f-8357-3a7b1f07ca79)

And should clearly not be done on each paintTile =)

Thanks.

**Comment by eszkadev** [comment]
I can confirm that this takes significant % of my profiles. I have some idea, we do caching for similar function: getting last cell with content in the table. I will try to cache also print area.

**Comment by mmeeks** [comment]
Nice =) it is partly because of 16k columns there I think.
quite possibly instead of using:     bool bHasPrintArea = GetPrintArea(nTab, rEndCol, rEndRow, false);
We could consider GetCellArea which may be faster.
Quite possibly Pedro's sheet is problematic because it uses only one column - so it has '0' rEndCol which may be an issue specific to this one.

Anyhow - glad to have you on that. Caching would be great; knowing when to invaliate that may be harder - but probably on an LOK_INVALIDATE callback or a sheet size changed method (I think we have that too ;-) - would mean we could do this easily in the LOK impl. somehow (?)

Thanks Szymon !

**Comment by eszkadev** [comment]
Yes, I cached GetCellArea in the past so it's faster and does the same.
Patch: https://gerrit.libreoffice.org/c/core/+/154437

**Comment by eszkadev** [comment]
Before:
![calc](https://github.com/CollaboraOnline/online/assets/5307369/9c2e0b06-b22a-4279-90e4-e4e35d419fa0)

After:
![calc-after](https://github.com/CollaboraOnline/online/assets/5307369/c308effe-dfb9-49c2-927a-864ef97ed6cd)

**Comment by mmeeks** [comment]
merged =)
