### ISSUE TITLE
23.05.1 Translate errors on staging, removes text

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#6898]
## Translate removes text

**To Reproduce**
1. Select text
2. Go to Review tab
3. Translate button
4. Select target language
5. Original text gets removed

## Screencast

https://github.com/CollaboraOnline/online/assets/65948705/8f6ebdef-53dd-4f6d-bcf9-539e24b51571

## Web Browser console
```javascript
14:59:32.060 cannot get focus for widget: "combobox1" Control.JSDialog.js:371:12
    addHandlers Control.JSDialog.js:371
    onJSDialog Control.JSDialog.js:574
    fire Events.js:152
    _onJSDialog Socket.js:1487
    _onMessage Socket.js:1176
    _emitSlurpedEvents Socket.js:346
    _slurpTimer Socket.js:296
    (Async: setTimeout handler)
    _queueSlurpEventEmission Socket.js:294
    _slurpMessage Socket.js:394

```
```javascript
14:59:39.887 [document] Received post message  
Object { msgId: "Doc_ModifiedStatus", args: {…}, deprecated: false }
document.js:360

14:59:39.887 PostMessageService.sendPostMessage parent {"MessageId":"Doc_ModifiedStatus","SendTime":1689253179885,"Values":{"Modified":true}} postMessage.tsx:52

14:59:39.887 [document] Unhandled post message 
Object { msgId: "Doc_ModifiedStatus", args: {…}, deprecated: false }
document.js:491

14:59:39.887 [document] Unhandled post message 
Object { msgId: "Doc_ModifiedStatus", args: {…}, deprecated: false }
document.js:491

```

## Version
COOLWSD version: 23.05.1.2 (git hash: 4c3be855 (E))
LOKit version: Collabora Office 23.05.1.2 (git hash: 272de6e)
Served by: openSUSE Leap 15.5
Server ID: 79edb2a9

**Comment by pedropintosilva** [comment]
Works locally on #81bfaee859d3057aaee743ddc56dcfac7aca0746

**Comment by pedropintosilva** [comment]
pull, it still works with the latest master on 4c3be8555f1b1cea5b3d28bd7d1a8616a6465799 so probably it's a staging.eu config problem

**Comment by thebearon** [comment]
This has been OK, right? Let's close.
