### ISSUE TITLE
More dynamic Style panel in the Notebookbar

### ISSUE THREAD

**Issue by mrkara** [CollaboraOnline/online#69]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @lpranam 

Switch the UI to using Notebookbar (in loolwsd.xml).

The style panel in notebookbar can be made more dynamic if we apply a style (show selected) with js/css (of course the remaining things can be kept untouched just overlap it with css). Style is applied to text almost instantly but in notebookbar it takes a few seconds to appear.

![Screenshot_20201002_155959 (1)](https://user-images.githubusercontent.com/24812220/94916243-f4640580-04cb-11eb-87b5-c4a33c038939.png)

Steps:
1. Select some text
2. Apply any style from the highlighted panel in the image

See the style is applied to the text is almost immediately but in the UI it takes a few seconds to reflect. We can speed this up if on click we apply some css on that panel.

Hint:
you can inspect the element and see how we are applying some style on that panel on hover and do something similar when clicked.

**Comment by DarkknightAK** [comment]
I'm not a big fan of this previews, but if you can reuse them in an native style sidebar, it would be great.

**Comment by lpranam** [comment]
Before we introduce these changes into online a little work is needed into the core. So temporary closing the issue so someone does not waste time.
