### ISSUE TITLE
Toolbar icons have low visibility in docx files when Darkmode is enabled.

### ISSUE THREAD

**Issue by Darkmatter1111** [CollaboraOnline/online#6902]
![image](https://github.com/CollaboraOnline/online/assets/4325539/33161875-c58b-4147-ba47-c069033100e6)
Could we please have the icons be white or some other color that contrasts well with the dark grey background.
Nextcloud version 26.0.2
Here are my theme settings
![image](https://github.com/CollaboraOnline/online/assets/4325539/4e40960c-4992-4d58-8f10-7a1d619c26fc)
![image](https://github.com/CollaboraOnline/online/assets/4325539/50c62fc5-1cd2-4e6d-b2aa-d96ee8f5dc37)

**Comment by thebearon** [comment]
Please share which version you're using.

**Comment by Darkmatter1111** [comment]
> Please share which version you're using.

My apologizes Nextcloud version 26.0.2

**Comment by gitgt** [comment]
No repro in latest Online 23.05.1, even with High Constrast Mode. 
![image](https://github.com/CollaboraOnline/online/assets/7240617/679b0163-848a-4596-9411-d1eb4e2a72f9)
Please update to NC 27 which is offered as stable. 
And write your exact Online version.

**Comment by Andreas-Kainz** [comment]
Dark mode icon change will work at collabora online so no open issue here.
