### ISSUE TITLE
Calc: Export to PDF popup sometimes doesn't get keyboard focus

### ISSUE THREAD

**Issue by JMoVS** [CollaboraOnline/online#6916]
**Describe the bug**
The "export as PDF" function pops up a small window where one is supposed to be able to adjust the name of the file, however sometimes even when clicking on the text, the text input focus will instead be on the document itself and modify the document

**To Reproduce**
1. Click "export as PDF"
2. Try to adjust the name in the popup (sometimes)
3. Text gets entered in the document behind the popup instead

**Expected behavior**
Adjusting the name of the document

**Actual behavior**
Document content gets modified

**Screenshots**

**Desktop (please complete the following information)**
 - OS: macOS
 - Browser: Brave, Firefox

COOLWSD Version:
23.05.1.3 git hash: 
[10deb70](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/10deb70'));)
(E)

**Additional context**

**Comment by Ezinnem** [comment]
This does not seem reproducible on my end.

I tested on:
COOLWSD version:
23.05.2.2 git hash: [61376360](https://github.com/CollaboraOnline/online/commits/61376360)(E)

Browser: Chrome
OS: Linux Ubuntu


@JMoVS Please can you test again using an updated version?

**Comment by JMoVS** [comment]
I haven't noticed it in a while either
