### ISSUE TITLE
Writer: Selecting words via double-click is unreliable

### ISSUE THREAD

**Issue by JMoVS** [CollaboraOnline/online#6917]
**Describe the bug**
Users expect to be able to double click on a word to select it, it sometimes works, sometimes doesn't

**To Reproduce**
1. Double click on a word
2. sometimes it selects, sometimes it doesn't

**Expected behavior**
Double clicking on a word should always select it

**Actual behavior**
Sometimes double clicking on a word doesn't select it

**Screenshots**

**Desktop (please complete the following information)**
- OS: macOS
- Browser: Firefox, macOS

**Additional context**

**Comment by thebearon** [comment]
I think this is #6833, so let me close as duplicate, if it isn't fixed with the next update, please reopen or open a new issue.

**Comment by JMoVS** [comment]
when is the release you mention scheduled? Should it land in a CODE docker build in the next few days?
