### ISSUE TITLE
Writer: Indenting doesn't work in a numbered list with multiple items

### ISSUE THREAD

**Issue by JMoVS** [CollaboraOnline/online#6920]
**Describe the bug**
If one inserts a new item at the top of a numbered list at least one level in, it is impossible to indent it to a sub level

**To Reproduce**
1. Create a writer document
2. create a numbered list
3. create a sub item
4. create more sub items on the same sub item level
5. Now try to create a new 1st item of the sub item list
6. try to indent the 2nd item
7. it will change the numbering but not indent

**Expected behavior**
Indent further

**Actual behavior**
No indentation

**Screenshots**

**Desktop (please complete the following information)**
 - OS: macOS
 - Browser: Firefox

**Additional context**
COOLWSD Version:
23.05.1.3 git hash: 
[10deb70](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/10deb70'));)
(E)
LOKit Version:
built on 
[a great technology base](javascript:void(window.open('http://col.la/lot'));)
Collabora Office 23.05.1.2 git hash: 
[cc6b8db](javascript:void(window.open('https://hub.libreoffice.org/git-core/cc6b8db'));)
Angeboten von: Debian GNU/Linux 12 (bookworm) 
[d76e69f3](https://office.phelas.com/hosting/discovery)

**Comment by Ezinnem** [comment]
Please can you test again using an updated version?

It is not reproducible for me on:
COOLWSD version: 23.05.2.2 (git hash: [42df0dac](https://github.com/CollaboraOnline/online/commits/42df0dac) (E))
LOKit version: Collabora Office 23.05.2.3 (git hash: [20fb8a5](https://git.libreoffice.org/core/+log/20fb8a5))

Please feel free to attach a screen-recording or a sample file of it is still reproducible.

**Comment by JMoVS** [comment]
cannot reproduce on latest version anymore
