### ISSUE TITLE
Tools > Language > * > More... Does not work

### ISSUE THREAD

**Issue by memand** [CollaboraOnline/online#6923]
**Describe the bug**
It will not let us change the language of the spell checker by going to the menu **Tools > Language > which ever menu point > More...**

**To Reproduce**
1. Go to 'Tools > Language > which ever menu point >'
2. Click on 'More...'
3. Scroll down to 'Language of choice'
4. Noting changes

**Expected behavior**
I would expect that when I choose a language f.eks. under the menu point 'All text' that the spellchecker language gets changed for 'All text'

**Actual behavior**
It does not change the language, but stays at the previously chosen language.

**Screenshots**
Tell me if you need them...

**Desktop (please complete the following information)**
 - OS: Arch x86_64
 - Browser: Firefox
 - Firefox Version: 115.0.2 (64-bit)
 - COOL version: 23.05.1.2

**System**
Univention Corporate Server 5.0-4 errata740

**Comment by gitgt** [comment]
I do not reproduce. can you please make a screencast, start with clicking thru paragraphs so that Status Bar language is seen,then change and click again in some to again see Status Bar.
