### ISSUE TITLE
Up and down arrow keys should move focus up/down a level

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#6933]
## Description
Not possible to use Up/Down arrow to navigate in between tab and tab's content.

### Mentors:
@Minion3665 

## To reproduce
1. `make run`
2. Switch to tabbed view if not already ( on the compact view: view > tabbed view)
3. Press `Alt` (chrome based browsers) or `Shift + Alt` (FF, etc)
4. AccessKey hints will appear
5. Press 'N' to switch to 'Insert' tab
6. Press `Down` arrow key
7. Focus outline appears surrounding one of that tab's buttons
8. Now press 'Up' arrow key
9. Nothing happens

It should move the focus back to the upper level: Active Tab.

Example: a pressed down arrow key when the focus is in the "Home" tab moves the focus to the first item inside of that tab

## Code pointer
Part of the solution may reside between these lines:
* https://github.com/CollaboraOnline/online/blob/1d7be47f0356b4a4d2b302c28c531551237bc86a/browser/src/control/Control.JSDialogBuilder.js#L1277

For going down at least. For going up, some more search may be needed :) according to @gokaysatir 

Also the following PR https://github.com/CollaboraOnline/online/pull/6823/files doesn't really work. You can test it and see that the focus never gets back to the tab.

**Comment by Minion3665** [comment]
@CosmicOli

**Comment by CosmicOli** [comment]
Hi, can you assign me this task?
