### ISSUE TITLE
Calc: "Dark Mode" Not Flipping Text Colors

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#6945]
### Describe the Bug

In Collabora Online Calc:

- Pressing the "Dark Mode" button multiple times causes black-on-black or white-on-white text.

### Steps to Reproduce

0. Have some visible text in a spreadsheet.
1. Go to "View" tab.
2. Click on "Dark Mode" once.
   - Text color changes. 👍 
3. Click on "Dark Mode" a few more times.
   - Bug: Colors sometimes "get stuck".

### Actual Behavior

After the first click:

- Text seems to always flip to the correct colors. 👍

But on subsequent clicks:

- Text seems to randomly "get stuck" in white/black, and doesn't correctly update.

### Expected Behavior

Flip colors of text every time "Dark Mode" is pressed.

- - -

**Workaround:** If you double-click inside a "stuck cell", the color for that cell correctly flips!

Example:

- A1 says `Hello World`
- A2 says `Hello2`

Trigger bug, then:

- Double-Click in A1.
- A1's `Hello World` will flip colors + A2 will remain "stuck".

- - -

### Screenshots

1 press is fine:

<img src="https://github.com/CollaboraOnline/online/assets/5774324/1853f7a2-2a4b-4854-b0ed-1f48defffc19" width="50%" height="50%"/>

2nd or 3rd presses soon after "get stuck":

<img src="https://github.com/CollaboraOnline/online/assets/5774324/93b2c861-acea-43af-94aa-9e03f1aea687" width="48%" height="48%"/> <img src="https://github.com/CollaboraOnline/online/assets/5774324/b595ca97-5c2b-41b7-bbf7-e89a20ebd1b2" width="48%" height="48%"/>

### Desktop

- **OS:** Linux Mint 21.1
- **Browser:** Firefox
- **Version:** 115.0.2 (64-bit)

> COOLWSD version: 23.05.1.2 (git hash: eaeaee41)
> LOKit version: Collabora Office 23.05.1.2 (git hash: 896fc92)
> Served by: Linux Mint 21.1
> Server ID: ea8b914d

### Additional Context

Similar to the one I reported for Writer:

- #6837 

(Maybe related?)

It *feels* like whatever Dark Mode refresh/update code is triggering ONLY ONCE, then, if pressed again too quickly, it doesn't fully kick in a 2nd/3rd time.

And if you are "stuck", wait around for a while, then press "Dark Mode" button again... it seems to temporarily correct itself, so it definitely *feels* like a timer/cache thing.

**Comment by Ezinnem** [comment]
This may be related to rendering. In my experience, the text colour becomes correctly updated after about 3 secs.

**Comment by Nitrousoxide** [comment]
I also experience this.  Waiting does not seem to resolve it.

<img width="612" alt="image" src="https://github.com/CollaboraOnline/online/assets/1363931/403d9355-a8d0-43dc-a869-11b44c12e29a">

<img width="793" alt="image" src="https://github.com/CollaboraOnline/online/assets/1363931/d18e9379-c933-436b-97d9-f703d60492b3">

**Comment by timur-g** [comment]
Do you have reproducible steps with a sample?
Please test with updated Online and NC and NC Office app and write your versions.

**Comment by Darshan-upadhyay1110** [comment]
the issues of black-on-black or white-on-white text when pressing the 'Dark Mode' button multiple times has not been reproducible in recent versions. I recommend closing this issue.

version info:

COOLWSD version: 24.04.5.1 (git hash: 1ecf31df)
LOKit version: Collabora OfficeDev 24.04.5.1 (git hash: e1cfc65)
Served by: Ubuntu 23.10
Server ID: 7a9ed233
