### ISSUE TITLE
Unstyled Copy Paste warning "Very Limited Access"

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#6946]
### Describe the Bug

The popup window:

> Your browser has very limited access to the clipboard, so use these keyboard shortcuts:
>
> `Ctrl+C` `Ctrl+X` `Ctrl+V`
> `Copy    Cut     Paste`

![Collabora 23 05 Writer - Right-Click Paste - Very Limited Access Window](https://github.com/CollaboraOnline/online/assets/5774324/21ff8d03-b276-4103-a824-671aa34ab6b0)

Looks like all 3 commands are squished right into each other.

Add some whitespace between.

### Steps to Reproduce

1. Open Writer document.
2. **Right-Click > Paste**
3. Popup will appear.

### Desktop

- **OS:** Linux Mint 21.1
- **Browser:** Firefox
- **Version:** 115.0.2 (64-bit)

> COOLWSD version: 23.05.1.2 (git hash: eaeaee41)
> LOKit version: Collabora Office 23.05.1.2 (git hash: 896fc92)
> Served by: Linux Mint 21.1
> Server ID: ea8b914d

**Comment by thebearon** [comment]
Let's add screenshot from 22.05:

![clipboard 22 05](https://github.com/CollaboraOnline/online/assets/19438782/516c7476-c04d-47cc-93c7-8c247ed77e74)

CC @pedropintosilva
