### ISSUE TITLE
"Font Color" Box Changes Shape/Size

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#6947]
### Describe the Bug

The entire "Font Color" box has 2 separate shapes/sizes, depending on what's selected:

<img src="https://github.com/CollaboraOnline/online/assets/5774324/4a355aa2-d7f6-4a93-a9bb-ea362896e3f8" width="80%" height="80%"/>

<img src="https://github.com/CollaboraOnline/online/assets/5774324/8687cede-dd0a-4e8a-b9c7-1ff380764936" width="80%" height="80%"/>

### Steps to Reproduce

1. Open Writer document.
2. Be in "Home" tab + click on "Font Color" button.
3. In dropdown, where it says `Standard`:
   - Change to `Theme Colors`

### Actual Behavior

- 8x8 = Standard
- 12x6 = Theme Colors

### Expected Behavior

Box to stay same shape/size.

### Desktop

- **OS:** Linux Mint 21.1
- **Browser:** Firefox
- **Version:** 115.0.2 (64-bit)

> COOLWSD version: 23.05.1.2 (git hash: eaeaee41)
> LOKit version: Collabora Office 23.05.1.2 (git hash: 896fc92)
> Served by: Linux Mint 21.1
> Server ID: ea8b914d

### Additional Context

I also tested in:

- LibreOffice 7.5.4
- Collabora Office 23.05.1

and any selection in that dropdown consistently stays:

- 12x10

with MUCH smaller color squares.

**Comment by gitgt** [comment]
Does not seem like a bug, I will close.

**Comment by pedropintosilva** [comment]
Maybe let's re-open it as an enhancement

**Comment by Tex2002ans** [comment]
While not an actual bug-bug...

It's a quirk, an oddity, an unexpected thing.

I'd expect the:

- Entire "Font Color" box to stay 8x8 or 12x10 (or whatever dimensions)

not morph depending on the secondary dropdown.

(I edited the initial post's "dropdown"->"box", I can see how you may have thought I was actually talking about the 2nd dropdown where you choose Standard/Theme Colors... lol.)
