### ISSUE TITLE
Insert Shapes icons for Dark mode in Nextcloud theme

### ISSUE THREAD

**Issue by timur-g** [CollaboraOnline/online#6948]
Insert Shapes in Writer, Calc, Impress should show contrast icons for Dark mode in 23.05 with Nextcloud. 

![image](https://github.com/CollaboraOnline/online/assets/7240617/f1387cea-4a25-4c6f-bf05-7a244f47020f)

**Comment by Andreas-Kainz** [comment]
Will check, but I think it's a NC bug.

**Comment by timur-g** [comment]
Yes, NC theme. OK unbranded.

**Comment by Ezinnem** [comment]
Confirmed. Seems fine without branding
