### ISSUE TITLE
Unhandled "Maximum call stack size exceeded" error by large "jsdialog:" response

### ISSUE THREAD

**Issue by Traktormaster** [CollaboraOnline/online#6954]
**Describe the bug**
It is possible that the WSD sends a "jsdialog:" payload so big, that "Maximum call stack size exceeded" error will be raised and not handled properly.

**To Reproduce**
1. Open a writer, draw or presentation file and add a drawing object.
2. When the object is selected the sidebar's jsdialog data payload will fail to process with:
```
Socket.js:411 Uncaught RangeError: Maximum call stack size exceeded
    at NewClass._extractCopyObject (Socket.js:411:35)
    at NewClass._extractTextImg (Socket.js:473:9)
    at NewClass._slurpMessage (Socket.js:393:8)
...
```

The culprit line is: https://github.com/CollaboraOnline/online/blob/master/browser/src/core/Socket.js#L412

If I replace that with one of the following, the error does not happen and the sidebar loads:
 - `e.textMsg = (new TextDecoder()).decode(e.imgBytes.subarray(0, index));`
 - `e.textMsg = this._strFromUint8('', e.imgBytes.subarray(0, index));`

**Desktop (please complete the following information)**
 - OS: Linux 6.1.37-1-lts x86_64 GNU/Linux
 - Browser: Chromium Version 114.0.5735.198 (Official Build) Arch Linux (64-bit)
 - Version: CODE tag: "cp-23.05.1-2"

**Additional context**
- The exact payload size that triggered the issue was 158276. That's pretty big, I'm not sure if it is normal to have such a big jsdialog payload. It has lots of png-data for icons and stuff.
- The same does not happen on Firefox, for some reason the size-limit is around 4-5 times higher to trigger the issue.

**Comment by eszkadev** [comment]
I can't reproduce. What do you mean by "and add a drawing object",  inserting a shape?

**Comment by Traktormaster** [comment]
Here is a draw file I can reproduce it with, with a screenshot of the issue. Selecting any of the shapes will trigger an error in the console and the sidebar on the right will not change to show the shape-editing controls.
![stack-error](https://github.com/CollaboraOnline/online/assets/9530287/ef2dcff0-166b-4618-9155-8a2b45a019d0)
[draw.odg](https://github.com/CollaboraOnline/online/files/12144444/draw.odg)

**Comment by Ezinnem** [comment]
@Traktormaster Please can you test again using an updated Collabora Online version?

**Comment by Darshan-upadhyay1110** [comment]
COOLWSD version: 24.04.10.1(git hash: dc930ffa6d)
LOKit version: Collabora OfficeDev 24.04.10.1(git hash: 8b2330d)
Served by: Ubuntu 23.10
Server ID: eab785be
WOPI host:
