### ISSUE TITLE
Arrow keys on notebook bar tab content should move around

### ISSUE THREAD

**Issue by Minion3665** [CollaboraOnline/online#6960]
**Describe the solution you'd like**
As a followup to #6933 it might be nice to have the arrow keys move around inside the notebook bar, so that instead of using the tab key you could use up-down-left-right to navigate between different items

**Describe alternatives you've considered**
You could use tab and shift-tab to navigate, which is already supported

**Additional context**
[Screencast from 24-07-23 09 43 08.webm](https://github.com/CollaboraOnline/online/assets/34243578/f5172651-af23-47c8-b53a-3d7841947d07)

**Comment by Ezinnem** [comment]
@Darshan-upadhyay1110 @pedropintosilva Please can you take a look?
