### ISSUE TITLE
Critical regression: Writer: No longer possible to work collaboratively on a document as of COOLWSD version: 23.05.2.1

### ISSUE THREAD

**Issue by JMoVS** [CollaboraOnline/online#6969]
**Describe the bug**
When the 2nd person joins a document in nextcloud office, the 2nd person cannot mark any text or comment or use the document while the first person can do successfully. It must be 2 different users, the same user opening the file multiple times does not work

**To Reproduce**
1. Upgrade to 23.05.2.1
2. have multiple users open the file
3. observe that 2nd user cannot interact with the file in Writer

**Expected behavior**
Multiple users be able to collaborate

**Actual behavior**
2nd user cannot interact with the document

**Screenshots**

**Desktop (please complete the following information)**
 - OS: macOS
 - Browser: Firefox and Brave

**Additional context**
COOLWSD version: 23.05.2.1 (git hash: 7256b59 (E))
LOKit version: Collabora Office 23.05.2.1 (git hash: af1c0f5)
Served by: Debian GNU/Linux 12 (bookworm)
Server ID: e82f9941

I'm rolling back to the version before as it worked there as a workaround until a fix is confirmed

**Comment by pedropintosilva** [comment]
Thanks for reporting! Can you please share the Nextcloud server version and also the richdocuments ?

Does web console through any useful info? Could you please attach a screenshot?

I couldn't reproduce this so, I'm trying to understand if there any missing bit from my side.

Much appreciated!

**Comment by JMoVS** [comment]
I didn't look at the webconsole yet, you want a screenshot of the webconsole?

**Comment by annanazarayan** [comment]
I used MacOS Safari browser and tested with 4 accounts,  I don't see the issue with collab editing 

https://github.com/CollaboraOnline/online/assets/132656915/bd39a27f-4ccb-4c32-9c6c-06648f3eb638

**Comment by JMoVS** [comment]
this is what it looked like for me: It displays but allows no interaction. The first time I clicked on the document, I jumped to the bottom of the document
https://github.com/CollaboraOnline/online/assets/7354506/ba778ae0-2835-4b7f-839d-c4f4cbe8eb99

**Comment by thebearon** [comment]
@JMoVS does it occur when starting from an empty document as well? Or any random document.

**Comment by JMoVS** [comment]
it was one existing document where I noticed it. I rolled back production and don't have time right now, maybe today later in the evening I can set up staging and see if I can reproduce it there again. Then I can more easily give you access and generate logs etc.

**Comment by timur-g** [comment]
@JMoVS Were you able to reproduce this?

**Comment by timur-g** [comment]
Since no reponse, let us assume that it is not reproducible.

**Comment by JMoVS** [comment]
I upgraded yesterday again and couldn't reproduce it anymore
