### ISSUE TITLE
Date Auto Filter not working After Unchecking 'All' Option

### ISSUE THREAD

**Issue by jtrumm** [CollaboraOnline/online#6978]
### Describe the Bug

The "OK" button on a Auto Filter for a Date type column is inactive after unchecking the 'All' option and making a new selection.

### Steps to Reproduce

1. Create a blank .ods Spreadsheet in Collabora Online 22.05.13.1
2. Add a column header in cell A1, e.g. "Test Column" and add 2 or more date values from different days and months below (see screenshot below)
3. Go to "Data" -> "AutoFilter" and add a filter to column A
4. Click on the filter icon in column A to show the filter options
5. Uncheck the option 'All'. Notice that the "OK" button gets inactivated.
6. Checkmark a value on the month or day level
7. The "OK" button remains inactive and it is not possible to filter for the selected value

### Expected Behavior

The "OK" button in the filter should be activated again after a selection has been made by the user to execute the filter condition.

### Actual Behavior

The "OK" button is inactive and it is not possible to execute the filter condition.

### Screenshots

![Date Auto Filter - OK button inactive](https://github.com/CollaboraOnline/online/assets/5574410/4198ab28-2bc6-4904-9af0-da2eea65be24)

### Desktop

(Please complete the following information)
 - **OS:** Windows 10 and Ubuntu 20.04 LTS
 - **Browser:** Chrome and Firefox
 - **Version:** Collabora Online 22.05.13.1 on Nextcloud 25.0.8-0 (both installed from Univention App Center)

### Smartphone

N/A

### Additional Context

The example file used to prepare the screenshot above: [Date Auto Filter Test.ods](https://github.com/CollaboraOnline/online/files/12229769/Date.Auto.Filter.Test.ods)

**Comment by Ezinnem** [comment]
I do not encounter this issue on my end.

@jtrumm, Please can you add a sample file for testing?

**Comment by jtrumm** [comment]
Thanks for check @Ezinnem . I am attaching the .ods example file which I also used to create the screenshot from the issue description. The file was created directly on Nextcloud using the new file dialog.

[Date Auto Filter Test.ods](https://github.com/CollaboraOnline/online/files/12229769/Date.Auto.Filter.Test.ods)

**Comment by timur-g** [comment]
I also did not reproduce with Online 22.05.17.1, both NC 27 and CODE branding. Only idea is ti update..

**Comment by jtrumm** [comment]
Dear All, thank you for checking and all your feedback. I will get in touch with our platform provider and see when they plan to offer a newer version of Collabora.

**Comment by Ezinnem** [comment]
Closing this issue as the bug seems fixed.

Please feel free to add comment if it is still reproducible for you.
