### ISSUE TITLE
Nothing happens when i try to insert a Text Box in a Presentation with the menu in Compact View

### ISSUE THREAD

**Issue by maks-w** [CollaboraOnline/online#6981]
### Describe the Bug

Nothing happens when i try to insert a Text Box in a Presentation with the menu in Compact View

### Steps to Reproduce

1. Go to Collabora Impress Presentation
2. Be sure that the menu is in compact view (View > Compact View)
3. Click on Insert > Text box
4. Nothing happens

### Expected Behavior

A Text Box should appear in the center of the document.
The same behavior with the menu in Tabbed View. 

### Actual Behavior

Nothing happens

### Desktop

 - **OS:** Debian GNU/Linux 11 (bullseye)
 - **Browser:** Brave
 - **Version:** Version 1.56.9 Chromium: 115.0.5790.98

### Additional Context
Error message
`warn:lok:71861:71829:desktop/source/lib/init.cxx:244: lok exception 'Failed to dispatch .uno:DrawText'`

I changed `.uno:DrawText` to `.uno:Text ` in `Control.Menubar.js:439` and it works, but i guess it would be better to make `Drawtext` work whith the menu in Compact mode.

**Comment by timur-g** [comment]
Not written where seen but seems in  both in 22.05 and 23.05.

**Comment by timur-g** [comment]
Fixed in 23.05 with https://github.com/CollaboraOnline/online/pull/7129.
