### ISSUE TITLE
"ch" + "lines" Units in Paragraph Styles Menus

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#6984]
### Describe the Bug

Instead of lengths being in inches/centimeters, the odd units—"ch" (# of characters) + "lines"—are appearing in certain locations.

### Steps to Reproduce

1. Go to "Format" tab.
2. Click “Paragraph” button.
3. Go to “Indents & Spacing” tab.

See "ch" + "line" Units:

![Collabora 23 05 2 - Paragraph Indents and Spacing - ch Units Bug](https://github.com/CollaboraOnline/online/assets/5774324/e985f1f5-b453-4c39-90fe-38cad6b1d1aa)

### Expected Behavior

The Units displayed should be in user's locale:

- `"` = inches
- `cm` = centimeters
- `mm` = millimeters

### Actual Behavior

The Units displayed are:

- `ch` = characters
- `lines`

which are mostly used in Asian typography.

### Desktop

 - **OS:** Windows 10
 - **Browser:** Chrome
 - **Version:** 115.0.5790.110 (Official Build) (64-bit)

> COOLWSD version: 23.05.2.2 (git hash: 16bb3284)
> LOKit version: Collabora Office 23.05.2.2 (git hash: 0f9beed)
> Served by: Linux Mint 21.1
> Server ID: 2a5e3a97

I also reproduced in COOL Weekly Meeting 129 yesterday:

> COOLWSD version: 23.05.2.2 (git hash: 85008937 (E))
> LOKit version: Collabora Office 23.05.2.2 (git hash: 0f9beed)
> Served by: openSUSE Leap 15.5
> Server ID: c3b28758

### Additional Context

guarom in the Collabora Forums initially spotted this issue:

- ["Italian units of measure Writer"](https://forum.collaboraonline.com/t/italian-units-of-measure-writer/1960)

Also see:

- [My "Potential Debugging" in the same thread](https://forum.collaboraonline.com/t/italian-units-of-measure-writer/1960/3#potential-debugging-2).
- [My "Related Bugs?"](https://forum.collaboraonline.com/t/italian-units-of-measure-writer/1960/3#related-bugs-1)
   - [LO Bug #101895: “Paragraph dialog units shown as “ch” and “lines” when “Enable char unit” is enabled by default”](https://bugs.documentfoundation.org/show_bug.cgi?id=101895)
   - [LO Bug #36709: “For first line indent using Ch (Characters) as unit, the indent value should change when font-size changes”](https://bugs.documentfoundation.org/show_bug.cgi?id=36709)

It effects:

- Collabora Office (Windows Store version) as well.

In 2022, @mikekaganski [found a root cause in LibreOffice](https://bugs.documentfoundation.org/show_bug.cgi?id=101895#c19) is:

- Having "Asian" languages enabled in:
  - **Tools > Options**
  - **Language Settings > Languages**
- "Enable char unit" enabled
  - **Tools > Options**
  - **LibreOffice Writer > General**
     - MUST HAVE "Asian" enabled in order to see 2 new checkboxes:
        - "Enable char units"
        - "Use square page mode for text grid" 

So, I'm assuming it's some weird interaction in Collabora Online with Asian options/layouts being enabled alongside Western ones.

**Comment by Minion3665** [comment]
The "use char unit" checkbox seems to be enabled by default when Asian language support is enabled. This makes some sense in LibreOffice where Asian and Complex text layout are both disabled by default...

the fix to this is probably either to disable Asian language support (and possibly also Complex text layout) by default to have parity with LO, or to disable the char unit setting by default

**Comment by thebearon** [comment]
It would probably be best to keep Asian language support enabled.

IIRC this can also be controlled by adding the following lines to `coolkitconfig.xcu`:
```
<item oor:path="/org.openoffice.Office.Common/I18N/CJK"><prop oor:name="CJKFont" oor:op="fuse"><value>false</value></prop></item>
<item oor:path="/org.openoffice.Office.Common/I18N/CTL"><prop oor:name="CTLFont" oor:op="fuse"><value>false</value></prop></item>
```

**Comment by Minion3665** [comment]
https://gerrit.libreoffice.org/c/core/+/155949 was merged, so this is fixed now
