### ISSUE TITLE
Debugging of postMessage

### ISSUE THREAD

**Issue by mrkara** [CollaboraOnline/online#70]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: _TBD_

In debug mode, it would be nice to have incoming and outgoing postMessage contents written into the browser console.

Interested one can grep for _console.log2_ in the _loleaflet/_ code to find out how it’s done for messages in existing debug mode.

Debug mode is accessible with : ```ctrl + alt + shift + d```

**Comment by Rash419** [comment]
@lpranam  can you help me with this issue?

**Comment by mrkara** [comment]
Hi @Rash419 , thank you for your interest! :)

Please feel free to start working on this issue, and ask your questions here.

**Comment by lpranam** [comment]
Sure @Rash419 what's the problem you are facing?

**Comment by Rash419** [comment]
while setting up project in my local machine, I got this error
 configure: error: header LibreOfficeKit/LibreOfficeKit.h not found, perhaps you want to use --with-lokit-path

**Comment by lpranam** [comment]
@Rash419 first you need to set up the core. you can find instructions here: https://collaboraonline.github.io/post/build-code/

**Comment by Rash419** [comment]
I built it successfully but it is not getting started  and i am getting following error in my terminal:
Bootstrapping exception 'component context fails to supply singleton com.sun.star.configuration.theDefaultProvider of type com.sun.star.lang.XMultiServiceFactory'

**Comment by Rash419** [comment]
@mrkara  can you elaborate the issue , I am having trouble understanding the issue

**Comment by mrkara** [comment]
Hi @Rash419,

After building COOL, run it with `make run`, and connect to it via a browser (let's say Chrome), and hit `Ctrl + Alt + Shift + d` to switch to the debug mode. In debug mode, you will see many things you don't see normally.

The task is to add outgoing postMessage contents also into the info seen here.

This is normal view of COOL with a sample Writer document:

![normal-mode-COOL](https://user-images.githubusercontent.com/9937631/97019494-10057d80-1559-11eb-8999-2ffe01e2b691.png)

And this is how it looks like after switching to the debug mode (-pay extra attention to the lower left corner):

![debug-mode-COOL](https://user-images.githubusercontent.com/9937631/97019551-1dbb0300-1559-11eb-99a2-5e82c23984c5.png)

If you bump into any issues, or have further questions, please don't hesitate to ask. :)

**Comment by Rash419** [comment]
I am confused and I don't know where to start from , I think I need do some changes in TitleLayer.js because it has all the functions 
related to it.

**Comment by mrkara** [comment]
@Rash419 That's okay. Let's try this: On top of the instructions above: hit F12 to open debug console on Chrome. You will see incoming and outgoign messages like this:

![debug-console](https://user-images.githubusercontent.com/9937631/97622156-e951b600-1a34-11eb-87b8-ff16449f15c0.png)

You will make sure incoming and outgoing postMessage messages are also logged and seen here.

To see how it is done for the existing ones, open a terminal and enter the loleaflet directory:

```bash
cd loleaflet
```

Then search for the `console.log2` occurences:

```bash
git grep "console.log2"
```

You will get a result similar to this:
```bash
js/global.js:   console.log2 = console.log;
src/core/Socket.js:             console.log2(+new Date() + ' %c' + type + status + '%c: ' + msg.concat(' ').replace(' ', '%c '),
src/layer/marker/TextInput.js:                  console.log2(
```

`src/core/Socket.js` looks like a good candidate, so let's open the file and search for `console.log2`. You will see it is inside the `_logSocket` function. Voila! That's how a local log function looks like. So you will write a similar function or reuse this one.

Now let's see how and where it is called. Search for `_logSocket` in the same file and investigate how it is called.

We got all we need from the existing example usages. Still with me? :)

Now it is time to find where these postMessage function is. So try:
```bash
git grep "postMessage: function"
```

You will get this as a result:
```bash
src/map/handler/Map.WOPI.js:    _postMessage: function(e) {
```

So open that file (`src/map/handler/Map.WOPI.js`), search for `_postMessage: function` and you will find where the outgoing postMessage messages are sent. Now go ahead and apply the same thing/logic you have seen to here. ;)

**Comment by Rash419** [comment]
![Screenshot from 2020-10-31 16-26-50](https://user-images.githubusercontent.com/26241069/97777408-0356da00-1b96-11eb-83d4-5b6383390f27.png)

added incoming and outgoing postmessage in bottom left section , check it out in the image

**Comment by mrkara** [comment]
@Rash419 Great! :+1: Let us see the code via a pull request then! ;)
