### ISSUE TITLE
"Glitchy Text" While Deleting/Rewriting Lines

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7010]
### Describe the Bug

When another user:

- Highlighted/Deleted old text
- Was highlighting/editing/typing new text

The new text became all glitchy-looking.

Looked like COOL was "overwriting text" but with a tiny offset or "outlined":

![Collabora 23 05 2 - Glitchy Text While in Dark Mode](https://github.com/CollaboraOnline/online/assets/5774324/c641d9b5-590a-474d-8748-e6c94d3b0634)

### Steps to Reproduce

I didn't do anything besides:

1. Turn on Dark Mode.
   - **View > Dark Mode**
2. A different user (not you) is editing/rewriting over a line of text inside the document.

I only:

- Stayed on first page/screen, not moving, as other user was editing the text.

Might be a Dark Mode-specific(?) issue, because I did not see this occurring while in Light Mode.

### Expected Behavior

Text will appear normally.

### Actual Behavior

Glitchy text.

### Desktop

 - **OS:** Windows 10
 - **Browser:** Chrome
 - **Version:** 115.0.5790.110 (Official Build) (64-bit)

I noticed this while poking around in today's COOL Weekly Meeting:

> COOLWSD version: 23.05.2.2 (git hash: 75ae9894 (E))
> LOKit version: Collabora Office 23.05.2.3 (git hash: 36c0cf3)
> Served by: openSUSE Leap 15.5
> Server ID: f1d7dde5

### Additional Context

@pedropintosilva  mentioned it might be a staging server issue. Might be exacerbated by the server being very slow.

Said this might need retesting on normal COOL installs.

**Comment by Tex2002ans** [comment]
During last week's COOL Weekly meeting, I was able to capture this with debug mode on!

![Collabora 23 05 2 - Dark Mode Glitchy Text - Debug Mode Cropped](https://github.com/CollaboraOnline/online/assets/5774324/14463268-95d0-45b7-8e49-249c6d2b310f)

This was the exact version info from Collabora's Share server:

> COOLWSD version: 23.05.2.2 snapshot (git hash: c12885c (E))
> LOKit version: Collabora Office 23.05.2.20230807 (git hash: 9615ffb)
> Served by: Debian GNU/Linux 12 (bookworm)
> Server ID: 5027e593
> RouteToken: a7912854

**Comment by Darshan-upadhyay1110** [comment]
@Ezinnem please can you confirm above issue is still in our latest cool version? I tried to reproduce it and it works fine now no glitchy text in document.

Version:

COOLWSD version: 24.04.5.1 (git hash: 1ecf31df)
LOKit version: Collabora OfficeDev 24.04.5.1 (git hash: e1cfc65)
Served by: Ubuntu 23.10
Server ID: 7a9ed233

**Comment by Ezinnem** [comment]
I can confirm that the the behaviour no longer occurs in:
COOLWSD version: 24.04.5.1 (git hash: [14d45ca4](https://github.com/CollaboraOnline/online/commits/14d45ca4) (E))
LOKit version: Collabora Office 24.04.5.1 (git hash: [9880a99](https://git.libreoffice.org/core/+log/9880a99))
