### ISSUE TITLE
[BUG] Spacing and padding number fields very glitchy.

### ISSUE THREAD

**Issue by nooblag** [CollaboraOnline/online#7027]
### Describe the Bug

In spacing and padding fields, the numbers are glitchy when changed or when user input is attempted. In below example, the target padding is 0.3" but the user has difficulty both entering this number on the keyboard and/or selecting it by the arrows.

The fields glitch and reset or simply do not accept user input at all.

### Steps to Reproduce

1. Start a new document.
2. Add example text and attempt to change padding value.

### Expected Behavior

Valid user input is allowed and accepted; user field values are not wiped out when using arrows.

### Actual Behavior

The fields glitch and reset or simply do not accept user input at all.

### Screenshots

https://github.com/CollaboraOnline/online/assets/1122344/7e1cd74f-1f44-44dd-920d-5417e53319b0

https://github.com/CollaboraOnline/online/assets/1122344/debe011a-68fa-45be-9b3b-f91ee2c6f9e7

### Desktop

 - **OS:** Linux, and Windows
 - **Browser:** Firefox
 - **Version:** 116.0

### Server

- `coolwsd` **version:** 23.05.2.2
- **Nextcloud version:** 27.0.1

**Comment by timur-g** [comment]
Sidebar - Spacing, Indent: arrow does not work on click (only when kept pressed) - this issue, confirmed. 
Sidebar - Spacing, Indent does not accept Enter (only click away ) - important when using arrow keys, to be checked if general.
Table - Borders - Padding changes text size: I did not reproduce, but taht would be another issue anyway.

**Comment by Ezinnem** [comment]
Fixed by https://github.com/CollaboraOnline/online/pull/7057
