### ISSUE TITLE
Saving a file via WOPI does not work anymore - file is downloaded instead

### ISSUE THREAD

**Issue by gendergap** [CollaboraOnline/online#7049]
### Describe the Bug

We use Collabora to read rich text documents from an API via WOPI. Nextcloud is not involved in this setup. Just saying.
The documents can be loaded into Collabora either in a read-only state (displaying just the viewer) or editable, displaying the whole ribbon bars of the editor and the save button.
When clicking the save button, the changed file used to be written back to the API. But for a while now, the browser instead starts a download to disk for the file `Untitled 1 (repaired document)_` (no suffix), that can be renamed to `something.odt` and thus is revealed as the real rich text document. But the download should not happen, it should write back to the WOPI API.

### Steps to Reproduce

1. Start a Collabora instance with the configuration allowing it to connect to the WOPI API server
2. Perform a `POST` request to Collabora `cool.html` with the appropriate `?WOPISrc=URL`
3. Browser displays the rich text document
4. Perform some text changes
5. Click the save icon (a red dot indicates that there are changes)

### Expected Behavior

We expect a PUT request to the WOPI API to happen.

### Actual Behavior

The browser downloads the document to the computer's disk.

### Screenshots

![image](https://github.com/CollaboraOnline/online/assets/85344655/988314db-94e8-445f-8914-d41a1a3acbb0)
![image](https://github.com/CollaboraOnline/online/assets/85344655/e780b836-e926-49ff-a9ef-947a836c2083)

### Desktop

 - **OS:** Windows 10 and 11
 - **Browser:** Chrome, Edge, Firefox
 - **Version:** several up to latest

### Additional Context

The Collabora log does show one single log line around the time of the problem:

>  [ docbroker_016 ] ERR  WOPI::CheckFileInfo does not specify a valid UserFriendlyName for the current user. Temporarily [UnknownUser] will be used until a valid name is specified.| wsd/Storage.cpp:807

Not sure though if it is related.

**Comment by timur-g** [comment]
Can you please write Collabora version where it does not work, and if you can say the version it worked in (can it be 22.05.9)?

**Comment by timur-g** [comment]
Similar issue was fixed for 23.05.05 so I close this one. If you find it not fixed, please write back.

**Comment by eszkadev** [comment]
Hi, I will add a comment here. This can happen if file is broken but we were able to repair it on load. In the new version there will be warning and it will work.

**Comment by gendergap** [comment]
@eszkadev Thanks for the update. So far, the version @timur-g mentioned has not been built as a container image (most recent one is 23.05.4.2.1). I will wait a few days and check if the behaviour is better.

Do you have a hint in which way the affected documents might be broken, so that we can check how they were created and fix that?

**Comment by gendergap** [comment]
The suitable Collabra version was released in the meantime. I can confirm that the save->download bug does not appear there anymore. Instead, I get this "pretty" dialogue:

![MicrosoftTeams-image](https://github.com/CollaboraOnline/online/assets/85344655/4372ad7f-f425-4392-bde6-2f576529caa4)

For my software, I now only need to find a way to prevent broken documents from the start. But at least it is now usable again. Thanks for your time and fixes!
