### ISSUE TITLE
Many Icons Not Inverting Color in Dark Mode

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7070]
### Describe the Bug

In Collabora's own internal style (the one with purple background/highlights), many icons don't correctly flip colors depending on:

- Dark Mode ON
- \+ If the buttons are Active or not.

![Collabora 23 05 2 - Dark Mode - Icons Wrong Colors Marked](https://github.com/CollaboraOnline/online/assets/5774324/5f5b858d-f6ba-44bc-8c19-f0664a8d01a6)
![Collabora 23 05 2 - Dark Mode - Icons Wrong Colors 2 Marked](https://github.com/CollaboraOnline/online/assets/5774324/8cb849aa-4cdb-413f-91ec-14c55d1524ae)

For example, in the 2 screenshots above:

"Review" tab:

- Automatic Spell Checking
   - Icon+Text are dark-on-dark.
- Show
   - Icon is dark-on-dark.
- Next + Previous
   - Icons are dark-on-dark.  

"View" tab:

- Dark Mode
   - Little moon shape stays dark, should be inverted.

Sidebar:

- Many icons don't inverse colors
   - (Drew many arrows/boxes to them.)

### Steps to Reproduce

1. Open document in Collabora's Share server.
2. Turn on Dark Mode.
3. See certain icons don't correctly inverse.

### Expected Behavior

Icons to be bright on dark background.

### Actual Behavior

Most are correctly flipped, but some are still dark-on-dark.

### Desktop

- **OS:** Windows 10
- **Browser:** Chrome
- **Version:** 115.0.5790.110 (Official Build) (64-bit)

> COOLWSD version: 23.05.2.2 snapshot (git hash: c12885c (E))
> LOKit version: Collabora Office 23.05.2.20230807 (git hash: 9615ffb)
> Served by: Debian GNU/Linux 12 (bookworm)
> Server ID: 5027e593
> RouteToken: a7912854

### Additional Context

Looks like it only occurs with the specific Collabora styles/icons with purple highlights.

Does not happen in normal Collabora Online.

**Comment by sebastiaanveld** [comment]
Color related icons seem to be "black" in both in both dark mode as well as in non-dark-mode.

![image](https://github.com/CollaboraOnline/online/assets/37268999/8a31f795-1ba5-4289-b379-a7218bd93ceb)

![image](https://github.com/CollaboraOnline/online/assets/37268999/afdf7dc2-d1ea-4eb7-afab-fbf12b4d0aa1)


COOLWSD version: 23.05.4.2 (git hash: 0b27e85 (E))
LOKit version: Collabora Office 23.05.4.2 (git hash: 78039c5)
Served by: Debian GNU/Linux 12 (bookworm)
Server ID: fdef652b

**Comment by Tex2002ans** [comment]
I also caught a few more in Calc while we were testing during last week's Community Weekly Meeting 138:

![Collabora 23 05 4 - Calc Dark Mode Non-Dark Icons](https://github.com/CollaboraOnline/online/assets/5774324/6b0584e1-1c50-4c4e-9b4b-a9efea63effe)

Doesn't look like this occurs in normal Collabora Online Calc... only this branded version.

**Comment by Darshan-upadhyay1110** [comment]
Thanks for the update. I tested it on the latest version, and all icons appear to be fixed as reported in this issue.

COOLWSD version: 24.04.4.5snapshot (git hash: eb91527)
LOKit version: Collabora Office 24.04.4.20240711 (git hash: c16803a)
Served by: Ubuntu 22.04.4 LTS
Server ID: b54ff9a9
