### ISSUE TITLE
combine viewport requests ...

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#7079]
When scrolling by dragging a slider through large documents we send lots of:

clientvisiblearea

messages - cf. git grep _sendClientVisibleArea # and then we also send a tilecombine for any missing tiles that the client is missing at the same time.

I -expect- that when we're moving lots of screens at a time, we spend some time to render the first screenful - and build up a queue of new clientvisiblearea messages, and tilecombines - for areas that are (by now) also not visible - we've moved on past them.

Most likely we then dutifully render those areas (in order) creating load we don't want and life is bad.

A simple fix (I guess) would be to compress / apply all the 'clientvisiblearea' messages in the queue in the Kit, and when choosing what next set of tiles to render to prioritize those tiles that intersect with at least on visible area.

Hopefully that could help use our CPU time more effectively for this use-case =)

**Comment by caolanm** [comment]
I think we've done this
