### ISSUE TITLE
Ctrl+f does not work on the Ukrainian keyboard layout.

### ISSUE THREAD

**Issue by AIlkiv** [CollaboraOnline/online#7084]
### Describe the Bug

Ctrl+f (Ctrl+а) does not work on the Ukrainian keyboard layout.
I have checked other keyboard shortcuts, and they work correctly on the Ukrainian keyboard layout.
There is no such problem on English layouts.

### Steps to Reproduce

1. Open the document/table in the Collabora Office browser.
2. Switch the keyboard layout to Ukrainian.
3. Press Ctrl+F.
4. The search bar does not appear.
5. I switch to the English layout.
6. When I press Ctrl+F, the search bar appears.

### Expected Behavior

A search bar should appear.

### Desktop

 - **OS:**  Windows 11
 - **Browser:** Chrome 115.0.5790.171
 - **Collabora Office Version:**  23.05.2.2

**Comment by oleua** [comment]
Still not working in Collabora 25.04.8.1 :(

COOLWSD version: 25.04.8.1(git hash: 278cb3481b (E))
LOKit version: Collabora Office 25.04.8.1(git hash: 489cb5d73b)
Served by: unknown
Server ID: ****
WOPI host: nextcloud 31.0.9.1 - richdocuments 8.7.5.3
