### ISSUE TITLE
Indication in the Admin console when the daemon shuts down

### ISSUE THREAD

**Issue by mrkara** [CollaboraOnline/online#71]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: _TBD_

While _wsd_ is running, open the admin console. Now ```Ctrl + C``` to stop the _wsd_ process. The admin console should show the user that Online was shut down. Worse, when the _wsd_ is restarted, the admin-console screen is not updated accordingly; it keeps showing the stale view from the previous launch.

An error box or the overlay saying that _wsd_ has been shut down should be done and refresh the page with the new _WS_ connection whenever user clicks on the overlay. This is similar to when the document becomes inactive.

#### How to hack:
Check what web socket messages we receive when _wsd_ shuts down in the backend and handle it appropriately in the admin websocket. One can check the websocket handling for the documents in _src/core/Socket.js_ and do something similar with the admin websocket. Code for admin websocket is in _loleaflet/src/admin/_

In debug mode, it would be nice to have incoming and outgoing _postMessage_ contents written into the browser console.

**Comment by Rash419** [comment]
I would like to work on this issue 😃

**Comment by mrkara** [comment]
@Rash419 Cool. Please, go ahead! :)

**Comment by Rash419** [comment]
I decreased the time to make document idle by changing the following lines:
  <out_of_focus_timeout_secs desc="The maximum number of seconds before dimming and stopping updates when the browser tab is no longer in focus. Defaults to 120 seconds." type="uint" default="15">15</out_of_focus_timeout_secs>
        <idle_timeout_secs desc="The maximum number of seconds before dimming and stopping updates when the user is no longer active (even if the browser is in focus). Defaults to 15 minutes." type="uint" default="30">30</idle_timeout_secs>

even though document is not becoming idle
