### ISSUE TITLE
iOS app: some boxes can't be scrolled with a finger

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#710]
**Describe the bug**
Some boxes in tunneled dialogs and also the sidebar can't be scrolled using a finger. Some examples:
* Impress > "Animation" (star icon) sidebar > box with elements that should be animated
* Writer > Format > Paragraph ... > Area > Color > the color palets (works if you hit the tiny scrollbar)

**To Reproduce**
1. Open an presentation using the iOS app
2. Open the "Animation" (star icon) sidebar
3. Add a bunch of elements to the box using the "+" button
4. Try to scroll the box

**Expected behavior**
A user should be able to scroll the box using a finger swipe

**Actual behavior**
It's not easily possible to scroll through the list using a finger swipe

**Screenshots**
![image](https://user-images.githubusercontent.com/1211300/99636643-fbc37c00-2a43-11eb-8564-75aa36ebe0b5.png)

**Tablet**
 - OS: iPad OS 14.2
 - Version: 6.4.0 (16)

**Comment by mmeeks** [comment]
This is broadly expected. I suppose we could try to convert a swipe there to a mouse-scroll-wheel button events, but I expect the physics / feel to behave rather poorly. My hope is that as we move this to local-JS widgets we can address these issues properly.

**Comment by nikslor** [comment]
FWIW: can't test on 21.6.1 (1) as the app crashes when dealing with impress content (#3296); will recheck with a later version as well as I think the HTML/JS sidebar also fixes this issue.

**Comment by nikslor** [comment]
Event with the HTML sidebar I can't scroll this list on a tablet.

**Comment by timar** [comment]
This is no longer a problem in 23.05.
