### ISSUE TITLE
No style previews when opening compact view first

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#7105]
### Describe the Bug

I saw empty style previews (tabbed view > Home tab) on share.

### Steps to Reproduce

1. In a private/incognito window
2. Got to https://share.collabora.com/index.php/s/6HcSmQZMcB3yDZs
3. Password: coolweekly132
4. Noticed that the compact view is loaded
5. Switch to tabbed view
6. Notice, style preview box is empty

Web browser's console: 
[console-export-2023-8-17_8-43-59.txt](https://github.com/CollaboraOnline/online/files/12366391/console-export-2023-8-17_8-43-59.txt)

**Comment by thebearon** [comment]
This doesn't just happen via share link, but whenever you start in compact view. Plus it's a regression.

**Comment by timur-g** [comment]
I see it NOK already in  23.05.0.1 - 24e2f6f7 and also in  22.05.10.0 - bcf1f0fb. IDK how to find good commit.
OTOH, 22.05 seems OK.

**Comment by Ezinnem** [comment]
This is fixed.


https://github.com/CollaboraOnline/online/assets/54344301/c7b01987-7957-42b6-8972-7d422533c5e0



Tested on:

COOLWSD version: 23.05.4.1 (git hash: [938b8e31](https://github.com/CollaboraOnline/online/commits/938b8e31) (E))
LOKit version: Collabora Office 23.05.4.1 (git hash:  [dc263a2](https://git.libreoffice.org/core/+log/dc263a2) )

**Comment by thebearon** [comment]
Fixing change: https://gerrit.libreoffice.org/c/core/+/156836
https://cgit.freedesktop.org/libreoffice/core/commit/?id=c0234520ba9afda5a8b32f7a04c2155cbfbe30ed

Related: https://bugs.documentfoundation.org/show_bug.cgi?id=155720
