### ISSUE TITLE
Rename document button works only on tabbed view

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#7109]
### Describe the Bug

The newly added "Rename Document" triggers the rename dialog only when on tabbed view. It does nothing when on the compact view. IIRC this was working before.

### Steps to Reproduce

1. Switch to compact view
2. File menu
3. Rename Document
4. Nothing happens

**Comment by Ezinnem** [comment]
Confimed in:
COOLWSD version:
23.05.2.2git hash: [c3aaae07](https://github.com/CollaboraOnline/online/commits/c3aaae07)(E)
