### ISSUE TITLE
Data Validation using Dropdown broken in latest docker container

### ISSUE THREAD

**Issue by skleffmann** [CollaboraOnline/online#7119]
### Describe the Bug

Data Validation using Dropdown is broken in the latest collabora docker version (23.05.2.2.x)

### Steps to Reproduce

Open a table containing field ranges with data validation list inputs.
Select a cell from that range.
The cell does not offer the drop down to select a value from that list.

### Expected Behavior

The selected cell should show a drop down icon on the right side to open a list with valid values.

### Actual Behavior

The cell does not offer the drop down to select a value from that list.

### Additional Context

This was working fine until version 23.05.2.1
A rollback to the previous docker container fixes the problem.

**Comment by Ezinnem** [comment]
The Data validation dropdown is functioning properly on my end.

I tested using:

COOLWSD version: 23.05.2.2 (git hash: [31ae779d](https://github.com/CollaboraOnline/online/commits/31ae779d) (E))
LOKit version: Collabora Office 23.05.2.3 (git hash: [352bcab](https://git.libreoffice.org/core/+log/352bcab))

Please can you share a sample file and a recording to show what is not working as you expected?

**Comment by skleffmann** [comment]
These are screenshots from the 23.05.2.1 and 23.05.2.2 (latest pull) versions.
You can see, the dropdown is not showing int the 2.2 version.
I attached the demo file.

[DropDownTest.ods](https://github.com/CollaboraOnline/online/files/12427552/DropDownTest.ods)

![230521](https://github.com/CollaboraOnline/online/assets/9338452/32e10710-4593-4e4f-8b66-8e603c22c14f)
![230522](https://github.com/CollaboraOnline/online/assets/9338452/21263154-8c8b-4a35-932e-f09a972a5b8c)

**Comment by Ezinnem** [comment]
Thank you for sharing the sample file and screenshots; I understand more clearly what the issue you described is.

I think it may be similar to the issue reported in https://github.com/CollaboraOnline/online/issues/6986

Please can you check the discussion in https://github.com/CollaboraOnline/online/issues/6986 confirm that they are similar @skleffmannlar?

**Comment by skleffmann** [comment]
Thanks for investigating this issue. Indeed the issue #6986 seems to be the same.

**Comment by Ezinnem** [comment]
Great. Thanks for confirming.

I think it will be good to close this issue and follow-up the discussion in #6986
