### ISSUE TITLE
calc comments don't have to be a red rectangle

### ISSUE THREAD

**Issue by caolanm** [CollaboraOnline/online#7130]
### Is your feature request related to a problem?

The red rectangles in the spreadsheet that indicate a comment aren't very pretty and don't scale when the spreadsheet is zoomed in

### Describe the solution you'd like

In https://github.com/CollaboraOnline/online/commit/ccb20f1ed329e483f52831858f711b3a0e73502d we moved the rendering of these into the browser, matching how they were doing in core. So just a simple fillRect in red. It might be nicer to at least draw something like a triangle that scales with the zoom.

**Comment by caolanm** [comment]
@pedropintosilva maybe of interest to you

**Comment by pedropintosilva** [comment]
@caolanm : that's great news , thanks for the ping!

**Comment by pedropintosilva** [comment]
## Color

I think it would be good to steer away from red color and instead use yellow or blue. Probably best to go with yellow so to make it stand out (and avoid too similar colors nearby).

## Shape

I would go with something that can signify "open comment, pop out" but still using a basic shape (no icon)
* Paint top right corner of the cell in yellow (Triangle) as it happens in other spreadsheet programs
