### ISSUE TITLE
Unable to sign up for Collabora Online demo

### ISSUE THREAD

**Issue by blacklightpy** [CollaboraOnline/online#7136]
### Describe the Bug

I am unable to sign up for Collabora Online demo. Filling up the form does not do anything.

### Steps to Reproduce

1. Go to https://www.collaboraoffice.com/collabora-online/
2. Fill in Details
3. Submit

### Expected Behavior

Something happens

### Actual Behavior

Submit button turns to "please wait"

### Screenshots

![image](https://github.com/CollaboraOnline/online/assets/28739146/5a85b785-314e-46f1-b274-a48826c30a41)

### Desktop

(Please complete the following information)
 - **OS:** Windows 11
 - **Browser:** Pulse Browser Alpha (Firefox fork) and on Chrome
 - **Version:** Pulse 1.0.0-a78 / Chrome 116.0

### Smartphone

N/A

### Additional Context

N/A

**Comment by timur-g** [comment]
Ater form staying open and seeming non reactive, I closed the page, but after few minutes I received confirmation mail - so it iseems to be working but may appear like not.

**Comment by blacklightpy** [comment]
But I did not get the email

**Comment by Ezinnem** [comment]
This issue has been resolved. The emails are sent after submitting the details.

@blacklightpy Please retest. Feel free to comment if you encounter any further issue.
