### ISSUE TITLE
"Help > Online Help" Disappears After Pressing "Keyboard Shortcuts"

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7148]
### Describe the Bug

"Online Help" button disappears after pressing other buttons in the Help menu.

### Steps to Reproduce

1. Press "Help" Tab.

See 6 buttons:

- Forum
- **Online Help**
- Keyboard Shortcuts
- Accessibility Check
- Report An Issue
- About

2. Press "Keyboard Shortcuts" button.

3. Close "Keyboard Shortcuts" popup.

See 5 buttons now:

- Forum
- [!!!MISSING!!!]
- Keyboard Shortcuts
- ...

### Screenshots

At Step 2:

![Collabora 23 05 2 - Online Help Disappearing 1](https://github.com/CollaboraOnline/online/assets/5774324/5f5700ba-73d7-4d44-9325-62ef7e76a674)

After Step 3:

![Collabora 23 05 2 - Online Help Disappearing 2](https://github.com/CollaboraOnline/online/assets/5774324/48d48ef5-53a7-4c05-b762-3e531846d4b2)

### Actual Behavior

"Online Help" button disappears.

### Expected Behavior

"Online Help" button stays!

### Desktop

- **OS:** Linux Mint 21.1
- **Browser:** Firefox
- **Version:** 116.0

> COOLWSD version: 23.05.2.2 (git hash: 6d7efe98)
> LOKit version: Collabora Office 23.05.2.3 (git hash: 6d3919c)
> Served by: Linux Mint 21.1
> Server ID: 6a211231

### Additional Context

I did not press other buttons to see if this odd "disappearing button" happens to any others.

After refreshing the browser tab, all buttons return fine.

**Comment by Ezinnem** [comment]
I can confirm this issue.

**Comment by Ezinnem** [comment]
I can confirm this issue.

**Comment by timur-g** [comment]
I do not reproduce with  23.05.2.2 - b85eb1b0 but do with  576fb1b1 so recent regression. 

commit 1a2500c8d31f12a8e23c648a0afb208e3d09bb05
Author: Gökay Şatır <gokaysatir@gmail.com>
Date:   Tue Aug 8 15:46:49 2023 +0300
    Merge accessibility definitions with notebookbar definitions.

@gokaysatir please see.

**Comment by timur-g** [comment]
Should be fixed now https://github.com/CollaboraOnline/online/pull/7223
