### ISSUE TITLE
Android not updating

### ISSUE THREAD

**Issue by PeterKW** [CollaboraOnline/online#7149]
As far as I can tell, all the Android update notifications have stopped. Google Play & FDroid don't update 

I've found recent updates released here: https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/

Is there any way to make this information clearer to find or to update how Android updates are received?

https://play.google.com/store/apps/details?id=com.collabora.libreoffice
https://www.collaboraoffice.com/downloads/fdroid/repo/

Thank you very much

**Comment by Rash419** [comment]
These are daily snapshots. They might have bugs and are not stable version. We only release stable version on Play Store and FDroid. You can use this snapshots and give us feedbacks etc.

**Comment by timur-g** [comment]
This is clarified for stable, and for F-Droud there is #3251 so let us close this.

**Comment by PeterKW** [comment]
What is the latest stable version number sorry?

**Comment by timur-g** [comment]
Latest is 21.11 as in Play store, and soon latest will be 23.05.

**Comment by user8446** [comment]
@Rash419 where is the preferred place for feedback on bug reports, suggestions, etc. on the snapshots?

**Comment by Rash419** [comment]
You can create issues on GitHub

**Comment by Rash419** [comment]
You can create issues on GitHub
