### ISSUE TITLE
Some Words in Long "Right-Click Suggestions" List Get Cut Off

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7155]
### Describe the Bug

When Right-Clicking a misspelled word, sometimes the list of suggestions gets "cut off".

### Steps to Reproduce

Have a misspelled word with *lots* of suggestions... like "JS" / "PRs" / "UNO".

1. Right-Click misspelled word.
2. First few suggestions in list sometimes gets cropped off the screen... missing some entries.

### Screenshots

Here, the entire list fits:

![Collabora 23 05 2 - Right-Click Suggestions 1](https://github.com/CollaboraOnline/online/assets/5774324/56c4f0b4-c86d-41d7-b539-0fe9a0c896c2)

but depending on where the misspelled word lands on screen when you Right-Click, the list might get cut:

![Collabora 23 05 2 - Right-Click Suggestions 2](https://github.com/CollaboraOnline/online/assets/5774324/e0b9738c-e19c-4e44-a1dc-10527833abe2)

Notice the 1st suggestion "UNI" is cropped out, so all you can see is 2nd suggestion "NO" and all the ones below it.

### Actual Behavior

Some suggestions don't appear on screen + aren't clickable.

### Expected Behavior

- All suggestions show up.
- Or, if can't fit entire thing on screen...
    - Entire box gets shifted further down.
    - OR limit suggestions to X entries.
       - (Although this only pushes issue if user has really large font sizes or odd window sizes.)
    - OR a scrollbar is introduced, like what happens with EXTREMELY long suggestion lists.

### Desktop

- **OS:** Windows 10
- **Browser:** Firefox
- **Version:** 117.0b9 (64-bit)

> COOLWSD version: 23.05.2.2 (git hash: 1117b612 (E))
> LOKit version: Collabora Office 23.05.2.3 (git hash: df2ec10)
> Served by: openSUSE Leap 15.5
> Server ID: cace7c49

### Additional Context

I tested this during Collabora Weekly Meeting (Nextcloud). Did not test in normal COOL or other strange configurations.

**Comment by Ezinnem** [comment]
I can confirm this issue.

**Comment by Darshan-upadhyay1110** [comment]
This issue is being fixed in latest version. 

- now if dialog will adjust based on the position of word on document
 - 
![image](https://github.com/user-attachments/assets/d5171f19-1833-428b-92f4-955f66341347)
- 
![image](https://github.com/user-attachments/assets/630c3b59-ab01-4577-8e42-e142ff5cae79)


Also, if there are too many suggestion words for the dialog will automatically have the scrollbar to fit all content within the browser window 😉
