### ISSUE TITLE
Missing Tools menu option

### ISSUE THREAD

**Issue by vincentkoevoets** [CollaboraOnline/online#7163]
### Describe the Bug

I am missing the Tools menu option. Everywhere in the documentation there is mention of a Tools menu and its underlying options, but I do not have a Tools menu option in my menu bar. 

### Steps to Reproduce

Open any document, see the Tools menu is missing

### Expected Behavior

The Tools menu should be there.

### Actual Behavior

The Tools menu is not there

### Screenshots

![Schermafdruk van 2023-08-25 12-15-13](https://github.com/CollaboraOnline/online/assets/43203114/c5a99c29-fbf2-4bb1-8f95-d98431ddf4e2)

### Desktop

Nextcloud installation with Collabora, all in seperate dockers, all updated to the latest version.

**Comment by timur-g** [comment]
Tools in English would be Extra there.
![image](https://github.com/CollaboraOnline/online/assets/7240617/e4e81702-d3b1-4bcf-9df9-a98b08e766f9)

**Comment by vincentkoevoets** [comment]
Okay, so that's located then. But there should be more items in the menu, right? I'm looking for Options in particular, as stated [here](https://help.collaboraoffice.com/6.4/en-US/text/scalc/main0106.html?&DbPAR=CALC&System=UNIX) Or does this not apply to Nextcloud Office?

**Comment by timur-g** [comment]
That help link is for menu items in desktop Collabora Office, Online is different, as not all is supported.

**Comment by vincentkoevoets** [comment]
Okay thanks for the clarification, clearly I'm not entirely up to date on all terminology. Thanks for taking the time to respond.
