### ISSUE TITLE
DocumentBroker::sendRequestedTiles !newTileCombined.hasDuplicates() assert

### ISSUE THREAD

**Issue by caolanm** [CollaboraOnline/online#7164]
### Describe the Bug
When a second user joins that can cause an assert of !newTileCombined.hasDuplicates(),. 

### Steps to Reproduce

1. I triggered this originally using "Open multiple urls" to open hello-world.odt in 20 tabs locally

### Actual Behavior

What I think is happening here is that the client is *sent* two canonicalidchange messages, the first message sends 1001 as viewid and the second message sends 1002 as viewid. But the first message appears before this._map._docLayer and so it put into a timer to happen later, then the second message appears but it is applied immediately it arrives, then the timer fires and the outdated obsolete canonicalidchange gets applied out of sequence which goes on to have unwanted sideeffects.

**Comment by caolanm** [comment]
I think this problem has become common since around

commit a003126a652474906bb8a2ecc67d52ec4f39fab5
    Give new sockets a canonical view id in tests

and
commit d0c5321aaf8bfd3cbda1adb7830b569e971aba5c
    Fix getting canonical view id of 1000

while the delaying thing is also relatively new since

commit e660bb8e66e60cbff64fff1eb6eb39968797ee32
Date:   Mon Aug 14 14:21:05 2023 +0300

When document layer is not ready and socket message is not delayed, message is lost

**Comment by caolanm** [comment]
@gokaysatir Putting a breakpoint into browser/src/layer/tile/CanvasTileLayer.js at
this._canonicalViewId = canonicalId;
I frequently see that (in a 2nd browser window) that _canonicalViewId gets set to 1002 first and then later 1001 from the delayed message so we end up with an obsolete _canonicalViewId

**Comment by caolanm** [comment]
The code added in e660bb8e66e60cbff64fff1eb6eb39968797ee32 is very much like the existing code of _tryToDelayMessage so maybe what case is desired to be caught by the new thing should be added to _tryToDelayMessage instead?

**Comment by mmeeks** [comment]
I suspect this could also be the cause of a new regression - whereby I lost a load of tiles on document load (I guess if there was a race) - it was easy to loose the top row of tiles in a document - until the doc was touched. And/or it was easy to loose the 2nd half of it at times =) a recent regression I've never seen before - on share as of now - share is c9e7591 currently which includes that patch.

**Comment by caolanm** [comment]
@gokaysatir for at least the sake of experimentation, would the above keep the original problem that e660bb8e66e60cbff64fff1eb6eb39968797ee32 solved working?

That problem was apparently triggered by d0c5321aaf8bfd3cbda1adb7830b569e971aba5c and was related to PDF. Was it originally trying to print, or export as pdf?

**Comment by gokaysatir** [comment]
@caolanm hello thank you for the help here. Let me test the PR now.

**Comment by gokaysatir** [comment]
@caolanm yes your PR seems to solve the PDF tiles issue.
