### ISSUE TITLE
Extra invalidation regression tests ...

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#7167]
We should expose in the JS client a total count of the number of empty deltas we have received, not just per-tile:
_applyDelta:
...
				tile.updateCount++;

Should bump a global counter somewhere. Prolly we should put this into an HTML element in the DOM somewhere easy for Cypress to find it as well: it would be nice to have it displayed - it is almost certainly a bad-ness metric.

If we invalidate something, and we generate an empty delta - something is wrong - not very wrong, but ... inefficient: we shouldn't be re-rendering identical tiles.

Then we should add code to our cypress tests to check that HTML element with the number in it to ensure that it doesn't change over eg. a new user joining the document, or a character being typed in writer at a certain point, or clicking in the header etc.

Thanks ! =)

**Comment by caolanm** [comment]
This is done now, the specific examples are included. I note we are sending empty updates from at least grammar checking while editing, so there is room for improvement uncovered by these regression tests for the more gross fixed invalidations.
