### ISSUE TITLE
Async file-locking

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#7168]
Currently our WOPI-like file locking is synchronous. This can cause delays in typing etc. as we renew the lease and/or save.

We should make this asychronous instead. nuff said =) @Ashod is interested no doubt.

Thanks.

**Comment by mmeeks** [comment]
Sven - this would be good for you I think =)

It seems reasonably to synchronously lock in the 1st instance - and I guess to unlock likewise at the end; but updating the lock/lease as we go along should be async to avoid blocking on slow/overloaded Nextcloud servers.

Code pointers:

git grep -20 'updateLockState' # for general code pointers

git grep -20 refreshLock # for the one use-case that should be async =)

Thanks!

**Comment by ferdiga** [comment]
Hi,
I am not sure that this is the right place...

Opening the same file stored on a NextCloud Server allows to edit both files independently and the one which is saved as last one overwrites the other without notice, leading to data loss - obviously.

**Comment by mmeeks** [comment]
I believe @Ashod may have already fixed this here:

commit b21e172047415f626bbc1e758108619c2fe1b656
Author: Ashod Nakashian <ashod.nakashian@collabora.co.uk>
Date:   Tue Aug 13 10:14:26 2024 -0400

    wsd: async lock/unlock documents
    
    Change-Id: I7cae93d9bbebc8f187053f581bfe0360d9e941c4
    Signed-off-by: Ashod Nakashian <ashod.nakashian@collabora.co.uk>

commit 1dd9356d90905518975cd9e973947cb131539037
Author: Ashod Nakashian <ashod.nakashian@collabora.co.uk>
Date:   Thu Aug 8 05:46:53 2024 -0400

    wsd: async updateLockState
    
    Change-Id: I201320218948549b83d15b646fc331d5ff5f2ca6
    Signed-off-by: Ashod Nakashian <ashod.nakashian@collabora.co.uk>
