### ISSUE TITLE
PDF corruption after adding a Comment to the document

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#7173]
A PDF document gets corrupted after adding a comment to a PDF document that was made from a scanned document/screenshotted file. I ran into this after opening a PDF that I received quite some time ago and don't have the original from anymore. I can reproduce the issue with the Nextcloud IOS App "Scan document" feature, scanning a document/book cover and create a PDF from this so the PDF is made up from like screenshots/capture/pictures (not sure how this is called from a PDF creation perspective). When the PDF file is now opened in CODE using "Open in Nextcloud Editor "you see the PDF document document and add a Comment to it. After adding a single comment and closing the document the PDF looks corrupted after reopening it either with CODE or a PDF viewer.

I cannot reproduce this when I export an .odt of .docx document from CODE to a PDF document and then open the .pdf with CODE and adding a comment to it. This seems to work fine.

### Steps to Reproduce

1.  Create a PDF file from a "picture" like using the Nexcloud IOS App to create a PDF document using the "Scan document" feature and make a scan from a page/object/book cover (in my example). Save the scan to a PDF with the app. One this file is synced to your NC server, in step 2:
2. Click in Nextcloud Files the option menu on the syned PDF file and select  'Open in Nextcloud Editor'
3. Add a comment to the PDF file
4. Close the pdf file
5. Open the PDF file with the comment with either CODE or a PDF editor (Nexctloud preview of your in browser viewer, etc)
6. The comment is still in the PDF as you can view it in CODE, but the scanned "picture" is a small pic in the lower left corner of the first PDF document page. 

### Expected Behavior

The user expects the PDF document looks the same as before adding a comment to the PDF document.

### Actual Behavior

The PDF document page the commend was added to is "corrupted" and appears as a small pic in the lower left corner of the document page. 

### Screenshots

PDF document opened from Nextcloud in CODE before adding a comment

![image](https://github.com/CollaboraOnline/online/assets/37268999/11a50aa0-8528-4984-b48b-66dd747322ad)

PDF document opened from Nextcloud in CODE after adding a comment, but before closing it.

![image](https://github.com/CollaboraOnline/online/assets/37268999/3eccdc26-4855-4c00-8a2f-e966e99603dd)

Reopened PDF document with comment in CODE, comment show it's still there

![image](https://github.com/CollaboraOnline/online/assets/37268999/679e2dd9-b463-4159-9dcd-ba2d71aee8e0)

Opened PDF document in NC PDF viewer, original page contend is schrinked to lower left corner showing a smalllll picture.

![image](https://github.com/CollaboraOnline/online/assets/37268999/3a067ea6-40aa-4ecf-80b3-1243ac8e2d73)

Server
    Nextcloud 27.0.2
    CODE:
    COOLWSD version: 23.05.2.2 (git hash: 91c166d (E))
    LOKit version: Collabora Office 23.05.2.2 (git hash: 22110b2)
    Served by: Debian GNU/Linux 12 (bookworm)
    Server ID: 0221ead1

Seen this issue with previous CODE builds too.

### Additional Context

-

**Comment by timur-g** [comment]
Can be reproduced when saving screenshot as PDF, or use this one. Reproduced already in 6.4 where comments were added.
 
[Screenshot saved as PDF.pdf](https://github.com/CollaboraOnline/online/files/12499800/Screenshot.saved.as.PDF.pdf)

**Comment by timur-g** [comment]
This was Core issue and should be fixed in 24.04.6 and 23.05.16.
@sebastiaanveld thanks for reporting and please test when available.
