### ISSUE TITLE
Calc: Drop down list (menu) in cells broken (23.05.2.2-1)

### ISSUE THREAD

**Issue by himpierre** [CollaboraOnline/online#7178]
### Describe the Bug

Hello Devs.

With the latest version (23.05.2.2-1) the drop down list in cells functionalty is not there anymore. It's similar to this collabora community post: https://forum.collaboraonline.com/t/calc-missing-drop-down-menu-since-update-to-21-11-4-on-ubuntu-20-04-3-lts/767

Key combination alt + arrow down still works.

### Steps to Reproduce

1. Open a xlsx file.
2. Click on a cell which usually has a drop down menu
3. No arrow visible to pull on

### Expected Behavior

Drop down list shoul be accessible.

### Actual Behavior

No arrow visible.

### Additional Context

We are using Collabora CODE with nextcloud 27.0.2 and Richdocuments 8.1.1. This happens with all browsers.

**Comment by Ezinnem** [comment]
Thanks for reporting @himpierre 
I think this issue is similar to https://github.com/CollaboraOnline/online/issues/6986
Please can you confirm that the issue described in https://github.com/CollaboraOnline/online/issues/6986 is what you are experiencing?

**Comment by himpierre** [comment]
> Thanks for reporting @himpierre I think this issue is similar to #6986 Please can you confirm that the issue described in #6986 is what you are experiencing?

Yes. Seems to be the same. Thanks.

**Comment by Ezinnem** [comment]
Alright.

I think it would be good to close this issue and follow-up on https://github.com/CollaboraOnline/online/issues/6986
