### ISSUE TITLE
In Columns dialog, plus/minus in spinfield doesn't adjust the value

### ISSUE THREAD

**Issue by thebearon** [CollaboraOnline/online#7236]
In Columns dialog, the number of columns can't be aligned using the +/- buttons.

- Open Columns dialog in Writer,
- Try increasing number of columns by pressing the `+` in the spinfield.

-> Number of columns stays the same.

It can be adjusted by editing the field manually.

CC @eszkadev.

**Comment by timur-g** [comment]
Regression:
commit 4b9cbab33db05b5ed601fbeb97fa0afc315f5bac
Author: Szymon Kłos <szymon.klos@collabora.com>
Date: Fri Aug 11 09:17:01 2023 +0200

jsdialog: fix spinfield precision detection

**Comment by timur-g** [comment]
Thanks.
