### ISSUE TITLE
Right-click on Calc tab of Read-only spreadsheet should not have a full menu

### ISSUE THREAD

**Issue by timur-g** [CollaboraOnline/online#7238]
Open Read-only spreadsheet in Online, see right-click.
It should have a limited menu or no menu at all, as none of the commands is possible.
Since there is no harm with current commands, I mark Enhancemet, 
![image](https://github.com/CollaboraOnline/online/assets/7240617/16b61d80-9455-4303-8fd1-37db849c8fcd)

**Comment by codewithvk** [comment]
I would like to work on it.

**Comment by timur-g** [comment]
@codewithvk feel free. Please explain the solution first.
