### ISSUE TITLE
Saving an xlsx file takes a long time

### ISSUE THREAD

**Issue by florian-bellencontre** [CollaboraOnline/online#7242]
### Describe the Bug

Saving an xlsx file takes a long time, and my tests have shown that the "P" column causes problems. Even if you delete all the data, the problem is still there.

### Steps to Reproduce

1. Upload [bug.xlsx](https://github.com/CollaboraOnline/online/files/12576351/bug.xlsx) file to Nextcloud
2. Start file editing
3. Save file
4. Depending on the number of CPUs allocated, this can take up to 50 seconds (4 threads)
5. If you delete the "P" column, the save is instantaneous

### Expected Behavior

Saving should be instantaneous

### Actual Behavior

Depending on the number of CPUs allocated, saving can take up to 50 seconds (4 threads).

### Server

 - **OS:** Debian 11
 - **Browser:** Firefox, Chrome, ect..
 - **Version:** 
```
root@collabora-1:~ # dpkg -l | grep collabora
ii  collaboraoffice                           23.05.3-1                      amd64        Brand module for Collabora Office 23.05
ii  collaboraoffice-ure                       23.05.3-1                      amd64        UNO Runtime Environment
ii  collaboraofficebasis-calc                 23.05.3-1                      amd64        Calc module for Collabora Office 23.05
ii  collaboraofficebasis-core                 23.05.3-1                      amd64        Core module for Collabora Office 23.05
ii  collaboraofficebasis-draw                 23.05.3-1                      amd64        Draw module for Collabora Office 23.05
ii  collaboraofficebasis-en-us                23.05.3-1                      amd64        Language module for Collabora Office 23.05, language en_US
ii  collaboraofficebasis-extension-pdf-import 23.05.3-1                      amd64        PDF import extension for Collabora Office 23.05
ii  collaboraofficebasis-graphicfilter        23.05.3-1                      amd64        Graphic filter module for Collabora Office 23.05
ii  collaboraofficebasis-images               23.05.3-1                      amd64        Images module for Collabora Office 23.05
ii  collaboraofficebasis-impress              23.05.3-1                      amd64        Impress module for Collabora Office 23.05
ii  collaboraofficebasis-math                 23.05.3-1                      amd64        Math module for Collabora Office 23.05
ii  collaboraofficebasis-ooofonts             23.05.3-1                      amd64        3rd party free fonts for Collabora Office 23.05
ii  collaboraofficebasis-ooolinguistic        23.05.3-1                      amd64        Linguistic module for Collabora Office 23.05
ii  collaboraofficebasis-writer               23.05.3-1                      amd64        Writer module for Collabora Office 23.05
root@collabora-1:~ # dpkg -l | grep cool
ii  coolwsd                                   23.05.3.1-1                    amd64        Collabora Online WebSocket Daemon
root@collabora-1:~ # dpkg -l | grep code-bra
ii  code-brand                                23.05-11                       all          Collabora Online Development Edition (CODE) branding
```

### Additional Context

If you unzip the [bug.xlsx](https://github.com/CollaboraOnline/online/files/12576351/bug.xlsx) file, you can see that the text "ça n’existait pas" remains in the sharedStrings.xml file. I think this is the problem.
```
cat xl/sharedStrings.xml 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="1" uniqueCount="1"><si><t xml:space="preserve">ça n’existait pas</t></si></sst>
```

**Comment by timur-g** [comment]
I see some slowness also in Core, but not this long.

**Comment by timur-g** [comment]
Collabora Online is based on LibreOffice Core, which also has a slowness - if I undertood the questions.
If you open XLSX as archive, you may see the app it was saved with in /docProps/app.xml.

**Comment by timur-g** [comment]
If file is resaved in MSO, than this line in sharedStrings.xml:
`<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="1" uniqueCount="1"><si><t xml:space="preserve">ça n’existait pas</t></si></sst>`
 is changed to:
`<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="1" uniqueCount="1"><si><t>ça n’existait pas</t></si></sst>`

Saving of that one is faster .
[7242 bug MSO.xlsx](https://github.com/CollaboraOnline/online/files/13000590/7242.bug.MSO.xlsx)

But new save with CO or LO again saves the same. So version does not seem relevant. 
This may be LibreOffice bug - I cannot say why saving is faster in LibreOffice than in Online.  Or file is corrupted. 

"ça n’existait pas" is a content in row 1048537, column P.
<row r="1048537" spans="16:16" x14ac:dyDescent="0.25">  <c r="P1048537" t="s"> <v>0</v> </c>

Cell tags that have a "t" attribute equal to "s" are string types. The value tag inside the c needs to be looked up and converted via the sharedStrings document. 
Excel stores strings that appear as cell values in a spreadsheet in a 'shared strings' document, as a space saving mechanism.
When the type of a cell is 's' then the value of a cell should be an integer - seems an issue here. 

Per https://learn.microsoft.com/en-us/archive/blogs/brian_jones/simple-spreadsheetml-file-part-3-formatting the style attribute ( "s" ) needs to be in the cells in the sheet and have it reference the third cell style. 
And here there is no something like  <c s="2">.

With all that, I will close this. Cannot say I am 100% sure but does not seem like Online originated issue.
