### ISSUE TITLE
Android app 23.05 slower than 21.11 when opening complex PDF

### ISSUE THREAD

**Issue by timur-g** [CollaboraOnline/online#7247]
Download https://www.careerladdersproject.org/docs/the%20Financial%20aid%20challenge.pdf and try to open in Android app.
Android app 23.05 is pretty slower than 21.11 when opening complex PDF.
Does not seem to be related to dark/light mode.

**Comment by timur-g** [comment]
On a second test, I do not see a difference. @Ezinnem can you please also test? Feel free to close if no repro.

**Comment by Ezinnem** [comment]
I tested with the sample you provided.

Opening the PDF file does not seem slow on my end. I clicked on the file, and it took about 7 seconds to load and open

Tested on:
COOLWSD version: 23.05.4.1 git hash: [938be31](https://github.com/CollaboraOnline/online/commits/938be31)
LOKit version: Collabora Office 23.05.4.1 [78039c5](https://hub.libreoffice.org/git-core/78039c5)

https://github.com/CollaboraOnline/online/assets/54344301/1168af6a-d38e-426e-860a-781860e07717
