### ISSUE TITLE
Enregistrement doc

### ISSUE THREAD

**Issue by EloEdwyge** [CollaboraOnline/online#7253]
Sur un doc tableur, lors de l'enregistrement automatique ou lors d'un enregistrement volontaire, je reçois un message d'erreur "Le document n'a pas pu être enregistré, veuillez vérifier vos droits" alors que je suis en compte Admin.

**Comment by timur-g** [comment]
This is English only forum, please write English directly or using translation tools.
What is your exact Online version? Please paste here from Help/ What is your WOPI host, integration?
Does that happen all the time or sometimes? 
Does that happen if you press Save multiple times?

**Comment by thebearon** [comment]
Including machine translation of the original post here:
```
On a spreadsheet document, during automatic saving or during voluntary registration, I receive an error message "The document could not be saved, please check your rights" even though I am in the Admin account.
```

Since there has been no reply, let's close.
