### ISSUE TITLE
Impress: deleting objects in a slide, removes the whole slide

### ISSUE THREAD

**Issue by fbim-genosr** [CollaboraOnline/online#7255]
### Describe the Bug

When deleting an object on a slide via backspace key, e.g. some characters in a text object, the whole slide is deleted.

### Steps to Reproduce

1. Create a new presentation.
2. Add several slides.
3. Create a text object on a slide and enter some text.
4. Select another slide an select the slide with the created text object again.
5. Click into the text object to delete some characters by pressing backspace key.
6. The whole slide will be removed.

### Expected Behavior

Just the selected object should be removed.

### Actual Behavior

The whole slide will be removed. 

### Screenshots

![Collabora-Bug](https://github.com/CollaboraOnline/online/assets/37347715/cc0cfcfb-505d-47fb-8084-34b5797a5afd)

### Desktop

 - **OS:** Windows 10
 - **Browser:** Firefox
 - **Version:** 117.0.1

### Additional Context

While selecting the text object, the slide in slide view is selected as well. Maybe its a problem with the focus.

**Comment by timur-g** [comment]
Please write Collabpra version, seen from Help.

**Comment by Ezinnem** [comment]
This issue occurred in the past and reported in https://github.com/CollaboraOnline/online/issues/7062

It was fixed at https://github.com/CollaboraOnline/online/pull/6070

@fbim-genosr please feel free to comment the Collabora Version as directed by @timur-g

**Comment by fbim-genosr** [comment]
> Please write Collabpra version, seen from Help.
 
Collabora Office 22.05.10.7 git hash: [d1b6e23]

> Is that reproducible for you for any slide, or just some? 

Yes, it happens in all slides.

**Comment by timur-g** [comment]
It was fixed in 22.05.12 and current version is 22.05.19. Please always update and search before reporting.
