### ISSUE TITLE
Android: This app isn't available for your device because it was made for an older version of Android

### ISSUE THREAD

**Issue by kolAflash** [CollaboraOnline/online#7262]
PlayStore does not let me install Collabora Office on my friends device.
_Please excuse my short issue description. I'm writing this on my Android device._

Galaxy Tab S7 FE   
SM-T733  
Android 13  
https://en.wikipedia.org/wiki/Samsung_Galaxy_Tab_S7

https://play.google.com/store/apps/details?id=com.collabora.libreoffice  
App version:  
21.11.6.1 (updated 2022-08-12)  
Target SDK version:  
30 (Android-11, which should not be too old)

Message:  
`This app isn't available for your device because it was made for an older version of Android`

Original German message (device is set to German):  
`Diese App ist für dein Gerät nicht verfügbar, weil sie für eine ältere Android-Version entwickelt wurde`

&nbsp;

I searched the web for that error message and other apps seem to suffer from it too. Here it seems app developers were able to do something about it.  
https://de.geneanet.org/forum/viewtopic.php?t=821996#post_content2359464

&nbsp;

P.S.  
On the other hand installation just worked fine on a Google Pixel 4a, running Android-13.  
https://en.wikipedia.org/wiki/Pixel_4a

**Comment by timur-g** [comment]
21.11 really was the latest version for long, but Collabora has just released Andorid app 23.05 for all in Play Store.
Please install this last version.
