### ISSUE TITLE
Calc: Chart trend line 'type' options have no effect

### ISSUE THREAD

**Issue by Smegheid** [CollaboraOnline/online#7265]
### Describe the Bug

After adding a trendline to a chart, double-clicking the trendline brings up a dialogue with 'type' and 'line' tabs to control aspects of the trendline. The 'line' tab controls formatting of the displayed trendline, while the 'type' options control the regression type, etc.

The controls in the 'type' tab do not work; when selected, they do not take effect.

### Steps to Reproduce

I'm going to refer to this simple example spreadsheet: [test trendline.ods](https://github.com/CollaboraOnline/online/files/12612921/test.trendline.ods). This is nothing interesting - it has a simple data series that consists of random values on top of a small upwards linear trend to test that trendlines are sensible, and a chart of that data with a linear trendline applied.

To reproduce:

1. Open the example spreadsheet.
2. Double-click the chart to edit the chart.
3. Double-click the trendline to bring up the "Trend line for Data Series 'y' dialogue.
4. Click the Type tab.
5. Attempt to show the equation of the linear trend by selecting 'Show Equation', then press 'OK'. The dialogue will be dismissed, but the equation will not be shown.
6. Bring up the dialogue again. Note that 'Show Equation' is not checked, despite having been selected in the previous step.
7. Attempt to change the trendline name. This will have no effect.
8. Attempt to change the regression type to anything but linear. This will have no effect.

### Expected Behavior

Changes in the 'type' tab should be reflected in the chart:

- After step 5, the equation for the linear fit should be displayed in the chart.
- After step 7, the name of the trend line should be displayed.
- After step 8, the type of the regression should be changed and the trend line should no longer be linear.

Note that when performing the same operations on this spreadsheet locally with libreoffice, all of the steps work and the expected behaviour is exhibited. The tested version of libreoffice was:

Version: 7.3.7.2 / LibreOffice Community
Build ID: 30(Build:2)
CPU threads: 16; OS: Linux 6.2; UI render: default; VCL: gtk3
Locale: en-US (en_US.UTF-8); UI: en-US
Ubuntu package version: 1:7.3.7-0ubuntu0.22.04.3
Calc: threaded

Additionally, when the trendline modifications made with libreoffice are saved and then opened with collabora, they are displayed as expected, so the problem appears to be in the dialogue.

### Actual Behavior

Explained in the reproduction steps above. While the description is not exhaustive in testing all the controls in the tab, it appears that none of them work.

### Screenshots

Videos probably make this more obvious than a series of screenshots.

Short screen capture video of the dialogue settings not sticking in Collabora calc: [Screencast from 09-14-2023 10:25:31 AM.webm](https://github.com/CollaboraOnline/online/assets/1828208/bb510b3c-1ee0-4332-a9a9-f468d03a31a0)

Demonstration of same steps working as expected in Libreoffice calc: [Screencast from 09-14-2023 10:33:19 AM.webm](https://github.com/CollaboraOnline/online/assets/1828208/a9b2b821-b2e3-4634-b3ca-f295f14e706b)

### Desktop

On the client side, I have tried this on:
- Ubuntu 22.04 64-bit:
  -  Chrome 116.0.5845.187
  -  Firefox 117.0
- Windows 10 64-bit:
  - Chrome 117.5938.63

### Server

I've tested this on three different servers:
- A personal test server.
- Collabora's demo owncloud server
- Collabora's demo nextcloud server

All three show the same hehaviour, including the demos of the commerical offerings. The latter two suggest that I've not done a dumb with my installation.

My system runs Ubuntu 22.04 server  with the current set of Nextcloud AIO containers. The reported version info in Help -> About is:

COOLWSD version: 23.05.3.1 (git hash: a719c0f (E))
LOKit version: Collabora Office 23.05.3.1 (git hash: 403de15)
Served by: Debian GNU/Linux 12 (bookworm)
Server ID: 8ae9fe66

Collabora's demo owncloud system reports:

COOLWSD version: 23.05.4.1snapshot (git hash: b3abc03)
LOKit version: Collabora Office 23.05.4.20230913 (git hash: c148e51)
Served by: Ubuntu 18.04.6 LTS
Server ID: b59496ab

Collabora's demo nextcloud system appears to be running the same thing:

COOLWSD version: 23.05.4.1snapshot (git hash: b3abc03)
LOKit version: Collabora Office 23.05.4.20230913 (git hash: c148e51)
Served by: Ubuntu 18.04.6 LTS
Server ID: b59496ab

**Comment by eszkadev** [comment]
Thanks for reporting. Fix in the core: https://gerrit.libreoffice.org/c/core/+/157031

**Comment by eszkadev** [comment]
merged
