### ISSUE TITLE
Can't edit documents in iOS

### ISSUE THREAD

**Issue by yumecosmos** [CollaboraOnline/online#7304]
### Can't edit LibreOffice documents in Collabora Office iOS app

Hello, I've been using this app for a while now, so first let me just say thank you for creating it! 

It seems like since the latest update I'm no longer able to edit text in any documents (odt), spreadsheets, or presentations in iOS mobile. Changing formatting - bold, italic, alignment, etc. - in existing documents works, and so does cut/paste. I'm able to save those changes as well as rename files, so it doesn't seem like they're read-only or anything.

I also tried removing and reinstalling from the app store to make sure I had the latest version.

### Steps to Reproduce

1. Create a new document (or open an existing one.)
2. Click the edit button.

### Expected Behavior

Should be able to insert/delete characters.

### Actual Behavior

The keyboard appears, but typing doesn't do anything.

### Smartphone

 - **Device:** iPhone 7
 - **OS:** 15.7.9
 - **Browser:** n/a
 - **Version:** 23.05.4.1

Apologies if this is not much to go on... I realize it's probably not an issue for all iPhones or someone would have noticed by now. Will try on a different phone as soon as I can borrow one.

**Comment by Ezinnem** [comment]
I am able to create and edit documents using the latest Collabora Office app on iPad.

Please can you share a screen recording showing this issue?

**Comment by yumecosmos** [comment]
Ok! Here's a quick demo with an existing document and then a new one. (Zipped because the file was too large, if that's no good I can split it up.)
[AMCY5983.zip](https://github.com/CollaboraOnline/online/files/12734335/AMCY5983.zip)

Sorry for all the scrolling up and down... Another thing I didn't pay much attention to until recording this is that when in edit mode, it seems like the keyboard opens more often than it used to. For example, when undoing a formatting change or after opening the hamburger menu. Could that be related?

**Comment by rpear** [comment]
Tested on another iPhone, and it tested OK:
Device: iPhone 12
OS: 17.0.1
Browser: n/a
Version: 23.05.4

**Comment by yumecosmos** [comment]
Ah, thanks! (I haven't found someone with a newer iPhone yet, most of my family has Android.)
Guessing maybe the issue is just that my phone/OS is too old then? In that case sorry to bother you!
Should I go ahead and close this?

**Comment by Ezinnem** [comment]
Thank you for submitting the report. Based on the information provided, I believe it is safe to close the issue for now. However, please let me know if you have any additional details to share.

**Comment by ianfrankmcg** [comment]
I have the same issue with two phones running iOS 15.7.9, an iPhone 7 and an original iPhone SE. I can effectively no longer edit text or spreadsheet documents even though the keyboard appears. I don't have a later iOS to test with and those phones are on the latest iOS that they will run.

The App Store states that Collabora Office will run from iOS 14.5, which for editing seems to be no longer the case.
