### ISSUE TITLE
/usr/bin/coolmount: unmount failed to detach [/opt/cool/child-roots]: Operation not permitted.

### ISSUE THREAD

**Issue by PatrickHsu36** [CollaboraOnline/online#7313]
### Describe the Bug

I deploy docker in the NAS without problem before, but now I encounter an issue on a new arm64 platform.

The first errors are, this is the different log with other arm64 platform which works normally.

/usr/bin/coolmount: unmount failed to detach [/opt/cool/child-roots]: Operation not permitted.
/usr/bin/coolmount: forced unmount of [/opt/cool/child-roots] failed: Operation not permitted.
wsd-00001-00001 2023-09-27 13:55:01.298608 +0800 [ coolwsd ] DBG  Failed to unmount [/opt/cool/child-roots/]| common/JailUtil.cpp:98
wsd-00001-00001 2023-09-27 13:55:01.298751 +0800 [ coolwsd ] DBG  Removing [/opt/cool/child-roots/] only.| common/FileUtil.cpp:269

...

Finally, it always loop the followings logs, and the container failed to be executed normally.

wsd-00001-00030 2023-09-27 14:02:14.308212 +0800 [ prisoner_poll ] TRC  #7: Handling events of wakeup pipe: 0x0| net/Socket.cpp:363
wsd-00001-00030 2023-09-27 14:02:14.308261 +0800 [ prisoner_poll ] TRC  #16: Handling poll events of prisoner_poll at index 0 (of 1): 0x0| net/Socket.cpp:455
wsd-00001-00030 2023-09-27 14:02:14.308309 +0800 [ prisoner_poll ] TRC  Executing SocketDisposition of #16: Type::CONTINUE| net/Socket.cpp:689
wsd-00001-00030 2023-09-27 14:02:14.308357 +0800 [ prisoner_poll ] TRC  #16: setupPollFds getPollEvents: 0x1| net/Socket.hpp:844
wsd-00001-00030 2023-09-27 14:02:14.308400 +0800 [ prisoner_poll ] TRC  ppoll start, timeoutMicroS: 5000000 size 1| net/Socket.cpp:341
### Steps to Reproduce

docker create -i -t --name=CollaboraCODE --privileged \
	--cap-add SYS_ADMIN --cap-add MKNOD \
	-p 29980:9980 \
	-e aliasgroup1=http://$NAS_HOST \
	-e username=admin \
	-e password=dockercollabora \
	-e extra_params=--o:ssl.enable=false \
	-v /etc/localtime:/etc/localtime:ro \
	--restart unless-stopped \
	collabora/code:latest

No matter I add --cap-add or not, the result are the same.

How can I do for this ?
Thanks a lot.

**Comment by DaanSelen** [comment]
It looks like some files inside the child-roots are owned by root:root instead of cool:cool which makes it unable to interact, I assume...

**Comment by timur-g** [comment]
Please write your current status, is this resolved with 24.04? 
If not, are many changes in 24.04.5, including https://github.com/CollaboraOnline/online/pull/9572.

**Comment by DaanSelen** [comment]
Collabora Online server is reachable.
Collabora Online Development Edition 24.04.5.2 ca2ed20

When closing a document inside NextCloud:
```
sh: 1: /usr/bin/coolmount: Operation not permitted
sh: 1: /usr/bin/coolmount: Operation not permitted
sh: 1: /usr/bin/coolmount: Operation not permitted
```
Also:
```
frk-00027-00027 2024-07-26 12:14:45.387022 +0200 [ forkit ] WRN  The systemplate directory [/opt/cool/systemplate] is read-only, and at least [/opt/cool/systemplate//etc/hosts] is out-of-date. Will have to copy sysTemplate to jails. To restore optimal performance, make sure the files in [/opt/cool/systemplate/etc] are up-to-date.| common/JailUtil.cpp:557
frk-00027-00027 2024-07-26 12:14:45.399638 +0200 [ forkit ] WRN  The systemplate directory [/opt/cool/systemplate] is read-only, and at least [/opt/cool/systemplate//etc/hosts] is out-of-date. Will have to copy sysTemplate to jails. To restore optimal performance, make sure the files in [/opt/cool/systemplate/etc] are up-to-date.| common/JailUtil.cpp:557
frk-00027-00027 2024-07-26 12:14:45.411352 +0200 [ forkit ] WRN  The systemplate directory [/opt/cool/systemplate] is read-only, and at least [/opt/cool/systemplate//etc/hosts] is out-of-date. Will have to copy sysTemplate to jails. To restore optimal performance, make sure the files in [/opt/cool/systemplate/etc] are up-to-date.| common/JailUtil.cpp:557
frk-00027-00027 2024-07-26 12:16:43.499814 +0200 [ forkit ] WRN  The systemplate directory [/opt/cool/systemplate] is read-only, and at least [/opt/cool/systemplate//etc/hosts] is out-of-date. Will have to copy sysTemplate to jails. To restore optimal performance, make sure the files in [/opt/cool/systemplate/etc] are up-to-date.| common/JailUtil.cpp:557
```
When I started the container with the image called `collabora:code:latest` built on 17-07-2024.
Nextcloud version: 29.0.3

**Comment by timur-g** [comment]
@DaanSelen you tested in #9220 which is related or duplicate. And for that, you may wait for the next version, or build the docker. 
Here, I asked @PatrickHsu36 to comment, hopefully to close.

**Comment by DaanSelen** [comment]
I will await @PatrickHsu36's response and if he also does not receive this specific issue, close this issue as solved.

**Comment by PatrickHsu36** [comment]
> @DaanSelen you tested in #9220 which is related or duplicate. And for that, you may wait for the next version, or build the docker. Here, I asked @PatrickHsu36 to comment, hopefully to close.

Sorry for late reply.
The issue is resolved on 24.04.4. 
Thanks !!

**Comment by PatrickHsu36** [comment]
The issue is resolved on 24.04.4.
Thanks !!

**Comment by sebastianfischer** [comment]
We have the same or similar problem on 24.04.7.1.1 with official docker code image from docker hub.

We get following error message:

```
notcoolmount: unmount failed to detach [/opt/cool/child-roots/<somepath>]: Operation not permitted.
notcoolmount: forced unmount of [/opt/cool/child-roots/<somepath>] failed: Operation not permitted.
```

Over time the directory `/opt/cool/child-roots/` grows to 20+ GBs within 12 hours and finally fills up our VM with 40 GB storage. Restart helps and frees storage.

container is running with privileged, all files / dirs under `/opt/cool/child-roots` have owner/group `cool:cool`

**Comment by DaanSelen** [comment]
> We have the same or similar problem on 24.04.7.1.1 with official docker code image from docker hub.
> 
> We get following error message:
> 
> ```
> notcoolmount: unmount failed to detach [/opt/cool/child-roots/<somepath>]: Operation not permitted.
> notcoolmount: forced unmount of [/opt/cool/child-roots/<somepath>] failed: Operation not permitted.
> ```
> 
> Over time the directory `/opt/cool/child-roots/` grows to 20+ GBs within 12 hours and finally fills up our VM with 40 GB storage. Restart helps and frees storage.
> 
> container is running with privileged, all files / dirs under `/opt/cool/child-roots` have owner/group `cool:cool` 

Issue #9220?
