### ISSUE TITLE
Calc: Grid lines render issue with firefox on linux

### ISSUE THREAD

**Issue by soeffi** [CollaboraOnline/online#7316]
### Describe the Bug

Not sure if this is actually a bug in Collabora, but I'd be glad if someone could help me out:

Using Code Calc (23.05.4.2, via docker, integrated in nextcloud) with firefox (118.0) on linux, grid lines are rendered as thick light grey lines, see screenshot below. Grid lines are distracting from actual contents, greatly limiting efficient use.

Interestingly, everything works fine with firefox on Windows and with Chromium on linux.

### Steps to Reproduce

Open Collarbora Calc with firefox on linux.

### Expected Behavior

Grid rendered with sharp lines as observed in other browsers.

### Actual Behavior

Grid is rendered with muddy, thick lines

### Screenshots

![grafik](https://github.com/CollaboraOnline/online/assets/28978584/1fd9e208-a3df-42b5-b35e-8ceb99c41078)

### Desktop

(Please complete the following information)
 - **OS:** Ubuntu 22.04.3 LTS
 - **Browser:** Firefox
 - **Version:** 118.0

**Comment by timur-g** [comment]
Really.. and it seem recent, I do not see it in ESR 102.15, but I see it in 117 (that is ESR 115).
![image](https://github.com/CollaboraOnline/online/assets/7240617/486d5ffc-1d16-45ea-bcab-13551bf42b28)

**Comment by mmeeks** [comment]
@timur-g can you link the up-stream firefox ticket here too ? =) or didn't we get far with that ?

**Comment by timur-g** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1857185

**Comment by mmeeks** [comment]
If the up-stream Mozilla "anti-aliasing" acceleration makes it impossible to draw accelerated lines with firefox - quite possibly we need to detect that browser and do pixel bashing instead to get the same result; hopefully only for firefox.

**Comment by Tex2002ans** [comment]
Looks like someone also posted a related issue on the Mozilla bugtracker:

- [Bug #1867194: "Canvas sizes beyond 127 x 127 can anti-alias paths when they shouldn't"](https://bugzilla.mozilla.org/show_bug.cgi?id=1867194)

Both that one+ours seems to have regressed on the same Firefox 115 issue 9 months ago:

- [Bug #1834079: "https://add-perf-dashboard--speedometer-preview.netlify.app/?suite=Perf-Dashboard is falling back to Skia"](https://bugzilla.mozilla.org/show_bug.cgi?id=1834079)

**Comment by mmeeks** [comment]
Thanks - would be good to cross-link the tickets if not =)

**Comment by mmeeks** [comment]
@Cwiiis fairly annoying browser bug - would it be something that you could look at implementing a "draw horizontal or vertical hair-line" method that performs reasonably well in firefox ? and then using that - particularly for spreadsheet grid-lines (rendered in the browser), but I guess also all around the place where we use the canvas (?) =)

Alternatively - if it's easy to fix in firefox, we should do that I suppose but ... ;-> shaders + other nightmares probably make that not so easy. Thoughts ?

**Comment by mmeeks** [comment]
Should be fixed in the next release; thanks for reporting ! =)
