### ISSUE TITLE
Menu items in English and Brazilian Portuguese instead of only Brazilian Portuguese (pt-BR)

### ISSUE THREAD

**Issue by lpwxyz** [CollaboraOnline/online#7319]
### Describe the Bug

Bumping collabora/code from 23.05.2.2.1 to 23.05.4.2.1 is causing some issues with the menu. Some words are on English and others are on Brazilian Portuguese.

Only "Inserir", "Referências" and "Leiaute" are brazilian portuguese words. The others are in english.

### Steps to Reproduce

1. Open the editor using lang=pt-BR

### Expected Behavior

It should show the menu items in Brazilian Portuguese (pt-BR)

### Actual Behavior

Menu items are shown in English and Brazilian Portuguese.

### Screenshots

![image](https://github.com/CollaboraOnline/online/assets/98703110/f0a9db9e-572c-4bae-a677-cbca8ff1d29d)

### Desktop

(Please complete the following information)
 - **OS:**: Linux
 - **Browser:** Firefox
 - **Version:** : 118.0

**Comment by timur-g** [comment]
pt 
![image](https://github.com/CollaboraOnline/online/assets/7240617/aa33a68b-4031-47bf-9486-aa134878cbe3)

pt-BR
![image](https://github.com/CollaboraOnline/online/assets/7240617/c15f515a-35b7-4e7f-9da8-bc204ebda093)

**Comment by timur-g** [comment]
@lpwxyz could you fix it yourself?
Go to https://hosted.weblate.org/projects/collabora-online/ui/pt_BR/ ,( register), Browse, find wrong strings like ex. File is translated as "~Arquivo", remove ~ and uncheck "Needs Editing". 
Of course you may also add missing translation as pt-br is 91% translated.

**Comment by lpwxyz** [comment]
> @lpwxyz could you fix it yourself? Go to https://hosted.weblate.org/projects/collabora-online/ui/pt_BR/ ,(need to register), Search for the string there, (there's a Search tab at the top, not the Search field, but next to Overview / Info ...), find wrongly shown strings like ex. File, see it is translated as "~Arquivo", remove ~ and "Needs Editing" should be unchecked. Of course you may also add missing translation as pt-br is 91% translated.

I will give it a shot, thanks.

**Comment by timur-g** [comment]
Fixed for 23.05.5.
