### ISSUE TITLE
Calc: tabbed view: Sparkline: Format options don't work

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#7321]
### Steps to Reproduce

1. The issue is reproducible only using Tabbed View (notebookbar).
2. No option in Format->Sparklines submenu is working

### Expected Behavior

Compact mode works. It should also work on tabbed view.

Where:
https://staging-perf.eu.collaboraonline.com/nextcloud/index.php/s/tESPC8GKwiMTXaQ

**Comment by timur-g** [comment]
I do not reporduce this locally not on staging.eu. There must be some detailll.

**Comment by gmasei11** [comment]
> I do not reporduce this locally not on staging.eu. There must be some detailll.

The scenario from the description is not the right one. Please see the below one:
1. The issue is reproducible only using Tabbed View (notebookbar).
2. No option in Format->Sparklines submenu is working

**Comment by pedropintosilva** [comment]
For me  even the insert didn't work, but let me edit the description

**Comment by timur-g** [comment]
Thanks.
