### ISSUE TITLE
23.05 : Navigator changing language during typing when user have different languages.

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#7322]
### Describe the Bug

Steps:

1. Share a link to a .ods with one user (User A) in English.
2. Using the Link open the file in an incoginto mode.
3. Change the language and locale setting of User B (I changed to German (Germany) and Deutshe)
4. Open the same .ods file

Open the navigator in both users.

The more users (probably because they are using different languages) the faster  the shifting

https://github.com/CollaboraOnline/online/assets/65948705/ac623cf0-a814-49dd-964f-a6303036edba

**Comment by Ezinnem** [comment]
Tracked internally [here](https://github.com/CollaboraOnline/online/issues/7322)

**Comment by pedropintosilva** [comment]
Szymon: Navigator works the same way as the normal sidebar and that doesn’t happen with normal sidebar so… probably there is a core problem related solely with Navigator.

**Comment by thebearon** [comment]
According to @aszucs3 this should be fixed now.
