### ISSUE TITLE
Delete key not always working in cell fields or formula bar

### ISSUE THREAD

**Issue by nooblag** [CollaboraOnline/online#7339]
### Describe the Bug

Can backspace text, but delete key doesn't always work.

Hard to reproduce in a new document, but definitely more noticeable in older or busier spreadsheets.

### Steps to Reproduce

1. Start new sheet.
2. Enter text into cell.
3. Add more text into cell, try to delete the old text. Sometimes works, sometimes doesn't.

### Expected Behavior

Delete key should always delete text after the cursor.

### Actual Behavior

Delete works sometimes, but not others.

### Screenshots

In this example, with the issue appears in the A1 cell when trying to delete the text after 'sss' which doesn't work for multiple presses, but then does start working.

https://github.com/CollaboraOnline/online/assets/1122344/ee51bdb9-d4bf-4668-8188-a16414534a4d

### Desktop

(Please complete the following information)
 - **OS:** Linux Mint 21.2
 - **Browser:** Firefox
 - **Version:** 118.0

**Comment by Ezinnem** [comment]
As a workaround, you can use the backspace key

**Comment by nooblag** [comment]
Haha sure, but it's still a bug. Can you reproduce?

**Comment by Ezinnem** [comment]
I have confirmed it, although it is not readily reproducible.

@Rash419 or @eszkadev may like to take a look.

**Comment by pedropintosilva** [comment]
Let me assign this to @GulsahKose

**Comment by pedropintosilva** [comment]
Couldn't' reproduce it

**Comment by nooblag** [comment]
It is difficult to encounter, yes.

Do you mean you do not experience the issue at all?

**Comment by thebearon** [comment]
@nooblag Do you encounter this in the latest update? It's probably been resolved by #7522.

**Comment by nooblag** [comment]
Thanks for following up. I haven't encountered the problem in a while, so let's say it's fixed :) Thanks!

**Comment by thebearon** [comment]
Glad to hear that, closing the issue, then.
