### ISSUE TITLE
User listed multiple times with tabs.

### ISSUE THREAD

**Issue by barvirm** [CollaboraOnline/online#7347]
### Describe the Bug
Hello, I'm not sure if it's a bug, but if you open the same document in multiple tabs you are listed numerous times in users.

### Steps to Reproduce
1. Open document in Collabora
2. Open the same document in the second tab.

### Expected Behavior
Only one listed user.

### Actual Behavior
![image](https://github.com/CollaboraOnline/online/assets/15948420/a9bc3549-20ec-4125-81eb-a2bdb5c7c254)

### Desktop (Docker collabora/code:latest)
 - Windows 11 
 - Chrome
 - 117

**Comment by timur-g** [comment]
Not a bug.
