### ISSUE TITLE
Freeze a line gets changed when moving between sheets

### ISSUE THREAD

**Issue by JensTheCoder** [CollaboraOnline/online#735]
**Describe the bug**
Freeze a line doesn't stick to the selection when moving to another sheet (tabs at the bottom) and then coming back. Actually, the frozen line appears on another line when moving to another tab and coming back.

**To Reproduce**
1. Create a bigger calc file with multiple tabs (sheets)
2. Chosse freeze lines and columns
3. Move to another sheet and then come back. Do this a few times.

**Expected behavior**
When freeze lines and columns is chosen for a specific selection on a tab, it belongs only to this tab. And, when moving to another tab, and then coming back, the freeze will still be applied to the selection made before in this tab only.

**Actual behavior**
Freeze lines and columns doesn't stick to the selection when moving to another sheet.

**Desktop (please complete the following information)**
 - OS: ubuntu desktop 20.04 lts
 - Browser: Firefox
 - Version: 82.0.3

**Server**
 - OS: ubuntu server 20.04 lts
 - Nextcloud: Snap package, version 20.01
 - collaboraoffice: ppa, version 6.4.10.11
 - Reverse proxy: apache2

**Comment by thebearon** [comment]
Can you please check again with a fresh version?

**Comment by Ezinnem** [comment]
Closing this issue due to lack of reply from the author.
