### ISSUE TITLE
Calc: sheet tab: triggering context menu switches tabs

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#7354]
### Describe the Bug

https://github.com/CollaboraOnline/online/assets/65948705/2b181f55-bd1e-4777-8d76-1212650e39ea

Right click (or long tab when using mobile or tablet) on a sheet tab triggers the contact menu **but** it also automatically switches the active tab. Result, user is now in a completely different sheet tab when the user just wanted to access the context menu of said sheet tab.

### Steps to Reproduce

1. Open a file in edit mode 
2. Right click (or long tap on mobile or tablet)
3. Context menu appears and at the same time user is now thrown to another sheet tab

### Expected Behavior

Do not switch sheet tabs when context menu is triggered. 

### Version

Master a8e97f6220790611f0626649fc3e69578ae9c470

**Comment by pedropintosilva** [comment]
@bayramcicek can you take this one?

**Comment by bayramcicek** [comment]
yes, working on it...
