### ISSUE TITLE
Calc: groupping doesn't work 

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#7369]
If you have multiple groups, one inside of the other then it seems impossible to show/hide all of them. It seems that only the top parent becomes responsive and all the others do not react to the click.

This was reported by Julius in the chat. Specifically: when trying to work with column groups

**But** both parent and child groups need to start at the same column.

1. Select A to F Columns
2. Data tab -> Group
3. Select A to C
4. Data Tab -> Group

Now collapsing the child group also collapses the parent group

**Comment by pedropintosilva** [comment]
let me assigned to you @bayramcicek : )

**Comment by bayramcicek** [comment]
notes:
- double clicking on a group's tail closes the groups correctly.
- but with expand (`+`) and collapse (`-`) buttons, only the top-parent is responsive to the click.

**Comment by timur-g** [comment]
Fixed in 23.05.
