### ISSUE TITLE
perf: surprisingly little delta threading ...

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#7374]
Surprisingly - looking at a profile like: https://user-images.githubusercontent.com/833656/272874219-79c39c7c-a482-4d3c-b9bf-6cfabfa56f2e.svg

Even for calc when large areas are invalidated - and we would expect lots of tiles to be rendered in a single pass, and for them to be 'createDelta'd in at least 4 threads (by default) - instead we see tons of work done in the main thread: ThreadPool::runOne - 22bn samples in the main thread, and 7bn samples for ThreadPool::runOne in all other threads it seems.

That's a really surprising result - and a quick skim of the code doesn't reveal anything particularly immediately obvious - except that if there is only a single tile - then we do the work in the main thread.

So - it is entirely possible that (in error) we are rendering calc scenes (and perhaps elsewhere) - not as large areas of tiles as we should in a single render pass - but as many individual tiles: which is far less optimal, and less susceptible to threading. It would be good to instrument the tilecombine / rendering process to see what is going on there - and how many tiles we are rendering at once: quite possibly there is some silly here.

@caolanm is it possible that sorting rendering by how old the request was may have somehow fragmented the rendering queue ? =)

**Comment by mmeeks** [comment]
The threads should do:

-   if (!_shutdown && !_work.empty())
=  while (!_shutdown && !_work.empty())

How silly :-) well worth a backport I think too.

**Comment by caolanm** [comment]
This is a lengthy writer collaborative editing session after this patch was applied now with a much more substantial 10% wide ThreadPool

![perf-14171](https://github.com/CollaboraOnline/online/assets/833656/acdd222e-243c-4a20-b5c8-8295e2a09e94)
