### ISSUE TITLE
loolwsd service won't start with 6.4.1-3 -- unit file restrictions too tight

### ISSUE THREAD

**Issue by lelutin** [CollaboraOnline/online#739]
**Describe the bug**
Using debian 9 (stretch) with packages from: `https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-debian9`

All servers that upgraded to the 6.4.1-3 package this morning could not start the loolwsd service. The only output in journalctl was about `/var/log/loolwsd.log` being read-only even though the file had the "lool" group and read-write permissions for the group.

After investigating, we found that modifying the unit file `/lib/systemd/system/loolwsd.service` to change the line that starts with `ReadWritePaths` to add `/var/log` to it in the following fashion made the service start back up again:

~~~
ReadWritePaths=/opt/lool /var/log
~~~

**Comment by lelutin** [comment]
ah, and additionally: starting the service manually without the unit file was working so it confirmed that the systemd unit file was causing the issue and not collabora online itself.

**Comment by lelutin** [comment]
this also happened on debian 10 (buster) servers with packages from `https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-debian10`

**Comment by timar** [comment]
Many thanks for finding this bug. I'll release 6.4.1-4 ASAP.

**Comment by timar** [comment]
I released fixed packages.
