### ISSUE TITLE
Transifex is proprietary

### ISSUE THREAD

**Issue by fitojb** [CollaboraOnline/online#74]
Please move to a libre, self-hosted solution for your translation platform.

**Comment by wget** [comment]
Hi @fitojb. Thanks for your feedback :) We had evaluated some translation solutions and we ultimately chose Transifex. But indeed, according to the first bunch of feedbacks we received from the Collabora Online community, we may chose another solution for the future. We are listening to what the community prefers :)
^WG

**Comment by fitojb** [comment]
May I suggest Weblate?

While I have used Transifex in the past, I’m not comfortable sharing my user data and TM with it anymore.

**Comment by wget** [comment]
@fitojb You're trying to convince someone already convinced by Weblate :P I followed the Weblate transition at TDF and was partially responsible for the Pootle -> Weblate migration at Mattermost ^^. I'm still trying to figure out the exact reasons why it has been chosen here. I think internally some Collaborans were more used to work with Transifex and were preferring it (projects like Netxcloud is using it), hence the switch. Pushing Weblate is something I'm trying as well (some people are indeed complaining about the use of Transifex), but am not promising any success ;)

**Comment by mmeeks** [comment]
As I said on telegram - and perhaps didn't make it here - we are not emotionally attached to Transifex. We're investigating moving to weblate indeed. and are exploring that options as of now.
Thanks for the feedback ! =) I've re-titled the bug to reflect that, and Kendy is investigating this.

**Comment by pedropintosilva** [comment]
https://collaboraonline.github.io/post/translate/ updated :heart: #weblate
