### ISSUE TITLE
Cells and text are ver small and there is no way to resize

### ISSUE THREAD

**Issue by smoofra** [CollaboraOnline/online#740]
Cells and text are very small and there is no way to resize

**Steps to Reproduce**
1. Install from nextcloud apps menu
2. make a spreadsheet
3. edit it  in nextcloud
4. everything is too small, oh no.

**Expected behavior**
Text should be a reasonable size or there should at least be a zoom option in the view menu.

**Actual behavior**
Text is way too small and there doesn't seem to be an option to fix it.

**Screenshots**
<img width="675" alt="Screen Shot 2020-11-20 at 11 42 01 AM" src="https://user-images.githubusercontent.com/3013304/99842839-6a2c3b00-2b25-11eb-97d7-e9a3e58ea740.png">

**Desktop (please complete the following information)**
 - OS: Mac OS
 - Browser: Safari
 - Version: 14.0

**Comment by thebearon** [comment]
This looks like #654, I'm assuming you're using Big Sur, and closing this as dupe.
