### ISSUE TITLE
Resume document message ignore click in message

### ISSUE THREAD

**Issue by hfiguiere** [CollaboraOnline/online#7403]
### Describe the Bug

Resume document message ignore click in message

### Steps to Reproduce

1. Open a document
2. Let it open for while. switch away from the tab.
3. Reactivate the tab with the document
5. Click **in the message**

### Expected Behavior

It resumes.

### Actual Behavior

It does nothing.

### Screenshots

The message:

![image](https://github.com/CollaboraOnline/online/assets/114441/e571589c-0669-4163-93c3-511a2f13adf0)

### Desktop

(Please complete the following information)
 - **OS:** Linux
 - **Browser:** Firefox
 - **Version:** stable

### Smartphone

n/a

### Additional Context

Clicking elsewhere (outside the message) works.

**Comment by Ezinnem** [comment]
Clicking on the document should make the document become active and ready for use.

@hfiguiere, if this issue is still reproducible for you, please can you share the Collabora Online you are using

**Comment by hfiguiere** [comment]
This is on share.collabora.com

**Comment by hfiguiere** [comment]
> Clicking on the document should make the document become active and ready for use.

But clicking in the message overlay doesn't. It's a natural user behaviour to click on the message that say "click to continue".

**Comment by hfiguiere** [comment]
This boils down to have the modalpopup stop propagation of the click event while the overlay that is below it is the one that will dismiss it.

I think that an alert like that without a button should just let the click go through.
