### ISSUE TITLE
Draw: Display rulers

### ISSUE THREAD

**Issue by hfiguiere** [CollaboraOnline/online#7405]
### Is your feature request related to a problem?

There are no rulers in the online version of Draw. The offline version has them. (View > Rulers)

### Describe the solution you'd like

Allow displaying the rulers in Draw.

In LibreOffice offline:

![image](https://github.com/CollaboraOnline/online/assets/114441/d654c845-d7ee-4ebd-8151-38f4b801b229)

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by Ezinnem** [comment]
This is an enhancement request

**Comment by rpear** [comment]
Looks like Darshan added this functionality, it tested OK for me in some tests in both  Draw and Presentation. Using LOKit version: Collabora Office 24.04.5.20240716 (git hash: ff487ed).

**Comment by Darshan-upadhyay1110** [comment]
Thanks, @rpear .
