### ISSUE TITLE
Draw: Display Grid

### ISSUE THREAD

**Issue by hfiguiere** [CollaboraOnline/online#7406]
### Is your feature request related to a problem?

In Draw in LibreOffice offline there is a grid.  View > Grid & Helpines > Display Grid, or the toolbar:

![image](https://github.com/CollaboraOnline/online/assets/114441/01a0f4a3-7cd6-4336-9bc2-f91a49c794ad)

The grid:

![image](https://github.com/CollaboraOnline/online/assets/114441/d7485091-e600-4e59-83c2-1b27e95f1f15)

It's not available in Draw online.

### Describe the solution you'd like

Allow display the grid. Also allow also snap to grid and other helpings.

### Describe alternatives you've considered
n/a

### Additional context

n/a

**Comment by hfiguiere** [comment]
Possibly #4893 (Impress)

**Comment by Ezinnem** [comment]
It could be regarded as an enhancement request

**Comment by hfiguiere** [comment]
Possibly a dupe of #4556

**Comment by JoshuaPettus** [comment]
Mentioned in the other thread,  also what goes hand and hand with the grid is the horizontal and vertical guide rulers.  Don't know how hard to implement but it is already part of LO for draw and impress

**Comment by hfiguiere** [comment]
One other issue is that currently setting the grid in a document on deskop (LibreOffice) will mean the grids are displayed in Draw or Impress, with no possibility to remove them.

**Comment by eszkadev** [comment]
implemented in https://github.com/CollaboraOnline/online/pull/10147
