### ISSUE TITLE
Sidebar/Navigator Animation Displays Previous Info

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7412]
### Describe the Bug

When you press the "Sidebar" or "Navigator" buttons, you can see a flash of the previous sidebar as the sliding animation plays.

### Steps to Reproduce

In Writer:

0. Go to "View" tab.
1. Press the "Sidebar" button.
2. Press the "Sidebar" button to close the sidebar.
3. Press the "Navigator" button.

As the Navigator slides in, you can see the Sidebar information.

When animation completes, Navigator info appears.

(Same happens if you swap Navigator/Sidebar buttons in the 3 steps above.)

### Expected Behavior

After Step 2, if you press:

- "Navigator", you should see Navigator info as it slides in.
- "Sidebar", you should see the Sidebar info as it slides in.

### Actual Behavior

After Step 2, if:

- "Navigator" is clicked after "Sidebar"
- "Sidebar" is clicked after "Navigator"

the opposite info displays as animation plays.

### Video

[CollaboraOnline23.05.4.2.-.Sidebar.Navigator.Previous.Info.Bug.webm](https://github.com/CollaboraOnline/online/assets/5774324/a2692cc2-a411-4460-a509-1aea828149bf)

From 0–5 secs, you can see what it SHOULD look like:

- "Sidebar" is clicked after "Sidebar"

From 6+ secs, you can see what it looks like when:

- "Navigator" is clicked after "Sidebar"
- "Sidebar" is clicked after "Navigator"

You see a flash of the previous menu option as the sliding animation plays.

### Desktop

- **OS:** Linux Mint 21.1
- **Browser:** Firefox
- **Version:** 118.0.1 (64-bit)

> COOLWSD version: 23.05.4.2 (git hash: 0ba51f81)
> LOKit version: Collabora Office 23.05.4.2 (git hash: b5a7948)
> Served by: Linux Mint 21.1
> Server ID: b67c7e81

**Comment by Darshan-upadhyay1110** [comment]
Works fine now 

[Screencast from 2024-07-15 18-39-35.webm](https://github.com/user-attachments/assets/f784696d-5b2d-4e11-9afc-d4de7d3a1ade)

COOLWSD version: 24.04.5.1 (git hash: 1ecf31df)
LOKit version: Collabora OfficeDev 24.04.5.1 (git hash: e1cfc65)
Served by: Ubuntu 23.10
Server ID: f5be9861
