### ISSUE TITLE
Fix radiobutton alignment in mobile view

### ISSUE THREAD

**Issue by eszkadev** [CollaboraOnline/online#7413]
### Describe the Bug

Radio buttons have weird layout on mobile in some cases. Example: Mobile -> hamburger menu -> download -> .pdf as ...
![pdfexpert](https://github.com/CollaboraOnline/online/assets/5307369/e7996205-08bd-47ce-a4ac-b8ceaaf9b269)

### Steps to Reproduce

On Mobile, go to:
hamburger menu -> download -> .pdf as ...

I would recomment to rework radiobutton mobile control to use css grid layout.
In case JS code change is also needed, widget is here: https://github.com/CollaboraOnline/online/blob/1fea2274fb991bfa55a6c80c379f5e3226f2ba25/browser/src/control/Control.MobileWizardBuilder.js#L256

**Comment by codewithvk** [comment]
I think, It would fix by this PR: https://github.com/CollaboraOnline/online/pull/7736

**Comment by Darshan-upadhyay1110** [comment]
Already fixed, closing this issue.

COOLWSD version: 24.04.5.2 (git hash: 4cc4dfe0)
LOKit version: Collabora OfficeDev 24.04.5.2 (git hash: 01593fc)
Served by: Ubuntu 23.10
Server ID: e660d28d
