### ISSUE TITLE
perf: writer - invalidation of bullet / numbering fields ?

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#7419]
With the team editing the weekly call notes:

![image](https://github.com/CollaboraOnline/online/assets/122848/e690d313-ab53-4f4c-b1e9-247cdc827ad6)

We get an invalidation of all of these numbered lists - on some operation (not visible) - presumably there is some lingering 'fields' invalidation creeping in, but in a big document this could cause performance issues - and of course, invalidating things that did not change just makes work and bandwidth use :-)

Thanks!

**Comment by mmeeks** [comment]
COOLWSD version: 23.05.5.1 (git hash: dffef0e9 (E))
LOKit version: Collabora Office 23.05.5.1 (git hash: 9f03693)
Served by: openSUSE Leap 15.5
Server ID: 3a813eff

**Comment by caolanm** [comment]
https://gerrit.libreoffice.org/c/core/+/152229 and https://gerrit.libreoffice.org/c/core/+/152433 were done for this case
