### ISSUE TITLE
Calc: comment edited by user1 seen and editable by user2 

### ISSUE THREAD

**Issue by timur-g** [CollaboraOnline/online#7421]
User1: in Calc Insert Comment
User2: sees comment and is able to edit it and apply and delete, regardless if in the same sheet as user1.

Seen in 23.05.4, not in .2.

### Describe the Bug

![Screenshot_20231012_130405](https://github.com/CollaboraOnline/online/assets/65948705/dca913e8-a537-4c23-ad76-33d8948bd0a5)

In there I could simply press the 3 vertical dots and press delete, to remove the comment. After pressing that I was then redirected (jumped from my sheet to @annanazarayan 's sheet).

Another user got the same behaviour, here is a screenshot of @Minion3665 editing a comment from @annanazarayan :
![image](https://github.com/CollaboraOnline/online/assets/65948705/1a23225a-e301-4a65-8eb4-b31760e5927d)

### Steps to Reproduce

1. Multiple users editing a spreadsheet on 12 Oct 2023 (COOL Weekly meeting)
   * The spreadsheet file: https://staging-perf.eu.collaboraonline.com/nextcloud/index.php/s/bdezLaf3WY6DoRy 
2. Insert a comment: Insert > Press the callout/speech balloon with a plus
3. Type something, ok
4. **user2* sees your comment's dialog appearing in his view (with the vertical dot)
5.  **user2** is now able to edit the comment or even remove it altogether
6. **user2** is redirected to **user1** sheet and the comment doesn't exist anymore

#### Staging perf
COOLWSD version: 23.05.5.1 (git hash: dffef0e9 (E))
LOKit version: Collabora Office 23.05.5.1 (git hash: 9f03693)
Served by: openSUSE Leap 15.5
Server ID: 3a813eff

#### Locally 
COOLWSD version:
23.05.5.1 git hash: [1fea227](https://github.com/CollaboraOnline/online/commits/1fea227)(E)
LOKit version:
Collabora Office 23.05.5.1 git hash: [c8d84f5](https://git.libreoffice.org/core/+log/c8d84f5)

### Additional screenshots or videos

https://github.com/CollaboraOnline/online/assets/65948705/f3f1be4a-6a41-419b-8e50-f285776b8eae

**Comment by timur-g** [comment]
Regressionby commit d4dcc9e74826f4404640d94280253f17dced078a.

**Comment by thebearon** [comment]
#7454 partly fixed this.
