### ISSUE TITLE
Dropdowns have wrong mark color in browsers

### ISSUE THREAD

**Issue by timur-g** [CollaboraOnline/online#7451]
Calc Format cells has wrong mark color, also other dropdowns. 

Firefox 118 - Light NOK
![image](https://github.com/CollaboraOnline/online/assets/7240617/141a426b-90e3-49a2-aa85-ae89313b5bc8) 

Firefox Dark OK 
![image](https://github.com/CollaboraOnline/online/assets/7240617/d954066d-87b1-49b3-8461-e0ef965df5a9)

 
Chromium 118 - Light OK
![image](https://github.com/CollaboraOnline/online/assets/7240617/fd5b2218-d4f2-4883-831d-5cf1ebde672f)

Chromium Dark NOK
![image](https://github.com/CollaboraOnline/online/assets/7240617/9640dd85-a959-4067-a6e0-6550378df0ae)

Seen with Online 23.05.5.1.
Please write both Online and browser version where tested. Not sure if Online or browser change.

@Ezinnem please test. @Darshan-upadhyay1110 please keep in mind.

**Comment by Darshan-upadhyay1110** [comment]
@timur-g 

Firefox 118- Dark OK 
![image](https://github.com/CollaboraOnline/online/assets/61383886/e702951a-e35e-460d-97b0-437f5c1e06ba)

Firefox 118 - Light OK
![image](https://github.com/CollaboraOnline/online/assets/61383886/1870f52f-75b9-441a-b415-bdca48112825)


Chrome 117 - Dark OK
![image](https://github.com/CollaboraOnline/online/assets/61383886/93c1bce4-b17b-4736-886b-fd0462ec2b78)


Chrome 117 - Light NOK
![image](https://github.com/CollaboraOnline/online/assets/61383886/524c1dec-ee7e-4f40-8f8d-3f6dd7f63d08)


@timur-g i have expirenced slightly diffrent then issue discription.

**Comment by timur-g** [comment]
Note: gridlines in Firefox are their regression, reported.

**Comment by Ezinnem** [comment]
In Chrome (Light Mode): Not OK

![format-cell-using-Nextcloud-Light](https://github.com/CollaboraOnline/online/assets/54344301/03574605-1774-42c3-abeb-a3ffb3c468b7)

In Chrome (Dark Mode) - OK
![format-cell-using-Nextcloud-Dark](https://github.com/CollaboraOnline/online/assets/54344301/c3c0f94d-2ed9-4ded-84a0-a030651ba74d)

In Firefox (Light Mode): OK

![Firefox-format-cells-Light](https://github.com/CollaboraOnline/online/assets/54344301/1917614e-d035-454f-beae-faa624e91224)


In Firefox (Dark Mode): OK

![Firefox-Format-cells--darkmode](https://github.com/CollaboraOnline/online/assets/54344301/5ade0689-69f6-4c2d-bc79-6899311435f7)

**Comment by pedropintosilva** [comment]
I have tested

https://staging.eu.collaboraonline.com/nextcloud/index.php/s/KYKpLsM5W48yDzb

https://staging-perf.eu.collaboraonline.com/nextcloud/index.php/s/THWmZoqm7fRZgC7

**Comment by Darshan-upadhyay1110** [comment]
Fix: https://github.com/nextcloud/richdocuments/pull/3238

**Comment by Darshan-upadhyay1110** [comment]
Backport PR to stable 27 :https://github.com/nextcloud/richdocuments/pull/3242

**Comment by Darshan-upadhyay1110** [comment]
Closing this issue as fix :https://github.com/nextcloud/richdocuments/pull/3238 merged.
