### ISSUE TITLE
No funciona el teclado del programa. No puedo escribir

### ISSUE THREAD

**Issue by juanriveragil** [CollaboraOnline/online#7456]
### Actual Behavior

A clear and concise description of what actually happens.

### Desktop

(Please complete the following information)
 - **OS:** [e.g. Windows 11]
 - **Browser:** [e.g. Chrome]
 - **Version:** [e.g. 114.0]

### Smartphone

(Please complete the following information)
 - **Device:** [e.g. iPhone14]
 - **OS:** [e.g. iOS16.5]
 - **Browser:** [e.g. Safari]
 - **Version:** [e.g. 16.4]

**Comment by juanriveragil** [comment]
No puedo utilizar el programa Collabora Office porque no funciona el teclado

**Comment by Ezinnem** [comment]
Typing texts works in Collabora Office on my device.

Please, @juanriveragil  can you share the screen-recording showing the issue you are experiencing?

Also, it would be good to know the Collabora Office version as well as the device type that you are using.

**Comment by timur-g** [comment]
This is invalid report. and this is no place for looking help, but for reporting bugs. There is Forum for discussion.
