### ISSUE TITLE
Rows and Column Headers And Cell Selection Marker Frequently Get "Out Of Sync" With Calc Table

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#746]
**Describe the bug**
In Collabora CODE (at least versions 4.0.x, 4.2.x and 6.4.0, but probably also 3.4.x), in Calc sheets the row headers and the cell selection marker rectangle often get "out of sync" with the actual table contents.

This means (some of) the e.g. row headers have different heights than the actual rows in the Calc table, causing a mismatch between headers and table and making editing - especially selecting the right cell for editing - basically impossible.

Used browsers are current versions of Chrome and Firefox, mainly under Windows, but also unter Linux.

The only solution is to exit the editing session and rejoin, which is very inconvenient - especially as the session has a high likelyhood to get out of sync again soon.

I could not reliably find a trigger to reproduce it, but it unfortunately still happens pretty frequently. Observation seems to indicate that it might happen more often (or even be caused by) concurrent editing of several users in the table.

Another observation is that it may be triggered by pasting text to a cell which then wraps in the cell, making it bigger.

Possibly those are also only 2 different ways to trigger this "out of sync situation", i.e. it may or may not be the same issue, which manifests using the same / similar symptoms.

So far, I had always hoped that it would finally be solved in the next bugfix release, but the problem even survived multiple "bigger" version steps so far without major improvements in this regard. :-(

**To Reproduce**
Unfortunately not quite sure. :-(

**Expected behavior**
The row headers should always correspond to the rows in the sheet.

**Actual behavior**
The row headers indicate rows numbers and heights which do not correspond to what's shown in the sheet. See also screenshot.

Also notice how the cell selection is "off" / does not properly match the selected cell.

**Screenshots**
![image](https://user-images.githubusercontent.com/26199042/99969157-62290100-2d9a-11eb-9e98-30be51c83e48.png)

**Desktop (please complete the following information)**
 - OS: Windows and Linux (with both GNOME and KDE Desktops)
 - Browser: Chrome, Chromium and Firefox
 - Version: different (always the current versions, but problem persists since a pretty long time)

**Smartphone (please complete the following information)**
 - Device: not tested

**Comment by mmeeks** [comment]
Thanks for reporting. We've very substantially re-written the code underneath the spreadsheet for 6.4 - and Gokay is going to be extending this to how we render row/column headers in the medium term too, so - having this as a lower priority issue on your TODO gokay - possibly gohrner could help you with some testing =)

**Comment by gohrner** [comment]
> Thanks for reporting. We've very substantially re-written the code underneath the spreadsheet for 6.4

That's why I reported it here, as it still occurs with CODE 6.4. I had hoped this issue to vanish with the new rendering code, but unfortunately, in vain. :-(

> possibly gohrner could help you with some testing =)

Possibly, if it can be done with feasible effort. I'm at least regularly upgrading to new CODE releases (Docker, based on the Dockerfile), so I can definitely supply feedback once the code went in there.

**Comment by gokaysatir** [comment]
Hello :)

We are working heavily on these features and hopefully send a new version in a short while. I just can't tell the exact date.

@gohrner  Thank you very much for your help:) I will inform you as soon as a new version is ready.

**Comment by thebearon** [comment]
> Another observation is that it may be triggered by pasting text to a cell which then wraps in the cell, making it bigger.

Yes, this is a consistent reproducer, you pick a cell, enable Wrap Text, and paste a long piece of text into it.

**Comment by thebearon** [comment]
These issues should generally be fixed in 6.4.7, if they still occur, let us know.
