### ISSUE TITLE
Draw: Icon to toggle side pane visibility  has unintuitive label

### ISSUE THREAD

**Issue by hfiguiere** [CollaboraOnline/online#7470]
### Describe the Bug

The label (tooltip) of the button to toggle the side pane visibility is unintuitive.

![image](https://github.com/CollaboraOnline/online/assets/114441/09c84732-bbd5-44f8-aea3-b7485b3c4a28)

Here it called "ModifyPage" (one word!)

### Steps to Reproduce

1. Hover the button with the mouse

### Expected Behavior

The tooltip say "Show sidepane" or "Hide sidepane", or something that clear.

### Actual Behavior

It says "ModifyPage"

### Screenshots

![image](https://github.com/CollaboraOnline/online/assets/114441/09c84732-bbd5-44f8-aea3-b7485b3c4a28)

### Desktop

(Please complete the following information)
 - **OS:** Linux
 - **Browser:** Firefox
 - **Version:** 118.0.1

### Smartphone

n/a

### Additional Context

See #7469 for another UI issue related.

**Comment by pedropintosilva** [comment]
Thanks @hfiguiere I think this is a very easy thing to fix and was fixed long time ago for writer but it seems no one applied to Draw.

Turn in this into an easy hack.

# Context
Modify page is the string that comes from the (uno) command itself that triggers the toggling of the sidebar that `.uno:ModifyPage`. 

## Code pointers
To anyone willing to do this easyhack:
* Search for that string
* Compare `getOptionsSectionData` function and see how it's used between `Control.Notebookbar.js` and `Control.NotebookbarDraw.js`
* Update label

**Comment by timar** [comment]
Oops, sorry @pedropintosilva for fixing the easy hack. I did not see this report.
