### ISSUE TITLE
Android app not showing additional sheets when opening file on mobile phone

### ISSUE THREAD

**Issue by DaddyAG** [CollaboraOnline/online#7485]
### Describe the Bug

Since last update (23.05.4 for Android) bug was introduced that hides available sheets in opened document. Last working version was 21.11.6 for Android.

### Steps to Reproduce

1. Open any Excel or Calc file (tested with xlsx and ods) that has multiple sheets.

### Expected Behavior

In version 21 you could see all sheets, present in a document, listed at bottom of the screen.

### Actual Behavior

In version 23 there are no sheets listed at bottom of the screen.

### Workaround

If I click on hamburger menu (three horisontal lines) to open menu, and click again on same icon to close menu, sheets magicaly appear on screen bottom.

### Smartphone

(Please complete the following information)
 - **Device:** Samsung S21, Samsung S23
 - **OS:** Android 13

### Additional Context

I'm reffering to Android application published on Google Play store.

**Comment by timur-g** [comment]
I see this in Android app. Not in Android browser.

**Comment by timur-g** [comment]
This should be resolved with https://github.com/CollaboraOnline/online/pull/9887 in the current snapshot (24.04.99-766), hopefully to be released as 24.04.6.
@DaddyAG thanks for reporting and finding a workaround.

**Comment by GilDH** [comment]
Corrected in Android App Vs. 24.04.6.2 on loaded Samsung A53
