### ISSUE TITLE
Spreadsheet border design

### ISSUE THREAD

**Issue by juliushaertl** [CollaboraOnline/online#7498]
### Describe the Bug

Comparing spreadsheets with other solutions i noticed some small changes that could improve the overall look:

- The border size of columns seem to be 2px while all other solutions as well as Libreoffice on the desktop uses 1px

| Collabora Online | Libreoffice Desktop | Microsoft Excel | 
|---|---|---|
| ![Screenshot 2023-10-20 at 12 21 57](https://github.com/CollaboraOnline/online/assets/3404133/e91bef18-f08b-4b0e-8467-3d026b400782) | ![Screenshot 2023-10-20 at 12 28 50](https://github.com/CollaboraOnline/online/assets/3404133/e2acef93-a082-47d9-90a5-0bdbd23d2b67) | ![Screenshot 2023-10-20 at 12 22 00](https://github.com/CollaboraOnline/online/assets/3404133/2932a433-51f4-4599-aa7e-8a92058389ec) |

- The border color seems to be not consistent, i though I reported this already but cannot find the issue (maybe it was just during a call)
  - Most visible in dark mode, but also the case in light mode. Every nth row is slightly changed in color

![Screenshot 2023-10-20 at 12 21 24](https://github.com/CollaboraOnline/online/assets/3404133/b180eba1-3da1-4ccc-ba0a-01412350be12)

- The focus outline seems to have a slight blur, compared to other solutions where it is full color with increased size

| Collabora Online | Libreoffice Desktop |
|---|---|
| ![Screenshot 2023-10-20 at 12 26 21](https://github.com/CollaboraOnline/online/assets/3404133/3c524db5-356d-44e5-a950-05484d3cb7a7) | ![Screenshot 2023-10-20 at 12 26 44](https://github.com/CollaboraOnline/online/assets/3404133/8d313913-3754-4f33-8998-66c664af0269) |

cc @pedropintosilva @jancborchardt

**Comment by jancborchardt** [comment]
Agree with everything except the cell highlight color for LibreOffice Desktop is probably too light for accessibility, should probably be our color-primary-element?

**Comment by timur-g** [comment]
If this was tested in Firefox, then there is a bug there from version 115, menitoned also in #7316. Bisected and reported.

**Comment by juliushaertl** [comment]
You're right, sorry I somehow missed to test this in other browsers. Hoping for a quick upstream fix 🤞 Let me close this then as a duplicate of #7316
