### ISSUE TITLE
Fix scroll direction in right-to-left mode

### ISSUE THREAD

**Issue by Minion3665** [CollaboraOnline/online#7515]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @Minion3665 

### Detailed description and rationale
This is issue #7298

Calc has a right-to-left mode, but unfortunately it still contains many bugs. This specific task focuses on a scroll direction bug, particularly evident on a touch device, where scrolling is not switched when RTL mode is enabled. This means that swiping left on a mobile device or scrolling left with a mouse that can scroll left will still increase the column numbers you can see in the document, even though the document is actually moving right

### Code pointers
- This is believed to be a Javascript bug even though there is a similar issue in LibreOffice core: <https://bugs.documentfoundation.org/show_bug.cgi?id=93352>. We think that because we don't believe we do a roundtrip to core every time we want to scroll
- You may want to use the `isCalcRTL` function from `browser/src/layer/tile/CanvasTileLayer.js` https://github.com/CollaboraOnline/online/blob/686f9d7ccb1ba9afebfac9b6a1f8e422c2dec0ce/browser/src/layer/tile/CanvasTileLayer.js#L7250-L7252 to detect if you're in right-to-left mode

**Comment by krunal-ctrl** [comment]
Hey @Minion3665, I would like to work on this, Can you assign me this issue?

**Comment by Minion3665** [comment]
> Hey @Minion3665, I would like to work on this, Can you assign me this issue?

Awesome and thanks! I've assigned you to the issue, please feel free to ping me if you'd like any help/have any questions

**Comment by krunal-ctrl** [comment]
Hey @Minion3665 ,  So far I have find the code responsible for drag event  and we need to set X position as opposite direction, here's what i have implemented 


```diff --git a/browser/src/dom/Draggable.js b/browser/src/dom/Draggable.js
index a442ec798e..fb27b51254 100644
--- a/browser/src/dom/Draggable.js
+++ b/browser/src/dom/Draggable.js
@@ -131,8 +131,8 @@ L.Draggable = L.Evented.extend({
 				offset.y = 0;
 			}
 		}
-		if (!offset.x && !offset.y) { return; }
-		if (L.Browser.touch && Math.abs(offset.x) + Math.abs(offset.y) < 3 && !e.autoscroll) { return; }
+		if (!offset.x && !offset.y && !this._map._docLayer.isCalcRTL()) { return; }
+		if (L.Browser.touch && Math.abs(offset.x) + Math.abs(offset.y) < 3 && !e.autoscroll && !this._map._docLayer.isCalcRTL()) { return; }
 
 		L.DomEvent.preventDefault(e);
 
@@ -155,6 +155,8 @@ L.Draggable = L.Evented.extend({
 		if (this._freezeX)
 			this._newPos.x = this._startPos.x;
 
+		// var docWidth = this._map.getPixelBoundsCore().getSize().x;
+		this._newPos.x = this._map._docLayer.isCalcRTL() ?  -1 * Math.abs(this._newPos.x) : this._newPos.x;
 		this._moving = true;
 
 		L.Util.cancelAnimFrame(this._animRequest);
```

As you can see here I'm setting opposite direction for x in case of RTL mode. But on second iteration it is not quite working as I'm seeing from debugging that we need to set some offset from previous position and add it to new position. 
I have also tried to subtract X from docWidth but it's not working also tried some other things, but i'm feeling that I'm stuck here.

I want to share this information just to get some idea  or second opinion on this.

**Comment by krunal-ctrl** [comment]
Also from further evaluation on desktop mode I found this method is responsible for scroll on desktop. But i don't think that this calculation would be applied here.
https://github.com/CollaboraOnline/online/blob/08f60bc72b3267ef12d4fec0f71db850f6c6ce15/browser/src/layer/tile/ScrollSection.ts#L436-L445

**Comment by krunal-ctrl** [comment]
Hey @Minion3665 , 
I've been working on addressing the issue we discussed, and I've made some progress. I believe I've identified the source of the problem and implemented a potential solution.

To mitigate this issue, I've made changes to the code in the Draggable.js file. Here's a snippet of the relevant code changes:

```diff --git a/browser/src/dom/Draggable.js b/browser/src/dom/Draggable.js
index a442ec798e..868159b492 100644
--- a/browser/src/dom/Draggable.js
+++ b/browser/src/dom/Draggable.js
@@ -131,8 +131,8 @@ L.Draggable = L.Evented.extend({
 				offset.y = 0;
 			}
 		}
-		if (!offset.x && !offset.y) { return; }
-		if (L.Browser.touch && Math.abs(offset.x) + Math.abs(offset.y) < 3 && !e.autoscroll) { return; }
+		if (!offset.x && !offset.y && !this._map._docLayer.isCalcRTL()) { return; }
+		if (L.Browser.touch && Math.abs(offset.x) + Math.abs(offset.y) < 3 && !e.autoscroll && !this._map._docLayer.isCalcRTL()) { return; }
 
 		L.DomEvent.preventDefault(e);
 
@@ -155,6 +155,7 @@ L.Draggable = L.Evented.extend({
 		if (this._freezeX)
 			this._newPos.x = this._startPos.x;
 
+		this._newPos.x = this._map._docLayer.isCalcRTL() ?  this._startPos.x - offset.x : this._newPos.x;
 		this._moving = true;
 
 		L.Util.cancelAnimFrame(this._animRequest);
```

I've introduced additional conditions that take into account the right-to-left (RTL) calculations, which should help in ensuring the scroll behaves as expected.

This resolves issue and works perfectly.

But what I have observed some unexpected behavior during fast dragging, where it scrolls in the default direction along with the unintended vertical scroll. After some investigation, I've found that  This discrepancy is related to `this._startPos` value being increased (in the positive direction on the ruler) during fast scrolling, which leads to the undesired behavior.

please review the code changes I've made and let me know your thoughts. Your feedback and suggestions will be highly appreciated. Thank you in advance for your assistance.

**Comment by Minion3665** [comment]
@krunal-ctrl, awesome! thanks for your hard work, it'd be amazing if you could also [make a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) so it's easier for anyone to pull down your changes and review them :)

In the meantime, I've applied your patch and it's working great for me on my phone! Scrolling slowly scrolls in the right direction now, which is awesome, good job!

---

> But what I have observed some unexpected behavior during fast dragging, where it scrolls in the default direction along with the unintended vertical scroll

however I have still noticed this too, have you looked into what causes it to increase when scrolling quickly yet?

---

I've also noticed that the patch seems to break things on touchpads... looking at it, it seems that the scroll direction with my touchpad was right before, and your patch successfully reverses it!... to the wrong direction. I'm curious if you have a touchpad that you can test with and are seeing this too?

---

Finally, I was interested in these couple lines in your patch
```patch
-		if (!offset.x && !offset.y) { return; }
-		if (L.Browser.touch && Math.abs(offset.x) + Math.abs(offset.y) < 3 && !e.autoscroll) { return; }
+		if (!offset.x && !offset.y && !this._map._docLayer.isCalcRTL()) { return; }
+		if (L.Browser.touch && Math.abs(offset.x) + Math.abs(offset.y) < 3 && !e.autoscroll && !this._map._docLayer.isCalcRTL()) { return; }
```

to me, it looks like you might want to reverse the conditions for RTL mode rather than ignoring them, what do you think?

---

Overall, a really good start! I'm happy to see this issue being worked on and it seems like you're doing an excellent job! Thanks!

**Comment by krunal-ctrl** [comment]
Thank you for appreciation @Minion3665.

>I've also noticed that the patch seems to break things on touchpads... looking at it, it seems that the scroll direction with my touchpad was right before, and your patch successfully reverses it!... to the wrong direction. I'm curious if you have a touchpad that you can test with and are seeing this too?

Sorry, I have forgot to mention a tochpad issue, I have noticed it too but currently i was focusing on drag only.

> however I have still noticed this too, have you looked into what causes it to increase when scrolling quickly yet?

Not yet, But I am putting it in my schedule

**Comment by krunal-ctrl** [comment]
Hey @Minion3665 what should be the touch pad direction ? For example I want to go from A -> Z, my fingers should move from right to left or left to right

**Comment by Minion3665** [comment]
> As am observing on my environment direction is right to left before and after applying patch. and touch-pad event flow does not hit patched code when debugging.

My apologies, I've retested this and you're right... I suspect when I applied the patch before I had some code to make stuff appear as tablet mode applied, that was my bad. The touchpad is fine with your patch, thanks for your diligence!

**Comment by Minion3665** [comment]
Hello! Are you still working on (or interested in) this @krunal-ctrl? If you are, great! If not, please may you let me know so I can reassign it?

Thanks

**Comment by krunal-ctrl** [comment]
Hey @Minion3665 , I have been working on this issue but i went on vacation from past week (will be back by this weekend). And just to report i believe i have not made any progress since last discussion on fast scroll issue.

while I'm still interested in tackling this bug, if someone is interested in solving this bug I'm happy to handover it to them.

Also Do you happen to have any code pointer or approach which I should focus on when i get back

**Comment by Minion3665** [comment]
> Hey @Minion3665 , I have been working on this issue but i went on vacation from past week (will be back by this weekend). And just to report i believe i have not made any progress since last discussion on fast scroll issue.
> 
> while I'm still interested in tackling this bug, if someone is interested in solving this bug I'm happy to handover it to them.

no worries, happy to hear you're still interested! Enjoy the rest of your vacation :)

> Also Do you happen to have any code pointer or approach which I should focus on when i get back

The "fast scroll" issue looks to me like it could be caused by something to make the sheet slow down for a little once you stop scrolling rather than doing it jarringly (try doing it without being in RTL mode, and you'll see the same effect in the correct direction), so I'd recommend seeing if you can find where that's done rather than worrying too much about how fast/otherwise you're scrolling first... Let me know if you want me to see if I can dive a little deeper and find some files/lines for you
