### ISSUE TITLE
Android: Cursor Stuck As Black Color After "Insert > Shape"

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7516]
### Describe the Bug

In Dark Mode, after inserting a shape and writing some text:

- The blinking cursor gets "stuck" as black/dark color.

### Steps to Reproduce

In Writer:

1. In upper right, press "Insert" button.
2. Scroll down the menu options + Choose "Shape".
   - Choose any random shape.
   - Example: I chose a rounded rectangle.
3. After shape is inserted:
   - Double-Tap on the shape.
4. Write text inside the shape:
   - For example: "Test"
      - (While inside the shape, see cursor flips from "white-on-black" to "black-on-color".)
5. Tap outside of the shape.

BUG: The cursor is now black-on-black.

### Screenshots

Steps 1+2:

<img alt="Android Collabora 23 05 4 1 - Black Cursor Insert Shape 1" src="https://github.com/CollaboraOnline/online/assets/5774324/5b347637-c31a-4797-b7dc-51f7208fc81e" width="40%" height="40%"/>

And this is cursor Before/After Step 5:

<img alt="Android Collabora 23 05 4 1 - Black Cursor Insert Shape 2" src="https://github.com/CollaboraOnline/online/assets/5774324/29dbbfb6-ebb3-4002-ac23-237cff8f97d8" width="40%" height="40%"/> <img alt="Android Collabora 23 05 4 1 - Black Cursor Insert Shape 3" src="https://github.com/CollaboraOnline/online/assets/5774324/fe2f1765-ca13-4a8f-991a-7bc33f383fde" width="40%" height="40%"/>

### Expected Behavior

After clicking out of shape in Step 5:

- The cursor should return to white-on-black.

### Actual Behavior

After clicking out of shape in Step 5:

- The cursor gets stuck as black-on-black.

### Smartphone

- **Device:** OnePlus 6T
- **OS:** Android 11 (OxygenOS 11.1.2.2)

> COOLWSD version: 23.05.4.1
> git hash: b3abc03d
> LOKit version:
> Collabora Office 23.05.4.1
> git hash: 966b9f8

### Additional Context

This does not seem to occur if you:

- Open a document with a shape w/ text already inside of it and repeat Steps 2–5.
   - At Step 3, the cursor stays light/white.

It seems to only occur if you:

- Insert a shape from scratch.
   - At Step 3, the cursor turns dark/black.

**Comment by Ezinnem** [comment]
This is not readily reproducible on my end using the 23.05.5.2 (git hash: [8fe1f0fe](https://github.com/CollaboraOnline/online/commits/8fe1f0fe))

See recording:

https://github.com/CollaboraOnline/online/assets/54344301/3b2afc8e-5036-432a-b489-30de1d8c5429

**Comment by timur-g** [comment]
I reproduce. If not on first insert, then on shape delete or new insert.

**Comment by Darshan-upadhyay1110** [comment]
It's not reproducible now. 
- i have inserted multiple shapes in dark mode as well as in light.
- changed theme left and right multiple times
- still able to see correct color of cursor in document after text edit inside shape

COOLWSD version: 24.04.5.1 (git hash: 1ecf31df)
LOKit version: Collabora OfficeDev 24.04.5.1 (git hash: e1cfc65)
Served by: Ubuntu 23.10
Server ID: f5be9861
