### ISSUE TITLE
Improve postMessage interface with tabbed UI

### ISSUE THREAD

**Issue by hfiguiere** [CollaboraOnline/online#7517]
### Describe the Bug

When using the postMessage interface, there are error that pops in the console when clicking "Hide XXX Command" or "Show XXX Command".

### Steps to Reproduce

1. Go to the post message interface as shown in the make run output.
2. In the post message page, Click on "Tabbed Toolbar"
3. Open the Developer tools, JS Console
4. In the post message page, Click on "Hide Save Command"

### Expected Behavior

No message in the console.

### Actual Behavior

Console shows
```
Menu item with id "save" not found.
```

### Screenshots

Before:
![image](https://github.com/CollaboraOnline/online/assets/114441/4df9cc57-1eef-4305-a7e0-af0cdd878152)

After:
![image](https://github.com/CollaboraOnline/online/assets/114441/a3174931-e126-411d-b32d-491da974ebbf)

### Desktop

(Please complete the following information)
 - **OS:** Linux
 - **Browser:** Firefox
 - **Version:** stable

### Additional Context

Some other observations: the icon in the tabbed bar isn't hidden.

Also happen with "Hide Print Command".

In the compact toolbar (classic), it actually doesn't happen and the toolbar button are also hidden.

**Comment by hfiguiere** [comment]
Another takeaway is that this feature doesn't work with the tabbed notebook interface. The messages `Hide_Button` or `Hide_Menu_Item` do nothing when using the tabbed notebook UI mode.

**Comment by thebearon** [comment]
Yes, those commands have only been implemented for the compact view (menu, toolbar) so far.

**Comment by hfiguiere** [comment]
Dupe of #5957

**Comment by nadirlouati** [comment]
any news ?
