### ISSUE TITLE
22.05: Broken link to Accessibility Check help page

### ISSUE THREAD

**Issue by cosminh11** [CollaboraOnline/online#7521]
### Describe the Bug

In Writer 22.05, the "Help" button from the Accessibility Check dialog goes to a 404 page.

### Steps to Reproduce

1. Using version 22.05, open an odt document
2. If using the tabbed view, go to "Help". If using the compact view, go to the "Tools" menu
3. Choose "Accessibility Check"
4. In the "Accessibility Check" dialog, click the "Help" button
5. In the "External Link" dialog, click the "Open link" button

### Expected Behavior

I am taken to [the corresponding help page](https://help.collaboraoffice.com/22.05/en-US/text/swriter/01/accessibility_check.html?System=&DbPAR=WRITER&HID=svx/ui/accessibilitycheckentry/accessibilityCheckEntryGotoButton#bm_id541630940172827)

### Actual Behavior

I am taken to [a 404 page](https://help.collaboraoffice.com/22.05/en-US/text/shared/05/err_html.html?System=&DbPAR=WRITER&HID=svx/ui/accessibilitycheckentry/accessibilityCheckEntryGotoButton)

### Desktop

 - **OS:** Ubuntu 22.04
 - **Browser:** Firefox
 - **Version:** e.g. 119.0

### Additional Context

I tried this with docker images and with [a document inside them](https://localhost:9980/browser/dist/cool.html?file_path=/opt/collaboraoffice/EULA.odt):
- 23.05: `docker run --network=host -e "extra_params=--o:storage.filesystem[@allow]=true" collabora/code:23.05.5.2.1`
    - the link displayed in the "External link" dialog is [link A](https://help.collaboraoffice.com/help.html?Target=swriter/svx/ui/accessibilitycheckentry/accessibilityCheckEntryGotoButton&Language=en-US&System=&Version=23.05)
    - the link where I am redirected is [link B](https://help.collaboraoffice.com/23.05/en-US/text/swriter/01/accessibility_check.html?System=&DbPAR=WRITER&HID=svx/ui/accessibilitycheckentry/accessibilityCheckEntryGotoButton#bm_id541630940172827)
- 22.05: `docker run --network=host -e "extra_params=--o:storage.filesystem[@allow]=true" collabora/code:22.05.14.3.1`
    - the link displayed in the "External link" dialog is [link C](https://help.collaboraoffice.com/help.html?Target=swriter/svx/ui/accessibilitycheckentry/accessibilityCheckEntryGotoButton&Language=en-US&System=&Version=22.05) which is exactly like "link A" but with 22.05, so it looks ok
    - the link where I am redirected is [link D](https://help.collaboraoffice.com/22.05/en-US/text/shared/05/err_html.html?System=&DbPAR=WRITER&HID=svx/ui/accessibilitycheckentry/accessibilityCheckEntryGotoButton) which is a 404 page
    - if I take "link B" (the page for 23) and replace 23 with 22 I get [link E](https://help.collaboraoffice.com/22.05/en-US/text/swriter/01/accessibility_check.html?System=&DbPAR=WRITER&HID=svx/ui/accessibilitycheckentry/accessibilityCheckEntryGotoButton#bm_id541630940172827) which is the proper page for 22.05 - so the page exists but the user is not properly redirected to it

**Comment by pedropintosilva** [comment]
@timur-g  could you please take a look at this

**Comment by timur-g** [comment]
![image](https://github.com/CollaboraOnline/online/assets/7240617/9f64d898-b886-4835-9d6b-c4e70f116eed)
Opens https://help.collaboraoffice.com/22.05/en-US/text/shared/05/err_html.html?System=UNIX&DbPAR=WRITER&HID=svx/ui/accessibilitycheckentry/accessibilityCheckEntryGotoButton
![image](https://github.com/CollaboraOnline/online/assets/7240617/67a3019f-c30a-44d1-8009-607594ab872d)

**Comment by timur-g** [comment]
22.05 only, as 23.05 opens https://help.collaboraoffice.com/23.05/en-GB/text/swriter/01/accessibility_check.html?System=&DbPAR=WRITER&HID=svx/ui/accessibilitycheckentry/accessibilityCheckEntryGotoButton#bm_id541630940172827

**Comment by thebearon** [comment]
This is probably relevant:
https://bugs.documentfoundation.org/show_bug.cgi?id=144332

**Comment by timar** [comment]
https://help.collaboraoffice.com/help.html?Target=swriter/svx/ui/accessibilitycheckentry/accessibilityCheckEntryGotoButton&Language=en-US&System=UNIX&Version=22.05 link has been fixed.
