### ISSUE TITLE
Comments overlapping so i can't edit them

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#7527]
Reported initially by @jospoortvliet https://github.com/nextcloud/richdocuments/issues/3254

----- 

**Describe the bug**
See this:
![Screenshot 2023-10-24 at 15 57 21](https://github.com/nextcloud/richdocuments/assets/551757/f2c3be2c-4ae1-4bf8-8b71-ae13ca600607)

Says it all, I guess. Firefox, on Mac OS, both latest version, on cloud.nextcloud.com

Happy to share the document.

**Comment by jospoortvliet** [comment]
Thanks!
