### ISSUE TITLE
Select of content in Formula Bar is hard as it changes position

### ISSUE THREAD

**Issue by timur-g** [CollaboraOnline/online#7548]
Online 23.05.5. 

Select of content in Formula Bar is hard as it changes position.
Best seen if ew double-click to select 1st word, here "test". If we select 3rd word "word" then 2 words are selected.

![image](https://github.com/CollaboraOnline/online/assets/7240617/e007b641-5f66-4ed4-b8bd-868e3a14c92a)

OK with 23.05.2, NOK with 23.05.4, regression. OK in Core, so Online issue.

**Comment by timur-g** [comment]
commit 1a2500c8d31f12a8e23c648a0afb208e3d09bb05
Author: Gökay Şatır <gokaysatir@gmail.com>
Date:   Tue Aug 8 15:46:49 2023 +0300

    Merge accessibility definitions with notebookbar definitions.
    
I confirm by bisect.

**Comment by eszkadev** [comment]
Fix merged
