### ISSUE TITLE
change "Twitter" to "𝕏 (Twitter)" in README.md

### ISSUE THREAD

**Issue by BandhiyaHardik** [CollaboraOnline/online#7562]
### Describe the Bug

Twitter is not updated to new name.

### Steps to Reproduce

1. Go to <a href='https://github.com/CollaboraOnline/online'>CollaboraOnline online Repository</a>
2. In Get in touch Section
3. Twitter is not updated to new name

### Expected Behavior
![image](https://github.com/CollaboraOnline/online/assets/110784317/95f8a40f-5d4e-4de7-b060-8d820c4ef9df)

Twitter is now known as 𝕏.

### Actual Behavior
![image](https://github.com/CollaboraOnline/online/assets/110784317/3927670b-c79f-4b1e-a86c-513be3a4840e)

**Comment by Ezinnem** [comment]
Fix with #7585
