### ISSUE TITLE
CODE 6.4.1: Cell Comments Unusable (Popup Frequently Auto-closes Suddenly and Unexpectedly, Overwriting Cell Contents)

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#757]
**Describe the bug**
Adding comments to a sheet in LOOL 6.4 (in its CODE 6.4.0 / 6.4.1 incarnation) is basically impossible, as the comment popup will just close in the middle of typing suddenly, causing you to overwrite the cell's contents where you wanted to add the comment... :-/

Also see attached animated GIF.
![LOOL Calc Vanishing Comment Popup](https://user-images.githubusercontent.com/26199042/100091368-cc05e100-2e54-11eb-9d0d-f52d78b7d224.gif)

I was the only one editing this (nearly empty) sheet.

The first time I opened it, it closed nearly immediately without me pressing any keyboard button.

The second time I mispositioned it so it wasn't visible, so I closed if by clicking "Cancel".

The third time I just entered text and didn't press ESC and didn't click anywhere. You can see the dialog suddenly just vanishes while typing, overwriting the cell's contents.

This makes editing comments in LOOL Calc basically impossible at the moment...

**To Reproduce**
1. Just try to add and edit comments in any Calc sheet - see animated GIF.

**Expected behavior**
Editing Comments should be possible.

**Actual behavior**
Editing Comments is basically impossible at the moment and additionally often leads to accidentally overwritten cell contents.

**Desktop (please complete the following information)**
 - OS: Linux (GNOME and KDE Desktops) and Windows 10
 - Browser: Firefox, Chrome and Chromium
 - Version: recent versions

**Smartphone (please complete the following information)**
 - Device: not tested

**Comment by thebearon** [comment]
Indeed, I can confirm the bug, both in 6.4.1 and in 4.2.12.

**Comment by thebearon** [comment]
This should be fixed in Collabora Online/CODE 6.4.7, thanks @eszkadev!
