### ISSUE TITLE
about view mode

### ISSUE THREAD

**Issue by daodol** [CollaboraOnline/online#7583]
### Is your feature request related to a problem?

Hello, I'm testing right now and I found it in view or readonly mode. I don't have a way to drag the mouse to do the copying function. What should I do.thanks

**Comment by daodol** [comment]
Or is there a way to implement just disabling keyboard input

**Comment by daodol** [comment]
hello？

**Comment by thebearon** [comment]
This feature request has already been reported, please see #4914.

**Comment by daodol** [comment]
> This feature request has already been reported, please see #4914.

thanks for ur answer，I noticed that this issue has been a long time ago and has not been resolved. I'm very sorry that I'm not familiar with the structure of this project. I can't make effective modifications, but for the front-end to disable the keyboard input event, it shouldn't be difficult, is there a way to solve it, this is a front-end problem, if the html is maliciously modified, it should be determined by the back-end permissions

**Comment by daodol** [comment]
hi，I applied for the collabora sample project on the official website, and I saw in collabora in owncloud that the collabora integrated in owncloud is in read-only mode, it is not allowed to enter, how is this implemented?

**Comment by daodol** [comment]
https://demo.eu.collaboraonline.com/owncloud/index.php/apps/richdocuments/documents.php/index?fileId=163834&dir=%2F&enforceSecureView=true
