### ISSUE TITLE
"Format > Columns" Menu: Style Dropdown Text Misaligned

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7591]
### Describe the Bug

In **Format > Columns**, the "None" text in the Style dropdown is oddly misaligned:

![Collabora 23 05 2 - Layout Columns - Columns Menu - Misaligned Styles Dropdown](https://github.com/CollaboraOnline/online/assets/5774324/a74445e0-03a9-497d-9ac6-183dff6b3b6c)

### Steps to Reproduce

In Writer:

1. Press **Format > Columns** button.

See misaligned text.

### Expected Behavior

"None" to vertically align in center, just like the other dropdowns with text.

### Actual Behavior

"None" looks like it's at the top of the box.

### Desktop

- **OS:** Linux Mint 21.1
- **Browser:** Firefox
- **Version:** 119.0
 
> COOLWSD version: 23.05.5.3 (git hash: 557f191d)
> LOKit version: Collabora Office 23.05.5.3 (git hash: 894db9a)
> Served by: Linux Mint 21.1
> Server ID: 36f66248

### Additional Context

That specific dropdown is where you choose what line types as a separator, so the graphics-mixed-with-text might be throwing this alignment off.

**Comment by Darshan-upadhyay1110** [comment]
Adding this in `easy hack` section
Potential mentor: @pedropintosilva
