### ISSUE TITLE
"Find and Replace" Open While Pasting = Text + Strange CSS

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7592]
### Describe the Bug

Copying text, then pasting with the "Find and Replace" window open, gets extra CSS pasted in too.

### Steps to Reproduce

In Writer:

1. Have some basic text like:

```
This is line 1.
This is line 2.
This is line 3.
```

2. Highlight line 1 + Copy (`Ctrl+C`).

3. Press **Home > Find and Replace**.

4. Back in the document:

- Click after line 3.

5. Paste (`Ctrl+V`).

See strange CSS be pasted along with Step 2's selected text.

### Video

[Collabora.23.05.5.2.-.Find.and.Replace.-.Paste.CSS.Bug.webm](https://github.com/CollaboraOnline/online/assets/5774324/82432041-edfe-4fcf-bb56-9c9f71eacfa1)

- 0–4 seconds = Steps 1+2.
- 6+ seconds = Steps 4+5.

### Expected Behavior

Only the copied text be carried over:

     This is line 1.

### Actual Behavior

The copied text gets carried over, along with strange CSS from somewhere:

     This is line 1.
     
     p { line-height: 120%; margin-bottom: 0.1in; background: transparent }

### Desktop

- **OS:** Linux Mint 21.1
- **Browser:** Firefox
- **Version:** 119.0
 
> COOLWSD version: 23.05.5.3 (git hash: 557f191d)
> LOKit version: Collabora Office 23.05.5.3 (git hash: 894db9a)
> Served by: Linux Mint 21.1
> Server ID: 36f66248

### Additional Context

With the "Find and Replace" window open, it seems like you can't copy text from the document.

I was trying to:

- Copy from my document.
   - Like line 2 or 3.
- Paste different text into the Replace box.

but I kept on getting stuck with line 1 text.

So there's definitely some weird interaction happening there with `Ctrl+C` and that window being open.

**Comment by Tex2002ans** [comment]
I got the same exact thing right now with:

- **File > Properties** menu open.

- - -

Having that menu open while pasting into the document adds an extra:

```
p { line-height: 120%; margin-bottom: 0.1in; background: transparent }a:link { color: #000080; text-decoration: underline
```

to the very end of the pasted material.

**Comment by Darshan-upadhyay1110** [comment]
Tested not reproducible.

[Screencast from 2024-07-15 21-49-23.webm](https://github.com/user-attachments/assets/39b50a67-f5ca-45f2-8824-2f91fd11b8ee)

COOLWSD version: 24.04.5.1 (git hash: 1ecf31df)
LOKit version: Collabora OfficeDev 24.04.5.1 (git hash: e1cfc65)
Served by: Ubuntu 23.10
Server ID: f5be9861
