### ISSUE TITLE
Allow unfollowing users by clicking on them again

### ISSUE THREAD

**Issue by Minion3665** [CollaboraOnline/online#7603]
### Is your feature request related to a problem?

When I want to unfollow someone, I often try to do it by clicking on the user I'm following
![Screenshot from 2023-11-03 10-11-32](https://github.com/CollaboraOnline/online/assets/34243578/7c1e4f96-ec67-4f6a-abb0-2a6562a74146)

Unfortunately, that's not possible... instead you have to click on yourself
![Screenshot from 2023-11-03 10-12-05](https://github.com/CollaboraOnline/online/assets/34243578/20c5d398-6b64-4c30-b964-d59ba598a2d2)

### Describe the solution you'd like

Presumably this was meant as a "follow yourself" thing, and it's fine but it'd be nice to be able to click on the user you're following to cancel as well. I'd like this to be implemented as an additional option

### Describe alternatives you've considered

- We could have a separate unfollow button instead
- We could make it clearer that clicking on yourself is the unfollow option (e.g. by adding some text underneath that said "stop following")
![Frame 1](https://github.com/CollaboraOnline/online/assets/34243578/d68a49d7-78e1-489e-b98d-7bc7e24eaa92)

### Additional context

This feature is related to #7602, in that they are both pain points with the following UI currently

**Comment by Minion3665** [comment]
By the way, Figma does this one too, and you don't have to be in the user list for it :)
![A tooltip in figma, showing you can unfollow a user by clicking on their profile image -- without even being in the user list!!](https://github.com/CollaboraOnline/online/assets/34243578/a96aa139-c6a1-456a-a27e-df939ff7d621)

And VSCode Live Share lets you click on the pin again
![VS live share, where clicking on the pin will "unfollow participant"](https://github.com/CollaboraOnline/online/assets/34243578/bcc4cbe3-3bca-4e40-9f6d-f6109500e33e)

**Comment by pedropintosilva** [comment]
> When I want to unfollow someone, I often try to do it by clicking here
> Unfortunately, that's not possible... instead you have to click here

Recently we got the improvement of closing the list simply by pressing it again (before you needed to press forcibly out for that to work). Next up was the Clicking in the user that you are following to unfollow. If that is what you propose, I agree : )
