### ISSUE TITLE
Left-align users

### ISSUE THREAD

**Issue by Minion3665** [CollaboraOnline/online#7604]
### Is your feature request related to a problem?

I don't like the right-alignment on the users list
![Frame 2](https://github.com/CollaboraOnline/online/assets/34243578/484dae63-11b7-4b84-86c1-30bc6e0d0af4)

### Describe the solution you'd like

I would prefer this list to be left aligned
![Frame 2(1)](https://github.com/CollaboraOnline/online/assets/34243578/1890b640-84ac-47cf-a3d9-8e2c1050c506)

### Additional context

This is related to #7602, #7603 as it is part of my list of changes I'd like to the following UI

**Comment by pedropintosilva** [comment]
agreed

**Comment by pedropintosilva** [comment]
It think this was fixed by 7912c89eef210fb60c073b631bc3d29496a78aba

**Comment by Minion3665** [comment]
Yep, certainly looks fixed for me and has been for some time... I haven't checked that it's that commit specifically but I'm more than happy to say it was fixed
