### ISSUE TITLE
Coolwsd RPM Update disable system service

### ISSUE THREAD

**Issue by rainerjung** [CollaboraOnline/online#7606]
Since a few months the RPM update procedure for coolwsd keeps the systemd service in disabled state after finishing. Before the update the service was enabled and up, after the update it is down and disabled. Manually re-enabling and starting it after the update works without problems. It seems there's a bug in the post script which fails to reenable the service after the update. Platform is EL9, more precisely Rock 9.2. Latest versions for which this was observed were 23.05.5.1 and 23.05.5.3.

**Comment by waclaw66** [comment]
Same for me at Fedora 38. Currently at 23.05.6.2.

**Comment by jejo86** [comment]
Same for me after automatic updates via DNF on Alma Linux 8.9.

**Comment by didierm** [comment]
Confirmed with latest version 23.05.7.5 on AlmaLinux 9.3.

**Comment by thebearon** [comment]
This is fixed thanks to Navid's change above.
