### ISSUE TITLE
Do not allow checkbox state to change if it is disabled

### ISSUE THREAD

**Issue by Darshan-upadhyay1110** [CollaboraOnline/online#7630]
### Describe the Bug

Disabled Checkbox is clickable using it's label

![image](https://github.com/CollaboraOnline/online/assets/61383886/0e99934f-dad3-41e1-8567-2a7a6cac4d72)

As we can see in above image the disabled button is clickable by it's label.

Go to
- Formate tab
- Click on `Character` Option
- Select `position`
- try to click on `Automatic` checkbox using it's label
- lable i mean click on text "Automatic"

Current behaviour :  Checkbox is getting check/Uncheck

Actual Behvaiour: In any case we should not give this control to user if it's disabled

**Comment by timur-g** [comment]
Good catch, thanks, fixed.
