### ISSUE TITLE
Android: "File > Properties" Misaligned Headings

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7638]
### Describe the Bug

In **File > Properties**, the menu that pops up has uneven + squished-together-headings:

### Steps to Reproduce

In Writer, after opening a document:

1. Press three-line hamburger menu in upper-right corner.
2. **File > Properties**

The menu appears at the bottom of device.

### Screenshots

Landscape:

<img alt="Collabora 23 05 5 2 - File Properties Alignment Landscape" src="https://github.com/CollaboraOnline/online/assets/5774324/be09ad33-7a8f-4911-942c-49e9a7bd27e3" width="50%"/>

Portrait:

<img alt="Collabora 23 05 5 2 - File Properties Alignment" src="https://github.com/CollaboraOnline/online/assets/5774324/6594d746-89ef-4f92-a7b1-c05225c2c14e" width="50%"/>

### Expected Behavior

The selections for:

- General
- Description
- Font
- Statistics

should be evenly spaced/distributed.

### Actual Behavior

"Font" + "Statistics" are jammed together along far-right edge.

And "Font" is very hard to click.

### Smartphone

- **Device:** OnePlus 6T
- **OS:** Android 11 (OxygenOS 11.1.2.2)

> COOLWSD version: 23.05.5.2
> git hash: 8fe1f0fe
> LOKit version:
> Collabora Office 23.05.5.2
> git hash: a2baff6

### Additional Context

I'd expect:

- All 4 to be ~ the same size when pressing with finger
- And/OR you should be able to "swipe" left/right through them.
   - Currently you can only PRESS each one with your finger.

Also, looks like the unchecked checkboxes in that "Font" screen are black in Dark Mode too:

- Embed fonts in the document
- Only embed fonts that are used in documents

Very hard to see.

**Comment by Darshan-upadhyay1110** [comment]
Not only a android bug but also Reproduce in mobile view.
