### ISSUE TITLE
Cannot open files anymore in Android app

### ISSUE THREAD

**Issue by timur-g** [CollaboraOnline/online#7680]
Cannot open files anymore in Android app. Just says Loading. 

OK with collabora-office-mobile-23.05-snapshot-armeabi-v7a-2023-10-29.
NOK with collabora-office-mobile-23.05-snapshot-armeabi-v7a-2023-11-12.

Android 11 LineageOS. Using armeabi as arm64 does not work for me.

**Comment by Ezinnem** [comment]
I can confirm this

**Comment by timur-g** [comment]
Release version 23.05.5 armeabi worked for me and this is a problem with snapshots that should be resolved by 23.05.6.
Separate issue is that arm64 did not work for me at all.
So this is not clear "last working was 21.11" - which 23.05 did you try?

**Comment by timur-g** [comment]
Fixed with https://github.com/CollaboraOnline/online/commit/00278bc5a9b1ba39f677cac0df8192ff087d2e71
