### ISSUE TITLE
Can not open encrypted PDF (Collabora for Android)

### ISSUE THREAD

**Issue by Nationalgeographic** [CollaboraOnline/online#7700]
### Describe the Bug
I'm using an e/OS version of Android. Since my company's payroll accounting was outsourced, I can no longer open this password-encrypted PDFs ( my payslip) with Collabora for Android. So, I think that the payroll accountants have changed something in the way the PDF is encrypted. There seems to be no more compatibility. 

### Steps to Reproduce
1. Try to open a password-encrypted PDF.
4. See error: the app just shuts down.

### Expected Behavior
I expect the app to be able to both open and decrypt the PDF.

### Actual Behavior
For a while there was a message that the password was incorrect, but now it locks up / crashes as soon as I even try to open the document.

### Screenshots
I can't provide a screenshot about a crashing app without an error code.

### Smartphone
(Please complete the following information)
 - **Device:** [Fairphone 3] 
 - **OS:** [e/OS S (Android 12)]

### Additional Context
I can still open the PDF on my PC with Thunderbird or Okular (KDE). On my phone I had success with proprietary apps like Adobe stuff, but I do not want to use these.

**Comment by timur-g** [comment]
Please write Android app version you open with. 
Can you ask them to make some sample with simple password, and attach it here?

**Comment by Nationalgeographic** [comment]
> Please write Android app version you open with. Can you ask them to make some sample with simple password, and attach it here?

Hello! Thanks for your answer.

It's Collabora app version **23.05.5.2.** 

YeahI will write them an email and then depending on their response, it may take several days.

**Comment by Nationalgeographic** [comment]
> Please write Android app version you open with. Can you ask them to make some sample with simple password, and attach it here?

I got one. They said that they don't have a sample payslip, but one without "important" data on it. Nevertheless, my employer's name and a random BIC (bank identifier code) can be seen on it. I wanted to black out the text somehow, but that is hardly possible in the PDF without being able to undo it (and without fundamentally changing the PDF, such as: make screenshot and convert again to pdf, which would not make sense for our purpose).

Hmm. Do you have any ideas?

**Comment by timur-g** [comment]
Can you check what enryption is used, depending on your program it may be File -> Properties -> Security and  "Show Details" , for example "128 bit RC4" or else.

**Comment by Nationalgeographic** [comment]
It's "256-bit AES".

**Comment by timur-g** [comment]
That should be upstream bug then.  It needs to be resolved in LIbreoffice. You may follow https://bugs.documentfoundation.org/show_bug.cgi?id=55425. 
I will close this one. Thanks.

**Comment by Nationalgeographic** [comment]
Thanks for your help! 

Oh, the ticket at LO has been open since 2012. Well, let's see when that will be fixed :p
