### ISSUE TITLE
"Rename" Icon Disappears After Dark Mode Turned On

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7703]
### Describe the Bug

In Writer, the **File > Rename** Icon disappears after turning on Dark Mode.

### Steps to Reproduce

0. Go to "File" tab.
   - See "Rename" icon is there.

1. Go to "View" tab.
   - Press "Dark Mode" button.

2. Go back to "File" tab.

BUG: See "Rename" icon is gone.

### Actual Behavior

Rename icon disappears.

### Expected Behavior

Rename icon NOT disappearing when clicking "Dark Mode".

### Video

[Collabora.23.05.5.4.-.File.Rename.Icon.Disappearing.Dark.Mode.webm](https://github.com/CollaboraOnline/online/assets/5774324/da0fbe59-14d2-4930-9ea7-7e9b94973db2)

- 0–5 seconds = Steps 0+1
- 5–8 seconds = Step 2
- 8+ = verifying it's gone

### Desktop

- **Collabora version:** 23.05.5.4
- **OS and version:** Linux Mint 21.1
- **Browser and version:** Firefox 119.0.1

> COOLWSD version: 23.05.5.4 (git hash: c3103030)
> LOKit version: Collabora Office 23.05.5.4 (git hash: d16375b)
> Served by: Linux Mint 21.1
> Server ID: bb24a08e

### Additional Context

This doesn't look to happen to any other icon/menu, only this one.

The only way to get it back was to refresh the browser page completely.

I couldn't see any error messages spit out in the log when pressing "Dark Mode" button.

**Comment by timur-g** [comment]
Yes. @Darshan-upadhyay1110 please see.

**Comment by Darshan-upadhyay1110** [comment]
Sure i will fix this
