### ISSUE TITLE
Cannot Type After Sidebar's "Line Spacing" Button Is Used

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7705]
### Describe the Bug

After using the sidebar's "Line Spacing" button (+ choosing a "Custom Value"):

- You cannot type in the document.

The keyboard can still type in the "Font Name"+other boxes, but trying to type in the document itself does nothing.

### Steps to Reproduce

In Writer:

0. Go to "View" tab + turn on "Sidebar".
1. In the sidebar:
  - Click on "Line Spacing" button.
2. Click back in document.

**BUG:** Try to type in the document.

### Video

[Collabora.23.05.5.4.-.Sidebar.Line.Spacing.Button.Can't.Type.webm](https://github.com/CollaboraOnline/online/assets/5774324/83bccf9b-9852-4a40-be0e-3a2b115de0c6)

- 0–3 seconds = Typing in document normally.
- 4–6 seconds = Steps 1+2.
- 6+ seconds = Typing furiously, but nothing is appearing.
   - 11+ = Showing I can still type in "Font Name" box though.

### Actual Behavior

Unable to type inside document after interacting with the sidebar's "Line Spacing" button.

### Expected Behavior

No effect. Especially when just clicking the button on/off, without even changing any options.

### Desktop

- **Collabora version:** 23.05.5.4
- **OS and version:** Linux Mint 21.1
- **Browser and version:** Firefox 119.0.1

> COOLWSD version: 23.05.5.4 (git hash: c3103030)
> LOKit version: Collabora Office 23.05.5.4 (git hash: d16375b)
> Served by: Linux Mint 21.1
> Server ID: bb24a08e

### Additional Context

See #7704 for other video.

Immediately after I stopped recording + submitted 7704 to Github, I tried to type in my ODT and continue testing other things... and saw nothing happened.

**Note 1:** It also looks like this bug happens if you choose anything in the:

- "Custom Value" dropdown.

While COOL is in this limbo state, you can get out of it by:

- Refreshing the entire page

OR:

1. Pressing the sidebar's "Line Spacing" button again.

2. Clicking on one of the 4 non-dropdown/button options instead:
  - Spacing: 1
  - Spacing: 1.15
  - Spacing: 1.5
  - Spacing: 2

**Note 2:** While narrowing this bug down, I also got disappearing text + a full COOL crash. I'm not sure what triggered it yet, but it was:

- Choosing between various options in that buggy "Line Spacing" dropdown.
- \+ Clicking back-and-forth between that menu and back in document.

**Comment by eszkadev** [comment]
Hi, this issue was recently addressed in https://github.com/CollaboraOnline/online/commit/a23adac78c34d3ea1717954fcab1a3caaeef0bbb

I think it should be fixed now in current master. @Ezinnem could you verify?

**Comment by Ezinnem** [comment]
Yes, I can verify.
See the recording of my screen:

https://github.com/CollaboraOnline/online/assets/54344301/7dfee365-6ba7-464c-9bac-23e2fcda1706



I tested using:

COOLWSD version: 23.05.5.4 (git hash: [3f46c1db](https://github.com/CollaboraOnline/online/commits/3f46c1db) (E))
LOKit version: Collabora Office 23.05.5.4 (git hash: [4c6c60d](https://git.libreoffice.org/core/+log/4c6c60d))

**Comment by Tex2002ans** [comment]
Fantastic. Great to hear it was fixed already!

Of course, the one time I decide NOT to upgrade to the latest version... lol.

I skimmed the previous week's commits and thought "Only a few. Doesn't look like anything with the sidebar buttons."
