### ISSUE TITLE
Writer: Color emoji displayed but not printed

### ISSUE THREAD

**Issue by jgmy** [CollaboraOnline/online#7733]
### Describe the Bug
Color emoji are displayed in writer, but not printed. Exporting to PDF shows blank spaces instead of emoji.

### Steps to Reproduce
1. Write a socks emoji (🧦). Test also with rain (🌧☔), :-( ( ☹ ) and T-shirt (👕)
2. You can see emoji in document.
3. Print or Export to PDF
4. emoji is not displayed in PDF, it is not printed.

### Expected Behavior
Collabora Office is supposed to be WYSYWIG, so you should get in screen what you get in print. Either do not show emojis if they are not going to be printed, or show them if they are going to be printed.
(It seems they SHOULD be embedded in the PDF before printing, but they aren't).

### Actual Behavior
Emojis are shown in document but not printed.

### Screenshots
PDF screenshot (paper print is identical to this PDF)
![screenshotcollaboraemojibug-2](https://github.com/CollaboraOnline/online/assets/2573642/47c0ec96-1772-4a57-833f-c46374e81f4a)
Collabora Office Writer screenshot
![screenshotcollaboraemojibug](https://github.com/CollaboraOnline/online/assets/2573642/452f2129-a9d6-41a8-8379-a16a8ee88a86)

### Desktop
(Please complete the following information)
 - Collabora Office 21.06.37.1 git hash: 809030c
 - Server OS: Red Hat Enterprise Linux 8.7 (Ootpa)
 - Client OS: Microsoft Windows [Version 10.0.19045.3693]
 - **Browser and version:** Versión 119.0.6045.160 (Build oficial) (64 bits)

**Comment by jgmy** [comment]
Edit: images captions were swept.

**Comment by timur-g** [comment]
21.06 is old version that does not receive fixes, did you try with the current 23.05?

**Comment by jgmy** [comment]
I can't change collabora version, since I'm just an user, not an admin.

Thanks for your reply.
