### ISSUE TITLE
"The Server has been disconnected" when accessing a cell with Unicode content

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#7751]
### Describe the Bug
In the Collabora Online Weekly Meeting #145 I found an issue in the calc document:
https://staging-perf.eu.collaboraonline.com/nextcloud/index.php/s/CzW52xSxStk79WD

I added the following text to a calc cell (cell G17 in Sheet13_2):

```
🎵 Hello World 
🎵
🎵
```
I then copy/pasted the "🎵" after "Hello Wold" and now, whenever I access to cell I get the following error: "The Server has been disconnected".

See the video:
[Screencast from 2023-11-30 12-57-39.webm](https://github.com/CollaboraOnline/online/assets/1211300/bfff4bad-ad65-4665-91b5-820cf37e2d06)

**Comment by timur-g** [comment]
I do not reproduce with current 23.05. 
I used file from the link. I noticed some additional symbol in that cell after "Hello World" that is not in the file. 
Can you please retest and clarify?

**Comment by nikslor** [comment]
Hi @timur-g 

I agree, the problem can't be reproduced anymore in newer versions. Let's close this one.
