### ISSUE TITLE
Calc: Dark-on-Dark '=' Icon + Groups

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7752]
### Describe the Bug

In Calc with Dark Mode ON:

- Near the formula bar:
   - The `=` icon is black.
- Above the cells, when Groups are used.
   - The `+` expander and lines are black-on-black.

![Collabora 23 05 5 4 - COOL Weekly 145 - Dark on Dark Icons](https://github.com/CollaboraOnline/online/assets/5774324/ca4bec05-a5dc-4643-a9f8-075987cb7513)

### Steps to Reproduce

In Calc:

1. **View > Dark Mode**
2. Select a cell.

You should see the `=` icon near formula bar.

(I'm unsure how to insert Groups, but someone else in the document added them.)

### Actual Behavior

Dark-on-Dark.

### Expected Behavior

Light-on-Dark.

### Desktop

- **Collabora version:** 23.05.5.4
- **OS and version:** Windows 10
- **Browser and version:** Chrome 119.0.6045.199 (Official Build) (64-bit)

> COOLWSD version: 23.05.5.4 (git hash: 97f986a4 (E))
> LOKit version: Collabora Office 23.05.5.4 (git hash: 866b0a7)
> Served by: openSUSE Leap 15.5
> Server ID: c6df5601

### Additional Context

Happened during COOL Weekly 145.

**Comment by Darshan-upadhyay1110** [comment]
@timur-g  for `fontcolor` and `backgroundColor` i have already PR => in Review 
https://github.com/CollaboraOnline/online/pull/7711

**Comment by timur-g** [comment]
= and groups still wrong.

**Comment by Darshan-upadhyay1110** [comment]
@timur-g i have this in my list will start to work on soon. Thanks for the reporting :)

**Comment by timur-g** [comment]
This should be seen OK now.
