### ISSUE TITLE
Calc: View > Dark Mode = Jump to "Home" tab

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7754]
### Describe the Bug

In Calc, pressing "Dark Mode" button flipped Calc to the "Home" tab.

(This happened during COOL Weekly 145.)

### Steps to Reproduce

In Calc:

1. Go to "View" tab.
2. Press "Dark Mode" button.

### Actual Behavior

Jumping from "View" to "Home" tab.

### Expected Behavior

Pressing "Dark Mode" button should do nothing but change UI to dark.

### Desktop

- **Collabora version:** 23.05.5.4
- **OS and version:** Windows 10
- **Browser and version:** Chrome 119.0.6045.199 (Official Build) (64-bit)

> COOLWSD version: 23.05.5.4 (git hash: 97f986a4 (E))
> LOKit version: Collabora Office 23.05.5.4 (git hash: 866b0a7)
> Served by: openSUSE Leap 15.5
> Server ID: c6df5601

### Additional Context

I **WAS NOT** able to reproduce on my local:

> COOLWSD version: 23.05.5.4 (git hash: c3103030)
> LOKit version: Collabora Office 23.05.5.4 (git hash: 97fcfa8)
> Served by: Linux Mint 21.1
> Server ID: ae081e03

so it might have something to do with many people editing in the same spreadsheet at the same time, because I was able to consistently get it to occur during meeting.

**Comment by timur-g** [comment]
Let us close unless reproduced.
