### ISSUE TITLE
In docker log sh: 1: /usr/bin/loolmount: Operation not permitted

### ISSUE THREAD

**Issue by triopsi** [CollaboraOnline/online#779]
Helo dear collabora community, 

i pull the last docker container image. My Host is a Ubuntu 20.04 LTS.

> root@dockerhost:~# lsb_release -a
> Distributor ID: Ubuntu
> Description:    Ubuntu 20.04.1 LTS
> Release:        20.04
> Codename:       focal

And docker:

> root@dockerhost:~# docker version
> Client: Docker Engine - Community
>  Version:           19.03.13
>  API version:       1.40
>  Go version:        go1.13.15
>  Git commit:        4484c46d9d
>  Built:             Wed Sep 16 17:02:52 2020
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          19.03.13
>   API version:      1.40 (minimum version 1.12)
>   Go version:       go1.13.15
>   Git commit:       4484c46d9d
>   Built:            Wed Sep 16 17:01:20 2020
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.3.7
>   GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
>  runc:
>   Version:          1.0.0-rc10
>   GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
>  docker-init:
>   Version:          0.18.0
>   GitCommit:        fec3683

I created a Docker container and connected it to Nextcloud with reverse proxy. Also worked wonderfully

Create statement:

> docker run -t -d -p 9980:9980 -e 'domain=domain\\.de' -e "username=admin" -e "password=secret" --name "collabory_app" --restart always --cap-add MKNOD collabora/code:wopiproof

I can edit a file, but i still get the following error in the log:

> frk-00038-00038 2020-11-26 09:17:29.572542 [ forkit ] ERR  Failed to get the realpath of [/etc/timezone] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> frk-00038-00038 2020-11-26 09:17:29.573287 [ forkit ] ERR  Failed to get the realpath of [/etc/localtime] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> kit-00053-00038 2020-11-26 09:17:30.307157 [ kit_spare_003 ] ERR  Failed to get the realpath of [/etc/timezone] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> kit-00053-00038 2020-11-26 09:17:30.307831 [ kit_spare_003 ] ERR  Failed to get the realpath of [/etc/localtime] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> sh: 1: /usr/bin/loolmount: Operation not permitted,
> frk-00038-00038 2020-11-26 09:17:32.611920 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/212a1JJ8VnCsgwdO/tmp].| common/JailUtil.cpp:68,
> sh: 1: /usr/bin/loolmount: Operation not permitted,
> frk-00038-00038 2020-11-26 09:17:32.631679 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/212a1JJ8VnCsgwdO/lo].| common/JailUtil.cpp:68,
> sh: 1: /usr/bin/loolmount: Operation not permitted,
> frk-00038-00038 2020-11-26 09:17:32.651440 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/212a1JJ8VnCsgwdO].| common/JailUtil.cpp:68,
> wsd-00006-00045 2020-11-26 09:18:35.625822 [ docbroker_001 ] WRN  Dropping empty tile response: tile: nviewid=0 part=0 width=256 height=256 tileposx=7680 tileposy=3840 tilewidth=3840 tileheight=3840 oldwid=62 wid=62 ver=299| wsd/DocumentBroker.cpp:2091,
> wsd-00006-00045 2020-11-26 09:18:41.134678 [ docbroker_001 ] WRN  Dropping empty tile response: tile: nviewid=0 part=0 width=256 height=256 tileposx=7680 tileposy=3840 tilewidth=3840 tileheight=3840 oldwid=65 wid=65 ver=310| wsd/DocumentBroker.cpp:2091,
> sh: 1: /usr/bin/loolmount: Operation not permitted,
> frk-00038-00038 2020-11-26 09:19:24.492606 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/LrUdQ9nipzqbIhwQ/tmp].| common/JailUtil.cpp:68,
> sh: 1: /usr/bin/loolmount: Operation not permitted,
> frk-00038-00038 2020-11-26 09:19:24.514771 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/LrUdQ9nipzqbIhwQ/lo].| common/JailUtil.cpp:68,
> sh: 1: /usr/bin/loolmount: Operation not permitted,
> frk-00038-00038 2020-11-26 09:19:24.535879 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/LrUdQ9nipzqbIhwQ].| common/JailUtil.cpp:68,
> frk-00038-00038 2020-11-26 09:19:25.636484 [ forkit ] ERR  Failed to get the realpath of [/etc/timezone] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> frk-00038-00038 2020-11-26 09:19:25.637054 [ forkit ] ERR  Failed to get the realpath of [/etc/localtime] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> kit-00079-00038 2020-11-26 09:19:26.415601 [ kit_spare_004 ] ERR  Failed to get the realpath of [/etc/timezone] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> kit-00079-00038 2020-11-26 09:19:26.416181 [ kit_spare_004 ] ERR  Failed to get the realpath of [/etc/localtime] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> sh: 1: /usr/bin/loolmount: Operation not permitted,
> frk-00038-00038 2020-11-26 09:19:28.472187 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/5DY2XkmuEquYvCKi/tmp].| common/JailUtil.cpp:68,
> sh: 1: /usr/bin/loolmount: Operation not permitted,
> frk-00038-00038 2020-11-26 09:19:28.495195 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/5DY2XkmuEquYvCKi/lo].| common/JailUtil.cpp:68,
> sh: 1: /usr/bin/loolmount: Operation not permitted,
> frk-00038-00038 2020-11-26 09:19:28.517806 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/5DY2XkmuEquYvCKi].| common/JailUtil.cpp:68,
> frk-00038-00038 2020-11-26 09:21:01.083749 [ forkit ] ERR  Failed to get the realpath of [/etc/timezone] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> frk-00038-00038 2020-11-26 09:21:01.083844 [ forkit ] ERR  Failed to get the realpath of [/etc/localtime] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> kit-00088-00038 2020-11-26 09:21:02.352641 [ kit_spare_005 ] ERR  Failed to get the realpath of [/etc/timezone] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> kit-00088-00038 2020-11-26 09:21:02.371972 [ kit_spare_005 ] ERR  Failed to get the realpath of [/etc/localtime] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> kit-00088-00097 2020-11-26 09:21:03.656697 [ thread-pool ] ERR  #26 Invoked from foreign thread. Expected: 0x7f98c6662780 but called from 140293210887936 (97).| ./net/Socket.hpp:305,
> kit-00088-00097 2020-11-26 09:21:03.656803 [ thread-pool ] ERR  #26 Invoked from foreign thread. Expected: 0x7f98c6662780 but called from 140293210887936 (97).| ./net/Socket.hpp:305,
> kit-00088-00097 2020-11-26 09:21:03.656829 [ thread-pool ] ERR  #26 Invoked from foreign thread. Expected: 0x7f98c6662780 but called from 140293210887936 (97).| ./net/Socket.hpp:305,
> kit-00088-00097 2020-11-26 09:21:03.662090 [ thread-pool ] ERR  #26 Invoked from foreign thread. Expected: 0x7f98c6662780 but called from 140293210887936 (97).| ./net/Socket.hpp:305,
> kit-00088-00097 2020-11-26 09:21:03.662442 [ thread-pool ] ERR  #26 Invoked from foreign thread. Expected: 0x7f98c6662780 but called from 140293210887936 (97).| ./net/Socket.hpp:305,
> kit-00088-00097 2020-11-26 09:21:03.662644 [ thread-pool ] ERR  #26 Invoked from foreign thread. Expected: 0x7f98c6662780 but called from 140293210887936 (97).| ./net/Socket.hpp:305,
> kit-00088-00097 2020-11-26 09:21:03.663241 [ thread-pool ] ERR  #26 Invoked from foreign thread. Expected: 0x7f98c6662780 but called from 140293210887936 (97).| ./net/Socket.hpp:305,
> kit-00088-00097 2020-11-26 09:21:03.663541 [ thread-pool ] ERR  #26 Invoked from foreign thread. Expected: 0x7f98c6662780 but called from 140293210887936 (97).| ./net/Socket.hpp:305,
> kit-00088-00097 2020-11-26 09:21:03.663706 [ thread-pool ] ERR  #26 Invoked from foreign thread. Expected: 0x7f98c6662780 but called from 140293210887936 (97).| ./net/Socket.hpp:305,
> sh: 1: /usr/bin/loolmount: Operation not permitted,
> frk-00038-00038 2020-11-26 09:21:05.454553 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/bdOMm8CrusOKK4dF/tmp].| common/JailUtil.cpp:68,
> sh: 1: /usr/bin/loolmount: Operation not permitted,
> frk-00038-00038 2020-11-26 09:21:05.475137 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/bdOMm8CrusOKK4dF/lo].| common/JailUtil.cpp:68,
> sh: 1: /usr/bin/loolmount: Operation not permitted,
> frk-00038-00038 2020-11-26 09:21:05.499612 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/bdOMm8CrusOKK4dF].| common/JailUtil.cpp:68,
> frk-00038-00038 2020-11-26 09:21:05.942254 [ forkit ] ERR  Failed to get the realpath of [/etc/timezone] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> frk-00038-00038 2020-11-26 09:21:05.942933 [ forkit ] ERR  Failed to get the realpath of [/etc/localtime] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> kit-00105-00038 2020-11-26 09:21:06.673137 [ kit_spare_006 ] ERR  Failed to get the realpath of [/etc/timezone] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> kit-00105-00038 2020-11-26 09:21:06.673298 [ kit_spare_006 ] ERR  Failed to get the realpath of [/etc/localtime] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> sh: 1: /usr/bin/loolmount: Operation not permitted,
> frk-00038-00038 2020-11-26 09:21:22.499385 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/A5GFwhGZ2IyZ38ap/tmp].| common/JailUtil.cpp:68,
> sh: 1: /usr/bin/loolmount: Operation not permitted,
> frk-00038-00038 2020-11-26 09:21:22.520903 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/A5GFwhGZ2IyZ38ap/lo].| common/JailUtil.cpp:68,
> sh: 1: /usr/bin/loolmount: Operation not permitted,
> frk-00038-00038 2020-11-26 09:21:22.543591 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/A5GFwhGZ2IyZ38ap].| common/JailUtil.cpp:68,
> frk-00038-00038 2020-11-26 09:21:22.982339 [ forkit ] ERR  Failed to get the realpath of [/etc/timezone] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> frk-00038-00038 2020-11-26 09:21:22.982472 [ forkit ] ERR  Failed to get the realpath of [/etc/localtime] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> kit-00105-00118 2020-11-26 09:21:23.024508 [ thread-pool ] ERR  #26 Invoked from foreign thread. Expected: 0x7f98c6662780 but called from 140293210887936 (118).| ./net/Socket.hpp:305,
> kit-00105-00118 2020-11-26 09:21:23.025285 [ thread-pool ] ERR  #26 Invoked from foreign thread. Expected: 0x7f98c6662780 but called from 140293210887936 (118).| ./net/Socket.hpp:305,
> kit-00105-00118 2020-11-26 09:21:23.025625 [ thread-pool ] ERR  #26 Invoked from foreign thread. Expected: 0x7f98c6662780 but called from 140293210887936 (118).| ./net/Socket.hpp:305,
> kit-00105-00118 2020-11-26 09:21:23.032096 [ thread-pool ] ERR  #26 Invoked from foreign thread. Expected: 0x7f98c6662780 but called from 140293210887936 (118).| ./net/Socket.hpp:305,
> kit-00105-00118 2020-11-26 09:21:23.032841 [ thread-pool ] ERR  #26 Invoked from foreign thread. Expected: 0x7f98c6662780 but called from 140293210887936 (118).| ./net/Socket.hpp:305,
> kit-00105-00118 2020-11-26 09:21:23.033478 [ thread-pool ] ERR  #26 Invoked from foreign thread. Expected: 0x7f98c6662780 but called from 140293210887936 (118).| ./net/Socket.hpp:305,
> kit-00105-00118 2020-11-26 09:21:23.034381 [ thread-pool ] ERR  #26 Invoked from foreign thread. Expected: 0x7f98c6662780 but called from 140293210887936 (118).| ./net/Socket.hpp:305,
> kit-00105-00118 2020-11-26 09:21:23.035157 [ thread-pool ] ERR  #26 Invoked from foreign thread. Expected: 0x7f98c6662780 but called from 140293210887936 (118).| ./net/Socket.hpp:305,
> kit-00105-00118 2020-11-26 09:21:23.035655 [ thread-pool ] ERR  #26 Invoked from foreign thread. Expected: 0x7f98c6662780 but called from 140293210887936 (118).| ./net/Socket.hpp:305,
> kit-00117-00038 2020-11-26 09:21:23.669874 [ kit_spare_007 ] ERR  Failed to get the realpath of [/etc/timezone] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> kit-00117-00038 2020-11-26 09:21:23.670035 [ kit_spare_007 ] ERR  Failed to get the realpath of [/etc/localtime] (ENOENT: No such file or directory)| common/FileUtil.cpp:256,
> sh: 1: /usr/bin/loolmount: Operation not permitted,
> frk-00038-00038 2020-11-26 09:21:25.021717 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/q4j9leBVFISWNhpH/tmp].| common/JailUtil.cpp:68,
> sh: 1: /usr/bin/loolmount: Operation not permitted,
> frk-00038-00038 2020-11-26 09:21:25.044894 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/q4j9leBVFISWNhpH/lo].| common/JailUtil.cpp:68,
> sh: 1: /usr/bin/loolmount: Operation not permitted,
> frk-00038-00038 2020-11-26 09:21:25.068131 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/q4j9leBVFISWNhpH].| common/JailUtil.cpp:68,

I don't understand the mistake or error. Can someone help?

**Comment by gaussli** [comment]
I have the same problem. In the collabora container, I can find the command "/usr/bin/loolmount", and the file permisison is the same as file named "loolwsd" or "loolconfig", all both are "-rwxr-xr-x". But I run command "/usr/bin/loolmount", then the error "bash: /usr/bin/loolmount: Operation not permitted" showed.

**Comment by thebearon** [comment]
Yes, this is related to doing bind mount that was introduced in 6.4, and it apparently doesn't align with the permissions in a container.

**Comment by Ashod** [comment]
> I have the same problem. In the collabora container, I can find the command "/usr/bin/loolmount", and the file permisison is the same as file named "loolwsd" or "loolconfig", all both are "-rwxr-xr-x". But I run command "/usr/bin/loolmount", then the error "bash: /usr/bin/loolmount: Operation not permitted" showed.

Hi @gaussli,

loolmount is not intended to be executed by end users. The error you get is normal and expected.

What are you expecting to happen when you run it?

Is there an issue you are trying to solve that we can help with?

Thank you.

**Comment by Ashod** [comment]
Hi @triopsi,

Thanks for reporting this.

> I don't understand the mistake or error. Can someone help?

If there are no functional issues, then you can safely ignore the errors.

The errors are hinting that the jail creation cannot be done in the new and more efficient way, which is important for native and large deployments. There is fallback that defaults to the older way of creating jails that is used through version 4.

While it would be great not to have these errors, and even better if the bind-mounting logic works in the docker, they should not impact the functionality in any way. If that is not the case, please do report any issues you experience.

Meanwhile, I think it's a good report to improve the situation in the docker, so thanks for that.

Thanks.

**Comment by Ashod** [comment]
@triopsi, @gaussli, can you please _add_ `--privileged` to your `docker run` command and report back please?

I expect it will resolve the issue and you should not see those errors.

Thanks.

**Comment by gaussli** [comment]
Hi @Ashod 
Thanks for reply.



> > I have the same problem. In the collabora container, I can find the command "/usr/bin/loolmount", and the file permisison is the same as file named "loolwsd" or "loolconfig", all both are "-rwxr-xr-x". But I run command "/usr/bin/loolmount", then the error "bash: /usr/bin/loolmount: Operation not permitted" showed.
> 
> Hi @gaussli,
> 
> loolmount is not intended to be executed by end users. The error you get is normal and expected.
> 
> What are you expecting to happen when you run it?
> 
> Is there an issue you are trying to solve that we can help with?
> 
> Thank you.

Hi, @Ashod 
Thanks for reply.

I run collaboraonline with docker like this command on CentOS 7.8:
`docker run -t -d -p 9980:9980 -e "domain=" -e "username=admin" -e "password=admin" -e "extra_params=-o:ssl.enable=false" -v /etc/localtime:/etc/localtime -v /etc/timezone:/etc/timezone -v /opt/loolwsd.xml:/etc/loolwsd/loolwsd.xml --restart=always --name collabora collabora/code`
And in the file 'loolwsd.xml', I only change the 'ssl.enable' from 'true' to 'false', and 'storage.filesystem' form 'false' to 'true'.

Then I call jodConverter framework's method in Java:
```
RemoteOfficeManager officeManager = RemoteOfficeManager.make("http://192.168.10.2:9980");
officeManager.start();
RemoteConverter.make(officeManager).convert(inputStream).as(inputDocumentFormat).to(outputStream).as(DefaultDocumentFormatRegistry.PDF).execute();
```
the result is convert success adn I get the correct outputstream, but I find some error log in docker container like this:
```
kit-00728-00745 2020-11-27 12:18:58.612858 [ thread-pool ] ERR  #25 Invoked from foreign thread. Expected: 0x7fe9094e1780 but called from 140638000908032 (745).| ./net/Socket.hpp:305
kit-00728-00745 2020-11-27 12:18:58.612992 [ thread-pool ] ERR  #25 Invoked from foreign thread. Expected: 0x7fe9094e1780 but called from 140638000908032 (745).| ./net/Socket.hpp:305
kit-00728-00745 2020-11-27 12:18:58.613009 [ thread-pool ] ERR  #25 Invoked from foreign thread. Expected: 0x7fe9094e1780 but called from 140638000908032 (745).| ./net/Socket.hpp:305
kit-00728-00745 2020-11-27 12:18:58.625173 [ thread-pool ] ERR  #25 Invoked from foreign thread. Expected: 0x7fe9094e1780 but called from 140638000908032 (745).| ./net/Socket.hpp:305
kit-00728-00745 2020-11-27 12:18:58.625199 [ thread-pool ] ERR  #25 Invoked from foreign thread. Expected: 0x7fe9094e1780 but called from 140638000908032 (745).| ./net/Socket.hpp:305
kit-00728-00745 2020-11-27 12:18:58.625216 [ thread-pool ] ERR  #25 Invoked from foreign thread. Expected: 0x7fe9094e1780 but called from 140638000908032 (745).| ./net/Socket.hpp:305
kit-00728-00745 2020-11-27 12:18:58.625274 [ thread-pool ] ERR  #25 Invoked from foreign thread. Expected: 0x7fe9094e1780 but called from 140638000908032 (745).| ./net/Socket.hpp:305
kit-00728-00745 2020-11-27 12:18:58.625292 [ thread-pool ] ERR  #25 Invoked from foreign thread. Expected: 0x7fe9094e1780 but called from 140638000908032 (745).| ./net/Socket.hpp:305
kit-00728-00745 2020-11-27 12:18:58.625308 [ thread-pool ] ERR  #25 Invoked from foreign thread. Expected: 0x7fe9094e1780 but called from 140638000908032 (745).| ./net/Socket.hpp:305
sh: 1: /usr/bin/loolmount: Operation not permitted
frk-00038-00038 2020-11-27 12:19:00.234212 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/W1QFaIPzj400AHvf/tmp].| common/JailUtil.cpp:68
sh: 1: /usr/bin/loolmount: Operation not permitted
frk-00038-00038 2020-11-27 12:19:00.239477 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/W1QFaIPzj400AHvf/lo].| common/JailUtil.cpp:68
sh: 1: /usr/bin/loolmount: Operation not permitted
frk-00038-00038 2020-11-27 12:19:00.244769 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/W1QFaIPzj400AHvf].| common/JailUtil.cpp:68
sh: 1: /usr/bin/loolmount: Operation not permitted
frk-00038-00038 2020-11-27 12:19:11.852338 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/iVb4r7ElOprzqLKx/tmp].| common/JailUtil.cpp:68
sh: 1: /usr/bin/loolmount: Operation not permitted
frk-00038-00038 2020-11-27 12:19:11.861205 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/iVb4r7ElOprzqLKx/lo].| common/JailUtil.cpp:68
sh: 1: /usr/bin/loolmount: Operation not permitted
frk-00038-00038 2020-11-27 12:19:11.866598 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/iVb4r7ElOprzqLKx].| common/JailUtil.cpp:68
sh: 1: /usr/bin/loolmount: Operation not permitted
```

SInce the converter can be done successfuly, I think is there the optimizing may be realized?

**Comment by gaussli** [comment]
I access into the docker container with command `docker exec -it collabora bash`
And I check the permission about 'loolmount' file like this: 
```
lool@6d67fb61241a:/$ ls -al /usr/bin/ |grep lool
-rwxr-xr-x. 1 root root   2661104 Nov 20 16:10 loolconfig
-rwxr-xr-x. 1 root root   3484360 Nov 20 16:10 loolconvert
-rwxr-xr-x. 1 root root   4639568 Nov 20 16:10 loolforkit
-rwxr-xr-x. 1 root root     10232 Nov 20 16:10 loolmount
-rwxr-xr-x. 1 root root   5877712 Nov 20 16:10 loolwsd
-rwxr-xr-x. 1 root root       854 Nov 20 16:10 loolwsd-generate-proof-key
-rwxr-xr-x. 1 root root      4592 Nov 20 16:10 loolwsd-systemplate-setup
``` 
I don't think there are any mistakes

**Comment by triopsi** [comment]
> 
> 
> Hi @triopsi,
> 
> Thanks for reporting this.
> 
> > I don't understand the mistake or error. Can someone help?
> 
> If there are no functional issues, then you can safely ignore the errors.
> 
> The errors are hinting that the jail creation cannot be done in the new and more efficient way, which is important for native and large deployments. There is fallback that defaults to the older way of creating jails that is used through version 4.
> 
> While it would be great not to have these errors, and even better if the bind-mounting logic works in the docker, they should not impact the functionality in any way. If that is not the case, please do report any issues you experience.
> 
> Meanwhile, I think it's a good report to improve the situation in the docker, so thanks for that.
> 
> Thanks.

Thanks @Ashod for your answer. I think i can accept your reply. It still works fine and i can edit my documents. Maybe anyone can improve the log output. It's not pretty. For me is this a info state and not a error state :)

> 
> 
> @triopsi, @gaussli, can you please _add_ `--privileged` to your `docker run` command and report back please?
> 
> I expect it will resolve the issue and you should not see those errors.
> 
> Thanks.

I tested it and i can say its works finely. I can`t see error message in the log anymore. Thanks :)

**Comment by triopsi** [comment]
My solution docker command:

`docker run -t -d -p 9980:9980 -e "domain=domain\\.com" -e "username=admin" -e "password=<StrongPassword>" -v /etc/localtime:/etc/localtime -v /etc/timezone:/etc/timezone --name Collabora_app_prod --restart always --cap-add MKNOD --privileged collabora/code`

**Comment by Ashod** [comment]
> I tested it and i can say its works finely. I can`t see error message in the log anymore. Thanks :)

Fantastic @triopsi, thanks for the confirmation. Your docker command looks sensible to me.

Btw, do you experience any issues if you don't map your /etc/localtime and /etc/timezone files? (I know they are missing from the docker image.)

**Comment by Ashod** [comment]
Thanks for the details @gaussli! 

> the converter is successful and I get the correct outputstream, but I find some error log in docker container like this:

Please _add_ --privileged to your docker run command, you shouldn't see those errors after that (and performance should be optimal.

Let me know the results please, and we should be able to close this issue.

Thanks.

**Comment by gaussli** [comment]
> Thanks for the details @gaussli!
> 
> > the converter is successful and I get the correct outputstream, but I find some error log in docker container like this:
> 
> Please _add_ --privileged to your docker run command, you shouldn't see those errors after that (and performance should be optimal.
> 
> Let me know the results please, and we should be able to close this issue.
> 
> Thanks.

I tested it and it worked. I accept the your reply too. 
Thanks for resolution. Wonderful!

**Comment by timar** [comment]
Let's close this, then.

**Comment by wvengen** [comment]
It's great that adding privileged solves the error, but I would very much hesitate to do this on any public-facing server. Doesn't this allow bugs with Collabora Online to easily escape the Docker container and get access to the host system?

If so, I hope that anyone documenting this (including docker-compose templates and blogs) will always add a big warning.

**Comment by Ashod** [comment]
Hi @wvengen,

> It's great that adding privileged solves the error, but I would very much hesitate to do this on a server running other apps. Doesn't this allow bugs with Collabora Online to easily escape the Docker container and get access to the host system?
> 
> If so, I hope that anyone documenting this (including docker-compose templates and blogs) will always add a big warning.

Normally privileged wouldn't be recommended/used for arbitrary dockers from untrusted sources. Yes.

In this case, there are two cases: 1) the user can leave out privileged, or, 2) enable privileged.

In 1) the result will be a bit of noise (the errors reported), there will be no functional issues. However, spawning documents will depend on how fast docker can hard-link and/or copy files (thousands of them) that are necessary to create the chroot used for each document. In some cases hard-linking is so slow that it takes minutes to create the chroot, which can be a serious issue (document loading fails in the extreme case).

In 2) adding privileged makes it possible to bind-mount the chroot, *in addition* to chroot. This makes it virtually impossible for one document to modify the systemplate used to create the chroot for each document, because the bind-mount is read-only. Of course chroot is already a security feature in Linux to contain a process in a single filesystem, which limits possible security risks. Beyond the added benefit of security with bind-mounting, it's also very fast (typically under ~150 ms per chroot).

Using dockers in production is an advanced setup that come with its own nuances. One should know the consequences of the features used, and the trade offs available. Enabling privileged would be unsafe when running untrusted software in the docker.

But this is not a security advice!

Hope this clarifies things, and feel free to ask questions and/or raise concerns as necessary.

**Comment by wvengen** [comment]
Thank you very much for the background and reason for the use of privileged with Docker.
That is really helpful and helps to make a good trade-off.

**Comment by finalclass** [comment]
Privileged does not work in docker swarm. Is there any other solution to this issue?

**Comment by ledufakademy** [comment]
this is just unacceptable fix : run app in privileged container  !!!

**Comment by Ashod** [comment]
> this is just unacceptable fix : run app in privileged container !!!

Hi @ledufakademy and @finalclass,

Unfortunately, we can't have it both ways. If we want fast jail setup (on systems that docker file linking is extremely slow), then we need to enable mounting, which requires privileged containers.

If privileged containers are unacceptable, then simply ignore the errors/warnings! The performance will be slower (sometimes extremely slow), but *it will work*. (Normally, linking files is very fast, but in docker they are often slow. The only faster solution we found is mounting, which is a privileged syscall in docker.)

So, privileged containers are only for those who want the fastest performance (when creating new jails for new documents). Privileged is *not* a requirement.

If the performance in docker is unacceptable without mounting, consider using a different container. Alternatively, you might want to explore mounting external filesystems in docker, which is certainly much more complex in terms of infrastructure and maintenance, but it is doable, if docker is a must and the performance is a serious issue.

Hope this helps.

**Comment by uamrws** [comment]
in docker-compose.yml, you need add `cap_add: SYS_ADMIN`
