### ISSUE TITLE
mixed language settings between toolbar and sidebar

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#780]
as the sidebar come from Collabora and the toolbar from COOL when there are mixed language settings, the UI can be a bit confused. Like you can see for example at the staging collaboraonline server.

![2020-11-26 11_14_50-Nextcloud](https://user-images.githubusercontent.com/8517736/100338512-f84a6a80-2fd8-11eb-8d9e-4b63970d6cc3.png)

**Comment by Ezinnem** [comment]
I can confirm this occurs in 6.4.14 (git hash: [fdc7ddf7](https://github.com/CollaboraOnline/online/commits/fdc7ddf7)).

**Comment by timar** [comment]
@Ezinnem What are the reproduction steps?

**Comment by Ezinnem** [comment]
@timar 

These are the reproduction steps:

1. set the Locale/Language to French/Francais.
2. Load .odt file and click to view the sidebar

Notice the Bold, Italics, Underline, and Strikethrough icons in the sidebar are different from those in the Notebookbar

**Comment by Andreas-Kainz** [comment]
I thought with the native Sidebar this issue should be fixed, but the tooltip of the classic toolbar and the sidebar are different.

**Comment by Franz-Heinz** [comment]
Same problem here. The topbar is presented in german (as it is supposed to) and the sidebar just remains english.

This is a real problem for our users without english skills.

![topbar](https://user-images.githubusercontent.com/63586284/162197681-79f7edcc-f134-47b0-ac9e-be9c21cf52a8.png)

![sidebar](https://user-images.githubusercontent.com/63586284/162197706-56b55368-f8b0-411b-9eef-e247c4aef6c3.png)

**Comment by thebearon** [comment]
@Franz-Heinz that's different, you didn't install the language-specific packages, see: https://sdk.collaboraonline.com/docs/installation/Installation_from_packages.html#localization

**Comment by thebearon** [comment]
> I thought with the native Sidebar this issue should be fixed, but the tooltip of the classic toolbar and the sidebar are different.

@Andreas-Kainz, can you please give a few specific examples?

**Comment by pedropintosilva** [comment]
closing this as it already passed quite long time
