### ISSUE TITLE
Calc: Recalculate data not available in Classic mode menu

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#781]
**Describe the bug**
https://forum.collaboraonline.com/t/processing-data-in-code-calc/80

**To Reproduce**
1. open a spreadsheet document
2. Select one cell with any "dynamic" value
3. Click on Data top menu
4. No Recalculate command available

note: recalculate date is available in notebookbar mode: Data tab > first icon

**Comment by eszkadev** [comment]
tip: it is probably .uno:Calculate command

**Comment by ayhanyalcinsoy** [comment]
I searched but  can't find .uno:Calculate  at CollaboraOnline/online repo

**Comment by pedropintosilva** [comment]
@ayhanyalcinsoy thanks for taking an interest in this issue : )

indeed by searching it in the whole directory you will probably not find it like that. It is used currently on  the Notebookbar and thus it might not be present in that form. Nevertheless here is a way to find out which command it's available in one mode and missing in the other (in this case available in the notbeokbar and missing in the classic mode):

1. Change the `loolwsd.xml` to use notebookbar mode:
```xml
    <user_interface>
      <mode type="string" desc="Controls the user interface style (classic|notebookbar)" default="classic">notebookbar</mode>
    </user_interface>
```
2. `make run`
3. in your web browser, open dev tools (f12) and go to the console
4. now navigate to the notebookbar respective tab (datat) and click recalculate 
5. take a note of the uno.command that is appearing in the logs : `xxxxxxxxxx OUTGOING: uno .uno:Calculate `

now we know the command to add it to the menu we will need to adjust two files:
* check that is present here and if not add it (provided that we know for sure it work on online) `loleaflet/src/unocommands.js`:
```js
Calculate:{spreadsheet:{menu:_('~Recalculate'),},},
```
* loleaflet/src/control/Control.Menubar.js 
```js
@@ -538,6 +538,7 @@ L.Control.Menubar = L.Control.extend({
                                {uno: '.uno:DataSort'},
                                {uno: '.uno:SortAscending'},
                                {uno: '.uno:SortDescending'},
+                               {uno: '.uno:Calculate'},
```

**Comment by eszkadev** [comment]
> I searched but can't find .uno:Calculate at CollaboraOnline/online repo

Not all commands are visible in this repo because eg. Notebookbar content is sent from the LibreOffice/core repo by the server in runtime

**Comment by pedropintosilva** [comment]
thanks @ayhanyalcinsoy ! I take it that the problem you were facing it was solved with the changing branches and I hope the provided guidance help to clarify this and possible other issues that you might want to tackle down : )
