### ISSUE TITLE
Ruler: Gap of Few Pixels Between Menu/Ruler

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7836]
### Describe the Bug

Above the ruler, you can see a few pixels of text from the underlying document:

![Collabora 23 05 6 2 - Ruler Few Pixel Gap](https://github.com/CollaboraOnline/online/assets/5774324/cf68ffaa-6e1b-42f2-9706-f38c01e93460)

### Steps to Reproduce

In Writer:

1. **View > Ruler**
   - Make sure ruler is ON.
2. Add some text to document.
   - I made mine a heading so it was BIG + BOLD = easy-to-see.
4. Scroll down so text you wrote goes "behind" the ruler.

BUG: You can see text.

### Expected Behavior

No gap.

### Actual Behavior

Gap of a few pixels. Can look through "like a window". (It was distracting as I was scrolling down document with Ruler open.)

### Desktop

 - **Collabora version:** 23.05.6.2
 - **OS and version:** Windows 10
 - **Browser and version:** Chrome 120.0.6099.71 (Official Build) (64-bit)

I caught this during COOL Weekly Meeting:

> COOLWSD version: 23.05.6.2 (git hash: c0527a2c (E))
> LOKit version: Collabora Office 23.05.6.3 (git hash: 9a94664)
> Served by: openSUSE Leap 15.5
> Server ID: 685e4733

but also reproduced on my local install:

> COOLWSD version: 23.05.6.2 (git hash: 4ea31bfe)
> LOKit version: Collabora Office 23.05.6.3 (git hash: 9a94664)
> Served by: Linux Mint 21.1
> Server ID: 02d1ad25

**Comment by Darshan-upadhyay1110** [comment]
Looks good in latest version.
![image](https://github.com/user-attachments/assets/a513e3e5-026a-424d-9599-568b8fb91b4a)

COOLWSD version: 24.04.5.2 (git hash: be940ae0 (E))
LOKit version: Collabora Office 24.04.5.2 (git hash: 3dcf0f9)
Served by: openSUSE Leap 15.5
Server ID: d1c5cea0
