### ISSUE TITLE
iOS App no writing

### ISSUE THREAD

**Issue by Seandebasti** [CollaboraOnline/online#7844]
### Describe the Bug
I started the official Collabora app on my iPad and I cannot write/change inside of a blank document like the cells in spreadsheet or in a text document. But I was able to change names of the sheet name but nothing more.
I'd was able to navigate. Maybe there is a issue with the keyboard from the iPad?

### Steps to Reproduce
1. Install Collabora office on iPad
2. Go to € blank document /spreadsheet
3. Click on a cell (hold long that the keyboard will open)
4. Write numbers or letters
5. See error (nothing will write)
The same with normal text document
Try after reinstalling the app with a blank document. No positive change

### Expected Behavior
Text will appear 

### Actual Behavior
Nothing through typing on the keyboard

### Screenshots
Screenshot doesn't help

### Smartphone
 - **Device:** iPad Air 2
 - **OS:** iOS 15.8

### Additional Context
Nothing after reinstalling

**Comment by 432894589023818079437890** [comment]
I have a simular issue where I can not type in documents using collabora office 23.05.5. I am on an iPad 9th generation running iPadOS 15.6. I did not have trouble typing in collabora office until I installed 23.05.4. Future version of collabora office have this issue. I have attached a video of the issue.

https://github.com/CollaboraOnline/online/assets/146480618/55e0ca4c-659e-4bc4-aec3-ed4dd7f9f90e

**Comment by rpear** [comment]
Mine works okay on an iPad gen 9. A couple of differences are:
1. My iPad is running iPadOS 17.2 the latest version.
2. to get the keyboard, I double click, not long press.
@432894589023818079437890 @Seandebasti can you upgrade to v17 and try again?

**Comment by thebearon** [comment]
@Seandebasti @432894589023818079437890 Please try with latest CODE, 23.05.7.

**Comment by 432894589023818079437890** [comment]
The issue has been resolved on my end after updating to Collabora Office 23.05.7 for iPad. I am now able to edit in documents.

**Comment by thebearon** [comment]
Excellent, let me close this then. Thanks for verifying, @432894589023818079437890!
