### ISSUE TITLE
Support for Citavi

### ISSUE THREAD

**Issue by smelt1024** [CollaboraOnline/online#7868]
### Is your feature request related to a problem?

I've been trying to use Citavi alongside Collabora but since there is no direct support in any online editors, using Citavi with anything is a very difficult.

### Describe the solution you'd like

I should be able to access citations within Citavi inside Collabora Online.

### Describe alternatives you've considered

Switching to other reference software.

### Additional context

I've look at the API the desktop app uses, and did some poking around. The API itself is stateful and can generally be split into two parts.

A realtime API (delivers some client info and other stuff), and a stateful API that has the rest of the more important information (such as projects, current users, etc.).

To access the API one needs to get the Oauth 2.0 bearer token (implicit flow/grant, so a redirect URI must be set) from the following url `https://citaviweb.citavi.com/identity/connect/authorize/`. 

Most of the parameters are standard here (with `nonce` and `guid` working with a randomly generated v4 UUID), and the redirect URI set to whatever the registered app wants to use (and is set by xdg-open). The bearer token needed to make authentecated requests will be in the fragment.

With just the bearer token some of the endpoints can be queried (the token is appended to the request header as normal):

- https://euw.citaviweb.citavi.com/api/ValidateAccessToken (gets expiry time) `GET`
- https://euw.citaviweb.citavi.com/identity/connect/userinfo `GET`
- https://euw.citaviweb.citavi.com/api/DesktopCloudUserLookups (user settings, + URI for project table) `GET`
- https://euw.citaviweb.citavi.com/api/GetLicensesWithExpiryDate `GET`
- https://euw.citaviweb.citavi.com/api/GetProjectRoles (projects the user is part of + permissions) `GET`

Most of these have self explanatory names, so I will not go into details... But the JSON response from some endpoints tend to have information you need to query other endpoints.

But since some of the other stuff depends on the state of the client, it would need more work to sync and create a nice API to access all the information.

For example, 

- /api/DesktopCloudUserLookups returns a JSON with a "BlocksSave" boolean  `GET`
- /api/ProjectAccessTokens `GET`
- /api/GetProjectMinClientVersion (implying possible breaking api changes) `GET`
- /api/GetProjectInfo (some variables indicating save locked status and the current changeset version, implying the client will need to keep track of the latest changeset) `GET`

and various other endpoints.

It would be really awesome if Citavi would step up and create an API so that I (and everyone else) can use it with software thats fits my needs and accessibility requirements. If not I was wondering if there is a community effort to create one.

**Comment by sebastiaanveld** [comment]
Any integration is welcome, but this looks like one of those solutions/companies ([bough last year](https://en.wikipedia.org/wiki/Citavi) bij an investment company running multiple software solutions) dedicated to supporting Windows an MS Office so working with them may be an uphill fight. There's no reference to LibreOffice on their site at all; according to the web archive there seemed to have been plans tor release a LO plugin back when Citavi 6 was released, but I guess that newer happened.

From what I read it could be that Word documents created in MS Office with Citavi links in it, which are then edited by LibreOffice could break those links. If that happens it may be usefull to open a bug in [Bugzilla](https://bugs.documentfoundation.org/) so such content could be left alone with a fix. This may be a first step in supporting Citavi in LO/Online.

**Comment by timur-g** [comment]
Not sure we can add more to what was written. You may submit ticket at Bugzilla. 
Seems that interest for Citavi is not at the level to be considered to Collabora enhancements.
