### ISSUE TITLE
File Title in the Nextcloud Integration Header

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#788]
I don't know why there is this Filename editor widget next to Last Modification. I didn't understood that it's such a promise feature that is should be available as separate widget. 

I would move it into the Menubar -> File -> Rename File

![2020-11-26 14_54_56-Nextcloud](https://user-images.githubusercontent.com/8517736/100359514-f217b680-2ff7-11eb-8fd0-0f44570dea52.png)

**Comment by thebearon** [comment]
The primary function of the file name field is to show the file name in a prominent place, as it is often hard to find, eg. in the tab header in the browser, when you have lots of tabs open. The rename functionality only takes up that little pencil icon in addition. @pedropintosilva, what are your thoughts?

**Comment by Andreas-Kainz** [comment]
Ah I see gdocs show the filename which is nice to know when you are within a document, true.

![Screenshot_20201127_090945](https://user-images.githubusercontent.com/8517736/100425905-55552780-3090-11eb-949c-f8b104fa8ee7.png)

But in google docs it look "better" or at least it look more useful.

**Comment by thebearon** [comment]
It also takes up a lot more vertical space.

**Comment by Andreas-Kainz** [comment]
That's true my question is would it be enough benefit for the vertical space?

Therefore you have on the right the ^ arrow to hide the Filename.

**Comment by Andreas-Kainz** [comment]
I don't know why and when but this look great and will work very nicely.
![2021-01-14 12_25_03-Einstellungen](https://user-images.githubusercontent.com/8517736/104585201-feb5a400-5663-11eb-809f-d47d3520e8d8.png)

on try.nextcloud.org it has the old layout.
![2021-01-14 10_06_46-presentation-transitions-animations odp - Dateien - Nextcloud](https://user-images.githubusercontent.com/8517736/104585204-0117fe00-5664-11eb-85ec-fc9af07a4813.png)

**Comment by Andreas-Kainz** [comment]
> ![2021-01-14 12_25_03-Einstellungen](https://user-images.githubusercontent.com/8517736/104585201-feb5a400-5663-11eb-809f-d47d3520e8d8.png)

Ah this layout was visible when you open the document via web link so when you go to your cloud the header didn't show the filename but when you send the link and open the file you see the header.

I would prefer to see the header always for example center align and if you have the correct rights you can see different commands on the left and right. 

At Markdown, Image and Audio files there is at the top center the file title.

**Comment by Andreas-Kainz** [comment]
@mmeeks do you know someone from NC how can help here?

**Comment by Andreas-Kainz** [comment]
Now:
![2021-01-15 09_10_49-XML_Notebookbar_Proposal odt - Files - Nextcloud](https://user-images.githubusercontent.com/8517736/104698668-029fff80-5712-11eb-89b6-38b83ed45b23.png)

Proposal:
![2021-01-15 09_10_49-XML_Notebookbar_Proposal odt - Files - Nextcloud_2](https://user-images.githubusercontent.com/8517736/104698685-09c70d80-5712-11eb-903e-11eeea752fd0.png)

**Comment by mmeeks** [comment]
I read the ticket, and I'm unclear what the ask is. If we have a clear request for Nextcloud we can include Julius - but it would be really good to have some very clear spec. for what is proposed, and Pedro can make an intro to their design team.

**Comment by Andreas-Kainz** [comment]
**Now:** 
The filename is within the area of the menubar (in NB where the tabs are) If the filename is to long, it was cutted. You can rename an file easy which would be possible with Menubar -> Files -> Save as to.
![NoTitle_in_the_Header](https://user-images.githubusercontent.com/8517736/104771356-740f9a80-5772-11eb-9e6c-89a199b49a4f.png)

**Proposal:**
Filename is in the Nextcloud Header. There it's center align like the NC Markdown editor has the file title or the NC image and video viewer has. Have the Filename in the NC Header will improve the overall layout cause there is a large/height text and so there is no need of the filename widget in the menubar line or at NB in the tab area. 
![Title_in_the_Header](https://user-images.githubusercontent.com/8517736/104771976-eed8b580-5772-11eb-8eba-41bc5bbf9104.png)
-> No different elements within one line (menubar + filename), better NC integration and better overall layout.

**Comment by Ezinnem** [comment]
@pedropintosilva, @eszkadev

**Comment by pedropintosilva** [comment]
I think this is already happening, right? 
![image](https://user-images.githubusercontent.com/65948705/154065043-51190b4e-5b31-45e0-8d2d-207a5765fdb5.png)

**Comment by pedropintosilva** [comment]
and with integrator theme xml option turned off:

![image](https://user-images.githubusercontent.com/65948705/154065324-f20a209e-e5ea-4f55-aa4d-031b7fa98f92.png)

**Comment by Andreas-Kainz** [comment]
No we are talking about add save-modified to notebookbar layout where it's not available (now).
