### ISSUE TITLE
Dark mode shows white page on read onlymode

### ISSUE THREAD

**Issue by juliushaertl** [CollaboraOnline/online#7888]
### Describe the Bug
Open a document without edit permissions in Nextcloud shows a broken dark mode where the page itself is still white

Also switching between dark/light mode or scrolling trying to rerender tiles does not change anything. 

Note I had another user in light mode joined the document.

### Steps to Reproduce
1. Open a file with read only permissions (Nextcloud indicates this to online with the UserCanWrite: false in the checkFileInfo repsponse
2. Switch to dark mode or have dark mode set from the integrator

### Expected Behavior
The page is also dark

### Actual Behavior
The page is white

### Screenshots
<img width="2560" alt="Screenshot 2023-12-22 at 09 44 03" src="https://github.com/CollaboraOnline/online/assets/3404133/2d910a9b-c685-41d7-84a3-a2b9222e3666">

### Additional Context
COOLWSD version: 23.05.6.3 (git hash: 3c909e4 (E))
LOKit version: Collabora Office 23.05.6.3 (git hash: f6f27ac)
Served by: Debian GNU/Linux 12 (bookworm)
Server ID: 4ab3d5e8

**Comment by timur-g** [comment]
I saw ODT differently, was always dark for me. But there is a bug here anyway, so I will remove Unconfirmed. 
ODS has a different issue, document background changes light to dark, but font does not.

**Comment by Darshan-upadhyay1110** [comment]
@juliushaertl thanks for reporting. I have added a fix for read-only mode. 

Thank you :)
