### ISSUE TITLE
Spell check window blows up text size of the text being evaluated

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#7890]
### Describe the Bug
Spell check window blows up text size of the text being evaluated making it near uable to follow and adding a large scrollbar in that windows. This seems to happen only the first time when spelling is selected after a document is openend. When the spelling window is then closed and reopend by again click on Spelling to restart te process the text size is normal as expected.  

### Steps to Reproduce
1. Open a document
2. Click on 'Review'
3. Click 'Spelling'
4. Spelling Window pops up, the text size is blown up (see screenshot)

### Expected Behavior
The text size of the text evaluated is expected to be in the same size as the font used in like the suggestiuons section.

### Actual Behavior
The text size is blown up in the section showing the text/words being evaluated

### Screenshots

![image](https://github.com/CollaboraOnline/online/assets/37268999/36a192a2-f89f-45f7-9575-8a6d65610947)

### Desktop
(Please complete the following information)
 - Collabora version:
  COOLWSD version: 23.05.6.3 (git hash: 3c909e4 (E))
LOKit version: Collabora Office 23.05.6.3 (git hash: f6f27ac)
Served by: Debian GNU/Linux 12 (bookworm)
Server ID: 831c21ee
- Nextcloud 27.1.5
- OS and version: Windows 11 Ent x64, Dutch
- Browser and version: Firefox 121.0 (x64), MS Edge 120.0.2210.91 (normal and privacy mode)

**Comment by timur-g** [comment]
@sebastiaanveld thanks for spotting this one. I failed the first bisect, as it is not always seen, to be sure one needs to click in.

But secont time more luck, here it the culprit, it went into release 23.05.6:

commit aa6fdeaa558267ac60e03acada7e576dbf4e9b70
Author: Gülşah Köse <gulsah.kose@collabora.com>
Date:   Wed Nov 29 16:47:49 2023 +0300
    Fix the thickness dialog is shown cut

@GulsahKose please see.
