### ISSUE TITLE
Spell correction annoyingly turned on for read-only users

### ISSUE THREAD

**Issue by RadiologieSLK** [CollaboraOnline/online#7935]
### Describe the Bug
Hello,

we have an .xlsx spreadsheet on our nextcloud to be shown permanently on an always-on display as a daily overview. For this the sheet is shared with a user which has only read-rights. He cannot change the spell correction option, so by default all words (we use only abreviations) are underlined with red. Sometimes we have to restart the computer/browser meaning, even if I disable spell correction by login in with the admin-user (write-rights) and disable the spell correction, it will return once we restart the computer/browser.

Is there a way to disable spell correction permanently? I tried to deactivate it and saved the file, this is not enough.

Thank you!

See here:
https://forum.collaboraonline.com/t/disable-spell-correction-permanently/2275

### Expected Behavior
We would like to have the spell correction turned off for specific users (or all) by default. Having a button for read-only users to switch off the correction would be a start, but better would be a completely disabled spell check.

Thank you

**Comment by c3systems** [comment]
Just to chime in on this one - I think everyone out there would appreciate a default behavior of spellcheck being off for any document opened in Read Only mode.  If you can't act on a spelling mistake, there's no reason to have it red-squigglied.  

Especially in documents with tons of technical terms, there's no hope to keep that dictionary up to date.  The read-only users have no ability to change anything, so, there's really no need to squiggle the heck out of their viewing experience.

- humble $0.02.  thanks for all you and the team do - this is an amazing platform.
