### ISSUE TITLE
Android: Calc behavior is not good. Can not read values of cell.

### ISSUE THREAD

**Issue by Darshan-upadhyay1110** [CollaboraOnline/online#7936]
### Describe the Bug

Since I updated to V 23.05.5.2 running under Android 12 I've had a problem not experienced before and one that makes Collabora unusable.

 - I open my .ods files (each 102KB with 12 sheets, each sheet is A1 to N38) and wait (now a long time) for it to load so that I can scroll.
 -  I then scroll the sheet to the required viewing position, only to find that it moves away to some point nearer the top left of the sheet. 
  - I therefore can't read the cells not visible when A1 is displayed. 
  - Also, the tab bar at the bottom of the screen is not visible unless I use the 'more' tab and then return to the sheet.
 - I want to read docs rather than write. I can live without writing, and spreadsheets are the most important to me.

**Comment by Darshan-upadhyay1110** [comment]
CC: @timur-g @thebearon @Ezinnem  can anyone please confirm above issue. I have got this feedback from user.

**Comment by rpear** [comment]
@Darshan-upadhyay1110, I had a go at repeating this, I created a simiar sized ods, no formula or comments, etc. it tests fine. I tested it using the Collabora Office app on a Chromebook, which I believe is the same Android app.
- Is there a lot of formula or comments in it?
- Ideally send a copy, but realise that privacy may need to be managed.
- Is it repeatable in a desktop version?
- Is it repeatable in an older version of the desktop version?
- I wonder if there is some corruption, coinciding with the upgrade, make a copy of it, save in other formats like xls and xlsx, then open these and see if the problem persists?
- What is the device?

**Comment by timur-g** [comment]
There are 2 issues here (which is not good, as each should have own ticket).
1. I tested with a large spreadsheet and could move without going back to top left. So best here would be to prepare sanitized file, screencast the issue and attach both.
2. The tab bar is not visible in Read-only mode after file open. And that is an issue for me. Tab bar is available only in Edit mode.
3. I am not sure if report refers to Read-only or Edit mode for tabs. If Edit, I see tab bar and can scrol by swipe.

So this all needs a clarification.

**Comment by siccovansas** [comment]
The scroll issue seems to be fixed since at least 24.04.6.2. See the latest comments in https://github.com/CollaboraOnline/online/issues/9291.

**Comment by Darshan-upadhyay1110** [comment]
> The scroll issue seems to be fixed since at least 24.04.6.2. See the latest comments in #9291.

Awesome, Thanks @siccovansas for pointing this we can close this now :)
