### ISSUE TITLE
List Bullets in Dark Mode Are Black-on-Black

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7938]
### Describe the Bug

Bullets for unordered lists are black-on-black:

![Collabora 23 05 6 4 - Writer - Dark Bullets in Lists](https://github.com/CollaboraOnline/online/assets/5774324/2a1b3b8d-75b8-4194-b5a7-3c239d47df8c)

I drew a RED SQUARE around level 1 + level 2 bullets.

### Steps to Reproduce

In Writer:

1. **View > Dark Mode** ON.
2. Add a few unordered list items.

### Expected Behavior

List bullets should be light-on-black.

### Actual Behavior

List bullets are black-on-black.

### Desktop

 - **Collabora version:** 23.05.6.4
 - **OS and version:** Windows 10
 - **Browser and version:** Chrome 120.0.6099.199 (Official Build) (64-bit)

> COOLWSD version: 23.05.6.4 (git hash: b5d6ed1e (E))
> LOKit version: Collabora Office 23.05.6.4 (git hash: e03b031)
> Served by: openSUSE Leap 15.5
> Server ID: 2dee4b92

### Additional Context

Happened during COOL Weekly 150, but this has been an issue for a looong time.

**Comment by timur-g** [comment]
Not a bug. You may try with a new document. That is the issue with that document,

**Comment by Tex2002ans** [comment]
> Not a bug. You may try with a new document. That is the issue with that document,

Heh, of course the time I feel lazy and didn't test on a separate install + document. :P

Now, time to download the ODT and see why...

**Comment by timur-g** [comment]
Because bullet is dark, not automatic color.
