### ISSUE TITLE
File > "Go Offline" Button Doesn't Have Icon

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7939]
### Describe the Bug

"Go Offline" button is missing an icon:

![Collabora 23 05 6 4 - Writer - File Go Offline Button - Missing Icon](https://github.com/CollaboraOnline/online/assets/5774324/77eacb32-19ff-4e35-b3c6-40065ca64906)

### Steps to Reproduce

In Writer:

1. Go to "File" tab.

See "Go Offline" button.

### Expected Behavior

Icon + text there.

### Actual Behavior

Only text.

### Desktop

- **Collabora version:** 23.05.6.4
- **OS and version:** Windows 10
- **Browser and version:** Chrome 120.0.6099.199 (Official Build) (64-bit)

> COOLWSD version: 23.05.6.4 (git hash: b5d6ed1e (E))
> LOKit version: Collabora Office 23.05.6.4 (git hash: e03b031)
> Served by: openSUSE Leap 15.5
> Server ID: 2dee4b92

### Additional Context

None.

**Comment by Doraemon012** [comment]
I would like to work on this issue, please assign this to me.

**Comment by Tex2002ans** [comment]
Sure @Doraemon012 . If you are interested in fixing any issue, then definitely start poking around at it. :)

**Comment by timar** [comment]
Fixed by bc9d8258bb9e7b76a6611f15f122fc02915ec7ab
