### ISSUE TITLE
"Insert Comment" Should Exist in Right-Click Menu

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7940]
### Is your feature request related to a problem?

In LibreOffice 7.6 Writer + Calc, you are able to:

- **Right-Click > Insert Comment**

very quickly/intuitively.

In Collabora Online that option isn't there, so you have to:

- Go to "Insert" tab
- Press "Comment" button.

### Describe the solution you'd like

An extra "Insert Comment" option when Right-Clicking something.

### Describe alternatives you've considered

None.

### Additional context

Noticed it missing during COOL Weekly 150 testing:

> COOLWSD version: 23.05.6.4 (git hash: b5d6ed1e (E))
> LOKit version: Collabora Office 23.05.6.4 (git hash: e03b031)
> Served by: openSUSE Leap 15.5
> Server ID: 2dee4b92

**Comment by timur-g** [comment]
Already in #6644.
