### ISSUE TITLE
Formula to Value

### ISSUE THREAD

**Issue by neilguertincollabora** [CollaboraOnline/online#7984]
### Is your feature request related to a problem?

In LibreOffice Calc, you can replace a formula with its value by
Data > Calculate > Formula to Value

This option does not exist in Collabora Online, or if it does, it's in a different place.

There is a workaround, but it's not obvious. The workaround is to copy the cells and then paste as plain text.

### Describe the solution you'd like

There should be a Formula to Value button under the Data tab in Collabora Online.

**Comment by timur-g** [comment]
I marked as Enancement. But for copy/paste of formula, Ctrl+V also pastes formula, while Cltr+Shift+V pastes value.
