### ISSUE TITLE
Clipboard: Implement permissions for pasting in Chrome-based browsers

### ISSUE THREAD

**Issue by vmiklos** [CollaboraOnline/online#8023]
### Is your feature request related to a problem?

Pressing ctrl-v pastes from the clipboard, but pressing the paste button, we just show a popup to press ctrl-v.

### Describe the solution you'd like

Chrome has some new clipboard API that allows asking for the clipboard permission, we should conditionally start using that. See <https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read>.

**Comment by venky-17** [comment]
hey can u pls assign me this issue??

**Comment by vmiklos** [comment]
> hey can u pls assign me this issue??

This issue is already assigned, please pick an other issue which is not yet assigned. Thanks.

**Comment by vmiklos** [comment]
https://github.com/CollaboraOnline/online/pull/8061 switches to the improved new markup, described above.

**Comment by vmiklos** [comment]
Next step is to actually use the new API in Chrome. To test the new functionality, have an `--enable-experimantal` build, and then the baseline gives you an annoying popup when you click the paste button on the toolbar, while the new code asks for this permission once, and otherwise it more or less "just works".

**Comment by vmiklos** [comment]
https://github.com/CollaboraOnline/online/pull/8091 removes the old markup.

**Comment by vmiklos** [comment]
#8106 adds tests, let's close this.
