### ISSUE TITLE
per_view.idle_timeout_secs values not working

### ISSUE THREAD

**Issue by Wurzelmann** [CollaboraOnline/online#8028]
### Describe the Bug
The parameter "per_view.idle_timeout_secs" ("The maximum number of seconds before dimming and stopping updates when the user is no longer active (even if the browser is in focus). Defaults to 15 minutes.") set in coolwsd.xml does not do anything.

### Steps to Reproduce
1. open /etc/coolwsd/coolwsd.xml (Debian 12.4)
2. change value for **per_view.idle_timeout_secs**
3. restart coolwsd service
4. open document via coolwsd, wait for set time to pass

### Expected Behavior
The document should be dimmed and a notification should warn the user about their inactivity

### Actual Behavior
No matter how long one waits, the expected behaviour does not set in.

### Screenshots
No screenshot, because nothing is happening.

### Desktop
(Please complete the following information)
 - **Collabora version:** 23.05.7
 - **OS and version:** Debian 12.4
 - **Browser and version:** Firefox 115.6.0esr, Chromium Version 120.0.6099.216

### Additional Context
After looking through js files on our collabora server, I found a function with a 60 second timeout in **/usr/share/coolwsd/browser/dist/bundle.js** (Debian 12.4.), line 13359:

`this._inactivityTimer);this._inactivityTimer=setTimeout(function(){_this._dimIfInactive()},1*60*1e3)`

this is a value that does not seem related, but is not changeable via the config file for coolwsd, yet this is hard coded here and overrides any setting of per_view.idle_timeout_secs in the /etc/coolwsd/coolwsd.xml config file.

**Comment by eszkadev** [comment]
It should be fixed now by:
- https://github.com/CollaboraOnline/online/pull/8012

**Comment by Wurzelmann** [comment]
Thanks for the quick reply and solution! Any ETA when it will be available via the Debian repo?
