### ISSUE TITLE
Replace all menubartoolitems with customtoolitems

### ISSUE THREAD

**Issue by eszkadev** [CollaboraOnline/online#8029]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @eszkadev

### Detailed description and rationale
There were in the past initial approach to share code between menubar and notebookbar by using `(big)menubartoolitem` element in the notebookbar JSON. Now we have better widget for that: `(big)customtoolitem` that will not use Menubar code at all so reduces external dependencies for us (to smartmenus library).

### Code pointers
- use `git grep menubartoolitem` command to identify existing items 
- we want to move implementation of command/action from menubar (https://github.com/CollaboraOnline/online/blob/master/browser/src/control/Control.Menubar.js#L1841) to `dispatch` function https://github.com/CollaboraOnline/online/blob/master/browser/src/control/Toolbar.js#L945
- `customtoolitem` runs `command` using `map.dispatch(command)` function where we need to put command implementation
- adjust Menubar code to also use `map.dispatch(command)` for item you moved
- JSON with notebookbar description is in `https://github.com/CollaboraOnline/online/blob/master/browser/src/control/Control.NotebookbarWriter.js` for Writer and similar files for other apps

**Comment by adighiero1** [comment]
hello could i be assigned to work on this?

**Comment by eszkadev** [comment]
hi, @adighiero1 sure

**Comment by adighiero1** [comment]
Hi @eszkadev. I was sick so I haven't been able to do it. can you tell me where the code is on your codebase that needs changing? I have the codebase on my computer right now and I'm getting familiar with the structure.

**Comment by adighiero1** [comment]
Hi @eszkadev. I've been sick. I should have an update by monday.
