### ISSUE TITLE
Validity List value doesn't detect new lines but "\n" instead

### ISSUE THREAD

**Issue by AiroPi** [CollaboraOnline/online#8036]
### Describe the Bug
When we set :
"""
a
b
c
"""
to validity List, it only get the "a" and ignore the rest.
We can provide the string "a\nb\nc" instead and it works.

### Steps to Reproduce
1. Select a cell / range
2. Go to "Data -> Validity"
3. Allow "List"
4. Set "entries" to :
"""
a
b
c
"""
5. Only "a" is set.

### Expected Behavior
The three values should be available.

### Actual Behavior
Only the first value is available.

### Screenshots
Doesn't work:
<img width="440" alt="image" src="https://github.com/CollaboraOnline/online/assets/47398145/7d529b4d-dd3e-4f0e-800a-062f76006470">
Works:
<img width="444" alt="image" src="https://github.com/CollaboraOnline/online/assets/47398145/f97cd0f8-0cee-44b2-9c22-3ee6298bcd82">

### Desktop
(Please complete the following information)
 - **Collabora version:** 3.05.6.4
 - **OS and version:** MacOS 14.2.1 (23C71)
 - **Browser and version:** Arc Browser 1.25.1 (45028), Chromium Engine Version 120.0.6099.216

**Comment by mikekaganski** [comment]
Fixed on Jan 9 by https://github.com/CollaboraOnline/online/pull/7974.
