### ISSUE TITLE
Image properties "Rotation Angle" popup sticks on the screen after closing the Image properties menu

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#8045]
### Describe the Bug
Image properties Roration ange popup sticks on the screen after closing the Image properties menu. 
Performing this action multiple times result in also multiple "Rotation angle" popups show on the screen and stay there.

### Steps to Reproduce
1. Go to Nextcloud, open a document for editing
2. Insert an Image
3. Select Image properties
4. Select the Rotation tab
5. Change the Rotation Angle bij dragging on the rotation wheel, the popup "Rotation angle" pops up
6. Close the properties dialog
7. The Rotation angle" popup still shows on the screen

### Expected Behavior
When using the "Rotation angle" wheel the popup should show and fade when the wheel is released.

### Actual Behavior
Change the Rotation Angle bij dragging on the rotation wheel, the popup "Rotation angle" pops up and stays on the screen. When performing this action multiple times also multiple "Rotation angle" popups show on the screen and stay there.

### Screenshots

![image](https://github.com/CollaboraOnline/online/assets/37268999/19d8144b-86f4-4026-82b5-dc4e93fbe479)

![image](https://github.com/CollaboraOnline/online/assets/37268999/6b850971-71de-4dee-b284-15cdb67a6214)

### Desktop
(Please complete the following information)
 - **Collabora version:** COOLWSD version: 23.05.7.2 (git hash: f76e08a (E))
LOKit version: Collabora Office 23.05.7.2 (git hash: 6d9d5d1)
Served by: Debian GNU/Linux 12 (bookworm)
Server ID: 298b6d4d
 
 - **OS and version:** Windows 11, Dutch, latest patches
 - **Browser and version:** Firefox 121.0.1 x64

**Comment by timur-g** [comment]
Thanks. Seems about popup in 23.05, it was not there in 22.05, so I marked regression. Minor, disappears when saved.
