### ISSUE TITLE
Remove obsolete locking

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#805]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @mmeeks 

### Detailed description and rationale
In recent times we've significantly simplified our threading model in COOL, but there are old / obsolete locking pieces left lying around.

### Code pointers
The kit/Kit.cpp has a _mutex field-  that needs to be removed. While we're there the getMutex() method should go, also from the common/Session base-class

Hopefully an easy one =)

**Comment by gozeloglu** [comment]
Hi @mmeeks . I want to work on this issue. But something is not clear to me. As I understood, I need to remove `_mutex` field in https://github.com/CollaboraOnline/online/blob/470497abd68fec833631554d9563da7c9cb12251/kit/Kit.cpp#L1662 . But what do you mean by 

> getMutex() method should go

https://github.com/CollaboraOnline/online/blob/470497abd68fec833631554d9563da7c9cb12251/kit/Kit.cpp#L991 line should be removed? Also I understood that https://github.com/CollaboraOnline/online/blob/470497abd68fec833631554d9563da7c9cb12251/common/Session.hpp#L265 line and `#include <mutex>` line in `common/Session.hpp` should be removed as well.  If I am wrong, please correct me. 

Thanks in advance.

**Comment by mmeeks** [comment]
good to remove the includes; and yes you got the getMutex() to kill - but you also need to cleanup the base class there
$ git grep getMutex # will help you out =)
Thanks !
