### ISSUE TITLE
Table gray rectangular elements for navigation

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#807]
![Screenshot_20201128_000537](https://user-images.githubusercontent.com/8517736/100488290-a2c3aa00-310d-11eb-8fa7-1e69ad4de5b9.png)

What's the reason for this not very sexy gray rectangular elements around an table? Why are they needed?

**Comment by thebearon** [comment]
They're for selecting rows/columns, but as I can see it doesn't work in 6.4, only in the previous 4.2 version, which is a regression.

**Comment by pedropintosilva** [comment]
> They're for selecting rows/columns, but as I can see it doesn't work in 6.4, only in the previous 4.2 version, which is a regression.

This has been fixed in  https://github.com/CollaboraOnline/online/pull/1303

_regarding style: closing this issue (we already have https://github.com/CollaboraOnline/online/issues/1297)_
