### ISSUE TITLE
iOS app: can't understand the version without opening a file

### ISSUE THREAD

**Issue by baffclan** [CollaboraOnline/online#808]
**Describe the bug**
Collabora Office has not "about Collabora Office" menu item in the first window.
To know the version number, you have to open a file.

**To Reproduce**
1. Tap a Collabora Office icon
2. Collabora Office opens
3. Recent files list are displayed

**Expected behavior**
There is a "About Collabora Office" menu item,
and you can see the version.

**Actual behavior**
No "about Collabora Office" menu item.
Therefore, I don't know the version.

**Smartphone (please complete the following information)**
 - Device: iPhoneXS
 - OS: iOS14.2

**Additional context**
Collabora Office:
 LOOLWSD
   6.4.1 (git hash: 465deeb8)

 LOKit
  Clooabora Office 6.4-14 (git hash: 4d0464d)

**Comment by baffclan** [comment]
This issue is a migration from TDF#137405.
https://bugs.documentfoundation.org/show_bug.cgi?id=137405

**Comment by tml1024** [comment]
The document broswer is a system control, and it is not really possible to add own buttons (even less menus) to it.

**Comment by baffclan** [comment]
> The document broswer is a system control, and it is not really possible to add own buttons (even less menus) to it.

I thought the iOS version, like the Android version, had its own file browser.

**Comment by tml1024** [comment]
Nope, it is a [UIDocumentBrowserViewController](https://developer.apple.com/documentation/uikit/uidocumentbrowserviewcontroller?language=objc)

**Comment by tml1024** [comment]
But yeah, using https://developer.apple.com/documentation/uikit/uidocumentbrowserviewcontroller/2874180-additionaltrailingnavigationbarb?language=objc it would apparently be possible to add more buttons, fort instance to show the version. I don't really think that is very high priority, though.
