### ISSUE TITLE
Calc Formular bar alignment

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#809]
local build 
![Screenshot_20201128_103532](https://user-images.githubusercontent.com/8517736/100498962-34f79c80-3166-11eb-849e-2c14e3c8298d.png)

staging collabora server
![Screenshot_20201128_103751](https://user-images.githubusercontent.com/8517736/100498976-42148b80-3166-11eb-9f6b-bb7032ec937c.png)

**Comment by thebearon** [comment]
Indeed, the formula bar part is tunneled, while the Name Box and the Function Wizard button are native elements.

**Comment by Andreas-Kainz** [comment]
Ah ok, than the name Box and Function Wizard need to get an update for vertical alignment. Thanks.
