### ISSUE TITLE
perf: sending cellviewcursor with N^2d

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#8223]
It seems we send the cellviewcursor message multiple times to each view - based on the number of users. Interestingly we also do zoom related adjustments, so the offsets are wrong there too as well as being slow:

A big log is: https://github.com/CollaboraOnline/online/files/14208723/calc-trace-2024-02-08.txt.gz

A picture is:
![image](https://github.com/CollaboraOnline/online/assets/122848/50e7922c-ca10-416e-834e-19f8e2cd8aae)

**Comment by caolanm** [comment]
The y value is different in each "cellviewcursor" line. Pulling those lines from the log gives full entries of:

`
1707392576253 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 20246, 12629, 299, 0, 64" } 
1707392576750 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 19946, 12629, 299, 0, 63" }
1707392576778 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 19646, 12629, 299, 0, 62" } 
1707392576808 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 19333, 12629, 312, 0, 61" }
1707392576844 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 19033, 12629, 299, 0, 60" } 
1707392576870 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 18733, 12629, 299, 0, 59" }
1707392576905 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 18433, 12629, 299, 0, 58" } 
1707392576938 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 18133, 12629, 299, 0, 57" }
1707392576974 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 17833, 12629, 299, 0, 56" } 
1707392576998 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 17533, 12629, 299, 0, 55" }
1707392577020 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 17220, 12629, 312, 0, 54" } 
1707392577049 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 16920, 12629, 299, 0, 53" }
1707392577081 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 16620, 12629, 299, 0, 52" } 
1707392577110 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 16307, 12629, 312, 0, 51" }
1707392577185 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 15994, 12629, 312, 0, 50" } 
1707392577185 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 15738, 12629, 255, 0, 49" }
1707392577210 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 15482, 12629, 255, 0, 48" } 
1707392577231 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 15226, 12629, 255, 0, 47" }
1707392577373 INCOMING: cellviewcursor: { "viewId": "10", "part": "0", "mode": "0", "rectangle": "0, 14458, 12629, 255, 0, 44" } 
1707392577374 INCOMING: viewlock: { "viewId": "3", "part": "7", "mode": "0", "rectangle": "EMPTY" }
`

so presumably this is from user of viewId 10 with their cursor initially in A66 and then holding/pressing down the up arrow until they reach A45.

We seem to include the cell address along with the rectangle. Maybe its worth just sending the cell addresses and let the browser side figure out the bounds itself.

**Comment by mmeeks** [comment]
Ah drat =) not a problem then - beyond more ideally merging these together in the server where we can; we should look at other issues in the trace I guess - like lots of jsdialog thrash =) Thanks !
