### ISSUE TITLE
perf: don't synchronize extension repositories

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#8231]
The latest week-long demo profile has:

![image](https://github.com/CollaboraOnline/online/assets/122848/1a6521c3-bbe1-4671-98cb-7a9e9e4889fe)

desktop::Desktop::SynchronizeExtensionRepositories chewing up more than 2% of CPU time - which seems completely excessive.

I guess we do this whenever we launch a kit, and it seems entirely pointless - or at least, we should be able to do this in the preload phase just once in desktop/source/lib/init.cxx - and save ourselves lots of memory, time etc.

Hopefully for not many lines of code ;-)

@caolanm any thoughts ? =)

**Comment by caolanm** [comment]
This got done with https://gerrit.libreoffice.org/c/core/+/165639 I believe
