### ISSUE TITLE
Multi-user text editing status bar confusion for the current page in Writer

### ISSUE THREAD

**Issue by vmiklos** [CollaboraOnline/online#8270]
### Describe the Bug
Multi-user editing can result in the cursor of user 1 to influence the status bar of user 2, with this document:

[orig.odt](https://github.com/CollaboraOnline/online/files/14281882/orig.odt)

### Steps to Reproduce
1. Open the bugdoc.
2. User 1 goes to page 3.
4. User 2 goes to page 19.
5. User 2 deletes the "page 19" text on page 19.

### Expected Behavior
Status bar of user 2 says we're on page 19.

### Actual Behavior

![image](https://github.com/CollaboraOnline/online/assets/13838/1e2ff4ee-6be5-4c7a-80fc-a342a2306e21)

I.e. status bar for user 2 says we're on page 3, which is the cursor position of user 1.

### Additional Context

Tested with Chrome and Linux, but probably the problem is general.

**Comment by Tex2002ans** [comment]
I spotted this last week too during COOL Weekly 155. This was my exact version:

> COOLWSD version: 23.05.8.4snapshot (git hash: fee6198(E))
> LOKit version: Collabora Office 23.05.8.20240207 (git hash: 3797310)
> Served by: Ubuntu 22.04.3 LTS 4f7c80eb

and these were my notes. I had slightly different steps, but similar symptoms:

- - - -

### Page Numbers in "Status Bar" Strangely flipping when "View > Sidebar" Goes ON/OFF

0. Open ODT with many pages.
1. **View > Status Bar ON**
2. Click in page 1.
   - See Status bar shows "Page 1 of 9".
3. **View > Sidebar** ON.
4. Repeat Step 4 OFF/ON again multiple times.

In Steps 4/5, you'll see bug:

- Page might hop to "Page 4 of 9".
    - (or other random page numbers.)

(I don't know if this had to do with different people editing at once, so the selected page was jumping to where users were...)

**Comment by vmiklos** [comment]
https://cgit.freedesktop.org/libreoffice/core/commit/?h=distro/collabora/co-23.05&id=fb33ed13f4f83f92de7d5276271ab0f95458e90b fixes this.
