### ISSUE TITLE
Presentation Layout/Master Bug

### ISSUE THREAD

**Issue by derigs** [CollaboraOnline/online#8278]
### Describe the Bug
If you open an .odp file and click on the layout and master buttons in various orders everything overites. 
I will leave one example in "Steps to reproduce" but just click on the both buttons as you want you will get the error in various variants. 

### Steps to Reproduce
1. Go to layout tab
2. Click on layout 
3. It should turn blue and sidebar comes out
4. Click it again sidebar goes but button still blue
5. Click on master
6. Sidebar should pop out and button turns blue
7. Click on master again should still blue but sidebar hides
8. Click on layout again.
9. Sidebar should pop up but the one from master

### Expected Behavior
If i click on a button whos not active it should turn blue and show the sidebar. 
If i click on a button whos active it should turn off and hid ethe sidebar.

### Actual Behavior
Buttons don't activate/deactivate correctly and may show correct, wrong or no sidebar.

### Desktop
(Please complete the following information)
 - **Collabora version: 23.05.8.4 96e80a8 (NC Office  8.2.4 and 8.3.1)
 - **OS and version: MacOS Sonoma 14.3.1 
 - **Browser and version: Firefox 122.0.1

**Comment by timur-g** [comment]
Reproduced:
click Layout - Slide Layout (or Sidebar button): may appear shortly  but not stay on - NOK
click again: sidebar appears, button is blue
click to turn off (or with Sidebar button): sidebar disappears, button is still blue - NOK

click Layout - Master Slides (or Master Slides button) when Slide Layout is not blue:  sidebar appears, button is not blue - NOK

click  Slide Layout then Master Slides : both buttons are blue and on- NOK
click Master Slides again: sidebar disappears, but botrh button are blue - NOK

**Comment by meven** [comment]
https://gerrit.libreoffice.org/c/core/+/165092

Fixed in 24.04 with https://cgit.freedesktop.org/libreoffice/core/commit/?h=distro/collabora/co-24.04&id=ccf6c869c3f61f410f608af007acb2f655f40985
