### ISSUE TITLE
"View > Sidebar" Opening/Closing Very Sluggish, Then Jumps Back to "Home" tab

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#8283]
### Describe the Bug

In Calc, pressing "View > Sidebar" took multiple seconds, then jumped me back to the "Home" tab.

- - -

**Note:** Probably requires lots of people (with multiple languages/UIs?) editing at same time? We had 16+ people editing the same Calc file.

I could not reproduce locally OR in a document by myself.

- - -

### Steps to Reproduce

In Calc:

1. **View > Sidebar** ON.
2. **View > Sidebar** OFF.
3. Repeat Steps 1+2 multiple times.
   - I only had to click once or twice more before symptoms appeared.

### Actual Behavior

1. Sidebar opened very quickly on Steps 1+2...
   - ... but on try 3 or 4+, it took many seconds for button/sidebar to finally react and expand/collapse.
2. Random jump to "Home" tab.

### Expected Behavior

- Sidebar appears/disappears quickly, every time.
- Stay on the "View" tab.

### Desktop

- **Collabora version:** 23.05.9.1snapshot
- **OS and version:** Windows 11
- **Browser and version:** Version 121.0.6167.184 (Official Build) (64-bit)

> COOLWSD version: 23.05.9.1snapshot (git hash: 619c3e6(E))
> LOKit version: Collabora Office 23.05.9.20240214 (git hash: 959a80b)
> Served by: Ubuntu 22.04.3 LTS 066d1b6f

### Additional Context

Happened during COOL Weekly 156:

- @mmeeks could not reproduce while we were live-testing, but I was consistently getting it to happen.
   - (Maybe he only toggled ON/OFF once, while I was on "try 2 or 3"?)
- Someone else mentioned "going back to the Home tab" is some sort of "default state".
   - Maybe multiple sidebar opening/closings triggered something?
- I COULD NOT get it to happen on first round of ON/OFFs.
   - It only seemed to happen on later ON/OFF toggles.

**Comment by timur-g** [comment]
Let us close unless reproduced.
