### ISSUE TITLE
LEFT ARROW while typing text in a cell = jumps to next cell over

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#8285]
### Describe the Bug

While typing in a cell, pressing the LEFT ARROW leaps you out of the cell instead of moving you one character left.

### Steps to Reproduce

In Calc:

1. **Single Left-Click** on a cell.
   - I chose B2.
2. Begin typing:
   - `Example text is`
3. Press LEFT ARROW.

### Expected Behavior

Cursor stays in box, so you'd go from:

Step 1: `Example text is|`
Step 2: `Example text i|s`

### Actual Behavior

Goes from B2 to A2.

(Leaping you out of the formula/current box, jumping you to next cell over.)

### Desktop

- **Collabora version:** 23.05.9.1snapshot
- **OS and version:** Windows 11
- **Browser and version:** Chrome 121.0.6167.184 (Official Build) (64-bit)

Happened on the Share server:

> COOLWSD version: 23.05.9.1snapshot (git hash: 619c3e6(E))
> LOKit version: Collabora Office 23.05.9.20240214 (git hash: 959a80b)
> Served by: Ubuntu 22.04.3 LTS 066d1b6f

and even my local:

> COOLWSD version: 24.04.0.0 (git hash: 7387d9cc)
> LOKit version: Collabora Office 23.05.9.1 (git hash: 959a80b)
> Served by: Linux Mint 21.1
> Server ID: 793e8cdf

### Additional Context

**Note:** Oddly, **only seems to happen on typing into a fresh cell** for the first time.

- If editing a cell with text already in it, you can LEFT/RIGHT ARROW fine.

**Comment by Ezinnem** [comment]
Please can you test again?

Not reproducible in:
23.05.9.2snapshot git hash: [9831402](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/9831402'));)

**Comment by Tex2002ans** [comment]
Still happens to me in today's:

> COOLWSD version: 24.04.0.0 (git hash: ff61e2a5)
> LOKit version: Collabora Office 23.05.9.2 (git hash: 83de0e8)
> Served by: Linux Mint 21.3
> Server ID: 0faf96bf

**Comment by Ezinnem** [comment]
I can confirm this issue. I see it is the same behaviour as in Core build.

**Comment by thebearon** [comment]
Other spreadsheet apps behave the same way, it is not a bug.

**Comment by Tex2002ans** [comment]
> Other spreadsheet apps behave the same way, it is not a bug.

Yes, I see Excel behaves the same way too. Interesting...
