### ISSUE TITLE
Always Restarting with latest Docker Image

### ISSUE THREAD

**Issue by flyinghuman** [CollaboraOnline/online#831]
**Describe the bug**
The latest Docker container is always restarting after updating the collabora/code image.

**To Reproduce**
1. stop the current image
2. docker pull collabora/code
3. docker run ...common collabora syntax... collabora/code
4. docker ps displaying Restarting ...

**Expected behavior**
conatainer should be up and running

**Actual behavior**
Conatiner is always restarting with Image "sha256:e23d8e269c7df15b8dad7728a478d331c590015eec92088c34e8b0102816e3ac",

Logfile:
`sh: 1: /usr/bin/loolmount: Operation not permitted
wsd-00006-00006 2020-12-01 12:27:22.315817 [ loolwsd ] ERR  Failed to unmount [/opt/lool/child-roots/].| common/JailUtil.cpp:68
wsd-00006-00006 2020-12-01 12:27:22.316100 [ loolwsd ] DBG  Removing [/opt/lool/child-roots/] only.| common/FileUtil.cpp:207
wsd-00006-00006 2020-12-01 12:27:22.316888 [ loolwsd ] DBG  Failed to remove [/opt/lool/child-roots/] only: Access to file denied| common/FileUtil.cpp:241
Access to file denied: /opt/lool/child-roots/lool_test_mount
cp: cannot create regular file '/opt/lool/systemplate/etc/resolv.conf': Permission denied
cp: cannot create regular file '/opt/lool/systemplate/etc/hosts': Permission denied
mkdir: cannot create directory ‘/opt/ssl/’: Permission denied
start-collabora-online.sh: line 9: cd: /opt/ssl/: No such file or directory
mkdir: cannot create directory ‘certs’: Permission denied
Cannot write random bytes:
139846994596288:error:24070079:random number generator:RAND_write_file:Cannot open file:../crypto/rand/randfile.c:213:Filename=/opt/lool/.rnd
genrsa: Can't open "certs/ca/root.key.pem" for writing, No such file or directory
Can't open certs/ca/root.key.pem for reading, No such file or directory
140332441448896:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:72:fopen('certs/ca/root.key.pem','r')
140332441448896:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:79:
unable to load Private Key
mkdir: cannot create directory ‘certs’: Permission denied
mkdir: cannot create directory ‘certs’: Permission denied
mkdir: cannot create directory ‘certs’: Permission denied
genrsa: Can't open "certs/servers/localhost/privkey.pem" for writing, No such file or directory
Can't open certs/servers/localhost/privkey.pem for reading, No such file or directory
140385508626880:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:72:fopen('certs/servers/localhost/privkey.pem','r')
140385508626880:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:79:
unable to load Private Key
Can't open certs/tmp/localhost.csr.pem for reading, No such file or directory
140514127749568:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:72:fopen('certs/tmp/localhost.csr.pem','r')
140514127749568:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:79:
mv: cannot stat 'certs/servers/localhost/privkey.pem': No such file or directory
mv: cannot stat 'certs/servers/localhost/cert.pem': No such file or directory
mv: cannot stat 'certs/ca/root.crt.pem': No such file or directory
Can't remove /etc/loolwsd/loolwsd.xml: Permission denied, skipping file.
Can't remove /etc/loolwsd/loolwsd.xml: Permission denied, skipping file.
Can't remove /etc/loolwsd/loolwsd.xml: Permission denied, skipping file.
Can't remove /etc/loolwsd/loolwsd.xml: Permission denied, skipping file.
Can't remove /etc/loolwsd/loolwsd.xml: Permission denied, skipping file.
Setting up watches.
Watches established.
Run the script as root.
wsd-00007-00007 2020-12-01 12:28:24.367204 [ loolwsd ] INF  Initializing wsd. Local time: Tue 2020-12-01 12:28:24+0000. Log level is [8].| common/Log.cpp:325
wsd-00007-00007 2020-12-01 12:28:24.367452 [ loolwsd ] INF  Setting log-level to [trace] and delaying setting to configured [warning] until after WSD initialization.| wsd/LOOLWSD.cpp:1073
wsd-00007-00007 2020-12-01 12:28:24.367502 [ loolwsd ] INF  Initializing loolwsd server [].| wsd/LOOLWSD.cpp:1077
wsd-00007-00007 2020-12-01 12:28:24.367543 [ loolwsd ] INF  Anonymization of user-data is configurable.| wsd/LOOLWSD.cpp:1084
wsd-00007-00007 2020-12-01 12:28:24.367589 [ loolwsd ] WRN  NOTE: both logging.anonymize.usernames and logging.anonymize.filenames are deprecated and superseded by logging.anonymize.anonymize_user_data. Please remove username and filename entries from the config and use only anonymize_user_data.| wsd/LOOLWSD.cpp:1095
wsd-00007-00007 2020-12-01 12:28:24.367621 [ loolwsd ] WRN  Since logging.anonymize.anonymize_user_data is provided (false) in the config, it will be used.| wsd/LOOLWSD.cpp:1098
wsd-00007-00007 2020-12-01 12:28:24.367646 [ loolwsd ] INF  Anonymization of user-data is disabled.| wsd/LOOLWSD.cpp:1132
wsd-00007-00007 2020-12-01 12:28:24.368849 [ loolwsd ] WRN  SSL support: SSL is disabled.| wsd/LOOLWSD.cpp:1181
wsd-00007-00007 2020-12-01 12:28:24.369017 [ loolwsd ] INF  Creating childroot: /opt/lool/child-roots/| wsd/LOOLWSD.cpp:1226
wsd-00007-00007 2020-12-01 12:28:24.369111 [ loolwsd ] INF  Cleaning up childroot directory [/opt/lool/child-roots/].| common/JailUtil.cpp:144
wsd-00007-00007 2020-12-01 12:28:24.369452 [ loolwsd ] TRC  Directory [/opt/lool/child-roots/] is not a jail, recursing.| common/JailUtil.cpp:162
wsd-00007-00007 2020-12-01 12:28:24.369655 [ loolwsd ] DBG  Unmounting [/opt/lool/child-roots/].| common/JailUtil.cpp:63
wsd-00007-00007 2020-12-01 12:28:24.369814 [ loolwsd ] TRC  Executing loolmount command: /usr/bin/loolmount -u  /opt/lool/child-roots| common/JailUtil.cpp:35
sh: 1: /usr/bin/loolmount: Operation not permitted
wsd-00007-00007 2020-12-01 12:28:24.373955 [ loolwsd ] ERR  Failed to unmount [/opt/lool/child-roots/].| common/JailUtil.cpp:68
wsd-00007-00007 2020-12-01 12:28:24.374084 [ loolwsd ] DBG  Removing [/opt/lool/child-roots/] only.| common/FileUtil.cpp:207
wsd-00007-00007 2020-12-01 12:28:24.374807 [ loolwsd ] DBG  Failed to remove [/opt/lool/child-roots/] only: Access to file denied| common/FileUtil.cpp:241
Access to file denied: /opt/lool/child-roots/lool_test_mount`

Due a lot of access denied: permission problem inside the docker container? we reverting back to the older image - this image is working ("Image": "sha256:e861ac5a339583bf9cb59c0c650fc349889f28494cd1e8e3bf1bf674210c57c5",).

It is a bug or a local Problem?
We are running Ubuntu 18.04 with latest patches installed and Docker version 19.03.6, build 369ce74a3c; Apache Reverse Proxy with valid Certificate.

Thanks!

**Comment by alexandergolz** [comment]
Same here. Ubuntu 20.04, docker 19.03.13

**Comment by itmagix** [comment]
Same here on: CentOS Linux release 7.9.2009 (Core)

Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:03:45 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:02:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by daddydaycare** [comment]
Same here Ubuntu 20.04

**Comment by timar** [comment]
It was a bug, but I pushed a new docker image yesterday. Please pull again.

**Comment by aneesijaz** [comment]
can't build on ubuntu 18.04.
same issue.

**Comment by harishjadhav26** [comment]
@aneesijaz use "--privileged" option in docker run command
