### ISSUE TITLE
perf: reduce JS subarray usage

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#8316]
We have a firefox performance profile: https://share.firefox.dev/487OMj8 around scrolling in calc that majors on JS' subarray which is interesting; perhaps a more permanent picture here:

![image](https://github.com/CollaboraOnline/online/assets/122848/7470968c-870b-42b9-b465-2348c2d54ce3)

Skimming _applyDelta - it seems that there are a number of easy wins:

- [ ] our initial 'subarray' is not necessary for an offset of zero 
			var delta = allDeltas.subarray(offset);
- [ ] the second subarray is also not necessary - we could pass delta + len into _unpremultiply quite easily
		var pixelArray = this._unpremultiply(delta.subarray(0, len));

I suspect that for the initial keyframe - we have lots of pixel data in the array, which is what we'd see in the profile scrolling down; and no smaller deltas packed after it so ... we could at least move the var delta = alDeltas ... into the else .. // no keyframe case I think with little effort.

Hope there is a nice easy win there or two. Then again, not entirely clear what B,C,F,S,u are - quite possibly all that cost is actually inside the fzstd.decompress method.

Quite possibly we should be not just sucking tiles ahead / around the visible scroll-area, but de-compressing them too =)

Thanks =)

**Comment by mmeeks** [comment]
Thanks Caolan; lets see =)

**Comment by caolanm** [comment]
I expanded out B,C,F,S,u from fzstd https://share.firefox.dev/3I9ZElO which I'll attach as bitmap here for reference:

![profile-subarray-fzstd](https://github.com/CollaboraOnline/online/assets/833656/3bf9ba82-4855-4fc9-8f48-01e1a1d8d874)

**Comment by mmeeks** [comment]
Related firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1874699 - indeed subarray is much slower than expected on firefox.
