### ISSUE TITLE
 Cannot present large powerpoint files

### ISSUE THREAD

**Issue by sinhkien** [CollaboraOnline/online#8404]
### Describe the Bug

1. I have a 200MB powerpoint file. I open the file with CollaboraOnline normally, but when I select the slideshow, this action takes a long time and gives an error.

![2024-02-27_13-56](https://github.com/CollaboraOnline/online/assets/127186304/33e7f8d7-3d09-4092-bab5-d40d34af355a)

3. I check during the presentation that my server is not overloaded
4. My server is installed on a separate machine and integrated with nextcloud
5.  Is there any way to solve this problem?

Looking forward to receiving your help. Thank you !

**Comment by Ezinnem** [comment]
@sinhkien Please can you share the sample file with us?

**Comment by sinhkien** [comment]
OK. You can see my documents here
https://drive.thacoagri.com.vn/s/4eXnMLKPyPgGfqW

**Comment by timur-g** [comment]
Thanks for the sample. Confrmed. May be extreme case of #6616.

**Comment by sinhkien** [comment]
Does that mean that if there is a video, the presentation may not be possible?
Is there any way to improve this problem?

**Comment by timur-g** [comment]
Video playback should be possible. These one just do not work. 
Since all is OSS, one may fix it himself or herself, or subscribe with a developer company that makes it possible, it is obvious which one.

**Comment by timur-g** [comment]
Slideshow rework is being done in Online 24.04, now presentation starts fast regardless of it's size and, this ticket, those slides with video play fine.
Not sure when it will be released, hopefully soon after some testing and fixing other issues (transitions in slide 5 NOK).
