### ISSUE TITLE
Comments are broken when editing a document

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#8407]
This was initially reported by @jospoortvliet in https://github.com/nextcloud/richdocuments/issues/3470

-----

**Describe the bug**
Opened a document from a Deck card in Deck. Loads nicely. But after inserting a comment, things go kaboom. See this video:

https://github.com/nextcloud/richdocuments/assets/551757/e6e9be82-16ec-4b43-8274-7d7754dad710

Reloading the doc puts the comment in the right place, but adding another is 💥  again.

Fun fact: it works fine when opened directly, so it is somehow due to Deck.

**To Reproduce**
1. open a document
2. Select text
3. insert comment
4. See error. now try scrolling and cry.

**Expected behavior**
well, normal behavior - comments added, scrolling etc still working.

**Client details:**
 - Laptop with Mac OS 14.3.1
 - Latest Firefox 122.0.1

## Server details
cloud.nextcloud.com with Nextcloud server 28.0.2.5

**Version of the richdocuments app**
latest, I guess.

**Version of Collabora Online**
23.05.8.4 git hash: [96e80a8](https://github.com/CollaboraOnline/online/commits/96e80a8)

#### Browser log
JS log
```
There is a section with the same name. Use doesSectionExist for existancy checks. bundle.js:14346:46
Uncaught TypeError: this.sectionProperties.container is null
    NextJS 7
bundle.js:14924:2
Uncaught TypeError: annotation.sectionProperties.container is null
    NextJS 3
bundle.js:15195:10
Uncaught TypeError: this._el is null
    NextJS 5
bundle.js:34823:40
Uncaught TypeError: comment.sectionProperties.replyCountNode is undefined
    NextJS 7
bundle.js:15539:69
```

</details>

**Comment by pedropintosilva** [comment]
@juliushaertl 
> I don't see how that could be related to deck. @eszkadev Any idea based on the js errors?

@eszkadev 
> It might be some race on our side. Probably we try to duplicate comment: `There is a section with the same name. Use doesSectionExist for existancy checks`. We will investigate. Thank you for a detailed report.

**Comment by pedropintosilva** [comment]
cc: @Ezinnem

**Comment by lpranam** [comment]
probably this one should fix it if it was just related to the notebookbar: https://github.com/CollaboraOnline/online/pull/8401
