### ISSUE TITLE
Rename the default UI config setting name in coolwsd.xml

### ISSUE THREAD

**Issue by meven** [CollaboraOnline/online#8475]
### Describe the Bug
Too many users do not use the notebookbar by default, because they used COOL in their browser before the default setting changed and the setting got stuck in their browser's cookie.
By renaming the config setting we ensure all users will have to reload the default setting.

This must be done for 24.04.

**Comment by meven** [comment]
cc @mmeeks

**Comment by mmeeks** [comment]
Idea is simple - force the new default and not drag around the legacy coolwsd.xml default from some much older version.

**Comment by timar** [comment]
Didn't we do this a few months ago? https://github.com/CollaboraOnline/online/pull/7391

**Comment by mmeeks** [comment]
Hmm - yes; I guess - interesting; I wonder then how this still plagued us =)

**Comment by meven** [comment]
> Hmm - yes; I guess - interesting; I wonder then how this still plagued us =)

We noticed the issue lately with a partner, but we still don't know the version they use.
I will know soon.
