### ISSUE TITLE
Indirect Formulas Do Not Update

### ISSUE THREAD

**Issue by phillmorgan28** [CollaboraOnline/online#8490]
### Describe the Bug
When using INDIRECT in a formula, the cell does not update to reflect changes made on another sheet.

### Steps to Reproduce
1. Create 2 sheets
2. Add a formula to the first sheet that references a cell from the second sheet (per the photo)
3. Enter a value into the referenced cell
4. See the value in the first sheet with the formula does not update

### Expected Behavior
The cell on the first sheet should update to match the value on the referenced sheets cell

### Actual Behavior
A manual refresh is required by entering edit mode in the formula cell and pressing enter

### Screenshots
![image](https://github.com/CollaboraOnline/online/assets/13579386/09b7757e-7c20-4290-825d-6f81e3ca101d)

### Desktop
 - **Collabora version:** 23.05.9.2 (via Nextcloud)
 - **OS and version:** Windows 11
 - **Browser and version:** 122.0.2365.66 (Official build) (64-bit)

**Comment by Ezinnem** [comment]
I can confirm on:
COOLWSD version:
23.05.9.4 git hash: [04343c2](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/04343c2'));)

**Comment by bschmitz7** [comment]
If I tested this correctly, the bug not only applies to the INDIRECT formula, but to everything in general.

COOLWSD-Version: 23.05.9.4, git hash: 04343c2(E)

**Comment by timur-g** [comment]
There is a regression in 23.05.9 preventing formula updating when value in other sheet changes. That should be fixed in 23.05.11.

**Comment by timur-g** [comment]
This should be fixed in 23.05.11. Can you please check?
