### ISSUE TITLE
Enable "Private Vulnerability Reporting"

### ISSUE THREAD

**Issue by tehofu** [CollaboraOnline/online#8529]
Since I have difficulty reporting a vulnerability using the email address listed on the security page (I get no response), I think it would be very useful to improve the process.

Using the mailing list for all vulnerabilities seems inappropriate to me, vulnerabilities that only affect Collabora Online should be reported directly. The "Private Vulnerability Reporting" feature available on Github would be very convenient for this (https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability).

**Comment by timar** [comment]
@tehofu thanks for the tip, I enabled "Private Vulnerability Reporting" feature. We are looking forward to having your report.
