### ISSUE TITLE
Heading 1 and Heading 2 font colour is static for Calc

### ISSUE THREAD

**Issue by codewithvk** [CollaboraOnline/online#8553]
### Describe the Bug
In Calc, the font color for H1 and H2 text is not set automatic, causing it to appear dark when switching to dark mode. This makes the text hard to read in dark mode.

### Steps to Reproduce
1. Apply H1 or H2 formatting in Calc.
2. Switch to dark mode.

### Expected Behavior
The font color should be white in dark mode.

### Actual Behavior
The font color remains black in dark mode.

### Screenshots
![Screenshot from 2024-03-18 10-58-35](https://github.com/CollaboraOnline/online/assets/61119120/1ada7c61-8ada-42ae-b69c-9b4cecc9602e)

**Comment by codewithvk** [comment]
@pedropintosilva , Can you please confirm this bug?

**Comment by Ezinnem** [comment]
I can confirm.

Tested on:
23.05.9.4 git hash: [04343c2](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/04343c2'));)

**Comment by codewithvk** [comment]
Fix for this : https://gerrit.libreoffice.org/c/core/+/164965

**Comment by timur-g** [comment]
@codewithvk when submitting PR in Gerrit for Core, please always also have it in master.

**Comment by codewithvk** [comment]
> @codewithvk when submitting PR in Gerrit for Core, please always also have it in master.

@timur-g  Ah, great advice. However, I usually create after the PR gets merged into the distro. It makes it easy in case the PR needs refactoring. From now onwards, I'll do this. It makes sense. Thanks.!

**Comment by timur-g** [comment]
I see this OK, thanks. 
Since this was pure Core, better place for report was bugs.documentfoundation.org. I could not find report there, but nevermind, PR description is clear enough and does not require test document. 
As for PRs, if it is Core, than IMO best to start from master, then port. If LOk then from 24 and port to master and 23.
