### ISSUE TITLE
Improve split button styling

### ISSUE THREAD

**Issue by eszkadev** [CollaboraOnline/online#8566]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @pedropintosilva @eszkadev 

### Detailed description and rationale
Split buttons are buttons which have 2 parts: "`<direct command button>` | `<dropdown arrow>`"
Left one applies/runs some command but right part opens dropdown with more options.
It should be marked in the UI as 2 separate parts somehow. This is used for color pickers in notebookbar for example.
Notice that there are MenuButtons which doesn't have different actions for arrow and icon - Paste button in notebookbar.

See how it looks now:
[split-button-2024-03-18_18.22.50.webm](https://github.com/CollaboraOnline/online/assets/5307369/3d9402dd-176b-48c1-8ead-e596df191e00)

Currently on hover we highlight full button. It is not possible to differentiate between split and regular menu button.

### Code pointers
Split button is a kind of MenuButton: https://github.com/CollaboraOnline/online/blob/master/browser/src/control/jsdialog/Widget.MenuButton.js#L118

**Comment by printfdebugging** [comment]
I would like to work on this issue.  Don't know much web-programming, but I hope I can come up with something working coming saturday-sunday.

**Comment by Darshan-upadhyay1110** [comment]
Hii @eszkadev after merging solution for this issue can you please add "Hacktoberfest-accepted" label here?

**Comment by Saurabhyadav0** [comment]
@Darshan-upadhyay1110  hello i want to contribute to this repo how can I do that

**Comment by pedropintosilva** [comment]
This was fixed with https://github.com/CollaboraOnline/online/pull/10027 by @maks-w

**Comment by Darshan-upadhyay1110** [comment]
> @Darshan-upadhyay1110 Hi! I'd like to contribute to this repository. How can I get started?

Hi @Saurabhyadav0! Welcome! There are plenty of interesting issues waiting to be solved. You can find them here: [Open Issues](https://github.com/CollaboraOnline/online/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest). 

Feel free to pick any issue, and don't hesitate to reach out if you need any help. Also, it's Hacktoberfest season! If you're interested, you can register and join in here: [Hacktoberfest](https://hacktoberfest.com/). Check out more details on how to participate: [Collabora Online Hacktoberfest](https://collaboraonline.github.io/hacktoberfest/).

**Comment by Saurabhyadav0** [comment]
@Darshan-upadhyay1110 thank you ! but i want to know that how I can know that if I am solving a issue that is in hacktober fest or not  . Is this  whole repo is in hacktoberfest !all the issues

**Comment by Darshan-upadhyay1110** [comment]
> @Darshan-upadhyay1110 thank you ! but i want to know that how I can know that if I am solving a issue that is in hacktober fest or not . Is this whole repo is in hacktoberfest !all the issues

@Saurabhyadav0 Issues with tag "Hacktoberfest" are only ones :) https://github.com/CollaboraOnline/online/labels/Hacktoberfest
