### ISSUE TITLE
Missing line spacing icons

### ISSUE THREAD

**Issue by Darshan-upadhyay1110** [CollaboraOnline/online#8595]
- line spacing icons are not being set correctly.

![image](https://github.com/CollaboraOnline/online/assets/61383886/1173cc64-b589-4780-ab24-a21e84d288ef)

Error logs:
![image](https://github.com/CollaboraOnline/online/assets/61383886/427b99bb-4d4f-44d9-a1a8-5e13b5548d47)

**Comment by timur-g** [comment]
I see that in 24.04. 22.05 is OK for me | 
![image](https://github.com/CollaboraOnline/online/assets/7240617/c91ca955-25a0-477f-b06b-60c8d82e6446) | 23.05 also OK | 
![image](https://github.com/CollaboraOnline/online/assets/7240617/0ed0310f-c67a-4788-95a8-8dce78d71be8)

**Comment by timur-g** [comment]
Fixed in 24.04 but can you also please fix 23.05?

**Comment by Darshan-upadhyay1110** [comment]
@timur-g  Sure i will fix in 23.05
