### ISSUE TITLE
Format -> Conditional Menu Button Not Working

### ISSUE THREAD

**Issue by codewithvk** [CollaboraOnline/online#8651]
#### Description
In the tabbed view, clicking on Format -> Conditional does not open the menu as intended. It also doesn't have the arrow that we have in other menu buttons.

#### Steps to Reproduce
1. Open Calc and Navigate to the Format tab.
2. Attempt to click on Conditional.
3. Observe that the menu does not open.

#### Expected Behavior
The Conditional menu should open upon clicking, similar to the behavior observed in the Home tab.

#### Actual Behavior
The Conditional menu fails to open upon clicking.

#### Screenshots
![Screenshot from 2024-03-28 01-34-02](https://github.com/CollaboraOnline/online/assets/61119120/25caa194-5763-427b-9c97-79280031f177)

**Comment by timur-g** [comment]
I do not reproduce, PR is not yet fixed, what is needed for this?

**Comment by codewithvk** [comment]
> I do not reproduce, PR is not yet fixed, what is needed for this?

Are you trying on 24.04? 
COOLWSD version: 24.04.1.1 (git hash: f2e9dee7 (E))
LOKit version: Collabora Office 24.04.1.1 (git hash: 19ed6ec)
Served by: openSUSE Leap 15.5
Server ID: ffb3f33f
![Screenshot from 2024-03-30 11-39-49](https://github.com/CollaboraOnline/online/assets/61119120/c0f508ba-12c4-4651-8dca-4c39943aecbd)

**Comment by timur-g** [comment]
You are right @codewithvk . It is a regression from https://github.com/CollaboraOnline/online/pull/8482, cc @eszkadev  

commit 6f8996d1c1ba733def8a2654b63c6a2c5ec3fd26
Author: Szymon Kłos <szymon.klos@collabora.com>
Date:   Sun Mar 10 20:02:30 2024 +0100
    jsdialog: reuse standard MenuButton for ConditionalFormatMenu
