### ISSUE TITLE
Automatic color text inserted on white background slide not visible in Dark mode

### ISSUE THREAD

**Issue by GulsahKose** [CollaboraOnline/online#8656]
### Steps to Reproduce
1. Open test.odp in dark mode
2. Insert Text box and add some text in.

### Expected Behavior
We should see the text on slide

### Actual Behavior
Text is not seen although it is Automatic color. (Bug not seen if inserted in Light mode)

### Desktop
COOLWSD version: 23.05.2.2 git hash: afe6c1be
[test.odp](https://github.com/CollaboraOnline/online/files/14785918/test.odp)

**Comment by TheCyberQuake** [comment]
I'm getting this with normal text as well after saving, closing, and then opening the file if I type on new lines.
It also happens with bullet lists. I'm getting black text on black background when in dark mode. If I change affected lines using automatic, it will turn white. But then saving, closing, and reopening those lines are black again until I again select them and change to automatic manually.

**Comment by GulsahKose** [comment]
Fixed by https://gerrit.libreoffice.org/c/core/+/172564, Thanks @caolanm
