### ISSUE TITLE
Can start latest docker collabora 6.4.2.2 due to permissions problem

### ISSUE THREAD

**Issue by kevdogg** [CollaboraOnline/online#869]
Hi I believe the latest commit of adding the lool user broke some of the functionality of the container.  I'm using collabora/code:latest which translates to 6.4.2.2.  I'm getting the following errors when trying to start the container (not using K8s - docker-compose.yml)

```
cp: cannot create regular file '/opt/lool/systemplate/etc/resolv.conf': Permission denied
cp: cannot create regular file '/opt/lool/systemplate/etc/hosts': Permission denied
Can't open /etc/loolwsd/loolwsd.xml: Permission denied.
Can't open /etc/loolwsd/loolwsd.xml: Permission denied.
Can't open /etc/loolwsd/loolwsd.xml: Permission denied.
Can't open /etc/loolwsd/loolwsd.xml: Permission denied.
Can't open /etc/loolwsd/loolwsd.xml: Permission denied.
Run the script as root.
Setting up watches.
Couldn't watch /etc/loolwsd/loolwsd.xml: Permission denied
-rw-r----- 1 lool lool 18170 Nov 30 14:51 /etc/loolwsd/loolwsd.xml modified --> restarting
Hangup
```

Problem starting occurring recently and it might me due to last commit: https://github.com/CollaboraOnline/online/commit/418743df893c7ec9b36c3661ea689e33150eb03a

**Comment by timar** [comment]
418743d was supposed to fix this issue, did you pull recently?

**Comment by kevdogg** [comment]
You can probably close this issue,  I had to remove all the images and volumes associated with the container.  I believe what happened is you updated the UID however some of the old retained volumes still have the old UID.  So for me in addition to updating the container I had to rm all the associated volumes when container stopped.
