### ISSUE TITLE
Calc: automatic font color appears as black on dark theme

### ISSUE THREAD

**Issue by am97** [CollaboraOnline/online#8718]
### Describe the Bug

When using dark theme in Nextcloud, text with automatic font color appears as black with CODE 23.05.10.1.1. It used to appear as white with CODE 23.05.9.4.1

### Steps to Reproduce

1. Enable dark theme on Nextcloud
2. Open this document: [test.ods](https://github.com/CollaboraOnline/online/files/14891780/test.ods) (created locally with LibreOffice 7.5.9.2)

### Expected Behavior

The text «test» in the cell A1 should be visible in white, as it's the case on CODE 23.05.9.4.1:

![Screenshot from 2024-04-06 02-43-59](https://github.com/CollaboraOnline/online/assets/18473412/b6673792-9d8f-4d90-b3f5-3c1d1c7a3dac)

### Actual Behavior

The text is black:

![Screenshot from 2024-04-06 02-41-41](https://github.com/CollaboraOnline/online/assets/18473412/7f402a72-5541-4180-9afd-0b7f43b9540a)

### Additional Context

 - **Collabora version:** 23.05.10.1.1 (using Docker image `collabora/code:23.05.10.1.1`)
 - **Nextcloud version:** 27.1.8
 - **Nextcloud Office version:** 8.2.6
 - Reproduced on Firefox 124.0.1and Chromium 123.0.6312.105

Looking at the changes between CODE 23.05.9.4.1 and  23.05.10.1.1, it seems that this commit introduced the problem: https://github.com/CollaboraOnline/online/commit/100def4c80d6e467c32e2a3300e695905c358838

**Comment by timur-g** [comment]
Yes, regression, fixed with https://github.com/CollaboraOnline/online/pull/8692.
