### ISSUE TITLE
Updating from 8.2.4 to 8.2.7 breaks calc usage on firefox with dark mode

### ISSUE THREAD

**Issue by Polve** [CollaboraOnline/online#8721]
I'm running NC v. 27.1.8 (I tried with latest v28 too) and when I upgrade the office app from 8.2.4 to 8.2.6 I'm unable to edit spreadsheets any more: I just get empty sheets with very thick cell borders.

Is there something I miss? I never had problems upgrading before.

**Comment by thebearon** [comment]
Works fine here. Which version of CODE/Collabora Online are you using, and which browser+version?

**Comment by Polve** [comment]
collaboraoffice/coolwsd 23.05.10.1-1 running under debian bookworm

tried both with firefox 123.0 and chrome 123.0.x

**Comment by Polve** [comment]
I checked with another document and I was wrong to say the sheet it's empty: it's all so dark that I couldn't read the data, but it seems that the data is still there, only with unreadable colors and very thick borders

**Comment by Polve** [comment]
![image](https://github.com/CollaboraOnline/online/assets/1634436/3c7335b6-091c-41c1-8512-6e6511d10943)

**Comment by Polve** [comment]
Ok I found the problem: the dark mode of Firefox.

Just try to enable it to verify it: something must have changed in the latest CSS and this renders calc unusable for firefox users that uses dark mode.

**Comment by Polve** [comment]
I verified the same problem with latest version 8.2.7

**Comment by FloJuh** [comment]
Same problem with Google Chrome

**Comment by Polve** [comment]
Updated to version 8.2.10 with same problems

**Comment by Polve** [comment]
In the latest release (24.04.4.1), probably thanks to https://github.com/CollaboraOnline/online/issues/9061 the issue seems fixed!
