### ISSUE TITLE
Document Close_Session and Session_Closed post messages

### ISSUE THREAD

**Issue by juliushaertl** [CollaboraOnline/online#8748]
While looking for options to improve the open locally feature in the Nextcloud integration I came across the `Close_Session` and `Session_Closed` post messages, that are actually very useful to us.

I assume that they are just missing from being documented, would it make sense to add them to https://sdk.collaboraonline.com/docs/postmessage_api.html or is there a reason why those are not listed?

cc @pedropintosilva

**Comment by thebearon** [comment]
Probably an oversight, this was implemented for the following:
https://bugs.documentfoundation.org/show_bug.cgi?id=103640

In this commit: b0933b063e8b0e8e0de7eeeb9706fb291af72b5c
