### ISSUE TITLE
24.04.1.2 dark mode: cursor not visible

### ISSUE THREAD

**Issue by joergmschulz** [CollaboraOnline/online#8751]
### Describe the Bug
When my client is configured for dark mode, and I enter a document, the cursor is not visible.
When I reset the mode to normal via 'view', the cursor is visible (black on white)
When I reset the mode to dark mode afterwards, the cursor is visible again (white on black)

### Steps to Reproduce
1. open a document when your client is configured for dark mode using the nextcloud integration 8.3.3+

### Expected Behavior
cursor visible 

### Actual Behavior
cursor not visible 

### Desktop
 - **Collabora version:** 24.04.1.2, nextcloud 28.0.4
 - **OS and version:** windows 11, macos
 - **Browser and version:** safari, firefox, edge

### Additional Context
maybe black-on-black cursor?

from https://forum.collaboraonline.com/t/24-04-1-2-dark-mode-cursor-not-visible/2536

**Comment by vmiklos** [comment]
Thanks, I can confirm this, somehow the tiles don't get the info that they need to be in dark mode.

**Comment by Polve** [comment]
I suppose this is one more problem of what I get in #8721

**Comment by joergmschulz** [comment]
Seems to be resolved now

**Comment by vmiklos** [comment]
Yes, I think @caolanm fixed this in the meantime.
