### ISSUE TITLE
Docker log errors - missing files for timezone settings

### ISSUE THREAD

**Issue by sseide** [CollaboraOnline/online#879]
**Describe the bug**
With latest version od docker container i see a lot of error messages in the docker logs - this is the first report, another follows.

Inside docker logs are errors regarding issing files:

Using image collabora/code:6.4.2.2

**To Reproduce**

1. start collabora image code:6.4.2.2, used params suggests to start docker container (used real domain not this one): 
```
docker run -t -d -p 127.0.0.1:9980:9980 -e 'domain=office\\.my-domain\\.redacted' --restart always --cap-add MKNOD collabora/code
```
2. collabora is integrated into nextcloud 20 - open a office file there (.xslx or .ods or something else, file type does not matter as long as its a file opened with collabora office).
3. check docker logs of code server - there are many error messages like:
```
frk-00047-00047 2020-12-03 22:10:32.741086 [ forkit ] ERR  Failed to get the realpath of [/etc/timezone] (ENOENT: No such file or directory)| common/FileUtil.cpp:256
frk-00047-00047 2020-12-03 22:10:32.741191 [ forkit ] ERR  Failed to get the realpath of [/etc/localtime] (ENOENT: No such file or directory)| common/FileUtil.cpp:256
kit-00083-00047 2020-12-03 22:10:32.973179 [ kit_spare_004 ] ERR  Failed to get the realpath of [/etc/timezone] (ENOENT: No such file or directory)| common/FileUtil.cpp:256
kit-00083-00047 2020-12-03 22:10:32.973553 [ kit_spare_004 ] ERR  Failed to get the realpath of [/etc/localtime] (ENOENT: No such file or directory)| common/FileUtil.cpp:256
```

**Expected behavior**
No error messages about files missing should be shown.

**Actual behavior**
Error message appers. Looking into the container with `docker exec` booth files are missing (/etc/timezone, /etc/localtime)

**Screenshots**
none

**Desktop (please complete the following information)**
not relevant

**Smartphone (please complete the following information)**
not relevant

**Additional context**
Installed docker container and nextcloud integration via scripts provided by Hannson IT prebuild Nextcloud 20 image.
Collabora Online is working sometimes, but often shows a "Forbidden Access" inside the browser - but this may be related to second ticket i'll create later on.

**Comment by timar** [comment]
There is no general way to pass time zone information to a docker container. If you start it from Linux host, you can add your host's /etc/timezone and /etc/localtime as volumes. On the other hand, we should not report these missing files as error. A warning is enough. The container will think that the time zone is UTC.
