### ISSUE TITLE
Collabora 23.05.10.1 doesn't show the zotero Bibliography

### ISSUE THREAD

**Issue by MicKress** [CollaboraOnline/online#8826]
### Describe the Bug
You can't add citations from zotero in Collabora CODE (Nextcloud Office) 23.05.10.1 although the zotero api is set.

### Steps to Reproduce
1. Open Nextcloud Office. A message is shown "citation is actualized"
2. Click on References -> Add citation
3. A Pop-Up-Window is shown "My bibliography" with no entries
4. Clicking "Actualize" takes no effort and you cannot close the window. 

### Expected Behavior
You can choose entries in the Pop-Up-Window "My bibliography" and you can click on the button "actualize". The Pop-Up-Window is closed.

### Actual Behavior
You cannot choose entries and the window is in foreground;you cannot close it.

### Screenshots
<img width="812" alt="Bildschirmfoto 2024-04-19 um 17 37 18" src="https://github.com/CollaboraOnline/online/assets/47255870/504998f6-c30c-4e7d-8091-90cd91a03492">

### Desktop
(Please complete the following information)
 - Collabora version: [23.05.10.1]
 - OS and version: [MacOs 14.4.1]
 - Browser and version: [Chrome 123.0.6312.124, also on Safari and Firefox]

**Comment by timur-g** [comment]
Should be fixed with  https://github.com/CollaboraOnline/online/pull/8779 in 23.05.11. 
There is another bug that Zotero menu is missing, but let us wait to see if that one will be fix in time for that release.
