### ISSUE TITLE
perf: async & caching DNS

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#8829]
Watchdog profiling suggests that synchronous, and apparently under-cached DNS lookups are something that blocks the websrv_poll thread quite often.

![image](https://github.com/CollaboraOnline/online/assets/122848/302ca14d-63b4-4267-94d9-b8a2bb24a663)

@vmiklos I wonder if this is a factor in copy/paste performance; since (I guess) we would need to get into the websrv_poll in order to eg. fetch and download a clipboard.

I expect that integrations hammer our 'allowConvertTo' quite hard and that we should do better here.

I imagine a small cache of DNS results that we can expire every 20 seconds or somesuch might be helpful; and then separately doing the DNS lookup itself in another thread and getting a callback back into the websrv_poll to finish the work when that is done would be reasonably easy & give a nice win.

**Comment by vmiklos** [comment]
> @vmiklos I wonder if this is a factor in copy/paste performance; since (I guess) we would need to get into the websrv_poll in order to eg. fetch and download a clipboard.

I guess it depends on if we detect a 1) normal external 2) internal 3) other COOL clipboard. I would expect it is a factor in case 3), but not in 1) and 2).

**Comment by caolanm** [comment]
https://github.com/CollaboraOnline/online/pull/9069 is the effort there
