### ISSUE TITLE
Menu item 'Datei' overlayed by 'in lokalem editor öffnen'

### ISSUE THREAD

**Issue by joergmschulz** [CollaboraOnline/online#8856]
### Describe the Bug
The menu item / Button 'Datei' is overlayed by the button 'in lokalem Editor öffnen':
<img width="229" alt="grafik" src="https://github.com/CollaboraOnline/online/assets/6523646/31c54f68-5d7b-4edb-b1a0-a6956737b4e6">
Thus, it is not possible to reach the 'Datei' menu.
This is independent from the used browser (Firefox, Safari, Chrome on Macos, Edge on Windows)
This happens within the nextcloud integration.
coolwsd 24.04.1.2

**Comment by thebearon** [comment]
That's supposed to be an icon, which version of Nextcloud and richdocuments are you using?
