### ISSUE TITLE
View > Zoom Out + Change Sheet = Extra space to top+left of original sheet

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#8874]
### Describe the Bug

When Zooming Out, extra space appears to the top+left of a different sheet.

See photos Before/After:

<img src="https://github.com/CollaboraOnline/online/assets/5774324/430d30ae-8974-48c5-b39e-02138bc7f5c8" alt="Collabora 24 04 1 3 - Calc - Zoom Out Change Sheet Extra Space Bug Before" width="49%"/> <img src="https://github.com/CollaboraOnline/online/assets/5774324/f615fda5-c3e7-42e0-b128-10ba8b286481" alt="Collabora 24 04 1 3 - Calc - Zoom Out Change Sheet Extra Space Bug After" width="49%"/>

### Steps to Reproduce

In Calc:

0. Open [Color.Columns.in.Sheet1.ods](https://github.com/CollaboraOnline/online/files/15108867/Color.Columns.in.Sheet1.ods) + start in Sheet1.
1. Go to Sheet2.
2. **View > Zoom Out**
3. Go back to Sheet1.

### Expected Behavior

In Sheet1, you should see red column (+ A1's text) in the upper left corner.

### Actual Behavior

You see a weird "extra row/column" of white space above+to the left of the cells.

### Desktop

- **Collabora version:** 24.04.1.3
- **OS and version:** Windows 11
- **Browser and version:** Chrome 124.0.6367.78 (64-bit)

This was on Share server:

> COOLWSD version: 24.04.1.3 (git hash: fa6d8f6d (E))
> LOKit version: Collabora Office 24.04.1.4 (git hash: e2cbe31)
> Served by: openSUSE Leap 15.5
> Server ID: 0c727364

and I even retested on local:

> COOLWSD version: 24.04.1.3 (git hash: 8510db55)
> LOKit version: Collabora Office 24.04.1.4 (git hash: 91ae3cd)
> Served by: Linux Mint 21.3
> Server ID: 8647ee4d

This DOES NOT occur in core LO 24.2:

> Version: 24.2.2.2 (X86_64) / LibreOffice Community
> Build ID: d56cc158d8a96260b836f100ef4b4ef25d6f1a01
> CPU threads: 8; OS: Windows 10.0 Build 22631; UI render: Skia/Raster; VCL: win
> Locale: en-US (en_US); UI: en-US
> Calc: CL threaded

### Additional Context

None.

**Comment by Darshan-upadhyay1110** [comment]
Tested and looks good

[Screencast from 2024-07-17 21-52-06.webm](https://github.com/user-attachments/assets/55e28675-7080-4f3d-86e8-ce8e3ec822e1)

COOLWSD version: 24.04.5.2 (git hash: be940ae0 (E))
LOKit version: Collabora Office 24.04.5.2 (git hash: 3dcf0f9)
Served by: openSUSE Leap 15.5
Server ID: d1c5cea0
