### ISSUE TITLE
Calc: add Define Range

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#890]
This hack has two parts - first, we need to add the UNO command: .uno:DefineDBName (and perhaps .uno:SelectDB) to the UI - to trigger the existing dialogs we have.

Then we need to hack the core - to allow this UNO command through desktop/source/lib/init.cxx (I guess).

Then we need to ensure the core has a non-modal dialog for this:

sdi/cellsh.sdi:    SID_DEFINE_DBNAME           [ ExecMethod = ExecuteDB; StateMethod = GetDBState; ]

sc/source/ui/view/tabvwshc.cxx-            xResult = std::make_shared<ScDbNameDlg>(pB, pCW, pParent, GetViewData());

Interetingly this method has:

std::shared_ptr<SfxModelessDialogController> ScTabViewShell::CreateRefDialogController(

Is it possible that those are all async ? if so that would be wonderful and we should look at exposing all of the calc features there; but we really need to ensure that they are not sync dialogs that push an 'Execute' on the stack.

Thanks !

**Comment by mmeeks** [comment]
Marco - if you're looking for a distraction this would be useful =)

**Comment by timar** [comment]
It's done. Target: Collabora Online 6.4.3 in January, 2021.
