### ISSUE TITLE
Automatic Spell Checking is not working

### ISSUE THREAD

**Issue by dapenamr** [CollaboraOnline/online#8910]
### Describe the Bug
When clicking on the Review>Automatic Spell Checking option, nothing happens. I don't see any indication of necessary text corrections or misspelling.

### Steps to Reproduce
![Issue_01-Collabora-20240426](https://github.com/CollaboraOnline/online/assets/125194763/9451f5b9-085a-4d74-a1e1-b3a0c1d69ebd)

1. See GIF attached

### Expected Behavior
I was expecting that after finishing the text, and clicking on Review>Automatic Spell Checking, it would indicate the misspelled words by underlining them.

### Actual Behavior
Clicking on Review>Automatic Spell Checking does nothing. The text remains in its original form, with the misspelled words.

### Screenshots
A GIF is attached.

### Desktop
 - Collabora version:
Collabora Office 23.05.8.2 git hash: 
[6b6e5cf](javascript:void(window.open('https://hub.libreoffice.org/git-core/6b6e5cf'));)
Served by: Debian GNU/Linux 12 (bookworm) 
[1a0c8054](https://office.drive.shadow.tech/hosting/discovery)

 - OS and version:
 Windows 11 Pro, Version 23H2, OS Build 22631.3447

 - Browser and version:
Firefox Browser 125.0.2 (64-bit)

### Additional Context
Using uBlock Origin 1.57.2

**Comment by thebearon** [comment]
Have you installed the respective language packages as described here?
https://sdk.collaboraonline.com/docs/installation/Installation_from_packages.html#localization

**Comment by dapenamr** [comment]
Hello, 
Thank you for your answer and information.
I'm currently using the 'Collabora Suite in Beta' version, which is available on my ShadowDrive. Since it's a trial version, I'm not 
sure if I can/should install the dictionaries your link mentioned. I also don't know how to access 'coolwsd.xml' from a web browser. 
Nevertheless, thank you for your time and reply.

**Comment by thebearon** [comment]
I assume you are referring to this, and you are not the hoster: https://shadow.tech/blog/collabora-shadow-drive

In that case please contact the support of your hosting company, and they can contact Collabora Productivity if they need assistance with their configuration.

**Comment by dapenamr** [comment]
Perfect, that's exactly what I mean. Thank you for responding so quickly, I will get in touch with my hosting company. Thank you once again.
