### ISSUE TITLE
The Smart Picker doesn't load after clicking on the Smart Picker button in the "Insert" tab of Collabora while editing an ODT or ODG file on Firefox 125.0.2 or Google Chrome 124.0.6367.91

### ISSUE THREAD

**Issue by S0ulf3re** [CollaboraOnline/online#8917]
### Describe the Bug
On Nextcloud 29.0.0.19 with the Nextcloud office 8.4.0 addon and Collabora v24.04.1.4 (All running through docker as separate images), the smart picker will simply not appear when it's button is clicked on while using Vivaldi 6.7.3329.17, Firefox 125.0.2, or Google Chrome 124.0.6367.91. This has been tested while editing ODT and ODG files

### Steps to Reproduce
1. Go to the insert tab
2. Click on the "Smart Picker" button
3. See nothing

### Expected Behavior
The Smart Picker from the Nextcloud smart picker API should appear and allow for input

### Actual Behavior
Nothing happens at all.

https://github.com/CollaboraOnline/online/assets/50301900/bc1b66d8-409a-4b55-bb68-5c130d44b619

### Desktop
(Please complete the following information)
 - **Collabora version:** 24.04.1.4
 - **OS and version:** macOS 14.4.1
 - **Browser and version:** Google Chrome 124.0.6367.91 and Firefox 125.0.2

**Comment by sebastiaanveld** [comment]
Same issue with Nextcloud 28.0.5.

    Collabora version: 24.04.1.4
    OS and version: Windows 11, latest patches
    Browser and version: Edge 124.0.2478.67 and Firefox 125.0.2 (x64)

**Comment by S0ulf3re** [comment]
According [here](https://github.com/nextcloud/richdocuments/issues/3644#event-12673357316), this has been fixed.
