### ISSUE TITLE
DNS seen as a watchdog hotspot on demo.eu

### ISSUE THREAD

**Issue by caolanm** [CollaboraOnline/online#8946]
### Describe the Bug
In watchdog profiles, to capture where online stalls, we see dns calls taking up a disproportionate amount of time on demo.eu
A sample framegraph can be found at:

<img src="https://raw.githubusercontent.com/caolanm/profiles/3022ef684cb3addeaf2ee16faa476fb26e216a8f/watchdog/Demo.eu-2024-05-01T08%3A20%3A13.361093.svg"/>

where the last two wide columns are DNS related. The effect is perhaps is more pronounced on that setup than on a typical one. 

@mmeeks FYI

**Comment by mmeeks** [comment]
Thanks - of course this potentially blocks serving pages, and also connecting to coolwsd - so we badly need to:

[ ] - get those name lookups - or even better filtering results so we cache IP -> positive & negative deny+allow cache entries - I expect lots of this is repetitive work for thumbnailing files in the file views.
[ ] - have one (or more?) DNS lookups at a time in a queue of threads to do that, with callbacks into the main SocketPoll to continue processing that request.
[ ] - ideally a nice async DNS API to abstract this stuff =)

**Comment by mmeeks** [comment]
A duplicate of - https://github.com/CollaboraOnline/online/issues/8829 ? =)

**Comment by caolanm** [comment]
Duplicate of #8829
