### ISSUE TITLE
Resulting docker image is incompatible with eliptic curves webservers(outdated libpoco)

### ISSUE THREAD

**Issue by kratzersmz** [CollaboraOnline/online#895]
**Describe the bug**
https://www.collaboraoffice.com/online/collabora-online-update-4-2-1-available/  --> 
"On CentOS 8, Ubuntu 18.04, and Debian 10, which have OpenSSL 1.1.1, now we link loolwsd with Poco 1.10.1. That solves SSL connection issues, e.g. connecting to sites that have certificates made with elliptic curve key"

The current provided docker build stuff will not result in docker images which are compatible with eliptic curves:
https://github.com/CollaboraOnline/online/tree/master/docker  ---> still outdated libpoco
https://github.com/CollaboraOnline/online/tree/libreoffice-7-0/docker ---> still outdated libpoco

With outdated libpoco i mean that libpoco has problems with eliptic curves...

**To Reproduce**
https://github.com/CollaboraOnline/online/tree/libreoffice-7-0/docker 

**Expected behavior**
Connect to e.g. an nextcloud instance with eliptic curves enabled should work without problems...

**Actual behavior**
lool cant connect to nextcloud storage with ssl error

**Comment by timar** [comment]
I'll fix this on master, but libreoffice-7-0 is out of scope.
