### ISSUE TITLE
Autfilter: filter changes 1st row's height

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#8961]
### Describe the Bug
originally reported in https://forum.collaboraonline.com/t/how-to-use-filter-in-collabora-online-problem-in-filtering/2518 

> I have a problem that shown big space at the top as below picture when use filtering in Collabora Online.
> But nothing problem when open the same file on LibreOffice.

### Steps to Reproduce
1. Open  [test.ods](https://github.com/CollaboraOnline/online/files/15197435/test.ods)
2. Click in any column header's arrow to open the autofilter options
3. Deselect all
4. Select individual values
5. Click ok
6. Scroll up
7. Observe: 1st column has changed height

### Expected Behavior
Column shouldn't change height

### Actual Behavior
A clear and concise description of what actually happens.

### Screenshots & Video
![image](https://github.com/CollaboraOnline/online/assets/65948705/68a104eb-55e4-4d8c-9174-0bc8bf1ba560)
[evidence.webm](https://github.com/CollaboraOnline/online/assets/65948705/184f3479-2a83-42e1-aa04-a6c397aad109)

### File
[test.ods](https://github.com/CollaboraOnline/online/files/15197508/test.ods)
(also tested in staging eu under `Community Test` folder: https://staging-perf.eu.collaboraonline.com/nextcloud/index.php/s/BSQqHmJJJG89Y7B)

### Desktop
(Please complete the following information)
* Nextcloud ver: Hub 4 (26.0.13)
* COOLWSD version: 23.05.10.1
* OS (Ubuntu, Windows10)
* Tested Brosers(Chrome, Vavaldi, Firefox)

### Additional debug info
```javascript
09:56:19.356 DEBUG: onStatusMsg: status: type=spreadsheet parts=1 current=0 width=55620 height=2340 viewid=4 lastcolumn=20 lastrow=464 readonly=0
Sheet1 bundle.js:18199:86
09:56:19.992 debug: got sheetGeometry: this._rtlParts =  this._selectedPart = 0 bundle.js:18324:82
09:56:42.886 XHRGET
https://staging-perf.eu.collaboraonline.com/nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications
[HTTP/1.1 304 Not Modified 181ms]
```
The following is not directly related to this ticket but it shows up when moving the cell cursor:

```javascript

09:57:11.316 Expected colour but found '#000NaN'.  Error in parsing value for 'background-color'.  Declaration dropped. 2 cool.html
09:57:11.887 XHRGET
https://staging-perf.eu.collaboraonline.com/nextcloud/index.php/apps/files/api/v1/stats
[HTTP/1.1 200 OK 76ms]

09:57:12.950 XHRGET
https://staging-perf.eu.collaboraonline.com/nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications
[HTTP/1.1 304 Not Modified 91ms]

09:57:30.018 Expected colour but found '#000NaN'.  Error in parsing value for 'background-color'.  Declaration dropped. 2 cool.html
09:57:42.960 XHRGET
https://staging-perf.eu.collaboraonline.com/nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications
[HTTP/1.1 304 Not Modified 187ms]


```

**Comment by lpranam** [comment]
Fix: https://gerrit.libreoffice.org/c/core/+/174755

**Comment by Ezinnem** [comment]
Tested OK in: COOLWSD version: 24.04.9.0 (git hash: 9d49ea31]( [[ https://github.com/CollaboraOnline/online/commits/9d49ea31) ]] (E)) LOKit version: Collabora Office 24.04.9.0(git hash:   [3eae554](https://git.libreoffice.org/core/+log/3eae554) 
 
[Screencast from 15-10-2024 08:33:39.webm](https://github.com/user-attachments/assets/aa81294c-22f1-457f-b275-19ade72de440)
