### ISSUE TITLE
Print button in Tabbed view in Calc does not work

### ISSUE THREAD

**Issue by PaulosV** [CollaboraOnline/online#8969]
### Describe the Bug

In Tabbed view in Calc, when trying to print a document using File -> Print, both "Active sheet" and "All Sheets" do not perform any action when clicked.

In Compact view, the "Print" button and both options seem to be working just fine. Ctrl+P also works and displays the dialog.

Writer and Impress seem to work fine.

This is reproducible with the current master (a6b3961c50559f8976f59f2803422f398376ea8c).

### Steps to Reproduce
1. Open a Calc document (reproducible both in Gitpod and Nextcloud integration).
2. With Tabbed view, go to tab File.
3. Click Print, and click either All sheets or Active sheet.

### Expected Behavior
After a few seconds, the print dialog should have appeared.

### Actual Behavior
No dialog is displayed.

### Desktop
 - **Collabora version:** 24.04.1.4 (git hash: f12ee1f)
 - **OS and version:** Arch Linux, amd64
 - **Browser and version:** Firefox 125.0.3

### Additional context

This is similar to https://github.com/CollaboraOnline/online/issues/8931 except for the fact that I can export and download the PDF just fine.

This is the event that is displayed with debug mode:

```
control: 'menubutton' id:'Data-Print' event: 'select' state: 'print-active-sheet'
OUTGOING: dialogevent -2 {"id":"Data-Print", "cmd": "select", "data": "print-active-sheet", "type": "menubutton"} 
```

![image](https://github.com/CollaboraOnline/online/assets/4086023/27888e67-ca87-499f-87d7-3eca0a1f8307)

**Comment by s1dh** [comment]
I confirm this problem too.

**Comment by timur-g** [comment]
Fixed with  https://github.com/CollaboraOnline/online/pull/9070 for Online 24.04.3.
