### ISSUE TITLE
user_interface set to classic in /etc/loolwsd/loolwsd.xml but still showing tabbed menu

### ISSUE THREAD

**Issue by wdehoog** [CollaboraOnline/online#897]
**Describe the bug**
We are running the docker image with  user_interface set to classic in /etc/loolwsd/loolwsd.xml (unedited so everything is the default). But still the UI is showing the tabbed menu.

**Expected behavior**
The classic menu shoud be shown.

**Actual behavior**
The tabbed menu is shown.

**Server**
 - Ubuntu 20.04
 - Firefox 83
 - Collabora Online Version: 6.4.2

**Comment by thebearon** [comment]
Indeed, it's set in `start-collabora-online.sh` in the root directory as parameter `--o:user_interface.mode=notebookbar`. As a workaround you could remove that piece, and restart the container.

**Comment by thebearon** [comment]
After #3632 the user interface mode in loolwsd.xml is disregarded again, but an extra parameter `user_interface_mode` can be passed as `-e 'user_interface_mode=classic'` during container creation to set classic toolbar.
