### ISSUE TITLE
Unit test failure when running CppunitTest_vcl_svm_test in core with cairo RGBA config

### ISSUE THREAD

**Issue by thebearon** [CollaboraOnline/online#9002]
I build my local core with a subset of the `CPLinux-LOKit` distro config.
If it has the following two config lines in `autogen.input`:
```
--enable-cairo-rgba
--without-system-cairo
```

... I get the unit test failures shown below when running `CppunitTest_vcl_svm_test`:

```
xmltesttools.cxx:170:Assertion
Test name: SvmTest::testBitmaps
equality assertion failed
- Expected: 469f0820
- Actual  : 3789377b
- In <>, attribute 'crc' of '/metafile/bmp[1]' incorrect value.

xmltesttools.cxx:170:Assertion
Test name: SvmTest::testBitmapExs
equality assertion failed
- Expected: ac936607
- Actual  : ecd75a28
- In <>, attribute 'crc' of '/metafile/bmpex[1]' incorrect value.
```

If I comment out the `--enable-cairo-rgba` config (or both), there are no failures.

CC @caolanm in case you have an idea why this might happen.

**Comment by caolanm** [comment]
The R and B or RGB colors are reversed with --enable-cairo-rgba (on purpose) in the config for reuse by online, so online can ship the bits to the browser in a format they can consume without swapping them around, so the test is right in that they are unexpected from the tests perspective, but they are right for what we want. See the similar issue for endianness in that test.

Anyhow, I propose https://gerrit.libreoffice.org/c/core/+/167314 to adjust the test to pass.
