### ISSUE TITLE
Add extra toggle when on dark mode or if the dark mode UI feature is disabled by the integrator to switch it of solely for the document

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#9061]
Let's split these in two parts
1st and top priority Add extra toggle when on dark mode that allows the user to invert document's color. So, the user is able switch the colors that the document is displaying at will when on dark mode.

1. On Light mode this new toggle shouldn't be visible
2. On Dark mode this new toggle should be visible and turned on by default.
  * The button will have a label such as "Switch background" or "Inverted Colors" as mentioned in https://github.com/CollaboraOnline/online/issues/9062
  * If the user clicks in it then the colors of the document are not inverted anymore 

The issue it fixes:
* Unable to switch mode selectively. There are cases where user would like to switch off dark mode for document only when the dark mode is on. Examples: Wants to colour/print proof simulate; Needs to check how the document will look like before exporting; Wants to edit document while making sure the company branding guidelines are being followed. There is some initial steps in the works config: remove scheme document background colors #8564: https://github.com/CollaboraOnline/online/pull/8564

**Comment by Ornanovitch** [comment]
Thanks a lot for this precious roadmap!

> On Dark mode this new toggle should be visible and turned on by default

Why on by default? It is not a default behavior on desktop... Could it be at least configurable in the server config?

**Comment by pedropintosilva** [comment]
@Ornanovitch thank you for chiming in.
The feedback (particularly by email or via the Help > Feedback) is that people prefer to have a full dark experience most of the times but still would like to be able to switch it off for the document¹. Nevertheless, the user change should be saved (similar as it already happens with the dark mode toggle), this means: if you press the "Invert Background" button you will not need to press once again for the next time you open any document.

----
1. I think we are flexible here so, if we get opposite feedback we are willing to learn and adapt.
