### ISSUE TITLE
Better clipboard paste error handling on Chrome for cross-origin iframes

### ISSUE THREAD

**Issue by vmiklos** [CollaboraOnline/online#9072]
### Describe the Bug

23.05 used to have suboptimal copy, but it did work to some extent. Now if an integration is not updated to allow clipboard write for cross-origin iframes, copy doesn't work at all on 24.04.

### Steps to Reproduce
1. Open e.g. a Writer document in COOL, in a setup where COOL and the integration is served from different domains. E.g. nextcloud with its richdocuments.git, stable28 branch, with commit 6e29846aeda3bb933935400bb7334a3a71445211 reverted. But https://github.com/owncloud/richdocuments/issues/545 is probably a similar environment.
2. Select some text.
3. Press 'copy' on the notebookbar.

### Expected Behavior

If the integration doesn't allow new-style copy, a popup should appear encouraging the user to try again via the keyboard. We should also remember that new-style copy failed and not try again.

### Actual Behavior

An error is logged on the JS dev console, but otherwise nothing.

### Desktop

Tested on Chrome, with old enough (see above) Nextcloud integration, COOL and Nextcloud served from different domains.

### Additional Context

An alternative would be to just remember the failure for the duration of the edit session (global JS variable). That would have the benefit that in case the integration gets fixed, new-style copy gets a chance again in the next edit session. The cost would be that every time the first copy would be broken. Seems the cost outweights the benefit, so for now we save a setting and never try again, even not after a browser reload.

**Comment by vmiklos** [comment]
The above PR fixes this for me.

**Comment by chris-fj** [comment]
I wanted to share that I updated to [`24.04.5.2.1`](https://hub.docker.com/layers/collabora/code/24.04.5.2.1/images/sha256-b2cdde5cabb3cfd59933daf3ce55990b258a4a1391d31d54833e436e7b7fc26f?context=explore) along with ownCloud 10.14 and the clipboard issue is gone. Thanks for your work here
