### ISSUE TITLE
Calc: Extra cursor remains after editing multiline cell

### ISSUE THREAD

**Issue by neilguertincollabora** [CollaboraOnline/online#9085]
### Steps to Reproduce
1. Open calc
2. Enter multiline text (using paste or ctrl+enter)
3. Delete cells

### Expected Behavior
Cursor appears only when editing a cell

### Actual Behavior
Extra cursor appears or remains when editing or deleting the cell with multiline text

### Screenshots
[Screencast from 2024-05-17 04-35-31.webm](https://github.com/CollaboraOnline/online/assets/153108452/0a8b2c29-5f7a-41ac-a2e2-28f49b3f7e82)

### Desktop
(Please complete the following information)
COOLWSD version: 24.04.2.1snapshot (git hash: cd9875e)
LOKit version: Collabora Office 24.04.2.20240515 (git hash: 07c93a6)
Served by: Ubuntu 22.04.4 LTS
Server ID: 9a360812

**Comment by thebearon** [comment]
Should be fixed once #9106 is merged.
