### ISSUE TITLE
add setting for canvas re-rendering debugging

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#914]
When you triple click on help->about you get a debugging palette of options. Currently we have canvas (ie. sidebar & dialog) invalidation re-rendering debugging which is great - but ... we should be able to turn that off so the app can be used normally.

Probably we should slave that to one of the other options instead of just debug; you can find those with 'git grep <user visible string>'.

git grep -5 _debug
git grep -10 _debugPaintWindow

would be some useful places to look =)

**Comment by Rash419** [comment]
what do you mean by invalidation re-rendering debuggging?
