### ISSUE TITLE
Hyperlink Shortcut should get the Link textbox in focus

### ISSUE THREAD

**Issue by Ezinnem** [CollaboraOnline/online#9141]
### Describe the Bug
Using CTRL + K to trigger the Hyperlink dialog does not bring the Link text box into focus.

### Steps to Reproduce
1. Open a .odt file
2. Press CTRL+K. This pops up the Hyperlink dialog.

### Expected Behavior
The text box for adding the link should be in focus

### Actual Behavior
The text box for adding the link does not get focus

### Screenshots
![Screenshot from 2024-05-23 11-15-29](https://github.com/CollaboraOnline/online/assets/54344301/beaa34d3-a3e4-44fb-9a9d-64970be1dc75)

### Desktop
(Please complete the following information)
 - **Collabora version:** 24.04.3.1 git hash:  [030895c7](https://github.com/CollaboraOnline/online/commits/030895c7)(E)
 - **Browser and version:**  Chrome 114.0

### Additional Context
Seems OK in 23.05 version:
COOLWSD version: 23.05.11.1 (git hash: [94ff17bf](https://github.com/CollaboraOnline/online/commits/94ff17bf))

**Comment by Darshan-upadhyay1110** [comment]
Working in our latest version.

COOLWSD version: 24.04.5.1 (git hash: 1ecf31df)
LOKit version: Collabora OfficeDev 24.04.5.1 (git hash: e1cfc65)
Served by: Ubuntu 23.10
Server ID: 7a9ed233


Closing this issue.
