### ISSUE TITLE
Password protected file cannot be opened / type detection aborted

### ISSUE THREAD

**Issue by JB1985** [CollaboraOnline/online#9192]
### Describe the Bug
A document that is password protected cannot be opened.

### Steps to Reproduce
1. Create a Document with a Password, on a Microsoft Office
2. Try to open with Collabora Inline
3. See error

### Expected Behavior
Open document and type the password.

### Actual Behavior
Error

```
kit-113661-113661 2024-05-31 11:04:00.036969 +0200 [ kitbroker_2bf ] ERR  Failed to load: file:///tmp/user/docs/qoYqFUbdMqAFhl2K/Das%20Geheimnis.xlsx, error: Unsupported URL <file:///tmp/user/docs/qoYqFUbdMqAFhl2K/Das%20Geheimnis.xlsx>: "type detection aborted" at /home/xxx/collabora-office/core/core/framework/source/loadenv/loadenv.cxx:189| kit/Kit.cpp:1828
kit-113661-113661 2024-05-31 11:04:00.037004 +0200 [ kitbroker_2bf ] ERR  ToMaster-ce60: error: cmd=load kind=faileddocloading| common/Session.hpp:168
kit-113661-113661 2024-05-31 11:04:00.037034 +0200 [ kitbroker_2bf ] FTL  Failed to load the document. Setting TerminationFlag| kit/Kit.cpp:1855
kit-113661-113661 2024-05-31 11:04:00.037041 +0200 [ kitbroker_2bf ] ERR  ToMaster-ce60: Failed to get LoKitDocument instance for [file:///tmp/user/docs/qoYqFUbdMqAFhl2K/Das%20Geheimnis.xlsx]| kit/ChildSession.cpp:816
```

### Screenshots
![Bildschirmfoto_2024-05-31_um_09 59 16](https://github.com/CollaboraOnline/online/assets/9932751/a3c15e19-09e9-4698-ac3b-85224a100e28)

### Desktop
(Please complete the following information)
 - **Collabora version:** 24.04.3-1
 - **OS and version:** Windows 11
 - **Browser and version:** Chrome

Server:
Debian Bookworm
Collabora Online: cp-24-04.3-1
Libreoffice: cp-24-04.3-1

**Comment by JB1985** [comment]
Same in Version: cp-24.04.3-2

**Comment by JB1985** [comment]
It probably only affects Microsoft Office documents that are protected with a password. 

Documents created with LibreOffice will be asked for a password. BUT the password doesn't work. The request for the password keeps coming.

**Comment by thebearon** [comment]
> Documents created with LibreOffice will be asked for a password. BUT the password doesn't work. The request for the password keeps coming.

Can you share the exact steps? I created a password-protected document in LO, and it opened in online fine. I haven't checked the MS Office case, yet.

**Comment by JB1985** [comment]
LibreOffice Version: Version: 24.2.3.2 (X86_64) / LibreOffice Community
Build ID: 433d9c2ded56988e8a90e6b2e771ee4e6a5ab2ba
CPU threads: 12; UI render: Skia/Raster; VCL: win
Locale: de-DE (de_DE); UI: de-DE
Calc: threaded
OS: Windows 11 pro

Open Calc
Save As (with password)
![image](https://github.com/CollaboraOnline/online/assets/9932751/0c8b55d9-632c-4f19-ba06-73c5a9bc6a38)

And then Upload to my Nextcloud (27.1.10)
Server:
Debian Bookworm
Collabora Online: cp-24-04.3-2
Libreoffice: cp-24-04.3-2

**Comment by JB1985** [comment]
Still in 24.04.3-6

**Comment by JB1985** [comment]
That was probably a compiling mistake on my part. Sorry, closed!
