### ISSUE TITLE
Invert Background option is not available on Compact mode

### ISSUE THREAD

**Issue by Ezinnem** [CollaboraOnline/online#9232]
### Describe the Bug
Invert Background option is not available on Compact mode

### Steps to Reproduce
1. Open any file
2. Switch to Compact mode Go to View

### Expected Behavior
Invert Background option is available on Compact mode

### Actual Behavior
Invert Background option is not available on Compact mode

### Screenshots

![preview-Screenshot_from_2024-06-06_16-20-47](https://github.com/CollaboraOnline/online/assets/54344301/f230568e-6e4a-4df4-b1b2-65b9d6d98745)

### Desktop

COOLWSD version: 24.04.4.1 (git hash:  9091043  (E))
LOKit version: Collabora Office 24.04.4.1 (git hash: | fdb5e53 )

**Comment by GulsahKose** [comment]
That is not a bug, We don't see the Invert Background because of we are in light mode. If you switch to dark mode you'll see the item.

**Comment by GulsahKose** [comment]
That is not a bug, We don't see the Invert Background because of we are in light mode. If you switch to dark mode you'll see the item.
