### ISSUE TITLE
calc: drop down for value lists not visible

### ISSUE THREAD

**Issue by himpierre** [CollaboraOnline/online#9250]
### Describe the Bug
It seems the issue from #6986 is back with collabora code 24.0.4.3.

### Steps to Reproduce

1. Open a xlsx file.
2. Click on a cell which usually has a drop down menu
3. Arrow is there but the menu is not droping down

### Expected Behavior
Drop down menu is visible.

### Actual Behavior
No drop down menu.

### Desktop
(Please complete the following information)
 - **Collabora version:** 24.0.4.3
 - **OS and version:** Linux
 - **Browser and version:** Firefox 126 / Chrome 125

cheers! t.

**Comment by timur-g** [comment]
What is your browser resolution, scaling, browser zoom, zoom in Online?

**Comment by Netlantique** [comment]
Hi,
We are having the same problem here. It was working correctly on previous Collabora version.
We also tested on Microsoft Excel the same file and the drop down menu is working correctly.

Resolution : 1920x1080
Browser Zoom: Normal 100%
No zoom on Collabora.

Actual Behavior
The drop down menu flash for 0.1sec then disappear.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop
(Please complete the following information)

Collabora version: 24.04.3.1
OS and version: Windows 10
Browser and version: 
brave [Version 1.66.118 Chromium: 125.0.6422.147 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by himpierre** [comment]
The numbers given here are valid for my setup too. So nothing special.

cheers!

Am 2024-06-12 16:49, schrieb Netlantique:
> Hi,
> We are having the same problem here. It was working correctly on 
> previous Collabora version.
> We also tested on Microsoft Excel the same file and the drop down menu 
> is working correctly.
> 
> Resolution : 1920x1080
> Browser Zoom: Normal 100%
> No zoom on Collabora.
> 
> Actual Behavior
> The drop down menu flash for 0.1sec then disappear.
> 
> Screenshots
> If applicable, add screenshots to help explain your problem.
> 
> Desktop
> (Please complete the following information)
> 
> Collabora version: 24.04.3.1
> OS and version: Windows 10
> Browser and version:
> brave [Version 1.66.118 Chromium: 125.0.6422.147 (Official Build) 
> (64-bit)](https://brave.com/latest/)

**Comment by timur-g** [comment]
I tried with Firefox and Chromium, cell with range or validity, I do nto reproduce. I miss something.

**Comment by Netlantique** [comment]
> I tried with Firefox and Chromium, cell with range or validity, I do nto reproduce. I miss something.

Do you need a example file to test ?

**Comment by timur-g** [comment]
Yes, please.

**Comment by Netlantique** [comment]
> Yes, please.

Here a example file.
You can test on Collabora. If you test the same file on Microsoft Excel, the dropdown menu is working correctly.

Thank you !
[Dropdown-Menu-TEST.xlsx](https://github.com/user-attachments/files/15807766/Dropdown-Menu-TEST.xlsx)

**Comment by timur-g** [comment]
Thanks for the sample. Already NOK in 24.04.2.1, regression. 
Maybe I could not see before as this is about Départements not Departments ... joke :)
Validity List or Range work in other file, not sure what is special about this one.

**Comment by Netlantique** [comment]
> Thanks for the sample. Already NOK in 24.04.2.1, regression. Maybe I could not see before as this is about Départements not Departments ... joke :) Validity List or Range work in other file, not sure what is special about this one.

Perfect ! Thank you !

**Comment by thebearon** [comment]
This is a regression from the following commit:
https://github.com/CollaboraOnline/online/commit/8a0843764b6cafc160f6bcbb9ff941d9c4f9ff4f
https://github.com/CollaboraOnline/online/pull/8878
```
Author:     Gökay Şatır <gokaysatir@collabora.com>
AuthorDate: Mon Apr 29 13:54:23 2024 +0300
Commit:     Gökay Şatır <gokaysatir@gmail.com>
CommitDate: Thu May 9 13:28:54 2024 +0300

    Move DropDownSection into its own file.
```

CC @gokaysatir.

**Comment by eszkadev** [comment]
@gokaysatir  could you please add simple cypress test for it with the fix?

**Comment by thebearon** [comment]
Also, positioning the dropdown on the bottom (where clicking is effective right now) is a reasonable change.

**Comment by b90g** [comment]
I noticed with fields with more than one line/or rather neighbouring field with more than one line the the drop down arrow is positioned at the lower end next to the field but displayed on the top end you can see the difference in libreoffice desktop:


![grafik](https://github.com/CollaboraOnline/online/assets/63392812/cc834d35-9242-443f-b6e4-3eed9607a6e4)


while in collabora:

![grafik](https://github.com/CollaboraOnline/online/assets/63392812/053030b0-c4a8-46f0-bbb1-e686336d66e1)


work around is to know you can click into the blank area underneath the drowdown arrow next to the blue size-dot where the arrow is supposed to be, to have the drop down:

![grafik](https://github.com/CollaboraOnline/online/assets/63392812/9210350b-4e52-4c29-aff9-87a419a15165)



Happends in Firefox 126  & Chromium 126 1920x1080  100%

**Comment by thebearon** [comment]
This has been fixed by #9286.

**Comment by Netlantique** [comment]
Hi,
How can we know on which version this fix will be applied to ?

Thank you !

**Comment by thebearon** [comment]
It's part of 24.04.4-2.
