### ISSUE TITLE
Error: Invalid LatLng object: (NaN, NaN) / Fails with Nextcloud iOS

### ISSUE THREAD

**Issue by SystemKeeper** [CollaboraOnline/online#9295]
### Describe the Bug

Since the latest upgrade opening *.doc/*.docx files fails on iOS device with the Nextcloud app.

Works: Docker 24.04.2.1.1 
Fails: Docker 24.04.3.1.1

### Steps to Reproduce
1. Have Nextcloud (29) with richdocuments (8.4.2) enabled, connected to Collabora Docker 24.04.3.1.1
2. Use the Nextcloud iOS app to open a *.doc/*.docx file (it can be a newly created file!)

### Expected Behavior
Works and opens the document.

### Actual Behavior
Document does not render, in the console I see:

<img width="432" alt="image" src="https://github.com/CollaboraOnline/online/assets/1580193/6892b515-944f-43b5-9c40-d73853669db9">

### Desktop
(Please complete the following information)
 - **Collabora version:** [e.g. 23.05.5.3]
 - **OS and version:** [e.g. Windows 11]
 - **Browser and version:** [e.g. Chrome 114.0]

### Smartphone
(Please complete the following information)
 - **Device:** iPhone 15 Pro
 - **OS:** iOS 17.5
 - **Browser and version:** Nextcloud iOS App

**Comment by thebearon** [comment]
While we investigate this on our end, it would be worth checking this with the latest CODE, which is 24.04.4.2.1 tag on Docker hub (version 24.04.4-2).

**Comment by thebearon** [comment]
This may have been fixed by #9287, which is part of 24.04.4-2. Please confirm.

**Comment by SystemKeeper** [comment]
Can confirm, 24.04.4-2 fixes it, thanks!

**Comment by thebearon** [comment]
Great, thanks for retesting!
