### ISSUE TITLE
Export as PDF not work

### ISSUE THREAD

**Issue by JB1985** [CollaboraOnline/online#9303]
### Steps to Reproduce
1. Open a document
2. Go to "Datei" -> "Exportieren als" -> PDF
3. See error

### Expected Behavior
I expected that I get a PDF Document.

### Actual Behavior
Error, not work!

### Screenshots
![image](https://github.com/CollaboraOnline/online/assets/9932751/36b17e62-bcf5-43b2-bc2f-8324c667cded)

### Desktop
(Please complete the following information)
 - **Collabora version:** 24.04.3-6
 - **OS and version:** Windows 11
 - **Browser and version:** Chrome & firefox (newest version)

### Additional Context

`kit-03389-03389 2024-06-18 09:56:30.408680 +0200 [ kitbroker_008 ] ERR  ToMaster-008: error: cmd=exportas kind=saveasfailed| common/Session.hpp:168
kit-03389-03389 2024-06-18 09:56:30.409177 +0200 [ kitbroker_008 ] ERR  ToMaster-008: CALLBACK_ERROR: {
    "code": "0x20d(Error Area:Io Class:General Code:13) arg1=SfxBaseModel::impl_store <file:\/\/\/tmp\/log%20in_communication.pdf> failed: 0xc10(Error Area:Io Class:Write Code:16) at \/home\/user\/collabora-office\/core\/core\/sfx2\/source\/doc\/sfxbasemodel.cxx:3277 at \/home\/user\/collabora-office\/core\/core\/sfx2\/source\/doc\/sfxbasemodel.cxx:1825",
    "kind": "",
    "cmd": "",
    "message": "General Error.\nGeneral input\/output error."
}
| kit/ChildSession.cpp:3090
wsd-03158-03400 2024-06-18 09:56:30.409189 +0200 [ docbroker_008 ] ERR  ToClient-008: exportas error failure: saveasfailed| wsd/ClientSession.cpp:1751
kit-03389-03389 2024-06-18 09:56:30.409654 +0200 [ kitbroker_008 ] ERR  ToMaster-008: error: cmd= kind= code=0x20d(Error Area:Io Class:General Code:13) arg1=SfxBaseModel::impl_store <file:///tmp/log%20in_communication.pdf> failed: 0xc10(Error Area:Io Class:Write Code:16) at /home/user/collabora-office/core/core/sfx2/source/doc/sfxbasemodel.cxx:3277 at /home/user/collabora-office/core/core/sfx2/source/doc/sfxbasemodel.cxx:1825| common/Session.hpp:162
wsd-03158-03400 2024-06-18 09:56:30.410081 +0200 [ docbroker_008 ] ERR  ToClient-008:  error failure: | wsd/ClientSession.cpp:1751
kit-03297-03297 2024-06-18 09:56:38.373694 +0200 [ kitbroker_004 ] ERR  ToMaster-005: error: cmd=exportas kind=saveasfailed| common/Session.hpp:168
kit-03297-03297 2024-06-18 09:56:38.374299 +0200 [ kitbroker_004 ] ERR  ToMaster-005: CALLBACK_ERROR: {
    "code": "0x20d(Error Area:Io Class:General Code:13) arg1=SfxBaseModel::impl_store <file:\/\/\/tmp\/Stripe%20bypass.pdf> failed: 0xc10(Error Area:Io Class:Write Code:16) at \/home\/user\/collabora-office\/core\/core\/sfx2\/source\/doc\/sfxbasemodel.cxx:3277 at \/home\/user\/collabora-office\/core\/core\/sfx2\/source\/doc\/sfxbasemodel.cxx:1825",
    "kind": "",
    "cmd": "",
    "message": "General Error.\nGeneral input\/output error."
}
| kit/ChildSession.cpp:3090
wsd-03158-03315 2024-06-18 09:56:38.374311 +0200 [ docbroker_004 ] ERR  ToClient-005: exportas error failure: saveasfailed| wsd/ClientSession.cpp:1751
kit-03297-03297 2024-06-18 09:56:38.374784 +0200 [ kitbroker_004 ] ERR  ToMaster-005: error: cmd= kind= code=0x20d(Error Area:Io Class:General Code:13) arg1=SfxBaseModel::impl_store <file:///tmp/Stripe%20bypass.pdf> failed: 0xc10(Error Area:Io Class:Write Code:16) at /home/user/collabora-office/core/core/sfx2/source/doc/sfxbasemodel.cxx:3277 at /home/user/collabora-office/core/core/sfx2/source/doc/sfxbasemodel.cxx:1825| common/Session.hpp:162
wsd-03158-03315 2024-06-18 09:56:38.375240 +0200 [ docbroker_004 ] ERR  ToClient-005:  error failure: | wsd/ClientSession.cpp:1751
kit-03389-03389 2024-06-18 09:56:43.149517 +0200 [ kitbroker_008 ] ERR  ToMaster-008: error: cmd=exportas kind=saveasfailed| common/Session.hpp:168
kit-03389-03389 2024-06-18 09:56:43.150317 +0200 [ kitbroker_008 ] ERR  ToMaster-008: CALLBACK_ERROR: {
    "code": "0x20d(Error Area:Io Class:General Code:13) arg1=SfxBaseModel::impl_store <file:\/\/\/tmp\/log%20in_communication.pdf> failed: 0xc10(Error Area:Io Class:Write Code:16) at \/home\/user\/collabora-office\/core\/core\/sfx2\/source\/doc\/sfxbasemodel.cxx:3277 at \/home\/user\/collabora-office\/core\/core\/sfx2\/source\/doc\/sfxbasemodel.cxx:1825",
    "kind": "",
    "cmd": "",
    "message": "General Error.\nGeneral input\/output error."
}
| kit/ChildSession.cpp:3090
wsd-03158-03400 2024-06-18 09:56:43.150333 +0200 [ docbroker_008 ] ERR  ToClient-008: exportas error failure: saveasfailed| wsd/ClientSession.cpp:1751
kit-03389-03389 2024-06-18 09:56:43.150703 +0200 [ kitbroker_008 ] ERR  ToMaster-008: error: cmd= kind= code=0x20d(Error Area:Io Class:General Code:13) arg1=SfxBaseModel::impl_store <file:///tmp/log%20in_communication.pdf> failed: 0xc10(Error Area:Io Class:Write Code:16) at /home/user/collabora-office/core/core/sfx2/source/doc/sfxbasemodel.cxx:3277 at /home/user/collabora-office/core/core/sfx2/source/doc/sfxbasemodel.cxx:1825| common/Session.hpp:162
wsd-03158-03400 2024-06-18 09:56:43.151046 +0200 [ docbroker_008 ] ERR  ToClient-008:  error failure: | wsd/ClientSession.cpp:1751`

**Comment by JB1985** [comment]
That was probably a compiling mistake on my part. Sorry, closed!

**Comment by diogotcorreia** [comment]
I'm running into the same problem, do you know what the issue was?

**Comment by jazevedo-coll** [comment]
> I'm running into the same problem,

Hi @diogotcorreia what is the

- OS version of the host system
-  Collabora online version that you are using 
- What is your setup? Docker / native package ?

**Comment by diogotcorreia** [comment]
@jazevedo-coll Hey!

I'm using the package from NixOS, so I suspect it's a packaging problem, hence why I was curious what the "compiling mistake" was :)
There is an [issue open in Nixpkgs](https://github.com/NixOS/nixpkgs/issues/218878#issuecomment-2471223335) about this as well, so it's a general problem there.

Either way, here are the details you asked for:
```
COOLWSD version:
24.04.6.1
LOKit version:
Collabora Office 24.04.5.3

NixOS 24.11 (Vicuna) 11415c7
nextcloud 30.0.6.2 - richdocuments 8.5.3
false
```

I'm using a native package, and this is my config:
https://github.com/diogotcorreia/dotfiles/blob/ef70da6198bfb1a432bb48371dba6f0ba0eb061b/hosts/hera/nextcloud.nix#L89-L109

One thing to note is that the package seems outdated in nixpkgs, so my first instinct would be to try to update it 😅

**Comment by rodrigoesborges** [comment]
@JB1985 would you mind sharing the compiling issue you had and the fix, if you found it? Thanks!

**Comment by JB1985** [comment]
> [@JB1985](https://github.com/JB1985) would you mind sharing the compiling issue you had and the fix, if you found it? Thanks!

I am using the CPLinux-LOKit.conf compiling options.

See: https://github.com/LibreOffice/core/blob/master/distro-configs/CPLinux-LOKit.conf
