### ISSUE TITLE
Grammar error on UI: "You has left"

### ISSUE THREAD

**Issue by timar** [CollaboraOnline/online#9316]
![image](https://github.com/CollaboraOnline/online/assets/290614/610d50cc-499a-48b1-acf0-4463f8ffdcdb)

In `browser/src/control/Control.UserList.ts` the following messages are defined:
- userJoinedPopupMessage: _('%user has joined')
- userLeftPopupMessage: _('%user has left')
The %user can be 'You'. This is where the grammar breaks, not only in English, but in many other languages, too.
We need to define a separate message for the 'You' case.

**Comment by Darshan-upadhyay1110** [comment]
@timar this done not seems too hard to fix, can we add an appropriate tag (like `easyhack`) ?

**Comment by timar** [comment]
@Minion3665 fixed this with 794e8b38cfcc0315013e411c9e0b2aef8fed3a36
