### ISSUE TITLE
docker container stop responding

### ISSUE THREAD

**Issue by nadirlouati** [CollaboraOnline/online#9318]
### Describe the Bug
sometimes libreOffice stops responding
the web/admin interface does not open
url:9980 does not return ok
no new lines in the log
docker container is running
memory used 0.8 / 6 GB
when I restart the container, everything returns to normal
how to find the problem ??

### Steps to Reproduce
without a specific scenario. it can happen without any particular logic

### Expected Behavior
remain working

### Actual Behavior
CODE don't respond 

### Desktop
(Please complete the following information)
 - **Collabora version:** 
           COOLWSD 24.04.1.4 / (git hash: [f12ee1f](https://github.com/CollaboraOnline/online/commits/f12ee1f))
           LOKit Collabora Office 24.04.1.4 (git hash: [91ae3cd](https://hub.libreoffice.org/git-core/91ae3cd))
 - **OS and version:** 
           Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-106-generic x86_64)
           Docker version 26.0.0, build 2ae903e
 - **Browser and version:** [e.g. Chrome 114.0]

### Additional Context
ping -t don't show network failure

**Comment by thebearon** [comment]
24.04.1 was the first release version in the 24.04 version, can you please pull the latest CODE Docker image and try again?

**Comment by timur-g** [comment]
No response here, so I will close. 
This should work correctly in 24.04.4-4.

**Comment by nursoda** [comment]
I'm seeing the same behavior with official latest docker image: The cool daemon inside latest docker image seems to be running, yet `curl http://localhost:9980/` inside the container does no longer yield "OK" – was fine before the latest update yesterday.

**Comment by GJSchaller** [comment]
Running into the same issue with the latest image as of December 24th, 2024.  Host is a TrueNAS 24.10 (Electric Eel) system, it was working a few weeks ago, then suddenly stopped.  I've refreshed the stack, tried rolling back to an earlier release of collabora/code, no change - it looks like the collabora container is running, but unresponsive.

**Comment by GJSchaller** [comment]
> Running into the same issue with the latest image as of December 24th, 2024. Host is a TrueNAS 24.10 (Electric Eel) system, it was working a few weeks ago, then suddenly stopped. I've refreshed the stack, tried rolling back to an earlier release of collabora/code, no change - it looks like the collabora container is running, but unresponsive.

This is resolved for me, at least - I noticed that if I browsed to the FQDN:9980 instead of IPaddress:9980, it worked.  I've updated my coolwsd file and Nextcloud, and it's behaving now.
