### ISSUE TITLE
There is unusual spacing between the icons in the mobile view.

### ISSUE THREAD

**Issue by Darshan-upadhyay1110** [CollaboraOnline/online#9320]
### Describe the Bug

![image](https://github.com/CollaboraOnline/online/assets/61383886/3ec1d4c3-2ca4-4f5a-8a73-64c0e038c241)

### Steps to Reproduce
Mobile

1. Go to writer
2. Insert image
3. Select image

**Comment by Darshan-upadhyay1110** [comment]
CC: @Ezinnem @timur-g @bearon

**Comment by timur-g** [comment]
I did not reproduce in Android app.

**Comment by aarsh21** [comment]
i think it exists only on browser
