### ISSUE TITLE
Grey background during loading tiles after switching back from dark mode

### ISSUE THREAD

**Issue by thebearon** [CollaboraOnline/online#9327]
- Open a longer document,
- Switch to dark mode, then switch back to light mode, or just switch to light mode if you were already in dark mode,
- Scroll down.

-> Note how you see grey background at the bottom before the tiles are loaded, instead of the expected white.

COOLWSD version: 24.04.4.2 (git hash: 99ee74b2 (E))
LOKit version: Collabora OfficeDev 24.04.4.2 (git hash: 37e7adc)

Not seeing it in
COOLWSD version: 23.05.13.1 (git hash: 9bb4cb97)
LOKit version: Collabora OfficeDev 23.05.12.1 (git hash: fe8f918)

CC @gokaysatir.

**Comment by Minion3665** [comment]
I believe this to be fixed in https://gerrit.libreoffice.org/c/core/+/169540, which is currently in review

**Comment by Ezinnem** [comment]
The patch is merged now.

Looks good on:
COOLWSD version: 24.04.4.2 (git hash: [8f901ba5](https://github.com/CollaboraOnline/online/commits/8f901ba5) (E))
LOKit version: Collabora Office 24.04.4.2 (git hash: [954c349](https://git.libreoffice.org/core/+log/954c349))

**Comment by Minion3665** [comment]
> The patch is merged now.
> 
> Looks good on: COOLWSD version: 24.04.4.2 (git hash: [8f901ba5](https://github.com/CollaboraOnline/online/commits/8f901ba5) (E)) LOKit version: Collabora Office 24.04.4.2 (git hash: [954c349](https://git.libreoffice.org/core/+log/954c349))

Awesome @Ezinnem!

May you clarify if this also fixed #9338? Thanks!
