### ISSUE TITLE
Grey background during loading tiles after coming back from idled out session

### ISSUE THREAD

**Issue by thebearon** [CollaboraOnline/online#9338]
This might or might not be related to #9327.

- For easier reproducibility, set `per_document.idle_timeout_secs` to something small, eg. `30`,
- When in light mode, open a longer document,
- Switch to a different tab/window, and wait for the session to idle out,
- Switch back, and scroll down quickly.

-> Note how you see grey background at the bottom before the tiles are loaded, instead of the expected white.

COOLWSD version: 24.04.4.2 (git hash: https://github.com/CollaboraOnline/online/commit/99ee74b2c64b26d41f61eda34c08bb3242154b45 (E))
LOKit version: Collabora OfficeDev 24.04.4.2 (git hash: 37e7adc)

Not seeing it in
COOLWSD version: 23.05.13.1 (git hash: 9bb4cb97)
LOKit version: Collabora OfficeDev 23.05.12.1 (git hash: fe8f918)

CC @gokaysatir.

**Comment by Minion3665** [comment]
I believe this to be fixed in [gerrit.libreoffice.org/c/core/+/169540](https://gerrit.libreoffice.org/c/core/+/169540), which is currently in review

**Comment by eszkadev** [comment]
merged, can we test?

**Comment by Darshan-upadhyay1110** [comment]
> I believe this to be fixed in [gerrit.libreoffice.org/c/core/+/169540](https://gerrit.libreoffice.org/c/core/+/169540), which is currently in review

Not reproducible it is fixed in latest version.
