### ISSUE TITLE
Huge offset in dropdown inside "Chart with Pivot Table"

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#9362]
### Describe the Bug

When you have a Chart with Pivot Table data, you get some extra "special dropdowns" which let you sort/filter data.

When clicking open the chart's dropdowns, instead of the filters appearing:

- **right below** the dropdown

it appears:

- **down and to the right**, far away from your selection.

**LO 24.2.4 vs. Collabora 24.04.4**

<img alt="LibreOffice 24 2 4 - Offset in Pivot Table Chart Dropdown Correct" src="https://github.com/CollaboraOnline/online/assets/5774324/1a75d1b2-a7c4-406e-8137-dcdcc29e15a7" width="45%" /> <img alt="Collabora 24 04 4 2 - Offset in Pivot Table Chart Dropdown" src="https://github.com/CollaboraOnline/online/assets/5774324/a7f9bf5f-eb6e-4f6b-b26f-2c4b272815bb" width="45%" /> 

### Steps to Reproduce

In Calc:

0. Open [LO.24.2.4.-.Pivot.Table.Chart.ods](https://github.com/user-attachments/files/16014197/LO.24.2.4.-.Pivot.Table.Chart.ods)
1. Double-Click on Chart to select it.
2. Single-Click on "Fruit" dropdown.

### Expected Behavior

Info appears **directly below** the dropdown.

### Actual Behavior

Info appears far away to the bottom right.

### Desktop

- **Collabora version:** 24.04.4.2
- **OS and version:** Windows 11
- **Browser and version:** Chrome 126.0.6478.127 (Official Build) (64-bit)

Tested on Sharing server:

```
COOLWSD version: 24.04.4.2 (git hash: a5718066 (E))
LOKit version: Collabora Office 24.04.4.2 (git hash: 7fb545b)
Served by: openSUSE Leap 15.5
Server ID: a16ecc5f
```

and tested in:

```
Version: 24.2.4.2 (X86_64) / LibreOffice Community
Build ID: 51a6219feb6075d9a4c46691dcfe0cd9c4fff3c2
CPU threads: 8; OS: Windows 10.0 Build 22631; UI render: Skia/Raster; VCL: win
Locale: en-US (en_US); UI: en-US
Calc: CL threaded
```

### Additional Context

This happened on default 100% Zoom. No idea if Zoom exacerbates this problem, making the "dropdown popup window" appear even further away.

Found during COOL Weekly 172.

**Comment by aarsh21** [comment]
it works fine in the lastest dev version

![image](https://github.com/CollaboraOnline/online/assets/131544056/99325e13-90b0-4e17-9952-b0c1b251f42e)
