### ISSUE TITLE
Pressing "Shift" jumps view to the cursor

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#9363]
### Describe the Bug

Scrolling down the document, then pressing `Shift` jumps you to the cursor.

(I was trying to `Shift+Click` to highlight a large chunk of text/cells, then kept on frustratingly getting "jumped back up".)

### Steps to Reproduce

In Writer or Calc with a "long document":

1. Left-Click in a paragraph/cell.
   - This places cursor somewhere.
2. Scroll down, so cursor is off the screen.
3. Press `Shift` on keyboard.

### Expected Behavior

Collabora to "not do anything"/"not move you anywhere", just like when pressing `Ctrl` key.

### Actual Behavior

Collabora "jumps back up" to where your cursor is located.

### Desktop

- **Collabora version:** 24.04.4.2
- **OS and version:** Windows 11
- **Browser and version:** Chrome 126.0.6478.127 (Official Build) (64-bit)

Tested on Sharing server:

```
COOLWSD version: 24.04.4.2 (git hash: a5718066 (E))
LOKit version: Collabora Office 24.04.4.2 (git hash: 7fb545b)
Served by: openSUSE Leap 15.5
Server ID: a16ecc5f
```

### Additional Context

Found during COOL Weekly 172.

I believe this regression is very recent (within the past few weeks). I do similar steps every week (paste a big chunk of plaintext, then Shift+Click to highlight/format it nicely), and don't remember this "jumping" happening previously.

**Comment by pedropintosilva** [comment]
I confirm, I had this behaviour in today's community meeting with Firefox

**Comment by pedropintosilva** [comment]
cc: @annanazarayan @Ezinnem

**Comment by eszkadev** [comment]
I think it is fixed by: https://github.com/CollaboraOnline/online/pull/9641
