### ISSUE TITLE
Calc: Dark Mode Invert Background option not working as expected for speadsheets

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#9379]
### Describe the Bug
Dark Mode Invert background option not working as expected in Calc. This works fine in Word, where one opens a document in Dark Mode and if text is not readable duse to text set to black instead of automatic, the Invert Background solves that to make teh doc readable. Now in Calc I would expect the same to happen, but while I do see some line turn from black to white, the text and cels in a (for example XLSX) stay all Dark Mode rendering the document hard to read.

### Steps to Reproduce

1. Go to 'Nextcloud' (Dark Mode)
2. Open a document (Make sur eto open Dark mode, or set the mode to Dark after opening)
3. You find some text in a document is near unreadable dus to coller set to black instead of automatic
4. Decide to set Invet background on the View tab. background of the spreadsheed is not turning white as one would expect.

### Expected Behavior
Background of the spreadsheet should turn white

### Actual Behavior

Background of the spreadsheed is not turning white as one would expect.

### Screenshots

![afbeelding](https://github.com/CollaboraOnline/online/assets/37268999/d24572fe-1b79-48e9-bcf5-f5acec6fa42a)

### Desktop

(Please complete the following information)
 - **OS:** Windows 11, latest patches, Dutch
 - **Browser:** Firefox
 - **Version:** 127.0.2 X64

### Server
Nextcloud staging;
COOLWSD version: 24.04.4.2 (git hash: 71b29f27 (E))
LOKit version: Collabora Office 24.04.4.2 (git hash: 399253c)
Served by: openSUSE Leap 15.5
Server ID: 299a4132

Personal Nextcloud environment:
NC 28.0.7
COOLWSD version: 24.04.4.2 (git hash: fbf97e9 (E))
LOKit version: Collabora Office 24.04.4.2 (git hash: 3709158)
Served by: Debian GNU/Linux 12 (bookworm)
Server ID: 1da6896c

### Additional Context

-

**Comment by GulsahKose** [comment]
Thanks for the report. Fixed with : https://github.com/CollaboraOnline/online/pull/9344
