### ISSUE TITLE
In Word read-only mode, do not display navigation bar

### ISSUE THREAD

**Issue by z80412007** [CollaboraOnline/online#9426]
### Describe the Bug
In Word read-only mode, do not display navigation bar
### Steps to Reproduce
1. Hide toolbar
2. Click on the view
3. No response when clicked
### Expected Behavior
In Word read-only mode, display navigation bar
### Actual Behavior
A clear and concise description of what actually happens.
### Desktop
(Please complete the following information)
- **Collabora version:** [23.05.9.3.31]
- **OS and version:** [Windows 11]
- **Browser and version:** [Chrome 114.0]

**Comment by Darshan-upadhyay1110** [comment]
Not reproducible with latest version.

COOLWSD version: 24.04.8.2snapshot(git hash: 77a0aab (E))
LOKit version: Collabora Office 24.04.8.20241009(git hash: ac08496)
Served by: Ubuntu 22.04.5 LTS
Server ID: 25bf5f25
WOPI host:
