### ISSUE TITLE
Calc: Username of a Comment gets lost on Save XLSX

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#9428]
### Describe the Bug

Adding a user Comment to a new XLSX or in an existing XLSX speadsheet document, while saving and closing the document then on reopen the document the name of the user that made the comment gets lost.

Tested this for ODS/ODT/DOCX also, here comments work fine. So seems related to XLSX only so far.

### Steps to Reproduce

1. Create a new XLSX or use an existing XLSX in Nextcloud and open in NC Office/CODE
2. Have some text inh a cell als add a comment to that. Comment shows username of the current user correctly
3. Now save and close the document
4. Reopen the document from Nextcloud in NC Office/CODE
5. Click the comment, the username of the user that made the comment shows Unknown user.

### Expected Behavior
Username of the user that makes a comment should stick in the document.

### Actual Behavior
Username of the user gets lost on document Save.

### Screenshots
Making a comment:

![afbeelding](https://github.com/CollaboraOnline/online/assets/37268999/210e46a4-27aa-4bd2-a7cb-5ef809e7f6aa)

After reopening the document the comment is lost:

![afbeelding](https://github.com/CollaboraOnline/online/assets/37268999/2c594ffa-7900-44af-999e-36fc20d9fbb6)

### Desktop

(Please complete the following information)
 - **OS:** Windows 
 - **Browser:** Firefox
 - **Version:** 127.0.2
 - NC Staging:
COOLWSD version: 24.04.4.2 (git hash: 841923e9 (E))
LOKit version: Collabora Office 24.04.4.2 (git hash: d634731)
Served by: openSUSE Leap 15.5
Server ID: 2a6e8533

Private NC:
COOLWSD version: 24.04.4.2 (git hash: fbf97e9 (E))
LOKit version: Collabora Office 24.04.4.2 (git hash: 3709158)
Served by: Debian GNU/Linux 12 (bookworm)
Server ID: 6c09a284

### Additional Context

-

**Comment by timur-g** [comment]
Yes, this was missing part in XLSX comment implementation, which is a new feature in 24.04.
It was fixed and I think it will be in 24.04.6.
Due to XLSX limitation, only author name is kept, nor date and time.
