### ISSUE TITLE
Calc : Add Data Labels in Charts for Spreadsheets

### ISSUE THREAD

**Issue by Darshan-upadhyay1110** [CollaboraOnline/online#9478]
**Description:**
In Collabora Online (COOL), there is currently no option to display data labels on charts, such as showing the name of the value and its percentage or actual value on pie chart slices. This feature is available in other spreadsheet applications and is essential for users.

**Steps to Reproduce:**
1. Install Collabora server and create .ods document.
2. Create or import a pie chart in a spreadsheet.
3. Attempt to add data labels to the pie chart to display the name and value (percentage or actual value) for each slice.

**Expected Behavior:**
Users should be able to add data labels to pie charts, displaying the name of the value and its percentage or actual value on each slice.
![image](https://github.com/CollaboraOnline/online/assets/61383886/157c825a-b863-4e61-9e92-8cb78c202e46)

**Actual Behavior:**
Collabora Online does not support adding data labels to charts in spreadsheets.

**Request:**
Please add support for data labels in charts within Collabora Online spreadsheets.

Thank you.

**Comment by JJspock** [comment]
I have the same problem here. In other types of graphs, it is impossible to add the values. Just the scale on the sides...
![Screenshot_1](https://github.com/user-attachments/assets/31544b70-0c46-4986-8500-ce9bab7daa97)
