### ISSUE TITLE
Show number of replies in comment wizard

### ISSUE THREAD

**Issue by lpranam** [CollaboraOnline/online#949]
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @lpranam 

### Detailed description and rationale
Recently we started showing comments in wizard in mobile. It would be nice to show the number of replies on the root comment in the writer. This detail will help the user to know if the user needs to open a thread or not.

### Code pointers
most changes will take place inside [this](https://github.com/CollaboraOnline/online/blob/20ba119b5d49febeeac9f8461bbb9c453edc206d/loleaflet/src/control/Control.JSDialogBuilder.js#L1865) block.

Thread related functions can be found in [this file](https://github.com/CollaboraOnline/online/blob/master/loleaflet/src/layer/AnnotationManager.js)

### Additional notes, tips & tricks
There exists no function which gives the length of the comment thread. You'll have to develop it, but there exists various functions which allows you to iterate over the thread so should be easy to develop one method to count the replies.

**Comment by lpranam** [comment]
@Rash419 maybe something of your interest?

**Comment by Rash419** [comment]
Yeah sure :D
