### ISSUE TITLE
admin warning for under-powered systems

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#9491]
It seems some users configure COOL to use far too little hardware, and then get a poor latency experience. 

https://github.com/CollaboraOnline/online/pull/9490

adds a warning in the log for this case; but it would be nice to use @eszkadev 's new admin/warning infrastructure to tell Admin users about this as well.

@Darshan-upadhyay1110  can you add some code pointers to turn this into an easy hack ? =)

**Comment by Darshan-upadhyay1110** [comment]
> far too little hardware

To address this issue, you can refer to the following code pointers:

[DocumentBroker.hpp#L602](https://github.com/CollaboraOnline/online/blob/master/wsd/DocumentBroker.hpp#L602)
[Control.ServerAuditDialog.ts#L25](https://github.com/CollaboraOnline/online/blob/master/browser/src/control/Control.ServerAuditDialog.ts#L25)

To manage admin warnings, you can use the server audit option in the help tab. By looking at examples such as `certwarning` or `isAdmin`, you can easily replicate and create a new property like `poorLatency ` to describe inadequate hardware resources.

As a result, at the end we should be able to see this information in server audit dialog as this
 👉🏼  
![image](https://github.com/user-attachments/assets/6a803144-78d0-4a0c-bab6-93e0abe3ecc0)

**Comment by rparth07** [comment]
> > It seems some users configure COOL to use far too little hardware, and then get a poor latency experience.
> > #9490
> > adds a warning in the log for this case; but it would be nice to use @eszkadev 's new admin/warning infrastructure to tell Admin users about this as well.
> > @Darshan-upadhyay1110 can you add some code pointers to turn this into an easy hack ? =)
> 
> To address this issue, you can refer to the following code pointers:
> 
> [DocumentBroker.hpp#L602](https://github.com/CollaboraOnline/online/blob/master/wsd/DocumentBroker.hpp#L602) [Control.ServerAuditDialog.ts#L25](https://github.com/CollaboraOnline/online/blob/master/browser/src/control/Control.ServerAuditDialog.ts#L25)
> 
> To manage admin warnings, you can use the server audit option in the help tab. By looking at examples such as `certwarning` or `isAdmin`, you can easily replicate and create a new property like `poorLatency ` to describe inadequate hardware resources.
> 
> As a result, at the end we should be able to see this warning information in server audit dialog as this 👉🏼 ![image](https://private-user-images.githubusercontent.com/61383886/348461535-6a803144-78d0-4a0c-bab6-93e0abe3ecc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODM0NzksIm5iZiI6MTcyMTI4MzE3OSwicGF0aCI6Ii82MTM4Mzg4Ni8zNDg0NjE1MzUtNmE4MDMxNDQtNzhkMC00YTBjLWJhYjYtOTNlMGFiZTNlY2MwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA2MTI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMTlmMjllOTYxMTlhNWU1Mzg5ZmU4YmM2M2M4ZDZjMTNkNDhhYzhkNTkwMTFmMmMwYjdlZDdjZDcyZGY2NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-2yGD9jtC_mOKlKKafzaFHW-iJx1x2v6Qq3CKBvCL_E)
> 
> For any questions or any further help, please post your findings here.
> 
> Happy hacking :)

@Darshan-upadhyay1110 Can I work on this issue?

**Comment by rparth07** [comment]
Hi, 
I am currently working on the issue regarding insufficient hardware configuration and making the necessary code changes. However, I am unsure about the correct link to include for the hardware requirements documentation.
Could you please provide the appropriate URL, If any?

**Comment by Darshan-upadhyay1110** [comment]
> Hi, I am currently working on the issue regarding insufficient hardware configuration and making the necessary code changes. However, I am unsure about the correct link to include for the hardware requirements documentation. Could you please provide the appropriate URL, If any? cc: @Darshan-upadhyay1110 @mmeeks

 @rparth07  It's amazing that you have almost completed this improvement. Here is the SSK information to set max concurrency thread for performance https://sdk.collaboraonline.com/docs/installation/Configuration.html?highlight=thread#performance. Let me know for any further questions 
 
 Thanks,
 Darshan

**Comment by rparth07** [comment]
Thanks @Darshan-upadhyay1110 created PR :)
