### ISSUE TITLE
Impress: Textbox blows up in size in CODE not in LibreOffice

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#9537]
### Describe the Bug
I've a PPTX presentation that shows fine in LibreOffice 24.8.0.1 an MS Powerpoint, but when opening it in CODE some "nested" Textboxes blow up in size. The PPTX can be downloaded from https://aka.ms/cspmasterscopilotsalesppt 

### Steps to Reproduce

1. Go https://staging-perf.eu.collaboraonline.com/nextcloud/
2. Upload https://aka.ms/cspmasterscopilotsalesppt 
3. Open the presentation in  CODE
4. Scroll down to slide 2 (or like slide 61, 22, 37)
5. You see the object "TextBox 3" is floating outside the bordered background object "Rectangle:  Top Corners Rounded 9" that it is supposed to be visible within

### Expected Behavior
Text should be visible within the area 

### Actual Behavior

Somehow the TextBox "blows up" and spills over the Rectangle beneath it and in which area it's supposed to be visible within.

### Screenshots
CODE:
![afbeelding](https://github.com/user-attachments/assets/745ec223-1751-47e5-baae-3cc8f84d6b0f)

LibreOffice:
![afbeelding](https://github.com/user-attachments/assets/b346e888-a184-4807-a622-2003988708bd)

PowerPoint:
![afbeelding](https://github.com/user-attachments/assets/58e9fe55-3d35-48fb-80d3-d5c38e471308)

### Desktop

(Please complete the following information)
 - **OS:** Windows 11, Dutch, latest patches
 - **MS Office:** MS Office 365, latest patches
Microsoft® PowerPoint® voor Microsoft 365 MSO (Versie 2406 Build 16.0.17726.20078) 64 bits 
 - **LibreOffice:** LibreOffice 24.8.1.0.1
Version: 24.8.0.1 (X86_64) / LibreOffice Community
Build ID: 6fd6cae02baed1e82d14ed2da1f2458092354dab
CPU threads: 16; OS: Windows 11 X86_64 (10.0 build 22631); UI render: Skia/Raster; VCL: win
Locale: nl-NL (nl_NL); UI: nl-NL
Calc: threaded

- ** CODE ** Staging Perf
COOLWSD version: 24.04.5.2 (git hash: aebb43f4 (E))
LOKit version: Collabora Office 24.04.5.2 (git hash: b57fd97)
Served by: openSUSE Leap 15.5
Server ID: a733cd2a

### Smartphone
-

### Additional Context
-

**Comment by timur-g** [comment]
CODE 24.04 is based on LO 24.2. Possible changes in 24.8 are not automatically backported, only some specific are.

**Comment by sebastiaanveld** [comment]
Hi @timur-g, is COOL based on LO or CO+fixes as I was assuming based on the blogs that a lot of that code is already in CO and backported to LO Master (to be released in the next major update). Mabe I just hit an in-between-release issuer here:)

**Comment by timur-g** [comment]
COOL 24.04 is based on Core/Desktop Collabora Office 24.04 which is LO 24.2 + some selected fixes, but not all from 24.8. 
For example, if fix from 24.8 is backported to 24.2 then it will also be in 24.04, while in special cases otherwise.

If you have access to MSO, can you please extract single slide and attach here? PPT is 445 MB and slow to download.

**Comment by timur-g** [comment]
I checked this and it is not a bug. 
It is missing Segoe UI font that you have in Windows, presumably from MSO, so it opens fine there. 
CODE is using Linux fonts and there you do not have it, and obviously replacement font is not of proper metrics.
