### ISSUE TITLE
Save "Invert Background" preference in JS storage

### ISSUE THREAD

**Issue by Rash419** [CollaboraOnline/online#9538]
### Describe the Bug
Save "Invert Background" state in js storage

### Steps to Reproduce
1. `View` -> `Dark Mode`
2. You will see `Invert Background` button
2. Click you will see document background becomes light
3. Reload the document it will reset to dark

### Expected Behavior
It should save the  `Invert Background` preference on client side

### Actual Behavior
It doesn't save the `Invert Background`, resets on document reload

**Comment by Minion3665** [comment]
This was mostly fixed in https://github.com/CollaboraOnline/online/pull/9652, but I have an additional pull request to fix it for calc here: https://github.com/CollaboraOnline/online/pull/9697
