### ISSUE TITLE
Insert Special Character dialog scrolling problem

### ISSUE THREAD

**Issue by eszkadev** [CollaboraOnline/online#9559]
### Steps to Reproduce
1. Go to Writer
2. Click on Inser Special Character
3. Try to scroll characters

### Expected Behavior
Smooth scrolling, possible to go to the next page

### Actual Behavior
Cannot scroll, size of the scrollable frame bigger than content...

### Desktop
(Please complete the following information)
 - **Collabora version:** 24.04.5.2
 
 Something is wrong with `updateSize` method: https://github.com/CollaboraOnline/online/blob/07964546be45a050e320a2d27a474ef54b42cfb5/browser/src/control/jsdialog/Widget.ScrolledWindow.js#L95
 
Regression from https://github.com/CollaboraOnline/online/commit/5b03c12
cc @meven

**Comment by meven** [comment]
Fixed with https://github.com/CollaboraOnline/online/pull/9926
