### ISSUE TITLE
Calc: cell insert mode caret not disappearing

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#9571]
### Describe the Bug
I have been experiencing (on master HEAD on https://github.com/CollaboraOnline/online/commit/5b65c75ccb5b80bf0f7cd6ce52a636b70cf967cc ) cypress fails and I saw the same fail locally when "make -C cypress_test run-desktop spec=calc/statusbar_spec.js". It fails on "it('Text editing mode.', function()". I have repeated the steps in that function manually and I can reproduce the issue.

### Steps to Reproduce
1. double clicking a cell
2. It correctly  changes the "#InsertMode" value to "Insert"
3. Go tot he formula bar and click on it
4. Press the enter key
5. The status badge remains with value "Insert" for some moment until finally switches to the expected "Insert mode: inactive"

### Videos

Also notice, that the caret remain visible and doesn't change

#### master online

https://github.com/user-attachments/assets/0a8fca18-79ce-434e-a36b-2fee665f3318

#### LO

https://github.com/user-attachments/assets/15b935ad-9dac-4203-b07c-4062279b8233

**Comment by pedropintosilva** [comment]
I also sometimes see weird cell value:

![image](https://github.com/user-attachments/assets/2f03d634-b2e9-4a29-9865-2aac3501a6ed)

**Comment by pedropintosilva** [comment]
```js
cy:command ✔  find	#sc_input_window.formulabar
          cy:log ✱  << documentChecks - end
          cy:log ✱  << loadDocument - end
          cy:log ✱  << setupAndLoadDocument - end
      cy:command ✔  cGet	#InsertMode
      cy:command ✔  assert	expected **<div#InsertMode.jsdialog.ui-badge.insert-mode->** to have text **Insert mode: inactive**
          cy:log ✱  >> dblClickOnFirstCell - start
          cy:log ✱  >> clickOnFirstCell - start
          cy:log ✱  Param - firstClick: false
          cy:log ✱  Param - dblClick: true
      cy:command ✔  cGet	#map
      cy:command ✔  assert	expected **<div#map.leaflet-container.notebookbar-opened>** to have property **length**
      cy:command ✔  assert	expected **<div#map.leaflet-container.notebookbar-opened>** to have a length of **1**
      cy:command ✔  cGet	body
      cy:command ✔  click	59, 185
      cy:command ✔  dblclick	59, 185
      cy:command ✔  cGet	.cursor-overlay .blinking-cursor
      cy:command ✔  assert	expected **<div.leaflet-cursor.blinking-cursor>** to be **visible**
      cy:command ✔  cGet	input#addressInput-input
      cy:command ✘  assert	expected **<input#addressInput-input.ui-edit.formulabar.jsdialog>** to have property **value** with the value **A1**, but the value was **A1:A1048576**
      cy:command ✔  fail:	
                    Test failed: integration_tests/desktop/calc/statusbar_spec.js / Statubar tests. / Text editing mode.
```

**Comment by pedropintosilva** [comment]
cc @Ezinnem @annanazarayan @jazevedo-coll

**Comment by pedropintosilva** [comment]
this is still happening today , staging eu perf

**Comment by Ezinnem** [comment]
Seen on:

COOLWSD version: 24.04.5.3 (git hash: [31292530](https://github.com/CollaboraOnline/online/commits/31292530) (E))
LOKit version: Collabora Office 24.04.5.2 (git hash: [7a2ac2d](https://git.libreoffice.org/core/+log/7a2ac2d))

**Comment by gokaysatir** [comment]
https://github.com/CollaboraOnline/online/issues/9571

**Comment by eszkadev** [comment]
@Ezinnem could be tested now, fix is merged
