### ISSUE TITLE
perf: invalidation overlay handling is horribly slow

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#9616]
Ctrl-Alt-Shift-D - and enable "Tile Invalidations" - and when you have lots of users using calc - and lots of invalidations (10's per second) of multiple users typing, we end up with a totally bogged down firefox, and an unusable experience.

Also - not seeing any invalidations rendered ;-)

Firefox profile is here:

https://share.firefox.dev/3Wh3OiB

It shows that all the time is spent in adding and removing canvas sections 

![image](https://github.com/user-attachments/assets/edfba7e9-728c-4d08-b8c1-b0ec918e4fcf)

I would imagine that having a single section with a list of things to render might be more helpful.

Then again - it seems deeply concerning that sections render as they are adjusted. I would expect all rendering to occur in a single pass at the end of the slurped message emission:

			if (this._map._docLayer) {
				// Resume with redraw if dirty due to previous _onMessage() calls.
				this._map._docLayer.resumeDrawing(true);
			}
			// Let other layers / overlays catch up.
			this._map.fire('messagesdone');

Would suggest that we should not be doing drawing here anyway - surely (!?) at least until resumeDrawing is called or 'messagesdone' is emitted.

What's up there ? =)

**Comment by gokaysatir** [comment]
https://github.com/CollaboraOnline/online/pull/9809
