### ISSUE TITLE
perf: connection re-use ...

### ISSUE THREAD

**Issue by mmeeks** [CollaboraOnline/online#9621]
When we receive incoming connections - we serve a single request - and then shut them down. This can waste lots of latency in terms of socket setup and shutdown - particularly with SSL; this is often hidden by a proxy of course, but it would be nice to not have to handshake again to serve javascript & UI images.

So - we should fix this - at least for the FileServer use-case.

git grep -20 handleFaviconRequest

Will show you code pointers for how this happens; of course:

    HttpHelper::sendFileAndShutdown(socket, faviconPath, response);

Is the culprit that we should probably keep; if we get an error or a malformed request on a socket we should shut it down - to hand the latency back to the bad actor I think ;-)

But I guess we need another method that will not add the Connection: Close, and ensure the socket ends up back in a good state for handling the next request - hopefully not horribly hard.

**Comment by mmeeks** [comment]
As a bonus - we should really remove the Poco message parsing code:

    Poco::MemoryInputStream startmessage(&socket->getInBuffer()[0], socket->getInBuffer().size());

and instead remove our Poco dependency; we should re-use @Ashod 's net/HttpRequest.hpp classes I expect to store the headers. There is a http::Request::readData() that should do lots of this for us I think.

Unit tests required of course. Long term we want to loose the Poco dependency of course.

Sven - would be a good one for you too I think =)

**Comment by sgothel** [comment]
Besides review and discussion, the replacement of Poco http request message parsing
starting with Ash's net/HttpRequest .. is also on the TODO.

I started with wrong unit test derived from UnitWOPIFileUrl,
this patch uses UnitSession and covers document + favicon download 
while keeping the connection/socket alive.

**Comment by mmeeks** [comment]
And - of course; it turns out that this is a nice-to-have; but the vast majority of our file server doesn't go through this method I think =)

See:

 void FileServerRequestHandler::handleRequest(const HTTPRequest& request,
                                             const RequestDetails& requestDetails,
                                             Poco::MemoryInputStream& message,
                                             const std::shared_ptr<StreamSocket>& socket,
                                             ResourceAccessDetails& accessDetails)

Which is where the real file-serving code-path is for most of what we send - prolly should focus on that as well =)
