### ISSUE TITLE
Collaborative editing - Other users get the effect of Invert Background

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#9626]
Open a odt in about two users. Switch to Dark mode in both users
In One user, select the Invert Background

Notice that the background is equally changed for all users.

Expected: The background is switched for only the user

Noticed in:
COOLWSD version: 24.04.4.2 (git hash: fbf97e9 (E))
LOKit version: Collabora Office 24.04.4.2 (git hash: 3709158)

**Comment by Minion3665** [comment]
I've got something WIP for this here: https://gerrit.libreoffice.org/c/core/+/171045

---

For your convenience, here is that commit's message

> WIP: fix separation for inverted backgrounds
> 
> In this commit...
> - [x] Refactor pixel assertion tests so assertion failure error messages are more helpful
> - [x] Write a test for inverted background separation
> - [x] Make inverted backgrounds give a separate view ID
> - [ ] Make inverted backgrounds correctly load on rejoin
> - [ ] Fix bug where inverted backgrounds will need 2 toggles to change when switching away from previously-set state, even on different views...
> - [ ] Write a better message than this ;)
> 
> Change-Id: I0aed702185e642f631854b1f8234355c9e69ff6e

---

[Capture vidéo du 2024-07-25 16-16-53.webm](https://github.com/user-attachments/assets/19ba4b3d-2de6-46bf-a376-0043c4d779ca)

**Comment by timur-g** [comment]
This should be resolved in 24.04.6 with Core patches and https://github.com/CollaboraOnline/online/pull/9652
