### ISSUE TITLE
Calc: Invert Background does not alter the background color of cells

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#9627]
Changing of the cell background when "Invert Background" is selected in Calc.

Steps:

1. Open .ods file. Switch to Dark mode
2. Select "Invert Background".

| note | Screen cast |
| -------| ---------------- |
| Notice that the text color in the cells changes, but the background color of the cells does not change | [Screencast_from_18-06-2024_07_25_11.webm](https://github.com/user-attachments/assets/a6702c46-10da-4faf-a8b8-5d471589b441) | It works better in writer | [Screencast_from_20-06-2024_11_48_53.webm](https://github.com/user-attachments/assets/8c28556a-22c8-4151-aec0-0b96180075c1) |

**Comment by pedropintosilva** [comment]
a fix got in https://github.com/CollaboraOnline/online/pull/9344 by @GulsahKose 

but @timur-g reported:

| 1st user | ![timur1](https://github.com/user-attachments/assets/d58dc89c-1784-4c2e-8666-1892b99ab9c0) | change light OK | ![timur2](https://github.com/user-attachments/assets/39634031-75fe-46eb-8842-2e2ac4a1fb70) | 1st dark, 2nd NOK | ![timur3](https://github.com/user-attachments/assets/c6febbf0-eec8-495e-a047-14882eb62aa3) | light OK | ![timur4](https://github.com/user-attachments/assets/cc524702-968f-4748-996e-a4c854e4e523) | 1st light, 2nd OK | ![timur5](https://github.com/user-attachments/assets/75d7778a-e584-470a-9ebd-456a66a9f996) | light NOK | ![timur6](https://github.com/user-attachments/assets/6f308083-9613-4d5a-8d71-6a0c264cca51)

This is improved and works for single user. While additional users are separated, it does not seem well, as shown in screenshots of the same file open by 2 users, also tested with 3.

**Comment by timur-g** [comment]
Fully fixed in 24.04.6. Ref https://github.com/CollaboraOnline/online/pull/9697.
