### ISSUE TITLE
Impress: Invert Background does not invert slide pane thumbnails

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#9628]
Reported by @timur-g 

In 24.04 was introduced Invert Background. In Impress, it does not seem to propely invert slide pane thumbnails.

| sample | before | on | off |
| ------ | ------ | -- | --- |
[Dark mode test.odp](https://github.com/user-attachments/files/16388598/Dark.mode.test.odp) | ![image1](https://github.com/user-attachments/assets/ed80ea77-fa8e-4ce2-a3c7-758a53b67a00) | ![image2](https://github.com/user-attachments/assets/bffe3621-8bf7-41ca-a255-ad1015d44299) |  ![image3](https://github.com/user-attachments/assets/b25dd3df-8367-4996-9e8a-47d6f5648b7e) |

**Comment by timur-g** [comment]
Fixed in 24.04.6.3
