### ISSUE TITLE
Add Invert Background button in mobile view main toolbar

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#9630]
Originally reported by @timur-g 

Now we have Android app working (as snapshot of 24.04, not released yet) and new Invert Background button, available in Dark mode (of CODE, not Android). 
This is enhancement proposal to have Invert Background button in mobile view in the main toolbar, near by Menu and Comments up right. 
That would help view older documents whih may be with black fonts. 
Changing mode needs a few clicks and presumably is not needed for menu, but for main document content.

**Comment by sebastiaanveld** [comment]
Such button would be nice in the IOS App too:)

**Comment by pedropintosilva** [comment]
@sebastiaanveld it will be : )
