### ISSUE TITLE
Insert comment box looks odd in dark mode

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#9631]
Originally reported by @jazevedo-coll 

![image](https://github.com/user-attachments/assets/3e618b1a-384f-4624-bd89-f5d104fd6ebe)

COOLWSD version: 24.04.4.5snapshot (git hash: eb91527) 
LOKit version: Collabora Office 24.04.4.20240711 (git hash: c16803a) 
Served by: Ubuntu 22.04.4 LTS Server ID: cf49b7f3

Steps to reproduce.

Switch to dark mode on the document.
insert a comment
Fill out the comment and save
Return to the comment and then it is normal

This happens on both Firefox and chromium

**Comment by thebearon** [comment]
I believe this can be closed after the fixes.
