### ISSUE TITLE
Dark mode does not set light text in read-only marked document

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#9632]
Originally reported by @timur-g 

Dark mode was fixed for read-only shared document #7888 with https://github.com/CollaboraOnline/online/pull/7906. it may open Dark or Light, depending on COOL. But mode change does not work.

Mode change is still NOK for read-only marked and so opened document, sample from:

![image](https://github.com/user-attachments/assets/31c55687-40dd-40d5-85b2-6d4dbc658f85)

**Comment by Darshan-upadhyay1110** [comment]
@timur-g for read-only mode it works fine can you please explain a bit more is there any specific thing you did, and then it was not working ?

[Screencast from 2024-07-26 18-04-33.webm](https://github.com/user-attachments/assets/3a21ceb8-1feb-4e60-9ffa-f681ab4448c0)

**Comment by timur-g** [comment]
As noted in the OP, this is not about read-only from WOPI, it is about read-only marked let's say XLSX from MSO.

**Comment by Darshan-upadhyay1110** [comment]
> As noted in the OP, this is not about read-only from WOPI, it is about read-only marked let's say XLSX from MSO.

I see I get it now . thanks @timur-g
