### ISSUE TITLE
[UI] String for entry "PDF Document (.pdf) as..." (tab File>Download) does not match the action

### ISSUE THREAD

**Issue by cornouws** [CollaboraOnline/online#9707]
### Describe the Bug
On the tab File>Download, the entry "PDF Document (.pdf) as..." opens the PDF Options dialog
It does not offer to enter a different name for the file.
The intention of the string of course is to differentiate with the direct export to PDF that is right above: "PDF Document (.pdf)" 

I suggest considering
-> "PDF (.pdf) with options"

COOLWSD version: 24.04.5.4snapshot (git hash: 7bfed20)
LOKit version: Collabora Office 24.04.5.20240731 (git hash: 8b60b23)
Served by: Ubuntu 22.04.4 LTS
Server ID: 8f3866cc

**Comment by pedropintosilva** [comment]
Thanks for reporting. I see how `as...` can be perceived as renaming but the ellipsis are very useful to visually signal the user that it will be a 2-step process. Furthermore the button does what it says Download > PDF Document (.pdf) as... :
* as Hybrid PDF (embed ODF file)
* as a form
* as a tagged PDF (add document structure)
* as an archival (PDF/A, ISO 19005)
* etc
