### ISSUE TITLE
Firefox Calc Rendering cursed

### ISSUE THREAD

**Issue by tatrapikao** [CollaboraOnline/online#9719]
### Describe the Bug
two cells blurred - else it is what i see when opening this specific Document in Firefox. 
![grafik](https://github.com/user-attachments/assets/ec8b5122-6acc-407b-9956-1fdf820800f5)
 ~400 rows / two sheets
Chrome does fine.
![grafik](https://github.com/user-attachments/assets/35c1b252-ee07-41a8-8b42-ad662039c72a)

### Desktop
(Please complete the following information)
 - **Collabora version: 24.04.5.1
 - **OS and version: Ubuntu 24.04
 - **Browser and version: 128.0.3 snap

**Comment by timur-g** [comment]
If that is reproducible, please make minimal sanitized sample and attach here.
