### ISSUE TITLE
UI defaults not applied

### ISSUE THREAD

**Issue by juliushaertl** [CollaboraOnline/online#9727]
### Describe the Bug

With the current code build and master branch settings handed over by integrators through ui_defaults are not applied.

One example is the saveAsMode that we send over in richdocuments

### Steps to Reproduce

1. Send a ui_default setting along the request to browser.html

### Expected Behavior

The setting is picked up

### Actual Behavior

It is not working

## Versions
productVersion: 24.04.6.1
productVersionHash: 8ec5fda

### Additional Context

Digging into it a bit this seems to have been caused by https://github.com/CollaboraOnline/online/pull/9442 where just inserting the raw json into the data-ui-defaults attribute results in the first `"`from the json cosing the attribute:

https://github.com/CollaboraOnline/online/blob/07f903660df88e3e03dcae72b56577fae70efd5e/browser/html/cool.html.m4#L250
![image](https://github.com/user-attachments/assets/1e17a20d-f56f-4250-80de-b489cf6a0b1b)
![image](https://github.com/user-attachments/assets/ba4e23b8-f191-4407-924e-6398f702ab7f)

**Comment by gokaysatir** [comment]
@juliushaertl hello, thank you again for the heads up. I prepared a fix. Can you have a look whenever you can have time? I also tested and it seems to work normal locally.

**Comment by gokaysatir** [comment]
https://github.com/CollaboraOnline/online/issues/9727

**Comment by gokaysatir** [comment]
I think we can close this one now.
