### ISSUE TITLE
Unwanted synchronous layout for the full document in Writer after a full-document invalidation

### ISSUE THREAD

**Issue by vmiklos** [CollaboraOnline/online#9735]
### Describe the Bug

Once some action invalidates all pages in Writer in LOK mode, we calculate the entire layout synchronously, which results in a visible lag.

### Steps to Reproduce
1. Open 
[scratch.odt](https://github.com/user-attachments/files/16539294/scratch.odt)
2. Go to the second, numbered paragraph in the document.
3. Paste some plain text, e.g. a URL from an other tab of the browser.

### Expected Behavior

Can see the pasted text after a little delay.

### Actual Behavior

Can see a significant lag, about 274 ms delay for me locally.

### Additional Context

The scope of this issue is not that we need a full-doc layout calc, the point is that we should first do the visible part, render tiles and only then do the rest of the layout, if possible.

**Comment by vmiklos** [comment]
https://gerrit.libreoffice.org/c/core/+/171660 is now pending CI to fix this.

**Comment by vmiklos** [comment]
The above is now in.

**Comment by vmiklos** [comment]
Some debug resources:

- If you want to measure idle layout, the above doc is useful, as it has 300 pages, so the cost of layout is not close to zero. An other useful bugdoc is [3pages.odt](https://github.com/user-attachments/files/16561947/3pages.odt), which allows debugging the idle layout. The typical case is that the first page is visible, so you want to lay that out instantly, and the remaining two pages are OK to layout only later, as those are not inside the visible area.

- If you want to verify the state of the pages, this is handy:

```diff
diff --git a/sw/source/core/layout/layact.cxx b/sw/source/core/layout/layact.cxx
index c217ded44514..5b45fca7ba0d 100644
--- a/sw/source/core/layout/layact.cxx
+++ b/sw/source/core/layout/layact.cxx
@@ -468,6 +468,19 @@ static void unlockPositionOfObjects( SwPageFrame *pPageFrame )
 
 void SwLayAction::InternalAction(OutputDevice* pRenderContext)
 {
+    SAL_DEBUG("SwLayAction::InternalAction start");
+    comphelper::ScopeGuard g(
+        [this]
+        {
+            std::cerr << "debug, SwLayAction::InternalAction end: idle is " << IsIdle();
+            for (SwFrame* pFrame = m_pRoot->Lower(); pFrame; pFrame = pFrame->GetNext())
+            {
+                SwPageFrame* pPage = pFrame->DynCastPageFrame();
+                std::cerr << ", page " << pPage->GetPhyPageNum() << " InvalidContent is " << pPage->IsInvalidContent();
+            }
+            std::cerr << std::endl;
+        });
+
     OSL_ENSURE( m_pRoot->Lower()->IsPageFrame(), ":-( No page below the root.");
 
     m_pRoot->Calc(pRenderContext);
```

Its typical output is like this:

```
debug:3530:3530: SwLayAction::InternalAction start
debug, SwLayAction::InternalAction end: idle is 0, page 1 InvalidContent is 0, page 2 InvalidContent is 1, page 3 InvalidContent is 1
debug:3530:3530: SwLayAction::InternalAction start
debug, SwLayAction::InternalAction end: idle is 1, page 1 InvalidContent is 0, page 2 InvalidContent is 0, page 3 InvalidContent is 0
```

I.e. you can see how the first pass is non-idle and calculates the first visible page, and the second pass calculates the remaining pages.

**Comment by vmiklos** [comment]
A related problem is that while we know do a short sync and a longer async layout, we still do the first PaintTile() after the longer async layout. Steps to fix this:

- https://gerrit.libreoffice.org/c/core/+/171860 for co-24.04 adds an API to signal that async layout should pause, as we have tiles to render (input to process in general)
- https://gerrit.libreoffice.org/c/core/+/171885 for master uses this new API for the Writer layout (still to be backported)
- the branch at https://github.com/collaboraonline/online/commits/private/vmiklos/anyinput gives you an idea how to use the new API on the online side (work in progress)

**Comment by vmiklos** [comment]
With https://gerrit.libreoffice.org/c/core/+/171950 (still needs backporting), the online.git anyinput branch passes the online.git C++ tests for me. Next is to see what cypress tests have to say.

**Comment by vmiklos** [comment]
https://github.com/CollaboraOnline/online/pull/9896 merges the above branch into master.

**Comment by mmeeks** [comment]
https://github.com/CollaboraOnline/online/pull/10118 is related =)

**Comment by eszkadev** [comment]
hmm, this sounds like it could be also related to: https://github.com/CollaboraOnline/online/issues/9013#issuecomment-2373733597

@GulsahKose could you check?
