### ISSUE TITLE
Cursor gets bigger at every cell

### ISSUE THREAD

**Issue by xavi-GH** [CollaboraOnline/online#9742]
### Describe the Bug
Cursor gets bigger at every new edited cell

### Steps to Reproduce
1. create a cell with  "text" 
2. copy it in at least 6 cells
3. edit each cell
4. the cursor gets bigger

### Expected Behavior
the cursor size should not increase

### Actual Behavior
it increases at every new edited cell

### Screenshots

https://github.com/user-attachments/assets/63aa3be5-1e83-41e9-998c-75716334608b

### Desktop
 - **Collabora version:**  24.04.4.2
 - **OS and version:** debian bookworm
 - **Browser and version:** Firefox 115

**Comment by thebearon** [comment]
This was a regression from the following commit:
https://github.com/CollaboraOnline/online/commit/ae20224fa7a8a6918e6b461f79278106f1714895
https://github.com/CollaboraOnline/online/pull/8654
```
Author:     Szymon Kłos <szymon.klos@collabora.com>
AuthorDate: Fri Mar 29 07:38:16 2024 +0100
Commit:     Szymon Kłos <eszkadev@gmail.com>
CommitDate: Fri Mar 29 21:55:23 2024 +0100

    Improve accuracy of Util.ScrollableBar
```

And has been fixed in 24.04.5 by #9332.
