### ISSUE TITLE
Remove "Hide Menubar" Option from View Tab in read only mode

### ISSUE THREAD

**Issue by Darshan-upadhyay1110** [CollaboraOnline/online#9746]
Description: Hiding the menubar in read-only mode makes it difficult to revert to the normal view. This option should be hidden in read-only mode.

![image](https://github.com/user-attachments/assets/a7528dd4-7b41-43fd-b0f1-034d1454b2f4)

**Comment by CodingwithKetan** [comment]
I’d like to work on this issue. Could you please assign it to me?

**Comment by Darshan-upadhyay1110** [comment]
> I’d like to work on this issue. Could you please assign it to me?

@CodingwithKetan Sure. Thanks :)

**Comment by Darshan-upadhyay1110** [comment]
Hello @CodingwithKetan any luck here ?

**Comment by CodingwithKetan** [comment]
> Hello @CodingwithKetan any luck here ?

Hi @Darshan-upadhyay1110 ,

I’m currently diving into the code structure and flow of control to get a better understanding. I’m reviewing the architecture and how different components interact with each other. This is taking some time, but I’m making progress and will update you once I have a clearer picture and the next steps.

Thanks for your patience!
