### ISSUE TITLE
Add toggle `Show menubar` icon option in compact view

### ISSUE THREAD

**Issue by Darshan-upadhyay1110** [CollaboraOnline/online#9749]
In the top toolbar of compact view, there should be an option/icon to toggle the menubar. The {type: 'button', id: 'fold', img: 'fold'} from Control.TopToolbar.js could be used for this.
 
 Please check in version 23.05, it was like this in image below.
 
 
![image](https://github.com/user-attachments/assets/7e6f094c-a323-4f53-906c-58855c073c9a)

This option will help to toggle menubar.

**Comment by Darshan-upadhyay1110** [comment]
Code pointers :

As I am to go through the code, i found some code pointers that can help here....

- Checkout the file Control.topToolbar.js file and find out why `fold` icon is not enabled ( hint : if you inspect in dev tools the `fold` icon element is there, but it had class `hidden`)
- add missing entry and all will start to work again 😉 

Also there can a new problem you will face after fixing this. (hint: overlapping images ), which is also easy to solve

**Comment by CodingwithKetan** [comment]
Hi @Darshan-upadhyay1110, I'm interested in contributing to it. I wanted to check if anyone else is currently working on it. If not, could you please assign it to me?
