### ISSUE TITLE
Calc: Function Wizard: broken UI

### ISSUE THREAD

**Issue by bayramcicek** [CollaboraOnline/online#9770]
### Describe the Bug

- Function Wizard: some button(s), labels and checkbox(es) are mis-aligned and scroll bar behaves strange:

https://github.com/user-attachments/assets/ed0f3175-2aff-4e90-839b-ab3c5d977fb2

---

- formula wizard doesn't show the input fields (Szymon)

![formulawizard](https://github.com/user-attachments/assets/cae4262f-bc9d-4b55-b7cf-70f6e96a544a)

### version

COOLWSD version: 24.04.6.1 (git hash: ed4edcc3)
LOKit version: Collabora Office 24.04.6.1 (git hash: 5797d70)
Served by: Manjaro Linux
Server ID: e9966fd2

**Comment by eszkadev** [comment]
This might be related to the: https://github.com/CollaboraOnline/online/issues/9559
Which is regression from https://github.com/CollaboraOnline/online/commit/5b03c12

**Comment by meven** [comment]
Fixed with https://github.com/CollaboraOnline/online/pull/9926
