### ISSUE TITLE
copy/duplicate sheets

### ISSUE THREAD

**Issue by photoalex** [CollaboraOnline/online#9787]
### Describe the Bug
I'm pretty sure I could this last time I used this app

### Steps to Reproduce
Tap and hold sheet tap > copy sheet

### Expected Behavior
Creates a copy of a sheet

### Actual Behavior
No such option but i'm sure I did it at some point. Am I missing something?

### Smartphone
 - android 13
- collabora 23.05.5.2
- 
### Additional Context
Maybe I was dreaming but such an action would seem quite trivial...

**Comment by Minion3665** [comment]
Hello! Thanks for reporting :)

I'm not sure we have ever had this option in the mobile app, but we definitely have it in desktop and tablet views, and I agree that we should make it available for mobile. This sounds trivial and I was as surprised as you to realize that it wasn't there!

---

We have an upcoming Android release - 24.04.5.4 - which it's unfortunately a little too late to make this in time for, however I will aim to do this by the Android release after that.

I'll keep you posted in this issue, thanks very much for your patience!

**Comment by Minion3665** [comment]
Hello! I've just fixed this now, so it should be available in the next Android release - we're expecting that to be around the start of October. I'll let you know when we have a snapshot with this commit in so you can test it out :)

**Comment by photoalex** [comment]
> Hello! I've just fixed this now, so it should be available in the next Android release - we're expecting that to be in early October. I'll let you know when we have a snapshot with this commit in so you can test it out :)

Awesome! Thank you very many!

**Comment by Minion3665** [comment]
Hello @photoalex! The latest snapshot, which you can get [from our website](https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/?C=M;O=D) here: (the exact correct link depends on your device, but it's probably [the arm64 build unless you know differently](https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/collabora-office-mobile-24.04-snapshot-arm64-v8a-2024-09-15.apk)), contains the option to copy sheets. Please feel free to test it out.

Thanks!
