### ISSUE TITLE
Hyperlink button tooltips are not being translated

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#9818]
### Describe the Bug

See the screenshot at the end. It seems we are correctly wrapping those `removeBtn.setAttribute('title', _('Remove link'));` but it doesn't reach weblate: [location: src/canvas/sections/URLPopUpSection.ts](https://hosted.weblate.org/projects/collabora-online/ui/ga/?q=%20location:src/canvas/sections/URLPopUpSection.ts#search)  which gives no results as opposed to what happens with [location: src/canvas/sections/CommentListSection.ts](https://hosted.weblate.org/translate/collabora-online/ui/ga/?q=+location%3Asrc%2Fcanvas%2Fsections%2FCommentListSection.ts&sort_by=-priority%2Cposition&checksum=)

I also didn't get any hit when grepping for `src/canvas/sections/URLPopUpSection.ts` within  `browser/po/templates/cool-ui.pot`  which seems odd.

Maybe we need perhaps to update pot files? I arrived to that conclusion when looking at git blame of `browser/po/templates/cool-ui.pot`, example commit: `Update l10n files for Weblate`

I think Andras was doing `make pot` inside of `browser/` using html2po (python3-translate-toolkit package)

### Steps to Reproduce
1. Open Collabora Online
2. append `&lang=de` to the url
3. Create an hyperlink (select text, ctrl + K, insert link, ok)
4. Click in the newly created hyperlink
5. Hover above the remove link icon and wait 
6. See tooltip in English instead of what is expect (DE)

### Expected Behavior
To see the tooltips in the user language

### Screenshots
![image](https://github.com/user-attachments/assets/820b1e14-e21d-4e5a-b143-a51a63121ee0)

### Desktop

(share)

COOLWSD version: 24.04.5.4snapshot (git hash: 8679835)

But also in staging perf

COOLWSD version: 24.04.6.2 (git hash: 868d8efb (E))

**Comment by pedropintosilva** [comment]
cc: @thebearon @gokaysatir

**Comment by pedropintosilva** [comment]
The file seems to be missing in the list of `pot:` https://github.com/CollaboraOnline/online/blob/1af37deb49b3ed059411008dd3eba1640838bd09/browser/Makefile.am#L802-L803

**Comment by pedropintosilva** [comment]
- [x] Add missing file to `online-browser/Makefile.am` https://github.com/CollaboraOnline/online/pull/9821 

But before that is merged maybe better to make sure we sync both of them


Weblate
1. [x] On weblate web interface: Manage -> Repository maintenance Press "Update" button to update Weblate repo from github/master 
2. [x] Cherry-pick commits from weblate/master to local master that follows github/master 
3. [x] After each cherry-pick, add the ChangeId and signoff: `git commit --amend --no-edit -s` 
4. [x] push to github.
6. [ ] Repeat step 1. You'll see that there are no pending commits on Weblate.
7. [ ] Create updated pot files (make pot in the browser directory) and push the additional commit to https://github.com/CollaboraOnline/online/pull/9821

**Comment by pedropintosilva** [comment]
Pressing again the "Update" button on weblate (step 1) after 1 to 4 steps were done returns:
> Could not rebase local branch onto remote branch Collabora Online/App Store Descriptions. 
> Page not found

I inspected the backup archive I did before and it seems in the weblate there is a `components/app-store-descriptions.json` 

```json
{
  "component": {
    "name": "App Store Descriptions",
    "slug": "app-store-descriptions",
    "vcs": "git",
    "repo": "https://github.com/CollaboraOnline/online.git",
    "push": "",
    "repoweb": "",
    "report_source_bugs": "",
    "branch": "distro/collabora/co-6-4",
    "push_branch": "",
    "filemask": "loleaflet/po/descriptions-*.po",
    "template": "",
    "edit_template": true,
    "intermediate": "",
    "new_base": "loleaflet/po/templates/descriptions.pot",
```

which seems to be https://hosted.weblate.org/projects/collabora-online/app-store-descriptions/ there is merge conflict `CONFLICT (content): Merge conflict in cypress_test/integration_tests/desktop/impress/annotation_spec.js`. 

<details>

warning: skipped previously applied commit 29586113b4
warning: skipped previously applied commit e77682db62
warning: skipped previously applied commit 34dd0afd2b
warning: skipped previously applied commit d71ecc9530
warning: skipped previously applied commit 85c43bb411
warning: skipped previously applied commit 4d7c3f3d6d
warning: skipped previously applied commit d226534e02
warning: skipped previously applied commit d6c0adbefa
warning: skipped previously applied commit 4434bb1693
warning: skipped previously applied commit 7872296c79
warning: skipped previously applied commit 5888c7a3a0
warning: skipped previously applied commit 1af12d2eaf
warning: skipped previously applied commit 2315cff0b6
hint: use --reapply-cherry-picks to include skipped commits
hint: Disable this message with "git config advice.skippedCherryPicks false"
Rebasing (1/69)
Rebasing (2/69)
Auto-merging cypress_test/integration_tests/common/helper.js
Auto-merging cypress_test/integration_tests/desktop/calc/annotation_spec.js
Auto-merging cypress_test/integration_tests/desktop/draw/pdf_page_up_down_spec.js
Auto-merging cypress_test/integration_tests/desktop/impress/annotation_spec.js
CONFLICT (content): Merge conflict in cypress_test/integration_tests/desktop/impress/annotation_spec.js
Auto-merging cypress_test/integration_tests/desktop/writer/annotation_spec.js
Auto-merging cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Auto-merging cypress_test/integration_tests/mobile/calc/nextcloud_spec.js
Auto-merging cypress_test/integration_tests/mobile/impress/insertion_wizard_spec.js
Auto-merging cypress_test/integration_tests/mobile/impress/nextcloud_spec.js
Auto-merging cypress_test/integration_tests/mobile/impress/table_operation_spec.js
Auto-merging cypress_test/integration_tests/mobile/writer/nextcloud_spec.js
Auto-merging cypress_test/integration_tests/mobile/writer/shape_properties_spec.js
error: could not apply d998f2c1c8... cypress: give each test a unique test document
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply d998f2c1c8... cypress: give each test a unique test document
 (1)

</details>

**Comment by timar** [comment]
I updated Weblate. Fortunately the old translations were automatically pulled in. 
Next time please do the repository maintenance in Collabora Online / UI. Then you won't get conflicts elsewhere.
