### ISSUE TITLE
Handle limited open Connections due to keepalive connections (cool#9621)

### ISSUE THREAD

**Issue by sgothel** [CollaboraOnline/online#9833]
### Is your feature request related to a problem?

Issue #9621 resolved by pull request #9777 keeps connections alive to enhance performance.
This may result in a shortage of available connection on the server and should be addressed

### Describe the solution you'd like

We should track inactivity of each socket and close the oldest-inactive sockets
either (a) in general and/or (b) when available connection count is below a threshold.

### Describe alternatives you've considered

Alternatively, we may need to close high-frequency short lived connections.

**Comment by mmeeks** [comment]
Yep - clearly rather related, and important to get this nailed before widely deploying the connection re-using code =)

While we're there - we should shut prolly also detect and shut connections that are not making progress - 'slow' connections and so on that are drip-feeding us data.

Thanks!
