### ISSUE TITLE
Collabora office on iOS is unable to open spreadsheet documents stored in icedrive cloud storage.

### ISSUE THREAD

**Issue by WingedRayeth** [CollaboraOnline/online#9838]
Using version 24.04.4 when I have collabora office set to save to IceDrive I am able to open documents in the Collabora app fine, but spreadsheet files are grayed out and have no option to open or save. I am able to open the files from IceDrive but after editing they won't save, and cannot be re-opened. Files stored locally don't seem to have any problems.

**Comment by WingedRayeth** [comment]
Further looking into this, I can move the files from IceDrive to my iPad's storage and back, but .ods files can only be opened when they are in the iPad storage, not in the directory from IceDrive

**Comment by timur-g** [comment]
This does not look like something that Collabora should fix.

**Comment by WingedRayeth** [comment]
I still believe it is a Collabora issue not an Icedrive issue. Other files, such as text files, open fine. It's only spreadsheets that are broken, and only in Collabora.
