### ISSUE TITLE
Show kebab menu in comment wizard in root comment 

### ISSUE THREAD

**Issue by lpranam** [CollaboraOnline/online#990]
currently in writer root comments do now show kebab menu instead it shows ">" in all the scenario even if it is a single comment in the thread.

Instead what it should do is, if root comment is the only comment in the thread then it should show kebab menu instead of ">" and tapping on it should not open the new view inside comment wizard.

**Comment by lpranam** [comment]
@Rash419 something you already wanted to work on.

**Comment by Rash419** [comment]
Yeah :D
