### ISSUE TITLE
Add a Slider for Navigating Spreadsheet Tabs

### ISSUE THREAD

**Issue by Darshan-upadhyay1110** [CollaboraOnline/online#9937]
Description:

In spreadsheets with numerous tabs, navigating between them using the current arrow buttons is slow and cumbersome. The arrows either jump to the extreme left or right, or move incrementally by very small amounts. This makes it difficult to efficiently switch between tabs, especially in larger files.

Request:

I propose adding a slider to the tab navigation area, allowing users to quickly and easily scroll through their tabs. A slider would provide a much faster and more intuitive way to navigate, enhancing the overall user experience.

**Comment by pedropintosilva** [comment]
As of the current state horizontally scrolling works (alt + scroll)

**Comment by Darshan-upadhyay1110** [comment]
> As of the current state horizontally scrolling works (alt + scroll)

Thanks Pedro, i think we should add a new entry in keyboard SC help section.

Note: It's `SHIFT` + scroll ( alt is for moving around sheets 😉 )
