### ISSUE TITLE
Current coolwsd deb package breaks AppArmor on Debian and Ubuntu 22.04 or older

### ISSUE THREAD

**Issue by michaellass** [CollaboraOnline/online#9945]
### Describe the Bug
The latest coolwsd deb package contains an AppArmor profile which was added in #9696. This breaks AppArmor on Debian as abi/4.0 is not supported.

### Steps to Reproduce
1. Install coolwsd 24.04.7.1-1 from https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-deb on Debian
2. Observe warning during installation or try to (re-)start apparmor.service

### Expected Behavior
No errors. apparmor.service should be able to start.

### Actual Behavior
apparmor.service fails to start with the following errors:
```
AppArmor parser error for /etc/apparmor.d in profile /etc/apparmor.d/usr.bin.coolwsd at line 4: Could not open 'abi/4.0': No such file or directory
AppArmor parser error for /etc/apparmor.d/usr.bin.coolwsd in profile /etc/apparmor.d/usr.bin.coolwsd at line 4: Could not open 'abi/4.0': No such file or directory
```

**Comment by solarisfire** [comment]
This is affecting me on Ubuntu 22.04.4 LTS

<pre>
AppArmor parser error for /etc/apparmor.d/usr.bin.coolwsd in profile /etc/apparmor.d/usr.bin.coolwsd at line 4: Could not open 'abi/4.0': No such file or directory
</pre>

**Comment by rportnoy2004** [comment]
confirming same bug here on 22.04 LTS after upgrade to 24.04.7.1-1

**Comment by RVB777** [comment]
confirms same bug on Debian 12 (6.1.0-25-amd64) since coolwsd update 24.04.7.1-1

**Comment by sjpp** [comment]
Downgrading abi version from 4.0 to 3.0 (which is still present in Debian 12) is not enough to fix this issue. Starting Apparmor after that results in the following error:
```
Erreur de l'analyseur AppArmor pour /etc/apparmor.d in profile /etc/apparmor.d/usr.bin.coolwsd ? la ligne 9 : syntax error, unexpected TOK_END_OF_RULE, expecting TOK_MODE
```

**Comment by timar** [comment]
Actually the apparmor profile is needed only on Ubuntu 24.04 (cf. https://caolanm.blogspot.com/2024/08/linux-namespaces-and-collabora-online.html). So probably the installation of it should be conditional.

**Comment by solarisfire** [comment]
So we can just remove the profile and restart AppArmor?

**Comment by timar** [comment]
The patch above fixes the issue.
