### ISSUE TITLE
Latest Docker image is only working in privileged mode

### ISSUE THREAD

**Issue by der-domi** [CollaboraOnline/online#9948]
### Describe the Bug
With the latest Docker image (tag: `24.04.7.1.1`) the container doesn't start up correctly without privileged rights. With previous versions (tag `24.04.6.2.1` and before) it was possible.

### Steps to Reproduce
Just follow the steps descriped in [How to grab the CODE image from Docker image](https://sdk.collaboraonline.com/docs/installation/CODE_Docker_image.html#how-to-grab-the-code-image-from-docker-image).
1. `docker pull collabora/code`
2. `docker run -t -d -p 127.0.0.1:9980:9980 --name collabora collabora/code`

### Expected Behavior
Latest Docker image shall still work without using privileged mode which increase the security aspect on a server.

### Actual Behavior
Analyze `docker logs collabora`. You will find following messages
```
/usr/bin/coolmount: unmount failed to detach [/opt/cool/child-roots]: Operation not permitted.
/usr/bin/coolmount: forced unmount of [/opt/cool/child-roots] failed: Operation not permitted.
/usr/bin/coolmount: mount failed to bind [/opt/cool/systemplate] to [/opt/cool/child-roots/1-a5e667ac/cool_test_mount]: Operation not permitted.
[...]
frk-00028-00028 2024-08-31 11:16:38.390825 +0000 [ coolforkit-caps ] ERR  Capability cap_sys_chroot is not set for the coolforkit program.| kit/ForKit.cpp:230
frk-00028-00028 2024-08-31 11:16:38.390828 +0000 [ coolforkit-caps ] ERR  Capability cap_fowner is not set for the coolforkit program.| kit/ForKit.cpp:230
frk-00028-00028 2024-08-31 11:16:38.390832 +0000 [ coolforkit-caps ] ERR  Capability cap_chown is not set for the coolforkit program.| kit/ForKit.cpp:230
Capabilities are not set for the coolforkit program.
frk-00028-00028 2024-08-31 11:16:38.390837 +0000 [ coolforkit-caps ] FTL  Capabilities are not set for the coolforkit program.| kit/ForKit.cpp:780
Please make sure that the current partition was *not* mounted with the 'nosuid' option.
frk-00028-00028 2024-08-31 11:16:38.390842 +0000 [ coolforkit-caps ] FTL  Please make sure that the current partition was *not* mounted with the 'nosuid' option.| kit/ForKit.cpp:781
If you are on SLES11, please set 'file_caps=1' as kernel boot option.
```

Those messages doesn't appear if privileged rights are assigned to the container or the previous tag will be used.

This ends up in a loop of following messages and container doesn't start up correctly
```
wsd-00001-00001 2024-08-31 11:16:58.389102 +0000 [ coolwsd ] INF  Waiting for a new child for a max of 20000ms| wsd/COOLWSD.cpp:4421
wsd-00001-00001 2024-08-31 11:17:18.389262 +0000 [ coolwsd ] INF  Waiting for a new child for a max of 20000ms| wsd/COOLWSD.cpp:4421
wsd-00001-00027 2024-08-31 11:16:38.389175 +0000 [ prisoner_poll ] TRC  #15: setupPollFds getPollEvents: 0x1| net/Socket.hpp:880
wsd-00001-00027 2024-08-31 11:16:38.389177 +0000 [ prisoner_poll ] TRC  ppoll start, timeoutMicroS: 64000000 size 1| net/Socket.cpp:430
wsd-00001-00027 2024-08-31 11:17:42.450286 +0000 [ prisoner_poll ] TRC  Poll completed with 0 live polls max (64000000us)(timedout)| net/Socket.cpp:448
wsd-00001-00001 2024-08-31 11:17:38.389392 +0000 [ coolwsd ] INF  Waiting for a new child for a max of 20000ms| wsd/COOLWSD.cpp:4421
wsd-00001-00001 2024-08-31 11:17:58.389544 +0000 [ coolwsd ] INF  Waiting for a new child for a max of 20000ms| wsd/COOLWSD.cpp:4421
```

**Comment by LMRW** [comment]
May be what I'm seeing too.

Undocumented changes are becoming a hassle if this is an intended change.

I recently suffered outage from an undocumented change to need an extra environment variable to allow self signed SSL.

Please let's work as a community to find a way to alert people to these changes well in advance and offer better logs when errors occur?

**Comment by LMRW** [comment]
Do we know what --cap-add flags may fix the issue for a less sledgehammer solution?

**Comment by p-gentili** [comment]
> I recently suffered outage from an undocumented change to need an extra environment variable to allow self signed SSL.

Can you expand on this? Any reference? I'm also having some problems with the latest images

**Comment by LMRW** [comment]
> > I recently suffered outage from an undocumented change to need an extra environment variable to allow self signed SSL.
> 
> 
> 
> @LMRW , can you expand on this? Any reference? I'm also having some problems with the latest images

https://github.com/CollaboraOnline/online/issues/9519

**Comment by nursoda** [comment]
> Do we know what --cap-add flags may fix the issue for a less sledgehammer solution?

I just tested that, and as it could be expected, `--cap-add=SYS_ADMIN` is sufficient.

**Comment by warioishere** [comment]
same here

**Comment by whahn1983** [comment]
I tried with both privileged and sys_admin and mine fails with the same above error regardless.

**Comment by tmaex** [comment]
> how do I downgrade the code version? putting `collabora/code:"CODE 21.11.4.2"` doesnt work

Try `collabora/code:24.04.6.2.1` (which is enough downgrade for me).

**Comment by mklemme1** [comment]
Hallo
> how do I downgrade the code version? putting `collabora/code:"CODE 21.11.4.2"` doesnt work

In a `docker-compose.yml`, use
```
services:
  collabora:
    image: collabora/code:24.04.6.2.1
```
That is the release before Saturday. It works for me.
Out of security considerations, I suggest you do not set it like this forever, but just for the next weeks, until the root cause is fixed.

**Comment by warioishere** [comment]
> Hallo
> 
> > how do I downgrade the code version? putting `collabora/code:"CODE 21.11.4.2"` doesnt work
> 
> In a `docker-compose.yml`, use
> 
> ```
> services:
>   collabora:
>     image: collabora/code:24.04.6.2.1
> ```
> 
> That is the release before Saturday. It works for me. Out of security considerations, I suggest you do not set it like this forever, but just for the next weeks, until the root cause is fixed.

thanks, found the docker hub version now and that was the version I was trying to use too, will let you know if it spins up again

**Comment by warioishere** [comment]
works again n VM running ubuntu 22.04.3 and the version 24.04.6.2.1

**Comment by ErikDW1** [comment]
Same error on straight CentOS installation......
Tried to do a downgrade with "yum undo" but it failed. Do you have any tip on how to do it?
Thanks.

**Comment by LMRW** [comment]
Has collabora confirmed issue will be resolved?

**Comment by pedropintosilva** [comment]
Thanks for reporting

Quick update: @timar and @caolanm are already investigating the issue.

**Comment by ferdiga** [comment]
Hi
just a question - 
if a docker image [24.04.7.1.1] does not work - shouldn't it be deleted from docker hub ASAP ?

**Comment by caolanm** [comment]
I think coolmount and coolforkit-caps are missing their capabilities. And this isn't specific to the docker images, just a side effect that when docker (as in docker-io and not docker-podman) blocks namespaces and the fallback is used, then that fallback is missing the capabilities in the original .debs, so the problem lies there.

**Comment by timar** [comment]
collabora/code:24.04.7.1.2 fixes the issue.

**Comment by mklemme1** [comment]
I can confirm that the new release works for me.

**Comment by der-domi** [comment]
Thanks to all participants for fixing that issue! 👍
